### ISSUE TITLE
"Multi" pseudo-machinery for multiple simultaneous machinery backends

### ISSUE THREAD

**Issue by mcm** [cuckoosandbox/cuckoo#1001]
We've got a setup where we have analysis machines in Xenserver, but also a physical machine available for analysis as well. There didn't appear to be any mechanism for configuring this currently, so I started work on a pseudo-machinery that just chains to other configured machinery backends. I wanted to gauge interest in this before I fully developed it out and submitted a PR with docs and tests and all that. A working (for me) example can be found at https://gist.github.com/mcm/b39cae18b99733bbc26809b368829a61

If this is something there's interest in including, I'd be happy to polish it up and submit. I look forward to feedback. Thanks.

**Comment by jbremer** [comment]
I'm up for implementing such functionality, but not through this way probably, as it is rather hacky.
If we'd improve the Scheduler to accept multiple machinery backends, properly identify which analyses should go to which backend, correctly setup configuration for the various backends (i.e., while a VM analysis will usually take 1-2 minutes, you'll probably want a bare metal analysis to take, e.g., 10-30 minutes), and probably some more improvements.. then I think it's worth going for :-)

**Comment by mcm** [comment]
@jbremer I'll see what I can whip up

**Comment by marklech** [comment]
Hi, 
I'm interested in this feature as well. I have both a physical machine 
and an ESX server, and as it seems there's no way to use both machineries 
concurrently. If such an option will be available I'll find it very useful . 
Regards, 
Mark.

**Comment by marklech** [comment]
Is it something you believe will be done in the near future? If not, I may also look at the option of extending this feature.

**Comment by mcm** [comment]
Finally looking at the code for scheduler, I can see going about this two different ways. I could update all of scheduler.py so that the `machinery` global is a list instead of a single instance of machinery, and all of the related changes that would go along with that. Alternatively, I could implement a "machinery manager" of sorts that would abstract that away from anything that refers to the `machinery` global. This would have the benefit of not impacting any other code (part of Cuckoo or third party) that might, for some reason, refer to the the `machinery` global.

As an outsider, the second seems like the better way to go, but it's not my call to make. Anyone have any opinions?

**Comment by jbremer** [comment]
I'm going to close this issue as I don't think this is a good idea for now. The easiest approach would be using `tags`, running multiple Cuckoo instances, and sharing the same SQL database.
Closing issue for these reasons. Keep in mind that, as I mentioned above as well, running multiple machineries also requires completely different configuration - that alone should be enough reason to not attempt to do this :-)

**Comment by garanews** [comment]
Hello, @jbremer : ok to using multiple instances that sharing the same SQL, but what about web interface? In this way there will be 2 separated gui, one for each machinery. Any thought?

**Comment by doomedraven** [comment]
why just not to point mongo to one server? or shard mongo? i have it with shard mongo in dist cluster, and have only one master gui :)

**Comment by garanews** [comment]
HEllo! So you suggest to create a cluster configuring a Distributed Cuckoo where for example one instance has a physical  machinery and another instance has virtualbox ?

**Comment by doomedraven** [comment]
if you want to have only one gui yes, shard mongo works fine for that

**Comment by garanews** [comment]
Great, think will try in this way.

**Comment by garanews** [comment]
Hello @doomedraven I would setup one instance for run distributed server and a couple of instances for run cuckoo with 2 different machinery.
Regarding shared db (using mysql&mongo), should I configure both cuckoo instances to point the same mysql and same mongo? and keep a separated db (mysql) for distributed script?

**Comment by doomedraven** [comment]
I use my own dist.py so all servers has their dbs but using the same mongo shard, so you need to check/modify the distributed part code, anyway im afk till monday

**Comment by garanews** [comment]
I tried to used same mongo, so I can see same analysis from both gui interfaces, but I can't use one interface to pilot both nodes..
I was wondering the distributed gui had this role (pilot both nodes) but instead it is only a performance monitor...

**Comment by doomedraven** [comment]
Shard mongo, not clasic mongo, and you need to change dist code to do that or wait till next week and i will can share mine

**Comment by garanews** [comment]
Okay, I will wait until monday! :)
Thanks in advance

**Comment by garanews** [comment]
I am on gitter

**Comment by Tigzy** [comment]
Hey, just starting to be interested about such thing. I'm planning to setup vbox VMware and baremetal, is this in dev?
