### ISSUE TITLE
info package does not show package on autodetect (required for sigs)

### ISSUE THREAD

**Issue by kevross33** [cuckoosandbox/cuckoo#1006]
Hi,

In converting cuckoo-modified signatures there are cases where the intial package is used either for whitelisting or detection of interesting things. Anyway this is covered as self.results["info"]["package"]. Now the autoanalysis in cuckoo does not fill in this package name. Would it please be possible to fill this information in everytime so it can be used?

Cuckoo-Modified:
{
    "info": {
        "shrike_msg": null, 
        "started": "2016-07-08 09:25:44", 
        "ended": "2016-07-08 09:28:58", 
        "shrike_refer": null, 
        "duration": 194, 
        "id": 15, 
        "category": "file", 
        "shrike_url": null, 
        "package": "exe", 
        "custom": "", 
        "machine": {

Cuckoo 2.0:
{
    "info": {
        "category": "file", 
        "score": 10.2, 
        "package": "", 
        "started": 1467988986.262219, 
        "route": "none",

**Comment by jbremer** [comment]
As mentioned earlier, we're working hard on this at the moment - please stay tuned :-)

**Comment by jbremer** [comment]
This has been resolved for the upcoming release. Closing issue.
