### ISSUE TITLE
USB AUTORUN MALWARE ANALYSIS

### ISSUE THREAD

**Issue by cssanchit** [cuckoosandbox/cuckoo#1010]
PLEASE HELP 

Hi

How can i perform malware analysis on USB based malware. I want to open infected USB in guest machine and perform analysis on spawned processes. 

THANKS

**Comment by doomedraven** [comment]
@cssanchit unselect human interaction and open the gui of that vm and you will can do it

**Comment by jbremer** [comment]
What @doomedraven said. If you're interested in developing a patch for Cuckoo so that it automatically inserts a (fake) USB device at runtime, please go ahead :-)

**Comment by jbremer** [comment]
Any update on this matter?

**Comment by jbremer** [comment]
Going to close this issue. Please reopen if you think it's still relevant.
