### ISSUE TITLE
Configure INETSIM with CUCKOO

### ISSUE THREAD

**Issue by cssanchit** [cuckoosandbox/cuckoo#1011]
PLEASE HELP
Hi
I want to configure INETSIM with my cuckko machine.Based upon information on internet, I Followed these steps:

1. wget http://www.inetsim.org/debian/binary/inetsim_1.2.5-1_all.deb
2. sudo apt-get install gdebi-core
3. sudo gdebi inetsim_1.2.5-1_all.deb
4. modified **/etc/inetsim/inetsim.conf**  
and set service_bind_address and dns_default_ip to 192.168.56.1 
5. modified /etc/default/inetsim
and set ENABLED to 1
and enabled 

I using host only networking with 192.168.56.1 (host machine)
I am running internet on other adapter eth0 and i dont want it to connect to INETSIM. 
Problem is setting dns port. 

If anyone else had set up INETSIM with cuckoo then please guide me.

Thanks

**Comment by doomedraven** [comment]
you will need apply this patch for router, https://github.com/cuckoosandbox/cuckoo/pull/943
or if you don't care what that vm will go all the time to inetsim(until you remove iptable) you can set single iptable command, and done

**Comment by jbremer** [comment]
InetSim routing has been implemented as part of #863, also thanks to @doomedraven's PR.
Please read its documentation here, https://cuckoo.sh/docs/installation/host/routing.html#inetsim-routing. Going to close as resolved.
