### ISSUE TITLE
lost of dll many samples can not run

### ISSUE THREAD

**Issue by abcd1f2** [cuckoosandbox/cuckoo#1015]
lost of dll many samples can not run in virtual machine,Is there any effective way?

**Comment by jbremer** [comment]
Can you be a little bit more specific?

**Comment by abcd1f2** [comment]
for example,a file can't execute success because it depend on another dll or others,how to do

**Comment by jbremer** [comment]
That sounds like an issue with your VM, rather than Cuckoo ;-) Install the `Visual C++ Redistributable Packages`, e.g., https://www.microsoft.com/en-us/download/details.aspx?id=40784.

**Comment by abcd1f2** [comment]
thanks
