### ISSUE TITLE
Ports Used by Cuckoo

### ISSUE THREAD

**Issue by Sanghyun-Hong** [cuckoosandbox/cuckoo#1016]
Hi,

I would like to know which ports are used by the Cuckoo sandbox analysis. So far, I have noticed the ports enlisted below used as defaults either at the host or at the guest:

**Host**: 80, 2042, 8090
**Guest**: 8000

I wonder if there can be another port used by the Cuckoo.

Best,
Sanghyun.

**Comment by skftn** [comment]
Yep, this is correct.

**Comment by Sanghyun-Hong** [comment]
Thanks, @skftn.
