### ISSUE TITLE
Error injecting to lasass.exe process

### ISSUE THREAD

**Issue by marklech** [cuckoosandbox/cuckoo#1019]
After initiating an emulation on a Windows 7 physical machine 
the following error pops : "Error getting access to process: 5!". 
The account is in the adminstrator group, UAC is turned off, and 
agent.py is running as an administrator. After checking a few options 
it seems that the problem stems from an injection to lsass.exe 
that occurs in analyzer/windows/modules/auxiliary/dumptls.py . 
I commented out the line that carries out this injection and everything
seems to work now. I should note that this Windows 7 machine has some late 
updates installed, which may be part of the problem.

**Comment by jbremer** [comment]
And you are 100% sure that the Agent is running as Administrator? Regardless of that, we should probably still loosen up the `lsass.exe` injection thing.

**Comment by marklech** [comment]
Yes, I'm sure. 
This message is invoked on OpenProcess and the error code is ERROR_ACCESS_DENIED. 
I also tried to run "is32bit.exe -n lsass.exe" manually and the same error occured (which didn't show up with similar attempts on other processes).  
I believe this is something that should happen with protected processes, which lsass is, starting from Windows 8.1 and on. I suspect that one of the latest updates for Windows 7 limits the access rights to it in a similar manner.

**Comment by jbremer** [comment]
Oke, thanks, we'll investigate it :-)

**Comment by jbremer** [comment]
Since our `2.0.4` release this has been improved - not being able to inject into `lsass.exe` should now no longer result in hard errors, but merely some logging entries. For now I think that's good enough, closing issue as resolved. Thanks!
