### ISSUE TITLE
can not generate behavior files under ubuntu within virtualbox （ubuntu 14.0.4 x64）

### ISSUE THREAD

**Issue by yexihu** [cuckoosandbox/cuckoo#1020]
hello,I need analyze .elf file, but it can not generate behavior files under ubuntu within virtualbox （host:ubuntu 14.0.4 x64,  guest:ubuntu 14.0.4 x64,win7 x64, Cuckoo Sandbox 2.0-rc1）.
# warning:Analysis results folder does not contain any behavior log files.

what is the reason? thank you.

note:  it can generate behavior files under win7 x64 within virtualbox.

cuckoo.conf
[cuckoo]
version_check = on
delete_original = off
delete_bin_copy = off
machinery = virtualbox

virtualbox.conf
[virtualbox]
mode = headless
path = /usr/bin/VBoxManage
interface = vboxnet0
machines = win7-64-1,win7-64-2,ubuntu-1

[win7-64-1]
label = win7-64-1
platform = windows
ip = 192.168.56.101

[win7-64-2]
label=win7-64-2
platform = windows
ip = 192.168.56.102

[ubuntu-1]
label=ubuntu-1
platform = linux
ip = 192.168.56.103
# tags = service, ubuntu-1
# options = nictrace noagent

**Comment by doomedraven** [comment]
@yexihu can you provide hashes ?

**Comment by yexihu** [comment]
@doomedraven  .elf file or cuckoo?

**Comment by doomedraven** [comment]
.elf which not generates behaviour

**Comment by yexihu** [comment]
Tank you.
I think it is not configured to host and guest  for .elf file.
Does host:ubuntu need to be configured for Linux guest? 
Online did not find the Linux guest configuration.

**Comment by jbremer** [comment]
Well, you have to compile the STAP script thing, which is located at `data/strace.stp`.
Unfortunately there's not a lot of documentation on this part, so you'll have to try out some things yourself. If you'd like to write some documentation on it, let us know with a PR ;-)

**Comment by jbremer** [comment]
Closing this issue for now. Please let us know if you have a PR on documentation or any other questions ;-)
