### ISSUE TITLE
resultserver unable to map ip to context (again)

### ISSUE THREAD

**Issue by lab313ru** [cuckoosandbox/cuckoo#1021]
In agent.py it tells that
```
[Python] Socket error: 10053 software caused connection abort
```

And I have
```2016-07-29 12:28:11,232 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.```
VirtualBox is closed. State is Powered off. Snapshot is created.

**Comment by doomedraven** [comment]
@lab313ru check your virtualbox.conf for that ip

**Comment by lab313ru** [comment]
It exists. And first time launched it works. But after it, it generates such error.

-----Зыходнае паведамленне-----
Ад: "doomedraven" <notifications@github.com>
Адпраўлена: ‎29.‎07.‎16 12:46
Каму: "cuckoosandbox/cuckoo" <cuckoo@noreply.github.com>
Копія:"Lab 313" <newinferno@gmail.com>; "Mention" <mention@noreply.github.com>
Тэма: Re: [cuckoosandbox/cuckoo] resultserver unable to map ip to context(again) (#1021)

@lab313ru check your virtualbox.conf for that ip

**Comment by doomedraven** [comment]
can you show the config? and you use static ips inside of vm or nat?

**Comment by lab313ru** [comment]
I'm using vboxnet0, and static ip address 192.168.56.101.
Config has mostly default parameters.

-----Зыходнае паведамленне-----
Ад: "doomedraven" <notifications@github.com>
Адпраўлена: ‎29.‎07.‎16 12:51
Каму: "cuckoosandbox/cuckoo" <cuckoo@noreply.github.com>
Копія:"Lab 313" <newinferno@gmail.com>; "Mention" <mention@noreply.github.com>
Тэма: Re: [cuckoosandbox/cuckoo] resultserver unable to map ip to context(again) (#1021)

can you show the config? and you use static ips inside of vm or nat?

**Comment by doomedraven** [comment]
i had that error, when name of vm and ip was incorrect, so it starts vm but as ip is wrong, is why im asking for conf...

**Comment by lab313ru** [comment]
Ok, I'll attach it soon.

-----Зыходнае паведамленне-----
Ад: "doomedraven" <notifications@github.com>
Адпраўлена: ‎29.‎07.‎16 12:58
Каму: "cuckoosandbox/cuckoo" <cuckoo@noreply.github.com>
Копія:"Lab 313" <newinferno@gmail.com>; "Mention" <mention@noreply.github.com>
Тэма: Re: [cuckoosandbox/cuckoo] resultserver unable to map ip to context(again) (#1021)

i had that error, when name of vm and ip was incorrect, so it starts vm but as ip is wrong, is why im asking for conf...

**Comment by lab313ru** [comment]
[conf.tar.gz](https://github.com/cuckoosandbox/cuckoo/files/390378/conf.tar.gz)
This is my conf dir.

**Comment by doomedraven** [comment]
here is your fail

in `cuckoo.conf`
# Specify a port number to bind the result server on.
port = 20440 

and in `virtualbox.conf`
# resultserver_port = 2042

**Comment by lab313ru** [comment]
I'll check it, and report soon, thank you.

**Comment by lab313ru** [comment]
As it was before: after first analysis finished, it closes vm, etc. But, after starting second analysis, it generates error:
```[lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.56.101.```

**Comment by lab313ru** [comment]
And, sometimes it generates this:
```[lib.cuckoo.core.resultserver] WARNING: Cannot bind ResultServer on port 2042, trying another port.```

**Comment by doomedraven** [comment]
did you change ports? because in cuckoo and vbox conf they are diffrent

**Comment by lab313ru** [comment]
Could you send me fixed configuration for me? With fixed config. Maybe with some other cool options enabled/disabled.

**Comment by doomedraven** [comment]
just replace in `cuckoo.conf` -> `port = 20440` to `port = 2042`

restart cuckoo and done

**Comment by lab313ru** [comment]
Problem still happens:
```2016-07-29 15:59:26,276 [lib.cuckoo.core.resultserver] WARNING: Cannot bind ResultServer on port 2042, trying another port.```

**Comment by doomedraven** [comment]
`netstat -putana | grep 2042` if is cuckoo `sudo fuser -n tcp -k 2042` and start it

**Comment by lab313ru** [comment]
**netstat -putana | grep 2042**:
```tcp        0      0 192.168.56.1:2042       0.0.0.0:*               LISTEN      4063/python```
**sudo fuser -n tcp -k 2042**
```2042/tcp:             4063```

**Comment by doomedraven** [comment]
now start cuckoo and execute analysis

**Comment by doomedraven** [comment]
@lab313ru works?

**Comment by lab313ru** [comment]
I think, it is. Thank you)

-----Зыходнае паведамленне-----
Ад: "doomedraven" <notifications@github.com>
Адпраўлена: ‎29.‎07.‎16 19:03
Каму: "cuckoosandbox/cuckoo" <cuckoo@noreply.github.com>
Копія:"Lab 313" <newinferno@gmail.com>; "Mention" <mention@noreply.github.com>
Тэма: Re: [cuckoosandbox/cuckoo] resultserver unable to map ip to context(again) (#1021)

@lab313ru works?

**Comment by doomedraven** [comment]
You are welcome, close issue, you can reopen if needed

**Comment by doomedraven** [comment]
@jbremer i think you can close this one

**Comment by jbremer** [comment]
Closing as resolved (apparently).
