### ISSUE TITLE
analysis not completed yet (status=1)

### ISSUE THREAD

**Issue by samreenk** [cuckoosandbox/cuckoo#1022]
I am currently setting up Cuckoo on Mac OSX El Capitan using Virtual Box (v.5). Cuckoo is able to start up and the web UI seems to be functioning properly. However, for some reason once cuckoo starts up and attempts to actually run the analysis on the malware specimen, it gets stuck until timeout saying analysis not completed yet (status = 1). No analysis is actually completed... 

Has anyone dealt with a similar issue/know how to fix it? Any help would be greatly appreciated!

**Comment by jbremer** [comment]
I believe you've figured it out already, closing this issue.
