### ISSUE TITLE
a lot of name as tmpXXX tcpdump file in /tmp cannot delete

### ISSUE THREAD

**Issue by liuchuang** [cuckoosandbox/cuckoo#1025]
after set "sort_pcap=on"  in cuckoo.conf,it will create a lot of tmpXXX dump file in dir /tmp,until 100% full.
and I found that, in file modules/processing/network.py,function batch_sort,will throw expcetion before os.remove(chunk.name) line.
DEBUG:modules.processing.network:name:Exception:'Reader' object has no attribute 'close'

**Comment by jbremer** [comment]
Sounds like a legitimate issue, will check it out later - thanks for reporting.

**Comment by jbremer** [comment]
Please find the commit above - it resolves this issue (also thanks to @chigley). Closing this issue as resolved. These changes will be featured in the next alpha or stable release. Thanks again for the feedback!
