### ISSUE TITLE
error getting access to process on Windows 7 guest - Cuckoo on Ubuntu 16.04

### ISSUE THREAD

**Issue by reyesjos** [cuckoosandbox/cuckoo#1028]
Cuckoo and Guest run on ESXi 6.0.
Using vsphere.conf
Host (Cuckoo): Ubuntu 16.04.1 LTS (Linux 4.4.0-31-generic)
VM Guest: Windows 7 64 bit

Steps:
1) Run cuckoo.py
2) Run submit.py <Lab03-01.exe> (attached as zip)
[Lab03-01.zip](https://github.com/cuckoosandbox/cuckoo/files/404704/Lab03-01.zip)

Results:
analysis not completed yet (status=2) is running until timeout to give an error.

I checked VM-Guest and find out that there is a popup window "is32bit error" with the message: [-] Error getting access to process: 5!  See attached png file (screenshot )
![cuckoo_vm_guest_bug](https://cloud.githubusercontent.com/assets/16214712/17452082/db74d79c-5b20-11e6-849e-08d131f800ba.PNG)

Workaround: When I click ok on that window, the analysis completed.

**Comment by doomedraven** [comment]
@reyesjos try with latest dev, i don't have this error

**Comment by dasfreak** [comment]
I encounter the same error.

Host: Ubuntu 14.04 (Cuckoo is latest dev version)
Guest: Windows 7 x86
VirtualBox: 4.3.36

I created the zip file using `zip test.zip file`, where the file was just a simple bash script (.sh).

`2016-08-08 14:56:03,873 [lib.cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.3 (id=antfarm, ip=192.168.56.10)
2016-08-08 14:56:08,202 [lib.cuckoo.core.guest] INFO: antfarm: analysis caught an exception
Traceback (most recent call last):
  File "C:\tmpskcirn\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\tmpskcirn\analyzer.py", line 631, in run
    "exception: %s" % (package_name, e)
CuckooError: The package "modules.packages.zip" start function encountered an unhandled exception: Error returned by is32bit: Command '['bin\\is32bit.exe', '-f', u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\CREATE~1.SH']' returned non-zero exit status 1
`

**Comment by doomedraven** [comment]
both read this plz https://github.com/cuckoosandbox/cuckoo/issues/996

**Comment by dasfreak** [comment]
I just zipped a 32bit exe file and submitted it to cuckoo. This works.
The exe was extracted and executed.

is32bit.exe seems to fail if it's not an exe to check?

**Comment by reyesjos** [comment]
I got it to work by giving admin rights to user in Win7 VM and disable UAC
