### ISSUE TITLE
The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted

### ISSUE THREAD

**Issue by reyesjos** [cuckoosandbox/cuckoo#1032]
Cuckoo version 2.0-dev on ESXi 6.0
Guest: Windos 7 SP1

file submitted: Lab03-01.exe (attached as zip, please change extension to exe
[Lab03-01.zip](https://github.com/cuckoosandbox/cuckoo/files/410409/Lab03-01.zip)
)

Please find attached the log file (
[080916_cuckoo-log.pdf](https://github.com/cuckoosandbox/cuckoo/files/410399/080916_cuckoo-log.pdf)

![080916-failed_to_execute_process_1](https://cloud.githubusercontent.com/assets/16214712/17543163/753ea9ce-5e83-11e6-92d8-49bdf3553ed5.PNG)

Notes:
- I noticed that in the VM (Win 7) an "inject error" popup window shows with the error: "No injection method has been provided". It closes right away because of modules.auxiliary.human click.

**Comment by reyesjos** [comment]
I tried running the file Lab03-01.exe by itself in the VM and it doesn't work. However, I tried another file: Lab07-01.exe (attached) and it does run in the VM but I get the same error if submitting from Cuckoo.

**Comment by SparkyNZL** [comment]
I had this same issue when i run the community.py -wfa this for some reason
broke my cuckoo (hmm that sounds rude) have you pulled the latest updates ?

**Comment by reyesjos** [comment]
when i run cuckoo I get:
Checking for updates....
You are running a development version! Current stable is 2.0-rc1

**Comment by reyesjos** [comment]
All right, got it to work. I cloned the latest from git, installed again and it works.

**Comment by SparkyNZL** [comment]
yup, if you had done a pull of the latest update this would have fixed it
also, im not sure  what happened to it, but something in the community
downloads broke mine also.

**Comment by SparkyNZL** [comment]
you would have ffound that if you had submitted anything like a pdf or xls
file it would have given you the same are modules.packages.xls or
modules.packages.doc, but i gather that it was because the community
downloads didnt match up witht he build of  the cuckoo i was useing, i
think i fyou had done a git pull and installed the updates it would have
worked again.
