### ISSUE TITLE
Cuckoo doesn't show any API call

### ISSUE THREAD

**Issue by shirinmgh** [cuckoosandbox/cuckoo#1033]
Hi, I have followed all the installation steps provided on the website and cuckoo installed completely. I scans many .exe files correctly with this. Now I write a sample in C with visual studio (that creates a file, etc), but cuckoo didn't show any API. 
I thought that might be necessary to install Visual Studio in virtualbox then again, I took snapshot and edited virtualbox.conf, but when I submited my program, windows in virtual box aborted and cuckoo failed. what is wrong? how I can solve it?

**Comment by Higgsz** [comment]
Did you compiled your C code via release mode? instead of Debug mode.

As I remember you need specific .dll files such as msvcrt.dll an so on, don't remember exactly what are names of these files. But these files is neccessary as you use C functions and C functions is implemented in .dll files.

**Comment by shirinmgh** [comment]
no, I compiled via Debug mode, what is the difference? 
Do not installed this dlls along with the Visual Studio?

**Comment by jbremer** [comment]
You will need to install the `visual studio redistributable files` to run your executable.

**Comment by jbremer** [comment]
Closing as resolved.
