### ISSUE TITLE
Problem with .vbs file analysis

### ISSUE THREAD

**Issue by Bolverk1** [cuckoosandbox/cuckoo#1037]
Hi,

I'm trying to analyze short VBScript:
```
Set IE = CreateObject("InternetExplorer.Application")
IE.Visible = 1
IE.navigate "https://google.com"
```
Instead of starting the script, VM shows Windows Scripting Host error box with 800A01AD error code (ActiveX component can't create object: 'InternetExplorer.Application').
The problem does not exist when I use "No Injection" option.

Could you verify if you can replicate this on your own?
I'm wondering if it's a bug or if I have something wrong with my setup.

**Comment by jbremer** [comment]
Although it's not waiting for Internet Explorer to finish execution (and thus terminates the analysis prematurely), it's running fine otherwise - said error does not occur on my 64-bit Windows 7 machine.

**Comment by Bolverk1** [comment]
Indeed, seems to be actually related to little mess in my files.
I pulled repo again and now it's running properly with the latest version :)

Thanks for help and great work!
