### ISSUE TITLE
can't upload files higher than 100MB to vm

### ISSUE THREAD

**Issue by sarulon** [cuckoosandbox/cuckoo#1041]
RROR: Error from the Cuckoo Guest: analysis1: unable to upload malware to analysis machine: <Fault 1: "<type 'exceptions.MemoryError'>:">

**Comment by doomedraven** [comment]
search in code the size of allowed file size and set it to your limit

**Comment by sarulon** [comment]
i found it in web/web/local_settings.py

thx
