### ISSUE TITLE
ALPN support missing

### ISSUE THREAD

**Issue by sarulon** [cuckoosandbox/cuckoo#1044]
Error: ALPN support missing (OpenSSL 1.0.2+ required)! HTTP/2 is disabled. Use --no-http2 to silence this warning.

openssl version -v
OpenSSL 1.0.2h  3 May 2016
pyOpenSSL==16.0.0

what can i do ? or how can i run the command --no-http2 with cuckoo ?

**Comment by jbremer** [comment]
How are you using Cuckoo to get this error message (I don't think I've seen it before)?
Also, which OS / Cuckoo version / etc?

**Comment by sarulon** [comment]
hi 
the os is ubuntu server 14.04 cuckoo version is 2.0-dev also checked with 2.0-rc1 
when i enable mitm i get this error

**Comment by jbremer** [comment]
Doesn't this make it a `mitmproxy` issue then? In my local setup(s) I haven't had any issues with installing `mitmproxy` though, and as such have not seen this error before. Please check their documentation as well.

**Comment by wbenny** [comment]
if you add "--no-http2" to the args (modules/auxiliary/mitm.py), it gets you rid of this warning: 

```python
       args = [
            mitmdump, "-q",
            "-s", "\"%s\" %s" % (script, self.task.options.get("mitm", "")),
            "-p", "%d" % self.port,
            "-w", outpath
        ]

```

**Comment by jbremer** [comment]
@sarulon can you verify that what @wbenny said fixes the issue for you?
Also, isn't there a proper fix here? Installing some extra packages maybe?

**Comment by sarulon** [comment]
@jbremer, I will try it tomorrow

**Comment by sarulon** [comment]
@wbenny thx , looks like it working

**Comment by jbremer** [comment]
I believe this has been resolved as we're shipping some cryptography packages by default now that resolve this warning. Closing as such. If it does still happen with the latest version of Cuckoo, feel free to reopen or create a new issue.
