### ISSUE TITLE
Can not analyse the sample which has a chinese file name

### ISSUE THREAD

**Issue by jackleexp** [cuckoosandbox/cuckoo#1049]
When i submit a sample which has a chinese file name. the cuckoo show me the error:The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.  My os in vm is windowsxp chinese version. Is that inject-x86.exe can not handle the unicode charset?

**Comment by jackleexp** [comment]
Anybody knows the reason?

**Comment by doomedraven** [comment]
no idea, but yes can be what is the unicode problem, try debug it and send patch :) or more details at least

**Comment by jbremer** [comment]
Can you share the filename of your sample? That way I'll be able to test some more.

**Comment by jackleexp** [comment]
the file name is "病毒.exe"。you can rename any executable file to this name, then try it.

**Comment by jackleexp** [comment]
can anybody know the reason?

**Comment by gugronnier** [comment]
for me there is no problem. i take a standard executable file, i rename it "病毒.exe" and i put it in my cuckoosand box (version Cuckoo Sandbox 2.0-dev || VM : windows SP1 x64 french)

**Comment by kevross33** [comment]
I think I have submitted an issue along the same lines: https://github.com/cuckoosandbox/cuckoo/issues/1080

**Comment by jbremer** [comment]
Yes, definitely the same issue @kevross33. Going to close this one as a duplicate. I need to fix it still, though.
