### ISSUE TITLE
Unable to start cuckoo

### ISSUE THREAD

**Issue by sibichakkaravarthy** [cuckoosandbox/cuckoo#1050]
![screenshot from 2016-08-19 06 43 33](https://cloud.githubusercontent.com/assets/3365954/17811558/2893f690-65d8-11e6-8c10-defd0560f581.png)

**Comment by jackleexp** [comment]
try disable check version in cuckoo.conf

**Comment by sibichakkaravarthy** [comment]
@jackleexp thanks for your help. I got working. Everything goes fine but i am not getting dashboard properly loaded when i execute cuckoo web interface

![screenshot from 2016-08-22 01 39 23](https://cloud.githubusercontent.com/assets/3365954/17848584/1b77b91e-6809-11e6-8567-68a966045c9d.png)

**Comment by jbremer** [comment]
Run it from the correct directory, as per documentation.

**Comment by jbremer** [comment]
Closing as probably resolved.
