### ISSUE TITLE
cuckoo.py failed in run

### ISSUE THREAD

**Issue by dmitriy-ddr** [cuckoosandbox/cuckoo#1052]
=== Exception details ===
Cuckoo version: 2.0-dev
OS version: posix
OS release: Kali kali-rolling kali-rolling
Python version: 2.7.12+
Machine arch: x86_64
Git version: 6c54a88b157d97b1125533f65c7b498642873d43
Modules: bson:0.4.3 cybox:2.0.1.4 django:1.10 maec:4.0.1.0 pydeep:0.4 pymongo:3.3.0 xsser:1.6 yara-python:3.1

Traceback (most recent call last):
  File "./cuckoo.py", line 120, in <module>
    test=args.test)
  File "./cuckoo.py", line 80, in cuckoo_init
    ResultServer()
  File "/root/cuckoo/lib/cuckoo/common/utils.py", line 206, in **call**
    cls._instances[cls] = super(Singleton, cls).__call__(_args, *_kwargs)
  File "/root/cuckoo/lib/cuckoo/core/resultserver.py", line 58, in **init**
    if e.errno == errno.EADDRINUSE:
AttributeError: 'exceptions.TypeError' object has no attribute 'errno'

P.S: all installed on a manual http://hacktr.org/2014/11/12/cuckoo-sandbox-installation/

**Comment by dmitriy-ddr** [comment]
And when I checked the ports command "netstat -aon" I did not write
"TCP 0.0.0.0:8000 LISTENING". What could be the problem?

**Comment by jackleexp** [comment]
8000 is django port, not cuckoo.py resultserver listening. check conf/cuckoo.conf resultserver port number.

**Comment by dmitriy-ddr** [comment]
the third day tried unsuccessfully to put the cuckoo. Perhaps you have a ready-made virtual machine vmware or virtualbox? Thanks

**Comment by jbremer** [comment]
Could you add `print e` on line 57 of `lib/cuckoo/core/resultserver.py` and show us the output?
It would appear that on your setup a different exception type is caught than the one we're interested in, so we'll have to tweak that a little bit.

**Comment by jbremer** [comment]
We don't have ready-made VMs as nested virtualization is generally speaking *suboptimal*. If the guide you found didn't work, please try again with our official documentation.
Closing for now as incomplete information has been provided to further triage this bug. Please reopen if you wish to further help us figuring out what went wrong ;-)
