### ISSUE TITLE
add new api calls to cuckoo

### ISSUE THREAD

**Issue by shirinmgh** [cuckoosandbox/cuckoo#1053]
Hi, Cuckoo doesn't log some API calls, for example those related to msvcrt.dll. Can I add them by editing conf files of cuckoo? and if yes how?

**Comment by doomedraven** [comment]
you can add hooks here https://github.com/cuckoosandbox/monitor, and replace your monitor

**Comment by shirinmgh** [comment]
which place? please explain more

**Comment by doomedraven** [comment]
read the documentation http://cuckoo-monitor.readthedocs.io/en/latest/

**Comment by shirinmgh** [comment]
I should add the dll completely or API calls one by one? 
how I should replace it? I found a folder with this name in data folder, but all of them are .exe.

**Comment by doomedraven** [comment]
you need place your hooks in correct files, then compile it, then replace it in data/monitor/latest

**Comment by shirinmgh** [comment]
I should put the the MSVCRT dll, hooks in sig/system.rst , is it true?

**Comment by doomedraven** [comment]
rst is documentation,
check https://github.com/cuckoosandbox/monitor/tree/master/src

**Comment by jbremer** [comment]
No, `sig/system.rst` is fine. It's just a custom format to define the hooks.

**Comment by shirinmgh** [comment]
Do you mean I should put all of my hooks in system.rst?

**Comment by jbremer** [comment]
That's one of the possibilities, yes.. Please just give it a try.

**Comment by shirinmgh** [comment]
I read all document and understood it. Now I don't know how I should compile it? I couldn't understand this line of document : 'To compile the Monitor on a machine that has been configured to feature all requirements all one has to do is run make. The various Components will be automatically processed and stitched together' . 
please say me how I should compile with make command?

**Comment by shirinmgh** [comment]
I added my APIs to sigs of cuckoo monitor successfully. Then compiled it and replaced my exe files with cuckoo monitor, after I ran cuckoo for submitting a sample, but I faced with this error : "analysis failed the package modules.packages.exe start function raised an error..."
why this happened while in generated report there is added API???

**Comment by jbremer** [comment]
Can you show your changes as well as the `report.json` file from the analysis?

**Comment by shirinmgh** [comment]
I just add GetStartupInfoA & GetStartupInfoW in sigs/system.rst as explained in monitor document, after I compile it and in output report this API was shown. but report isn't complete and top of the report is written " Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted."
I didn't do anything else... what is the problem?

**Comment by jbremer** [comment]
Did the analysis work before you added those hooks? If so, the added hooks are probably incorrect :-)

**Comment by jbremer** [comment]
Going to close this issue. Feel free to provide a pull request to the `monitor` branch or let us know what you've been working on & reopen this issue :-)
