### ISSUE TITLE
Prevent of skipping APIs in cuckoo

### ISSUE THREAD

**Issue by shirinmgh** [cuckoosandbox/cuckoo#1061]
I want to add some API calls to Cuckoo sandbox, like __p__fmode, ... but when I add them, and run make command I faced with this :"skipping ignored API signature: __p__fmode" and the same message for the others.
what is the problem? how I should fix it?

**Comment by jbremer** [comment]
It's because of the somewhat *unexpected* leading underscore(s). Is there any point in hooking this function, though?

**Comment by shirinmgh** [comment]
yes, I found it in utils/process.py, and deleted this part of code : 
if apiname.startswith('_'):
                print>>sys.stderr, \
                    'Skipping ignored API Signature:', apiname[1:]
                continue
after that previous problem was solved but now I faced with this : 
File "utils/process.py", line 728, in <module>
    dp.process()
  File "utils/process.py", line 438, in process
    for sig in self.normalize(self.dp.read_document(sig_path)):
  File "utils/process.py", line 410, in normalize
    flag['name'], row['apiname'], flagname))
Exception: Flag u'extended_style' of u'_CreateWindowExA' (u'_CreateWindowExA_dwExStyle') is unknown!
make: *** [objects/code/hooks.c] Error 1
make: *** Waiting for unfinished jobs....

I'm not familiar with python and couldn't understand it :((((

**Comment by jbremer** [comment]
Completely remove the `_CreateWindowExA`/`W` signatures from, I believe, `sigs/ui.rst`.

**Comment by shirinmgh** [comment]
I did it but again for my APIs such __p_fmode, __p_commode,... had problem :(( 
I think, I should change the process.py code :(

**Comment by jbremer** [comment]
I still don't see the point of hooking those specific functions?

**Comment by shirinmgh** [comment]
I added these functions to sigs/misc.rst with specified signature format, after deleted `_CreateWindowExA/W` and `_DialogBoxIndirectParamA/W` again faced with this:
`File "utils/process.py", line 728, in <module>
    dp.process()
  File "utils/process.py", line 438, in process
    for sig in self.normalize(self.dp.read_document(sig_path)):
  File "utils/process.py", line 341, in normalize
    (retval, row['apiname']))
Exception: Unknown return_value u'int' for api u'__p__commode'.
make: *** [objects/code/hooks.c] Error 1
make: *** Waiting for unfinished jobs.... ` 
So I thought maybe I should change my code :(

**Comment by jbremer** [comment]
You can make `utils/process.py` not skip functions starting with an underscore, but that doesn't mean that hooking `__p_fmode` still most likely doesn't make sense anyway.
Closing this issue as I don't think the proposed problems affect any practical usage. Please reopen if you have any other questions etc.
