### ISSUE TITLE
Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.pdf" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by wang0528** [cuckoosandbox/cuckoo#1063]
Hello Team,

I try to analysis the PDF file on the Cuckoo, some how it will not open the PDF, and it generate error when i run the analysis. 

2016-08-30 11:43:06,799 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.pdf" start function raised an error: Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\gzxquxejpd\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\gzxquxejpd\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.pdf" start function raised an error: Unable to execute the initial process, analysis aborted.

My guest OS is win7, and I installed adobe acrobat reader 11

Please Help

Thank you so much

**Comment by jbremer** [comment]
Although I believe Adobe 11 should somewhat work, I've tested it as not working completely.
Could you for the time being try out Adobe PDF Reader 9?

**Comment by nsmfoo** [comment]
Could you run:  ./community.py -waf and see if this resolves your issue? I had the same issue previously which was resolved this way

**Comment by jbremer** [comment]
Closing this issue as not enough information has been provided. Please reopen if you intend to share more and work together on fixing any bugs.
