### ISSUE TITLE
Debug cuckoo

### ISSUE THREAD

**Issue by g00dv1n** [cuckoosandbox/cuckoo#1064]
How I can debug cuckoo when writing my own modules (like reporting) without submit sample and waiting results ?

**Comment by doomedraven** [comment]
pycharm or any another IDE with debug capabilities, set breakpoint on your plugin, or use `process.py -r ID` to regenerate, more quickest then resubmit sample

**Comment by g00dv1n** [comment]
Thanks man! "process.py -r ID" is what I need !

**Comment by doomedraven** [comment]
you are welcome, if solved, close ;)
