### ISSUE TITLE
Windows Analyzer: Time drift bug

### ISSUE THREAD

**Issue by ChriDr** [cuckoosandbox/cuckoo#1067]
Hi,

I think there is a Bug within the analyzer/windows/lib/core/startup.py file . When an analysis starts, the system time will be set to the time when the task was submited. The timzone information is also included in that time, it is not just an utc time.

Therfore when the set_clock(clock) method is used, the time will be interpreted as utc time without timezone information. Because KERNEL32.SetSystemTime(ctypes.byref(st)) set the system as utc time. Then the time jumbs e.g 2 hours ahead.

Instead of SetSystemTime, the SetLocalTime function should be used.

Best regards,

**Comment by jbremer** [comment]
Thanks for that insight. Would you like to do a small pull request for that? :-)

**Comment by ChriDr** [comment]
Sure :).  I will do it today or tomorrow

**Comment by jbremer** [comment]
Resolved as per your PR, thanks again.
