### ISSUE TITLE
Question: how does the cuckoo recognize the latest task_id?

### ISSUE THREAD

**Issue by Sanghyun-Hong** [cuckoosandbox/cuckoo#1076]
Hi,

Since I try to run the many analysis using Cuckoo, I've struggling with storage issue. I want to keep some of the analysis results to the other storage. I'm planning to store the cuckoo data according to the task_id of each analysis, and I would like to know how the cuckoo recognizes the latest number of task_id. Does it use the symbolic link under the store/analysis/ directory?

-S.

**Comment by doomedraven** [comment]
There is a latest folder in analysis + db id as key

**Comment by Sanghyun-Hong** [comment]
@doomedraven, do you mean that Cuckoo is reading the directory name for the task_id?
