### ISSUE TITLE
Why was Android MITM functionality reverted?

### ISSUE THREAD

**Issue by kuza55** [cuckoosandbox/cuckoo#1078]
I'm interested in MITMing Android apps so I'm curious why the Android MITM code got reverted: https://github.com/cuckoosandbox/cuckoo/commit/2bf7e20d698888c6a1fed6512b733e30bd03f2a2

pinging @RuneTM

**Comment by jbremer** [comment]
I don't remember :-) @kuza55 do you have Android analysis working right now?
There have been some people posting issues around that recently, so I guess something may have broken in the past months. Could use your input here :-)

**Comment by kuza55** [comment]
I'm not working on malware analysis any more, and when I was I was running cuckoodroid w/ cuckoo 1.3, so I can't really help with what's current, sorry :(

**Comment by jbremer** [comment]
Gotcha, thanks for the quick reply. I guess I'll close this issue then :-)
Let me know if I can help out in any other scenarios!
