### ISSUE TITLE
Submitting files with diacritic characters fails.

### ISSUE THREAD

**Issue by kevross33** [cuckoosandbox/cuckoo#1080]
Hi,

While running the files here http://www.malware-traffic-analysis.net/2016/09/08/index.html I ran the file "Planilha_Oráamento.js". However it did not run and responding with error:

Error: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.js" start function raised an error: Unable to execute the initial process, analysis aborted. Traceback (most recent call last): File "C:\lytjamc\analyzer.py", line 778, in <module> success = analyzer.run() File "C:\lytjamc\analyzer.py", line 626, in run (package_name, e) CuckooError: The package "modules.packages.js" start function raised an error: Unable to execute the initial process, analysis aborted. 

Now I renamed it renamed.js and it ran fine and alerts on the payload signature (writing EXE, network activity etc) so I believe the issue is submitting files with a name with diacritic letters i.e á.

**Comment by jbremer** [comment]
The latest versions of Cuckoo should certainly feature improved unicode support, although there's still one PR left to merge I believe. Did you have any issues with this recently?

**Comment by jbremer** [comment]
Having pushed through fixes for a couple more unicode-related issues, this should certainly work properly now. Going to close this as resolved. Of course let me know if you do still run into issues here ;-)
