### ISSUE TITLE
Cuckoo running successfully but it is not giving any result

### ISSUE THREAD

**Issue by mahaveer1984** [cuckoosandbox/cuckoo#1086]
I am using cuckoo for .apk analysis. My cuckoo is running without any error and agent in VM getting the submitted apk but neither cuckoo performing static analysis nor dynamic. it means cuckoo is not doing anything. it is starting the VM and stopping properly. Why cuckoo is not giving any result.
![cuckoo](https://cloud.githubusercontent.com/assets/19815922/18433146/a12637d8-7903-11e6-8fd1-67536bf7f2e0.png)

**Comment by alabiana** [comment]
looked in the named storage folder? ~/Downloads/cuckoo/storage/analyses/35
There should be something, at least the analysis.log

**Comment by jbremer** [comment]
And did you enable the Android-related processing modules etc? Sorry for the late reply. Did you already resolve these issues by now?

**Comment by jbremer** [comment]
I guess we can close this issue, although I'd be happy to get some more feedback!
