### ISSUE TITLE
Cuckoo redirecting incorrectly

### ISSUE THREAD

**Issue by E3L-1** [cuckoosandbox/cuckoo#1088]
I have a new cuckoo 2.0RC1 installation and i'm having an issue when the status page of a submitted file tries to redirect once it's done. I have an nginx reverse proxy fronting the cuckoo web box redirecting all incoming traffic to 127.0.0.1:8000.

To recreate: submit sample, then click on the sample id to get to the waiting page. Once the waiting page refreshes and it knows the sample is done being analyzed, it redirects to 127.0.0.1:8000/analysis/<id>. This of course fails as the user's browser is not able to hit 127.0.0.1:8000. 

As i'm writing this, I just realized why this was working prior to fronting it with nginx. I was hitting a local network address. e.g. Client is able to resolve server address 172.16.10.5 and when that final redirect happens, the client already knows how to resolve that. In this case, the server being hit is 127.0.0.1 from the rev proxy.. At least the bug now makes sense to me.

Any ideas on a fix for this or a general location for the fix?

**Comment by prats84** [comment]
One way you can try is : 

Create a file with the below lines

server {
        listen cuckoo.anyfake.domain.com:80 default_server;
        location / {
            proxy_pass http://cuckoo.anyfake.domain.com:8000;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }

Add that file to /etc/nginx/sites-available 

Also, add an entry in the /etc/host file for 127.0.0.1 pointing to cuckoo.anyfake.domain.com

**Comment by E3L-1** [comment]
@prats84  - Thank you for the suggestion!

I was able to resolve it by having the following in the nginx config.

proxy_pass  http://127.0.0.1:8000;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

My original configuration did not have the last two proxy_set_header lines and my proxy_pass looked like this: 
proxy_pass  http://127.0.0.1:8000:$request_uri;

When i tried what you suggested above exactly, something was not happy and the site wouldn't come up any longer. So after troubleshooting a bit, i ended up with what i posted above.

Thanks again!
