### ISSUE TITLE
Request: Floss instead of strings if available?

### ISSUE THREAD

**Issue by kevross33** [cuckoosandbox/cuckoo#1090]
Just a feature request for consideration. As in malware running strings on malware rarely comes back with much I have been using this (it is issued under apache licence). I was thinking if it was installed on the host perhaps it could be used instead of strings and if not? 

https://www.fireeye.com/blog/threat-research/2016/06/automatically-extracting-obfuscated-strings.html
https://github.com/fireeye/flare-floss
Sans Forensics Conference Video on it: https://www.youtube.com/watch?v=i2gDruusO3I

**Comment by jbremer** [comment]
I mostly just wonder on how much malware this tool has been tested and how well it benchmarks. Provided they're using a custom emulator in certain cases, I foresee deadlock issues etc.

**Comment by jbremer** [comment]
Closing for reasons stated above - it's a decent suggestion, though.

**Comment by capnspacehook** [comment]
@jbremer since FLOSS has been battle-tested amoung the malware analysis community, would you consider allowing a FLOSS module to be added? I'd be happy to submit a pull request for it if you think it's a good idea.
