### ISSUE TITLE
Could not able to read report.json and runserver hits error

### ISSUE THREAD

**Issue by bganeshmail** [cuckoosandbox/cuckoo#1093]
All:

I ran the Malware analysis and report is in JSON format.When i start web run server it throws below error.
Can you please advice

root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/web# python manage.py runserver 0.0.0.0:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0xb19acae4>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

System check identified 1 issue (0 silenced).

**Comment by doomedraven** [comment]
which is the django version?

**Comment by bganeshmail** [comment]
I am new to this analysis,could you pls advice the command to identify version?

**Comment by doomedraven** [comment]
`pip freeze | grep django`

also in cuckoo root there are file called `requierements.txt` you should execute `sudo pip install -r requirements.exe`

but as you telling you are new, probably would be better first read the documentation ;)
http://docs.cuckoosandbox.org/en/latest/

**Comment by bganeshmail** [comment]
Sure .Thanks much...

**Comment by doomedraven** [comment]
so which version of django do you have?

**Comment by bganeshmail** [comment]
Hi Draven,

I am fan of this Cuckoo project..

I amtrying this for last one week but could not succeed.

I am following the link above but i am not sure where the mistake it.


pip freeze | grep django
root@ubuntu-To-be-filled-by-O-E-M:~# pip freeze | grep django
root@ubuntu-To-be-filled-by-O-E-M:~#



Attached the log file while running
requirements.troot@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo# grep -i
failed logger
  error: command 'i686-linux-gnu-gcc' failed with exit status 1
  distutils.errors.DistutilsError: Setup script exited with error: command
'i686-linux-gnu-gcc' failed with exit status 1
  distutils.errors.DistutilsError: Setup script exited with error: command
'i686-linux-gnu-gcc' failed with exit status 1
Failed to build cffi cryptography
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo#

**Comment by doomedraven** [comment]
Google your errors, is not cuckoo related issue

**Comment by bganeshmail** [comment]
Ok All Done.

I have one final Error.Could not locate pefile in google sites..even

 http://pefile.googlecode.com/files/

Collecting pefile from
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
(from -r requirements.txt (line 21))
  HTTP error 404 while getting
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
  Could not install requirement pefile from
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
(from -r requirements.txt (line 21)) because of error 404 Client Error: Not
Found for url: http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz
Could not install requirement pefile from
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
(from -r requirements.txt (line 21)) because of HTTP error 404 Client
Error: Not Found for url:
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz for URL
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile

**Comment by seifreed** [comment]
Hi,

 

You can resolve this point doing:

 

sudo –H pip install pefile 

 

remove pefile in requirements, or change to pefile

 

Regards,

 

--

Marc Rivero López | @seifreed

 

De: bganeshmail [mailto:notifications@github.com] 
Enviado el: sábado, 17 de septiembre de 2016 16:58
Para: cuckoosandbox/cuckoo <cuckoo@noreply.github.com>
Asunto: Re: [cuckoosandbox/cuckoo] Could not able to read report.json and runserver hits error (#1093)

 

Ok All Done.

I have one final Error.Could not locate pefile in google sites..even

http://pefile.googlecode.com/files/

Collecting pefile from
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
(from -r requirements.txt (line 21))
HTTP error 404 while getting
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
Could not install requirement pefile from
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
(from -r requirements.txt (line 21)) because of error 404 Client Error: Not
Found for url: http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz
Could not install requirement pefile from
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
(from -r requirements.txt (line 21)) because of HTTP error 404 Client
Error: Not Found for url:
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz for URL
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile

**Comment by doomedraven** [comment]
@bganeshmail uninstall pefile and intall `pefile2`

**Comment by doomedraven** [comment]
also i think you trying to install cuckoo-mod not oficial one as in requirements it specify pefile2 nto that your one, so is incorrect project to report

**Comment by bganeshmail** [comment]
Hi Draven,

I am not sure where was the mistake .Each time new new errors.

All seems to be OS errors.

Is there preconfigured Ubuntu Machine such like one provided by
OWASP/MEtaploitable ,if not cam we make one ready.This will save lot of
times to researchers.

I spent nearly week and still i could not configure the machine.


I tried in Ubuntu 16.05 and now trying 14.04.

I tried dev version as well a stable version .Issues still occuring.


root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo# python
cuckoo.py

    sSSs   .S       S.     sSSs   .S    S.     sSSs_sSSs      sSSs_sSSs
   d%%SP  .SS       SS.   d%%SP  .SS    SS.   d%%SP~YS%%b    d%%SP~YS%%b
  d%S'    S%S       S%S  d%S'    S%S    S&S  d%S'     `S%b  d%S'     `S%b
  S%S     S%S       S%S  S%S     S%S    d*S  S%S       S%S  S%S       S%S
  S&S     S&S       S&S  S&S     S&S   .S*S  S&S       S&S  S&S       S&S
  S&S     S&S       S&S  S&S     S&S_sdSSS   S&S       S&S  S&S       S&S
  S&S     S&S       S&S  S&S     S&S~YSSY%b  S&S       S&S  S&S       S&S
  S&S     S&S       S&S  S&S     S&S    `S%  S&S       S&S  S&S       S&S
  S*b     S*b       d*S  S*b     S*S     S%  S*b       d*S  S*b       d*S
  S*S.    S*S.     .S*S  S*S.    S*S     S&  S*S.     .S*S  S*S.     .S*S
   SSSbs   SSSbs_sdSSS    SSSbs  S*S     S&   SSSbs_sdSSS    SSSbs_sdSSS
    YSSP    YSSP~YSSY      YSSP  S*S     SS    YSSP~YSSY      YSSP~YSSY
                                 SP
                                 Y

 Cuckoo Sandbox 2.0-rc1
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

2016-09-18 14:01:28,934 [lib.cuckoo.core.scheduler] INFO: Using
"virtualbox" as machine manager
2016-09-18 14:01:31,233 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-09-18 14:01:31,247 [lib.cuckoo.core.scheduler] INFO: Waiting for
analysis tasks.
2016-09-18 14:07:03,117 [lib.cuckoo.core.scheduler] INFO: Starting analysis
of FILE "tini.exe" (task #1, options "")
2016-09-18 14:07:03,306 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired
machine xp (label=xp)
2016-09-18 14:07:03,342 [modules.auxiliary.sniffer] INFO: Started sniffer
with PID 4471 (interface=vboxnet0, host=192.168.56.101
snapshot = snap
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042,
pcap=/home/cuckoo/cuckoo/cuckoo/storage/analyses/1/dump.pcap)
tcpdump: syntax error
2016-09-18 14:07:06,932 [lib.cuckoo.core.guest] INFO: Starting analysis on
guest (id=xp, ip=192.168.56.101
snapshot = snap
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042)
2016-09-18 14:07:14,610 [lib.cuckoo.core.scheduler] ERROR: Failure in
AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 447,
in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 339,
in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 257,
in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 382, in
start_analysis
    r = self.get("/")
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 255, in
get
    return requests.get(url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in
request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378,
in send
    raise ConnectionError(e)
ConnectionError:
HTTPConnectionPool(host='192.168.56.101%0Asnapshot%20=%20snap%0Ainterface%20=%20vboxnet0%0Aresultserver_ip%20=%20192.168.56.1%0Aresultserver_port%20=%202042',
port=8000): Max retries exceeded with url: / (Caused by <class
'socket.gaierror'>: [Errno -2] Name or service not known)
2016-09-18 14:12:29,560 [lib.cuckoo.core.scheduler] INFO: Starting analysis
of FILE "tini.exe" (task #2, options "")
2016-09-18 14:12:29,564 [lib.cuckoo.core.scheduler] INFO: File already
exists at
"/home/cuckoo/cuckoo/cuckoo/storage/binaries/9654bb748199882b0fb29b1fa597c0cfe3b9d610adf4188a0b440f3faf5ee527"
2016-09-18 14:12:29,706 [lib.cuckoo.core.scheduler] INFO: Task #2: acquired
machine xp (label=xp)
2016-09-18 14:12:29,711 [modules.auxiliary.sniffer] INFO: Started sniffer
with PID 4714 (interface=vboxnet0, host=192.168.56.101
snapshot = snap
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042,
pcap=/home/cuckoo/cuckoo/cuckoo/storage/analyses/2/dump.pcap)
tcpdump: syntax error
2016-09-18 14:12:33,106 [lib.cuckoo.core.guest] INFO: Starting analysis on
guest (id=xp, ip=192.168.56.101
snapshot = snap
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042)
2016-09-18 14:12:39,811 [lib.cuckoo.core.scheduler] ERROR: Failure in
AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 447,
in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 339,
in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 257,
in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 382, in
start_analysis
    r = self.get("/")
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 255, in
get
    return requests.get(url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in
request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378,
in send
    raise ConnectionError(e)
ConnectionError:
HTTPConnectionPool(host='192.168.56.101%0Asnapshot%20=%20snap%0Ainterface%20=%20vboxnet0%0Aresultserver_ip%20=%20192.168.56.1%0Aresultserver_port%20=%202042',
port=8000): Max retries exceeded with url: / (Caused by <class
'socket.gaierror'>: [Errno -2] Name or service not known)

**Comment by bganeshmail** [comment]
Hi Team,

Please advice where the issues lies.

Attaching all details.

Configuaration File
====================

root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/conf# grep -v
^# cuckoo.conf
[cuckoo]
version_check = off

delete_original = off

delete_bin_copy = off

machinery = virtualbox

memory_dump = off

terminate_processes = off

reschedule = off

process_results = on

max_analysis_count = 0

max_machines_count = 0

max_vmstartup_count = 10

freespace = 64

tmppath = /tmp

rooter = /tmp/cuckoo-rooter

[routing]
route = none

internet = none

[resultserver]
ip = 192.168.56.1

port = 2042

upload_max_size = 10485760

[processing]
analysis_size_limit = 104857600

resolve_dns = on

sort_pcap = on

[database]
connection =

timeout =

[timeouts]
default = 120

critical = 600

vm_state = 60
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/conf# grep -v
^# virtualbox.conf
[virtualbox]
mode = gui

path = /usr/bin/VBoxManage

interface = vboxnet0

machines = xp

[xp]
label = xp

platform = windows

ip = 192.168.56.101

 snapshot = snap1

 interface = vboxnet0

 resultserver_ip = 192.168.56.1

 resultserver_port = 2042


[honeyd]
label = honeyd
platform = linux
ip = 192.168.56.102
tags = service, honeyd
options = nictrace noagent
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/conf# grep -v
^# processing.conf

[analysisinfo]
enabled = yes

[apkinfo]
enabled = no

[baseline]
enabled = no

[behavior]
enabled = yes

[buffer]
enabled = yes

[debug]
enabled = yes

[droidmon]
enabled = no

[dropped]
enabled = yes

[dumptls]
enabled = yes

[googleplay]
enabled = no
android_id =
google_login =
google_password =

[memory]
enabled = no

[network]
enabled = yes

[procmemory]
enabled = yes
idapro = no

[screenshots]
enabled = no
tesseract = /usr/bin/tesseract

[snort]
enabled = no

[static]
enabled = yes

[strings]
enabled = yes

[suricata]
enabled = no

[targetinfo]
enabled = yes

[virustotal]
enabled = yes
timeout = 60
scan = 0
key = a0283a2c3d55728300d064874239b5346fb991317e8449fe43c902879d758088
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/conf# grep -v
^# reporting.conf

[jsondump]
enabled = yes
indent = 4
encoding = latin-1
calls = yes

[reporthtml]
enabled = no

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100

[moloch]
enabled = no
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/conf#



====================================

Starting Cuckoo Now

Croot@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo# python
cuckoo.py

  _____________________________________/\/\_______________________________
  ___/\/\/\/\__/\/\__/\/\____/\/\/\/\__/\/\__/\/\____/\/\/\______/\/\/\___
  _/\/\________/\/\__/\/\__/\/\________/\/\/\/\____/\/\__/\/\__/\/\__/\/\_
  _/\/\________/\/\__/\/\__/\/\________/\/\/\/\____/\/\__/\/\__/\/\__/\/\_
  ___/\/\/\/\____/\/\/\/\____/\/\/\/\__/\/\__/\/\____/\/\/\______/\/\/\___
  ________________________________________________________________________

 Cuckoo Sandbox 2.0-rc1
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

2016-09-23 10:03:08,712 [root] INFO: Updated running task ID 3 status to
failed_analysis
2016-09-23 10:03:08,725 [lib.cuckoo.core.scheduler] INFO: Using
"virtualbox" as machine manager
2016-09-23 10:03:11,072 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-09-23 10:03:11,085 [lib.cuckoo.core.scheduler] INFO: Waiting for
analysis tasks.



===================================================

Running Submit.py

root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/utils#
./submit.py /tmp/Viruses/tini.exe
Success: File "/tmp/Viruses/tini.exe" added as task with ID 4
root@ubuntu-To-be-filled-by-O-E-M:/home/cuckoo/cuckoo/cuckoo/utils#



==========================

Error Below

Cuckoo Sandbox 2.0-rc1
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

2016-09-23 10:03:08,712 [root] INFO: Updated running task ID 3 status to
failed_analysis
2016-09-23 10:03:08,725 [lib.cuckoo.core.scheduler] INFO: Using
"virtualbox" as machine manager
2016-09-23 10:03:11,072 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-09-23 10:03:11,085 [lib.cuckoo.core.scheduler] INFO: Waiting for
analysis tasks.
2016-09-23 10:05:07,978 [lib.cuckoo.core.scheduler] INFO: Starting analysis
of FILE "tini.exe" (task #4, options "")
2016-09-23 10:05:07,983 [lib.cuckoo.core.scheduler] INFO: File already
exists at
"/home/cuckoo/cuckoo/cuckoo/storage/binaries/9654bb748199882b0fb29b1fa597c0cfe3b9d610adf4188a0b440f3faf5ee527"
2016-09-23 10:05:08,165 [lib.cuckoo.core.scheduler] INFO: Task #4: acquired
machine xp (label=xp)
2016-09-23 10:05:08,170 [modules.auxiliary.sniffer] INFO: Started sniffer
with PID 4778 (interface=vboxnet0, host=192.168.56.101
snapshot = snap1
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042,
pcap=/home/cuckoo/cuckoo/cuckoo/storage/analyses/4/dump.pcap)
tcpdump: syntax error
2016-09-23 10:05:12,014 [lib.cuckoo.core.guest] INFO: Starting analysis on
guest (id=xp, ip=192.168.56.101
snapshot = snap1
interface = vboxnet0
resultserver_ip = 192.168.56.1
resultserver_port = 2042)
2016-09-23 10:05:18,902 [lib.cuckoo.core.scheduler] ERROR: Failure in
AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 447,
in run
    self.launch_analysis()
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 339,
in launch_analysis
    self.guest_manage(options)
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 257,
in guest_manage
    guest.start_analysis(options, monitor)
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 382, in
start_analysis
    r = self.get("/")
  File "/home/cuckoo/cuckoo/cuckoo/lib/cuckoo/core/guest.py", line 255, in
get
    return requests.get(url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in
request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378,
in send
    raise ConnectionError(e)
ConnectionError:
HTTPConnectionPool(host='192.168.56.101%0Asnapshot%20=%20snap1%0Ainterface%20=%20vboxnet0%0Aresultserver_ip%20=%20192.168.56.1%0Aresultserver_port%20=%202042',
port=8000): Max retries exceeded with url: / (Caused by <class
'socket.gaierror'>: [Errno -2] Name or service not known)

**Comment by jbremer** [comment]
Closing this issue. I think @doomedraven has given more than enough help here and it would appear somebody is not reading the actual exceptions thrown.
