### ISSUE TITLE
Python Script to Verify all the packages under requirements.txt is perfect.

### ISSUE THREAD

**Issue by bganeshmail** [cuckoosandbox/cuckoo#1097]
Hi All,

A general Feedback.

Requirements.txt is a great resource to set the pre work Part.But as per understanding lot of issues occurs dues to some package not getting installed properly.

Can we create some script to look for package under requirements is getting installed properly and if not report those package to get installed.

Please advice.

**Comment by jbremer** [comment]
In #863 this will all be taken care of automatically.

**Comment by bganeshmail** [comment]
Fantastic Bremer .

This is great news...

We need to wait for some more time to make us of the suggesstion in #863 ?

**Comment by bganeshmail** [comment]
Thanks much ...Very nice Support given..

Please let know the new updates once ready.

**Comment by bganeshmail** [comment]
Good Support from Cuckoo Team and let this team  grow to new heights and build more security programs like this,God bless You Cuckoo Team,.

You will be  Security leader one day.
