### ISSUE TITLE
Why not use gevent to make the processing to asynchronous execute ?

### ISSUE THREAD

**Issue by Ryuchen** [cuckoosandbox/cuckoo#1109]
http://www.gevent.org/

**Comment by jbremer** [comment]
Which part exactly do you suggest to become asynchronous?

**Comment by Ryuchen** [comment]
http://www.gevent.org/
I mean in a single processing, if we can use this packages to run the behavior.py and static.py at same time?

**Comment by jbremer** [comment]
We could do that, I guess, but I don't think it will gain any speed ups in terms of performance. It will just balance the load on to multiple threads (or greenlets) which right now we handle by having multiple processing utilities running (i.e., be able to process multiple analyses results at once).

At this point I don't think anyone will be working on this (or have special interest in it), so I'm going to close it ;-)
