### ISSUE TITLE
Index page is slow to load when there are a lot of analyses

### ISSUE THREAD

**Issue by daviesjamie** [cuckoosandbox/cuckoo#1110]
The code that generates the statistics for the index page is not optimised for large numbers of analyses, and as such, loading of the index page slows down dramatically when there are many analyses.

I think the worst offenders in the code are the `for` loops that are finding the min/max timestamp ([/web/dashboard/views.py](https://github.com/cuckoosandbox/cuckoo/blob/master/web/dashboard/views.py#L59)):

```
# Get the time when the first task started.
started = min(timestamp(task.started_on) for task in tasks)

# Get the time when the last task completed.
completed = max(timestamp(task.completed_on) for task in tasks)
```

These operations would be much more efficient as a database query (assuming there's an index on task `started_on`/`completed_on` datetimes).

**Comment by razuz** [comment]
@daviesjamie can you test changes in #1117 ? it should resolve it and speed it up nicely no matter how much analyses are in DB. I was testing with ~500k under high load and it was OK.

**Comment by doomedraven** [comment]
awesome, works much more faster :)
thanks dude
