### ISSUE TITLE
TaskID in Django web interface

### ISSUE THREAD

**Issue by satmit** [cuckoosandbox/cuckoo#1114]
Hi Team,

I need Task ID to display in Recent tab of Django web interface.

Request you to help me in this. Attached the screenshot.

Thanks & Regards,
Satheesh
![screenshot from 2016-09-28 19 56 24](https://cloud.githubusercontent.com/assets/19163822/18917696/21876df2-85b6-11e6-98ef-b18a5acb961b.png)

**Comment by doomedraven** [comment]
Can you give more info which branch, version etc do you use? Is not last version as there missed import export, or is cuckoomod?

**Comment by satmit** [comment]
@doomedraven

Django 1.84
Cuckoo 2.0

Issue is I don't know how to fetch Task ID to display along with already available FileName, MD5.

**Comment by doomedraven** [comment]
It strange because ot show it by defautl without any problem

**Comment by doomedraven** [comment]
ah yeah it true it not shown, feel free to add it and do a pull req :)

**Comment by jbremer** [comment]
We're currently doing quite some refactoring on the Web Interface and this is definitely something that has been resolved. I guess we'll keep the issue open a little bit longer, though, until said releases come out.

**Comment by satmit** [comment]
Hi,

Thanks for your time.!

We have already completed this task of adding ID in web interface display.


Regards,
Satheesh

**Comment by jbremer** [comment]
@satmit Do you mind doing a pull request to share your changes with the rest of the community?

**Comment by satmit** [comment]
@jbremer Sure., below are the codes, I have added in index.html under cuckoo/web/templates/analysis

 <a href="{% url "analysis.views.report" analysis.id %}"><span class="mono">{{analysis.id}}</span></a>

**Comment by jbremer** [comment]
Which version of Cuckoo are you running in the first place? I'm not seeing any `Task ID` column in either `2.0-rc1` or `2.0-dev`.

**Comment by satmit** [comment]
Cuckoo v2.0-rc1.

I have added that column manually to display Task ID. Attached the edited contents in index.html under cuckoo/web/templates/analysis
![index](https://cloud.githubusercontent.com/assets/19163822/19886261/76078ad6-a048-11e6-9f16-c14008a9404e.PNG)

**Comment by jbremer** [comment]
Ok, thanks. We'll have this in an upcoming version of Cuckoo as well - so closing as resolved.
