### ISSUE TITLE
.zip analyzer package splits arguments incorrectly

### ISSUE THREAD

**Issue by hoppers2k9** [cuckoosandbox/cuckoo#1116]
When using the .zip analyzer, if I specify arguments=helloworld, then 'h e l l o w o r l d' is passed to the sample in the zip. 

The .zip package does not use shlex.split on the args like the .exe analyser does. I am happy to submit a pull request for this.

**Comment by jbremer** [comment]
Soon this package will be deprecated in the first place anyway, so I'm not sure if those efforts would be fruitful. For more information, see also https://cuckoo.sh/blog/sflock01.html.

**Comment by hoppers2k9** [comment]
Ok cool, out of interest, will this update retain the ability to pass arguments to the sample?
