### ISSUE TITLE
 “modules.packages.exe” : Cannot create a file when that file already exists 

### ISSUE THREAD

**Issue by CheHaoKang** [cuckoosandbox/cuckoo#1118]
Dear all,

I encountered the below error when executing cuckoo analysis:
**Analysis failed: The package "modules.packages.exe" start function encountered an unhandled exception: [Error 183] Cannot create a file when that file already exists**
([Error Message Picture](http://i.imgur.com/w7dAb8V.png))

I googled it but most of the information is about Windows.
So, I searched Cuckoo folder and found the error is generated by:
**./lib/cuckoo/core/guest.py:223: raise CuckooGuestError("Analysis failed: {0}".format(error))**

However, this doesn't help me to solve the problem.
Just want to know does anyone have this problem ever?

Thanks a lot,
Kang

**Comment by doomedraven** [comment]
never saw that problem, can you also provide more details? as cuckoo version? rc1? dev? if dev are you on last commit? did you try upload for new the same sample and error was raised for new?

**Comment by CheHaoKang** [comment]
Hi, doomedraven,

Thanks for reminding me to try another malware program.

I tried another one and it looks fine.
([Execution Picture](http://i.imgur.com/rGjYskM.png))

Now I know not every error messages are related to Cuckoo execution error.
Anyway, the following are the information of my setting:
1. Ubuntu 16.04 LTS (xenial)
2. Cuckoo Sandbox 2.0-rc1

Thanks a lot,
Kang

**Comment by doomedraven** [comment]
Please consider try to use dev branch it has many errors fixed from rc1

**Comment by CheHaoKang** [comment]
Hi, doomedraven,

I've switched to dev branch.

Thanks a lot,
Kang

**Comment by doomedraven** [comment]
everything solved? if yes close this ;)
