### ISSUE TITLE
Error with httpreplay

### ISSUE THREAD

**Issue by alabiana** [cuckoosandbox/cuckoo#1125]
I have the problem, that every analysis contains this error in console:
2016-10-13 13:21:05,719 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/home/user/cuckoo/modules/processing/network.py", line 764, in run
    results.update(Pcap2(pcap_path, self.get_tlsmaster()).run())
  File "/home/user/cuckoo/modules/processing/network.py", line 695, in run
    r = httpreplay.reader.PcapReader(self.pcap_path)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(fp)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/pcap.py", line 115, in __init__
    buf = self.__f.read(FileHdr.__hdr_len__)
AttributeError: 'str' object has no attribute 'read'

HTTPReplay is installed in version 0.1.15
Any idea how to fix this? I'd like to see the full network analysis :(

**Comment by jbremer** [comment]
Assuming you're running Cuckoo `2.0-rc1`, you'll have to use the httpreplay version that's specified in `requirements.txt`. Not the latest one.

**Comment by alabiana** [comment]
> HTTPReplay is installed in version 0.1.15

This is the version wich is specified in the requirements.txt
Are there any other permissions to set or groups like for tcpdump?

**Comment by jbremer** [comment]
Following is a link to `requirements.txt` as per `2.0-rc1`, https://github.com/cuckoosandbox/cuckoo/blob/2.0-rc1/requirements.txt#L11, stating `0.1.5`, not `0.1.15`, is required :-)
Regardless, I just pushed `0.1.16a1` which should be backwards compatible with Cuckoo `2.0-rc1`, could you please give that version a try - `pip install httpreplay==0.1.16a1`. Thanks!

**Comment by jbremer** [comment]
You're not the first person to come with this error, hence my attempt to fix it altogether.

**Comment by jbremer** [comment]
After confirmation that the new release fixes the issue, I've pushed httpreplay `0.1.16`, so that people will no longer run into this issue in the future. Please upgrade @alabiana to the latest and you should be good to go.

**Comment by jbremer** [comment]
Meh, I pushed `0.1.16` from the wrong Git `HEAD`, so now it contains the same as `0.1.15` rather than `0.1.16a1`. Pushed `0.1.17` which contains the correct up-to-date httpreplay package.
