### ISSUE TITLE
Error after installing Python requirements and running cuckoo.py. AttributeError: 'CompiledFFI' object has no attribute 'def_extern'

### ISSUE THREAD

**Issue by roxy9990** [cuckoosandbox/cuckoo#1127]
Hi there,

I followed the instructions here (http://docs.cuckoosandbox.org/en/latest/installation/host/requirements/) to install Cuckoo's requirements. I am seeing the error below after installing the requirements and running cuckoo.py. Do you have any ideas on how I can fix this please?

Thanks in advance for any help.

`scramble@scramble-HP-Z400-Workstation:~/cuckoo$ sudo -H pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): alembic==0.8.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): cffi==1.2.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Collecting chardet==2.3.0 (from -r requirements.txt (line 4))
  Downloading chardet-2.3.0.tar.gz (164kB)
    100% |████████████████████████████████| 174kB 1.3MB/s 
Collecting cryptography (from -r requirements.txt (line 5))
  Downloading cryptography-1.5.2.tar.gz (400kB)
    100% |████████████████████████████████| 409kB 992kB/s 
Collecting Django==1.8.4 (from -r requirements.txt (line 6))
  Downloading Django-1.8.4-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 177kB/s 
Collecting dpkt==1.8.6.2 (from -r requirements.txt (line 7))
  Downloading dpkt-1.8.6.2-py2.py3-none-any.whl (100kB)
    100% |████████████████████████████████| 102kB 1.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.0.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Collecting Flask==0.10.1 (from -r requirements.txt (line 10))
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 552kB 973kB/s 
Collecting HTTPReplay==0.1.5 (from -r requirements.txt (line 11))
  Downloading HTTPReplay-0.1.5.tar.gz
Collecting idna==2.0 (from -r requirements.txt (line 12))
  Downloading idna-2.0-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 1.8MB/s 
Requirement already satisfied (use --upgrade to upgrade): ipaddress==1.0.14 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Collecting itsdangerous==0.24 (from -r requirements.txt (line 14))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 351kB/s 
Collecting Jinja2==2.8 (from -r requirements.txt (line 15))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 1.4MB/s 
Collecting jsbeautifier==1.5.10 (from -r requirements.txt (line 16))
  Downloading jsbeautifier-1.5.10.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 2.4MB/s 
Requirement already satisfied (use --upgrade to upgrade): Mako==1.0.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Collecting ndg-httpsclient==0.4.0 (from -r requirements.txt (line 19))
  Downloading ndg_httpsclient-0.4.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pefile from http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): pyasn1==0.1.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): pycparser==2.14 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22))
Collecting pymongo==3.0.3 (from -r requirements.txt (line 23))
  Downloading pymongo-3.0.3.tar.gz (419kB)
    100% |████████████████████████████████| 419kB 1.0MB/s 
Collecting pyOpenSSL==0.15.1 (from -r requirements.txt (line 24))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
    100% |████████████████████████████████| 112kB 1.3MB/s 
Collecting python-dateutil==2.4.2 (from -r requirements.txt (line 25))
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 1.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): python-editor==0.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 26))
Collecting python-magic==0.4.6 (from -r requirements.txt (line 27))
  Downloading python-magic-0.4.6.tar.gz
Collecting requests==2.7.0 (from -r requirements.txt (line 28))
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 965kB/s 
Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy==1.0.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): tlslite-ng==0.6.0-alpha3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 31))
Collecting wakeonlan==0.2.2 (from -r requirements.txt (line 32))
  Downloading wakeonlan-0.2.2.tar.gz
Collecting Werkzeug==0.10.4 (from -r requirements.txt (line 33))
  Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB)
    100% |████████████████████████████████| 296kB 1.1MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/dist-packages (from pefile->-r requirements.txt (line 20))
Building wheels for collected packages: chardet, cryptography, Flask, HTTPReplay, itsdangerous, jsbeautifier, ndg-httpsclient, pymongo, python-magic, wakeonlan
  Running setup.py bdist_wheel for chardet ... done
  Stored in directory: /root/.cache/pip/wheels/28/8c/bf/a69199bd4901d84e13362f95a9ea7bc9a691fed2d655a90bc4
  Running setup.py bdist_wheel for cryptography ... done
  Stored in directory: /root/.cache/pip/wheels/2a/ac/9b/ca4a3a6e2c17459ead35ee3bb7b4c26774bd386b5b0057cc18
  Running setup.py bdist_wheel for Flask ... done
  Stored in directory: /root/.cache/pip/wheels/b6/09/65/5fcf16f74f334a215447c26769e291c41883862fe0dc7c1430
  Running setup.py bdist_wheel for HTTPReplay ... done
  Stored in directory: /root/.cache/pip/wheels/b8/97/b1/774f8717475cace0bdfa6cd81222f31447904014b7409021b1
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: /root/.cache/pip/wheels/fc/a8/66/24d655233c757e178d45dea2de22a04c6d92766abfb741129a
  Running setup.py bdist_wheel for jsbeautifier ... done
  Stored in directory: /root/.cache/pip/wheels/17/e4/b5/3ceaab61763f82fb22743db8ec21de74b2ee57eeaaf9fd0f6d
  Running setup.py bdist_wheel for ndg-httpsclient ... done
  Stored in directory: /root/.cache/pip/wheels/c9/88/f1/348d5ec506bef5a2a8351243028289a7bb9513b8dd8bbf1c14
  Running setup.py bdist_wheel for pymongo ... done
  Stored in directory: /root/.cache/pip/wheels/ae/a4/25/8a17a59744913feb97e5eaed646050c2579550760b22af6986
  Running setup.py bdist_wheel for python-magic ... done
  Stored in directory: /root/.cache/pip/wheels/61/3c/59/27eacd1e57b0bb379873e5b46c7128b1f9f61fe50d6969301f
  Running setup.py bdist_wheel for wakeonlan ... done
  Stored in directory: /root/.cache/pip/wheels/03/51/b3/f939c3d64694e24ec8b5f770fc3358cdfa68dea6dfd7dbf9db
Successfully built chardet cryptography Flask HTTPReplay itsdangerous jsbeautifier ndg-httpsclient pymongo python-magic wakeonlan
Installing collected packages: chardet, idna, cryptography, Django, dpkt, Werkzeug, Jinja2, itsdangerous, Flask, HTTPReplay, jsbeautifier, pyOpenSSL, ndg-httpsclient, pymongo, python-dateutil, python-magic, requests, wakeonlan
  Found existing installation: Django 1.9.6
    Uninstalling Django-1.9.6:
      Successfully uninstalled Django-1.9.6
  Found existing installation: dpkt 1.8.7
    Uninstalling dpkt-1.8.7:
      Successfully uninstalled dpkt-1.8.7
  Found existing installation: HTTPReplay 0.1.15
    Uninstalling HTTPReplay-0.1.15:
      Successfully uninstalled HTTPReplay-0.1.15
  Found existing installation: pymongo 3.2.2
    Uninstalling pymongo-3.2.2:
      Successfully uninstalled pymongo-3.2.2
  Found existing installation: python-dateutil 2.5.3
    Uninstalling python-dateutil-2.5.3:
      Successfully uninstalled python-dateutil-2.5.3
  Found existing installation: requests 2.11.1
    Uninstalling requests-2.11.1:
      Successfully uninstalled requests-2.11.1
Successfully installed Django-1.8.4 Flask-0.10.1 HTTPReplay-0.1.5 Jinja2-2.8 Werkzeug-0.10.4 chardet-2.3.0 cryptography-1.5.2 dpkt-1.8.6.2 idna-2.0 itsdangerous-0.24 jsbeautifier-1.5.10 ndg-httpsclient-0.4.0 pyOpenSSL-0.15.1 pymongo-3.0.3 python-dateutil-2.4.2 python-magic-0.4.6 requests-2.7.0 wakeonlan-0.2.2

scramble@scramble-HP-Z400-Workstation:~/cuckoo$ python2.7 cuckoo.py 
Traceback (most recent call last):
  File "cuckoo.py", line 18, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/home/scramble/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/home/scramble/cuckoo/lib/cuckoo/core/guest.py", line 11, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/**init**.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/**init**.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 87, in <module>
    error=-1)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 76, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
`

**Comment by jbremer** [comment]
Which operating system and version are you running on? Did you try updating/upgrading the `apt` packages etc? Sounds like some outdated stuff out of our reach to me.

**Comment by opexxx** [comment]
sudo easy_install -U cffi

**Comment by jbremer** [comment]
Indeed, looks like an older version. Please update or do as @opexxx mentioned.
