### ISSUE TITLE
utils/submit.py fails on non-ascii files when executed non-interactively

### ISSUE THREAD

**Issue by h3x2b** [cuckoosandbox/cuckoo#1134]
utils/submit.py fails on non-ascii files when executed non-interactively.

This seems to be based rather on python feature that the default io encoding seems to be ascii when running in non-interactive mode. If you run submit.py with non-ascii filename (like russian azbuka) it will fail on the string conversions although in the code it is explicitly declaring the strings as unicode.

**This can possibly affect also some other cuckoo python code** which is running non-interactively without terminal. If running non-interactively, it seems that discrepancy between stdin and stdout encoding is causing some really strange issues.

The only workaround I have found is to set the **PYTHONIOENCODING=utf8**
Just setting the " -_\- coding: utf-8 -_-" in the python script doesn't seem to be enough.

Testcase 01:

```
cuckoo$ unset PYTHONIOENCODING

cuckoo$ echo -n "копии.js" |xxd
00000000: d0ba d0be d0bf d0b8 d0b8 2e6a 73         ...........js
cuckoo$ FILENAME=`echo -e '\xd0\xba\xd0\xbe\xd0\xbf\xd0\xb8\xd0\xb8\x2e\x6a\x73'`
cuckoo$ echo "$FILENAME"
cuckoo$ echo "alert(1);" > "$FILENAME"
cuckoo$ ls -l "$FILENAME"
-rw-rw-r--. 1 cuckoo cuckoo 10 Oct 20 00:37 копии.js
cuckoo$ /opt/cuckoo/utils/submit.py "$FILENAME"
Success: File "/home/cuckoo/копии.js" added as task with ID 30
cuckoo$ RESULT=`/opt/cuckoo/utils/submit.py "$FILENAME"`
Traceback (most recent call last):
  File "/opt/cuckoo/utils/submit.py", line 253, in <module>
    main()
  File "/opt/cuckoo/utils/submit.py", line 248, in main
    print(bold(green(u"Success")) + u": File \"{0}\" added as task with ID {1}".format(to_unicode(file_path), task_id))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 45-49: ordinal not in range(128)
cuckoo$ export PYTHONIOENCODING=utf-8
cuckoo$ RESULT=`/opt/cuckoo/utils/submit.py "$FILENAME"`
cuckoo$ echo "$RESULT"
Success: File "/home/cuckoo/копии.js" added as task with ID 32
```

Testcase 02:

```
cuckoo$ unset PYTHONIOENCODING
cuckoo$ #interactive execution - seems to be OK
cuckoo$ python -c 'import sys; print "Encoding: {0}".format(sys.stdout.encoding);'
Encoding: UTF-8
cuckoo$ python -c 'import sys; print "Encoding: {0}".format(sys.stdin.encoding);'
Encoding: UTF-8
cuckoo$ #non-interactive execution - here there is discrepancy between stdout and stdin
cuckoo$ RESULT=`python -c 'import sys; print "Encoding: {0}".format(sys.stdout.encoding);' ` ; echo "$RESULT"
Encoding: None
cuckoo$ RESULT=`python -c 'import sys; print "Encoding: {0}".format(sys.stdin.encoding);' ` ; echo "$RESULT"
Encoding: UTF-8
cuckoo$ export PYTHONIOENCODING=utf-8
cuckoo$ RESULT=`python -c 'import sys; print "Encoding: {0}".format(sys.stdout.encoding);' ` ; echo "$RESULT"
Encoding: utf-8
cuckoo$ RESULT=`python -c 'import sys; print "Encoding: {0}".format(sys.stdin.encoding);' ` ; echo "$RESULT"
Encoding: utf-8
```

**Comment by h3x2b** [comment]
![python_01](https://cloud.githubusercontent.com/assets/22624991/19541102/2a25ea10-9664-11e6-9c02-415a32346cb1.png)
![python_02](https://cloud.githubusercontent.com/assets/22624991/19541101/2a24df8a-9664-11e6-8f2e-fca1faf7bd1a.png)

**Comment by jbremer** [comment]
Thanks for pointing out these unicode issues. We've had some unicode issues in the past, but I imagine some have been re-introduced at some point. I'll be fixing this as part of #863 where we can properly unit test it to ensure it remains working later on. Sorry for the inconvenience.
I know it probably isn't what you want, but for now you can always rename the file to something ASCII compliant and use it like that.

**Comment by jbremer** [comment]
This has now been tested pretty thoroughly and should work out of the box in our upcoming alpha or stable release. Please stay tuned and upgrade once we bring out the next version!
Going to close this issue as resolved, but do let us know if you run into additional issues in the future.
