### ISSUE TITLE
"pip install m2crypto" and "apt-get install python-m2crypto"

### ISSUE THREAD

**Issue by CheHaoKang** [cuckoosandbox/cuckoo#1137]
Dear all,

My cuckoo branch is **2.0-dev** and the top commit is **657a5166d711135ee6159c8d0abc599d56d294fe**.
[Commit pic](http://i.imgur.com/DwmJuzG.png)

I encountered "**You do not have the m2crypto library installed preventing certificate extraction: pip install m2crypto**"
[Screenshot](http://i.imgur.com/NZ0dbn5.png)

I tried "**sudo -H pip install m2crypto**" but it was **not working**.
(it is installed under "/usr/**local**/lib/python2.7/dist-packages")

However, when I used "**sudo apt-get install python-m2crypto**", it **WORKS**.
(it is installed under /usr/lib/python2.7/dist-packages)

I typed "**pip list**" and the above two both can be seen.
**I am just wondering what the differences are between the two different commands?**

Thanks,
Kang

**Comment by hsheep** [comment]
me too :(
os: win7 32bit cn
env: office 2003 cn

**Comment by jbremer** [comment]
Thanks for reporting. It could be pip's `m2crypto` is more recent than apt's. I'll have to investigate if any changes are required etc etc.

**Comment by jbremer** [comment]
After some investigations it appears that the most recent supported version of `m2crypto` (for us) is version `0.24.0`. I've added some documentation and other goodies around this in the `package` branch. See also https://github.com/cuckoosandbox/cuckoo/commit/328e9b694ea2442495379b9aadf3319661be3384. Closing this issue as resolved. Note that currently this has only been tested on Linux.
