### ISSUE TITLE
Error getting access to process 5!

### ISSUE THREAD

**Issue by Waffles-2** [cuckoosandbox/cuckoo#1143]
Hi all,

So when running cuckoo all works fine until I try and change the agent.py file to agent.pyw to attempt to have the file run silently in the background, when I do this I get the error "Error getting access to process 5"

Also UAC is disabled and I am running it as an admin.

**Comment by jbremer** [comment]
And if you change it back, the error goes away? Are you sure you ran the Cuckoo Agent as `Administrator`?

**Comment by jbremer** [comment]
As mentioned above, have to run it as Administrator. Improving this situation is on the todo list, but already covered in other tickets, and hence closing this issue. Thanks.
