### ISSUE TITLE
Issue regarding cuckoo sandbox producing json report having garbage values

### ISSUE THREAD

**Issue by MxResearch** [cuckoosandbox/cuckoo#1144]
Hi,

I have query  regarding why cuckoo sandbox is producing json report having garbage values? The file size is 221MB , upper contents of file are readable but I start getting  garbage data in between or later part of the file. My notepad ++ editor also takes lots of time to display this content and even makes my system stuck for some time.  Can anyone help on this issue ?

Regards

**Comment by jbremer** [comment]
First of all, which version of Cuckoo are you using? And could you share the analysis with us?

**Comment by MxResearch** [comment]
Yes sure link for json file: https://www.dropbox.com/s/gcdrknj5rkmmhm5/report.json?dl=0 , and Version is cuckoo 2.0 developer. Kindly suggest me that whether it is problem while cuckoo generating reports because other json files are in readable format so not able to understand why this particaluar file is showing garbage values?

**Comment by jbremer** [comment]
I meant the entire analysis, not just the JSON report ;-)

**Comment by MxResearch** [comment]
Sorry this question might sound like a goon, but do you want the entire folder cuckoo generates after analysis ? If that is the case I will upload it tommorrow.

**Comment by jbremer** [comment]
No worries about that, and yes please.

**Comment by MxResearch** [comment]
Hi @jbremer ,

I need to re-check again cuckoo generated files because some times the json file takes too long to open  and show garbage values(as per link given)  , otherwise the contents of same file are getting loaded correctly. I will let you know once I re-check the issue.

Thanks for your support.

**Comment by jbremer** [comment]
Any update here?

**Comment by MxResearch** [comment]
Hi @jbremer , sorry for the delay in my response , I got busy with other work for now I am closing the issue and come back to you as soon as I get any update on this one.

Thanks
