### ISSUE TITLE
VBoxManage exited with error restoring the machine's snapshot

### ISSUE THREAD

**Issue by gongqihunan** [cuckoosandbox/cuckoo#1145]
After submitting the sample for analysis I am getting below error. 
I don't know how to solve this problem

![wxid_0bkhlb7mo0au22_1477621246008_11](https://cloud.githubusercontent.com/assets/18669930/19791943/3ceb0334-9cf8-11e6-877b-4d00a027dfc7.png)

**Comment by gongqihunan** [comment]
Could any one help me thanks indeed

**Comment by doomedraven** [comment]
Looks like you vm snapshot was taken in incorrect strate, in which state it was done?

**Comment by gongqihunan** [comment]
I forgot install my Agent!! but after i install the agent,i find the problem still exists
![1](https://cloud.githubusercontent.com/assets/18669930/19796674/a86f34ac-9d18-11e6-9a3b-ff1d84130fa7.png)

**Comment by doomedraven** [comment]
is because your snapshot taken in incorrect state, see documentation

**Comment by gongqihunan** [comment]
I flIowed the documentation and  checked my snapshot and my vm .they are OK`````
![2](https://cloud.githubusercontent.com/assets/18669930/19800178/21ee8652-9d2d-11e6-84f6-e5205590b165.png)

**Comment by doomedraven** [comment]
can you start vm manually and do `curl vm_ip:8000` it should give error 50x, means connection works, also which version of vbox, cuckoo used?

**Comment by gongqihunan** [comment]
![3](https://cloud.githubusercontent.com/assets/18669930/19801181/b40e9f4c-9d30-11e6-94cc-505d273cd5d7.png)
I get 501.

Cuckoo Sandbox 2.0-rc1
![5](https://cloud.githubusercontent.com/assets/18669930/19801186/b75655c8-9d30-11e6-86b0-6248ad8ee571.png)

**Comment by doomedraven** [comment]
* 2 things,
* 1 - rc1 contains a lot of bugs, use better dev version(master branch)
* 2 - your vbox is very very old

**Comment by gongqihunan** [comment]
oh.....  thanks indeed. I will update my vbox.But I cann't connect to cuckoosandbox.org .
Could you provide the resources?

**Comment by doomedraven** [comment]
you don't need connect there, just clone this repo

**Comment by jbremer** [comment]
And you can successfully run/start the VM manually?

**Comment by jbremer** [comment]
Oh, wow, VirtualBox 4.1.44 :D

**Comment by gongqihunan** [comment]
thanks~~ now,after updated to 2.0-dev and VirtualBox5.x。I solved the problem。but i get a now one T-T.
when I use sudo to run . IT tell me 
![1](https://cloud.githubusercontent.com/assets/18669930/19843226/30ed7912-9f5b-11e6-91dc-8132052dee21.png)
when I don't use sudo to run .It tell me 
![2](https://cloud.githubusercontent.com/assets/18669930/19843248/57595602-9f5b-11e6-8e8d-307a61f2ee56.png)
this is under /tmp. It doesn't work to try "chmod 777 -R /tmp"
...........

**Comment by doomedraven** [comment]
As first error said, you have problem with snapshot

Dont run as root, create for example cuckoo user and run all cuckoo related scripts under that user

**Comment by gongqihunan** [comment]
oh.. It's ok.happy Halloween~ I would like to learn cuckoo for adaptation to sandbox related to the javascript .Is there have discussion group for using cuckoo ?like ISC or QQ?

**Comment by doomedraven** [comment]
#cuckoosandbox on irc, on freenode

but about usage, read the documentation first ;)

**Comment by gongqihunan** [comment]
;)

**Comment by vhari96** [comment]
Did you found any solution for this? @ariansvirsky

**Comment by ariansvirsky** [comment]
yes, it was an issue with the snapshot names.

**Comment by vhari96** [comment]
But my snapshot name is snapshot1 itself. But i'm still facing this issue. Please help me to get out of this issue @ariansvirsky 
Also, if possible please provide your troubleshoot steps
