### ISSUE TITLE
VBoxManage permission denied error

### ISSUE THREAD

**Issue by arulraji** [cuckoosandbox/cuckoo#1148]
arul-3530@arul-3530:/opt/cuckoo$ python cuckoo.py 

                     _ 
    ____ _   _  ____| |  _ ___   ___
   / ___) | | |/ ___) |_/ ) _ \ / _ \
  ( (___| |_| ( (___|  _ ( |_| | |_| |
   \____)____/ \____)_| \_)___/ \___/

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 You are running a development version! Current stable is 2.0-rc1.
2016-10-31 21:13:43,330 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2016-10-31 21:13:43,373 [lib.cuckoo.core.scheduler] INFO: Machinery name : virtualbox 
2016-10-31 21:13:43,397 [root] CRITICAL: CuckooCriticalError: Error initializing machines: VBoxManage error listing installed machines: [Errno 13] Permission denied

please help anyone i got stuck with this permission denied error

**Comment by Ads5740** [comment]
Is your user part of the VBoxManage group? For example:

_If you’re using VirtualBox, make sure the new user belongs to the “vboxusers” group (or the group you used to run VirtualBox):

$ sudo usermod -a -G vboxusers cuckoo_

**Comment by gongqihunan** [comment]
I think you should change your cuckoo version fisrtly for 2.0-rc1 have many bugs.  2.0-dev

**Comment by jbremer** [comment]
Did you run any virtualbox-related commands with `sudo`? If so, you should probably remove all of those and create some new VMs.

**Comment by arulraji** [comment]
Thanks @Ads5740 & @gongqihunan 

Problem solved by changing version from 2.0-dev to 2.0-rc1 and also small VBoxManage configuration mistake in virtualbox.conf file.

**Comment by jbremer** [comment]
Ok. Although I guess `2.0-dev` should work just as fine with the configuration mistake resolved. Closing as resolved.
