### ISSUE TITLE
After I submit the file,My VBox's start button blinks.but cuckoos can't work

### ISSUE THREAD

**Issue by gongqihunan** [cuckoosandbox/cuckoo#1150]
Do other people have the same problems?
![d7b4 tm](https://cloud.githubusercontent.com/assets/18669930/19880775/197f7d6c-a03b-11e6-8f70-b80e4d36701b.png)
![d7b5 tm](https://cloud.githubusercontent.com/assets/18669930/19880774/197f38fc-a03b-11e6-85f6-2b1e92b229db.png)
my vbox isn't broken. ...
It is that can't change my vbox's state. I try to update my snapshot but it doesn't work

**Comment by jbremer** [comment]
Manually starting the VM works properly?

**Comment by gongqihunan** [comment]
yes

**Comment by gongqihunan** [comment]
![727 tm](https://cloud.githubusercontent.com/assets/18669930/19893396/007df58e-a084-11e6-8f3f-88202b0edaa5.png)

**Comment by gongqihunan** [comment]
yes I make a poweroff snapshot

**Comment by doomedraven** [comment]
it must be runned

**Comment by gongqihunan** [comment]
ah...I'm sure it's a poweroff snapshot.and I follow the 2.0-dev docs. reinstall cuckoo and VM. get the same problem....

**Comment by doomedraven** [comment]
can you point where in doc it said it must be shutoff? :)

**Comment by jbremer** [comment]
Yes, as @doomedraven said, you must create a snapshot while the VM is running. Closing as resolved, please follow the docs more closely.
