### ISSUE TITLE
Cuckoo static anlysis of Office documents does not display VBA macros

### ISSUE THREAD

**Issue by ronbarrey** [cuckoosandbox/cuckoo#1153]
The for loop is iterating over:

`{% for office in analysis.static.office %}`

It should iterate over:

`{% for macro in analysis.static.office.macros %}`

Then replace any references to the 'office' variable with 'macro'. The changes will then display the original and deobfuscated macros in the static analysis main tab.

**Comment by jbremer** [comment]
That's a few commit references too many, but it's fixed now, thanks for reporting! Also finished off some web interface unit testing so to make a start on making it easier to locate such bugs in the future.
