### ISSUE TITLE
Bug in baseline-reporting?

### ISSUE THREAD

**Issue by alabiana** [cuckoosandbox/cuckoo#1158]
Hey,

tried to create a baseline report with the submit.py as follows:
`./submit.py --machine cuckoo.win7a --baseline`

Are there any other option i have to set. the json of the report ist nearly empty:
`{
    "memory": {}
}`

I realy need the baseline for representative reports. Or is this function not fully implemented yet?

Thanks for help.

**Comment by alabiana** [comment]
> I realy need the baseline for representative reports. Or is this function not fully implemented yet?

@jbremer

**Comment by jbremer** [comment]
As-is the baseline feature is limited in its coverage - it's only focussing on volatility output right now (iirc). As you can imagine, you do have to enable the volatility plugin etc for that to work.
What's your goal? Perhaps there's a new feature request in there that we could add to our roadmap.

**Comment by alabiana** [comment]
My goal is, to see in an analysis only the anomalies created by the sample. 
Example: I upload a sample java file which echo "hello world" and exit i should only see the execution created by this java file.
This would be my understanding of using the baseline report....

**Comment by jbremer** [comment]
Yes, that's exactly the goal for baseline. However, at this point it's still quite limited - namely to the volatility output. This functionality is most certainly on our todo list, but keep in mind that it requires a lot of development work and as such we need to allocate resources for such work on our side ;-)

**Comment by alabiana** [comment]
No stress :+1: only want to know the reason for the empty file.
