### ISSUE TITLE
Installer files with license agreement tickboxes confuse Cuckoo. Stuck in a loop.

### ISSUE THREAD

**Issue by binsec** [cuckoosandbox/cuckoo#1160]
I noticed that Cuckoo has the ability to click "Next", "Next" to automate an install file. Cool.

However, when a license agreement "Tickbox" is required before clicking "Next" ... Cuckoo seems to get stuck in a loop.

Cuckoo can click a tickbox no problem, but it unclicks it before clicking next... resulting in a loop and the installation never finishes. It just keeps clicking and unclicking the tickbox. 

Maybe a timing or logic error ? One example file was a NotePad++ v7.0 MSI installer file, I get the same result with other similar MSI files as well.

VM - Win 7, IE10, "Simulated Human Interaction" enabled, no other Cuckoo options selected.

Demo file: https://www.hass.de/files/nodes/story/45/npp.7.0.0.installer.x86.msi

**Comment by jbremer** [comment]
For `.msi` files probably the easiest would be to add a command-line parameter like `/quiet` (I don't recall the exact one) for automated installation, rather than trying to properly fill out a tickbox. What do you think?

**Comment by jbremer** [comment]
Going to close this issue. Analyzing `notepad++` is not one of our main objectives and there's only so much malware that requires manual interaction as described above.
