### ISSUE TITLE
Elasticsearch and Recent Files/URLS

### ISSUE THREAD

**Issue by gra55h0pp3r** [cuckoosandbox/cuckoo#1162]
I've installed cuckoo and using vmware workstation, but what I noticed is the web interface displays maybe 50 or so recent submitted files. I tried enabling elasticssearch, so I could search by a hash to find an older analysis, but it doesn't work.

What can I do to get elasticsearch working and to allow people to search for hash, filenames, text, and etc... For example, we have over 100+ files submitted for analysis, but the analyst is unable to see analysis 1-50 results, but unable to find search by hash, so they resubmit the files over even though the file was already analyzed.

**Comment by razuz** [comment]
if you just want to grow listing for main page then 50 limit is there :
https://github.com/cuckoosandbox/cuckoo/blob/master/web/analysis/views.py#L41-L42

ref ES:
can you validate if you have results in ES aswell already ? cause if you enabled it after running analysis then you have to rerun the processing eg `./utils/process.py -r _ID_` for it to become available in ES

**Comment by jbremer** [comment]
In the upcoming Cuckoo Package (#863) this has been resolved with a lazy loading recent page thing, but it's not ready for release yet. Until then you can do as @razuz mentioned by patching the hardcoded limit of 50 analyses.

**Comment by jbremer** [comment]
Closing as it will be resolved by an upcoming release.
