### ISSUE TITLE
Where I can find API categories? 

### ISSUE THREAD

**Issue by g00dv1n** [cuckoosandbox/cuckoo#1163]
Cuckoo use this categories for API calls:
 registry, file, network, process, services, synchronisation

Where I can find list of API functions for each category?

**Comment by jbremer** [comment]
In the source of the Cuckoo Monitor, https://github.com/cuckoosandbox/monitor.

**Comment by codekaust** [comment]
@jbremer can you point to some specific location?
@g00dv1n did you find any list that we can readily use?
