### ISSUE TITLE
Reporting html 

### ISSUE THREAD

**Issue by Quietiger** [cuckoosandbox/cuckoo#1166]
Cuckoo not creating report.html file..

**Comment by doomedraven** [comment]
Logs? Details?

**Comment by Quietiger** [comment]
I am running cuckoo sandbox in Ubuntu 16.04 xenial and it is working fine, when i tested a malware file the report generated with all the events after test in storage folder with ID numbe have all the file including json but it is not creating a html file for the web interface.

later i installed the reporting module where i added nginx and other dependencies and executed api.py file with default port it is still showing page not found error.

**Comment by doomedraven** [comment]
api.py not showing html, you need execute `python manage runserver` from web to see webgui

**Comment by Quietiger** [comment]
did that and did some changes to reporting and localsettings:

and this is error

./manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f3521737a28>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

System check identified 1 issue (0 silenced).

**Comment by doomedraven** [comment]
i think you have missed dependencies

**Comment by doomedraven** [comment]
you also need post version of cuckoo, django, etc

**Comment by Quietiger** [comment]
okay i will re install the system and look for it..thank you

**Comment by doomedraven** [comment]
google also probably can help, but you post too small portions to details to tell you what could be wrong

**Comment by Quietiger** [comment]
sorry for that i will get back back to you once i finish re installing, as i am doing a project where i am connecting Cuckoo with MISP...and i did so many changes to conf files and now i am lost.. i will redo it again carefully.

**Comment by doomedraven** [comment]
see the pulls in this repo, you have my pull req about misp integration which works just fine, and also there already misp recon mpdule in processing, in pull req, it upgrate to be able push back to misp

**Comment by Quietiger** [comment]
okay thank you...

**Comment by Quietiger** [comment]
Hi after installing all the requirements and cuckoo
The error is now this:
**root@mvsgroup-VirtualBox:~/cuckoo/web# ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/cuckoo/web/web/settings.py", line 20, in <module>
    raise Exception("Mongo reporting module is not enabled in cuckoo, aborting!")
Exception: Mongo reporting module is not enabled in cuckoo, aborting!**

i am using this link to setup cuckoo:
http://hacktr.org/2014/11/12/cuckoo-sandbox-installation/

and also i used cuckoo documentation to install requirements.txt contents

**Comment by jbremer** [comment]
Did you read the last sentence?
`** Exception: Mongo reporting module is not enabled in cuckoo, aborting!**`

**Comment by Quietiger** [comment]
yes.. i installed mongo and upgraded it....do i need to install mongodb server?

**Comment by Quietiger** [comment]
i enabled mongo in reporting.conf and encountered a new error:

**root@mvsgroup-VirtualBox:~/cuckoo/web# ./manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fd2a82f7410>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

System check identified 1 issue (0 silenced).**

**Comment by jbremer** [comment]
Which version of `Django` do you have installed? Can you share the output of `pip freeze` with us?

**Comment by Quietiger** [comment]
root@mvsgroup-VirtualBox:~/cuckoo# pip freeze
adium-theme-ubuntu==0.3.4
alembic==0.8.0
beautifulsoup4==4.4.1
bottle==0.12.7
bson==0.4.3
chardet==2.3.0
click==6.6
cybox==2.0.1.4
Django==1.10.2
dpkt==1.8
dumbnet==1.12
Flask==0.11.1
itsdangerous==0.24
Jinja2==2.8
libvirt-python==1.3.1
lxml==3.6.4
maec==4.0.1.0
Magic-file-extensions==0.2
Mako==1.0.1
MarkupSafe==0.23
pefile==1.2.10.post139
pycparser==2.14
pydeep==0.4
pymongo==3.3.1
python-dateutil==2.5.3
python-editor==0.3
pytz==2016.7
requests==2.11.1
six==1.10.0
SQLAlchemy==1.0.8
unity-lens-photos==1.0
vboxapi==1.0
Werkzeug==0.11.11
XenAPI==1.2
yara-python==3.1

**Comment by jbremer** [comment]
As per `requirements.txt` we don't support Django version `1.10.2`. Please install the appropriate version - we still have to upgrade to the latest version. Closing as resolved.

**Comment by Quietiger** [comment]
which version should i do....just got the latest but still error?

**Comment by jbremer** [comment]
https://github.com/cuckoosandbox/cuckoo/blob/master/requirements.txt#L6
