### ISSUE TITLE
Connecting to cuckoo api/web server from sandbox?

### ISSUE THREAD

**Issue by dperrie20** [cuckoosandbox/cuckoo#1167]
Is there a way from inside a sandbox to communicate with the cuckoo api running on the host or access the web server?

Whenever I try to access the web server from the sandbox I get "Connection has been Reset" and in the terminal "CRITICAL: ResultServer unable to map ip to context: 192.168.56.8" and when I try to connect to Cuckoo REST API server I get connection refused.

**Comment by jbremer** [comment]
Well, depends on the ip:port that you make api/web listen. If it's localhost or a subnet other than what's used for your VMs, they naturally won't be able to reach it.

**Comment by dperrie20** [comment]
Thanks, what ip/port would you suggest hosting the api on?

**Comment by jbremer** [comment]
Well, normally you don't want the VM to be able to reach the API/Web, so I'd keep it as-is ;-)

**Comment by dperrie20** [comment]
Haha I know I know :p I am trying to push samples from a VM into cuckoo that is on the host. Is there a way to make it so that the VM can reach the API?

**Comment by jbremer** [comment]
Assuming VirtualBox you could give your VM a special `hostonly` adapter, e.g., `vboxnet1` with the `192.168.57.0/24` subnet. Then connecting to `192.168.57.1:8090` from that VM should reach the API if the API binds to `192.168.57.1:8090` on the host.
You can of course also simply listen on `0.0.0.0:8090`, but then the analysis VMs can probably also reach it.

**Comment by dperrie20** [comment]
yeah, I tried something along those lines earlier but was running into a problem. The error being: "socket.error: [Errno 49] Can't assign requested address"

**Comment by jbremer** [comment]
Then you don't have the correct hostonly subnets up and running. Closing as resolved though, this is not a Cuckoo related issue.

**Comment by dperrie20** [comment]
Okay, thanks for your help! Much appreciated!
