### ISSUE TITLE
Libvirt vm.state call does not return (runs infinitely)

### ISSUE THREAD

**Issue by wattad169** [cuckoosandbox/cuckoo#1174]
Hi,
I'm using ESX as machinery module and I have a very strange behavior.
Sometimes I notice that all guest machines are in "paused" state.
While debugging I figured out that the last call that cuckoo nest does is the following :
self.vms[label].state(flags=0) call in lib/cuckoo/common/abstracts.py (line 485).
These call may run infinitely and during the infinite run the network analyzer keeps sniffing the network that leads to create a huge pcap file.

**Comment by jbremer** [comment]
Sounds like your VM is somehow corrupt and as such doesn't boot / resume properly. Could you share any debug logs? I don't have an ESX setup myself so I can't help much directly on that front, unfortunately.

**Comment by wattad169** [comment]
Thank you :_, 
I replaced my VM's and it's better now.
However, do you agree with me that it's better to wrap this call (self.vms[label].state(flags=0)) with timeout if it's not available in libvirt API ?

**Comment by KillerInstinct** [comment]
Try using the vSphere machinery. It's considerably better than the libvirt esx implementation.

**Comment by jbremer** [comment]
Please feel free to do a PR @wattad169, as I'm not using ESX myself I can't judge on that, but I'm sure there will be some users that can better inform me about that before merging ;-) Closing this issue as resolved as @KillerInstinct also provided a good workaround.
