### ISSUE TITLE
No screenshots

### ISSUE THREAD

**Issue by gokumatrix** [cuckoosandbox/cuckoo#1179]
I apologize if this is written somewhere but I looked around in the issues/readme and couldn't find anything.

Cuckoo runs perfectly except it will not take screenshots. Do I need to move screenshots.py to the guest VM or something, or is there a setting in a .conf I missed to turn it on? I tried running it with --debug but I didn't see an error saying it was trying to take them and couldn't. If I can provide more information to help diagnose what's going on, just let me know.

Thank you!

**Comment by doomedraven** [comment]
did you installed it in vm? http://docs.cuckoosandbox.org/en/latest/installation/guest/requirements/

**Comment by gokumatrix** [comment]
yes, PIL is installed in the VM. I have my cuckoo box running in Vsphere and a Windows 7 box running inside virtualbox within the cuckoo machine.

**Comment by gokumatrix** [comment]
Actually, 2.7 Pillow is installed, not PIL.
