### ISSUE TITLE
cuckoo.py --clean should clean the ES instance too

### ISSUE THREAD

**Issue by keithjjones** [cuckoosandbox/cuckoo#1183]
If not, old data is left in the ES server.  Right now, it has to be cleaned by hand with a:

```
curl -X DELETE ESHOST:9200/cuckoo-2016 
```

**Comment by swackhamer** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/1120 is a PR that provides that functionality.

**Comment by jbremer** [comment]
Will close this issue as it's being handled as part of #1196 (which is superior to #1120). Merging that PR hopefully sooner rather than later. Thanks!
