### ISSUE TITLE
Failing to Submit Url from Distributed API

### ISSUE THREAD

**Issue by prats84** [cuckoosandbox/cuckoo#1185]
Unable to Submit a Url using the Distributed Restful api - api/task (curl localhost:9003/api/task -F file=@<filename>). The api cuckoo/distributed/distributed/views/api.py only checks for Files names and nothing for URLs.

**Comment by jbremer** [comment]
Feel free to submit a PR to handle this :-)

**Comment by jbremer** [comment]
Please note that - where possible - some unit tests would be useful, as this changes (in a good way) some core principals of Distributed Cuckoo.

**Comment by jbremer** [comment]
Closing as duplicate of #1232 (or the other way around, but that issue is a little bit more active).
Please, if you have the time to PR this functionality, do let me know ;-)

**Comment by prats84** [comment]
I will be working on this feature from April 2nd week.
