### ISSUE TITLE
enabling malheur in cuckoo 

### ISSUE THREAD

**Issue by ikennarene** [cuckoosandbox/cuckoo#1187]
i want to enable malheur in cuckoo, so after analysis i can get cluster result in malheur,  i already enable = yes in cuckoo reporting.conf, but i still not getting result for malheur

**Comment by doomedraven** [comment]
are you sure you use cuckoo v2 and not cuckoo-mod?

**Comment by ikennarene** [comment]
yea, https://cuckoosandbox.org/

**Comment by doomedraven** [comment]
here no code for malheur

Nothing
https://github.com/cuckoosandbox/cuckoo/search?utf8=%E2%9C%93&q=malheur nothing found 

nothing 
https://github.com/cuckoosandbox/cuckoo/blob/master/conf/reporting.conf

**Comment by ikennarene** [comment]
okay, i was wondering if anyone have done it before, saw this 
https://blog.malwarebytes.com/threat-analysis/2015/08/automatic-analysis-using-malheur-and-cuckoo/

**Comment by doomedraven** [comment]
reread it, it point to cuckoo-mod, i have backported it to v2, but it damn slow, and before open issue use search in repo, as there already opened issues about the same

**Comment by doomedraven** [comment]
@jbremer you can close it as it not related to v2

**Comment by ikennarene** [comment]
okay, thanks
