### ISSUE TITLE
unable to analyze a file

### ISSUE THREAD

**Issue by ikennarene** [cuckoosandbox/cuckoo#1189]
just started seeing this error after using cuckoo yesterday and working fine. This happens when i upload a file to analyze or resubmit a file.

ERROR :-(
Error adding task to Cuckoo's database.

**Comment by jbremer** [comment]
Probably your database is not up-to-date anymore for some reason. The easiest would be cleaning it completely and starting from scratch. Also, which version of Cuckoo are you using?

**Comment by jbremer** [comment]
Closing issue for not providing enough information. Let us know if you have more information for us.

**Comment by emilianooddo** [comment]
I have the same problem, after i run the command cuckoo.py --clean, and now the db seems to be corrupted. I tried to delete the db and then i ran the command cuckoo.py, so cuckoo created the new db but the problem is always there. How can I do?

**Comment by doomedraven** [comment]
First of all if you stilll use cuckoo.py, upgrade you using an old version

sudo pip install cuckoo

**Comment by emilianooddo** [comment]
It's not problem of upgrade. I use cuckoo.py because I use cuckoodroid and it don't work with cuckoo 2.0.6, which I have already installed. Before I started the command cuckoo.py --clean, it worked fine.
