### ISSUE TITLE
Issues with starting VMs

### ISSUE THREAD

**Issue by benrau87** [cuckoosandbox/cuckoo#1192]
Probably not the best place for this, but the community page is down for me....
Whenever I start cuckoo it will either shutdown any running VMs in VirtualBox or fail to start them up if they are currently down.
The 'Start'  button in the VirtualBox Manager GUI is evening being activated every second until the timeout is tripped when I launch cuckoo.py
Any ideas what could be causing this? Thanks in advance!

**Comment by doomedraven** [comment]
cuckoo shutdown vms and it correct, is to have then poweroff and ready to be used.
did you take snapshot in running state?

**Comment by benrau87** [comment]
Yes, I did take a snapshot of the machine after installing the agent. It was powered off when I took it.

**Comment by doomedraven** [comment]
why powered off? if documentation says __in running state__

**Comment by benrau87** [comment]
I'll will take a running snapshot later and see if that solves it. Also, if
you don't specify a snapshot in the conf file, will it just use the latest
image?

**Comment by doomedraven** [comment]
yes

**Comment by benrau87** [comment]
Gave that a shot and still have the same issue. I can see that the call to launch the VM is being executed but  it throws back an error of VBoxManage failed starting the machine in HEADLESS mode.

If I try to start the machine with VBoxManage startvm cuckoo1 --type headless, it works fine.

**Comment by benrau87** [comment]
It also goes straight to a status of Aborted if I try launching another submission.

**Comment by jbremer** [comment]
Which version of Cuckoo are you running? Is `virtualbox` configured to `headless` mode in `virtualbox.conf`?

**Comment by benrau87** [comment]
It is configured for headless in the conf file and I have tried it with both 2-0dev and 2.0-rc2

**Comment by benrau87** [comment]
Well I made some headway. I needed libvert-python in order to get things working and needed the libvert-dev package as well. Apparently those aren't dependencies?

**Comment by benrau87** [comment]
So now... I can curl to the agent and can telnet from the agent to the host. No issues with network connections. When I submit a file the snapshot will restore, the machine starts, but nothing happens within the guest. Then I get a timeout error. Perhaps this is an issue pertaining to using Win7x86 as the guest?

**Comment by jbremer** [comment]
If you update to our latest version release you'll find that the error reporting has been much improved for these types of issues. Please give it a spin to see if you can better pinpoint the issues with your setup.
Closing this issue as resolved. Thanks. Feel free to reopen or create a new issue if you do still have questions etc.
