### ISSUE TITLE
Django Debug : You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code. 

### ISSUE THREAD

**Issue by Quietiger** [cuckoosandbox/cuckoo#1193]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8080/analysis/20/

Django Version: 1.8.4
Python Version: 2.7.12
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'analysis',
 'compare')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'web.headers.CuckooHeaders')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py" in inner
  45.             return func(request, *args, **kwargs)
File "/root/cuckoo/web/analysis/views.py" in report
  252.     report = results_db.analysis.find_one({"info.id": int(task_id)}, sort=[("_id", pymongo.DESCENDING)])
File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py" in find_one
  1014.         for result in cursor.limit(-1):
File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py" in next
  1090.         if len(self.__data) or self._refresh():
File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py" in _refresh
  1012.                                        self.__read_concern))
File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py" in __send_message
  850.                                                               **kwargs)
File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py" in _send_message_with_response
  827.             server = topology.select_server(selector)
File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py" in select_server
  210.                                                  address))
File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py" in select_servers
  186.                         self._error_message(selector))

Exception Type: ServerSelectionTimeoutError at /analysis/20/
Exception Value: 127.0.0.1:27017: [Errno 111] Connection refused

**Comment by KillerInstinct** [comment]
Looks like MongoDB is disabled/firewalled or not listening on the correct interface.

**Comment by doomedraven** [comment]
today is faced with the same, all the time, checking mongo log i found `too many open files` so ulimit is your friend https://docs.mongodb.com/manual/reference/ulimit/

**Comment by doomedraven** [comment]
btw after almost 2 days i got another error, and was solved with upgrading to latest mongo https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04

but check mongo log before do something

**Comment by jbremer** [comment]
Closing as resolved, MongoDB probably wasn't running or crashed due to what @doomedraven explained.
