### ISSUE TITLE
Don't require https for Moloch install

### ISSUE THREAD

**Issue by keithjjones** [cuckoosandbox/cuckoo#1198]
Right now moloch is hard coded as an https URL in web/analysis/views.py.  It should be configurable for https or http via the moloch configuration in reporting.conf.

**Comment by SparkyNZL** [comment]
cheers for this :)

**Comment by jbremer** [comment]
@keithjjones' PR has been merged, so closing this issue as resolved. Note that it'll be merged into `package` as well eventually ;-)
