### ISSUE TITLE
Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by gongqihunan** [cuckoosandbox/cuckoo#1206]
ubuntu14.01 and my cuckoo is 2.0-rc2 
, I try to solve the problem follow #611 #545 #572 .But It doesn't work.Cloud anybody help me ?
oh...I'm analyzing a same url  with different result,one is failed and one succeed

**Comment by jbremer** [comment]
A little bit more information, e.g., the sample that you're analyzing, would be helpful ;-)

**Comment by gongqihunan** [comment]
I think because the agent didn't hook the API?
![1481456805 1](https://cloud.githubusercontent.com/assets/18669930/21079878/9a2105c6-bfda-11e6-85f9-8f33ef0f0f08.png)
 
but sometimes, I can analysis success. like this
![1481456950 1](https://cloud.githubusercontent.com/assets/18669930/21079893/f0772cfc-bfda-11e6-87f9-009fb625b7d7.png)

Besides that.. I have a new issue``
![3](https://cloud.githubusercontent.com/assets/18669930/21079907/62b57cba-bfdb-11e6-95e0-cbb5ec03470a.png)

thank you ~ ;-)

**Comment by doomedraven** [comment]
last one is your yara setup issue, google it

**Comment by gongqihunan** [comment]
ok I will try it

**Comment by gongqihunan** [comment]
but the first one still not resolved

**Comment by gongqihunan** [comment]
the reason is the sample is too small, so cuckoo cann't hook him.

**Comment by gongqihunan** [comment]
I solved this. 
Summarized as follows:

1.  Turn off the firewall, turn off security software

2. agent and cuckoo version does not match the use, and sometimes lead to this problem.

3. update your monitor branch
now I closed this comment

**Comment by MirrorFeng** [comment]
hi， I encountered the same problem as you：
**Error: Analysis failed: The package "modules.packages.ie" start function raised an error: Unable to execute the initial process, analysis aborted.**
and in analysis.log:
**2018-04-25 08:35:13,280 [lib.api.process] ERROR: Failed to execute process from path 'C:\\Program Files\\Internet Explorer\\iexplore.exe' with arguments ['bin\\inject-x64.exe', '--app', u'C:\\PROGRA~1\\INTERN~1\\iexplore.exe', '--args', 'www.jd.com', '--apc', '--dll', 'C:\\wjxsjj\\bin\\monitor-x64.dll', '--config', 'c:\\users\\mirror\\appdata\\local\\temp\\tmpn9qul2', '--curdir', u'C:\\Users\\mirror\\AppData\\Local\\Temp', '--maximize'] (Error: The pipe has been ended (ERROR_BROKEN_PIPE))**
Can you help me solve this problem?

**Comment by gongqihunan** [comment]
你好，这个问题是因为你的分析机器没有配置正确。 也就是说 你检查一下你分析机是否关闭了防火墙以及安装分析机的虚拟机是否最新版本。




--
发自我的网易邮箱手机智能版


在 2018-04-25 08:56:03，MirrorFeng <notifications@github.com> 写道：

**Comment by MirrorFeng** [comment]
我的client机是win7系统，已经关闭了防火墙、windows
update、UAC，浏览器的安全检查也关闭了，host机是Ubuntu16.04，已经运行过sudo apt-get update; sudo
apt-get dist-upgrade,不知道还要怎么配置。。。。

2018-04-25 12:08 GMT+08:00 Lucky <notifications@github.com>:

**Comment by MirrorFeng** [comment]
安装虚拟机的virtualbox是5.0版本，这个和virtualbox版本也有关系么？

**Comment by gongqihunan** [comment]
是的，虚拟机virtualbox需要的是最新的版本。






在 2018-04-25 14:30:25，"MirrorFeng" <notifications@github.com> 写道：


安装虚拟机的virtualbox是5.0版本，这个和virtualbox版本也有关系么？
