### ISSUE TITLE
Unable to start Cuckoo

### ISSUE THREAD

**Issue by zwyaniv** [cuckoosandbox/cuckoo#1208]
Hi All.

Im new with Cuckoo Sandbox, im trying to install it on CentOS 7.2, and after i installed and configure everything, in getting the following error : 
Please note that im running it as root from the root directory.

Failed to import '/usr/lib/libyara.so'
PATH = /usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin;/usr/lib
Traceback (most recent call last):
  File "cuckoo.py", line 18, in <module>
    from lib.cuckoo.common.utils import exception_message
  File "/root/cuckoo/lib/cuckoo/common/utils.py", line 26, in <module>
    from lib.cuckoo.common.config import Config
  File "/root/cuckoo/lib/cuckoo/common/config.py", line 11, in <module>
    from lib.cuckoo.common.objects import Dictionary
  File "/root/cuckoo/lib/cuckoo/common/objects.py", line 30, in <module>
    import yara
  File "/usr/lib/python2.7/site-packages/yara-1.7.7-py2.7.egg/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/lib/python2.7/site-packages/yara-1.7.7-py2.7.egg/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/lib/python2.7/site-packages/yara-1.7.7-py2.7.egg/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpcre.so.3: cannot open shared object file: No such file or directory

**Comment by doomedraven** [comment]
You installed yara in wring way, as you have missed core file libyara.so, try google it you have tons of solutions there :)

Best regards
Andriy

**Comment by zwyaniv** [comment]
Thank you, what is the right way to install Yara?

בתאריך 11 בדצמ׳ 2016 6:19 אחה״צ,‏ "doomedraven" <notifications@github.com>
כתב:

**Comment by doomedraven** [comment]
http://yara.readthedocs.io/en/v3.4.0/gettingstarted.html

**Comment by zwyaniv** [comment]
Hi, i have a new problem starting the Cuckoo : 


"ERROR: Missing dependency: No module named requests"

What am i missing now? im running ubuntu 16.04

**Comment by doomedraven** [comment]
read the manual how to install dependencies

**Comment by zwyaniv** [comment]
Ok, so everything is working, beside last part that i cannot get the cuckoo web interface on this 

 
open your web browser and type your host ip and port to access Cuckoo’s web interface. In my case the host had the IP 192.168.59.130 so I accessed http://192.168.59.130:8000 and there it was.

**Comment by zwyaniv** [comment]
When running "python manage.py runserver 0.0.0.0:8000" im getting error: 

Unhandled exception in thread started by <function wrapper at 0xb1a76c6c>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

**Comment by zwyaniv** [comment]
Thank you

בתאריך 13 בדצמ׳ 2016 6:55 אחה״צ,‏ "Jurriaan Bremer" <
notifications@github.com> כתב:

**Comment by zwyaniv** [comment]
Hi again,

I am very very sorry, but i cannot find what is the problem with my
configuration, when i start cuckoo im getting error (screenshot attached).

I have ping beetween the ubunto and vm guest, im running ubunto 16 as host
and win7 as guest.

I will appreciate if you can point me to any solution.

Sorry again for being annoing.

**Comment by doomedraven** [comment]
no screenshot

**Comment by zwyaniv** [comment]
![cuckoo-sandbox](https://cloud.githubusercontent.com/assets/24508942/21178226/38d52efe-c1f7-11e6-935f-d5a1d85178df.jpg)

**Comment by doomedraven** [comment]
looks like snapshot wasn't taken in running state

**Comment by zwyaniv** [comment]
when i try to take snapshot im getting this error 

root@WaterfallRX:/home/cuckoo/cuckoo/conf# sudo vboxmanage snapshot "windows7" take "snapshot1" --pause
VBoxManage: error: Could not find a registered machine named 'windows7'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(bstrMachine.raw(), pMachine.asOutParam())" at line 326 of file VBoxManageSnapshot.cpp
root@WaterfallRX:/home/cuckoo/cuckoo/conf#

**Comment by doomedraven** [comment]
so is not cuckoo error, is vbox error, google it

**Comment by zwyaniv** [comment]
Yes, i think i found the problem, working on fixing it right now.... thank you

**Comment by doomedraven** [comment]
fixed? if yes close it ;)

**Comment by zwyaniv** [comment]
Yes, i fixed it, thank you

**Comment by doomedraven** [comment]
Close this issue ;)

**Comment by zwyaniv** [comment]
Hi Sir,

Hope you are well.

Other questions: is there a way to automatically analyze files that are
getting to a specific folder on the Cuckoo server?

We are sending files from a different server to a specific folder, locate
on the Cuckoo server.

Thank you for your help.
Yaniv z

**Comment by doomedraven** [comment]
Check pull requests cuckoomx can be interesting for you, or write small watchdog script to monitor folder

**Comment by zwyaniv** [comment]
And if I'm writing a watchdog script, it will monitor every new file in the
desired folder?

**Comment by doomedraven** [comment]
yup, https://pypi.python.org/pypi/watchdog

**Comment by zwyaniv** [comment]
Thank you !!!

**Comment by doomedraven** [comment]
you are welcome, so if issues is solved, close it ;)

**Comment by jbremer** [comment]
Closing as resolved.
