### ISSUE TITLE
Some analyses finish without process memory dump (when --enforce-timout is enabled) 

### ISSUE THREAD

**Issue by marklech** [cuckoosandbox/cuckoo#1210]
Hi all, 
 Iv'e noticed that some analyses are accomplished without a process memory dump (while they were submitted with procmemdump=yes and --enforce-timeout is enabled). 
 The weird part is, that without the --enforce-timeout flag the analyses are accomplished with all process memory dumps and often in less time than the value specified in the timeout field. This is really confusing to me. Does someone have an explanation for this?
Mark.

**Comment by KillerInstinct** [comment]
What hypervisor?

**Comment by marklech** [comment]
esx

בתאריך 14 בדצמ' 2016 23:55,‏ "KillerInstinct" <notifications@github.com>
כתב:

**Comment by marklech** [comment]
Ok, so let me restate the problem - 
In all analyses in which --enforce-timeout flag is on I get the process memory dumps partially (that is, only a subset of the proc. mem. dumps finds it's way to the final report) . The weird part is, that without this flag the analyses are accomplished with all process memory dumps and sometimes in less time than the value specified in the timeout field. This is really confusing to me. Does someone have an explanation for this?

**Comment by jbremer** [comment]
Bit late, but probably with enforce timeout enabled the Cuckoo Analyzer is *too late* to make the process memory dumps (e.g., if the processes no longer exist). Without the enforce timeout flag the analysis finishes when Cuckoo determines that the malware has finished running, usually when it exits the process. Closing issue as resolved. Thanks!
