### ISSUE TITLE
Interrupted or failed reports are ignored by process2.py

### ISSUE THREAD

**Issue by keithjjones** [cuckoosandbox/cuckoo#1211]
I have 2 analyses (4 and 5 below) that aren't being reprocessed when I start "process2.py auto".  As you can see, they are completed in the database, but not reported:

```
cuckoo=> select id,processing,status from tasks;
 id | processing |  status   
----+------------+-----------
  1 | auto       | reported
  2 | auto       | reported
  3 | auto       | reported
  4 | auto       | completed
  5 | auto       | completed
(5 rows)
```

Process2.py doesn't pull them because they already have an instance associated with them and are missed by the SQL query:

https://github.com/cuckoosandbox/cuckoo/blob/657a5166d711135ee6159c8d0abc599d56d294fe/lib/cuckoo/core/database.py#L1406

There doesn't seem to be a -r feature with process2.py that there was with process.py.

I believe there should be a way to reprocess a task or process2 should be able to determine that a task wasn't finished when it is started.

**Comment by jbremer** [comment]
Actually for `-r` you could still use `process.py`. Anyway, this functionality has been combined in our latest 2.0.0 release, so closing as such. I.e., `cuckoo process auto` and `cuckoo process -r 4,5` do what you expect it to.
