### ISSUE TITLE
Cuckoo Rest API error

### ISSUE THREAD

**Issue by fahrettin89** [cuckoosandbox/cuckoo#1218]
Hi,
I have a strange problem with REST API.  I can run this code successfully;
"curl http://localhost:8090/machines/view/cuckoo1"

but I cannot execute this command;
"curl -F file=@/home/ubuntu/fiskiye http://localhost:8090/tasks/create/file"
it says that;

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

 do you have any idea what I am doing wrong?

**Comment by doomedraven** [comment]
is there any proxy between restapi and nginx

**Comment by fahrettin89** [comment]
no. there is no proxy.

**Comment by doomedraven** [comment]
is where any output in console where api started?

**Comment by fahrettin89** [comment]
I followed this documentation for setup. I use uwsgi. When I start uwsgi thisis the log of "/var/log/uwsgi/app/cuckoo-api.log" ;
*** Starting uWSGI 1.9.17.1-debian (64bit) on [Fri Dec 23 17:42:57 2016] ***
Fri Dec 23 17:42:57 2016 - compiled with version: 4.8.2 on 23 March 2014 17:15:32
Fri Dec 23 17:42:57 2016 - os: Linux-3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015
Fri Dec 23 17:42:57 2016 - nodename: cuckoo
Fri Dec 23 17:42:57 2016 - machine: x86_64
Fri Dec 23 17:42:57 2016 - clock source: unix
Fri Dec 23 17:42:57 2016 - pcre jit disabled
Fri Dec 23 17:42:57 2016 - detected number of CPU cores: 4
Fri Dec 23 17:42:57 2016 - current working directory: /
Fri Dec 23 17:42:57 2016 - writing pidfile to /run/uwsgi/app/cuckoo-api/pid
Fri Dec 23 17:42:57 2016 - detected binary path: /usr/bin/uwsgi-core
Fri Dec 23 17:42:57 2016 - setgid() to 1001
Fri Dec 23 17:42:57 2016 - set additional group 116 (vboxusers)
Fri Dec 23 17:42:57 2016 - setuid() to 1001
Fri Dec 23 17:42:57 2016 - your processes number limit is 31853
Fri Dec 23 17:42:57 2016 - your memory page size is 4096 bytes
Fri Dec 23 17:42:57 2016 - detected max file descriptor number: 1024
Fri Dec 23 17:42:57 2016 - lock engine: pthread robust mutexes
Fri Dec 23 17:42:57 2016 - thunder lock: disabled (you can enable it with --thunder-lock)
Fri Dec 23 17:42:57 2016 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/cuckoo-api/socket fd 3
Fri Dec 23 17:42:57 2016 - Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
Fri Dec 23 17:42:57 2016 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Fri Dec 23 17:42:57 2016 - Python main interpreter initialized at 0x996070
Fri Dec 23 17:42:57 2016 - your server socket listen backlog is limited to 100 connections
Fri Dec 23 17:42:57 2016 - your mercy for graceful operations on workers is 60 seconds
Fri Dec 23 17:42:57 2016 - mapped 218376 bytes (213 KB) for 2 cores
Fri Dec 23 17:42:57 2016 - *** Operational MODE: preforking ***
Fri Dec 23 17:42:57 2016 - WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x996070 pid: 27245 (default app)
Fri Dec 23 17:42:57 2016 - *** uWSGI is running in multiple interpreter mode ***
Fri Dec 23 17:42:57 2016 - spawned uWSGI master process (pid: 27245)
Fri Dec 23 17:42:57 2016 - spawned uWSGI worker 1 (pid: 27257, cores: 1)
Fri Dec 23 17:42:57 2016 - spawned uWSGI worker 2 (pid: 27258, cores: 1)

this is the error I get from same log file when I execute this command  "curl -F file=@/home/ubuntu/fiskiye http://localhost:8090/tasks/create/file";

[pid: 27257|app: 0|req: 1/2] 192.168.1.15 () {38 vars in 597 bytes} [Fri Dec 23 17:43:14 2016] POST /tasks/create/file => generated 291 bytes in 14 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)

**Comment by doomedraven** [comment]
well that is the proxy, is uwsgi is not `python api.py -H 0.0.0.0 -p 8090`
so probably something wrong with yout uwsgi config

**Comment by doomedraven** [comment]
this should works

```
[uwsgi]
    plugins = python
    callable = application
    ;change this patch if is different
    chdir = /opt/cuckoo/utils
    master = true
    mount = /=api.py
    processes = 5
    manage-script-name = true
    socket = 0.0.0.0:8090
    pidfile = /tmp/api.pid
    ; if you will use with nginx, comment next line
    protocol=http
    enable-threads = true
    lazy-apps = true
    timeout = 600
    chmod-socket = 664
    chown-socket = cuckoo:cuckoo
    gui = cuckoo
    uid = cuckoo
```

**Comment by fahrettin89** [comment]
so you mean uwsgi is proxy?
I will try your config and let you know the results.

**Comment by doomedraven** [comment]
well proxy for api because it not directly started, uwsgi start that that script not pure python

**Comment by fahrettin89** [comment]
is there any typo in your config like  "mount = /=api.py" is it correct?

**Comment by doomedraven** [comment]
nop, it works fine for me i can access it in `:8090/`

**Comment by fahrettin89** [comment]
it gives me the bind() address port already in use.Because I use nginx and it listens 8090 port.  I delete the line "protocol=http" as you say.

this is the new error;

bind(): Address already in use [core/socket.c line 763]

what should I do?

**Comment by doomedraven** [comment]
lol i asked if you have proxy and you told no, but you have nginx and uwsgi in front, so there is application proxies, try `python apy.py -H 0.0.0.0 -p 8090` if that work, there is just problem with your config somewhere

**Comment by fahrettin89** [comment]
Threre is one proxy for me and it is in network :) . So let me try with api.py and get back to you.

**Comment by doomedraven** [comment]
yah i should specify the application proxy not network proxy :P before try with just `api.py` turn down nginx and uwsgi to make free that port

**Comment by fahrettin89** [comment]
I think cuckoo's documentation mislead people to use not api.py but use uwsgi and nginx :). thanks btw.

**Comment by doomedraven** [comment]
I have it with uwsgi and nginx, is better for perfomance and stability
