### ISSUE TITLE
Ability to reprocess a range of reports eg from 17000 - 18000,

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1221]
This would be a nice to have, just noticed that my database partition become full and it continues to process the reports but leaves the database with no entries. I would be nice to be able to reporcess these a range of samples. This would be handy  when issues arise and you need to re-report your samples.

Cheers
A :)

**Comment by SparkyNZL** [comment]
or even supply a list for eg able cuckoo process -r 1324,464,232,3543 this would reprocess these four samples, currently Ive been having to write a terrible bash script :(

**Comment by jbremer** [comment]
Sorry, didn't notice your earlier request. We could definitely do this, as I've also had plenty of use-cases for this. Thanks!

**Comment by SparkyNZL** [comment]
awesome :)

**Comment by jbremer** [comment]
@SparkyNZL Had the need for this functionality again this morning, please find the commit above :-) Note that this is still in my development `package` branch in the `jbremer/cuckoo` repository. Will be pushed to `cuckoosandbox/cuckoo` eventually ;-)

**Comment by SparkyNZL** [comment]
@jbremer Cheers mate, this will help AMAZINGLY for me and testing stuff  as well, I usualy submit ~ 5000 samples a day at the moment so it can be a pain if 1000 of them dont report what i would expect and i need to re run them :)

**Comment by jbremer** [comment]
Great to hear :-) Closing this issue as resolved. Will push the relevant commits soon'ish ;-)
