### ISSUE TITLE
Cuckoo Sandbox - Guest

### ISSUE THREAD

**Issue by zwyaniv** [cuckoosandbox/cuckoo#1222]
Hi All,

Can the Guest VM be always online, and not on standby mode?

Thank you
YZ

**Comment by doomedraven** [comment]
explain you a bit better what do you mean exactly

**Comment by jbremer** [comment]
Would you like to have VMs started automatically to cut on the time it takes to restore it otherwise?

**Comment by jbremer** [comment]
Closing for lack of additional information. Please reopen if you'd like to ask further ;-)
