### ISSUE TITLE
Question to Analyse Malware in a ZIP-Data

### ISSUE THREAD

**Issue by Comchees** [cuckoosandbox/cuckoo#1223]
Hi there,

At the moment I want to analyze Malware wich is in a passworded Zip-data.
How can I submit the zipped-malware to Cuckoo?
I want to use submit.py for it, but I can't find the password-command in the help menue.

Regards

edit: 
Okay the command `sudo python submit.py --options password=infectet test.zip` is the right one! But Cuckoo throws an exception during the analys... :(
![bildschirmfoto vom 2016-12-28 23-19-49](https://cloud.githubusercontent.com/assets/4396935/21532809/400ef584-cd54-11e6-974d-98faef5b221c.png)

**Comment by doomedraven** [comment]
that is not supported yet, you must use https://github.com/jbremer/sflock/tree/master/sflock to pre process your archives, if you want execute files from inside and not zip with zip package

**Comment by Comchees** [comment]
Is there any doc for sflock? Or how can use it to pre process my archive?

**Comment by doomedraven** [comment]
no idea, i just readed the code
here my code which i use

```
try:
    from sflock.main import unpack
    from sflock.unpack import ZipFile
    from sflock.abstracts import File
except ImportError:
    print "Missed deps"\
    "sudo apt-get install p7zip-full rar unace-nonfree"\
    "sudo pip install -U sflock"

#passing content, unpaacking in memory, you can use from file check source code
z = ZipFile(File(contents=attachment))
files = list(z.unpack(duplicates=[]))
for file in files:
            new_file = EXTRACTED(sha256=file.sha256)
            new_file.name = file.filename
            new_file.md5 = hashlib.md5(file.contents).hexdigest()
            new_file.sha1 = hashlib.sha1(file.contents).hexdigest()
            new_file.content_type = file.mime
```

i hope that helps

**Comment by doomedraven** [comment]
also check cuckoomx there i use it 

https://github.com/cuckoosandbox/cuckoo/pull/1175/files

**Comment by jbremer** [comment]
Actually what you want to do is just `sflock.unpack()` ;-) For ideas on usage, it's easiest to see some examples in the unit tests https://github.com/jbremer/sflock/blob/master/tests/test_unpack.py

**Comment by Comchees** [comment]
Ah I will try it, thanks for the help. I only hope that the `sflock.unpack(**.zip, None, "infected", **, None)` doesn't activate the malware. After the unpacking I will send the file directly to cuckoo.

**Comment by jbremer** [comment]
It only unpacks the `.zip` in-memory, naturally it doesn't run the malware in any way ;)

**Comment by Comchees** [comment]
Okay. :D

Another Question: Do cuckoo have some problems with wireshark, which is running in the background? Because always it smashes my screen with a bloody error during the analyse. :D It is working well without wireshark.

**Comment by jbremer** [comment]
Any screenshots or logs may help here ;-)
