### ISSUE TITLE
Cuckoo and guest on same virtualbox

### ISSUE THREAD

**Issue by rmsferreira** [cuckoosandbox/cuckoo#1225]
Hi all,
I`m try to install cuckoo on a virtualbox machine and the guests in the same virtualbox machine.
How i configure cuckoo to manage virtualbox.
How can i configure the virtualbox.conf to remote connection

Path to the lremote installation of the VBoxManage utility.

**Comment by doomedraven** [comment]
if you mean host -> vm(cuckoo) -> guests inside of vm, then use search in issues It was responded a bit ago, but if you mean vm cuckoo and other vms apart i think that won't be possible, as you won't able sniff traffic, and do another operations, as set routes for routing etc

**Comment by jbremer** [comment]
@rmsferreira Did you resolve this (seemingly impossible) issue already?

**Comment by jbremer** [comment]
Closing for lack of additional information. Feel free to reopen if you have more information / questions / feedback.
