### ISSUE TITLE
first time install cuckoo in ubuntu

### ISSUE THREAD

**Issue by najeex** [cuckoosandbox/cuckoo#1242]
hey 
i am try to proper install cuckoo. i follow same process as installation doc say's..but i am new so make some mistake...i am using ubuntu 16.10 lts python3 and python 2 and for requriment i use this command "sudo -H pip install -r requirements.txt" or other like tcpdump i have already ...and hare is my error...

`najeeb@najeeb:/usr/local/src/cuckoo$ python2 cuckoo.py 
Traceback (most recent call last):
  File "cuckoo.py", line 20, in <module>
    from lib.cuckoo.core.scheduler import Scheduler
  File "/usr/local/src/cuckoo/lib/cuckoo/core/scheduler.py", line 21, in <module>
    from lib.cuckoo.core.guest import GuestManager
  File "/usr/local/src/cuckoo/lib/cuckoo/core/guest.py", line 28, in <module>
    db = Database()
  File "/usr/local/src/cuckoo/lib/cuckoo/common/utils.py", line 206, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/src/cuckoo/lib/cuckoo/core/database.py", line 386, in __init__
    raise CuckooDatabaseError("Unable to create database directory: {0}".format(e))
lib.cuckoo.common.exceptions.CuckooDatabaseError: Unable to create database directory: Unable to create folder: /usr/local/src/cuckoo/db
Exception AttributeError: "'Database' object has no attribute 'engine'" in <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0xb41d2aec>> ignored
`

**Comment by doomedraven** [comment]
it looks like you have error/typo in cuckoo.conf

**Comment by najeex** [comment]
can past my cuckoo.conf hare

**Comment by doomedraven** [comment]
do it with markdown code formating plz to make it easy to read

**Comment by doomedraven** [comment]
i wont provide my conf but here one https://github.com/cuckoosandbox/cuckoo/blob/master/conf/cuckoo.conf

**Comment by najeex** [comment]
@doomedraven but i was not modify cuckoo.conf...
i will see this wait min

**Comment by doomedraven** [comment]
check for typo/error here in oyur conf
https://github.com/cuckoosandbox/cuckoo/blob/master/conf/cuckoo.conf#L146

**Comment by najeex** [comment]
@doomedraven what should i fill there? and how i get 

`[database]
Specify the database connection string.
 NOTE: If you are using a custom database (different from sqlite), you have to
 use utf-8 encoding when issuing the SQL database creation statement.
 Examples, see documentation for more:
 sqlite:///foo.db
 postgresql://foo:bar@localhost:5432/mydatabase
 mysql://foo:bar@localhost/mydatabase
 If empty, default is a SQLite in db/cuckoo.db.
 connection =`

**Comment by najeex** [comment]
@doomedraven i was saw tutorial no one tut are do this.. modify cuckoo.conf file

**Comment by doomedraven** [comment]
there should be db connection string if you what you what to use something else than sqlite, which cuckoo version do you use?

**Comment by najeex** [comment]
@doomedraven i am not use any database connection...how i fix error ...

**Comment by doomedraven** [comment]
it should work from the box, i don't know which version do you use, etc

**Comment by najeex** [comment]
@doomedraven  i am install today by git... i don't understand which information you need...tell me what information you need...i think this is not big deal to fix...i can't do it bcos to many lib are inclued and painful process to setup...

**Comment by doomedraven** [comment]
i think you have some missed lib, or incorrect lib
can you post output from `sudo -H pip install -r requirements.txt` ?

**Comment by najeex** [comment]
`Requirement already satisfied: alembic==0.8.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: beautifulsoup4==4.4.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: cffi==1.6.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: chardet==2.3.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: cryptography==1.3.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: Django==1.8.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: dpkt==1.8.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: ecdsa==0.13 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: elasticsearch==2.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: enum34==1.0.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: Flask==0.10.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: HTTPReplay==0.1.17 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: idna==2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: ipaddress==1.0.14 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: itsdangerous==0.24 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: Jinja2==2.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied: jsbeautifier==1.5.10 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied: lxml==3.6.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already satisfied: Mako==1.0.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied: MarkupSafe==0.23 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied: ndg-httpsclient==0.4.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 21))
Requirement already satisfied: oletools==0.42 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22))
Requirement already satisfied: peepdf==0.3.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Requirement already satisfied: pefile2==1.2.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 24))
Requirement already satisfied: pyasn1==0.1.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 25))
Requirement already satisfied: pycparser==2.14 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 26))
Requirement already satisfied: pymisp==2.4.54 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 27))
Requirement already satisfied: pymongo==3.0.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 28))
Requirement already satisfied: pyOpenSSL==0.15.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 29))
Requirement already satisfied: python-dateutil==2.4.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 30))
Requirement already satisfied: python-editor==0.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 31))
Requirement already satisfied: python-magic==0.4.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 32))
Requirement already satisfied: requests==2.7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 33))
Requirement already satisfied: six==1.9.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 34))
Requirement already satisfied: SQLAlchemy==1.0.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 35))
Requirement already satisfied: tlslite-ng==0.6.0-alpha3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 36))
Requirement already satisfied: wakeonlan==0.2.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 37))
Requirement already satisfied: Werkzeug==0.10.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 38))
Requirement already satisfied: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography==1.3.2->-r requirements.txt (line 5))
Requirement already satisfied: urllib3<2.0,>=1.8 in /usr/lib/python2.7/dist-packages (from elasticsearch==2.2.0->-r requirements.txt (line 9))
Requirement already satisfied: click<7,>=6.6 in /usr/local/lib/python2.7/dist-packages (from HTTPReplay==0.1.17->-r requirements.txt (line 12))
Requirement already satisfied: colorama==0.3.7 in /usr/local/lib/python2.7/dist-packages (from peepdf==0.3.2->-r requirements.txt (line 23))
Requirement already satisfied: Pillow==3.2.0 in /usr/local/lib/python2.7/dist-packages (from peepdf==0.3.2->-r requirements.txt (line 23))
Requirement already satisfied: pythonaes==1.0 in /usr/local/lib/python2.7/dist-packages (from peepdf==0.3.2->-r requirements.txt (line 23))
Requirement already satisfied: jsonschema in /usr/local/lib/python2.7/dist-packages (from pymisp==2.4.54->-r requirements.txt (line 27))
Requirement already satisfied: functools32; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from jsonschema->pymisp==2.4.54->-r requirements.txt (line 27))
`

**Comment by najeex** [comment]
all are good in lib

**Comment by doomedraven** [comment]
@jbremer any idea?

**Comment by jbremer** [comment]
Same issue as #1243, so closing this one as a duplicate.
