### ISSUE TITLE
process.py hanging when reporting on certain malware samples

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1244]
Evening.

Just wondering if someone would be so kind to try and process a couple of reports for me using process.py

This seems to hang indeffently  one at the below (strings)

DEBUG:lib.cuckoo.core.plugins:Executed processing module "Screenshots" on analysis at "/home//cuckoo/storage/analyses/24810"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "Snort" on analysis at "/home/cuckoo/storage/analyses/24810"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "Static" on analysis at "/home/cuckoo/storage/analyses/24810"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "Strings" on analysis at "/home/cuckoo/storage/analyses/24810"

To get passed this i have to delete the "binary" and restart procress.py -rdp 10 auto

The other one is , of this file exists in the /cuckoo/storage/analyses/XXXX/files/ 6c28c56ed38525bf___9dbd8eaa5b0349ef944b086f64fe8e92.dll

if this existed in the "files" directory the sample again would not process. The error i would get was   ./process.py -rd  28846
DEBUG:lib.cuckoo.core.plugins:Executed processing module "AnalysisInfo" on analysis at "/home/adroot/cuckoo/storage/analyses/28846"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "MetaInfo" on analysis at "/home/adroot/cuckoo/storage/analyses/28846"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "BehaviorAnalysis" on analysis at "/home/adroot/cuckoo/storage/analyses/28846"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "DroppedBuffer" on analysis at "/home/adroot/cuckoo/storage/analyses/28846"
DEBUG:lib.cuckoo.core.plugins:Executed processing module "Debug" on analysis at "/home/adroot/cuckoo/storage/analyses/28846"
Segmentation fault (core dumped)

once the above file was deleted it would process fine.

Im running the following

Ubuntu 16.04
Cuckoo Rc2
Win7 VMs
Postgres Database on a remote system

I can send through the Malware or MD5's or even ZIP up the report directories, but it seems that there are a number similar samples causing these issues .... 

Cheers
SparkyNZL

**Comment by jbremer** [comment]
`process.py` is known to hang and therefore deprecated'ish by `process2.py`. In #863 we introduce `cuckoo process` which combines `process.py` and `process2.py` in a way that it works properly.

**Comment by SparkyNZL** [comment]
Cheers, Sorry but am i being an egg, pip install cuckoo doesnt work i get this 

Collecting cuckoo
  Could not find a version that satisfies the requirement cuckoo (from versions: )
No matching distribution found for cuckoo

Cheers

**Comment by doomedraven** [comment]
@SparkyNZL  here is my man of how to deploy package, but routing is not working directly out of box, you need trick it
* [README](https://github.com/cuckoosandbox/cuckoo/pull/863) 

```
virtualenv cuckoo
. cuckoo/bin/activate

git clone -b package https://github.com/cuckoosandbox/cuckoo.git cuckoo_package
git clone https://github.com/cuckoosandbox/community.git
cp -rp community/data/monitor cuckoo/data/

python setup.py sdist
sdist/develop/install
```

* Then uncomment tor/inetsim in rooter.conf, and do the rest of configurations in configs

```
cuckoo rooter
cuckoo web -H 0.0.0.0 -p 8000
cuckoo process -m 4 auto
cuckoo -d
```

* Help
```
cuckoo --help
cuckoo command --help
```

**Comment by SparkyNZL** [comment]
thanks mate, Im just running this up now  :) Ill let you know how i get on.

**Comment by SparkyNZL** [comment]
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    latest = open(os.path.join(monitor, "latest"), "rb").read().strip()
IOError: [Errno 21] Is a directory: 'cuckoo/data/monitor/latest'

I also had to alter these

virtualenv cuckoo
. cuckoo/bin/activate

git clone -b package https://github.com/cuckoosandbox/cuckoo.git cuckoo_package
git clone https://github.com/cuckoosandbox/community.git
cp -rp community/data/monitor cuckoo_package/cuckoo/data/
                                                             ^^^^^^^^^^^^^^^^    
cd cuckoo_package
python setup.py sdist
<above error occurs here>
sdist/develop/install

**Comment by doomedraven** [comment]
ah yah, instead of read the latest file in setup.py i just change it to folder
https://github.com/cuckoosandbox/cuckoo/blob/package/setup.py#L17

```
excl, monitor = [], os.path.join("cuckoo", "data", "monitor")
latest = open(os.path.join(monitor, "latest"), "rb")
for h in os.listdir(monitor):
    if h == "latest":
```

you can assign dirrectly latest to h and done if you want

**Comment by SparkyNZL** [comment]
Hmm surely this won't work either as your are trying to open a directory (lastest) as read, and it cant becuae the symlink is a directory not a file ? or am i missing something my python is poor its been 2 years since i did any python work ;(

**Comment by SparkyNZL** [comment]
got around this by hardcoding the variable, everything it creates the package and i installed it using PIP reedited all if the conf files in .cuckoo/conf looking all good... then i tried to run it, and i get the postgres error, i have verified that i have installed the requirements eg psycopg2, so i uninstalled it using PIP and re installed psycopg2 and still no go :( this is the error i get

Traceback (most recent call last):
  File "./cuckoo", line 11, in <module>
    sys.exit(main())
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/cuckoo/main.py", line 468, in web
    Database().connect()
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/database.py", line 413, in connect
    self._connect_database(dsn)
  File "/home/adroot/cuckoo/local/lib/python2.7/site-packages/cuckoo/core/database.py", line 498, in _connect_database
    "Missing PostgreSQL database driver (install with "
cuckoo.common.exceptions.CuckooDependencyError: Missing PostgreSQL database driver (install with `pip install psycopg2`)


Idea's suggestions ? 

Chur

**Comment by SparkyNZL** [comment]
ok so this turned out to be operator error (suprise) all sorted :)

**Comment by SparkyNZL** [comment]
So the initial issue still exists , when processing some samples im getting the following

2017-01-22 19:21:22,118 [cuckoo] INFO: Initialized instance=auto, ready to process some tasks
2017-01-22 19:21:22,263 [cuckoo.apps.apps] INFO: Task #22933: reporting task
Segmentation fault (core dumped)

**Comment by jbremer** [comment]
The `psycopg2` package was outdated or? Well, obviously it shouldn't segfault - can you enable verbose mode so we get a *little* bit more information on where it may be happening? `cuckoo -d process auto`. Alternatively, can you enable core dumping and share one so we can investigate?

**Comment by SparkyNZL** [comment]
I think ghte psycopg2 issues was cause by me trying to cut corner with the conf file LOLz. I deleted the install and did a new install with new conf files and it all worked fine :)

I really like the new Web Interface its a great improvement

Here is the segfault i get. 
cuckoo -d process -r 22980

2017-01-23 11:24:13,216 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
2017-01-23 11:24:15,224 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
2017-01-23 11:24:15,239 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
2017-01-23 11:24:15,475 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
2017-01-23 11:24:47,642 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
2017-01-23 11:24:47,642 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
2017-01-23 11:24:47,643 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" on analysis at "/home/adroot/.cuckoo/storage/analyses/22980"
Segmentation fault (core dumped)

Ive tracked it down to files in the buffers directory, there were 218 files in there. Ill see if i can narrow it down, but i had the same issue with a file in the "files" directory causing similar issues.

**Comment by doomedraven** [comment]
Can you provide hash to test it on my side?

**Comment by SparkyNZL** [comment]
md5 is : 0d7dfd5bdd0f4d23a306bc11e5260dd0

**Comment by SparkyNZL** [comment]
if you cant find it i can zip it up and send it to you

**Comment by SparkyNZL** [comment]
so after filtering through 218 dropped buffers i found the one causing the problem. In fact if i copy to any dropped buffer directory for any already processed report it causes a segfault . This causes the processing of reports to die and get stuck (i have around 40K items back logged at the moment hahaha meh) 5K which have been processed but not reported.

How do i go about uploading the file for you guys to have a look at ? from what i can see its just a plain old data file but there is something about it that the droppedbuffers processing library does not like at all ! after doing a search there seems to be a number of files breaking the reporting of samples

**Comment by SparkyNZL** [comment]
OK so Im pretty sure the issue is with the processing , I have completely reinstalled the OS and cuckoo, and i have samples which are causeing a Segfault when processing. 

Can someone please verify this for me the 

Size 	420.6KB
Type 	PE32+ executable (DLL) (GUI) x86-64, for MS Windows
MD5 	b1c1cf0f8d77aad3694cab6181ebd2c0
SHA1 	a7617931a7c51aa3b87c75fe6c96c56dd4b0283b
SHA256 	3bffc96b45addbbec91cdfe7f1b2b620f24012c57bcb72a7177fd00eae26ee06

**Comment by doomedraven** [comment]
just executed on rc2, cuckoo says that is not a valid win32 app, but processing works fine

**Comment by doomedraven** [comment]
i don't have x64 vm to test it

**Comment by KillerInstinct** [comment]
What does dmesg have to say about the segfault?

**Comment by SparkyNZL** [comment]
So i rebuild the entire system including the file system and this appears to have fixed this issue, its really bizzare and i see no valid explanation for it. but its is now analyzing the very samples which it couldn't earlier ! Thanks to everyone who looked into this for me, I cant explain WHY.

Im reprocessing the 40K samples and see if something nasty pops up as the samples increase, but for the mean time ill close this.

Cheers

**Comment by doomedraven** [comment]
testing only this as the rest are not on vt

```
	Downloaded to File -- d9493b97b963ac42d78bf0fd3053de00
	Downloaded to File -- f76f644515930c0d039e6dc51508db60
	Downloaded to File -- d460669aa7582822d554e3c1ea741e50
	Downloaded to File -- 1971e5cd4541b1b16ed5d4ab7d6c9fc0
	Downloaded to File -- dc4e3a85631121642d66ad542257b070
```

all works fine on my side, some looks like installers
some as flooders, but no issue with yara/processing

**Comment by SparkyNZL** [comment]
Can u tell me what version of Yara you are using , are you on a 64 bit
Ubuntu or 32 bit ?

Cheers


Sent from my spaceship...

On 6/02/2017 1:40 AM, "doomedraven" <notifications@github.com> wrote:

testing only this as the rest are not on vt

	Downloaded to File -- d9493b97b963ac42d78bf0fd3053de00
	Downloaded to File -- f76f644515930c0d039e6dc51508db60
	Downloaded to File -- d460669aa7582822d554e3c1ea741e50
	Downloaded to File -- 1971e5cd4541b1b16ed5d4ab7d6c9fc0
	Downloaded to File -- dc4e3a85631121642d66ad542257b070

all works fine on my side, some looks like installers
some as flooders, but no issue with yara/processing

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/cuckoosandbox/cuckoo/issues/1244#issuecomment-277517235>,
or mute the thread

**Comment by doomedraven** [comment]
Ubuntu 16.04 x64, yara 3.4.0 as 3.5.0 gave me some problems

**Comment by SparkyNZL** [comment]
Ok I'll down grade my Yara too to 3.4 and see what happens ;)

Thanks ;)

**Comment by SparkyNZL** [comment]
ok so i can finally close this for good,
Downgrading this didnt fix the issue. what i had do to was the following
delete yara.x86_64-linux-gnu.so from the system, this broke yara but it also fixed the issue or at least verified it was a yara issue.  I then uninstall yara-python recompiled yara-3.4.0 snd installled and then also installed pip install yara-python.  

This fixed it ! FML , :)

S.
