### ISSUE TITLE
Error message when analyzing certain zip-files

### ISSUE THREAD

**Issue by simon268K** [cuckoosandbox/cuckoo#1245]
Hi, I have a problem when trying to analyze zip files without a password.
The analysis worked with a zipped .exe file, but it doesent work with a zipped .bat or .doc files. Here is my error message for a zipped file named 'test.bat':

Error: Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.zip" start function encountered an unhandled exception: Error returned by is32bit: Command '['bin\\is32bit.exe', '-f', u'C:\\Users\\_username_\\AppData\\Local\\Temp\\Test.bat']' returned non-zero exit status 1 Traceback (most recent call last): File "C:\xtbfojs\analyzer.py", line 778, in <module> success = analyzer.run() File "C:\xtbfojs\analyzer.py", line 631, in run "exception: %s" % (package_name, e) CuckooError: The package "modules.packages.zip" start function encountered an unhandled exception: Error returned by is32bit: Command '['bin\\is32bit.exe', '-f', u'C:\\Users\\_username_\\AppData\\Local\\Temp\\Test.bat']' returned non-zero exit status 1

These are the specs of my environment:
Cuckoo Sandbox 2.0-rc2
Cuckoo Host OS: Ubuntu Server 16.04 LTS 64Bit
Analysis VMs: All Windows 7 32 Bit

Thanks for any help.

**Comment by doomedraven** [comment]
zip files are not supported yet, you should unpack and upload files, before open issues do search in issues you have this question responded so many times ;)

https://github.com/jbremer/sflock can be useful for you
