### ISSUE TITLE
i don't understant how to fix this

### ISSUE THREAD

**Issue by najeex** [cuckoosandbox/cuckoo#1246]
hey i am don't understand what i wrong doing..this is issue,,,,

> najeeb@najeeb:/usr/local/src/cuckoo$ sudo python2 cuckoo.py 

    _______ _     _ _______ _     _  _____   _____ 
    |       |     | |       |____/  |     | |     |
    |_____  |_____| |_____  |    \_ |_____| |_____|

  Cuckoo Sandbox 2.0-dev
  www.cuckoosandbox.org
  Copyright (c) 2010-2015

  Checking for updates...
  You are running a development version! Current stable is 2.0-rc1.
  2017-01-16 23:10:09,447 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
   2017-01-16 23:11:24,437 [root] CRITICAL: CuckooCriticalError: Please update your configuration.   Unable to shut 'cuckoo1' down or find the machine in its proper state: Timeout hit while for machine     cuckoo1 to change status

**Comment by doomedraven** [comment]
Your vm snapshot is in incorrect state

**Comment by doomedraven** [comment]
Did you read the documentation?

**Comment by najeex** [comment]
@doomedraven yes and i do as doc say's

**Comment by doomedraven** [comment]
btw before open issue, do search in issues(open/closed)there are tons of the same questions and answers ;) it will save you and us a lot of time

**Comment by jbremer** [comment]
@najeex Did you resolve this issue already by now?

**Comment by jbremer** [comment]
Closing for a lack of feedback.
