### ISSUE TITLE
M2Crypto problem

### ISSUE THREAD

**Issue by bincker** [cuckoosandbox/cuckoo#1247]
HI all   
     plz install the older version of M2Crypto like M2Crypto-0.22.   M2Crypto-0.25 newest version have some bug.

**Comment by jbremer** [comment]
Yes, we're aware ;-) This is for the upcoming version #863, https://github.com/cuckoosandbox/cuckoo/commit/328e9b694ea2442495379b9aadf3319661be3384. Thanks for the report nonetheless, if you have any further questions and/or suggestions, please do let us know.
