### ISSUE TITLE
"The analysis is not completed yet, it's still completed."

### ISSUE THREAD

**Issue by MarkusTeufelberger** [cuckoosandbox/cuckoo#1249]
"Hang on...

The analysis is not completed yet, it's still completed. This page will refresh every 5 seconds."
in the webui /submit/status/[submission_id]/

Reason: The report generation takes a little while and "completed" is the state before "reported" (reported being the one that actually is the one you're waiting for).

This looks at least a little irritating or like something has gone wrong, a possible solution would be to rename "completed" to "analysed" or "completed_analysis" (to be in line with "failed_analysis").

**Comment by jbremer** [comment]
Fair enough :) fortunately we've replaced this page by much more awesomeness in the `package` branch, so I'm going to close this as resolved ;-)
