### ISSUE TITLE
REALLY NEED YOUR HELP!!!

### ISSUE THREAD

**Issue by choiwj1216** [cuckoosandbox/cuckoo#1250]
The most recent thing I did was uWSGI and Nginx setup from http://docs.cuckoosandbox.org/en/latest/usage/api/#starting-the-api-server.

And I rebooted the system, tried to run following command and resulted with this error.
Can anybody tell me how to fix this issue?

cuckoo@triage-qa-cuckoo-01:~/cuckoo/utils$ python api.py --host 0.0.0.0 --port 8090
 * Running on http://0.0.0.0:8090/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "api.py", line 556, in <module>
    app.run(host=args.host, port=int(args.port))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 512, in make_server
    passthrough_errors, ssl_context)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by jbremer** [comment]
Because you setup uwsgi+nginx, it is already running, and you don't have to run it manually ;-)

**Comment by choiwj1216** [comment]
But after the installation, I am getting this error on the web interface..... :(

![capture](https://cloud.githubusercontent.com/assets/25231502/22122167/ec572d78-de54-11e6-88a4-3c7d0c7573e5.PNG)

**Comment by SparkyNZL** [comment]
did you put the port number in after it get http://172.20.1.195:8090 ?

**Comment by doomedraven** [comment]
also provide logs from uwsg/nginx

**Comment by choiwj1216** [comment]
Yes, I also have tried putting the port number.

![capture1](https://cloud.githubusercontent.com/assets/25231502/22210198/ff2cdfa6-e156-11e6-8f7c-6295d3df8001.PNG)

**Comment by choiwj1216** [comment]
Searched under this issue and changed the configs, but did not work :(

```
ubuntu@cuckoo:~$ cat /etc/nginx/nginx.conf
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/x-javascri                                                                             pt text/xml application/xml application/xml+rss text/javascript;

        ##
        # nginx-naxsi config
        ##
        # Uncomment it if you installed nginx-naxsi
        ##

        #include /etc/nginx/naxsi_core.rules;

        ##
        # nginx-passenger config
        ##
        # Uncomment it if you installed nginx-passenger
        ##

        #passenger_root /usr;
        #passenger_ruby /usr/bin/ruby;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}
```

```
[uwsgi]
    plugins = python
    callable = application
    ;change this patch if is different
    chdir = /opt/cuckoo/utils
    master = true
    mount = /=api.py
    processes = 5
    manage-script-name = true
    socket = 0.0.0.0:8090
    pidfile = /tmp/api.pid
    ; if you will use with nginx, comment next line
    protocol=http
    enable-threads = true
    lazy-apps = true
    timeout = 600
    chmod-socket = 664
    chown-socket = cuckoo:cuckoo
    gui = cuckoo
    uid = cuckoo

```

**Comment by doomedraven** [comment]
provide nginx and uwsgi logs

**Comment by choiwj1216** [comment]
> cat error.log.1
> 2017/01/20 08:12:50 [emerg] 1355#0: bind() to 0.0.0.0:8090 failed (98: Address already in use)
> 2017/01/20 08:12:50 [emerg] 1355#0: bind() to 0.0.0.0:8090 failed (98: Address already in use)
> 2017/01/20 08:12:50 [emerg] 1355#0: bind() to 0.0.0.0:8090 failed (98: Address already in use)
> 2017/01/20 08:12:50 [emerg] 1355#0: bind() to 0.0.0.0:8090 failed (98: Address already in use)
> 2017/01/20 08:12:50 [emerg] 1355#0: bind() to 0.0.0.0:8090 failed (98: Address already in use)
> 2017/01/20 08:12:50 [emerg] 1355#0: still could not bind()
> 2017/01/20 08:17:59 [crit] 1322#0: *20 connect() to unix:/run/uwsgi/app/cuckoo-api/socket failed (2: No such file or directory) while connecting to upstream, client: 172.21.1.175, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-api/socket:", host: "172.20.1.95:8090"
> 2017/01/20 08:17:59 [crit] 1322#0: *21 connect() to unix:/run/uwsgi/app/cuckoo-api/socket failed (2: No such file or directory) while connecting to upstream, client: 172.21.1.175, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-api/socket:", host: "172.20.1.95:8090"
> 2017/01/20 08:21:25 [crit] 1322#0: *24 connect() to unix:/run/uwsgi/app/cuckoo-api/socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /machines/view/cuckoo1 HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-api/socket:", host: "localhost:8090"

**Comment by choiwj1216** [comment]
```
cat error.log
2017/01/23 08:31:10 [crit] 1320#0: *45 connect() to unix:/run/uwsgi/app/cuckoo-api/socket failed (2: No such file or directory) while connecting to upstream, client: 172.21.1.175, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-api/socket:", host: "172.20.1.95:8090"

```

**Comment by choiwj1216** [comment]
nothing shows up in /var/log/uwsgi/app/cuckoo-api.log

**Comment by doomedraven** [comment]
`bind() to 0.0.0.0:8090 failed (98: Address already in use)` something else already listening in your port

**Comment by choiwj1216** [comment]
that log shows because I was creating a new cuckoo server, when I had no idea how to get this straightened up. I will close this case for now and get back to this issue later. Thank you!
