### ISSUE TITLE
Guest machine not launching 

### ISSUE THREAD

**Issue by asdarunasd1** [cuckoosandbox/cuckoo#1253]
When i try to run ./cuckoo.py..the below error is showing( no machines available).. I have configured the guest windows in virtual box and added the details in cuckoo.conf and virtualbox.conf... i can ping both the guest system and host system in both ways

root@ubuntu:/home/cuckoo/cuckoo# python ./cuckoo.py

           _______                   _____                    _____
          /::\    \                 /\    \                  /\    \
         /::::\    \               /::\____\                /::\    \
        /::::::\    \             /::::|   |               /::::\    \
       /::::::::\    \           /:::::|   |              /::::::\    \
      /:::/~~\:::\    \         /::::::|   |             /:::/\:::\    \
     /:::/    \:::\    \       /:::/|::|   |            /:::/  \:::\    \
    /:::/    / \:::\    \     /:::/ |::|   |           /:::/    \:::\    \
   /:::/____/   \:::\____\   /:::/  |::|___|______    /:::/    / \:::\    \
  |:::|    |     |:::|    | /:::/   |::::::::\    \  /:::/    /   \:::\ ___\
  |:::|____|     |:::|    |/:::/    |:::::::::\____\/:::/____/  ___\:::|    |
   \:::\    \   /:::/    / \::/    / ~~~~~/:::/    /\:::\    \ /\  /:::|____|
    \:::\    \ /:::/    /   \/____/      /:::/    /  \:::\    /::\ \::/    /
     \:::\    /:::/    /                /:::/    /    \:::\   \:::\ \/____/
      \:::\__/:::/    /                /:::/    /      \:::\   \:::\____\
       \::::::::/    /                /:::/    /        \:::\  /:::/    /
        \::::::/    /                /:::/    /          \:::\/:::/    /
         \::::/    /                /:::/    /            \::::::/    /
          \::/____/                /:::/    /              \::::/    /
           ~~                      \::/    /                \::/____/
                                    \/____/
                                                       it's Cuckoo!

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 You are running a development version! Current stable is 2.0-rc1.
2017-01-22 06:19:32,898 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-01-22 06:19:32,961 [lib.cuckoo.common.abstracts] WARNING: Configuration details about machine windows are missing: Option windows is not found in configuration, error: Config instance has no attribute 'windows'
2017-01-22 06:19:33,043 [root] CRITICAL: CuckooCriticalError: No machines available.

**Comment by doomedraven** [comment]
looks like you not configurated `conf/virtualbox.conf`

**Comment by asdarunasd1** [comment]
i have configured virtualbox.conf also ... my windows virtual machine ip is 192.168.56.101 

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui", "sdl" or "headless". Refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path =  /usr/bin/virtualbox

# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = windows
[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = windows

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
# snapshot = Snapshot1
# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
# interface = vboxnet0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
# resultserver_ip = 192.168.56.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
# resultserver_port = 2042

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by doomedraven** [comment]
this is your fail

machines = windows
[cuckoo1] 

machines should be `cuckoo1`, reread documentation

**Comment by jbremer** [comment]
What @doomedraven said. I'm going to close this as resolved. Please re-open or create a new issue if you have any additional questions and/or feedback.
