### ISSUE TITLE
FOG login issue

### ISSUE THREAD

**Issue by leotant** [cuckoosandbox/cuckoo#1258]
I'm using a physical guest for my malware analysis and everything was going well until I tried to automate the deployment of the images using fog 1.3.2. Cuckoo is unable to connect to the fog server and I get the following error: 

CuckooCriticalError: The supplied FOG username and/or password do not allow us to login into FOG, please configure the correct credentials.

My physical.conf file looks like this: 

hostname=128.4.20.16
username=fog
password=password

I didn't change the fog username or password after installing fog. I used the defaults (which are precisely 'fog' and 'password'). Then I tried setting a new password, updating the physical.conf with the new password and running cuckoo, but I still got the same error. 

I know the documentation said it had only been tested with for 1.2.0, could that be the reason? Any advice?

**Comment by doomedraven** [comment]
see https://github.com/cuckoosandbox/cuckoo/issues/1146

**Comment by leotant** [comment]
Thanks for replying. I did look into that issue but I think that person's situation was different. He was using host='fog', which is incorrect because the host is supposed to be the ip address that you assign to it. 

In my case, cuckoo is able to reach the host, but fails at the point where it has to enter the username and password. 

Since that person was forced to downgrade to fog 1.2.0, I will try that now.

**Comment by doomedraven** [comment]
did you do a network sniffing to see if the request is correct? you can try to modify cuckoo part of fog integration to make it works with latest version, i don't have baremetal analyzer to debug it

**Comment by nsmfoo** [comment]
Currently the "ALT-API"(tm) being used to instrument FOG, does not work with the 1.3.x branch of FOG as the site layout changed. I might get the time to look at the mechanize parsing in the days to come.

**Comment by jbremer** [comment]
Haha @nsmfoo. Yes, it would be possible to start supporting a more recent version of FOG, but as-is that's not the case. For anyone doing a PR, keep in mind that I'll want unit tests working that show proof it's working properly with both versions (e.g., through the usage of stored responses.. due to a lack of a better way to do this). Sorry for the extra work required due to this ;-)

**Comment by leotant** [comment]
Thank you all for your replies. I downgraded to Fog 1.2.0 and it worked. For anyone using a physical machine as a guest, keep in mind that fog 1.2.0 only works with Ubuntu 14.0.4, since fog 1.2.0 requires php5, which seems to be no longer supported by Ubuntu 16.0.4 (the latter uses php7).

**Comment by jbremer** [comment]
Thanks for your feedback @leotant :-) There's a pending PR for migrating to `FOG 1.3.4` (I believe) which would hopefully get rid of that limitation. Closing this issue as resolved now, though.
