### ISSUE TITLE
vbox manager path missing 

### ISSUE THREAD

**Issue by asdarunasd** [cuckoosandbox/cuckoo#1260]
I am running a virtualbox in windows 2008. I installed ubuntu as host VM and windows 7 as guest VM.  I connected both VM using hostonly interface. Both getting ping . But when i launch cuckoo, its says vboxmanage path is missing .. which i need to add in virtualbox.conf (usually in /usr/bin/vboxmanage) . But since virtualbox is running on windows. what should i give as vboxmanage path ? 
![cuckoo](https://cloud.githubusercontent.com/assets/13660186/22299142/7e10767a-e33c-11e6-90c5-a98a78e17da2.png)
added a pic to just get an idea of the architecture which we are trying

**Comment by doomedraven** [comment]
the guests should be inside of host, you can't use them as 2 different vms

**Comment by asdarunasd** [comment]
Do you know if there is any other solution for this architecture to work out

**Comment by doomedraven** [comment]
at the moment there no solution

**Comment by jbremer** [comment]
I guess we should update the documentation to discourage users from trying to run Cuckoo itself in a VM (at least when using VirtualBox and alike), as this remains one of the most asked questions..
@asdarunasd Please run Cuckoo on the host if you want to use VirtualBox. If you want to use ESXi/XenServer/etc you may run Cuckoo in a VM, though, as those work remotely.

**Comment by asdarunasd** [comment]
I dont have the license of esxi that supports cuckoo....thats why i thought of trying in virtualbox..
 
@doomedraven @jbremer ..Thanks a lot...You guys are awesome..:)
