### ISSUE TITLE
Lack of Linux Guest Documentation

### ISSUE THREAD

**Issue by hoppers2k9** [cuckoosandbox/cuckoo#1261]
I have been trying to perform an analysis on a CentOS 6 guest using RC1. 

I am struggling to find any documentation for preparing the guest? I have got the agent running fine but it seems the analyser relies on kernel logging being configured, is this documented anywhere?

**Comment by doomedraven** [comment]
Search in pull reqs you have my docs there

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/1231

**Comment by jbremer** [comment]
Unfortunately this hasn't been documented, indeed. If you'd be interested to do any documentation on that that'd be totally awesome, though ;-) What's your current status on this matter @hoppers2k9?

**Comment by jbremer** [comment]
We're currently working on integrating @doomedraven's PR and more. We'll also be reviewing our documentation (which exists at the moment already, btw) and go further from there. Closing this issue as we have separate issue trackers for the mentioned items.
Let us know if you have more feedback etc.
