### ISSUE TITLE
machinery module

### ISSUE THREAD

**Issue by rmsferreira** [cuckoosandbox/cuckoo#1265]
Hi all.

Because the last malware cam bypass sandbox, i`m questing if is possible to have two machinery modules activate on cuckoo.
Virtualbox and physical.
Thanks

**Comment by doomedraven** [comment]
why just not do hardening of vm ? and no, at the moment that is impossible, you can found answer to this question in another issues :)

**Comment by jbremer** [comment]
Supporting multiple machinery is for several reasons not among one of our interests right now. (E.g., for a `physical` machine you'll want totally different timeout values than for a regular VM as it takes much longer to restore the VM etc - how would you document this in the configuration?)
Please simply just use two instances of Cuckoo for such setups. If you have any additional questions and/or suggestions, please do let us know. For now I'm closing this issue though.
