### ISSUE TITLE
Cuckoo Malware scoring

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1268]
Currently all the samples are only receiving a 0 score, even though they are dropping files and testing positive to AV etc.

I couldn't see an already open ticket or comment so my apologies if this is already reported.

Cheers.

**Comment by doomedraven** [comment]
provide some hashes, logs, image, as here it works fine with rc2 and package

**Comment by SparkyNZL** [comment]
Hmm its a little strange aye, Operator error no doubt :( Here are some pictures. Hmm Ive just had a thought, do  you still have to enable the scoring system, or is it on by default ? Im getting a nasty gut feeling that ive been a noob

:(

**Comment by doomedraven** [comment]
em that is by default, but i still not see pics :P

**Comment by SparkyNZL** [comment]
![Uploading pic2.jpg…]()

**Comment by jbremer** [comment]
Do you have any Signatures enabled?

**Comment by SparkyNZL** [comment]
Hmm I might not, where would I check that ?

**Comment by jbremer** [comment]
On startup, with `./cuckoo.py -d`, you'll get a list of loaded Signatures.

**Comment by SparkyNZL** [comment]
ok so it has an entry but nothing under it, There are files in the .cuckoo/signatures/ has directories in it, but also files in side of that. But none of these seem to be listed at startup of cuckoo with cuckoo -d

**Comment by jbremer** [comment]
Wait, so are you running `2.0-rc2` or the python package? And if it's the package, what is the latest commit?

**Comment by SparkyNZL** [comment]
in reporting.conf  the
#Show matched cuckoo signatures
show signatures = yes

Oh just spoted your post im using the python package (sorry for not saying that) umm I did an update under 7 days ago, after the correction to submit.

**Comment by jbremer** [comment]
That's just an option for the `mattermost` reporting module, unrelated to the rest of Cuckoo ;-)
Ah, yes, I know what the issue is. For now you'll have to use the `package` branch of `community`, i.e., run `cuckoo community -fb package`. Sorry about that, some big changes regarding Signatures and still have to test backwards compatibility with `2.0-rc1` / `2.0-rc2` of that branch.

**Comment by SparkyNZL** [comment]
awesome thanks for that jbremer, Ill sort that out.

**Comment by SparkyNZL** [comment]
Have you tried running that command ? You might want to have a look at
that, it appears to broken, complains about latest being a directory :(

A>

**Comment by jbremer** [comment]
Interesting. Can you give me the full stacktrace?

**Comment by SparkyNZL** [comment]
Will do ill do that when im finished at work :) Chur

**Comment by SparkyNZL** [comment]
Here is the trace

 cuckoo community -fb package
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.0', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 228, in community
    fetch_community(force=force, branch=branch, filepath=filepath)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/apps.py", line 84, in fetch_community
    t.makelink(member, filepath)
  File "/usr/lib/python2.7/tarfile.py", line 2277, in makelink
    os.unlink(targetpath)
OSError: [Errno 21] Is a directory: '/home/cuckoot/.cuckoo/monitor/latest'

**Comment by doomedraven** [comment]
that because you did change in setup and did with my install instruction, but that strange as that works for me

**Comment by SparkyNZL** [comment]
but i did change the setup.py, and just set variable "latest" like this. 

I dont see how this would effect the above command but i don't have a architecture diagram for cuckoo. 

# through exclude_package_data, but without much luck.

excl, monitor = [], os.path.join("cuckoo", "data", "monitor")
latest = "/home/cuckoo/cuckoo_package/cuckoo/data/monitor"
for h in os.listdir(monitor):
    if h != "latest" and h != latest:
        excl.append(
            "recursive-exclude cuckoo/data/monitor/%s *  # AUTOGENERATED" % h
        )

**Comment by doomedraven** [comment]
just download the monitor part with the same command as in install instructions and place latest from it to `/home/cuckoot/.cuckoo/monitor/latest` and should be done

**Comment by jbremer** [comment]
So what was the reason that you guys modified `setup.py` again? Because that probably shouldn't be required (or done in upstream).

**Comment by doomedraven** [comment]
I was lazy to see which is the hash in latest and then move files to that folder xD
but for me everything works fine :P

**Comment by SparkyNZL** [comment]
I don't see how this will fix the scoring issue. Sure lets fix the setup.py, ill have a look at it this weekend. but copying the latest from the community archive isn't going to fix the scoring issue is it?

**Comment by doomedraven** [comment]
just make this OSError: [Errno 21] Is a directory: '/home/cuckoot/.cuckoo/monitor/latest' a text file and create folder with the same hash and monitor and done

**Comment by doomedraven** [comment]
see the monitor folder when you download it in instalation steps

**Comment by SparkyNZL** [comment]
hmm ok so after i updated the package it the scoring is working. So at
least that is sorted for the mean time, ill look at the python stuff this
weekend and see if i can get a solution for that error :)

Ill use your solution to get the community stuff sorted 1st and then see
what i can come up with. (break out the python books haahah)
