### ISSUE TITLE
How does cuckoo execute a sample?

### ISSUE THREAD

**Issue by Waffles-2** [cuckoosandbox/cuckoo#1269]
I am wondering how cuckoo executes the file? And what process cuckoo goes through to execute the file? For example, does it drop it to temp files and execute it from there? Or run it from memory etc? 

Thanks.

**Comment by doomedraven** [comment]
there you have your answer
https://github.com/cuckoosandbox/cuckoo/tree/master/analyzer/windows/modules/packages

**Comment by Waffles-2** [comment]
So if I wanted to change the drop location of a executable would I change os.environ temp to a file path in analyzer.py or change something in packages/exe.py

**Comment by doomedraven** [comment]
overwrite path and done

**Comment by Waffles-2** [comment]
Sorry, I'm slightly confused, where is the path I should be overwriting?

**Comment by doomedraven** [comment]
that is not a package, https://github.com/cuckoosandbox/cuckoo/blob/master/analyzer/windows/modules/packages/exe.py#L21

**Comment by Waffles-2** [comment]
Changing that path I just get an error. Where does that package get the path location from in the first place? 

ERROR: Analysis failed: The package "modules.packages.exe" start function raised an error: Unable to execute the initial process, analysis aborted.

I'm moving to cuckoo-modified so I will x-post this there.

**Comment by doomedraven** [comment]
lol @jbremer close it

**Comment by Waffles-2** [comment]
SOLUTION: After pouring over the code for the past day I managed to succeed.

On line 854 of analyzer.py you need to change os.environ["TEMP"] to the directory you want the file to be dropped to.

On line 87 of agent.py you need to change os.environ["TEMP"] to the directory you changed it to in analyzer.py.


@doomedraven thanks for pointing me in the right direction, apologies if I offended you.

**Comment by jbremer** [comment]
Actually you can use the undocumented `curdir` analysis option. As in, `cuckoo submit sample.exe -o curdir=C:\\` and it will execute the sample from, well, the `C:\\` directory.

**Comment by Waffles-2** [comment]
Thanks @jbremer I'll be sure to give that a go! Just to shed some light on why I was requesting this, it for a case where a user wouldn't have access to the Temp directory so I was attempting to drop the sample into a shared folder that both the admin and the user could access. 

Thanks for the solution though!
