### ISSUE TITLE
Socket Error on client - Agent unresponsive

### ISSUE THREAD

**Issue by skilgall** [cuckoosandbox/cuckoo#1277]
I'm trying to run a physical machine setup for a long time with possibly multiple machines, but I get an error that makes the machine go down and be unusable long term.  The host error is that the analysis times out, but the client say analysis completed.
The host message:
```
[lib.cuckoo.core.guest] DEBUG: physical1: error retrieving status: timed out
ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
```
The clients agent.py output shows a threading/socket error:
<img width="644" alt="screen shot 2017-02-07 at 3 07 55 pm" src="https://cloud.githubusercontent.com/assets/12789486/22709370/8f1b00ec-ed47-11e6-99b8-19b38a1f79ea.png">

Then the machine stays in this error'd out state unable to accept any more analyses:
```
[modules.machinery.physical] DEBUG: Checking if machine u'physical1' is running.
[modules.machinery.physical] DEBUG: Getting status for machine: physical1.
[modules.machinery.physical] DEBUG: Agent unresponsive: 1 (IP) (Error: timed out).
[modules.machinery.physical] DEBUG: Getting status for machine: physical1.
[modules.machinery.physical] DEBUG: Agent unresponsive: 1 (IP) (Error: timed out).
[lib.cuckoo.common.abstracts] DEBUG: Waiting 0 cuckooseconds for machine physical1 to switch to status ['running']
[modules.machinery.physical] DEBUG: Getting status for machine: physical1.
[modules.machinery.physical] DEBUG: Agent unresponsive: 1 (IP) (Error: [Errno 111] Connection refused).
```
(Error: [Errno 111] Connection refused) Keeps happening forever.  Can this error be caught?

**Comment by leotant** [comment]
I am experiencing the same issue. Any comments on this?

**Comment by jbremer** [comment]
Could the both of you please let me know which version of OS, Cuckoo, FOG, and other software you're using? Thanks!

**Comment by leotant** [comment]
Sure. I'm running:
Windows 7 Professional x64 on my guest physical Machine. 
Cuckoo Sandbox 2.0-RC2 
Fog 1.2.0
Ubuntu 14.0.4 on my host

**Comment by jbremer** [comment]
Could you perhaps give #1288 a try?

**Comment by seantree** [comment]
Hi @leotant,

my centos 7 is showing Agent unresponsive: (192.168.0.11), Error Timeout and connection refused.

Thanks & Regards
Seantree

**Comment by jbremer** [comment]
Did anyone here try PR #1288? Perhaps it resolves some issues presented here.

**Comment by jbremer** [comment]
Closing issue for lack of additional information.
