### ISSUE TITLE
Cuckoo API and Viper

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1286]
I have been trying to get these two to work together but it looks like the API calls have changed in cuckoo so VIPER cant submit any longer ?

 GET /cuckoo/submit?hash=4f3128f77da8c37d809724d54f782c23c265da188f7307c67d68195c71010c7a

 is the command , but i cant see where /cuckoo/submit is an API command any longer ? is this correct ?

Cheers
A.

**Comment by jbremer** [comment]
That has never been a feature in upstream Cuckoo. Perhaps it's a `cuckoo-modified` feature. We do have this functionality in our new Web Interface, perhaps also a good idea to put it in the API :-)

**Comment by SparkyNZL** [comment]
Sorry , you are correct it was for a modified version of Cuckoo, bugger, Ill point it at the web interface and see what happens :) LOLz @jbremer

**Comment by jbremer** [comment]
Nah, let's keep it open for now. It's a good-to-have feature anyway.

**Comment by razuz** [comment]
just checked - seems slight mis-comm (at least from web) and few hardcoded vars

@SparkyNZL you use cli or web on viper to submit ?

**Comment by SparkyNZL** [comment]
I was using the Web interface, i can try the CLI

**Comment by razuz** [comment]
right, so might want to modify the parameters right now in here : https://github.com/viper-framework/viper/blob/master/viper-web#L51-L53
I still had some odd response behaviour linking back to wrong ID, but taking a look into that to make it work with cuckoo aswell

**Comment by SparkyNZL** [comment]
thanks so much :)
