### ISSUE TITLE
Cuckoo on VirtualBox

### ISSUE THREAD

**Issue by npormambi** [cuckoosandbox/cuckoo#1287]
Hello All,
I am trying to deploy cuckoo in Virtual Box.
I have two VM one is Ubuntu (Cuckoo Machine ) and other is XP.
Both the systems are in Host Only Mode.
I have provide Internet to Ubuntu its working perfectly file.
Followed this article
http://santi-bassett.blogspot.in/2013/01/installing-cuckoo-sandbox-on-virtualbox.html
The only problem is when I run cuckoo.py  on Ubuntu gives me below error.

Checking for updates...
Failed! unable to establish connection.

CRITICAL: CuckooCriticlaError: Unable to import plugin "modules.processing.behavior": No module named dateutil.parser

Anyone is aware of this issue.

Thanks,
Npormabi

**Comment by doomedraven** [comment]
You habe not installed dependencies, check official manual

**Comment by npormambi** [comment]
@doomedraven  
Thanks for update
But I have cross checked all the requirement but still getting same error.

Thanks,
Npormambi

**Comment by jbremer** [comment]
`pip install -r requirements.txt`, as the documentation mentions. Closing as resolved ;-)

**Comment by npormambi** [comment]
@jbremer  trying to install the same but getting error now :(

**Comment by doomedraven** [comment]
no log no error :P

**Comment by doomedraven** [comment]
btw provide more details, as os, cuckoo version etc etc etc

**Comment by npormambi** [comment]
@doomedraven 
I have win 7 as my Host OS, I have installed oracle Box.
Ubunt and Win7 are guest OS on it
Using Ubuntu(14.04.4 LTS) for cuckoo installation.
Using Win 7 as analysis system
cuckoo i have downloaded from below url
https://github.com/cuckoosandbox/cuckoo.git
Attached is the error i m getting
![cuckoo error](https://cloud.githubusercontent.com/assets/16058609/23073658/4824daa6-f55c-11e6-8448-366516436d4d.jpg)

Thanks,Npormabi

**Comment by doomedraven** [comment]
`sudo apt-get install python-dateutil` google is your friend

**Comment by npormambi** [comment]
@doomedraven getting below error
CucckooCriticalError: VirtualBox VBoxManage not found at specified path "/usr/bin/VBoxManage

As mentioned earlier I am running cuckoo(ubuntu) box as VM on Oracle Virtual Box.

Thanks,
Npormambi

**Comment by doomedraven** [comment]
have you installed vbox inside of vm(cuckoo)?

**Comment by npormambi** [comment]
nopes..
Bcz already cuckoo is running inside Oracle Virtual Box, 
Is it possible to install vbox inside os which is already on vm? :)

**Comment by doomedraven** [comment]
if you don't install it, how do you think to run vms? :D

**Comment by jbremer** [comment]
We don't officially support running Cuckoo from inside a VM. Please either use a sane setup (i.e., run Cuckoo on the host machine as per our documentation) or resolve the issues on your own.

**Comment by npormambi** [comment]
@jbremer 
thanks for the update.
btw, thats why I was constantly mentioning my setup configuration
I thought it will work
Anyways thanks @doomedraven  & @jbremer 


Thanks
Npormambi

**Comment by doomedraven** [comment]
it will work but(probably with poor perfomance), everything depends of your hardware

**Comment by jbremer** [comment]
Ah, I missed that part, sorry ;)

**Comment by npormambi** [comment]
@jbremer  No Worries,
@doomedraven  will spend some more time on it
If get some solution will let you know, :)


Thanks
Npormambi
