### ISSUE TITLE
'NoneType' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by nziqua** [cuckoosandbox/cuckoo#1289]
Hi,
when i try to log on in web interface, i get error:
'NoneType' object has no attribute 'strftime'
[debug_log.txt](https://github.com/cuckoosandbox/cuckoo/files/783251/debug_log.txt)

when i startup web by manage.py, a get the same error:

Django version 1.8.4, using settings 'web.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/cuckoo/web/dashboard/views.py", line 53, in index
    started, completed = db.minmax_tasks()
  File "/opt/cuckoo/web/../lib/cuckoo/core/database.py", line 1218, in minmax_tasks
    return int(_min[0].strftime("%s")), int(_max[0].strftime("%s"))
AttributeError: 'NoneType' object has no attribute 'strftime'

**Comment by heartbleeded** [comment]
Hi, I have the same problem while importing an analysis. How did you solve it?

**Comment by jbremer** [comment]
Hi, yes. For now you can resolve this issue by actually analyzing some samples (iirc) or by applying the first part of the following commit b736b42adbaade1dc447ba61aaf62d2ef3ca17a5. If you have any more questions, do let me know!
