### ISSUE TITLE
Poor or no response via the Web interface - package

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1296]
I have noticed that when requesting items which were submitted a wile back im getting the following error or a 302 which doesn't progress to anything more and sits there until it times out.  this happens when requesting a direct URL get not going to " recent" and then clicking the link to the analysis, and more with .

As you can see from the below this ending with a stack trace,

[23/Feb/2017 09:56:28] "GET /analysis/30000/summary/ HTTP/1.1" 200 52005
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer

**Comment by jbremer** [comment]
Hm, unfortunately this is not something I can do much with. If anything I'd say that the backend (MongoDB?) is just really slow causing the socket to be closed. There's still a lot of new goodies coming up in the web interface as I'm currently porting revisiting older code etc and ensuring everything works smoothly, so if you can hold out a few more days.. :-)
Thanks for letting me know though, but as you can see there's no Cuckoo-specific code in the stacktrace due to which I can't really pinpoint the issue.

**Comment by SparkyNZL** [comment]
All good, just letting you know, Im going to check the database tonight and make sure something hasn't died in there. It seems the more recent are all good, but the older the summary the more likely there to be a time out. 

Cheers

**Comment by razuz** [comment]
sounds like the issue is mongo ... make sure you're running on rocksdb engine ... I'm running few TB percona mongodb (https://www.percona.com/software/mongo-database/percona-server-for-mongodb) and it's alright. Before moving to rocksdb I had very odd issues

**Comment by SparkyNZL** [comment]
ok ill give that a go, i 2 are having weird issues , sometimes it works other times it doesnt :(

Cheers

**Comment by SparkyNZL** [comment]
I can confirm this has muchly improved the response from the web server :) it seemed to take about an hour before i started getting great response times, not sure if it reindexes the database, but it working great now :)
