### ISSUE TITLE
ResultServer unable to map ip to context

### ISSUE THREAD

**Issue by tehfcae** [cuckoosandbox/cuckoo#1297]
Whenever I attempt to go 192.168.56.1:2042, I get the error 'CRITICAL: ResultsServer unable to map ip to context: 172.16.149.224'

My result server in cuckoo.conf is set to ip 192.168.56.1 port 2042.

My vboxnet0 IP address is 192.168.56.1, but my ens33 address is 172.16.149.255. Is that the issue is there something else I should investigate?

**Comment by razuz** [comment]
it shouldn't try to map it to ens33 address ... is vboxnet0 up ?

**Comment by jbremer** [comment]
Are you trying from the host to connect to that port? I'm asking because you mention that you have a specific interface with that IP range while you should only be connecting to it from your VMs, which should be on the same IP range.

**Comment by SparkyNZL** [comment]
if you type in ifconfig does vboxnet0 appear in the output? if now make sure you have setup the host only adapter in virtualbox.

**Comment by jbremer** [comment]
Any update @tehfcae? If not I'll be closing this issue shortly.

**Comment by tehfcae** [comment]
I was attempting to connect from the host which was probably the issue. My partition was too small for a second vm so I had to resize stuff and just got back to everything.

I have gotten a few errors since but I think they have been resolved in other issues. Thanks for your help.
