### ISSUE TITLE
Cuckoo/MISP integration issue

### ISSUE THREAD

**Issue by Tux-Panik** [cuckoosandbox/cuckoo#1298]
Hi all,

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | 7
| Cuckoo version / git hash   | 2.0-RC2
| Browser                   | N/A

### Expected behavior
Allow communication and sharing information between standalone MISP server and Cuckoo (standard) server.

### Actual behavior
I reach an error about timeout on Cuckoo side when a sample is submitted.
This error indicates that Cuckoo knows that it must contact MISP to enrich analysis.

### Steps to reproduce the behavior
PyMISP is installed on both sides (MISP and Cuckoo) and it has been updated.
Configuration ha been made using the official tutorial.
Modified files are:
$CUCKOO_LOCATION/conf/processing.conf
$CUCKOO_LOCATION/conf/reporting.conf

APIkey and URL are good and verified.
HTTP has been allowed to discard SSL protocol issue.

Running a PyMISP script sample (last.py) from Cuckoo server server works (first log section below).
**But when a sample is submitted to Cuckoo, I reach the following error on Cuckoo side.** (second log section below). In this case, there is no connection on MISP side.

### Logs, screenshots, configuration dump, ...
**1st section**:
```
xxx.xxx.xxx.xxx - - [23/Feb/2017:14:17:07 +0100] "GET /servers/getPyMISPVersion.json HTTP/1.1" 200 20 "-" "PyMISP 2.4.65 - Python 2.7.5"
xxx.xxx.xxx.xxx - - [23/Feb/2017:14:17:07 +0100] "GET /attributes/describeTypes.json HTTP/1.1" 200 15178 "-" "PyMISP 2.4.65 - Python 2.7.5"
xxx.xxx.xxx.xxx - - [23/Feb/2017:14:17:07 +0100] "POST /events/restSearch/download HTTP/1.1" 200 910165 "-" "PyMISP 2.4.65 - Python 2.7.5"
```

**2nd section:**
```
2017-02-23 14:20:43,677 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "MISP" for task #87:
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/modules/processing/misp.py", line 81, in run
    self.misp = PyMISP(self.url, self.apikey, False, "json")
  File "/usr/lib/python2.7/site-packages/pymisp/api.py", line 113, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
PyMISPError: Unable to connect to MISP (http://<my_misp_url_is_correctly_set_here>/). Please make sure the API key and the URL are correct (http/https is required): 504 Server Error: Gateway Timeout
```

Please,
**- Have you any idea about this error?**
**- Can you confirm that interaction between them are made on port 80/443?**
**- Can you tell me where can I find more traces/logs?**

Thanks,
Regards,

**Comment by doomedraven** [comment]
it looks like you have some configuration errors as server returns 504 error 

try to create event with pymisp manually

```
from pymisp import PyMISP
from datetime import datetime
misp = PyMISP("url" ,"APIKEY", False, 'json')
event = misp.new_event(1, 1, 1, "test", date=datetime.now().strftime('%Y-%m-%d'), published=True, org_id="1", orgc_id="4")
```

if you can see it than it works, but i think that will fail

**Comment by Tux-Panik** [comment]
Thanks for your reply.
Just tried and it works.
I can find the event in my MISP instance.

**Comment by doomedraven** [comment]
Hm is there some proxi or somethig?  As it sais ir cant to connect to misp, PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e)) 

Btw you try reporting or processing mips module? You filled them?

**Comment by Tux-Panik** [comment]
There are no proxy or firewall between Cuckoo and MISP.
It's still a lab.
I filled "processing.conf" & "reporting.conf" files like this: [](https://github.com/xme/cuckoo/tree/master/config)https://github.com/xme/cuckoo/tree/master/config
Can it be a setting mistake in the network interface used by my Cuckoo console?

**Comment by doomedraven** [comment]
Could be, use oficial configs to avoid some problems, did you replace oficials with those?

**Comment by Tux-Panik** [comment]
Yes I did. I only wanted to explain that I've strictly filled fields, like APIkey and URL.

**Comment by SparkyNZL** [comment]
did you set up MISP as the guidelines ? If so it should be https not http, you also need to make sure that the workers are all running also. Im running Cuckoo package and the latest MISP at the moment.

**Comment by Tux-Panik** [comment]
MISP as been installed using official documentation.
All steps have been finally lead successufully.
I met some errors with "scheduler" worker, but finally I could resolve it (permission issue).
About HTTP/HTTPS, my instance only listen on TCP/443, but regarding this issue I decided to enable TCP/80 (without SSL of course) to exclude this origin.
If communication works a day, I'll disable TCP/80 to secure connection (I'm on a lab and not on production)
Thanks guys.

**Comment by SparkyNZL** [comment]
Did you check to make sure all of your worker are working ? you can long into mine and have a play around its not prod and its just my malware lab, but have a poke, flick me an email and ill send you some admin creds sparkynzl at g mail.

**Comment by SparkyNZL** [comment]
also if you go into administration on MISP and then Server setting and then Diagnostics check to make sure that is all "OK".

**Comment by jbremer** [comment]
So just to verify, `2.0-rc2` doesn't have a MISP reporting module. Did you add that in yourself or are you running a development version of Cuckoo (i.e., `master` branch)? Could it be that the analyses you're trying out has a *lot* of IOCs and as such the queries that are sent off to MISP trigger timeout issues? (We're currently experiencing gateway timeout issues, hence the question).

**Comment by Tux-Panik** [comment]
@SparkyNZL: I'm using an IP address to reach my MISP instance. All my workers are fine.
@jbremer: I add the [MISP] section, following a tutorial [ https://github.com/xme/cuckoo/tree/master/config](url). I'll change my sample, but it's just a tricky .dll not very verbose. But may be... I'll keep you in touch and I'll share closer network traces.
Regards,

**Comment by Tux-Panik** [comment]
As expected, network traces are empty:

- Cuckoo doesn't initiate connection to MISP.
- MISP doesn't receive any connection from Cuckoo.

I restarted all my workers.
I also realize that a proxy is specified in Cuckoo's bash environnement, to allow Virustotal connexions.
May be all flows are proxied and, in this case, the MISP server (in same subnet) is unreachable.
If I disable proxy setting, Virustotal check is KO, but MISP API query seems to be OK (according to logs).

I'll try again with a more malicious sample and I'll keep you in touch.
Thanks

**Comment by jbremer** [comment]
So why do you have a proxy in-place for VirusTotal?

**Comment by Tux-Panik** [comment]
@jbremer Is think you know my answer: "To allow outbound connection to VirusTotal..."
Your question reveal a dark subject, as I can read it...
`Might as well just add an internal IP address for www.virustotal.com into /etc/hosts and go for some proxying black magic from there.`
Is it your recommandation?

**Comment by jbremer** [comment]
Using `/etc/hosts` would probably be a better solution, yes ;-) Unless we *blacklist* proxies for more HTTP requests made throughout Cuckoo, most of those requests will go through the proxies specified in the environment variables.

**Comment by SparkyNZL** [comment]
@jbremer MISP reporting pluging seems to get slower and slower to the point it processed 121 reports in 8 hours ! eeek, have you guys experienced this?

**Comment by doomedraven** [comment]
strange, I never saw it works in that way, maybe somehow related to misp server specs?

**Comment by SparkyNZL** [comment]
it weired and if i enable the MISP in reporting you get a lot of 500 error but we know about that. I have 16g and 4 processor assigned to the MISP instance so its doing ok

**Comment by jbremer** [comment]
I haven't used MISP on scale yet myself, but surely there could be some performance bottlenecks.
@adulau @rafiot Do you happen to know about any obvious performance issues in MISP? Alternatively, would there be a way for @SparkyNZL to export his data set so that you can triage any such performance issues (of course if he's able to do so, otherwise I'll manage to find a data set elsewhere)?

**Comment by SparkyNZL** [comment]
ive dont all the usual regarding latency to the databases etc, and the Web
instance, Im going to do another install of it this weekend and see if it
fixes it,

**Comment by Rafiot** [comment]
@SparkyNZL Can you give me more details? My first guess would be an untuned MySQL, which is going to be insanely slow.

**Comment by SparkyNZL** [comment]
Yes I agree @Rafiot Im going to have a look at this over the weekend and see if i can tune it up.

**Comment by Tux-Panik** [comment]
Hi found an efficient work around using $no_proxy. In a terminal:

> export HTTP_PROXY="http://<your_proxy>:<port>"
export HTTPS_PROXY=$HTTP_PROXY
export no_proxy="127.0.0.1,.localhost,<your_misp_subdomain_and_domain>"
