### ISSUE TITLE
[Question] How to enable stacktrace?

### ISSUE THREAD

**Issue by pinksawtooth** [cuckoosandbox/cuckoo#1301]
Please tell me how to enable stacktrace in "report.json".
I can not find it in the document and configuration files.

```
"calls": [
                    {
                        "category": "exception", 
                        "status": 0, 
                        "stacktrace": [], 
                        "last_error": 0, 
                        "nt_status": -1073741515, 
                        "api": "SetUnhandledExceptionFilter", 
                        "return_value": 0, 
                        "arguments": {}, 
                        "time": 1488017642.913614, 
                        "tid": 4940, 
                        "flags": {}
                    },
```

**Comment by jbremer** [comment]
That's just a Windows API call that we intercept, it's not actually an exception. Closing this issue ;)
Let us know if you have additional questions etc.

**Comment by pinksawtooth** [comment]
@jbremer 
I want to record the stack trace (caller) at the time of all API tracing.
Like this, https://github.com/arbor-jjones/idataco/blob/master/taco_ruxcon.pdf
How do I modify it?
