### ISSUE TITLE
CSV Analysis Report

### ISSUE THREAD

**Issue by bnder321** [cuckoosandbox/cuckoo#1304]
Hello Everybody.

I have analysed hundreds of files. Unfortunately, the reports are either json or html. For my task, I need CSV files to work with some machine learning techniques. Does cuckoo support such type of reports?

Thank you..

**Comment by doomedraven** [comment]
No, but you can write that kind of reporting module http://docs.cuckoosandbox.org/en/latest/customization/reporting/

**Comment by jbremer** [comment]
You can convert the JSON file to your CSV format of choice in a matter of minutes. Closing this issue. Please let us know if you've been working on interesting ML stuff that you're willing to share back with the community.
