### ISSUE TITLE
Cuckoo - Package - Scoring module

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1305]
Hi again :)
Can anyone point me in what conf file you turn this on, i the upgrade last night and now all my samples are scored as "0" :( Ive looked through them, but can;t for the life of me find it :(

Cheers

**Comment by jbremer** [comment]
Can you please try to re-run `cuckoo community`? I've just pushed https://github.com/cuckoosandbox/community/commit/2663f9776fa8745f8c877ddaf49c7e80b8235b60 which I guess was still missing from there ;-)

**Comment by SparkyNZL** [comment]
just doing it now :)

**Comment by SparkyNZL** [comment]
Fixed :)
