### ISSUE TITLE
Setting up Cuckoo with Nginx

### ISSUE THREAD

**Issue by cvdsouza** [cuckoosandbox/cuckoo#1321]
Hi , 
I'm attempting to set up Cuckoo with nginx and was wondering if there is a guide that would help me with the set up or any pointers that could help with the set up? I've usually set up applications with apache2, however this time I need to use nginx for this project. Any pointers would be very much appreciated. 

Thanks

**Comment by jbremer** [comment]
If you use the Python package (see #863), then you may want to read the following https://cuckoo.sh/docs/usage/web.html#web-deployment. For `2.0-rc2` you can use similar'ish steps.

**Comment by cvdsouza** [comment]
@jbremer Thank you for the suggestion. Up and running with nginx . Used the cuckoo docs and tip here : https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27 to get up and running. Facing issues with the VM but have commented on another issue about it. 

Thanks.
