### ISSUE TITLE
Looks like there might be a memory leak in cuckoo or yara  - Best i can call it

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1322]
So ive noticed that my cuckoo instance has started to run out of memory ( i have 70gig) of ram allocated to it. I have also see this error a number of times and it correlates with something running away in memory whether that be cuckoo or yara im un-sure.. but here are the details, all cuckoo processes are "cuckoo process auto" and it pretty much consumbed 70gig + 30gig swap , and in the end i had to kill both processes to get things back to a usable state.

My guesses is either a rogue yara rule (but i would think it would do this on ever sample)
A memory leak in Yara ?
A memory leak in cuckoo ?

----------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 370, in get_yara
    matches = File.yara_rules[category].match(self.file_path)
Error: internal error: 30

----------------------------------------------------------------------------------------------

![screenshot from 2017-03-07 17-35-01](https://cloud.githubusercontent.com/assets/17818264/23642132/58687544-035d-11e7-8864-90923a34108e.png)
![screenshot from 2017-03-07 17-35-58](https://cloud.githubusercontent.com/assets/17818264/23642136/5e22ab30-035d-11e7-852b-0c17cf736341.png)

----------------------------------------------------------------------------------------------

**Comment by jbremer** [comment]
Please check with `htop`, 99% sure that it the `cuckoo -d` processes are at fault, rather than `cuckoo process auto`.

**Comment by SparkyNZL** [comment]
here is the HTOP , sorry i was a little short on time, but it was sitting at 3.9gig and growing, it just continues to grow until i run out of memory :(

![screenshot from 2017-03-08 20-23-49](https://cloud.githubusercontent.com/assets/17818264/23694219/76f6e8b6-043d-11e7-8299-b6dab2f15900.png)

**Comment by jbremer** [comment]
@SparkyNZL you do have to give unique names to `cuckoo process` though, not multiple times `auto`. Perhaps I should simplify that..

**Comment by SparkyNZL** [comment]
Sorry, im a tard, ill see if that make a difference :)

**Comment by SparkyNZL** [comment]
ok so i opened up 10 processing instances, these had names 1 - 10 so all unique,  there were 4 stuck for over 2 hours with a consumption of over 55gigs of RAM.

I had to kell a nuber of thtme to make the system respond in a decent way.

![screenshot from 2017-03-09 13-23-44](https://cloud.githubusercontent.com/assets/17818264/23730458/4963a60c-04cc-11e7-9d29-36162daf892a.png)

**Comment by SparkyNZL** [comment]
Here is some more details .
I have run just one processing instnce,
Here are the results.
I think it is hanging on the Yara rules, im going to delete them (i have about 150 rules in place) and see if that fixes the problem. Id there any way to see which rule its hanging on ?

A.

------------------------------------------------------------------------------

2017-03-10 02:00:24,134 [cuckoo.apps.apps] INFO: Task #23370: reports generation completed
2017-03-10 02:00:25,406 [cuckoo.apps.apps] INFO: Task #23371: reporting task
2017-03-10 02:00:40,210 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/23371"
2017-03-10 02:00:40,434 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" on analysis at "/home/adroot/.cuckoo/storage/analyses/23371"
2017-03-10 02:00:40,549 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" on analysis at "/home/adroot/.cuckoo/storage/analyses/23371"

------------------------------------------------------------------------------------

![screenshot from 2017-03-10 08-20-08](https://cloud.githubusercontent.com/assets/17818264/23766656/a26872d4-056a-11e7-985b-a2c0cce89c0b.png)

--------------------------------------------------------------------------------------------

![screenshot from 2017-03-10 08-13-51](https://cloud.githubusercontent.com/assets/17818264/23766660/a570a44c-056a-11e7-812c-08165bc10e11.png)

-----------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
Question for you @jbremer , when the yara rules are run, does it only run against the submitted file, or does it run then against all the dropped files as well ? Im slowly tracing this issue back up the chain, but knowing this answer will save me a lot of time.

**Comment by SparkyNZL** [comment]
Found the issue, there were 2 bad yara rules which caused these symptoms , I have isolated them and chucked them into an archive, its a little odd, one is just a base64 with a straightforward regex and the other one is much more complex but, i guess this can be closed now, weird thing is, is if i run this manually with yara -g index_binary.yar <file> it works fine :(

**Comment by doomedraven** [comment]
can you share which exactly yara causes that?

**Comment by SparkyNZL** [comment]
Hi @doomedraven I have just emailed them to jbremer, i can email them to you too if you would like ? ill need your email though or email me at sparkynzl at gmail .

**Comment by doomedraven** [comment]
email sent :)

**Comment by SparkyNZL** [comment]
here it is, the password is infected

**Comment by SparkyNZL** [comment]
i got a number of requested, everyone should have them now
it should be base64.yar and crypto_signatures.yar

**Comment by SparkyNZL** [comment]
keep in mind im using the Packaged version of Cuckoo

**Comment by doomedraven** [comment]
thanks :)

**Comment by SparkyNZL** [comment]
should i close this now ?

**Comment by jbremer** [comment]
Guess so yeah. Thanks!

**Comment by SparkyNZL** [comment]
this doesn't seem to be an issue any longer with Yara 3.5 so not sure what
has changed. I ran my 10K samples through and non hung.
