### ISSUE TITLE
to know about maec parser and schema in cuckoo 

### ISSUE THREAD

**Issue by vineetabajaj** [cuckoosandbox/cuckoo#1325]
i want to knw how differnt tools in cuckoo are giving output in maec format i.e., xml.
Can you help me understanding the schema by which its is giving output?

**Comment by doomedraven** [comment]
check https://github.com/cuckoosandbox/cuckoo/tree/master/modules/reporting

**Comment by jbremer** [comment]
We haven't had MAEC reporting since quite a while. MAEC was just a different representation of the data that we already have in our JSON report. What is your question @vineetabajaj?

**Comment by vineetabajaj** [comment]
i want to which different tools are used in cuckoo for analysis.
like for static analysis, it have pefile.

**Comment by vineetabajaj** [comment]
I want to know which tools are used inside cuckoo sandbox.
like for static analysis , there is pefile.

**Comment by jbremer** [comment]
Take a look at, e.g., https://github.com/cuckoosandbox/cuckoo/tree/master/modules/processing.
There are many components used in Cuckoo and I'm not going to list all of them here, so please look around the repository.

**Comment by vineetabajaj** [comment]
I am trying to track how a tool run, and maintain its log and giving output in xml.
where i can find these parser without using cuckoo, please help me in tracking info so that i can make use of parser for different tool.
