### ISSUE TITLE
run ./utils/api.py error!!

### ISSUE THREAD

**Issue by MrJeffyw** [cuckoosandbox/cuckoo#1326]
when I run ./utils/api.py , I got "Running on http://localhost:8090/". But when I access this address, I got 404 not found! Can anyone teli me why? Thanks a lot.

**Comment by jbremer** [comment]
Well, there's no API endpoint for `/`. Please try any of the URLs from our documentation :)

**Comment by jbremer** [comment]
E.g., `/cuckoo/status`. Closing as this is not an actual issue.
