### ISSUE TITLE
Cuckoo Package, Elasticsearch

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1334]
Evening guys,

Hey noticeed this has started popping up, I Haven't changed my config and am a little lost at what is causing this message. Do you know if there has been a fix for error 2 I did a search but didnt really find a resolution ?

----------------------------------------------------------------------------

error 1
2017-03-13 08:38:39,029 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #45561: 'module' object has no attribute 'helpers',

------------------------------------------------------------------------------

error 2
2017-03-13 08:42:55,783 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #45575: TransportError(400, u'mapper_parsing_exception', u'object mapping for [signatures.marks.section] tried to parse field [section] as object, but found a concrete value')

-------------------------------------------------------------------------------

**Comment by jbremer** [comment]
Please check #1196. I'm hoping to merge it soon, but awaiting some feedback.

**Comment by SparkyNZL** [comment]
Sweet Ill make some changes and see what happens,
:) Ive just send @doomedraven  the binary which causes a couple of yara rules to hang

**Comment by SparkyNZL** [comment]
Hi Jurriaan,

I updated the elasticseach template, deleted the index and rerun the tast,
but this errir is still popping up, but there seems to be data going into
the index as it is growing

------------------------------------------------------------------------------

2017-03-14 17:24:09,140 [cuckoo.core.plugins] DEBUG: Executed reporting
module "Moloch"
2017-03-14 17:24:14,672 [cuckoo.core.plugins] WARNING: The reporting module
"ElasticSearch" returned the following error: Failed to save results in
ElasticSearch for task #50500: 'module' object has no attribute 'helpers'
2017-03-14 17:24:20,012 [cuckoo.core.plugins] DEBUG: Executed reporting
module "MongoDB"
2017-03-14 17:24:20,034 [cuckoo.apps.apps] INFO: Task #50500: reports
generation completed

---------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
Hey guys ive tried to sort this but to no avail, it is a new error which has croped up since the last build, so all i can think it is that its a bug rather than a config fault. I have carried out what #1196 . its fixed this error

2017-03-13 08:42:55,783 [cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #45575: TransportError(400, u'mapper_parsing_exception', u'object mapping for [signatures.marks.section] tried to parse field [section] as object, but found a concrete value')

but not the other one :(

**Comment by dalgomtaeng** [comment]
maybe @SparkyNZL see analysis in web_ui, find something similar to the picture at below![image](https://cloud.githubusercontent.com/assets/16236106/24024683/a84b5e8a-0af8-11e7-8f91-d5fb44ca84ca.png)
that covert json
`"marks": [{"section": "UPX0", "type": "generic", "description": "Section name indicates UPX"}, {"section": "UPX1", "type": "generic", "description": "Section name indicates UPX"}]`
Elasticsearch does not allow multiple objects of the same name in an array.

**Comment by dalgomtaeng** [comment]
maybe @SparkyNZL see analysis in web_ui, find something similar to the picture at below
![image](https://cloud.githubusercontent.com/assets/16236106/24025864/7fc4208e-0b00-11e7-87c0-0dfe6562aaa2.png)
that covert json

"signatures": [
{"markcount": 0, "families": [], "description": "Performs some HTTP requests", "severity": 2, "marks": [], "references": [], "name": "network_http"},
{"markcount": 2, "families": [], "description": "The binary likely contains encrypted or compressed data.", "severity": 2, "marks": [{"entropy": 7.887608192093195, **"section": {"size_of_data": "0x0000a400", "virtual_address": "0x00018000", "entropy": 7.887608192093195, "name": "UPX1", "virtual_size": "0x0000b000"}, "type": "generic", "description": "A section with a high entropy has been found"}**, {"entropy": 0.9111111111111111, "type": "generic", "description": "Overall entropy of this PE file is high"}], "references": ["http://www.forensickb.com/2013/03/file-entropy-explained.html", "http://virii.es/U/Using%20Entropy%20Analysis%20to%20Find%20Encrypted%20and%20Packed%20Malware.pdf"], "name": "packer_entropy"}, 
{"markcount": 2, "families": [], "description": "The executable is compressed using UPX", "severity": 2, "marks": [{**"section": "UPX0"**, "type": "generic", "description": "Section name indicates UPX"}, {**"section": "UPX1"**, "type": "generic", "description": "Section name indicates UPX"}], "references": [], "name": "packer_upx"}]

Elasticsearch does not allow multiple objects of the same name but different structures in the array. So
Can't merge a non object mapping [signatures.marks.section] with an object mapping [signatures.marks.section]

**Comment by jbremer** [comment]
Is this still an actual issue @SparkyNZL?

**Comment by SparkyNZL** [comment]
nope this issue has been fixed. Ill close it
