### ISSUE TITLE
about processing pcap with libpcap

### ISSUE THREAD

**Issue by xvsfekcn** [cuckoosandbox/cuckoo#1336]
I would like to ask a question, why not process the pcap when catpure the pcap from the interface, for example use libpcap to capture the pcap and process the pcap to get the infomation what we want and store to the disk.

**Comment by xvsfekcn** [comment]
what about this?

**Comment by jbremer** [comment]
What about it? You want to apply realtime filtering on the PCAP?

**Comment by xvsfekcn** [comment]
Yes, i want to apply the realtime processing . but it seems not necessary now
