### ISSUE TITLE
cuckoo package : Submit issue (File)

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1340]
When i try and submit a file in the WGUI eveything seem to work well with the pre submit form, but when i actually hit analyse i get the following..

It looks like to me, that the GUI think that there has only been 27 items submitted, but i have submitted over 70000 items via the "cuckoo submit" command.

If i try and submit another item , the number increases from 27 to 28 and so forth.

Web server logs

[16/Mar/2017 20:18:53] "POST /submit/api/filetree/ HTTP/1.1" 200 1155
[16/Mar/2017 20:18:54] "POST /analysis/api/tasks/stats/ HTTP/1.1" 200 183
[16/Mar/2017 20:18:55] "POST /submit/api/submit HTTP/1.1" 200 33
[16/Mar/2017 20:18:55] "GET /submit/post/27 HTTP/1.1" 500 12001

![submit](https://cloud.githubusercontent.com/assets/17818264/23986081/3de670be-0a87-11e7-83fc-652e4fbce642.jpg)

**Comment by jbremer** [comment]
Running `cuckoo submit` is unrelated to submitting a file through the new web interface, so the number 28 isn't odd there. Most likely you submitted a file that Cuckoo/SFlock didn't know how to handle, could you share some hashes so I can check it out?

**Comment by SparkyNZL** [comment]
you are once again correct ! DAMNIT ! :) i was stuffing around with some files and had renamed a txt file to and exe and guess what  ? it didnt work :)

**Comment by jbremer** [comment]
@SparkyNZL Well, I'd still like to see the sample (if possible) so that `500 error` screens will not be necessary again in the future. I have a sample myself as well, but more is always better :)

**Comment by SparkyNZL** [comment]
Hi @jbremer 

Ok so you are right about the file type, but it will only accept exe, I get a 404 on PDF, Png, Txt, Bin even if i say to run them as an executable. 

There are also some major issues with cuckoo 2 and IE (not that anyone with a brain uses this) but its kinda broken, and even worse in compatibility mode hahaha :(

IE 11
![capture](https://cloud.githubusercontent.com/assets/17818264/24068275/9e505a50-0bef-11e7-99ac-cd2cc4ea6eab.JPG)

**Comment by SparkyNZL** [comment]
This is no longer an issue
