### ISSUE TITLE
Websites not working, CSRF verify failed and bad gateway

### ISSUE THREAD

**Issue by jay** [cuckoosandbox/cuckoo#1345]
Hello, I'm trying to submit a sample for analysis on http://sandbox.pikker.ee/submit/ but it keeps telling me CSRF error. I can't figure out if this project is affiliated with that website but it identifies as cuckoo.

~~~
CSRF verification failed. Request aborted.
You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.
Help
Reason given for failure:
    CSRF cookie not set.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function passes a request to the template's render method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.
~~~

I would have asked about this issue in your https://community.cuckoosandbox.org/ first but that says `502 Bad Gateway`.

**Comment by doomedraven** [comment]
I dont think is affilated, anybody can deploy their cuckoo :)

**Comment by jay** [comment]
Ok. I did a whois on that website and e-mailed the contact. There is still the issue of community.cuckoosandbox.org not working though.

**Comment by jbremer** [comment]
Looping in @razuz as he's hosting that Cuckoo instance.
Regarding community - while it's down, please stick to Github issues & IRC :)

**Comment by heikipikker** [comment]
Site is not down. You get this error if you submit you sample over non-secure URL.
Try https://sandbox.pikker.ee/submit/ instead http://sandbox.pikker.ee/submit/

**Comment by jay** [comment]
Thanks, indeed that was the problem. Also thank you for your e-mail. It is working with https. http I don't get redirects in Firefox or Chrome to https.

Is there a way to specify arguments to the program? I'm submitting a sample curl.exe and I want to run curl.exe google.com so in the 'options' advanced field I put google.com. I turned on a web debugger and I can see it's submitted in options but it's not used as an argument when the program is run.
~~~
------WebKitFormBoundaryBlBkv39BhoNGpL6g
Content-Disposition: form-data; name="options"

google.com
~~~

~~~
2017-03-20 08:36:44,967 [lib.api.process] INFO: Successfully executed process from path u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\curl.exe' with arguments '' and pid 3004
~~~

**Comment by razuz** [comment]
@jay put to options box `arguments=google.com`

**Comment by jay** [comment]
@razuz thanks, that worked

**Comment by jbremer** [comment]
Closing as resolved. Feel free to reopen if you have additional questions and/or feedback etc.
