### ISSUE TITLE
Database Error when Resubmitting Samples (mySQL / mariaDB)

### ISSUE THREAD

**Issue by yeejay** [cuckoosandbox/cuckoo#1350]
I recently switched my database from the default SQLite to mariaDB so I could accommodate multiple analytic machines.

When using the web client, initial sample submission has not been a problem.  However, I noticed that if I use the "resubmit sample" button, I get directed toward the ":( Database error" screen.  I'm fairly certain it's not the file since if I submit it again, it processes fine.

I was wondering if this is a known issue or if there is a solution.

OS: CentOS 7 
Software: Cuckoo V2.0-RC2, mysql Ver 15.1 Distrib 5.5.52-MariaDB

**Comment by jbremer** [comment]
Sorry for not replying. I guess you figured out the issue?

**Comment by yeejay** [comment]
I'm not sure how, but the problem resolved itself after an update and reload.  Apologies for creating it as an issue.  I would've posted in the community section on the main site, but it appears to be down.
