### ISSUE TITLE
Submit crash on SFX archive

### ISSUE THREAD

**Issue by FernandoDoming** [cuckoosandbox/cuckoo#1356]
If a self-extracting executable is submitted to Cuckoo for analysis via the web interface server returns error with the following message: 

```
Something went wrong!
The server returned an error. Please check our file compatibility list with the file you're trying to upload or try again.
If the problem persists, send us a feedback report.
```

### Steps to reproduce:
* Submit a self-extracting .exe file for analysis (for example, this one: `8a23c6f4ed334a04f6d5283bdca052ff79dbe1bec182b5cf5ef2f1f70ccb7a4e` **beware! malware inside**)
* That's pretty much it

**Comment by jbremer** [comment]
Seems to work just fine for me. Could you elaborate a bit further on the steps taken?

**Comment by FernandoDoming** [comment]
Seems to have fixed itself. Maybe it was due to a background process filling the storage on the host...
