### ISSUE TITLE
Pinging the Cuckoo Guest VM from another device on the Host's LAN

### ISSUE THREAD

**Issue by FoxyNPF** [cuckoosandbox/cuckoo#1376]
Hi,

I have setup the API for cuckoo. I am looking to submit malware samples from other devices on the Host machines network.

My host machine is 192.168.1.36 (Ubuntu), the guest is a Windows 7 VM with the IP 192.168.56.1 and works fine, I can ping between the 2 machines and submit malware samples from the host.

However I have another device 192.168.1.28 that I would like to be able to submit samples to my guest VM 192.168.56.1. In order to do this I have configured the following static route and enabled IP Forwarding:

route add -net 192.168.56.1 netmask 255.255.255.255 gw 192.168.1.36 dev ens3

Despite being able to ping the host 192.168.1.36 I cannot ping the Cuckoo guest VM.

Has anybody come across this before? I am using VirtualBox for my VM.

Thanks

**Comment by littlejob** [comment]
Per the below instructions, why not permit the entire subnet?

```
For example, using VirtualBox, you can enable Internet access to the virtual machines using the following iptables rules (assuming that eth0 is your outgoing interface, vboxnet0 is your virtual interface and 192.168.56.0/24 is your subnet address):

iptables -A FORWARD -o eth0 -i vboxnet0 -s 192.168.56.0/24 -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A POSTROUTING -t nat -j MASQUERADE

And adding IP forwarding:
sysctl -w net.ipv4.ip_forward=1
```

[https://downloads.cuckoosandbox.org/docs/installation/guest/network.html](url)

**Comment by FoxyNPF** [comment]
Hi, now you mention it I have already done that. I don't get why I cant ping the device from another machine in the same subnet.

**Comment by yeejay** [comment]
what's your hypervisor config file look like?  Are you trying to submit directly to the guest and then have it report back to the host?

One thing you might want to try is using the web interface so that everything is brokered by the host.

**Comment by FoxyNPF** [comment]
Hi,

Here's my virtualbox conf.

"Are you trying to submit directly to the guest and then have it report back to the host?" - Yes thats correct

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui", "sdl" or "headless". Refer to VirtualBox's official
# documentation to understand the differences.
mode = gui

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = Cuckoo

[Cuckoo]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = Cuckoo

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
# snapshot = Snapshot 2

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
# Example (vboxnet0 is the interface name):
# interface = vboxnet0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here 
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
# resultserver_ip = 192.168.56.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
# resultserver_port = 2042

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by yeejay** [comment]
Since I don't know your setup, I'm making some assumptions.  Hopefully a dev can correct me if I'm wrong, but I don't think Cuckoo works quite like you want it to.  

First, it's my understanding that after an analysis, the cuckoo host shuts down the VMs.  Thus, you couldn't ping them even you wanted to.  Now, in the case that you have the VM up and you can't ping it, well that's a routing issue where your gateway isn't properly forwarding to the next hop.  

Now, is there a reason why you're trying to bypass the cuckoo host completely?  Submit.py has a method of using remote IPs, but the task still needs to be given an ID.  Without this tagging, the database on the host won't really know what to do with the returned data.

**Comment by FoxyNPF** [comment]
Hi yeejay,

Sorry I think I've caused a bit of confusion here.

So my host is 192.168.1.36. It has a vboxnet0 interface of 192.168.56.1, the guest VM is 192.168.56.101.

So I cannot ping the vboxnet0 interface 192.168.56.1 from another device on the 192.168.1.0/24 subnet. 

This is why I initially tried setting up static routes such as:

route add -net 192.168.56.0 netmask 255.255.255.0 gw 192.168.1.36 dev ens3

Apologies for the confusion.

**Comment by yeejay** [comment]
Ok, so you're not pinging the Cuckoo VM.  You're pinging the virtual interface.

I hate to say this, but this isn't a Cuckoo Issue, so it's not really a problem that should be in the github issue tracker.  

My gut feeling says it's a firewall issue.  Try flushing iptables and seeing if it can route.  Make sure you don't have any conflicting iptable rules.  Also, it's been my experience that systems with firewalld and iptables can really screw up with routing.

Hope this helps.

**Comment by FoxyNPF** [comment]
No worries, thanks for your help

**Comment by JyotsnaJain** [comment]
hi,
i want to submit file from remote IP, this machine is connected to host(ubuntu in which cuckoo is set).
When i am trying to submit file using REST API i am getting Django webpage.
![webcuckoo](https://user-images.githubusercontent.com/37400010/47422029-60e21000-d79f-11e8-8d4a-6f5c8ed1738c.PNG)

thanks.

**Comment by doomedraven** [comment]
pay attention what you posting to wrong port `8000` instead of `8090`

**Comment by JyotsnaJain** [comment]
I get "curl: (7) Failed to connect to 10.213.161.137 port 9090: Connection
refused" if i am posting to 8090.

**Comment by doomedraven** [comment]
Well then check how you start the api service on which port, and use correct port, if you dont know how to start it use documentation and/or cuckoo —help

**Comment by JyotsnaJain** [comment]
Thanks  it helps!!

**Comment by doomedraven** [comment]
next time please read the manual first :)
