### ISSUE TITLE
Error from the Cuckoo Guest: Analysis failed: The package "modules.packages.generic" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by 007scorpio** [cuckoosandbox/cuckoo#1377]

**Comment by doomedraven** [comment]
No details no bug ;)

**Comment by 007scorpio** [comment]
Traceback (most recent call last):
  File "C:\rdnpzfxje\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\rdnpzfxje\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.generic" start function raised an error: Unable to execute the initial process, analysis aborted.

**Comment by doomedraven** [comment]
No cuckoo version, no hypervisor software version, no hash/url whcih trigger error, etc

**Comment by 007scorpio** [comment]
cuckoo version = 2.0-rc2
virtualbox version = 5.1.18


Sorry... the error does not give much info except the few i wrote... thanks

**Comment by doomedraven** [comment]
But ehat trigger that? Any url/hash?

**Comment by 007scorpio** [comment]
i submitted a .exe malware file please.

**Comment by doomedraven** [comment]
ok but we don't have access to your .exe xD so we can't reproduce
if you want a good support, provide good info to devs so they can reproduce it

**Comment by yeejay** [comment]
Run cuckoo with -d flag and post the results.  Also post configs, etc.

Reporting an issue without details is useless.

**Comment by 007scorpio** [comment]
fixed it... Thanks all :)

**Comment by jbremer** [comment]
@007scorpio and what was the fix?

**Comment by jbremer** [comment]
I guess I'll be closing this issue - if you do have some feedback, let us know.
