### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by CSIRTUK** [cuckoosandbox/cuckoo#1381]
Every time I submit a file for analysis I get the following error:

2017-04-07 03:46:16,513 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 478, in launch_analysis
    machinery.start(self.machine.label, self.task)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/machinery/virtualbox.py", line 150, in start
    if "nictrace" in machine.options:
TypeError: argument of type 'NoneType' is not iterable

Any help would be much appreciated.

Kind regards
Andy D

**Comment by doomedraven** [comment]
provide whole info, as cuckoo version, vbox version, what cause error url or hash etc etc

**Comment by CSIRTUK** [comment]
Apologies,  I am using Version 2.0.0 installed this morning on Ubuntu 16.04 via Pip
I'm using VirtualBox 5 for my virtualisation.
The error occurs whenever I submit any file for analysis.  I can see the VM start but it then dies instantly and the message appears in my cuckoo window.

**Comment by CSIRTUK** [comment]
Here us is my virtualbox.conf file

[virtualbox]
mode = gui
path = /usr/bin/VBoxManage
interface = vboxnet0
machines = VICTIM-WIN7

[VICTIM-WIN7]
label = VICTIM-WIN7
platform = windows
ip = 192.168.56.21
snapshot = clean
interface = vboxnet0
resultserver_ip = 
resultserver_port = 
tags = 
options =

**Comment by doomedraven** [comment]
hm not sure as im not vbox user ,but try to comment out thi in config
```
resultserver_ip =
resultserver_port =
tags =
options =
```

**Comment by CSIRTUK** [comment]
You're a star.  All sorted.  Thank you.

**Comment by doomedraven** [comment]
glad that works for you :)
@jbremer that `option` in vbox config is for backward compatibility? 

@CSIRTUK close if solved ;)

**Comment by jbremer** [comment]
Don't close it as of yet if it's not properly fixed ;-)

**Comment by doomedraven** [comment]
why you keep that one if put comment no fill it ? :D

**Comment by jbremer** [comment]
@CSIRTUK Just in case you'd be interested to help check something for me, I've put up an alpha release with a bugfix to your earlier issue. You can test it by upgrading with `pip install cuckoo==2.0.1a3`. Thanks!

**Comment by CSIRTUK** [comment]
Thanks Jurriann, I'll do that today. I think I have another issue to raise
to but I'm going to try a work around first.
Andy

**Comment by jbremer** [comment]
This issue should be resolved now, closing.
