### ISSUE TITLE
Cuckoo Package : No scroll bars on the right to scroll through the report

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1384]
Hi, ivew noticed that since the last update you can no longer scroll through a report, i have checked this on 3 browsers IE Chrome and FF. It seems to be isolated to the report s only, eg i can scroll through the samples fine .

Cheers

**Comment by SparkyNZL** [comment]
if you change the following it should fix the issue

![screenshot from 2017-04-08 13-09-21](https://cloud.githubusercontent.com/assets/17818264/24824289/becb384a-1c5c-11e7-93ad-80100d08cad7.png)
![screenshot from 2017-04-08 13-09-43](https://cloud.githubusercontent.com/assets/17818264/24824290/c08d5d84-1c5c-11e7-81f0-1bf411ddbd46.png)

**Comment by jbremer** [comment]
@automagisch please take a look.

**Comment by SparkyNZL** [comment]
this seems to be isolated to FF in ubuntu, i just tried this from windows box and it did the same thing until i closed it and did an cache refresh, but even doing this in ubuntu doesnt seem to fix the issue for me

**Comment by jbremer** [comment]
Resolved as per #1394. Please verify by upgrading Cuckoo to the latest stable (i.e., currently `2.0.1`) and reopen this issue if you still experience issues. Thanks!
