### ISSUE TITLE
VBoxManage can take screenshots

### ISSUE THREAD

**Issue by HarryR** [cuckoosandbox/cuckoo#1386]
From: http://www.dedoimedo.com/computers/virtualbox-screenshot.html
```
VBoxManage controlvm <vm name> screenshotpng <filename>.png
```
If using virtualbox machinery it could take screenshots of the VM independently of the agent.

**Comment by doomedraven** [comment]
so where is the issue? there no only vbox used, there qemu, kvm, xen, vmware etc and not all of them has this command ;)

**Comment by jbremer** [comment]
What @doomedraven said. We could use this for VirtualBox, but what's the advantage? :-) I'd be happy to hear more about that.

**Comment by HarryR** [comment]
Leave it for now, it's just a reminder to me and the world in general that there might be cool things that can be done with virtualbox screenshots.

**Comment by jbremer** [comment]
Fair enough. VirtualBox also does VRDE, which I do intend to start using at some point.. :-)
Anyway, closing this issue as it is indeed a nice feature, but not something that I see a direct advantage in from a Cuckoo point of view. Thanks and let us know if you have any more suggestions & feedback.
