### ISSUE TITLE
Error fetching configuration file!

### ISSUE THREAD

**Issue by paradise6** [cuckoosandbox/cuckoo#1388]
my tools is Virtualbox win7 64-bit machine, i cannot get any process tree results or anything useful,  So i try to use gui mode to see what happened on earth.   i find the problem but don't know how to deal with it.
When the machine is poweron, it appears 
        "   is32bit error [-] Error getting access to process: 5! "

 after that,
      "    Cuckoo Error: Error fetching configuration file! This is a serious error. if encountered, please notify the Cuckoo developers as this error prevents analysis."

 finally
 "Error: Pipe has not been initialized yet!"

my test file info:  Type PE32 executable (GUI) Intel 80386 (stripped to external PDB), for MS Windows

**Comment by jbremer** [comment]
Did you disable UAC & run the Agent as Administrator?

**Comment by paradise6** [comment]
i disabled UAC and it's ok, thks
