### ISSUE TITLE
Pre Submit Page doesn't accept VPN options 

### ISSUE THREAD

**Issue by lowson** [cuckoosandbox/cuckoo#1389]
Migrating this issue over here as its different then the original issue 1367

Fresh 2.0.0 install from the pip repo.
Ubuntu 16.04

When I select a VPN option during the pre analyze stage it doesn't seem to submit correctly and it ends up using the last selected non VPN option.

POST data after selecting VPN:
https://pastebin.com/t6Nqq3ST

Logs after selecting a VPN option:
[cuckoo.core.scheduler] DEBUG: Processing task #5
[cuckoo.core.scheduler] INFO: Starting analysis of URL "http://www.whatsmyip.org" (task #5, options "procmemdump=yes,route=internet")
[cuckoo.apps.rooter] DEBUG: Processing command: forward_enable eth1 eth0 192.168.56.x
[cuckoo.apps.rooter] DEBUG: Processing command: srcroute_enable main 192.168.56.x

Now to test this I hard set the vpn0 in the routing.conf file as the default routing option and everything worked with the VPN as expected and the VM traffic was routed. 

POST data after forcing VPN:
https://pastebin.com/7TMMHD3m

Logs after forcing a VPN option:
[cuckoo.core.scheduler] DEBUG: Processing task #29
[cuckoo.core.scheduler] INFO: Starting analysis of URL "http://www.whatsmyip.org" (task #29, options "procmemdump=yes,route=vpn0")
[cuckoo.apps.rooter] DEBUG: Processing command: forward_enable eth1 tun0 192.168.56.x
[cuckoo.apps.rooter] DEBUG: Processing command: srcroute_enable tun0 192.168.56.x

I suspect the issues might be within the submission.js file, TOR and inetsim work without issues when selected, this issue was found in both Firefox and Chrome.

If anyone has any ideas on what might be causing the issue or how to debug further let me know.

**Comment by jbremer** [comment]
Thanks for the report! I've fixed the issue and will be releasing `2.0.1a1` shortly so you can upgrade easily.

**Comment by lowson** [comment]
Thanks @jbremer I will verify once release and update you :)

**Comment by jbremer** [comment]
I've put up version `2.0.1a1`, an alpha version including a fix for this issue. Please upgrade (i.e., `pip install cuckoo==2.0.1a1`). Closing this issue as fixed.
