### ISSUE TITLE
cuckoo 2.0.0 web interface can not scroll.

### ISSUE THREAD

**Issue by pinksawtooth** [cuckoosandbox/cuckoo#1394]
Can not scroll Directories under the ```http://127.0.0.1:8000/analysis/number``` 
for example ```http://127.0.0.1:8000/analysis/15/summary/```,  ```http://127.0.0.1:8000/analysis/15/static/``` , etc...

![screenshot from 2017-04-12 07-24-48](https://cloud.githubusercontent.com/assets/18203311/24933626/310188a4-1f52-11e7-9761-11c00be47ffd.png)

**Comment by jbremer** [comment]
Thanks. I thought this was fixed already, will get back to you asap.

**Comment by SparkyNZL** [comment]
Hi @pinksawtooth 
I have already reported this. but it seems to be isolated to FireFox in Ubuntu. if you browse to it using a windoze box it should work ok. please look at ticket number #1384 

Cheers.

**Comment by jbremer** [comment]
We've resolved this issue and pushed out a new release including this and all earlier bugs, `pip install -U cuckoo`  will now get you version `2.0.1`. Please verify and re-open this issue if the issue is not resolved for you with this new version release!
