### ISSUE TITLE
URL Broken for MISP Analysis

### ISSUE THREAD

**Issue by CSIRTUK** [cuckoosandbox/cuckoo#1398]
On the analysis page, clicking on the MISP tab results in a 404 error.  This appears to be because the URL terminates with couple of extra characters as shown here ( http://10.80.X.X/analysis/14/misp/%7D).  Manually deleting the characters fixes the problem and displays the page correctly.

**Comment by doomedraven** [comment]
can you post part of misp config section?

**Comment by CSIRTUK** [comment]
[misp]
enabled = yes
url = https://misp.xxxx.co.uk/
apikey = oE....Fr

# Maximum amount of IOCs to look up (hard limit).
maxioc = 100

**Comment by CSIRTUK** [comment]
Thanks for the fix.  I've sorted my local version now.

**Comment by jbremer** [comment]
Sweet, thanks for the feedback!
