### ISSUE TITLE
JS errors in IE11

### ISSUE THREAD

**Issue by MarkusTeufelberger** [cuckoosandbox/cuckoo#1399]
SCRIPT1028: Expected identifier, string or number
File: vendor.js, Line: 63451, Column: 5

and

SCRIPT5009: 'Handlebars' is undefined
File: handlebars-templates.js, Line: 2, Column: 1

**Comment by jbremer** [comment]
Currently IE11 is not officially supported. This may be changed in one of our upcoming versions, but we recommend Chrome or Firefox.

**Comment by SparkyNZL** [comment]
refer #1344

**Comment by jbremer** [comment]
Closing as duplicate of #1344 indeed - thanks for reporting!
