### ISSUE TITLE
supervisorctl BAD_NAME error

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1404]
In 2.0.1 attempting to stop Cuckoo started via the supervisor as documented at https://cuckoo.sh/docs/usage/start.html...

sudo supervisorctl stop cuckoo:

...results in the error...

error: <class 'xmlrpclib.Fault'>, <Fault 10: 'BAD_NAME: cuckoo'>: file: /usr/lib/python2.7/xmlrpclib.py line: 794

**Comment by jbremer** [comment]
How did you start `supervisord`?

**Comment by Kolano** [comment]
Ran "supervisord" from the Cuckoo Working Directory ~/.cuckoo.

Such seems to have started the Cuckoo processes correctly...
ps -eaf | grep cuck
pass      3799  3748  1 14:37 ?        00:00:28 /usr/bin/python /usr/local/bin/cuckoo process p1
pass      3800  3748  1 14:37 ?        00:00:28 /usr/bin/python /usr/local/bin/cuckoo process p0
pass      3801  3748  1 14:37 ?        00:00:26 /usr/bin/python /usr/local/bin/cuckoo process p3
pass      3851  3748  1 14:37 ?        00:00:26 /usr/bin/python /usr/local/bin/cuckoo process p2
...but perhaps not the main cuckoo process, so perhaps that's the issue.

**Comment by jbremer** [comment]
Then probably you shouldn't be using `sudo` for `supervisorctl` :)
Does indeed look like `cuckoo -d` failed, can you take a look at `~/.cuckoo/log/cuckoo.log`?

**Comment by Kolano** [comment]
Then I get...
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 224

**Comment by Kolano** [comment]
Seems "python -m cuckoo.distributed.worker" is resulting in...
"No handlers could be found for logger "cuckoo.processing.memory""

**Comment by jbremer** [comment]
Hmm, your logs seem incomplete. No, no `sudo` is used for anything in Cuckoo, except for the Cuckoo Rooter (if you use that functionality in the first place). Seems that PyCrypto is missing which hasn't been bundled with the Cuckoo Package - I'll have to take a look at that later.

**Comment by Kolano** [comment]
It seems like installing PyCrypto as able to resolve the Cuckoo startup. I now have the following cuckoo services running...

```
ps -eaf | grep "cuckoo" | grep -v grep
pass     30177     1  0 18:06 ?        00:00:00 /usr/bin/python /usr/bin/supervisord -c /home/pass/.cuckoo/supervisord.conf
root     30180     1  0 18:06 ?        00:00:01 /usr/bin/python /usr/local/bin/cuckoo -d rooter -g pass
root     30184     1  0 18:06 ?        00:00:00 su pass -c cuckoo -d web runserver
pass     30192 30184  0 18:06 ?        00:00:10 /usr/bin/python /usr/local/bin/cuckoo -d web runserver
pass     30207 30177  5 18:06 ?        00:01:11 /usr/bin/python /usr/local/bin/cuckoo -d -m 10000
pass     30267 30192  3 18:06 ?        00:00:47 /usr/bin/python /usr/local/bin/cuckoo -d web runserver
pass     30287 30177  1 18:06 ?        00:00:26 /usr/bin/python /usr/local/bin/cuckoo process p2
pass     30288 30177  1 18:06 ?        00:00:26 /usr/bin/python /usr/local/bin/cuckoo process p3
pass     30322 30177  1 18:06 ?        00:00:25 /usr/bin/python /usr/local/bin/cuckoo process p1
pass     30337 30177  1 18:06 ?        00:00:25 /usr/bin/python /usr/local/bin/cuckoo process p0
```
Even with that resolved I see the same error attempting to stop Cuckoo services via Supervisor.

[cuckoo.log.txt](https://github.com/cuckoosandbox/cuckoo/files/918039/cuckoo.log.txt)
[log.log.txt](https://github.com/cuckoosandbox/cuckoo/files/918040/log.log.txt)

**Comment by Kolano** [comment]
OK, I think the problem was failing to run supervisorctl from the CWD.

**Comment by jbremer** [comment]
Really, `supervisorctl -c CWD` doesn't work?
Btw, the `PyCrypto` related issue is due to having `volatility` installed but missing their dependencies, the error reporting for this has been improved as part of 7435f5495b72a83065bd7b4b1265b831b58951c6.
So ok, am I correct to state that there are no `supervisor` permission issues if you use the correct user at all times etc (i.e., not root)? If so, can this issue be closed then? :)

**Comment by Kolano** [comment]
I believe so. The issue is that the default Upstart startup of Supervisor on boot is run as root, as further discussed in [1403](https://github.com/cuckoosandbox/cuckoo/issues/1403).

**Comment by jbremer** [comment]
Yep :)

**Comment by jwilczek** [comment]
Running `supervisorctl -c CWD` did not work for me either. But, running `supervisord` from within CWD did work perfectly.

In case this helps anyone else....
