### ISSUE TITLE
Failure: NoneType error

### ISSUE THREAD

**Issue by hiblackbear** [cuckoosandbox/cuckoo#1407]
Cuckoo Version: 2.0.0

![error 1](https://cloud.githubusercontent.com/assets/27399764/24991289/b24b5310-2054-11e7-8065-4539c573b78f.png)

I got a error.

**Comment by hiblackbear** [comment]
I solved it through the following issues.
#1381 

sorry.
thanks.

**Comment by jbremer** [comment]
No problem, thanks for figuring out yourself :-)
