### ISSUE TITLE
CuckooCriticalError: Unable to import plugin "modules.reporting.maec40": cannot import name fix_key

### ISSUE THREAD

**Issue by raikikon** [cuckoosandbox/cuckoo#1409]
@gtback and all
```
Cuckoo Sandbox 2.0-rc2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Good! You have the latest version available.

2017-04-13 12:09:33,302 [root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.reporting.maec40": cannot import name fix_key 
```
here the pip list
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
adium-theme-ubuntu (0.3.4)
alembic (0.8.0)
androguard (3.0)
beautifulsoup4 (4.4.1)
bson (0.4.7)
cffi (1.6.0)
chardet (2.3.0)
Cheetah (2.4.4)
click (6.7)
cryptography (1.3.2)
cybox (2.0.1.4)
Cython (0.25.2)
distribute (0.7.3)
Django (1.8.4)
dpkt (1.8.7)
ecdsa (0.13)
elasticsearch (2.2.0)
enum34 (1.0.4)
Flask (0.10.1)
HTTPReplay (0.1.17)
idna (2.0)
ipaddress (1.0.14)
itsdangerous (0.24)
Jinja2 (2.8)
jsbeautifier (1.5.10)
libvirt-python (1.3.1)
lxml (3.7.3)
M2Crypto (0.26.0)
maec (4.0.1.0)
Mako (1.0.1)
MarkupSafe (0.23)
mixbox (1.0.1)
numpy (1.12.1)
ordered-set (2.0.1)
pip (9.0.1)
protobuf (3.2.0)
pyasn1 (0.1.8)
pycparser (2.14)
pymango (0.1.1)
pymongo (3.4.0)
pystan (2.14.0.0)
python-dateutil (2.6.0)
python-editor (0.3)
pytz (2017.2)
requests (2.13.0)
setuptools (20.7.0)
six (1.9.0)
SQLAlchemy (1.0.8)
tlslite-ng (0.6.0a3)
typing (3.6.1)
unity-lens-photos (1.0)
urllib3 (1.20)
weakrefmethod (1.0.3)
Werkzeug (0.10.4)
wheel (0.29.0)
XenAPI (1.2)
```
i alreday has maec==4.0.1.0
also had cybox=2.0.1.4

please help ....

**Comment by raikikon** [comment]
@gtback 
~_~

**Comment by jbremer** [comment]
Not sure how @gtback is involved in this thread, but please upgrade to our latest version https://cuckoosandbox.org/2017-04-07-cuckoo-sandbox-200.html :-)

**Comment by gtback** [comment]
I'll guess I was mentioned because the error involves MAEC and CybOX 😀 

I honestly haven't used Cuckoo in a while, but as far as I can tell, the maec40 module was removed and is not in 2.0-rc2. So it's possible you either have a config file copied from an earlier version, or some stale ".pyc" files from an earlier installation (or both). If neither of those is the case, maybe try installing Cuckoo in a clean environment?

cc: @ikiril01

**Comment by lovina37** [comment]
@jbremer please see my issue which I opened ... and will this new version work for android too ??

**Comment by gtback** [comment]
@lovina37, I'm not sure I understand how this issue is related to #1406, if that's the issue you're referring to.

**Comment by jbremer** [comment]
@raikikon what @gtback said should fix your issue, which btw is unrelated to MAEC or anything, but simply a side effect of upgrading from `2.0-rc1` (or similar) to `2.0-rc2` in the same directory.
Also please feel free to update to the latest version.
Closing this issue as all seems to be resolved - please feel free to reopen or create a new issue if other problems occur.
