### ISSUE TITLE
Routing traffic through TOR

### ISSUE THREAD

**Issue by FoxyNPF** [cuckoosandbox/cuckoo#1411]
Hi,

I am having trouble getting Cuckoo to route traffic through TOR, i am running cuckoo 2.0-dev.

I have installed and setup TOR as per the following instructions:

https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27

However when I look at the official cuckoo documentation it tells me to open /conf/routing.conf and enable TOR. However there is no routing.conf file.

Any advice would be greatly appreciated.

**Comment by jbremer** [comment]
Please upgrade to our latest version (https://cuckoosandbox.org/2017-04-07-cuckoo-sandbox-200.html) and use our official documentation on the matter (https://cuckoo.sh/docs/installation/host/routing.html#routing-tor). That should certainly work ;-)

**Comment by FoxyNPF** [comment]
superb, thankyou

**Comment by FoxyNPF** [comment]
Hi,

I've ran 'pip install -U cuckoo' as root.

The updates install as expected however when I launch cuckoo.py I'm still told I'm running 2.0-dev

**Comment by doomedraven** [comment]
bcz you should start `cuckoo` not `cuckoo.py`

**Comment by FoxyNPF** [comment]
aaah, cheers!
