### ISSUE TITLE
Machine timeout during falling back to strace analysis (Ubuntu guest)

### ISSUE THREAD

**Issue by vlakas** [cuckoosandbox/cuckoo#1413]
On Ubuntu 14.04.5 (3.13.0-116-generic kernel) guest system I have troubles with behaviour analysis.
Guest system installed without systemtap and there is no any modules with stap_*.ko name. So Cuckoo have to fallback to strace. Here is 2 issues:
* There is no any messages about falling back to strace
* Every behaviour analysis is timed out
`[lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
...
[modules.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.`

I use Cuckoo rc-2. All logs and also sample of file are attached here.

[mlwr.zip](https://github.com/cuckoosandbox/cuckoo/files/921245/mlwr.zip)
[cuckoo-files.zip](https://github.com/cuckoosandbox/cuckoo/files/921244/cuckoo-files.zip)

**Comment by doomedraven** [comment]
That is not an issue just process not ends so cuckoo kills vm, if you push an .sh with wget ipinfo.io it will close vm after finishing retrieve page

**Comment by vlakas** [comment]
doomedraven, thank you for your comment.
Unfortunately with simple bash script the issue is the same.
```bash
#!/bin/bash
for I in $(seq 1 10); do
    echo "Hello $I"
    sleep 1
done
exit 0
```

It should take apporx 10 sec (+/-) to finish. But behaviour analysis still is timed out.
Here is report:
[cuckoo_report.txt](https://github.com/cuckoosandbox/cuckoo/files/921814/cuckoo_report.txt)

```
"2017-04-14 12:01:31,967 [root] INFO: Analysis timeout hit, terminating analysis.\n",
```

**Comment by doomedraven** [comment]
Weird, i dont have that issue try to test it here https://linux.huntingmalware.com/

**Comment by doomedraven** [comment]
https://linux.huntingmalware.com/analysis/4/summary your sample without timeout

**Comment by doomedraven** [comment]
but there is qemu used, not vbox, try to increase default timeouts maybe a bit just as test

**Comment by vlakas** [comment]
@doomedraven You are right. I see here that analysis completed successfuly. I've tried to increase timeout from 120 to 300. But no luck.

Can you provide info about guest linux system? I mean what distro, version, kernel?

**Comment by doomedraven** [comment]
hm weird, well i would you to suggest to upgrade to the latest release first of all, as there really a lot of improvements in that release

about the setup
that is clear ubuntu 16.04.2(kernel 4.8)

**Comment by vlakas** [comment]
@doomedraven once more thank you for the tip. Cuckoo 2.0.1 + ubuntu 16 works just fine.

**Comment by jbremer** [comment]
Thanks for the feedback @vlakas!
