### ISSUE TITLE
Future Request : Individual module processing

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1414]
It would be great in the future if you could reprocess a number off samples but only a specific modules eg

cuckoo -d process -r 500-1000 misp

and this would rerun the misp module against the sample and update the report.

Just a thought :)

**Comment by jbremer** [comment]
This isn't really how it works, unfortunately. Updating, e.g., the JSON report is more effort than recreating it in the first place :-)

**Comment by jbremer** [comment]
Yeah, for reasons stated above I'm going to close this issue. Thanks for the suggestion though.
