### ISSUE TITLE
Error in analisys and Unable to find the correct offsets

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1416]
I have installed cuckoo 2.0.0 with agent 0.7 ,
win7 sp1.
If i analyze a file in my log i find more and more
WARNING: Unable to find the correct offsets for functions of: 32-bit kernel32.dll (with timestamp 0x4ce7b8ef)
WARNING: Unable to find the correct offsets for functions of: 32-bit jscript.dll (with timestamp 0x4ce7b848)
WARNING: Unable to find the correct offsets for functions of: 32-bit kernel32.dll (with timestamp 0x4ce7b8ef)
etc etc

In my result i always find
Perform some http request (ok,but this is my ip)
request	GET http://192.168.56.101:8000/
request	GET http://192.168.56.101:8000/pinning
request	GET http://192.168.56.101:8000/environ
request	POST http://192.168.56.101:8000/mkdtemp
request	POST http://192.168.56.101:8000/extract
request	POST http://192.168.56.101:8000/store
request	POST http://192.168.56.101:8000/execpy
request	GET http://192.168.56.101:8000/status

Connect to an IRC server (but not connection are made)

Thanks

**Comment by Maurotb** [comment]
I have update to 2.0.1, same problem

**Comment by jbremer** [comment]
Thanks for the feedback. Unfortunately the feature to provide us the correct feedback to work on this wasn't finished as part of version `2.0.0`/`2.0.1`. That said, it isn't a critical issue and as such you can ignore it for now.

**Comment by Maurotb** [comment]
Ok thanks,
for ip problem there are a solution?

I have some score that match this rule
1)Perform some http request (ok,but this is my ip)
request	GET http://192.168.56.101:8000/

2)Connects to an IP address that is no longer responding to requests (legitimate services will remain up-and-running usually) (1 event)
dead_host	192.168.56.103:49173

is possible to make a whitelist for 192.168.56.0/24?

**Comment by sebdg** [comment]
@Maurotb same issue as #1493  and #1492

**Comment by jbremer** [comment]
Closing as resolved.
