### ISSUE TITLE
I do not know why I need a reboot module.

### ISSUE THREAD

**Issue by hiblackbear** [cuckoosandbox/cuckoo#1420]
I do not know how it works when I look at the code.

Please Can you give a brief description of the operation process?

**Comment by doomedraven** [comment]
Read the documentation

**Comment by jbremer** [comment]
I'm not sure if there's docs on it, actually. However, if you don't need it, easiest just to ignore it? :-)

**Comment by hiblackbear** [comment]
I could not find the document.
I will consider it in the direction not to use it.
thanks.

**Comment by jbremer** [comment]
Sure, no problem. I'm going to close this issue, though.
