### ISSUE TITLE
Guest HTTP(S) traffic seems not to be forwarded through mitm proxy

### ISSUE THREAD

**Issue by vlakas** [cuckoosandbox/cuckoo#1422]
It seems that HTTP(S) traffic of guest system is not forwarded to mitm proxy.
The lastest stable version of mitm proxy is installed on Cuckoo host system and is enabled in auxiliary.conf. Also I can see in analysis logs that mitm proxy starts successfuly. But dump.mitm, mitm.{err,log} and tlsmaster.txt are empty.

In the case of proxying HTTP(S) traffic we need to specify proxy in guest's os or froward such traffic to mitm proxy with iptables. Nothing was found in cuckoo sources.

mitm.py contains nothing (is this a problem?)
Where I'm wrong or do really mitm proxy works in cuckoo?

Cucko version: 2.0.1

cuckoo.log has been attached.

[cuckoo.log.txt](https://github.com/cuckoosandbox/cuckoo/files/927808/cuckoo.log.txt)

**Comment by jbremer** [comment]
Currently the mitm proxy integration isn't transparent yet, in other words, you'll have to configure a socks5 proxy in the VM. Only that traffic will be redirected.
Reasoning for this behavior is the fact that when it was developed, Cuckoo was not yet able to perform transparent proxying. Now it would be possible with some modifications here and there, but that still requires a few days of R&D :-)

**Comment by vlakas** [comment]
@jbremer Thank you for your answer. But there is an issue with proxy configuration in guest host. Separate mitm daemon instance starts for every analysis and binds to dynamic listening port on  the host system. So proxy configuration of guest system needs to be dynamic to. And I can't figure out how this can be achieved. I mean that we need somehow pass ip:port of mitm proxy to guest and configure proxy settings dynamic.
Here my point of view is the following (as I've already described). We can configure transparent proxy with forwarding traffic with iptables or configure guest system to use http(s) proxy during startup. But both ways need dynamic configuration (with agent in the first case or rooter in the other).

Btw I understand you and thank you for clearing this issue.

**Comment by poerschke** [comment]
I am having the same problem, many malwares are using HTTPS to transfer files and cuckoo can not show this
