### ISSUE TITLE
MySQL Web DB Creation Problem

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1428]
Trying to start up Cuckoo web with a MySQL DB on a fresh install I'm seeing a DB error...

```
Traceback (most recent call last):
  File "/home/pass/cuckoo_ve/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.1', 'console_scripts', 'cuckoo')()
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/cuckoo/main.py", line 483, in web
    Database().connect()
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/cuckoo/core/database.py", line 446, in connect
    self._create_tables()
  File "/home/pass/cuckoo_ve/local/lib/python2.7/site-packages/cuckoo/core/database.py", line 467, in _create_tables
    "Unable to set schema version: %s" % e
cuckoo.common.exceptions.CuckooDatabaseError: Unable to set schema version: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '181be2111077' for key 'PRIMARY'") [SQL: u'INSERT INTO alembic_version (version_num) VALUES (%s)'] [parameters: ('181be2111077',)]
```

Seen with Cuckoo 2.0.1 installed via...

```
pip install -U cuckoo
```

I thought this had been working on Mon Apr 17th. Might be related to transitioning to a virtualenv?

**Comment by Kolano** [comment]
Sorry, Seems to have been due to a failure with my python-mysqldb install.

**Comment by Kolano** [comment]
Hrm, actually I'm not sure about that. Seems a repeat install with Python-Mysql installed properly for the cuckoo virtual environment...

```
pip install MySQL-python
Requirement already satisfied: MySQL-python in ./cuckoo_ve/lib/python2.7/site-packages
```

...fails in the same way reported initially. It seems to actually just start up on a second attempt, but guessing there may still be some problem with the DB structure created.

**Comment by Kolano** [comment]
Sorry, again, likely that I forgot to include the -U switch, so the it's related to using an outdated version of the MySQL libs.

**Comment by Kolano** [comment]
Er, nope, that's not it, library was up to date on a repeated install attempt.

**Comment by jbremer** [comment]
That's quite odd, I'll have to take a look at that! Thanks for reporting.

**Comment by Kolano** [comment]
Looking more closely at my install I think this is related to my transition to use of a virtualenv.

It seems running the mysql-python install via PIP rather than apt-get results in "EnvironmentError: mysql_config not found" errors. Apparently the libmysqlclient-dev client must be installed to avoid such.
```
sudo apt-get -y install libmysqlclient-dev
pip install -U mysql-python
```
I'm presuming errors seen were likely due to an older revision of mysql-python installed outside of the virtualenv (required for an alternate app on the system). So mysql-python was present, but not the revision currently needed by Cuckoo.

Had hoped that would resolve things but now with things installed successfully I still get "Can't connect to MySQL server on '192.168.0.64'" errors, I didn't see when not using a virtualenv.

In any case this seems to likely be related to problems with MySQL libs in a virtualenv, rather than specific problems with Cuckoo.

**Comment by jbremer** [comment]
Ok, I guess we can close this issue then? It's an odd error, because we literally do a check "are there any records in the alembic_version table" and then insert the current revision. So having a duplicate entry error doesn't make a whole lot of sense. Thanks for feedback!
