### ISSUE TITLE
I do not have reports file in my storage/analyses/num route

### ISSUE THREAD

**Issue by ChristineQi** [cuckoosandbox/cuckoo#1433]
I have fund many places,but can solve my problem.everything seem goes fine ,I can submit my project and virtualbox can get the right way.But there is no reports file.I need your help.
there is my cuckoo.log
2017-04-19 21:29:54,964 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/server/cuckoo/storage/binaries/91114be0498ecf4b1b627ad0bfa0c1011093ab931fcf6c15377228651bce44d5"
2017-04-19 21:29:55,071 [lib.cuckoo.core.scheduler] INFO: Task #18: acquired machine XP1 (label=XP1)
2017-04-19 21:29:55,116 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2825 (interface=vboxnet0, host=192.168.56.101, pcap=/home/server/cuckoo/storage/analyses/18/dump.pcap)
2017-04-19 21:29:55,130 [lib.cuckoo.common.objects] WARNING: Error enumerating exported functions: 'NoneType' object has no attribute 'AddressOfData'
2017-04-19 21:30:00,105 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=XP1, ip=192.168.56.101)
2017-04-19 21:32:20,351 [lib.cuckoo.core.guest] INFO: XP1: analysis completed successfully
2017-04-19 21:32:20,483 [lib.cuckoo.core.plugins] WARNING: Unable to stop auxiliary module: Potential error while running tcpdump, did not expect the following standard error output: 'dropped privs to root'.

**Comment by doomedraven** [comment]
https://cuckoo.sh/docs/installation/host/requirements.html?highlight=tcpdump#installing-tcpdump

**Comment by ChristineQi** [comment]
I have reinstall tcpdump according the link you giving me ,the problem still arise

**Comment by jbremer** [comment]
You're probably running cuckoo as root user? Regardless, this error has been resolved if you update to the latest version. Did you have more issues? I'm looking into the `AddressOfData` problem currently.

**Comment by ChristineQi** [comment]
Yes I run cuckoo as root user,I encounter the problem is there has no reports file,don’t know how to solve it.
There is my  analyses result without reports file
![3i3 0g9g_dr3e wtw u k](https://cloud.githubusercontent.com/assets/22070980/25230927/778568ba-2608-11e7-8ac5-dfa0172d902e.png)

**Comment by ChristineQi** [comment]
Yes I run cuckoo as root user,I encounter the problem is there has no reports file,don’t know how to solve it.
There is my analyses result without reports file
![v5ssll0bcj0zaz igem an](https://cloud.githubusercontent.com/assets/22070980/25231080/ffde325a-2608-11e7-8d12-6afcad303998.png)

**Comment by jbremer** [comment]
Is `process_results` enabled in the configuration? Can you show us the status of the analysis in the web interface?

**Comment by ChristineQi** [comment]
I change my reporting.conf as follow:

# Enable or disable the available reporting modules [on/off].
# If you add a custom reporting module to your Cuckoo setup, you have to add
# a dedicated entry in this file, or it won't be executed.
# You can also add additional options under the section of your module and
# they will be available in your Python class.
[jsondump]
enabled = yes
indent = 4
encoding = latin-1
calls = yes

[reporthtml]
enabled = yes

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100

[elasticsearch]
enabled = no
# Comma-separated list of ElasticSearch hosts. Format is IP:PORT, if port is
# missing the default port is used.
# Example: hosts = 127.0.0.1:9200, 192.168.1.1:80
hosts = 127.0.0.1
# Set to yes if we want to be able to search every API call instead of just
# through the behavioral summary.
calls = no
# Index of this Cuckoo instance. If multiple Cuckoo instances connect to the
# same ElasticSearch host then this index (in Moloch called "instance") should
# be unique for each Cuckoo instance.
#
# index = cuckoo
#
# Logging time pattern.  This sets how elasticsearch creates indexes
# by default it is yearly in most instances this will be sufficient
# valid options: yearly, monthly, daily
#
# index_time_pattern = yearly
#
# Cuckoo node name in Elasticsearch to identify reporting host. Can be useful
# for automation and while referring back to correct Cuckoo host. 
#
# cuckoo_node = "cuckoo.example.host"

[moloch]
enabled = no
# If the Moloch web interface is hosted on a different IP address than the
# Cuckoo Web Interface then you'll want to override the IP address here.
# host = 127.0.0.1
#
# Following are various configurable settings. When in use of a recent version
# of Moloch there is no need to change any of the following settings as they
# represent the defaults.
#
# moloch_capture = /data/moloch/bin/moloch-capture
# conf = /data/moloch/etc/config.ini
# instance = cuckoo

[notification]
# Notification module to inform external systems that analysis is finished.
# You should consider keeping this as very last reporting module.
enabled = no

# External service URL where info will be POSTed.
# example : https://my.example.host/some/destination/url
url =

# Cuckoo host identifier - can be hostname.
# for example : my.cuckoo.host
identifier =

[mattermost]
enabled = no

# Mattermost webhook URL.
# example : https://my.mattermost.host/hooks/yourveryrandomkey
# url=
#
# Cuckoo host URL to make analysis ID clickable.
# example : https://my.cuckoo.host/
# myurl=
#
# Username to show when posting message
username = cuckoo
# What kind of data to show apart from default.
# Show virustotal hits.
# show-virustotal=yes
#
# Show matched cuckoo signatures.
# show-signatures=no
#
# Show collected URL-s by signature "network_http".
# show-urls=no
#
# Hide filename and create hash of it
# hash-filename=no

 **If  submit my project in terminal i can get the reports file including report.html report.json,but if submit my project in web interface ,there is no reports file. Is there some problems?Some screenshot:**
![9 b88c4vl ix erzy6 hs2](https://cloud.githubusercontent.com/assets/22070980/25300451/5bb45ed0-2742-11e7-9d22-eec0bb394c9a.png)
![1 ut co w2wkonqd6v3 p](https://cloud.githubusercontent.com/assets/22070980/25300484/f75e6b3c-2742-11e7-914e-27c1fe845ef2.png)
![cmulk6ug 6n3 bp574pn](https://cloud.githubusercontent.com/assets/22070980/25300487/fe874956-2742-11e7-86e3-8093f6cb14f5.png)

**Comment by doomedraven** [comment]
do you have activated `cuckoo process auto` ?

**Comment by ChristineQi** [comment]
I am sorry too late to aply this message, my cuckoo is run normally,thanks your heip

**Comment by jbremer** [comment]
Guess we can close this issue then. Please reopen if you have additional questions or feedback on this issue. Thanks!
