### ISSUE TITLE
Syslog anyone?

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1434]
Hello all,

  Wondering if the old syslog module has been updated for this version? Boy do I miss the syslog output.
Could someone help point me in the right direction?

**Comment by jbremer** [comment]
I don't we've ever had syslog integrated, but we could work on that for one of our upcoming versions.
Anything in particular you'd like to see in there?

**Comment by doomedraven** [comment]
i think he is speaking about cuckoo-mod https://github.com/brad-accuvant/cuckoo-modified/blob/master/modules/reporting/syslog.py

**Comment by RANGERBEE** [comment]
Yes, that's it. I have already tried testing by dropping the module in. At startup all runs fine, though at time of reporting the module is unable to create the syslog report format. I suspect the data is not located in same area or not named the same. I have yet to start digging. I am unfamiliar with the code at this point, though will begin researching.
I am running the 1.3NG mod version along side this 2.0rc2.
Both running well with no problems.. 

Thanks for help guys..

**Comment by doomedraven** [comment]
upgrade to 2.0.1 ;)

**Comment by RANGERBEE** [comment]
Wow 2.0.2a2 is awesome!  Good job guys!  I'll be getting up to speed, hopefully I can contribute on the syslog piece.  Really Im after getting it into my splunk instance like syslog was nicely feeding it prior.  I thought about sending to elastisearch index, then out to splunk index, though would like to avoid all the "hops", disk usage, read / writes yada yada...

Cheers!

**Comment by RANGERBEE** [comment]
Closing, found that monitoring the analyses report.json with  Splunk UF is much easier / efficient..  Let me know if you all need the working configs. ;D
