### ISSUE TITLE
help me kvm.conf

### ISSUE THREAD

**Issue by Killerwhale91** [cuckoosandbox/cuckoo#1437]
Test : Cuckoo SandBox(192.168.250.250), KVM Server(192.168.50.254), TestWindowsXP(192.168.100.100)

        ------------------------------------------------------------------
        |                       KVM Server  ---(virbr2)-----|                            |       
        |                                |                                  |                            |       
        |                            (virbr6)                           |                             |
        |                               |                                  |                              |
        |                               |            Cuckoo Sandbox Server(ens3)    |
        |                               |                                                                |
        |                 TestWindowsXP(eth0)                                             |                    
        -------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
kvm.conf
interface : [interface name] <- Cuckoo Sandbox Inteface? or KVM Server Interface?
and if cuckoo sandbox interface isn't Why No such Device Error Message popup?

-----------------------------------------------------------------------------------------------
I'm Sorry, I don't English....

Thank you :)

**Comment by doomedraven** [comment]
kvm interface

**Comment by jbremer** [comment]
What @doomedraven said, you have an incorrect network setup. Closing issue.
