### ISSUE TITLE
Static analysis tab is blank for PDFs in Cuckoo 2.0.1

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#1439]

**Comment by jbremer** [comment]
Hm, yes. It seems only some PDFs get their data extracted correctly. I'll have to see what's causing the missing information for the other files. Thanks for reporting!

**Comment by jbremer** [comment]
@seanthegeek this has now been improved in our `2.0.3a4` release (install with `pip install cuckoo==2.0.3a4`). Metadata, URLs, and Javascript are now shown slightly more properly in the web interface, the UI has been improved, and you can directly submit any and all embedded URLs in the PDF! The Signature for PDF URLs has yet to be done, but we have an internal todo item for that.
Closing issue as resolved. Thanks!
