### ISSUE TITLE
The Firefox module is no longer a selectable package

### ISSUE THREAD

**Issue by Popsiclestick** [cuckoosandbox/cuckoo#1441]
## Issue
Despite the [package existing under the windows module](https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/analyzer/windows/modules/packages/ff.py) in ```../cuckoo/analyzer/windows/modules/packages/ff.py```. It doesn't appear to be a selectable option, nor is it referenced in the [documentation](http://docs.cuckoosandbox.org/en/latest/usage/packages/).
![Picture for reference](https://raw.githubusercontent.com/Popsiclestick/popsiclestick.github.io/master/Screen%20Shot%202017-04-20%20at%209.40.02%20AM.png)

**Comment by jbremer** [comment]
Committed the above, seems like it's in the list now!

**Comment by jbremer** [comment]
Closing as resolved, thanks for reporting etc.
