### ISSUE TITLE
Cuckoo Web "How to" links

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1445]
The revised Cuckoo Web interface include a number of "How to" links on the dashboard. They seem to have no hrefs, and currently do nothing. Unclear if they are simply not populated or if there is some JS handler for them perhaps going wrong.

**Comment by jbremer** [comment]
Yeah, I commented them out earlier today - we'll have to brainstorm a bit to see what kind of URLs would be useful here. See also 52e67017c6d647e589244b9e0a251103577832e9. Going to close this issue though :-) thanks for the feedback!
