### ISSUE TITLE
Cuckoo Submit by machine is broken

### ISSUE THREAD

**Issue by gra55h0pp3r** [cuckoosandbox/cuckoo#1446]
When I submit a sample and specify a machine that I want to run the sample against it fails. I get the the following error from cuckoo -d "ERROR: Cannot acquire machine: No machines match selection criteria." and in the report I see the following error: 

It appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to the connect to the Guest or the other way around (i.e., Guest wasn't able to contact the Cuckoo Host). There could be a few reasons for this:
    The IP address of the VM has been configured incorrectly. Please verify that the VM has a static IP address, that it matches the one in the Cuckoo configuration, and that the configured network interface exists and is up. Also, in case of VirtualBox, did you configure the network interface to be a "Host-Only interface"?
    Please check that there are no firewalls in-place that hinder the communication between your Host and Guest.
    If you've triple-checked the above and are still experiencing issues, then please contact us. Just below the errors you'll find a Send Feedback button to do so.

Now, if I don't specify a machine to run it against it works just fine. I machine I originally picked runs. I'm testing the new cuckoo prior to deploying it production right now, so I only have one VM, but in my production environment I have 10.

Do you know when their will be a fix for it as I specify most machine to use in my production environment.

**Comment by jbremer** [comment]
I tested this myself yesterday and from what I could see in the database it seemed fine, I'll do some additional testing though - thanks for reporting!

**Comment by jbremer** [comment]
@gra55h0pp3r Please find the commit above, it should fix the issue you described here. I'll be pushing out a new alpha release (probably) today containing this fix today - will let you know. Thanks again!

**Comment by jbremer** [comment]
Resolved in `2.0.2a3`, closing issue! Thanks.
