### ISSUE TITLE
JSON problem

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1447]
If i parse task report with perl 
$response =$ua->get("http://x.x.x.x:8090/tasks/report/2");
$jsonresponse=decode_json($response->decoded_content);
i get garbage after JSON object, at character offset 7271589
[json.txt](https://github.com/cuckoosandbox/cuckoo/files/946642/json.txt)
There is a problem in this particular json response, other json works correctly

**Comment by jbremer** [comment]
Wow, something definitely went wrong there. Do you get the exact same JSON file if you run the same query again? What version of Cuckoo is this? Fwiw, at the very end you see the same JSON data twice - rending the JSON document invalid.

**Comment by Maurotb** [comment]
Yes, same json if i relaunch http://x.x.x.x:8090/tasks/report/2
My version in 2.0.1

**Comment by jbremer** [comment]
Ok. Can you reprocess the analysis and try again (i.e., `cuckoo process -r 2`)?

**Comment by Maurotb** [comment]
Ok, i have launched cuckoo process -r 2 and now is ok.... Can it be a problem that is repeated?

**Comment by jbremer** [comment]
I'm not sure, normally it shouldn't. Is your Cuckoo machine running on age-old hardware or something? The only reason I can come up for this error is some sort of memory / harddisk corruption, unrelated to Cuckoo.

**Comment by Maurotb** [comment]
mmm no, i running on esxi, debian8 with 100Gb disk (38% used) and 8Gb ram (3 used)...
I'm doing a lot of tests, maybe I caused the problem when I started mysql backend...

**Comment by jbremer** [comment]
Hm, that should be mostly fine. Definitely haven't seen this before. Anyway, probably shouldn't be happening again, so going to close this issue. If it does happen again please do reopen the issue or create a new one so that we can really get to the bottom of this. Thanks!

**Comment by Maurotb** [comment]
ok thanks!
