### ISSUE TITLE
CuckooStartupError: There was a syntax error in one or more Yara rules:(2, 'No such file or directory')

### ISSUE THREAD

**Issue by Roslekas** [cuckoosandbox/cuckoo#1448]
Hi,

1. having problem with Yara rules :/
Linux ubuntu 4.8.0-46-generic #49~16.04.1-Ubuntu
Cuckoo Sandbox 2.0.1
yara 3.4.0

![image](https://cloud.githubusercontent.com/assets/16913780/25275743/825df53a-269f-11e7-8974-9658584c8da8.png)

2. Also tried to download rules from https://github.com/Yara-Rules/rules and got error "duplicate identifier ", so all rules are already included with cuckoo ?
3. but without adding rules from https://github.com/Yara-Rules/rules every time in report i got "yara rules not matched"

:/ so i don't understand, yara rules are included or not, because in online YaraRules Analyzer finds binary, in  cuckoo sandbox report  - "yara rules not matched"

![image](https://cloud.githubusercontent.com/assets/16913780/25276028/dfff8e14-26a0-11e7-9a4a-d6c3affa9aba.png)

Big Thanks

**Comment by RANGERBEE** [comment]
Im pretty sure the following must apply:

"**Adding YARA rules:**
Cuckoo looks for YARA rules three sub directories in data/yara, by the type of data to match:

binaries
memory
urls
Place your .yar rule files in the appropriate directories, and then restart Cuckoo."

What I am now doing is updating the index files to point to the correct directories of the rules I just dropped in..  then a restart to test.  I will update here..

**Comment by jbremer** [comment]
By default Cuckoo doesn't ship too many rules - so `yara rules not matched` means that, well, no Yara rules matched. You can't pull the `Yara-Rules` repository straight away for the simple fact that it's currently not very well organized and contains duplicate rules etc, those have to be sorted at some point.
I was hoping to work on that, but that project doesn't seem to go through unfortunately.

**Comment by Roslekas** [comment]
Hi,

1. my working catalog of cuckoo look like this:

i created data folder, because it wasn't when i installed cuckoo...
![image](https://cloud.githubusercontent.com/assets/16913780/25325727/a96d1cae-28d5-11e7-9a5b-c8271a49a978.png)

2. every time i start cuckoo, it creates index_binaries.yar and index_memory.yar files and seems cuckoo looking yara rules in /root/.cuckoo/yara/binaries folder, but not in /root/.cuckoo/data/ folder. If binaries folder is without any rules, so index_binaries.yar after starting cuckoo is clean, if binaries folder is with rules, index_binaries.yar creates it self with rules written inside like this:
![image](https://cloud.githubusercontent.com/assets/16913780/25325935/916b415c-28d6-11e7-9549-d0adf954afb1.png)

don't know why but cuckoo is not starting with in data folder or in yara binaries folder

![image](https://cloud.githubusercontent.com/assets/16913780/25325988/ce81a28e-28d6-11e7-9dfb-3942ed5743a1.png)

3. now tried to disable yara in processing.conf and memory.conf, got error, not starting, i think need to remove yara from ubuntu...

![image](https://cloud.githubusercontent.com/assets/16913780/25326173/b742a112-28d7-11e7-88d2-9116ef77f258.png)

thanks

**Comment by Roslekas** [comment]
Created new virtualenv and cuckoo working with volitility 2.5, yara 3.5 and did not installed python-yara and also without yara rules...cuckoo started well without creating index_binaries.yar and index_memory.yar also disappeared error "No such file or directory"... but got error while volatility was running :/
![image](https://cloud.githubusercontent.com/assets/16913780/25337547/f941a004-2904-11e7-9d9b-26db5026099e.png)

Any idea ? my vm is virtualbox...

Thanks

**Comment by jbremer** [comment]
Thanks for that error @Roslekas, I hadn't seen that one yet. Currently working on getting Volatility all sorted out, so please stay tuned!

**Comment by Roslekas** [comment]
OK thanks

**Comment by RANGERBEE** [comment]
I noticed that when you muck around with the Yara rules / folders it hoses the module. I leave it all default rules and settings for now and it starts just fine and runs the module with default rules just fine. Cuckoo2.02.a3 , Yara3.4, Volatility2.6, Python 2.7.6

**Comment by Roslekas** [comment]
Yes its true, now cuckoo working with default rules without additional yara rules and without installing python-yara, so yarascan error disappeared:
![image](https://cloud.githubusercontent.com/assets/16913780/25340695/358a133e-290f-11e7-80da-9cc717b2c3f9.png)

**Comment by jbremer** [comment]
So I guess we can close this issue?

**Comment by Roslekas** [comment]
Yes

**Comment by jbremer** [comment]
Sweet :)

**Comment by Roslekas** [comment]
Maybe it is able to import other yara rules than the "https://github.com/Yara-Rules/rules" without getting "duplicate identifier" error ?

Thanks
