### ISSUE TITLE
Mem profile specification - option

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1452]
version 2.02a2:

  Wondering why we can not specify the mem profile in the machine option?  When I specify the machine option under the machine profile such as:

 (Optional) Specify a memory profile to be used by volatility for this
virtual machine. This will override the guest_profile variable in memory.conf which solves the problem of having multiple types of VM's
and properly determining which profile to use. Examples below:
mem_profile = WinXPSP2x86

, the following error is observed:

Configuration error: Type of config parameter virtualbox:cuckoo1:mem_profile not found! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.

Should I just keep the mom profile omitted? Will future release have something based on genre like "basic, advanced, super-advanced"?  I see something eluding to this in the mem.conf...

Thx!

**Comment by doomedraven** [comment]
you can backport code from this PR for memory only https://github.com/cuckoosandbox/cuckoo/pull/1354

**Comment by jbremer** [comment]
@RANGERBEE We've put out a new release, version `2.0.2`, which you may obtain through `pip install -U cuckoo`, including various improvements for the `Volatility` / `memory.py` issue posted above. Please check it out! From now on you can specify the profile for each VM by adding, e.g., `osprofile = WinXPSP2x86`, to each of your VMs.
I'll leave this issue open for now - in case you require any additional support on this matter - but will be closing it in the coming days. Thanks for your feedback and if you have any additional feedback, do not hesitate to let us know or create a new issue!

Please note that our new release uses the configuration value `osprofile` rather than `mem_profile` so you'll have to slightly tweak your configuration.
I don't think the configuration files will get any basic/advanced tags, but for the web-based configuration editor that we've planned that might be an idea ;-)

**Comment by RANGERBEE** [comment]
@jbremer  I am currently running 2.0.2a3. How do I upgrade this version? Will it overwrite and supersede all current updates?

Thx!

**Comment by jbremer** [comment]
Just `pip install -U cuckoo` will do! Yes, it will supersede your `2.0.2a3` :)

**Comment by RANGERBEE** [comment]
@jbremer  Could you tell me what the allowed mem profile syntaxes used? I am running into an error for a Win7SP1x86 profile setting on a Win7x86 VM.  Error in processing as follows:

> 2017-04-26 16:00:56,144 [volatility.debug] ERROR: This command does not support the selected profile.
2017-04-26 16:00:56,144 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #8:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1105, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1023, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 934, in netscan
    for net_obj, proto, laddr, lport, raddr, rport, state in commands:
  File "/usr/local/lib/python2.7/dist-packages/volatility/plugins/netscan.py", line 224, in calculate
    debug.error("This command does not support the selected profile.")
  File "/usr/local/lib/python2.7/dist-packages/volatility/debug.py", line 60, in error
    sys.exit(1)
SystemExit: 1
26/4/2017 -- 16:00:57 - <Info> - Configuration node 'EXTERNAL_NET' redefined.
26/4/2017 -- 16:00:57 - <Notice> - This is Suricata version 3.2.1 RELEASE
26/4/2017 -- 16:01:02 - <Notice> - all 13 packet processing threads, 4 management threads initialized, engine started.
26/4/2017 -- 16:01:02 - <Notice> - Signal Received.  Stopping engine.
26/4/2017 -- 16:01:02 - <Notice> - Pcap-file module read 81 packets, 9514 bytes
[26/Apr/2017 16:01:22] "GET /dashboard/ HTTP/1.1" 200 22340

I do not get this error when running the WinXPSP2x86 profile on an XP VM.


Cuckoo 2.0.2 latest build, Volatility 2.6, Yara 3.4

**Comment by RANGERBEE** [comment]
found it.  ;-)

https://github.com/volatilityfoundation/volatility/wiki/Volatility-Usage

**Comment by RANGERBEE** [comment]
Works beautifully now..     Had to specify my osprofile as "osprofile = WinSP1x86_23418"

**Comment by jbremer** [comment]
I think you meant `Win7SP1x86_23418`, but yes, that's great to hear! Closing issue as resolved.
