### ISSUE TITLE
Cuckoo Package : WGUI, MISP page

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1460]
Hi guys,

there is no scroll bars on the MISP page and the Left hand menu is all screwed up :(

![screenshot from 2017-04-23 13-29-19](https://cloud.githubusercontent.com/assets/17818264/25309737/f4743168-2828-11e7-9e30-c637bfbdc2f5.png)

**Comment by jbremer** [comment]
Ah, thanks. We'll have to check that out.

**Comment by jbremer** [comment]
Supposedly fixed in #1784 #1789. Thanks for reporting. Closing as resolved.
