### ISSUE TITLE
Restart analisys if restart services or server

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1462]
If i restart services or server during analisys (not pending,running analysys), 
analysys are not re-performed and are lost

**Comment by doomedraven** [comment]
yup

**Comment by SparkyNZL** [comment]
Yes, well they aren't lost, but the never get reported, perhaps some way to
list the items run but not yet reported, in old cuckoo I found this quite
handy 😀 at the moment u need to do a database query to get a list of these
un reported items and then manually report them with cuckoo process -r
xxx-xxxx

Cheera

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data-private/cwd/conf/cuckoo.conf#L32
if was analyzed this do the trick

**Comment by Maurotb** [comment]
Ok thanks!

**Comment by jbremer** [comment]
Closing as resolved. Thanks!
