### ISSUE TITLE
Feature Request: Add custom tag to analisys

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1463]
I need to add a custom tag to analisys. 
This tag should then be visible in the report and in json.
It is very useful to know the origin of the analysis and to have a match with the program that injected him.

**Comment by Maurotb** [comment]
Sorry, i have find "custom" item to post in /task/create/file
That was what I needed... ;)

**Comment by jbremer** [comment]
Yep! Closing issue as resolved.
