### ISSUE TITLE
Cuckoo Package: Upgrade causes whitelist overwrite

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1465]
Hey guys, when you do an upgrade or update with pip, this deletes the domain.txt white list, which is a pain as i have quite a big white list and i have to keep updating it manually, can the while list be put in the .cuckoo directory ?

**Comment by jbremer** [comment]
Hm, I had moved it to the private directory because I thought that'd be better - assuming users don't update it all that much (see also f240c5eb4d6abf004ed15917878fc8208df682c8), but perhaps we can have Cuckoo load both files; from private and from CWD.

**Comment by razuz** [comment]
@jbremer you want to make this configurable or just load both files in a row ?

another thing I noticed is that whitelists are loaded even if whitelisting is not enabled. maybe that check should be moved into _build_whitelist() instead of _is_whitelisted()

**Comment by razuz** [comment]
just for the ref ... same thing applies here
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/common/whitelist.py#L13

**Comment by jbremer** [comment]
This will indeed be possible in the upcoming release. Closing as resolved.
