### ISSUE TITLE
Error while submitting file for anaysis

### ISSUE THREAD

**Issue by Mackousko12** [cuckoosandbox/cuckoo#1466]
Hi folks,

I am getting an error while submitting the file for analysis. Following is a Cuckoo web log. Any help is much appreciated.

[24/Apr/2017 11:07:01] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 13
[24/Apr/2017 11:07:01] "GET /static/fonts/Roboto_normal_400_default.woff HTTP/1.1" 304 0
[24/Apr/2017 11:07:01] "GET /cuckoo/api/status HTTP/1.1" 200 514
[24/Apr/2017 11:07:11] "POST / HTTP/1.1" 405 0
[24/Apr/2017 11:07:11] "POST /submit/api/presubmit/ HTTP/1.1" 302 0
- Broken pipe from ('192.168.0.90', 52342)

IP in the broken pipe is a host IP address.

**Comment by kevross33** [comment]
Try submitting it using the submit page rather than the one on the dashboard. I can't remember if this is exactly the same error as I had but I had a similar issue if not the same  when submitting files from the dasboard.

**Comment by jbremer** [comment]
Yes, please update to `2.0.2a4` for now (which contains a fix for your error)!
I'll be putting out `2.0.2` shortly after finishing up on some volatility related issues.

**Comment by Mackousko12** [comment]
Thanks lads.

@jbremer : If I use 'sudo pip install -U cuckoo' would that update Cuckoo without change in my existing configuration?

**Comment by jbremer** [comment]
Yes, although `-U` will get you `2.0.1` at the moment, rather than `2.0.2a4` which contains the bug fix for the bug you mentioned (since `2.0.2` wasn't released yet).

**Comment by jbremer** [comment]
That said, closing this issue as resolved.
