### ISSUE TITLE
Potential Bugs

### ISSUE THREAD

**Issue by Mackousko12** [cuckoosandbox/cuckoo#1470]
Hi folks,

Not sure if only I am having this issue or everyone else but I am facing the following two issues.

1) Analysis score is not updating (Always 0/10)
2) Running analysis doesn't show up in pending tasks.

Thanks

**Comment by doomedraven** [comment]
no cuckoo versions, no logs, nothing, is not bug reporting :P

**Comment by SparkyNZL** [comment]
If u are using cuckoo package, make sure you do a cuckoo community

Cheers

**Comment by Mackousko12** [comment]
Attached log files. I don't see any error during analysis, its just do not set the score. Also this is just one example, I have this issue in all my analysis.

[Cuckoo log.txt](https://github.com/cuckoosandbox/cuckoo/files/954870/Cuckoo.log.txt)
[Analyzer log.txt](https://github.com/cuckoosandbox/cuckoo/files/954871/Analyzer.log.txt)

Thanks

**Comment by jbremer** [comment]
Did you do as @SparkyNZL said, running `cuckoo community` to load our signatures?

**Comment by Mackousko12** [comment]
Thanks. It appears to be working.

quick question before you close this ticket, I ran analysis on other instance of cuckoo (Old instance running 2.0.-rc2) and all the analysis appeared on my new instance of cuckoo web portal. I am using the default db.

Thanks

**Comment by jbremer** [comment]
Yes, they're persisted across upgrades of Cuckoo! We try to remain as backwards compatible as possible ;-) Thanks for the feedback, let us know if you have any more.
