### ISSUE TITLE
System info - Top data?

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1472]
Had an idea about posting top data to the system info box, next to disk usage..    (2.0.2a3)
Any advice?

**Comment by jbremer** [comment]
We can include the CPU load, yeah. Thanks for the suggestion!

**Comment by jbremer** [comment]
We've added the CPU load. Will be adding memory usage as well and then I think this issue should be good to go :-)

**Comment by RANGERBEE** [comment]
@jbremer   Thanks Bud!!    A little nit-picky note....   I have noticed the disk usage indicator incorrectly creates an abbreviation for TeraByte.   Should be TB (?)

![image](https://cloud.githubusercontent.com/assets/15255470/25669432/0e36799c-3019-11e7-8d49-793e9777dcdc.png)

**Comment by jbremer** [comment]
TIL https://en.wikipedia.org/wiki/Tebibyte Well, it's mostly the same.. :-)
Anyone else have a preference?

**Comment by RANGERBEE** [comment]
aww dang it, I was looking here..  http://www.abbreviations.com/abbreviation/TeraByte

**Comment by RANGERBEE** [comment]
@jbremer  What version should I -U to see the new load graphics?

**Comment by jbremer** [comment]
@RANGERBEE we've just put out `2.0.3a4` including CPU & memory data (and some other stuff as well). Install with `pip install cuckoo==2.0.3a4`. We're finishing up some other stuff for `2.0.3` release :)

**Comment by jbremer** [comment]
We also changed the `TiB` vs `TB` thing, so this issue can be closed altogether now, thanks!
