### ISSUE TITLE
Cuckoo launch notification.py two time

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1473]
Cuckoo launch notification.py two time per analisys,
ver 2.0.1
mongodb enabled

**Comment by jbremer** [comment]
I'll test this in a bit, but in the meanwhile, do you have any logs to show this behavior? :)

**Comment by Maurotb** [comment]
Sorry my problem,
i have set process_results=on in cuckoo.conf,but i have "cuckoo process instance" daemon in my setup...
All report are processing twice... To resolve, set process_results=off

**Comment by jbremer** [comment]
Ok, closing as resolved.
