### ISSUE TITLE
Problem with image in some report

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1474]
Cuckoo 2.0.0
In some report i get on top of web page:
Failed to run the processing module "Screenshots" for task #132:
but on bottom i correctly view images.
In this case, html page generated by singlefile.py, no images are present.

This is my cuckoo.log during issue

2017-04-24 22:49:05,550 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Screenshots" for task #132:
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 235, in process
    data = current.run()
  File "/venv/local/lib/python2.7/site-packages/cuckoo/processing/screenshots.py", line 51, in run
    im.thumbnail((320, 320), PIL.Image.ANTIALIAS)
  File "/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 1798, in thumbnail
    im = self.resize(size, resample)
  File "/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 1538, in resize
    self.load()
  File "/venv/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 218, in load
    "(%d bytes not processed)" % len(b))
IOError: image file is truncated (15 bytes not processed)

**Comment by jbremer** [comment]
Can you share some of these corrupted screenshots? What's your configuration like, e.g., using VirtualBox?

**Comment by SparkyNZL** [comment]
My 2cents, I find this happens when a screen shot is being taken and vbox
tears the machine down causing a corrupt image file.

**Comment by jbremer** [comment]
Thanks @SparkyNZL, that makes sense. I'll fix it in a bit.

**Comment by Maurotb** [comment]
yes, i use virtualbox!

**Comment by Maurotb** [comment]
I attach log for one task with problem.
The error is in cuckoo-process_0-stderr.log (IOError: image file is truncated)

[Analyzer.log.txt](https://github.com/cuckoosandbox/cuckoo/files/960887/Analyzer.log.txt)
[Cuckoo.log.txt](https://github.com/cuckoosandbox/cuckoo/files/960888/Cuckoo.log.txt)
[cuckoo-process_0-stderr.txt](https://github.com/cuckoosandbox/cuckoo/files/960889/cuckoo-process_0-stderr.txt)

**Comment by jbremer** [comment]
Thanks @Maurotb! I've implemented some error handling for this issue, see also the commit above. Will push out a new alpha release soon.

**Comment by jbremer** [comment]
You'll be able to find the fix in `2.0.3a1`!

**Comment by jbremer** [comment]
I assume you haven't run into this issue anymore since? Will be closing this issue soon'ish if that's the case.

**Comment by Maurotb** [comment]
I'm waiting for update to test.... if i make pip install -U cuckoo
i stay on 2.0.2...

**Comment by jbremer** [comment]
As mentioned earlier you can find this fix in `2.0.3a1`. I just pushed `2.0.3a3` though, so I suggest to update there instead; `pip install cuckoo==2.0.3a3`.

**Comment by Maurotb** [comment]
Ok thanks, i did not know i could decide the version with pip. 
Now I've updated cuckoo

**Comment by Maurotb** [comment]
Ok! The problem does not occur anymore. Thanks

**Comment by jbremer** [comment]
Oke, excellent. Closing issue.
