### ISSUE TITLE
Analyse Network Traffic

### ISSUE THREAD

**Issue by Huthifh** [cuckoosandbox/cuckoo#1477]
Dear All.
Can cuckoo analyse a network traffic ?

**Comment by doomedraven** [comment]
yes, read the documentation

**Comment by Huthifh** [comment]
I don't mean PCAP file.
I mean working as a network sniffer and automatically extract file or URL and analyses it ?

**Comment by doomedraven** [comment]
no, check suricata/snort reporting module, you can extend it for your needs

**Comment by Huthifh** [comment]
what you mean ?
could you please explain more ?

**Comment by jbremer** [comment]
@Huthifh what @doomedraven was trying to say is that Cuckoo isn't a network IDS. What you can do, however, is put Suricata or Bro in your network and forward their results to Cuckoo. I believe there's a script floating around the internet for the Bro <> Cuckoo integration.

**Comment by Huthifh** [comment]
I could't find any thing about integration ? could you please where can I found it ?

**Comment by jbremer** [comment]
It's not yet released to the public - if I hear something about it I'll let you know. Otherwise it shouldn't be too much effort to develop a basic version of such functionality yourself, I think.

**Comment by jbremer** [comment]
@Huthifh You can find the blogpost at https://davyboekhout.nl/posts/automate-cuckoo-bro-python.html and the code at https://github.com/dboekhout/BroCoo/blob/master/koekoe.py, hope it helps ;-)
We haven't taken the effort yet to really integrate it with Cuckoo (as official code etc, I mean). That'll be done in the future.

**Comment by jbremer** [comment]
We have an internal todo item on officially supporting the Bro script, to be continued. Closing issue as resolved. Please reopen if that's not the case. Thanks!
