### ISSUE TITLE
process_results = no

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1482]
When selecting the configuration to perform processing in separate threads, I receive no results.

After the analysis on guests, all work stops.  Should this happen by design? I was under the impression that if selecting the "no" switch then the processing would occur in independent threads.?

Thanks!

CuckooSandbox- 2.0.2a3, Volatility 2.6, Yara 3.4, Ubuntu Trusty...

**Comment by jbremer** [comment]
Well, you do have to run `cuckoo process [instance name]` in that case ;-) See also https://cuckoo.sh/docs/usage/utilities.html#cuckoo-process
Closing issue as this is well documented etc, thanks for reaching out though!

**Comment by RANGERBEE** [comment]
thanks!   I just couldn't find that dang doc...
