### ISSUE TITLE
Supervisord not stop cuckoo web

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1483]
Using 2.0.1 and supervisord.conf provided with package, daemon is 3.0r1-1.
Debian 8
When i stop supervisord in log i find

2017-04-25 22:34:43,729 WARN received SIGTERM indicating exit request
2017-04-25 22:34:43,729 INFO waiting for cuckoo-daemon, cuckoo-process_0, cuckoo-process_3, cuckoo-process_2, cuckoo-process_4, cuckoo-web, cuckoo-process_1, cuckoo-api to die
2017-04-25 22:34:43,738 INFO stopped: cuckoo-process_1 (terminated by SIGTERM)
2017-04-25 22:34:43,739 INFO stopped: cuckoo-process_0 (terminated by SIGTERM)
2017-04-25 22:34:43,739 INFO stopped: cuckoo-web (terminated by SIGTERM)
2017-04-25 22:34:43,748 INFO stopped: cuckoo-daemon (terminated by SIGTERM)
2017-04-25 22:34:43,748 INFO stopped: cuckoo-process_3 (terminated by SIGTERM)
2017-04-25 22:34:43,749 INFO stopped: cuckoo-process_2 (terminated by SIGTERM)
2017-04-25 22:34:43,749 INFO stopped: cuckoo-api (terminated by SIGTERM)
2017-04-25 22:34:43,750 INFO stopped: cuckoo-process_4 (terminated by SIGTERM)

but

ps -aux|grep cuck
cuckoo    7710  3.3  0.6 579996 162312 ?       Sl   22:34   0:05 /venv/bin/python /venv/bin/cuckoo web runserver 0.0.0.0:8080
root      7845  0.0  0.0  12752  2280 pts/1    S+   22:37   0:00 grep cuck

This is my supervisord.conf

[supervisord]
logfile_maxbytes=10MB                           ; maximum size of logfile before rotation
logfile_backups=10

[program:cuckoo-daemon]
environment=PATH="/venv/bin:%(ENV_PATH)s"
command = /venv/bin/python /venv/bin/cuckoo -d -m 10000
user = cuckoo
startsecs = 30
autorestart = true

[program:cuckoo-process]
environment=PATH="/venv/bin:%(ENV_PATH)s"
command = /venv/bin/python /venv/bin/cuckoo process p%(process_num)d
process_name = cuckoo-process_%(process_num)d
numprocs = 5
user = cuckoo
autorestart = true

[program:cuckoo-web]
environment=PATH="/venv/bin:%(ENV_PATH)s"
command = /venv/bin/python /venv/bin/cuckoo web runserver 0.0.0.0:8080
user = cuckoo
startsecs = 30
autorestart = true

[program:cuckoo-api]
environment=PATH="/venv/bin:%(ENV_PATH)s"
command = /venv/bin/python /venv/bin/cuckoo api -H 0.0.0.0 -p 8090
user = cuckoo
startsecs = 30
autorestart = true

[group:cuckoo]
programs = cuckoo-daemon, cuckoo-process, cuckoo-web,cuckoo-api

i have try to add stopsignal=kill with no success

If i stop cuckoo-web with supervisorctl , 
supervisor> stop cuckoo:cuckoo-web
cuckoo:cuckoo-web: stopped
but process stay running

**Comment by jbremer** [comment]
First of all, this is not how you properly deploy the Web Interface. We have documentation on doing so with `uWSGI` & `nginx`.
Secondly, what about any logging?

**Comment by Maurotb** [comment]
cuckoo-web of supervisord is empty , other log in first post.
web insterface is only for testing and monitor, simple setup it's enough for me...

When i launch supervisord i found this process

root@Shark-Cuckoo01:/Config/.cuckoo/log# ps -auxwww|grep pyth|grep web

cuckoo   20092 89.0  0.6 511412 162320 ?       Sl   08:57   0:01 /venv/bin/python /venv/bin/cuckoo web runserver 0.0.0.0:8080
cuckoo   20350  0.0  0.0  50084 17816 ?        R    08:57   0:00 /venv/bin/python /venv/bin/cuckoo web runserver 0.0.0.0:8080

Two web process are present, when i stop it supervisord kill only one, other process stay active
2017-04-26 08:58:38,912 DEBG killing cuckoo-web (pid 20092) with signal SIGTERM

**Comment by jbremer** [comment]
If you want a simple setup, why not just run `cuckoo web` in a `screen` session?
Seems overly complex to use `supervisor` for that.

**Comment by Maurotb** [comment]
Ok thanks

**Comment by jbremer** [comment]
@Maurotb did you resolve this issue by now? If so, we can close this issue.

**Comment by Maurotb** [comment]
No, but i have make a script to manually kill cuckoo web when i stop supervisor...
cuckoo web spawn two process , one of this has a pid that supervisor not know...
Is a workarround but ok for me...

**Comment by jbremer** [comment]
Yes, that's because `cuckoo web` is using Django's **development** HTTP server. As I mentioned a proper deployment is using `uwsgi`/`nginx`. Closing as resolved anyway.
