### ISSUE TITLE
"ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating" after submitting sample to Win XP SP3

### ISSUE THREAD

**Issue by plaxer** [cuckoosandbox/cuckoo#1484]
After submitting the malware sample, the XP virtual machine force closes and I receive the error below:

```
            _       _                   _             _              _            _
          /\ \     /\_\               /\ \           /\_\           /\ \         /\ \
         /  \ \   / / /         _    /  \ \         / / /  _       /  \ \       /  \ \
        / /\ \ \  \ \ \__      /\_\ / /\ \ \       / / /  /\_\    / /\ \ \     / /\ \ \
       / / /\ \ \  \ \___\    / / // / /\ \ \     / / /__/ / /   / / /\ \ \   / / /\ \ \
      / / /  \ \_\  \__  /   / / // / /  \ \_\   / /\_____/ /   / / /  \ \_\ / / /  \ \_\
     / / /    \/_/  / / /   / / // / /    \/_/  / /\_______/   / / /   / / // / /   / / /
    / / /          / / /   / / // / /          / / /\ \ \     / / /   / / // / /   / / /
   / / /________  / / /___/ / // / /________  / / /  \ \ \   / / /___/ / // / /___/ / /
  / / /_________\/ / /____\/ // / /_________\/ / /    \ \ \ / / /____\/ // / /____\/ /
  \/____________/\/_________/ \/____________/\/_/      \_\_\\/_________/ \/_________/

 Cuckoo Sandbox 2.0.2
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

2017-04-26 05:56:38,501 [cuckoo.core.startup] WARNING: Unable to import yara (please compile from sources)
2017-04-26 05:56:38,503 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-26 05:56:38,905 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-26 05:56:38,925 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-26 05:56:54,507 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "Quittung.com" (task #6, options "")
2017-04-26 05:56:54,535 [cuckoo.core.scheduler] INFO: Task #6: acquired machine xp (label=xp)
2017-04-26 05:56:54,541 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 8168 (interface=vboxnet0, host=192.168.56.101, pcap=/home/olu/.cuckoo/storage/analyses/6/dump.pcap)
2017-04-26 05:56:57,413 [cuckoo.core.guest] INFO: Starting analysis on guest (id=xp, ip=192.168.56.101)
2017-04-26 05:57:02,464 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=xp, ip=192.168.56.101)
2017-04-26 06:00:03,069 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-04-26 06:00:05,032 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label xp to path /home/olu/.cuckoo/storage/analyses/6/memory.dmp
2017-04-26 06:00:09,428 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2017-04-26 06:00:09,429 [cuckoo.processing.memory] ERROR: Cannot run volatility module: the volatility library is not available. Please install it according to their documentation.
2017-04-26 06:00:09,762 [cuckoo.core.scheduler] INFO: Task #6: reports generation completed (path=/home/olu/.cuckoo/storage/analyses/6)
2017-04-26 06:00:09,789 [cuckoo.core.scheduler] INFO: Task #6: analysis procedure completed
```
Everything is setup and properly configured but cuckoo times out after about 2-3 minutes. Here is a screenshot of the `agent.py` of a previous sample which returned the same error as well.:

![2017-04-26 05_07_10-greenshot](https://cloud.githubusercontent.com/assets/27310922/25419022/d16960c8-2a47-11e7-83b1-e8c58947baba.png)

I tried two different samples but they both returned the same timeout error. Is there any fix for this or is the problem from my end? @jbremer I installed alpha build but had issues so had to go back to previous build.

Guest: Ubuntu 17.04
VM: Windows XP SP3

**Comment by plaxer** [comment]
By the way, has anyone run an analysis of the finfisher or finspy malware using cuckoo in the past? Does the malware detect sandbox and fail to run or something like that?

**Comment by azza39925** [comment]
I am having the exact same issue.

**Comment by ikiril01** [comment]
See also: https://github.com/cuckoosandbox/cuckoo/issues/1479

It looks like this is really an issue with the new analyzer not working properly on Windows XP.

**Comment by jbremer** [comment]
I'll give it a try as well @ikiril01, thanks.

**Comment by plaxer** [comment]
Any luck resolving this issue?

**Comment by ikiril01** [comment]
@plaxer your best bet at this point is to build a Windows 7 (or later) guest VM.

**Comment by RANGERBEE** [comment]
Analyzer working fine here on XPSP3x86.   Be sure to specify in your machine config the correct mem profile - now known as "osprofile".   What I did today was set my Xp Vm osprofile to:

> "osprofile = WinXPSP3_x86"

Im running Cuckoo 2.0.2 latest update (today), Volatility 2.6, Yara 3.4, Python 2.7..
sudo pip install -U cuckoo

Also see:  https://github.com/volatilityfoundation/volatility/wiki/Volatility-Usage#selecting-a-profile

**Comment by plaxer** [comment]
I was able to successfully analyse 3 samples on a win7 VM. Is there a reason why this no longer works on xp VMs?

**Comment by RANGERBEE** [comment]
I too always hit a critical timeout with xp machine. After setting osprofile, I now get results  including screenshots with the critical timeout.  Running pafish always hits critical timeout in either xp or win7 guests.
I will try to trace and post findings.

**Comment by jbremer** [comment]
I did an analysis just now on Windows XP and that seemed to work just fine?
https://cuckoo.sh/8c42d0261a327fac/screenshot.png

**Comment by ikiril01** [comment]
@jbremer yeah it seems like it works fine for some but others are having this issue. What Host OS/virtualization machinery are you using in your testing?

Here's my setup:
* Cuckoo v2.0.1
* Monitor version: 2bd01...
* Host: Ubuntu 16.04
* Guest: Windows XP SP3
   * Firewall and AV off
* Virtualization: Virtualbox 5.0.32_Ubuntu

**Comment by plaxer** [comment]
@jbremer can you please post your conf files so I can compare to mine to see what's wrong?

**Comment by plaxer** [comment]
- Cuckoo Sandbox 2.0.2
- Host: Ubuntu 17.04
- Guest: Windows XP SP3 (No AV and Firewall off)
- Latest Virtual box 5.1.8 IIRC

That's my setup

**Comment by plaxer** [comment]
5.1.18

**Comment by plaxer** [comment]
@jbremer how do I get the file?

**Comment by jbremer** [comment]
Still working on finishing off on some CWD migration code, please stay tuned ;-)

**Comment by jbremer** [comment]
@plaxer @ikiril01 @RANGERBEE Thanks for the feedback - it is indeed correct that Windows XP analysis was broken. In the meanwhile we've put out a new alpha release which fixes these issues (as well as introduces migration code for the CWD, because the files that have to be updated for this fix include those in `$CWD/analyzer/windows/`).
Assuming you haven't made any out of the ordinary changes in your CWD you'll be able to install the latest version of Cuckoo and Cuckoo will automatically upgrade your CWD to the latest version the next time you run it. If an automatic upgrade isn't possible, Cuckoo will inform you on steps forward.
You may upgrade with `pip install cuckoo==2.0.3a2` for now, until we release a stable release.
Please let me know if these instructions are enough to upgrade your version of Cuckoo & if they resolve your Windows XP analyses.
Thanks again! If you have any additional questions, do not hesitate to let us know :-)

**Comment by plaxer** [comment]
@jbremer Thanks so much for fixing this mate. Will have a check later and provide an update. Do have a nice weekend.

**Comment by ikiril01** [comment]
@jbremer I just tested `2.0.3a2` and can confirm that my WinXP setup works fine now. Thanks for the quick fix! Cheers :)

**Comment by jbremer** [comment]
Didn't get any complaints here since the update, so going to close the issue as fixed :-) Thanks!

**Comment by Ma780aPar** [comment]
Hi everyone 

I just installed cuckoo latest version 
and 

I am getting all the time after analyses finished next error message in web console 

Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.

![image](https://user-images.githubusercontent.com/26720030/30493610-701e8034-9a4d-11e7-9b3e-8b79de2dc19f.png)

Should I worry about that and how to fix that error 

Thank you! 

Cuckoo is awesome

**Comment by doomedraven** [comment]
@jbremer ROFL

**Comment by doomedraven** [comment]
@Ma780aPar that isn't an error, jsut "warning" what timeout for analysis done, nothing else
