### ISSUE TITLE
No MISP expression code in Django

### ISSUE THREAD

**Issue by hakawati** [cuckoosandbox/cuckoo#1485]
Hi,

It works fine by enabling misp in `reporting.conf` and `processing.conf`. 
- reporting.conf
> [misp]
> enabled = yes
> url = http://192.168.0.250
> apikey = JR520ltb3SxStCbuluMFHRGP4WcUz4FW8sNd5rUo
> mode = maldoc ipaddr hashes url

- processing.conf
> [misp]
> enabled = yes
> url = http://192.168.0.250
> apikey = JR520ltb3SxStCbuluMFHRGP4WcUz4FW8sNd5rUo

[nav-sidebar.html](https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/web/templates/analysis/pages/nav-sidebar.html) contains MISP-related content. 

> 	{% if report.analysis.misp %}
> 			\<li>
> 				\<a href="{% url "analysis" report.analysis.info.id "misp" %}"
> 				{% if env.view_kwargs.page == 'misp' %} class="active" {% endif %}>
> 					\<i class="fa fa-flag"></i> 
> 					\<span>MISP</span>
> 					\<em>{{ report.analysis.misp|length }}</em>
> 				\</a>
> 			\</li>            
>         {% endif %}

However, the sidebar of the Django web interface has nothing to do with MISP. Thanks for reading this issue.

**Comment by Roslekas** [comment]
Hi, i noticed the same, MISP sidebar does not appear in Django web interface, with Debugging mode shows that Executed proccesing module "MISP" and Executed reporting module "MISP"...

![image](https://cloud.githubusercontent.com/assets/16913780/25429583/303afbcc-2a82-11e7-827a-a109e98dca21.png)

![image](https://cloud.githubusercontent.com/assets/16913780/25429572/24e9395a-2a82-11e7-8b51-7e928302b42e.png)

Thanks

**Comment by SparkyNZL** [comment]
same as #1460 ?

**Comment by SparkyNZL** [comment]
Look like the MISP processing is broken in 2.0.3a2. Im going to open a new TIcket for this,

**Comment by jbremer** [comment]
Thanks, bit late to the party but this should now be resolved due to #1784 #1789. Closing issue!
