### ISSUE TITLE
"Recent analyses" Links Aren't Links

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1488]
Elements of the "Recent analyses" section of the Cuckoo home page seem to be clickable links but their style fails to indicate such. Text is not colored or underlined on hover like other page links, nor does the cursor swap on hover.

Similarly, the "Show" in the header caused a cursor swap as if it were a link, but it's not, but the actually clickable portion of that UI element does not.

**Comment by jbremer** [comment]
These are disabled in `2.0.2` and we'll be showing 'em again after we do some brainstorming to think about what should be shown there in the first place. Thanks for the feedback, but closing issue :)
