### ISSUE TITLE
Linefeed tacked on to IP:Port (or Django Upstart Problems)

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1489]
Starting cuckoo-web in a virtualenv on boot via Upstart becomes a bit complicated due to permissions. I was able to work it out with the Upstart script shown below (note the virtualenv names differs from cuckoo's documented one)...

```
description "Cuckoo Web Service"
stop on runlevel [!2345] or stopping mysql or stopping mongod
start on started mysql and started mongod
script
	exec su cuckoo -c ". /home/cuckoo/cuckoo_ve/bin/activate && cuckoo -d web runserver 0.0.0.0:8000"
end script
```

...but, that for some odd reason seems to tack an excess line feed to the end of the port, resulting in complaints from Django about invalid ip:port combos (IP replaced)...
```
CommandError: "X.X.X.X:8000
" is not a valid port number or address:port pair.
```
Was able to resolve by tacking on an additional pointless echo command...
```
description "Cuckoo Web Service"
stop on runlevel [!2345] or stopping mysql or stopping mongod
start on started mysql and started mongod
script
	exec su pass -c ". /home/cuckoo/cuckoo_ve/bin/activate && cuckoo -d web runserver 0.0.0.0:8000 && echo 'Exit Cuckoo-web'"
end script
```
...though that should probably not be necessary.

**Comment by doomedraven** [comment]
incorrect syntax, see `cuckoo web --help`

**Comment by jbremer** [comment]
Ehm, that command line on itself should work actually. Not sure why all this complexity is required when you can also deploy with `uWSGI`+`nginx`, though.

**Comment by Kolano** [comment]
It seems the linefeed is tacked on regardless of the parameters used, so we get the similar error even without specifying IP/Port...
```
Usage: cuckoo [OPTIONS] COMMAND [ARGS]...

Error: No such command "web
".
```
...where an apparently undesired linefeed is post-fixed to "web".

I had been trying to avoid the need to setup uWSGI+nginx, or more specifically hoping to work out how to integrate into a webserver that wasn't nginx since I have too many web servers running on my system as is. This method had been quite simple /w the 2.0-rc2 release, it's been frustrating to account for the 2.0 release which seems to have changed more extensively than expected between an RC and final release version.

Guessing little will be done here since it's outside documented suggestions on the handling of things, but wanted to provide something for others that might run into this.

**Comment by jbremer** [comment]
Oh, lol, but that's not a Cuckoo issue, although it isn't clear to me why Upstart would add the newline for you :-)
Sure, I understand that, my point was more that `cuckoo web` uses the Django's HTTP thing which is a development environment rather than a production one. So if you intend to deploy it, better do it the proper way.
Yes, `2.0.0` is completely different from `2.0-rc1` and `2.0-rc2`, so the wording of our *legacy* releases (i.e., `2.0-rc2` and older) isn't very good, but I do hope that all the awesomeness that we brought you in the `2.0.0` release is worth it ;-)

**Comment by Kolano** [comment]
That's fine, 

I think the Cuckoo issue here is that folks want clarity on a web environment setup that integrates in with the other services better, as also came up in #1483.

**Comment by jbremer** [comment]
I'm all up for improving our usage etc, but `cuckoo web` is exactly the same as it used to be in, e.g., `2.0-rc2`. The only difference is that you now call `cuckoo web` or `cuckoo web runserver` instead of `cd web && ./manage.py runserver`.

**Comment by jbremer** [comment]
Closing issue as resolved. If you have additional questions and/or feedback, do let us know!
