### ISSUE TITLE
nginx + uwsgi 502 bad Gateway

### ISSUE THREAD

**Issue by Roucuck** [cuckoosandbox/cuckoo#1490]
i  am trying to deploy  my web server with nginx+ uwsgi  i  follow the steps on the documentation http://docs.cuckoosandbox.org/en/latest/usage/web/  but when i  try to run it with  nginx i have 502 BAD GATEWAY
 please can you help me ?

**Comment by RANGERBEE** [comment]
https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27

Scroll down to "Configure web services" and REVIEW  through nginx setup ....    This may help in your instantiation. (There may be slight differences needed)


I have yet to get my reverse proxy ssl session working correctly. This is merely due to a configuration deficiency that I have not had time to track down.


Hope it helps.

**Comment by Roucuck** [comment]
thank you but it  doesn't work  403 forbidden  :/

**Comment by Roucuck** [comment]
thanks a lot it works  you save my life :D

**Comment by jbremer** [comment]
@Roucuck What's the exact change that you performed (as opposed to what's in your documentation)?

**Comment by Roucuck** [comment]
hello 
when i follow the steps on the documentation it dosen't work  :/ 
so  i just  follow the steps on the link that RANGERBEE  posted and it works

**Comment by RANGERBEE** [comment]
Follow up ::

After following the Infospeak instructions here: [ https://infosecspeakeasy.org/t/howto-build-a-cuckoo-sandbox/27](url)
Scroll down to "Configure web services" and REVIEW through nginx setup .... This may help in your instantiation. I have made slight changes to work with what is mostly the default cuckoo configuration.
The working configuration I have as a reverse HTTPS proxy is as follows:


> server {
    listen MyIPaddress:443 ssl;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
    # Uncomment this next line if you are using a signed, trusted cert
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; p                                                reload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    #index index.html index.htm;
    client_max_body_size 101M;
    auth_basic "Login required";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        proxy_pass http://MyIPAddress:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

   # location /storage/analysis {
    #   alias /opt/cuckoo/storage/analyses/;
     #  autoindex on;
      # autoindex_exact_size off;
       #autoindex_localtime on;
   # }

    #location /static {
     # alias /opt/cuckoo/web/static/;
   # }
}

server {
    listen MyIp Address:8000;
    return 301 https://$server_name$request_uri;
}


#server {
#  listen 192.168.56.1:8000;

#    root /home/cuckoo/vmshared;

#     location / {
#           try_files $uri $uri/ =404;
#           autoindex on;
#           autoindex_exact_size off;
#           autoindex_localtime on;
#     }
#}

# Host the upstream legacy API
server {
    listen MyIPAddress:4343 ssl;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
   # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; p                                                reload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;


    location / {
        proxy_pass http://MyIPAddress:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Restrict access
       allow MyNET/8;
      # allow 192.168.1.0/24;
      deny all;
    }
}

**Comment by RANGERBEE** [comment]
New problem:
When submitting a sample from HTTP web UI, the POST request performs a pre-submit using HTTP/1.1 and executes without error.
When submitting a sample from HTTPS web UI, the POST request performs a pre-submit with HTTP/1.0 and simply hangs.  I am using the nginx config attached above in thread. 

![image](https://cloud.githubusercontent.com/assets/15255470/25672698/4a97ed70-3024-11e7-93c7-24a42a94f6b8.png)


Thanks for the help!!

**Comment by doomedraven** [comment]
lol i just had this issue and was surprised wtf, and everything is bcz i forgot about `sudo adduser www-data cuckoo` after that no more 502

**Comment by jbremer** [comment]
Closing issue as resolved. Smells like permission denied, indeed. Please reopen if that's not the case or you have additional information. Thanks!
