### ISSUE TITLE
Per-Analysis Inetsim usage

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1491]
Receiving following error:    need help tracking it down.

> 2017-04-26 19:42:35,984 [cuckoo.apps.rooter] ERROR: Error executing command: remote_dns_forward() takes exactly 4 arguments (3 g                 iven)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/rooter.py", line 388, in cuckoo_rooter
    output = handlers[command](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/rooter.py", line 202, in inetsim_enable
    remote_dns_forward(ipaddr, inetsim_ip, "-A")
TypeError: remote_dns_forward() takes exactly 4 arguments (3 given)
2017-04-26 19:42:35,990 [cuckoo.core.rooter] WARNING: Rooter returned error: remote_dns_forward() takes exactly 4 arguments (3 given)

The routing.conf has tor, inetsim enabled properly.
iptables set for global routing per docs as well.   https://cuckoo.sh/docs/installation/host/routing.html#routing-inetsim

If iptables are set in global routing should I not select INetSim in per-analysis?

Thanks!

**Comment by doomedraven** [comment]
see prs

**Comment by doomedraven** [comment]
you should apply this fixes https://github.com/cuckoosandbox/cuckoo/pull/1435

**Comment by RANGERBEE** [comment]
@doomedraven  Should I update the entire rooter.py?  Where is it hiding? I cant find it in the $CWD folder..

Thx!

**Comment by doomedraven** [comment]
it is not in CWD, `locate rooter.py` will return you result, it mor easier replace whole then do c&p of each block

**Comment by RANGERBEE** [comment]
yep. found it... /usr/local/lib/python2.7/dist-packages/cuckoo/apps/rooter.py


Thanks!

**Comment by doomedraven** [comment]
you are welcome, @jbremer time to update it? :P

**Comment by jbremer** [comment]
@doomedraven certainly time for that.. sorry for delay ;)

**Comment by jbremer** [comment]
The InetSim PR has been merged, please test it and provide us with feedback. Please leave your comments in #1435. If something else has been discussed in this thread that I missed, but that's important in one way or another, please reopen the issue with an additional comment or copy the comment / issue / whatever to #1435.
I'll be closing this issue now. In #1435 I'll be announcing when a new alpha or stable release is out in which you may find the InetSim working once again. Thanks again for the feedback & sorry once more for the delay on our side.
Ping @RANGERBEE.
