### ISSUE TITLE
False positive "Connects to an IRC server, possibly part of a botnet"

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1492]
Cuckoo 2.0.2,vm win7 sp1,virtualbox
In all report i find a False positive Connect to an IRC server.
Function get_net_generic("irc") return always a value 
In json report i find:

            "markcount": 0,
            "families": [],
            "description": "Connects to an IRC server, possibly part of a botnet",
            "severity": 3,
            "marks": [],
            "references": [],
            "name": "network_irc"

        "irc": [
            {
                "command": "NAMES",
                "params": "= ()",
                "type": "client"
            }

But in pcap, i can't find any connection to an irc server
[dump_sorted.zip](https://github.com/cuckoosandbox/cuckoo/files/960981/dump_sorted.zip)

**Comment by SparkyNZL** [comment]
Funny you mention this, i had the same issue yesterday for a sample. and I too couldnt see where it was detecting any IRC traffic. im going to look into this further over the weekend.

**Comment by jbremer** [comment]
I'll check it out, thanks!

**Comment by jbremer** [comment]
Looks like the IRC module is doing sub-optimal checks which trigger detection on one of the Cuckoo files being sent over to the guest which isn't filtered out properly in your setup.
Implementing a more stateful IRC parser would be useful (and mitigate this issue), but isn't something we'll spend time on in a reasonably short timeframe as it requires quite some R&D efforts from our side. For now I guess the best would be if you could ignore this error :-)

**Comment by sebdg** [comment]
@Maurotb this is also due to you nictrace option as in #1493

**Comment by jbremer** [comment]
Closing as sort of resolved. At some point we should revisit the IRC parser though.
