### ISSUE TITLE
False positive "Perform some http request"

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1493]
Cuckoo 2.0.2,vm win7 sp1,virtualbox
In all report i find False positive "Perform some http request"
cuckoo trigger a rule  for  reporting request from vm whithout whitelist it

request	GET http://192.168.56.101:8000/
request	GET http://192.168.56.101:8000/pinning
request	GET http://192.168.56.101:8000/environ
request	POST http://192.168.56.101:8000/mkdtemp
request	POST http://192.168.56.101:8000/extract
request	POST http://192.168.56.101:8000/store
request	POST http://192.168.56.101:8000/execpy
request	GET http://192.168.56.101:8000/status

**Comment by jbremer** [comment]
Interesting, that should certainly be left out of the results (and normally is). Can you share the PCAP and any configuration settings that you've changed?

**Comment by Maurotb** [comment]
Ok, i attach pcap and config file. All changes in config are prefixed by #Mao

This is the report result

request	GET http://192.168.56.104:8000/
request	GET http://192.168.56.104:8000/pinning
request	GET http://192.168.56.104:8000/environ
request	POST http://192.168.56.104:8000/mkdtemp
request	POST http://192.168.56.104:8000/extract
request	POST http://192.168.56.104:8000/store
request	POST http://192.168.56.104:8000/execpy
request	GET http://192.168.56.104:8000/status
request	GET https://clients2.google.com/service/check2?appid=%7B430FD4D0-B729-4F61-AA34-91526481799D%7D&appversion=1.3.33.3&applang=&machine=1&version=1.3.33.3&userid=&osversion=6.1&servicepack=Service%20Pack%201



[data.zip](https://github.com/cuckoosandbox/cuckoo/files/961670/data.zip)

**Comment by sebdg** [comment]
Hi @Maurotb, 
I know it comes late on this topic but you shouldn't use the nictrace option, that one is capturing all nic traffic.

**Comment by jbremer** [comment]
Ah, what @sebdg said makes sense. Closing as resolved.
