### ISSUE TITLE
Failed to execute tcpdump

### ISSUE THREAD

**Issue by dforce** [cuckoosandbox/cuckoo#1497]
I followed the install described in the manual.
Everything went fine.
Starting "cuckoo web" I receive this error :
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH

Tcpdump was already installed.
Performing getcap gives this :
/usr/sbin/tcpdump = cap_net_admin,cap_net_raw+eip

Tcpdump was working with the previous versions of cuckoo but the I was running cuckoo outside the virtualenv.

How can I solve this problem ?

**Comment by doomedraven** [comment]
what about apparmor?, check documentation

**Comment by dforce** [comment]
In the documentation is mentioned that we don't need apparmor when using debian.

**Comment by dforce** [comment]
After installing apparmor and performing aa-disable I received following message :
Profile for /usr/sbin/tcpdump not found

But /usr/sbin/tcpdump exists.

What now ?

**Comment by doomedraven** [comment]
that is correct, no apparmor rule for tcpdump

**Comment by doomedraven** [comment]
no idea, check your $PATH what is wrong

**Comment by dforce** [comment]
Problem solved, problem with $PATH.

**Comment by jbremer** [comment]
Always nice to see the issue was outlined by the error warning :-)
I'm curious though, how is `/usr/sbin` not in your `$PATH`?

**Comment by enzok** [comment]
is this an issue with virtualenv?

**Comment by jbremer** [comment]
@enzok It is not - for some more information see the commit above.

**Comment by Arul-Raaj** [comment]
Hey! I am using Termux the same problem occurs how to solve it? (Unable to locate path)🙄
