### ISSUE TITLE
Firefox Submit Supported Files List Misalignment

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1498]
The text/icons of the "Supported file types" list on the submit page are misaligned in Firefox 53.0 (32-bit).

![firefox supported file types](https://cloud.githubusercontent.com/assets/6509657/25497629/3e7d6a7c-2b53-11e7-996e-0dfa3e6301a4.png)

**Comment by jbremer** [comment]
Thanks! I'm having it fixed soon'ish.

**Comment by jbremer** [comment]
Resolved in `2.0.3a3` (`pip install cuckoo==2.0.3a3`)! Closing issue & thanks again for feedback :-)

**Comment by Kolano** [comment]
Confirmed thanks.
