### ISSUE TITLE
Rooter.py not executing [Ubuntu]

### ISSUE THREAD

**Issue by kpachay** [cuckoosandbox/cuckoo#1499]
I've been able to successfully deploy cuckoo in a isolated enviroment (no internet access), and I am able to successfully run analysis. I am running the host on the latest version of Ubuntu (17.04) and the guest is running on Windows 10. However, when trying to give the guest internet access, I run into issues starting rooter.py. In cuckoo.conf:

```
route = internet
internet = eth0 (this is correct)
```

I have created and set rooter.py to use the proper group (named "cuckoo"), however when I try to execute rooter.py using `$ sudo python cuckoo rooter.py`, the process just hangs indefinitely until I interrupt it. 

Am I missing a step here? Please let me know if you need any additional information.

**Comment by doomedraven** [comment]
Is not .py, execute cuckoo -d rooter and provide output

But without -d it there is not output

**Comment by RANGERBEE** [comment]
hint, hint...  Create a startup script....
Heres a little bit that may help get you started...

> !#/bin/bash

# Start rooter
sudo cuckoo --cwd /path/to/your/cuckoosandbox/.cuckoo rooter -g cuckoo &

# Start Cuckoo
sudo cuckoo --cwd /path/to/your/cuckoosandbox/.cuckoo &

yada yada...

**Comment by jbremer** [comment]
@kpachay the `cuckoo rooter` will stay in the background to do its thing. You can think of it as a daemon process. So what you described is correct. Also both suggestions above are useful, btw.

**Comment by jbremer** [comment]
Closing issue as it seems to be resolved. Feel free to reopen or create a new one if you have other feedback and/or questions!
