### ISSUE TITLE
virustotal processing not visible?

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1501]
VT processing enabled timeout 60, scan = no, using default key.

Scan and processing completes without errors.

No VT info shows on dashboard. Where should the VT info be visible?
Where can I view the log that shows the outbound call to VT?

Thanks!

Cuckoo2.0.2, Volatility2.6, Yara3.4

**Comment by doomedraven** [comment]
in static section see result of vt
vt request in processing module output(maybe debug mode required not sure)

**Comment by RANGERBEE** [comment]
got it, was my fault....    works fine!
