### ISSUE TITLE
Failed to run the processing module "Memory" for task...

### ISSUE THREAD

**Issue by Roslekas** [cuckoosandbox/cuckoo#1502]
Hi,

Volatility 2.5, yara 3.5.0, cuckoo 2.0.2

Error in malfind, running analysis with vm Windows8, with Windows7 analysis works well without errors

![image](https://cloud.githubusercontent.com/assets/16913780/25529692/d6dd3cd8-2c2b-11e7-812d-84a4ee40bd7d.png)

Any advice ?
Thanks

**Comment by jbremer** [comment]
This seems like a Volatility issue. Can you try installing Volatility 2.6 and re-processing the analysis (and thus memory dump)?

**Comment by Roslekas** [comment]
Hi,

fixed with 2.6 volatility, but got a lot WARNINGS in svcscan

![image](https://cloud.githubusercontent.com/assets/16913780/25606679/5ea09524-2f1b-11e7-8c18-035481b7f962.png)

**Comment by jbremer** [comment]
This was resolved by 51a5bb1995915336c26127f907d69befa812c6a5, you're sure you're running `2.0.2`? ;-)

**Comment by Roslekas** [comment]
Strange, using 2.0.2 version, but memory.py was different than "51a5bb1", so i made changes manually...
![image](https://cloud.githubusercontent.com/assets/16913780/25611736/de02d9f2-2f30-11e7-89a0-068457c940e6.png)

Still i noticed that, Score is much bigger with Win7 than the Win8 :/
![image](https://cloud.githubusercontent.com/assets/16913780/25611928/7cda43f8-2f31-11e7-909c-0af82c57797e.png)

Win7 matched signatures
![image](https://cloud.githubusercontent.com/assets/16913780/25611979/af24d774-2f31-11e7-9554-3ce76b914bbd.png)

Win8 matched signatures
![image](https://cloud.githubusercontent.com/assets/16913780/25611994/b9d52f8e-2f31-11e7-9bc8-c9a33ff52c55.png)

Have any thoughts? thanks

**Comment by jbremer** [comment]
Thanks. We don't officially support Windows 8.1, but I'm happy to see you got it working anyhow. This may also be the reason for less signatures matching properly.

**Comment by Roslekas** [comment]
Thanks

**Comment by jbremer** [comment]
I think we can close this issue, please let us know if you have additional feedback.
