### ISSUE TITLE
Multiple instance - unstable processing?

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1503]
Specs for environment:
Cuckoo 2.0.2, Volatility 2.6, yara 3.4, Python 2.7.6, Ubuntu Trusty
cuckoo.conf set process_results = no
starting two instances for processing at startup.
auxilary.conf  virustotal enabled
All Win7SP1x86 guests with osprofile set correctly in machine.conf

Problem:
Running same file on four different simultaneous sample submissions I see an instability in:
1.) Processing does not always complete. One or two submission threads may complete with same info, but not all the same. (Pics to follow)
2.) Analysis usually always completes task without error. When processing the failures begin in an inconsistent manner, especially at time of report generation.

This is the ony error I see on the output reports with broken data. ( Not sure if it breaks the rest of the processing and report generation process down stream)
> 2017-04-28 14:12:57,211 [cuckoo.processing.virustotal] WARNING: Path "a3842eda367c4db38b97242401f1e784313d3540ba33ce042dd59a2f0eb60e31" could not be found for VirusTotal lookup, skipping it
2017-04-28 14:12:57,571 [cuckoo.core.plugins] ERROR: Failed to run 'on_complete' of the packer_polymorphic signature
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 394, in call_signature
    if not signature.matched and handler(*args, **kwargs):
  File "/media/cuckoo/Storage/.cuckoo/signatures/windows/packer_polymorphic.py", line 41, in on_complete
    target_ssdeep = self.get_results("target", {})["file"]["ssdeep"]
KeyError: 'ssdeep'

![image](https://cloud.githubusercontent.com/assets/15255470/25532956/8bf7c70e-2c1e-11e7-8f98-51ad59db6fcb.png)
brackets = Best results -  (5) ran stand alone, (7) run in parallel with three other submissions.

![image](https://cloud.githubusercontent.com/assets/15255470/25533325/d5a2600c-2c1f-11e7-87c6-bb2114a0315f.png)
Submission 7 = output results visible from report generation.

![image](https://cloud.githubusercontent.com/assets/15255470/25533443/28fa5692-2c20-11e7-8fb7-f7268f113236.png)
Submission 8 = no output here, due to broken report generation. Screenshots are sometimes visible. (running parallel to Submission 7)

![image](https://cloud.githubusercontent.com/assets/15255470/25533758/2c636c28-2c21-11e7-9b73-59cbbcc45b55.png)
Submission 5 = running stand alone.

Hope this helps...

**Comment by jbremer** [comment]
Can you show the commands you run to start the processing utilities?
In the commit above you can see the fixed Signature that was throwing the exception in the traceback you pasted above. Re-running the `cuckoo community` command will get you the fix.

**Comment by RANGERBEE** [comment]
This is pretty much how I start everything...

> 
# Restart services that bind to the bridge
/usr/sbin/service nginx restart
/usr/sbin/service tor restart
/usr/sbin/service inetsim restart
/usr/sbin/service vsftpd restart

# Clean it up first
fuser -k 2042/tcp
fuser -k 8090/tcp
fuser -k 8080/tcp

# Start rooter
sudo cuckoo --cwd /media/cuckoo/Storage/.cuckoo rooter -g cuckoo &

# Start Cuckoo
sudo cuckoo --cwd /media/cuckoo/Storage/.cuckoo &
sudo cuckoo --cwd /media/cuckoo/Storage/.cuckoo process instance1 &
sudo cuckoo --cwd /media/cuckoo/Storage/.cuckoo process instance2 &


# Start the Cuckoo web UI
sudo cuckoo --cwd /media/cuckoo/Storage/.cuckoo web runserver 10.0.1.40:8080 &

# Start the legacy upstream API
sudo cuckoo --cwd /media/cuckoo/Storage/.cuckoo api --host 10.0.1.40 --port 8090 &

**Comment by jbremer** [comment]
Sorry for typo in commit btw :(

**Comment by RANGERBEE** [comment]
all good..  Thanks!

**Comment by jbremer** [comment]
Are the issue(s) from this thread still relevant @RANGERBEE?

**Comment by RANGERBEE** [comment]
Seems to be stable now.  If it pops up again I'll create new thread.

**Comment by jbremer** [comment]
Cool, closing issue then.
