### ISSUE TITLE
Resultserver problem

### ISSUE THREAD

**Issue by dforce** [cuckoosandbox/cuckoo#1504]
Hi all,

I am not using the default IP, set in cuckoo, for the resultserver. I changed everything within the conf files (cuckoo.conf and virtualbox.conf), setting the resultserver to the IP address I am using.
In previous versions everything was running fine.

When starting cuckoo now it is still referring to the default IP for the resultserver, stating it can't find that address, which is normal because I am not using that address.

Are there other places where I have to change that IP address ?

Thanks

**Comment by jbremer** [comment]
Can you please provide logs & the related configuration files? :)

**Comment by dforce** [comment]
I only have conf files, no logs 

https://mega.nz/#!YlkCAJQa!2P1HIjDf1aeFN6R4rxSL3FmMvzL_kJs_db9JvwAMLIY
https://mega.nz/#!EwcBXbBL!vtF9sQX9DHZCHsFxZVDuNZoKnlEWn11D39v2DKJq6LQ

**Comment by dforce** [comment]
This is the error message
CuckooCriticalError: Unable to bind ResultServer on 192.168.56.1:2042 [Errno 99] Cannot assign requested address. This usually happens when you start Cuckoo without bringing up the virtual interface associated with the ResultServer IP address.

The virtual interface is up.

**Comment by jbremer** [comment]
I changed `resultserver`'s `ip` to `0.0.0.0` locally and get the following line in the logs: `2017-04-28 19:52:31,505 [cuckoo.core.resultserver] DEBUG: ResultServer running on 0.0.0.0:2042.`. So seems to work fine for me. Are you sure you use the correct CWD etc?

**Comment by jbremer** [comment]
Any update here @dforce?

**Comment by jbremer** [comment]
Next time I'll close this issue if no additional feedback is provided :-)

**Comment by msreddy470** [comment]
Hai, I am also facing same problem, with my result server... please check this [result servers](http://in.resultservers.com/2017/02/anna-university-results-2017.html)

**Comment by jbremer** [comment]
As per the comment above.

**Comment by Kashyapkrs** [comment]
I am also facing a similar issue
please help

**Comment by doomedraven** [comment]
please read the msgs in the thread, without logs without nothing impossible to help, do you want us to hack you and fix it? :D  i'm kidding ;)
