### ISSUE TITLE
cuckoo runtime error

### ISSUE THREAD

**Issue by ShadmanReju** [cuckoosandbox/cuckoo#1506]
I m new in installing cuckoo.. tell me whats the solution.when i run cuckoo then this error occurs :+1: CuckooCriticalError: Unable to import plugin "modules.machinery.virtualboxUnable to shut 'Win8.1' down or find the machine in its proper state:": No module named virtualboxUnable to shut 'Win8.1' down or find the machine in its proper state:

**Comment by jbremer** [comment]
Please upgrade to the latest version (https://cuckoosandbox.org/2017-04-07-cuckoo-sandbox-200.html) and try again.

**Comment by jbremer** [comment]
Closing for lack of additional comments or information. The new version should make your problems easier to debug, though.
