### ISSUE TITLE
Unable to start Cuckoo when mongodb set enabled = yes in reporting.conf

### ISSUE THREAD

**Issue by bcallaughan** [cuckoosandbox/cuckoo#1507]
When I set mongodb enabled = yes in reporting.conf i get the follow error when attempting to start cuckoo:

 Checking for updates...
 You're good to go!
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.2
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0 appdirs:1.4.3 asn1crypto:0.22.0 beautifulsoup4:4.5.3 cffi:1.10.0 chardet:2.3.0 cheetah:2.4.4 click:6.6 colorama:0.3.7 cryptography:1.8.1 cuckoo:2.0.2 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.10.1 functools32:3.2.3.post2 httpreplay:0.2 idna:2.5 ipaddress:1.0.18 itsdangerous:0.24 jinja2:2.8 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:1.3.1 m2crypto:0.24.0 mako:1.0.6 markupsafe:1.0 olefile:0.43 oletools:0.42 packaging:16.8 peepdf:0.3.4 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 pycparser:2.17 pycrypto:2.6.1 pydeep:0.4 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.0.0 pyparsing:2.2.0 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 scapy:2.3.2 setuptools:35.0.2 sflock:0.2.7 six:1.10.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unity-lens-photos:1.0 urllib3:1.21 vboxapi:1.0 virtualenv:15.0.1 volatility:2.6 wakeonlan:0.2.2 werkzeug:0.12.1 wheel:0.29.0

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 186, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 123, in cuckoo_init
    init_modules()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 192, in init_modules
    module.init_once()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 34, in init_once
    if "cuckoo_schema" in mongo.db.collection_names():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:8000: [Errno 111] Connection refused

**Comment by jbremer** [comment]
Thanks for the error report, @bcallaughan. It would appear you don't have a running MongoDB server - which is required when enabling it in the configuration ;-)
In the commit above I've improved our error reporting for this issue so it will be more clear for future users where the problem lies.

**Comment by bcallaughan** [comment]
Thanks Jurriaan, 

 I did during the installation instructions with sudo apt-get install mongodb

 Will these instructions get me to where i need to be: https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04

**Comment by jbremer** [comment]
DO articles are usually correct, so yeah probably ;-)
Or just run `/etc/init.d/mongodb start`.

**Comment by bcallaughan** [comment]
thanks mate

**Comment by bcallaughan** [comment]
both methods yield the same results:
brett@Sandbox:~$ /etc/init.d/mongodb start
[ ok ] Starting mongodb (via systemctl): mongodb.service.

Then attempt to start cuckoo:

Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.2
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0 appdirs:1.4.3 asn1crypto:0.22.0 beautifulsoup4:4.5.3 cffi:1.10.0 chardet:2.3.0 cheetah:2.4.4 click:6.6 colorama:0.3.7 cryptography:1.8.1 cuckoo:2.0.2 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.10.1 functools32:3.2.3.post2 httpreplay:0.2 idna:2.5 ipaddress:1.0.18 itsdangerous:0.24 jinja2:2.8 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:1.3.1 m2crypto:0.24.0 mako:1.0.6 markupsafe:1.0 olefile:0.43 oletools:0.42 packaging:16.8 peepdf:0.3.4 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 pycparser:2.17 pycrypto:2.6.1 pydeep:0.4 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.0.0 pyparsing:2.2.0 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 scapy:2.3.2 setuptools:35.0.2 sflock:0.2.7 six:1.10.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unity-lens-photos:1.0 urllib3:1.21 vboxapi:1.0 virtualenv:15.0.1 volatility:2.6 wakeonlan:0.2.2 werkzeug:0.12.1 wheel:0.29.0

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 186, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 123, in cuckoo_init
    init_modules()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 192, in init_modules
    module.init_once()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 34, in init_once
    if "cuckoo_schema" in mongo.db.collection_names():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:8000: timed out

**Comment by jbremer** [comment]
Oh, did you configure MongoDB to go to port `8000`? The default port is `27017` ;-)

**Comment by bcallaughan** [comment]
Changed mongodb port in reporting.conf and that resolved it, now i just need to fix one more error:

Checking for updates...
 You're good to go!
2017-04-29 21:20:49,295 [cuckoo.core.startup] WARNING: Unable to import yara (please compile from sources)
2017-04-29 21:20:49,296 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-29 21:20:50,153 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-29 21:20:50,174 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks

I defiantly used source files as per: http://yara.readthedocs.io/en/v3.5.0/gettingstarted.html

**Comment by jbremer** [comment]
Let me update that comment, it should say run `pip install yara-python==3.5.0` for now. We're still awaiting a new release from the Yara guys, though. A future version should be automatically installed with Cuckoo :-)

**Comment by bcallaughan** [comment]
Genius! Everything is smooth as silk now! Thank You!

**Comment by jbremer** [comment]
Changes here have been included in our `2.0.3a3` release (`pip install cuckoo==2.0.3a3`), closing issue as resolved.

**Comment by Sanch091** [comment]
Hi there,
I got quiet the same problem. I started mongodb with he command above and its running:
[ ok ] Starting mongodb (via systemctl): mongodb.service.

When I try to start the web-service at the guest this error appears:
(Win7) cuckoo@Det-Chamb1:~$ cuckoo web
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

Can some1 help maybe?

Also I am affraid, I dont know how to use it right :(

Thanks
Sanch0

**Comment by renjithrjames** [comment]
I am getting following error even i run with the default port.

# cuckoo web -H 127.0.0.1 -p 27017
Performing system checks...

System check identified no issues (0 silenced).
September 18, 2019 - 10:50:21
Django version 1.8.4, using settings 'cuckoo.web.web.settings'
Starting development server at http://127.0.0.1:27017/
Quit the server with CONTROL-C.
Error: That port is already in use.
