### ISSUE TITLE
SQLite Capabilities: At what point should I move to MySQL or PostgreSQL

### ISSUE THREAD

**Issue by bcallaughan** [cuckoosandbox/cuckoo#1508]
Hi All, 

 I know this isn't really an issue but while I am building the sandbox now I want to build for longevity at what point does SQLite reach its capacity after adding a second guest I see the following at cuckoo start:

WARNING: As you've configured Cuckoo to execute parallel analyses, we recommend you to switch to a MySQL or a PostgreSQL database as SQLite might cause some issues.

If I only plan to run a Maximum of 4 Guests will SQLite see me out or should I look at another DB?

**Comment by jbremer** [comment]
It should mostly be fine (I believe), just a matter of best practices ;-)
Been a while since I've used SQLite3 for more than 1 VM.

**Comment by bcallaughan** [comment]
ok ill see how it goes for a while i have noticed, even though I have configured to run 2 guests at the moment it doesn't run the analysis on both guests just the first one, I can select the second guest manually and it will process there however.

**Comment by Huthifh** [comment]
how to switch to a MySQL ?

**Comment by bcallaughan** [comment]
This got me where i needed to be http://blog.michaelhaag.org/2013/10/cuckoo-sandbox-and-mysql.html
I didn't bother with the XAMPP GUI for mySQL though just created the db and user from CLI very straight forward

**Comment by jbremer** [comment]
I think we're all set here - closing issue.
