### ISSUE TITLE
CuckooMx

### ISSUE THREAD

**Issue by Roucuck** [cuckoosandbox/cuckoo#1511]
hello 
I am trying to deploy cuckooMx with cuckoo i folllow https://github.com/xme/cuckoomx  but it dosen't work
please can you help meeee guyss

**Comment by doomedraven** [comment]
Check utils/cuckoomx.py is similar

**Comment by doomedraven** [comment]
Ah it still in prs

**Comment by Roucuck** [comment]
i don't have the file cuckoomx.py on the utils directory :/

**Comment by Roucuck** [comment]
How can i  generate it plz

**Comment by doomedraven** [comment]
Check in  pull requests ;)

**Comment by jbremer** [comment]
Yes, if you want the old `cuckoomx`, you'll have to take a look at @doomedraven's PR. In the meanwhile I've removed our older version of it as I believe this functionality should be implemented as part of a simple `postfix` configuration, but that effort has yet to come ;-)

**Comment by doomedraven** [comment]
Yup but first linux :D

**Comment by Roucuck** [comment]
hey guys i add cuckoomx.py and cuckooconf to my configuration but it doesen't work any help please :'(

**Comment by doomedraven** [comment]
Doesnt work doesnt say nothing, logs? Why not working? Details?

**Comment by Roucuck** [comment]
i try to run cuckoomx.py   i have [ Errno 111 ] connection refused what should i do exactly to run it  i don't receive notification   when i receive a mail thereis no logs on the syslog file abt the cuckoomx  i really need help can u please tell me how can i run it or can i attach cuckoomx to my mail and the cuckoosandbox

**Comment by doomedraven** [comment]
if do the request for help provide as must info as you can to save you and other time

about execution is just `python cuckoomx.py`

and that your error 111 means what you didn't configure something correctly, post config of mx

**Comment by jbremer** [comment]
@Roucuck this is not an official feature yet, as we're still awaiting to do some additional development on it before I consider "cuckoo mx" production quality.
Your two possibilities at the moment are
1) following @doomedraven instructions (which should be more than enough)
2) I can point you to the following page so we can really finish off this feature ;) https://cuckoosandbox.org/2015-05-15-consultancy-services.html

**Comment by doomedraven** [comment]
what @jbremer told, that requires some time to get it to "production quality" as my priority now is `linux cuckoo`. `make linux cuckoo great againt`, but `cuckoomx can be second` ___enought youtube for today___ :D
but step 2 will be faster solution for you if my suggestion doesn't work ;)

**Comment by Roucuck** [comment]
@jbremer  thanks for your help i really wish that u finish this feature cause cuckoomx is a great tool but  for the moment in my situation i really need it work   as soon as possible so please help me 

@doomedraven 
this is my cuckoomx.conf file: mail.cuckoo.com is my mail domain 
[cuckoomx]
server = mail.cuckoo.com
port = 587
user = 
password = 
db = sqlite:///cuckoomx.db
archive_password = infected
cuckoo_url = http://localhost:8000/analysis/

and this is my  cuckoomx.py :
#!usr/bin/python
import os
import re
import sys
import email
import imaplib
import hashlib
import tempfile
import smtplib
from time import sleep
import mimetypes
from email import Encoders
from email.mime.text import MIMEText
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase

try:
    from sflock.main import unpack
    from sflock.unpack import ZipFile
    from sflock.abstracts import File
except ImportError:
    print "Missed deps"\
    "sudo apt-get install p7zip-full rar unace-nonfree"\
    "sudo pip install -U sflock"

# Cuckoo root
CUCKOO_ROOT = os.path.join(os.path.abspath(os.path.dirname(__file__)), "..")
sys.path.append(CUCKOO_ROOT)
from lib.cuckoo.common.config import Config
email_config = Config("cuckoomx")

from lib.cuckoo.core.database import Database
from lib.cuckoo.common.utils import store_temp_file

from sqlalchemy.sql import func
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Boolean, DateTime


main_db = Database()
Base = declarative_base()
email_config = Config("cuckoomx")

class CUCKOOMX(Base):
    __tablename__ = 'cuckoomx'
    id = Column(Integer, primary_key=True)
    sha256 = Column(String(64), nullable=False)
    email = Column(String(250), nullable=False)
    cuckoo_id = Column(Integer, nullable=False)
    reported = Column(Boolean, default=False)
    uploaded_date = Column(DateTime, default=func.now())

engine = create_engine(email_config.cuckoomx.get("db", "sqlite://cuckoomx.db"))
Base.metadata.create_all(engine)

def send_notification(db, db_entry = False):
    tasks = list()
    if db_entry:
        tasks = [db_entry]
    else:
        tasks = cuckoomx_db.query(CUCKOOMX).filter_by(reported=False).order_by(CUCKOOMX.id.asc())
    if tasks:
        for task in tasks:
            task_info = main_db.view_task(task.cuckoo_id)
            if task_info.status == "reported":
                send_email(email_config.cuckoomx.get("cuckoo_url"), str(task.cuckoo_id), task.email)
                task.reported = True
    db.commit()
def send_email(url, id, to):
    try:
        msg = MIMEMultipart()
        msg['Subject'] = "[Cuckoo] Analysis finished for: {}".format(id)
        msg['From'] = email_config.cuckoomx.get("user")
        msg['To'] = to
        msg['Body'] = url+id
        part = MIMEBase('application', "octet-stream")
        msgAlternative = MIMEMultipart('alternative')
        msg.attach(msgAlternative)
        msgAlternative.attach(MIMEText(url+id, 'plain'))

        server = smtplib.SMTP_SSL(email_config.cuckoomx.get("server"), int(email_config.cuckoomx.get("port")))
        server.login(email_config.cuckoomx.get("user"), email_config.cuckoomx.get("password"))
        #server.set_debuglevel(1)
        server.sendmail(email_config.cuckoomx.get("from"), to.split(", "), msg.as_string())
        server.quit()
    except Exception as e:
        print e

def get_new_emails(db):
    imaplib.IMAP4.debug = imaplib.IMAP4_SSL.debug = 1

    conn = imaplib.IMAP4_SSL(email_config.cuckoomx.get("server"))
    conn.login(email_config.cuckoomx.get("user"), email_config.cuckoomx.get("password"))
    conn.select("Inbox")

    (retcode, messages) = conn.search(None, "(UNSEEN)")
    if retcode == "OK" and messages:
        for num in messages[0].split(" "):
            if num:
                typ, data = conn.fetch(num,"(RFC822)")
                msg = email.message_from_string(data[0][1])
                if msg:
                    email_dict = dict()
                    email_dict["Attachments"] = list()
                    for k, v in msg.items():
                       email_dict[k] = v

                    if email_dict.get("Subject", ""):
                        print "[+] Procesing email with Subject: {0}".format(email_dict["Subject"])
                    for part in msg.walk():
                        attachment = False
                        if part.get_filename():
                            filename = part.get_filename()
                            content_type = part.get_content_type()
                            attachment = part.get_payload(decode=True)


                            if attachment:
                                sha256 = hashlib.sha256(attachment).hexdigest()
                                #unpack it
                                z = ZipFile(File(contents=attachment, password=email_config.cuckoomx.get("archive_password")))
                                files = list(z.unpack(password=email_config.cuckoomx.get("archive_password"), duplicates=[]))
                                for file in files:
                                    new_file = db.query(CUCKOOMX).filter(CUCKOOMX.sha256 == file.sha256).first()
                                    if new_file is None:
                                        new_file = CUCKOOMX(sha256=file.sha256)

                                        temp_file_path = store_temp_file(file.contents, file.filename)
                                        task_id = main_db.add_path(
                                            file_path=temp_file_path
                                        )
                                        new_file.cuckoo_id = task_id
                                        new_file.email = email_dict.get("From", "")
                                        db.add(new_file)
                                        db.commit()
                                    else:
                                        send_notification(db, new_file)
                #mark as seen
                typ, data = conn.store(num,"+FLAGS","\Seen")

    conn.close()
    conn.logout()

if __name__ == "__main__":
    Base.metadata.bind = engine
    DBSession = sessionmaker(bind=engine)
    cuckoomx_db = DBSession()
    while True:
        pass
        try:
            send_notification(cuckoomx_db)
        except Exception as e:
             print e
        try:
             get_new_emails(cuckoomx_db)
        except Exception as e:
             print e
        sleep(30)
    cuckoomx_db.close()
wish u can help meee

**Comment by Roucuck** [comment]
cuckoomx.py`
#!usr/bin/python
import os
import re
import sys
import email
import imaplib
import hashlib
import tempfile
import smtplib
from time import sleep
import mimetypes
from email import Encoders
from email.mime.text import MIMEText
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase

try:
    from sflock.main import unpack
    from sflock.unpack import ZipFile
    from sflock.abstracts import File
except ImportError:
    print "Missed deps"\
    "sudo apt-get install p7zip-full rar unace-nonfree"\
    "sudo pip install -U sflock"

# Cuckoo root
CUCKOO_ROOT = os.path.join(os.path.abspath(os.path.dirname(__file__)), "..")
sys.path.append(CUCKOO_ROOT)
from lib.cuckoo.common.config import Config
email_config = Config("cuckoomx")

from lib.cuckoo.core.database import Database
from lib.cuckoo.common.utils import store_temp_file

from sqlalchemy.sql import func
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Boolean, DateTime


main_db = Database()
Base = declarative_base()
email_config = Config("cuckoomx")

class CUCKOOMX(Base):
    __tablename__ = 'cuckoomx'
    id = Column(Integer, primary_key=True)
    sha256 = Column(String(64), nullable=False)
    email = Column(String(250), nullable=False)
    cuckoo_id = Column(Integer, nullable=False)
    reported = Column(Boolean, default=False)
    uploaded_date = Column(DateTime, default=func.now())

engine = create_engine(email_config.cuckoomx.get("db", "sqlite://cuckoomx.db"))
Base.metadata.create_all(engine)

def send_notification(db, db_entry = False):
    tasks = list()
    if db_entry:
        tasks = [db_entry]
    else:
        tasks = cuckoomx_db.query(CUCKOOMX).filter_by(reported=False).order_by(CUCKOOMX.id.asc())
    if tasks:
        for task in tasks:
            task_info = main_db.view_task(task.cuckoo_id)
            if task_info.status == "reported":
                send_email(email_config.cuckoomx.get("cuckoo_url"), str(task.cuckoo_id), task.email)
                task.reported = True
    db.commit()
def send_email(url, id, to):
    try:
        msg = MIMEMultipart()
        msg['Subject'] = "[Cuckoo] Analysis finished for: {}".format(id)
        msg['From'] = email_config.cuckoomx.get("user")
        msg['To'] = to
        msg['Body'] = url+id
        part = MIMEBase('application', "octet-stream")
        msgAlternative = MIMEMultipart('alternative')
        msg.attach(msgAlternative)
        msgAlternative.attach(MIMEText(url+id, 'plain'))

        server = smtplib.SMTP_SSL(email_config.cuckoomx.get("server"), int(email_config.cuckoomx.get("port")))
        server.login(email_config.cuckoomx.get("user"), email_config.cuckoomx.get("password"))
        #server.set_debuglevel(1)
        server.sendmail(email_config.cuckoomx.get("from"), to.split(", "), msg.as_string())
        server.quit()
    except Exception as e:
        print e

def get_new_emails(db):
    imaplib.IMAP4.debug = imaplib.IMAP4_SSL.debug = 1

    conn = imaplib.IMAP4_SSL(email_config.cuckoomx.get("server"))
    conn.login(email_config.cuckoomx.get("user"), email_config.cuckoomx.get("password"))
    conn.select("Inbox")

    (retcode, messages) = conn.search(None, "(UNSEEN)")
    if retcode == "OK" and messages:
        for num in messages[0].split(" "):
            if num:
                typ, data = conn.fetch(num,"(RFC822)")
                msg = email.message_from_string(data[0][1])
                if msg:
                    email_dict = dict()
                    email_dict["Attachments"] = list()
                    for k, v in msg.items():
                       email_dict[k] = v

                    if email_dict.get("Subject", ""):
                        print "[+] Procesing email with Subject: {0}".format(email_dict["Subject"])
                    for part in msg.walk():
                        attachment = False
                        if part.get_filename():
                            filename = part.get_filename()
                            content_type = part.get_content_type()
                            attachment = part.get_payload(decode=True)


                            if attachment:
                                sha256 = hashlib.sha256(attachment).hexdigest()
                                #unpack it
                                z = ZipFile(File(contents=attachment, password=email_config.cuckoomx.get("archive_password")))
                                files = list(z.unpack(password=email_config.cuckoomx.get("archive_password"), duplicates=[]))
                                for file in files:
                                    new_file = db.query(CUCKOOMX).filter(CUCKOOMX.sha256 == file.sha256).first()
                                    if new_file is None:
                                        new_file = CUCKOOMX(sha256=file.sha256)

                                        temp_file_path = store_temp_file(file.contents, file.filename)
                                        task_id = main_db.add_path(
                                            file_path=temp_file_path
                                        )
                                        new_file.cuckoo_id = task_id
                                        new_file.email = email_dict.get("From", "")
                                        db.add(new_file)
                                        db.commit()
                                    else:
                                        send_notification(db, new_file)
                #mark as seen
                typ, data = conn.store(num,"+FLAGS","\Seen")

    conn.close()
    conn.logout()

if __name__ == "__main__":
    Base.metadata.bind = engine
    DBSession = sessionmaker(bind=engine)
    cuckoomx_db = DBSession()
    while True:
        pass
        try:
            send_notification(cuckoomx_db)
        except Exception as e:
             print e
        try:
             get_new_emails(cuckoomx_db)
        except Exception as e:
             print e
        sleep(30)
    cuckoomx_db.close()`

**Comment by Roucuck** [comment]
`#!usr/bin/python
import os
import re
import sys
import email
import imaplib
import hashlib
import tempfile
import smtplib
from time import sleep
import mimetypes
from email import Encoders
from email.mime.text import MIMEText
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase

try:
    from sflock.main import unpack
    from sflock.unpack import ZipFile
    from sflock.abstracts import File
except ImportError:
    print "Missed deps"\
    "sudo apt-get install p7zip-full rar unace-nonfree"\
    "sudo pip install -U sflock"

# Cuckoo root
CUCKOO_ROOT = os.path.join(os.path.abspath(os.path.dirname(__file__)), "..")
sys.path.append(CUCKOO_ROOT)
from lib.cuckoo.common.config import Config
email_config = Config("cuckoomx")

from lib.cuckoo.core.database import Database
from lib.cuckoo.common.utils import store_temp_file

from sqlalchemy.sql import func
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Boolean, DateTime


main_db = Database()
Base = declarative_base()
email_config = Config("cuckoomx")

class CUCKOOMX(Base):
    __tablename__ = 'cuckoomx'
    id = Column(Integer, primary_key=True)
    sha256 = Column(String(64), nullable=False)
    email = Column(String(250), nullable=False)
    cuckoo_id = Column(Integer, nullable=False)
    reported = Column(Boolean, default=False)
    uploaded_date = Column(DateTime, default=func.now())

engine = create_engine(email_config.cuckoomx.get("db", "sqlite://cuckoomx.db"))
Base.metadata.create_all(engine)

def send_notification(db, db_entry = False):
    tasks = list()
    if db_entry:
        tasks = [db_entry]
    else:
        tasks = cuckoomx_db.query(CUCKOOMX).filter_by(reported=False).order_by(CUCKOOMX.id.asc())
    if tasks:
        for task in tasks:
            task_info = main_db.view_task(task.cuckoo_id)
            if task_info.status == "reported":
                send_email(email_config.cuckoomx.get("cuckoo_url"), str(task.cuckoo_id), task.email)
                task.reported = True
    db.commit()
def send_email(url, id, to):
    try:
        msg = MIMEMultipart()
        msg['Subject'] = "[Cuckoo] Analysis finished for: {}".format(id)
        msg['From'] = email_config.cuckoomx.get("user")
        msg['To'] = to
        msg['Body'] = url+id
        part = MIMEBase('application', "octet-stream")
        msgAlternative = MIMEMultipart('alternative')
        msg.attach(msgAlternative)
        msgAlternative.attach(MIMEText(url+id, 'plain'))

        server = smtplib.SMTP_SSL(email_config.cuckoomx.get("server"), int(email_config.cuckoomx.get("port")))
        server.login(email_config.cuckoomx.get("user"), email_config.cuckoomx.get("password"))
        #server.set_debuglevel(1)
        server.sendmail(email_config.cuckoomx.get("from"), to.split(", "), msg.as_string())
        server.quit()
    except Exception as e:
        print e

def get_new_emails(db):
    imaplib.IMAP4.debug = imaplib.IMAP4_SSL.debug = 1

    conn = imaplib.IMAP4_SSL(email_config.cuckoomx.get("server"))
    conn.login(email_config.cuckoomx.get("user"), email_config.cuckoomx.get("password"))
    conn.select("Inbox")

    (retcode, messages) = conn.search(None, "(UNSEEN)")
    if retcode == "OK" and messages:
        for num in messages[0].split(" "):
            if num:
                typ, data = conn.fetch(num,"(RFC822)")
                msg = email.message_from_string(data[0][1])
                if msg:
                    email_dict = dict()
                    email_dict["Attachments"] = list()
                    for k, v in msg.items():
                       email_dict[k] = v

                    if email_dict.get("Subject", ""):
                        print "[+] Procesing email with Subject: {0}".format(email_dict["Subject"])
                    for part in msg.walk():
                        attachment = False
                        if part.get_filename():
                            filename = part.get_filename()
                            content_type = part.get_content_type()
                            attachment = part.get_payload(decode=True)


                            if attachment:
                                sha256 = hashlib.sha256(attachment).hexdigest()
                                #unpack it
                                z = ZipFile(File(contents=attachment, password=email_config.cuckoomx.get("archive_password")))
                                files = list(z.unpack(password=email_config.cuckoomx.get("archive_password"), duplicates=[]))
                                for file in files:
                                    new_file = db.query(CUCKOOMX).filter(CUCKOOMX.sha256 == file.sha256).first()
                                    if new_file is None:
                                        new_file = CUCKOOMX(sha256=file.sha256)

                                        temp_file_path = store_temp_file(file.contents, file.filename)
                                        task_id = main_db.add_path(
                                            file_path=temp_file_path
                                        )
                                        new_file.cuckoo_id = task_id
                                        new_file.email = email_dict.get("From", "")
                                        db.add(new_file)
                                        db.commit()
                                    else:
                                        send_notification(db, new_file)
                #mark as seen
                typ, data = conn.store(num,"+FLAGS","\Seen")

    conn.close()
    conn.logout()

if __name__ == "__main__":
    Base.metadata.bind = engine
    DBSession = sessionmaker(bind=engine)
    cuckoomx_db = DBSession()
    while True:
        pass
        try:
            send_notification(cuckoomx_db)
        except Exception as e:
             print e
        try:
             get_new_emails(cuckoomx_db)
        except Exception as e:
             print e
        sleep(30)
    cuckoomx_db.close()`

**Comment by doomedraven** [comment]
use markdown code escape to post code, if no is difficult to read,  i won't compare it line by line, i expect it to be identical to https://github.com/cuckoosandbox/cuckoo/pull/1175/files

ok conf looks ok, the problem which maybe happens here is that not expect ssl/tls 

are you able to connecto to that ports in static way?

like 

```
import smtplib
import imaplib
imaplib.IMAP4.debug = imaplib.IMAP4_SSL.debug = 1
conn = imaplib.IMAP4_SSL(email_config.cuckoomx.get("server"))
conn.login(X, X)
conn.select("Inbox")

```

**Comment by Roucuck** [comment]
No it  tell me email_config not defined  :/ :'(

**Comment by doomedraven** [comment]
Replace that with you server address, i gave example but you shoud fill the fields correctly ti test it

**Comment by Roucuck** [comment]
IT dosen't work it tell me that my server "has not an attribute cuckoomx" and  when i just type
 con = imaplib.IMAP4_SSL(host,port) i have connection refused

**Comment by doomedraven** [comment]
so there is your problem, your server doesn't accept connections, investigate your server

**Comment by Roucuck** [comment]
i will check my configuration thank u anyway for ur helppppp i wish it works

**Comment by doomedraven** [comment]
you are welcome, maybe time to close it as this is not a cuckoo problem? ;)

**Comment by Roucuck** [comment]
yeah you're rigth thanks anywayyyy so much

**Comment by jbremer** [comment]
Closing as per the last comments.
