### ISSUE TITLE
No pdf report generating

### ISSUE THREAD

**Issue by bcallaughan** [cuckoosandbox/cuckoo#1512]
I have updated config to produce both html and pdf reports but only the html report gets generated?

**Comment by jbremer** [comment]
Share some logs ;)

**Comment by bcallaughan** [comment]
Sorry mate I didn't think I actually posted this I was collecting the logs to add to the post when I found the problem!

**Comment by bcallaughan** [comment]
Resolved!

**Comment by jbremer** [comment]
Hence my question :)

**Comment by bcallaughan** [comment]
:)
