### ISSUE TITLE
Broken API endpoint? /tasks/delete/xxx

### ISSUE THREAD

**Issue by PGrantham** [cuckoosandbox/cuckoo#1515]
When I hit the endpoint /tasks/delete/xxx, I get a 200 response with "status": "OK" but the analysis report still shows in the web UI. If I try to hit the endpoint again with the same task id Cuckoo responds with "message": "Task not found". I'm not seeing any errors in the cuckoo logs.

I am still able to delete the report associated with the same task id through the UI.

**Comment by jbremer** [comment]
Hi, yes, you're correct. Unfortunately the Cuckoo API & Cuckoo Web Interface are two completely separate things at the moment. The Cuckoo API currently operates only on the SQL database and the Web Interface operates only on the MongoDB database.
We intend to improve this at some point. For now I hope you find a workaround :-)

**Comment by Popsiclestick** [comment]
If the API endpoint just doesn't work. What do you think a workaround would look like?

**Comment by jbremer** [comment]
As a workaround you can also invoke the `/delete` endpoint in the Web Interface (just check where the `delete analysis` option goes to). It's a little bit hacky though ;-)

**Comment by jbremer** [comment]
We're aware of this bug/feature and intend to improve it in the near'ish future, however, for now I'll be closing this issue. Thanks!
