### ISSUE TITLE
Error resubmitting file (doesn't exist)

### ISSUE THREAD

**Issue by gra55h0pp3r** [cuckoosandbox/cuckoo#1523]
When I try resubmitting a sample that was submitted and shows up in recent analysis, I get an error message "The file you're trying to resubmit no longer exists. Please resubmit it altogether!" I submitted 70+ files yesterday and tried to just resubmit the sample again today and that's when I got the error message. Both the "delete_original" or "delete_bin_copy" are set to "no" in the cuckoo.conf file. When I reboot the server and restart all the cuckoo service (rooter, cuckoo, web) and try to resubmit a file I get the same error.

**Comment by gra55h0pp3r** [comment]
Sorry. I'm using cuckoo version 2.0.3a2. I spoke with @jbremer on IRC Chat about this issue. So it this a new thing in cuckoo 2.0, because the previous version I had I was always able to resubmit the sample file even after rebooting the server. So once the server is rebooted the temp files are deleted, cuckoo will no longer be able to resubmit a file from a previous analysis? I know I can just download the sample and resubmit the sample file, so I was just curious why I would get the error message.

**Comment by jbremer** [comment]
Ah, there we go :-) Downloading the file from the web interface is based on the GridFS backend whereas the resubmit button is based on the filesystem copy of the file.
We're still trying to figure out the best solution for this (the fact that files are both on the file system as well as in GridFS), but unfortunately there doesn't seem to be a best solution.

**Comment by gra55h0pp3r** [comment]
Ah, I see. Thanks for the information and insight into what is going on. If you want, you can go ahead and close this issue.

**Comment by jbremer** [comment]
Will do, thanks!
