### ISSUE TITLE
UI “Submit a file for Analysis” is broken, returning 404, file not processed

### ISSUE THREAD

**Issue by jingkang99** [cuckoosandbox/cuckoo#1526]
cuckoo works fine if submitting from command line.

error
404
---
I changed resultserver and agent comm(common/constants.py) ports. btw, I suggest to moving agent communication port(8000) setting to cuckoo.conf for easy config.

**Comment by jbremer** [comment]
Could you please share hashes that caused errors during web submission? :-)
It could be that the backend of our new submission screen (based on `sflock`, https://github.com/jbremer/sflock) provides errors for your specific files - for various different reasons. Having a copy of whatever it is you submitted would help a great deal there. Thanks!

**Comment by jingkang99** [comment]
I just find out that it happens with IE 11 when submit a exe, not FireFox.

**Comment by jingkang99** [comment]
btw, which UI framework is it?

**Comment by jbremer** [comment]
Oh, yeah, we don't support IE yet as a browser. I'll see if we can have a warning at least to convince users not to use IE for now. Thanks!
Ehm, the old web interface was mostly bootstrap, now it's a mixture of different things. You can check out the `cuckoo/web/src/` directory to learn more about it :)

**Comment by jingkang99** [comment]
Cuckoo doesn't support IE. Issue closed.

**Comment by jbremer** [comment]
A warning for IE11 users is being featured in our upcoming release, btw ;-)
I also tested on IE8, but there it barely loads the dashboard in the first place, so I guess that should be obvious enough.
