### ISSUE TITLE
import rule yara for cuckoo

### ISSUE THREAD

**Issue by anle18** [cuckoosandbox/cuckoo#1527]
Hi guys,

I have a dictionary rules yara and i want to import for cuckoo.  so what should i do ?
Thanks all.

**Comment by jbremer** [comment]
You have a what? :-) You'll want to place your Yara rules in the correct directory in the `$CWD/yara/` directory. It appears there's not much documentation on this, but that should be enough information to get started.

**Comment by anle18** [comment]
sorry, i reply late. i have imported yaraa. but now, when i run cuckoo, i have error this : 

CuckooCriticalError: Please update your configuration. Unable to shut 'cuckoo1' down or find the machine in its proper state: The virtual machine 'cuckoo1' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!

i don't understand why it error. plz help me. Tks

**Comment by jbremer** [comment]
As Cuckoo says, the `cuckoo1` VM doesn't exist. Please follow our documentation and setup Cuckoo correctly. Closing issue.
