### ISSUE TITLE
doc file automatic extraction

### ISSUE THREAD

**Issue by consen** [cuckoosandbox/cuckoo#1531]
I am using cuckoo 2.0, when I submit a doc file on web, the files in the doc file are automatically extracted, but I just want to analyze the single doc file, how to select the single doc file?

![doc](https://cloud.githubusercontent.com/assets/2787272/25894395/34d61946-35ae-11e7-82a3-e3da09cf2a48.png)

**Comment by jbremer** [comment]
Ah yes, improving this is still on our todo list indeed. You can simply tick/select the `.docx` file, though.

**Comment by consen** [comment]
Thanks, now I have to use the CLI `cuckoo submit sample.docx`

**Comment by jbremer** [comment]
Yes, indeed. We'll try to address this for the upcoming release. Thanks for the feedback!

**Comment by jbremer** [comment]
I've pushed out the commit above. You'll be able to check it out by cloning the `sflock` repository and installing it manually. As per the commit message some additional work is still required on both the Cuckoo & SFlock side, but let's take one step at a time. Thanks for the feedback!

**Comment by jbremer** [comment]
@consen We've fixed this as part of `2.0.3a5` (install with `pip install cuckoo==2.0.3a5` until `2.0.3` comes out), please verify & let us know results once you do! Thanks again for the bug report.

**Comment by consen** [comment]
Yes, now I can select the docx file.

![image](https://cloud.githubusercontent.com/assets/2787272/26095537/938228bc-3a50-11e7-8a0d-1bb09eedf8e7.png)

**Comment by jbremer** [comment]
Thanks for acknowledgement! I've pushed out `2.0.3` as well so all future users will get this fix. Closing as resolved.
