### ISSUE TITLE
Error: Failed to run the processing module "Memory"

### ISSUE THREAD

**Issue by bcallaughan** [cuckoosandbox/cuckoo#1532]
I get this with almost every analysis, I understand from searching that this maybe should be suppressed? I am running Volatility 2.6 and Cuckoo 2.0.2.

 If this should be suppressed am I missing an update?

**Comment by jbremer** [comment]
Please share some more information ;-)

**Comment by bcallaughan** [comment]
Failed to run the processing module "Memory" for task #7:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1105, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 984, in __init__
    self.vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 79, in __init__
    self.init_config()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 138, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 WindowsAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 LinuxAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

**Comment by bcallaughan** [comment]
Sorry buddy! I'll get better with reporting logs etc in the future.

**Comment by jbremer** [comment]
No problem. In a later alpha release we've improved the error logging for this, but the point remains that you've incorrectly tagged a VM as a certain OS. E.g., labeled a Windows 7 VM as being Windows XP.
Hope that helps.

**Comment by bcallaughan** [comment]
Hmm is the reference to the OS in Virtual Box? I haven't made any changes to VM's since initial Install and this error has only started showing the past few days.

**Comment by doomedraven** [comment]
vm config

**Comment by bcallaughan** [comment]
The OS is identified correctly in the VM Config (virtualbox)

**Comment by bcallaughan** [comment]
if I change the guest_profile in memory.conf it works just fine, using osprofile =  Win7SP1x64 in virtualbox.conf doesn't work.

# Volatility configuration
# Basic settings
[basic]
# Profile to avoid wasting time identifying it
guest_profile = WinXPSP2x86

When i change this to Win7SP1x64 everything works fine, no error on analysis.

I've found some early references to mem_profile additions (https://github.com/KillerInstinct/cuckoo-modified/commit/0b925f567e05535f6ce9c5ecc1d1e211f9c8d39d) in order to set Volatility profile was this wrapped into 2.0.2?

**Comment by doomedraven** [comment]
use `osprofile= Win7SP1x64 ` in vm configuration, and before open issues do search as it reported so many times and you could get answer in few seconds ;)

**Comment by bcallaughan** [comment]
@doomedraven thanks mate, yeah i searched and found that, it wasn't working but I just worked out why it wasn't working.

 i threw osprofile = Win7SP1x64 in the vm configuration towards the top of the host configuration for the Windows 7 x64 machine.
 osprofile = 
Was further down in the host config undefined which overwrites the previous entry.

**Comment by doomedraven** [comment]
so everything solved? ;)

**Comment by bcallaughan** [comment]
Yep all sorted thanks mate .. closing

**Comment by doomedraven** [comment]
great :)

**Comment by geudrik** [comment]
I know I'm a potato, but... Reviving because I'm having the same issues, despite having the correct `osprofile` specified in my VM config, and `guest_profile = Win7SP1x64` in the basic settings for memory.

```
2017-05-23 14:36:28,837 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #3:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1000, in __init__
    self.vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 79, in __init__
    self.init_config()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 150, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF error: did not find any PT_NOTE segment with VBCORE
 VMWareMetaAddressSpace: VMware metadata file is not available
 QemuCoreDumpElf: ELF error: did not find any PT_NOTE segment with CORE
 VMWareAddressSpace: Invalid VMware signature: 0x464c457f
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Win7SP1x64 selected
 WindowsAMD64PagedMemory: Failed valid Address Space check
 LinuxAMD64PagedMemory: Incompatible profile Win7SP1x64 selected
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile Win7SP1x64 selected
 IA32PagedMemory: Incompatible profile Win7SP1x64 selected
 OSXPmemELF: No PT_LOAD segments found
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check
```

When I run Volatility on it manually, it works as expected

```
$ python ~/volatility/vol.py -f memory.dmp --profile=Win7SP1x64 psscan
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
0x00000000f6524d0c System                4      0 0x0000000000187000 2017-05-23 17:19:16 UTC+0000                                 
0x00000000f652905c wininit.exe         396    348 0x00000001d11d5000 2017-05-23 17:19:18 UTC+0000                                 
0x000000020da6b7fc cyrprtui.exe       2056   2548 0x00000001892d1000 2017-05-23 18:19:19 UTC+0000   2017-05-23 18:19:22 UTC+0000  
```

**Comment by jbremer** [comment]
Can you show the machinery configuration? And which version of Cuckoo?

**Comment by geudrik** [comment]
![image](https://cloud.githubusercontent.com/assets/2020115/26404171/e4baabb4-405e-11e7-890a-00b3651239c6.png)

```
[virtualbox]
mode = headless
path = /usr/bin/VBoxManage
interface = vboxnet0
machines = cuckoo1


[cuckoo1]
label = Win7UltSP1_1
platform = windows
ip = 192.168.56.106
snapshot = analysis_booted_ready
interface =
resultserver_ip =
resultserver_port =
tags =
options =
osprofile = Win7SP1x64
```

**Comment by geudrik** [comment]
```$ vboxmanage showvminfo Win7UltSP1_1
Name:            Win7UltSP1_1
Groups:          /Windows 7 x64 SP1
Guest OS:        Windows 7 (64-bit)```

**Comment by geudrik** [comment]
Any ideas? Would this be better suited in its own issue?

**Comment by geudrik** [comment]
@rholloway did we fix this elsewhere, or did we opt to not use volatility?
