### ISSUE TITLE
Failed to run the reporting module: MISP

### ISSUE THREAD

**Issue by gra55h0pp3r** [cuckoosandbox/cuckoo#1535]
I've setup a MISP server and configured the processing and reporting configuration files with the correct settings to connect to the MISP server. When I submit a sample everything works fine, but if I trying to reprocess a previous analysis I get an error message: "Failed to run the reporting module: MISP". I'm trying to have cuckoo regenerate all previous analysis and enter the information into cuckoo.

Command line: cuckoo --cwd /mydirectory/path/ process -r ## (## analysis ID).

**Comment by gra55h0pp3r** [comment]
You can go ahead and close this issue. What I did was go into each analysis, read task.json, pulled the target, then created the directory path and copied the file over. Once I did this and ran the command everything completed successfully and all information was inserted into MISP.

**Comment by doomedraven** [comment]
you can close your issues by yourself ;)
