### ISSUE TITLE
Extra Options not working in Cuckoo 2.0.2

### ISSUE THREAD

**Issue by ronbarrey** [cuckoosandbox/cuckoo#1537]
When specifying an extra option from the web UI, the extra options are not serializing properly, line 2197 in submission.js.

Fix: add the code blocks for the setValue command after the if statement.

After correcting the issue, the extra options are not getting added to the analysis config.

**Comment by jbremer** [comment]
Yes, the last part was still on our todo list. Thanks for highlighting the issue :)

**Comment by jbremer** [comment]
@ronbarrey Please find the commit above - we're halfway fixing this issue now :-) Thanks again.

**Comment by jbremer** [comment]
Hmm, I wanted to say this has been fixed in `2.0.3a5`, but it has not. To be fixed still :-)

**Comment by jbremer** [comment]
Yes, this seems resolved now. We've released `2.0.3` in the meanwhile, so you can upgrade with `pip install -U cuckoo`. Thanks for the feedback!
