### ISSUE TITLE
Package selection from web UI does not work in Cuckoo 2.0.2

### ISSUE THREAD

**Issue by ronbarrey** [cuckoosandbox/cuckoo#1538]
When selecting a package from the web UI, there is a reference error 'setFieldValue is not defined', line 2765 in submission.js.

Fix: remove the setFieldValue line

**Comment by jbremer** [comment]
Thanks! Going to have a look as well.

**Comment by automagisch** [comment]
Fixed this issue straight away by removing the 'setFieldValue' property, it was not needed after all. Thanks for the catch! Fix will be available in the upcoming update.

**Comment by jbremer** [comment]
We've released a fix for this in `2.0.3a5`. Closing as resolved. Please reopen if there are additional issues etc :-)
