### ISSUE TITLE
Unreachable code after return statement Cuckoo 2.0.2

### ISSUE THREAD

**Issue by ronbarrey** [cuckoosandbox/cuckoo#1539]
A return statement is specified before a code block in submission.js, line 499.

Fix: move the return statement after the code block

**Comment by jbremer** [comment]
Thanks! Going to have a look.

**Comment by automagisch** [comment]
This has been fixed internally, will be pushed in the next update! Good catch @ronbarrey , to enlighten this issue a bit, it was nothing breaking, it returned because the function was not utilised anymore. Removed the method in its entirety.

**Comment by jbremer** [comment]
We've released a fix for this in `2.0.3a5`. Closing as resolved. Please reopen if there are additional issues etc :-)
