### ISSUE TITLE
scheduler.py - syntax error

### ISSUE THREAD

**Issue by zashraf1337** [cuckoosandbox/cuckoo#1541]
I may be wrong here but this may be what is intended

```
diff --git a/cuckoo/core/scheduler.py b/cuckoo/core/scheduler.py
index 6c782dc..60f6ad3 100644
--- a/cuckoo/core/scheduler.py
+++ b/cuckoo/core/scheduler.py
@@ -357,7 +357,7 @@ class AnalysisManager(threading.Thread):
         if self.route == "inetsim":
             rooter("inetsim_disable", self.machine.ip,
                    cfg.inetsim.server,
-                   str(cfg.resultserver.port))
+                   str(self.cfg.cuckoo.resultserver_port))
 
         if self.route == "tor":
             rooter(

```
There is an error message I got - that is pending investigation
```
2017-05-11 15:08:50,928 [cuckoo.core.rooter] WARNING: Rooter returned error: remote_dns_forward() takes exactly 4 arguments (3 given)

```

**Comment by zashraf1337** [comment]
```
Traceback (most recent call last):
  File "/home/zashraf/cuckoo/cuckoo/apps/rooter.py", line 388, in cuckoo_rooter
    output = handlers[command](*args, **kwargs)
  File "/home/zashraf/cuckoo/cuckoo/apps/rooter.py", line 202, in inetsim_enable
    remote_dns_forward(ipaddr, inetsim_ip, "-A")
TypeError: remote_dns_forward() takes exactly 4 arguments (3 given)

```

**Comment by doomedraven** [comment]
see inetsim2 pr, solved there

**Comment by doomedraven** [comment]
@jbremer was time to merge that no? :P

**Comment by jbremer** [comment]
The InetSim PR has been merged, please test it and provide us with feedback. Please leave your comments in #1435. If something else has been discussed in this thread that I missed, but that's important in one way or another, please reopen the issue with an additional comment or copy the comment / issue / whatever to #1435.
I'll be closing this issue now. In #1435 I'll be announcing when a new alpha or stable release is out in which you may find the InetSim working once again. Thanks again for the feedback & sorry once more for the delay on our side.
Ping @zashraf1337.
