### ISSUE TITLE
idle VM count

### ISSUE THREAD

**Issue by kimgudtjr** [cuckoosandbox/cuckoo#1551]
I have installed Cuckoo Sandbox (has 100 virtual machines)

Then, I requested About 300 samples in a short time.

After the request, I have monitored the entire sample changes from the pending state to the running state.

There are 80-50 idle virtual machines, but actually running virtual machines is just only 15-20.

I do not know why many virtual machines are idle.

I'm wondering if you're having a similar problem or a solution.

**Comment by doomedraven** [comment]
check virtualization app max client, we saw a bit ago case like this with kvm, which has max clients only 18

**Comment by jbremer** [comment]
And also check the `max_vmstartup_count` value in `cuckoo.conf` :)

**Comment by kimgudtjr** [comment]
Thank you for your reply.
But already my max_vmstartup_count value in cuckoo.conf is 100.
Therefore, this is not a problem with max_vmstartup_count.
And I'm using VirtualBox.
Can VirtualBox also have a max client problem?
I found the following problem through log file analysis
when it fetch task in the scheduler.py
the speed is getting slower.
To fetch task takes between 5 and 6 seconds.
It seems to be slower in database access code.
Why is this happening?
please answer about my question.

**Comment by jbremer** [comment]
Did you submit the files with anything special, e.g., `tags` or `machine` fields set? In that case, that's something we still have to improve. Otherwise, Cuckoo setups with 20-30 VMs seem to work fine for me - I don't have experience with 100 VMs, though.

**Comment by tuxx42** [comment]
kimgudtjr, I am having the same problem when running cuckoo on a machine with 40 Virtualhosts, usually about half are idle at all times, while the rest is either running or restoring. I'm not entirely sure what the bottleneck is here, but it seems like something is blocking execution of the cuckoo daemon.

**Comment by doomedraven** [comment]
check in cuckoo.conf how many vms can be run in parallel

**Comment by tuxx42** [comment]
I have the following restrictions

process_results = no
max_analysis_count = 0
max_machines_count = 0
max_vmstartup_count = 40

**Comment by doomedraven** [comment]
i would suggest to dig in vbox forum about that, as i remember in one of the issues it was in hypervisor conf(default hypervisor conf not cuckoo related) but i don't remember which exactly

**Comment by tuxx42** [comment]
I have been able to verify that its not an issue with the virtualbox config, as I am easily able to manually spawn 40 VMs simultaneously using VBoxManage. Running strace -e execve against the cuckoo process shows that cuckoo makes no attempt to schedule more analysis, presumably due to it maxing out on a single core.

Again to my original question, is there any conceivable ways to reduce the cpu load of the cuckoo process in order to free up some resources to maybe allow it to attempt to spawn more vms?

**Comment by seantree** [comment]
Hi @tuxx42 

Are you using any cloud storage? I am also planning to add 50+ machines so kindly suggest me if you don't mind and are you using with the help of qemu or kvm?

Thanks & Regards
Seantree

**Comment by jbremer** [comment]
By running Cuckoo in regular mode (as opposed to verbose mode, i.e., `cuckoo -d`) one should be able to run up to 50 VMs with a single Cuckoo instance on a machine. A number of performance issues should be addressed to further bump this number. To be continued ;-)

**Comment by tuxx42** [comment]
we're running cuckoo with "cuckoo -m 0" however it still consumes 100% cpu.
and slows down to only a handful of vms (maybe 10) despite having 40
physical cores (80 hyperthreaded)

**Comment by jbremer** [comment]
`cuckoo -m 0` doesn't make a lot of sense as that's the default option anyway. But yes, due to it being Python it's kind of limited. As I said, needs some (a bunch of those, really) additional performance tweaks etc ;-)

**Comment by jbremer** [comment]
Closing issue. Feel free to reopen if any discussion still needs to happen here.
