### ISSUE TITLE
Package Feature Request

### ISSUE THREAD

**Issue by ronbarrey** [cuckoosandbox/cuckoo#1552]
Could we add a registry modification for doc, xls, and ppt packages to automatically enable ActiveX?
`
        [
            HKEY_CURRENT_USER,
            "Software\\Microsoft\\Office\\Common\\Security",
            {
                # Enable ActiveX controls in Office.
                "DisableActiveX": 0,
                "UFIControls": 1,
            },
        ],
`

**Comment by doomedraven** [comment]
feel free to do PR https://github.com/cuckoosandbox/cuckoo/tree/master/cuckoo/data/analyzer/windows/modules/packages here you can find the packages

**Comment by jbremer** [comment]
Closing this issue as you've opened #1555 :-) Looks good btw, going to test it soon.
