### ISSUE TITLE
URL submission 2.0.2

### ISSUE THREAD

**Issue by benrau87** [cuckoosandbox/cuckoo#1554]
Hello,
Working with 2.0.2 and not sure why I keep getting errors when submitting URLs for analysis. It will not process the submission unless it is this specific FQDN format:  http://example.com.
If I try to submit an URI after the fact, it will not show up under the submission. For example it will not parse examle.com/wp-admin , also cannot submit a domain such as  example.com.de 
Thanks for any assistance, or helping me get my head out of my...

**Comment by jbremer** [comment]
If I submit the following, it processes the URLs just fine for me.

```
example.com
example.com.de
example.com/wp-admin
```

https://cuckoo.sh/db3f1ac16daa53c5/screenshot.png

Do you see different behavior?

**Comment by benrau87** [comment]
Well now I feel dumb...
Turns out the issue was having a trailing / on the URI for each case, since
I just copy and pasted the GET string over.
Example.com/wp-admin works but not example.com/wp-admin/

Thank you for the fast response!

**Comment by jbremer** [comment]
Ehm, if that doesn't work that'd be a bug, however, I just tested and that seems to work fine here?
Could you share some screenshots or whatever from input vs output?

**Comment by benrau87** [comment]
Okay, narrowed down the exact issue. It was an artifact added by copy and paste or neglectful typing. If you have a space after the URL then it fails to parse that input into the submission screen.  Nothing to do with the ending character, just don't hit the space bar after it haha.

**Comment by jbremer** [comment]
Ah, saw this issue just too late or I could have included it in the `2.0.3` release. Anyway, resolved now, see also https://github.com/jbremer/cuckoo/commit/3894d83effc5d0907444638e0d02256a1394ed3a. Will be pushing it as part of the next alpha release! :-) I'll close this issue as you're aware of the workaround for now. Thanks for the feedback!

**Comment by linik99** [comment]
Nice post article
https://www.youtube.com/watch?v=igoUfnQmPfQ
