### ISSUE TITLE
linux agent returns ptrace(PTRACE_TRACEME, ...): Operation not permitted

### ISSUE THREAD

**Issue by WalterJia** [cuckoosandbox/cuckoo#1556]
strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
trace: Process 3354 attached
strace: Process 3355 attached

**Comment by doomedraven** [comment]
let me google that for you :D
https://blog.packagecloud.io/eng/2015/11/15/strace-cheat-sheet/

**Comment by WalterJia** [comment]
I have updated configuration like that before, but it doesn't work.
I saw the strace command in guest like this "strace -ff -o /strace/straced -p xxx", xxx is the PID of analyze.py, is this process correct?

**Comment by doomedraven** [comment]
no, as it upload file to guest, and it should trace the target file not the analyzer

subprocess.Popen(["strace", "-ff", "-o", "strace/straced", path], stderr=stderrfd)

for details see 
https://github.com/cuckoosandbox/cuckoo/pull/1545/files

**Comment by WalterJia** [comment]
I saw the code went through the statement below when there is something wrong in stap module, it might be a bug or not, currently I have fixed it in my code, thanks a lot.
        else:
            # we can't find the stap module, fallback to strace
            log.warning("Could not find STAP LKM, falling back to strace.")
            return self.start_strace()

    def start_strace(self):
        try: os.mkdir("strace")
        except: pass # don't worry, it exists

        stderrfd = open("strace/strace.stderr", "wb")
        self.proc = subprocess.Popen(["strace", "-ff", "-o", "strace/straced", "-p", str(os.getpid())], stderr=stderrfd)

**Comment by doomedraven** [comment]
check documentation here in repo about linux guest install if you want to use stap, but better apply that pr and use ptrace it returns better results

**Comment by doomedraven** [comment]
i have one question if you don't care, why you trace analyzer instead target file? you will have in behavior part of analyzer which is just a noise

**Comment by WalterJia** [comment]
I have fixed this problem, so close this issue, thank you doomedraven very much.

**Comment by doomedraven** [comment]
Which was the fix finally? You are welcome
