### ISSUE TITLE
Slow report delivery

### ISSUE THREAD

**Issue by pskmsc** [cuckoosandbox/cuckoo#1557]
Hello,

I got an issue with reporting, the analysis is available a long time after the run is marked as completed.
If I send multiple files, let say 5 files, the result is available only hours after all is marked completed.

I've made a long test on Friday with a certain number of samples :
Logs: https://pastebin.com/tqeqS4Cu

2 hours after I started the test, no reports were available.
Monday morning all reports were available.

It looks like no reports are available until all runs are finish.

Can you please give advises about how to optimize this ?

Here are some more details :

CPU : Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz  (16 cores)

Cuckoo disk :
              *-disk:1
                   description: SCSI Disk
                   product: LOGICAL VOLUME
                   vendor: HP
                   physical id: 1.0.1
                   bus info: scsi@2:1.0.1
                   logical name: /dev/sdb
                   version: 6.64
                   serial: xxxxxxxxxxxxxx
                   size: 279GiB (299GB)
                   capabilities: 15000rpm partitioned partitioned:dos
                   configuration: ansiversion=5 logicalsectorsize=512 sectorsize=512 signature=80263ae8
                 *-volume
                      description: Linux filesystem partition
                      vendor: Linux
                      physical id: 1
                      bus info: scsi@2:1.0.1,1
                      logical name: /dev/sdb1
                      logical name: /opt/cuckoo
                      version: 1.0
                      serial: 402f7a36-177e-4f19-a37a-6d63aefcf46b
                      size: 279GiB
                      capacity: 279GiB
                      capabilities: primary extended_attributes large_files ext2 initialized
                      configuration: filesystem=ext2 lastmountpoint=/opt/cuckoo modified=2017-05-12 12:16:22 mount.fstype=ext4 mount.options=rw,relatime,block_validity,delalloc,barrier,user_xattr,acl mounted=2017-05-12 12:16:22 state=mounted

Memory :
              total        used        free      shared  buff/cache   available
Mem:          32161        3914       14028          68       14218       27673
Swap:         32755          25       32730

auxiliary.conf : https://pastebin.com/iUza9PjH
cuckoo.conf: https://pastebin.com/qBT4fsPQ
reporting.conf : https://pastebin.com/TRkNF8HV
memory.conf : https://pastebin.com/4hspVpvb

Thanks in advance.

Regards,

**Comment by doomedraven** [comment]
easy, read the documentation

process_results = yes <- in cuckoo.conf, should be no, and you should start 
`cuckoo -d process a1`
`cuckoo -d process a2`
`cuckoo -d process aX` # as much as you want parallel processing

**Comment by pskmsc** [comment]
Thanks, Nice RTFM, you are right, even if i've read the doc, I missed http://docs.cuckoosandbox.org/en/latest/usage/utilities/?highlight=process_results 
This is solving one point, unfortunately, reporting is still a bit slow.
Other tips ?

**Comment by doomedraven** [comment]
post one log with in debug mode `-d` and post it so we can see timing of each reporting part

**Comment by doomedraven** [comment]
as documentation also says

Posting messages saying just something like “Doesn’t work, help me” are completely useless. If something is not working report the error, paste the logs, the config file, the information on the virtual machine, the results of the troubleshooting, etc. Give context. We are not wizards and we don’t have a crystal ball.

**Comment by pskmsc** [comment]
OK thanks.

**Comment by doomedraven** [comment]
post log from `process` window to see which module takes so much to process
