### ISSUE TITLE
Analysis Print Problems

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1565]
The current analysis output in Cuckoo 2.0.2 has various problems when printed:
- Output that should be many pages long only shows the first page
- UI is not hidden
- Top buttons are styled inconsistently

![print issue](https://cloud.githubusercontent.com/assets/6509657/26124901/3819351c-3a4e-11e7-9300-472c91e72a39.png)
Firefox screenshot down, similar issues seem to occur in Chrome.

**Comment by jbremer** [comment]
Well, yeah, there's not much we can do here. Simply put the Web Interface is not something that you're supposed to print - we have the upcoming `singlefile` HTML & PDF reporting module for that ;-)
Closing as wont fix, thanks for the feedback though.
