### ISSUE TITLE
agent.py not showing anything in windows Xp guest

### ISSUE THREAD

**Issue by bryannn7** [cuckoosandbox/cuckoo#1566]
I installed python for the guest running on windows xp, however when I tried to run agent.py on the guest, nothing happens just a black box. I understand that there is supposed to be "Starting agent on 0.0.0.0:8000 ..." appearing in the black box. Why isn't it showing on mine?
![capture](https://cloud.githubusercontent.com/assets/28752591/26146901/5b4acd8a-3b24-11e7-9ce9-02ace87c333e.PNG)

**Comment by robputt796** [comment]
I think this is normal, mine doesn't log anything either. Probably expected after all its designed to be ran in windowless mode. Have you tried submitting an analysis job to the machine? It'll probably work.

**Comment by jbremer** [comment]
Eh yeah, that's correct. The new Cuckoo Agent doesn't show anything (currently).

**Comment by jbremer** [comment]
Does that answer your question?

**Comment by bryannn7** [comment]
Oh I see, yes it does. Thank You!

**Comment by jbremer** [comment]
Great, closing issue. Thanks.
