### ISSUE TITLE
Guest OS analysis error (Help please)

### ISSUE THREAD

**Issue by bryannn7** [cuckoosandbox/cuckoo#1570]
I am trying to run an analysis on cuckoo but I am stuck with some error. I hope someone can help me with it! 
![cuckoo error](https://cloud.githubusercontent.com/assets/28752591/26158983/f2ec8266-3b4f-11e7-8cf9-68d7fc74e886.png)

Both guest and host can ping each other.

log file
![log file](https://cloud.githubusercontent.com/assets/28752591/26159283/c84cd866-3b50-11e7-9080-645bae736f74.png)

**Comment by doomedraven** [comment]
as it says, search apparmor in documentation + you maybe executed vbox as root, and now you have problems no? or upgraded kernel ?
google vbox error

**Comment by bryannn7** [comment]
Thanks for the reply but I don't quite understand what you mean. Can you explain it again? Thanks.

**Comment by doomedraven** [comment]
https://cuckoo.sh/docs/installation/host/requirements.html#installing-tcpdump

**Comment by doomedraven** [comment]
you should read the whole documenation for correct setup

**Comment by bryannn7** [comment]
Okay thanks I will read that

**Comment by jbremer** [comment]
I see a number of issues here.

* Somewhere you misconfigured the sniffer plugin, see also the `unknown host 'no'` error in the first screenshot (this error is new to me).
* Did you close the `cuckoo rooter` while executing the Cuckoo daemon? That's not how it's supposed to work :-)
* Something weird happened to your VM, although I'm not sure what..

**Comment by cheantik** [comment]
To resolve error "Unable to restore to the snapshot....."
You can try to restore vm cuckowinxp to snapshot winxplatest manualy
```
vboxmanage snapshot cuckoowinxp list (copy winxplatest UUID)
vboxmanage snapshot cuckoowinxp restore "paste winxplatest UUID"
```
In case of error you can try to clone vm without any snapshots
(https://cuckoo.sh/docs/installation/guest/cloning.html)
such as
`vboxmanage clonevm cuckoowinxp --name "newvmname" --register`
Then you need to:
1. create snapshot for vm "newvmname"
2. modify your virtualbox.conf (machines,label,snapshot & etc)

In my case it was helpfull.

**Comment by jbremer** [comment]
Thanks for additional insights @cheantik. Closing issue as resolved. Please reopen if there are additional questions or feedback. Thanks!
