### ISSUE TITLE
it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host

### ISSUE THREAD

**Issue by shadoww0** [cuckoosandbox/cuckoo#1572]
I am using a windows 7 host with vmware. Set to NAT.

cuckoo.conf:
[resultserver]
ip = 192.168.0.100
port = 2042

vmware.conf:
ip = 192.168.233.129

I can ping each other machines.

In my host I get this error:

```
2017-05-18 00:40:00,723 [cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.233.129)
2017-05-18 00:40:01,740 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=cuckoo1, ip=192.168.233.129)
2017-05-18 00:40:02,213 [cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.0.100.
2017-05-18 00:40:02,213 [cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.0.100.
```

And inside the vmware agent:

![untitled](https://cloud.githubusercontent.com/assets/27292675/26179243/d5d38ec8-3b62-11e7-87d0-c9b9d780af6f.png)

```

**Comment by shadoww0** [comment]
Any help appreciated.

**Comment by doomedraven** [comment]
ip = 192.168.0.100
port = 2042

vmware.conf:
ip = 192.168.233.129

They are in different networks

**Comment by shadoww0** [comment]
Is there a way to enable this configuration?   Other services work between the two machines (web, telnet).

**Comment by doomedraven** [comment]
try to set in cuckoo.conf result_ip to 0.0.0.0 and specify result ip in vm config
as i suppouse there few network interfaces? of is just /16 range?

**Comment by shadoww0** [comment]
it is just my host machine (win7)and vmware workstation (win7 too)

with 0.0.0.0 this is the error:
CRITICAL: ResultServer unable to map ip to context: 192.168.0.100.

There is also an error in the guest (agent.py) see attached picture
![error](https://cloud.githubusercontent.com/assets/27292675/26260146/754356fe-3ccc-11e7-9896-8dc9cf4bc5d8.png)
.

**Comment by shadoww0** [comment]
So basically these are the same errors.

**Comment by doomedraven** [comment]
As cuckoo say it cant map that ip to any vm, post vms configuration, also did you configured firewall?

**Comment by shadoww0** [comment]
Firewalls turned off in both machines.

**Comment by shadoww0** [comment]
[ipconfig_guest.txt](https://github.com/cuckoosandbox/cuckoo/files/1015248/ipconfig_guest.txt)
[ipconfig_host.txt](https://github.com/cuckoosandbox/cuckoo/files/1015247/ipconfig_host.txt)


[cuckoo.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/1015249/cuckoo.conf.txt)
[vmware.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/1015250/vmware.conf.txt)

**Comment by doomedraven** [comment]
you still have the wrong configuration
```
ip = 192.168.233.129
resultserver_ip = 192.168.0.100
```

they are in different network ranges

**Comment by shadoww0** [comment]
If I change the IP manually I lost internet connection in the guest.

**Comment by shadoww0** [comment]
Ok. with bridged connections it is working.
Thank you sir!

**Comment by doomedraven** [comment]
you are welcome, be aware of the danger of bridge mode

**Comment by rainkin1993** [comment]
I have one more question:
why should VM's Ip and ResultserverIp in the same subnet (network) ?  Are there any solutions to do this?

I run `cuckoo -d` in a docker container, whose ip is 172.17.0.2 and vm in another ip address, which is 192.168.12.227.

And the config is:
**kvm.conf**
ip=192.168.12.227
resultserver_ip = 172.12.0.2
resultserver_port = 2042

**cuckoo.conf**
[resultserver]
ip = 0.0.0.0
port = 2042

And I get a very strange error:
`ResultServer unable to map ip to context: 172.17.0.1.`

it's not the resultserver_ip I set.

**Comment by doomedraven** [comment]
that isn't the same network range

**Comment by rainkin1993** [comment]
Thanks for your help. But I want to know why they should be in the same network range. Can I figure out a way to do this?

**Comment by doomedraven** [comment]
that sound pretty logical, your host not route traffic correctly so you will need apply extra iptables, vm will look for host in the same subnet

**Comment by rainkin1993** [comment]
Sorry. I don't understand your reply. 

To be clear: the firewall allows connection between **172.17.0.2** and  **192.168.12.227**. When I run the command `nc -l 2042` in **172.17.0.2** and `telnet 172.17.0.2 2042` in **192.168.12.227**, the communication works well. Thus no traffic problem in my question.

`ResultServer unable to map ip to context: 172.17.0.1.`
What makes me strange is that guest connects to the 172.17.0.1 instead of the resultserver IP (172.17.0.2) I set in the kvm.conf.

If I am wrong, please correct me.

Thanks
