### ISSUE TITLE
Sniffing the connection between all the guests

### ISSUE THREAD

**Issue by ofekbgu** [cuckoosandbox/cuckoo#1575]
Hi 
I have 3 guests one is Windows and the others are Ubuntu. 
I want to analyze the network traffic between all the guests. 
Before the submission I'm running the Ubuntu's guests, and then I'm submitting a task to the windows guest. for the testing I submit a script with ping commands to all the nodes in the network in order to see the packets at the Network Analysis area.
after it I'm taking the pcap file and open it with Wireshark
the problem is that I can't see the traffic between the guests, only between host-guest.

Host - 192.168.56.1
guest1- 192.168.56.101
guest2 - 192.168.56.102
windows guest - 192.168.56.103
  
Thanks 

![pic](https://cloud.githubusercontent.com/assets/28686383/26203815/614d53e4-3be5-11e7-86c3-81e7b02b676f.png)

**Comment by doomedraven** [comment]
if you use host only, guests can't speak between them, and why do you need do that?

**Comment by ofekisra** [comment]
Hi, Thanks for reply.
When I made a ping command from one guest to other I got the reply so the guests can speak between them, they are all in same virtual network 192.168.56.0.
I need it in order to analyze how behave of malware affect the the lan network. 
Thanks again.

**Comment by doomedraven** [comment]
well that all depends on the network format which do you use, bridge/host only etc, use host only + apply fix for rooter from pr inetsim2 and you will have hardened netwrok part :)

which current network style do you use? because in host only they shouldn't be able to ping between guests, if i'm not confuse something

**Comment by ofekisra** [comment]
I'm using host only.

**Comment by doomedraven** [comment]
but how you have configured/using rooter? if you provide whole picture of the setup then it will be more easy to help you :)

**Comment by ofekbgu** [comment]
I've just enter the command 
`sudo cuckoo rooter -g <user>` and I don't use Per-Analysis Network Routing
which exactly conf file do u need to look on it, I'll upload it.

**Comment by ofekbgu** [comment]
I fix it by comment the code that filter all these traffic 

![image](https://cloud.githubusercontent.com/assets/28686383/26685069/af745c86-46f1-11e7-818d-f7c7551d8077.png)

**Comment by jbremer** [comment]
Closing issue as resolved. Seems unnecessary to uncomment the filtering for the Cuckoo Agent traffic, though. Please reopen if you have additional questions / feedback on this matter. Thanks!
