### ISSUE TITLE
[Question] How is machine selected ?

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#1588]
Hello, 
When I submit a file for analysis, how is machine automatically selected?
Is there some criterion to only run 64 bits files on 64 bits machines?
If yes, how do I specify that in machines tags?
If no, would you consider adding ?

**Comment by doomedraven** [comment]
Hint, check in scheduler.py for fetch

**Comment by Tigzy** [comment]
So what I isee now is that it's taking machine by name (if forced) then by tag, then the first avail?

**Comment by Tigzy** [comment]
Ok I think I'll move the logic on my side and work with 32 / 64 bits tags to force selection

**Comment by doomedraven** [comment]
Correct you can fix it adding one small if to check if pe32+ is in magic, and set x64 tag done
