### ISSUE TITLE
Options are not sent

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#1589]
Hello, 
I'm writing an auxiliary module (guest side), and I want to switch it on/off or tweak behavior based on options sent, either via API or from web interface.

So I looked at the existing modules, and found that:
```
class DbgView(Auxiliary):
    """Run DbgView."""
    def start(self):
        if not self.options.get("dbgview"):
            return
```
So I've created my own module and I'm just dumping the options dict for testing, but it appears that the custom options are not inside. This is all I get when I'm adding "test: yes" in the "Extra options" fields of the submission page:

```[modules.auxiliary.roguekiller] INFO: {"procmemdump": "yes", "route": "none", "apk_entry": ":"}```

Any chance that is a bug? Or do I need to validate options elsewhere in the code?

**Comment by jbremer** [comment]
Did you try this against our `2.0.3` release? If not, could you? :) I've tested this as working, see also #1537.

**Comment by Tigzy** [comment]
Already? ok, I will make a pull

**Comment by Tigzy** [comment]
Confirmed NOT fixed, at least for the Auxilary packages.
INFO: {"procmemdump": "yes", "route": "none", "apk_entry": ":"}

**Comment by Tigzy** [comment]
I think this bug is potentially impacting the other existing auxilliary modules (dbgview, human etc...)

**Comment by Tigzy** [comment]
Ok wait a bit, I've restarted the API and Web modules, now I see some changes: 
[modules.auxiliary.roguekiller] INFO: {"test": "yes", "procmemdump": "yes", "route": "none", "apk_entry": ":"}

Will do more tests.

**Comment by Tigzy** [comment]
OK, NVM confirmed fixed :) 👍

**Comment by jbremer** [comment]
Good, thanks for feedback ;)
