### ISSUE TITLE
Human module, unicode characters

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#1592]
Hello, 
Running a Cuckoo guest on XP French, the agent is having a hard time (100% CPU, a lot of exceptions) with the human module and the accentuated characters in the open windows.

Attached capture, as I can't do much on the guest:
![human_crash](https://cloud.githubusercontent.com/assets/9531438/26318724/5ccbdf86-3f1c-11e7-8f8a-c33b4035f7ff.JPG)

**Comment by Tigzy** [comment]
Analysis still running (15 mns now), I think it will hit the critical timeout. There's definitely something wrong here...

**Comment by jbremer** [comment]
@Tigzy The issue should be resolved with the commit(s) above in place. To be included in a next alpha/stable release nearby! ;-) Thanks for reporting.

**Comment by jbremer** [comment]
The above had been included in our `2.0.4a2` release. Closing this issue as such.
