### ISSUE TITLE
Cuckoo Package : 2.0.3a5 Droped files

### ISSUE THREAD

**Issue by SparkyNZL** [cuckoosandbox/cuckoo#1602]
Currently the submit dropped file button is broken :( 

The url its trying to reach is 

http://<ip address>/submit/<sample number>/dropped/<sha1>/

The web browser just sit waiting for a reply, the interesting thing is that the cuckoo web process gives a 301 

-------------------------------------------------------------------------------------------

[24/May/2017 18:39:48] "GET /submit/40740/dropped/f6e1e0df6b9f9e4207006ae5cf9cf329254009ee HTTP/1.1" 301 0

---------------------------------------------------------------------------------------------

And on this, how hard would it be to automatically submit dropped files ?

**Comment by jbremer** [comment]
Do you happen to know if this issue is still present @SparkyNZL?

**Comment by jbremer** [comment]
Closing issue.
