### ISSUE TITLE
linux cuckoo analyzer not found issue

### ISSUE THREAD

**Issue by ahroobe** [cuckoosandbox/cuckoo#1603]
I got same error with #1549 and I revised cuckoo source code by using #1545 then #1549 error has been gone.
However I got another issue that in guest, 
/usr/bin/python: can't open file '/root/tmp~~\analyzer.py' : Error2 No such file or directory
error occurred.
I checked /root/tmp~~/analyzer.py is there, but that guest just finds \analyzer.. I think this is a problem.
and also in analyzer.py, has some tab and space problem.

**Comment by doomedraven** [comment]
first of all why there is `~~` ? that is what breaks everything
+ why analyzer.py in /root/tmp/?
+ missed logs ;)

there a lot of not understanding parts at least for me, more context what you did would be good

**Comment by ahroobe** [comment]
![ddd](https://cloud.githubusercontent.com/assets/12726078/26407182/5a69deae-40d5-11e7-9951-3453a6acd4ab.png)
sorry i forgot to upload the capture.
as you can see, This is the situation right after run cuckoo and submit some .sh file.
guest is debian8 32bit and host is 64bit ubuntu.

and analyzer.py error is
python analyzer.py on upper terminal got some error.( I forgot it but error message was related to space and tab, near "straces")

**Comment by doomedraven** [comment]
ok so you applied all/few patches from my pr as i understand no? that is weird because i have deployed 2 cuckoos with that patches and everything works just fine %)

can you replace on your side this 
https://github.com/doomedraven/doomedraven-cuckoo/blob/f9f368ace96b89bf165b6ae6ddf56f6f44077d4a/cuckoo/core/guest.py#L483
`//` to `\\` and test it? but that is so weird

can you provide more info about `straces`?

**Comment by ahroobe** [comment]
sorry second one was my fault i guess.. (when changing the code)

and first one, I revised 
"filepath": "%s\\analyzer.py" % self.analyzer_path, 
to
"filepath": "%s/analyzer.py" % self.analyzer_path, 
and it pretty works well. Thanks!

**Comment by doomedraven** [comment]
you are welcome, which agent version do you use? 0.7? i will add fix for that, as i never had that error %)

**Comment by ahroobe** [comment]
yes version 0.7

**Comment by doomedraven** [comment]
can you test that commit? i have tested in production works fine, but the double check would be good :)

and if solved, close ;)

**Comment by ahroobe** [comment]
Yes it works. 

and +) Linux analyzer still uses xmlrpcserver and new agent version not.  (windows analyzer uses compatible analyzer with try catch ) It causes xmlrpcserver 404 not found error, and should be changed xmlrpcserver to urllib2..

**Comment by doomedraven** [comment]
Great thanks, side note for you @jbremer
