### ISSUE TITLE
error after analysis complete!

### ISSUE THREAD

**Issue by shorlak** [cuckoosandbox/cuckoo#1607]
I have issue anytime analysis is completed.
The error is related to the scheduler.py. here is my output:
`2017-05-23 17:52:48,532 [cuckoo.core.resultserver] DEBUG: File upload request for memory/592-1.dmp
2017-05-23 17:52:51,451 [cuckoo.core.guest] DEBUG: Windows-7-SP1-X64-01: analysis still processing
2017-05-23 17:52:53,008 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 51292424
2017-05-23 17:52:57,086 [cuckoo.core.guest] DEBUG: Windows-7-SP1-X64-01: analysis still processing
2017-05-23 17:53:02,633 [cuckoo.core.guest] INFO: Windows-7-SP1-X64-01: analysis completed successfully
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 744, in run
    "status": "error",
TypeError: exception() got an unexpected keyword argument 'extra'

`
my system is old cuckoo that I didn't touch since 2014. so I install cuckoo from the top.
here is the system info from other error i got earlier:
Cuckoo version: 2.0.3
OS version: posix
OS release: Ubuntu 12.04 precise
Python version: 2.7.3
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0 appdirs:1.4.3 apt-xapian-index:0.44 asn1crypto:0.22.0 beautifulsoup4:4.5.3 bottle:0.10.6 bzr:2.5.1 cffi:1.10.0 chardet:2.3.0 click:6.6 colorama:0.3.7 command-not-found:0.2.44 configobj:4.7.2 cryptography:1.8.1 cuckoo:2.0.3 distorm3:3 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dnspython:1.9.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.10.1 functools32:3.2.3.post2 futures:3.1.1 gnupginterface:0.3.2 httplib2:0.7.2 httpreplay:0.2 idna:2.5 ipaddress:1.0.18 itsdangerous:0.24 jinja2:2.8 jsbeautifier:1.6.2 jsonschema:2.6.0 keyring:0.9.2 landscape-client:14.12 language-selector:0.1 launchpadlib:1.9.12 lazr.restfulclient:0.12.0 lazr.uri:1.0.3 libvirt-python:0.9.8 logbook:1.0.0 lxml:2.3.2 m2crypto:0.24.0 magic-file-extensions:0.2 mako:1.0.6 markupsafe:1.0 mastiff:0.5.0 minipdf:0.1 oauth:1.0.1 olefile:0.43 oletools:0.42 packaging:16.8 pam:0.4.2 paramiko:1.7.7.1 peepdf:0.3.4 pefile2:1.2.11 pefile:1.2.10.post139 pillow:3.2.0 pip:9.0.1 plumbum:1.6.0 psycopg2:2.7.1 py:1.4.33 pycparser:2.17 pycrypto:2.6.1 pycurl:7.19.0 pydeep:0.4 pymisp:2.4.54 pymongo:3.0.3 pynids:0.6.2 pyopenssl:17.0.0 pyparsing:2.2.0 pypcap:1.1.1 pyserial:2.5 pyshark:0.3.7.5 pysqlite:1.0.1 python-apt:0.8.3ubuntu7.3 python-dateutil:2.4.2 python-debian:0.1.21ubuntu1 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 rpyc:3.3.0 scapy:2.3.2 setuptools:35.0.2 sflock:0.2.12 simplejson:3.5.0 six:1.10.0 sqlalchemy:1.0.8 ssdeep:2.0-0.1 tlslite-ng:0.6.0 trollius:1.0.4 twisted-core:11.1.0 ufw:0.31.1.post1 unattended-upgrades:0.1 urllib3:1.21.1 virtualenv:1.7.1.2 volatility:2.6 wadllib:1.3.0 wakeonlan:0.2.2 werkzeug:0.12.2 yapsy:1.10.323 yara-python:3.2.0 yara:1.7.7 zope.interface:3.6.1

**Comment by shorlak** [comment]
solved!
Apparently that you can't write direct to /root/.cuckoo/* even if you root with tcpdump and the sniffer fail and the whole process not working well. (i'm not sure if it's because apparmor but my dmesg gave me an error about that so even when I tried to fix the apparmor rules it doesn't work.) solved when I changed the cwd of cuckoo to /root/cuckoo/.cuckoo/*.

**Comment by jbremer** [comment]
Actually what I find more interesting is as to why you're getting that ` TypeError: exception() got an unexpected keyword argument 'extra'` error, as the logging statement at that address should work just fine. Oh, Python 2.7.3 on Ubuntu 12.04.. interesting.
