### ISSUE TITLE
InetSim question

### ISSUE THREAD

**Issue by netpacket** [cuckoosandbox/cuckoo#1610]
I have InetSim setup in a FreeBSD VM.

Is there a work around patch for getting InetSim working? Or is my best option to put in iptable rules to setup InetSim network?

**Comment by doomedraven** [comment]
check inetsim2 pr

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/1435

**Comment by doomedraven** [comment]
@jbremer xD

**Comment by netpacket** [comment]
@doomedraven,

I made the changes to the cuckoo rooter.py and scheduler.py... I am getting this python error when I run the cuckoo rooter and start cuckoo with analysis:

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 360, in rooter
    cuckoo_rooter(socket, group, ifconfig, service, iptables, ip)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/rooter.py", line 365, in cuckoo_rooter
    command, addr = server.recvfrom(4096)
socket.error: [Errno 4] Interrupted system call

Cuckoo debug does not error and shows the analysis finished. Is this normal?

**Comment by doomedraven** [comment]
yup i have the same error and @jbremer doesn't like try/except solution, so at the moment you should fix your `/usr/local/lib/python2.7/dist-packages/cuckoo/apps/rooter.py` wrap `command, addr = server.recvfrom(4096)` and till the end

**Comment by netpacket** [comment]
@doomedraven 

I am not familiar with this code. 

I am looking into this post... 
https://stackoverflow.com/questions/16094618/python-socket-recv-and-signals

**Comment by doomedraven** [comment]
No, go to my profile, to repo doomedraven-cuckoo/cuckoo/apps/rooter.py replace your router in that path with cpde from my router

**Comment by netpacket** [comment]
@doomedraven 

Sorry that I miss understood your instruction. I actually have your rooter in my path... I am still getting the error. I downloaded the zip folder of your github and swapped out the original rooter for yours.

**Comment by doomedraven** [comment]
Impossible, mine is here and has try except
https://github.com/doomedraven/doomedraven-cuckoo/blob/master/cuckoo/apps/rooter.py

**Comment by netpacket** [comment]
@doomedraven 

Alright, weird. I looked your link and saw the try except line... Then, I looked at the download zip that I got. I don't have the try except line.

Looks like the copy and paste worked. Thank you for your help.

**Comment by doomedraven** [comment]
Bcz that are different repos ;)

**Comment by netpacket** [comment]
@doomedraven 

Gotcha, I get it now. Well, thanks for the fix. Everything is running smoothly.

**Comment by doomedraven** [comment]
Thanks for feedback :)

**Comment by netpacket** [comment]
@doomedraven, have you noticed an issue with cuckoo daemon and inetsim issues? Or, this is my setup issue? Just wondering.

**Comment by doomedraven** [comment]
Which issue? I dont have any

**Comment by doomedraven** [comment]
did you update sheduler when yo applied router fix? as it has 4 args
https://github.com/cuckoosandbox/cuckoo/pull/1435/files#diff-94bfe53419c7c4b5fad35952d0d1b8e0R308

**Comment by netpacket** [comment]
@doomedraven 
Yep, I took the code from that commit and put into my scheduler. I am still getting the same error. I don't really get why the cuckoo daemon breaks with InetSim but without the daemon, InetSim works perfectly. Plus, the cuckoo doesn't launch right now. 

The only strange part is that the peid file in supervisord directory is missing. I have had to relink the supervisord.conf file again, because the unix.socket was rejected in use.

**Comment by netpacket** [comment]
I don't know if this makes a huge difference but supervisorclt status:
supervisorctl status
cuckoo:cuckoo-daemon             RUNNING   pid 5124, uptime 0:17:19
cuckoo:cuckoo-process_0          RUNNING   pid 5125, uptime 0:17:19
cuckoo:cuckoo-process_1          RUNNING   pid 5128, uptime 0:17:19
cuckoo:cuckoo-process_2          RUNNING   pid 5127, uptime 0:17:19
cuckoo:cuckoo-process_3          RUNNING   pid 5126, uptime 0:17:19
distributed                      STOPPED   Not started

The log.log file looks fine as it show everything is running correctly. Could the code just not interpreted correctly? Is there any other logs to look at to deduce the cause of the issue other than the error output?

**Comment by doomedraven** [comment]
@jbremer can you merge/whatever unetsim, so user wont do copy&paste errors, im tired of help people with inetsim problems

@netpacket verify for new what code from commit and your is identical

**Comment by netpacket** [comment]
@doomedraven 

I noticed interesting problem... I noticed that cuckoo rooter still has the wrong port that resultant server port.

2017-06-05 08:07:27,109 [cuckoo.apps.rooter] ERROR: Error executing command: inetsim_enable() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/rooter.py", line 432, in cuckoo_rooter
    output = handlers[command](*args, **kwargs)
TypeError: inetsim_enable() takes exactly 4 arguments (3 given)
2017-06-05 08:07:28,263 [cuckoo.apps.rooter] DEBUG: Processing command: drop_disable 192.168.56.101 192.168.56.1 2051 

This is making the timeout issue. 

I ran a diff on the scheduler.py and commit one. They are the same except the whitespace.

**Comment by doomedraven** [comment]
no idea, it works fine for me so maybe @jbremer can solve it for you 
you should check rooter.py and scheduler.py as in that pr there 2 files modified

**Comment by netpacket** [comment]
@doomedraven 

I am looking at the code at the rooter.py. 


line 180 has the variable, machinery_iface. I looked at the forward_enable method which has three variables also. What is the machinery_iface variable supposed to store in inetsim_enable? 

I see the forward_enable method inside of the the inetsim_enable method. Does the machinery_iface need to be passed into the inetsim_enable method?

Before the cuckoo rooter threw an error earlier, the cuckoo rooter showed the destination ip address of the inetsim vm, wrong resultant server port, and the ip address of the resultant server.

**Comment by doomedraven** [comment]
it already passed

https://github.com/doomedraven/doomedraven-cuckoo/blob/3c95982491cd1c28e81a472fd448f6d6578df65d/cuckoo/apps/rooter.py#L180

https://github.com/doomedraven/doomedraven-cuckoo/blob/3c95982491cd1c28e81a472fd448f6d6578df65d/cuckoo/core/scheduler.py#L306

interface is gotten from `config("%s:%s:interface" % (self.cfg.cuckoo.machinery, self.cfg.cuckoo.machinery)),`
from your hypervisor for example `virtualbox.conf` inside of the `[virtualbox]` interface value

**Comment by netpacket** [comment]
Well, this looks like bug either with my installation or code execution. Only three parameters are being passed into this function. I would assume if the machinery_iface has some value not selected from the config files... Obvious, cuckoo confused as why its not getting an argument.

**Comment by doomedraven** [comment]
Add print and you will see it

**Comment by doomedraven** [comment]
What do you mean with cuckoo deamon? Cuckoo -d is uniq debug mode

**Comment by netpacket** [comment]
I am running Cuckoo in the background...
https://cuckoo.sh/docs/usage/start.html#cuckoo-in-the-background

This is where I am getting the same problem about missing arguments. Your inetsim fix works fine as long as I do not run cuckoo in the background.

**Comment by netpacket** [comment]
Just noticed the pidfile reappeared after linking the supervisord.conf... I don't know what the pidfile is for, but it was missing in my directory.

**Comment by doomedraven** [comment]
Maybe cuckoo restores original files as i saw something from that

**Comment by netpacket** [comment]
I would really like to run cuckoo in the background in order to put this on my production network.... However, inetsim only works with cuckoo rooter without cuckoo daemon.

**Comment by doomedraven** [comment]
I have it with supervisor and it works fine

**Comment by doomedraven** [comment]
Give a shot to this https://github.com/doomedraven/doomedraven-cuckoo is the same as upstream but with some fixes which not accepted here yet

**Comment by netpacket** [comment]
Weird. I still have issues with the supervisor. As soon as I turn off supervisor, inetsim works fine. I grabbed both of your rooter and scheduler... I wonder if I should update everything else if you've made edits.

**Comment by netpacket** [comment]
I assume there's no one else having issues with supervisor / cuckoo rooter.

**Comment by netpacket** [comment]
These are the files that I grabbed for copy/paste 
https://github.com/doomedraven/doomedraven-cuckoo/blob/master/cuckoo/apps/rooter.py

https://github.com/doomedraven/doomedraven-cuckoo/blob/3c95982491cd1c28e81a472fd448f6d6578df65d/cuckoo/core/scheduler.py

I am not getting a syntax error.

**Comment by netpacket** [comment]
Hey, did you try running the supervisor with a submission through the web interface? It seems like the command line works fine with inetsim and the supervisor. Looks like for some reason the machinery_iface is dropped or missing during execution.

**Comment by doomedraven** [comment]
for webgui you have uwsgi+nginx for correct deployment, maybe bcz as i already told cuckoo restores files as there check by hash, grab files from my fork and use it here won't help you

btw sorry i will leave you only with @jbremer for this issues as i tried to convence him for too long to merge it, but no luck

**Comment by netpacket** [comment]
Alright, thanks for your help. Yeah, I am not sure particulars of why uwsgi+ngnix are breaking your cuckoo rooter / scheduler code.

**Comment by jbremer** [comment]
The InetSim PR has been merged, please test it and provide us with feedback. Please leave your comments in #1435. If something else has been discussed in this thread that I missed, but that's important in one way or another, please reopen the issue with an additional comment or copy the comment / issue / whatever to #1435.
I'll be closing this issue now. In #1435 I'll be announcing when a new alpha or stable release is out in which you may find the InetSim working once again. Thanks again for the feedback & sorry once more for the delay on our side.
Ping @netpacket.

**Comment by jbremer** [comment]
In the meantime `2.0.4a3` has been released.
