### ISSUE TITLE
Writing a diploma on the topic of analyzing the security of files

### ISSUE THREAD

**Issue by pavgul** [cuckoosandbox/cuckoo#1613]
Hello! I'm writing a diploma on the subject of Cuckoo Sandbox, and I'm interested in some questions, such as:
1. What is the difference between installing Cuckoo on Windows, Mac OS, Ubuntu, FreeBSD.
2. And if there are differences between the installation and the scan, then in what?

**Comment by doomedraven** [comment]
RTM https://cuckoo.sh/docs/index.html

**Comment by pavgul** [comment]
Did not find the information on my question.
I need more information about how disassembling occurs, starting and compiling

**Comment by doomedraven** [comment]
i would suggest start reading the code, or here will appear someone who wants to spend a lot of time explaining it in details

**Comment by pavgul** [comment]
I do not need to explain everything, I just need to know a couple of things that I can not find on the Internet!

**Comment by Tigzy** [comment]
@pavgul I can answer your questions if you want, PM me on Twitter: @tigzyrk

**Comment by pavgul** [comment]
@Tigzy i add you, my twitter @pavgul

**Comment by jbremer** [comment]
There isn't much of a difference, except that FreeBSD isn't supported.
Cuckoo should work the same on each platform, except that on Linux you also have per-analysis network routing & perhaps a few other goodies.
Closing issue as resolved, thanks!
