### ISSUE TITLE
Oops! Cuckoo failed in an unhandled exception!

### ISSUE THREAD

**Issue by cdiaz1971** [cuckoosandbox/cuckoo#1616]
When starting cuckoo I get the following error message

`Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0-rc2
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Machine arch: x86_64
Modules: alembic:0.8.0 appdirs:1.4.3 beautifulsoup4:4.4.1 cffi:1.6.0 chardet:2.3.0 click:6.7 colorama:0.3.7 cryptography:1.3.2 distorm3:3.3.0 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 elasticsearch:2.2.0 enum34:1.0.4 flask:0.10.1 html5lib:0.999 httpreplay:0.1.17 idna:2.0 ipaddress:1.0.14 itsdangerous:0.24 jdcal:1.0 jinja2:2.8 jsbeautifier:1.5.10 lxml:3.6.0 mako:1.0.1 markupsafe:0.23 ndg-httpsclient:0.4.0 olefile:0.44 oletools:0.42 openpyxl:2.3.0 packaging:16.8 peepdf:0.3.2 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 py:1.4.31 pyasn1:0.1.8 pycparser:2.14 pycrypto:2.6.1 pymisp:2.4.49 pymongo:3.0.3 pyopenssl:0.15.1 pyparsing:2.2.0 pytest:2.8.7 python-dateutil:2.4.2 python-editor:0.3 python-magic:0.4.6 pythonaes:1.0 pytz:2014.10 requests:2.7.0 setuptools:35.0.2 six:1.9.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0a3 urllib3:1.21.1 vboxapi:1.0 volatility:2.5 wakeonlan:0.2.2 werkzeug:0.10.4 wheel:0.29.0 yara-python:3.4.0

Traceback (most recent call last):
  File "cuckoo.py", line 120, in <module>
    test=args.test)
  File "cuckoo.py", line 68, in cuckoo_init
    init_modules()
  File "/home/cesar/cuckoo/lib/cuckoo/core/startup.py", line 215, in init_modules
    import modules.signatures
  File "/home/cesar/cuckoo/modules/signatures/__init__.py", line 5, in <module>
    from . import android, cross, darwin, extractor, network, windows
  File "/home/cesar/cuckoo/modules/signatures/windows/__init__.py", line 8, in <module>
    __file__, "windows", globals(), dict(platform="windows")
  File "/home/cesar/cuckoo/modules/signatures/compat.py", line 22, in enumerate_signatures
    g, Signature, attributes
  File "/home/cesar/cuckoo/lib/cuckoo/core/plugins.py", line 42, in enumerate_plugins
    importlib.import_module("%s.%s" % (module_prefix, module_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cesar/cuckoo/modules/signatures/windows/powershell_reg.py", line 12, in <module>
    from cuckoo.misc import cwd
ImportError: No module named misc`

I followed the installation steps in [https://downloads.cuckoosandbox.org/docs/index.html](url) but I am obviously missing something.  Any assistance is greatly appreciated.

Thanks

**Comment by jbremer** [comment]
That was quick, heh, this was a mistake from my side from yesterday :-) I've updated the Community, so if you re-run `./utils/community.py -waf` everything will work again. Please also note that we've released a couple of more recent Cuckoo versions - check our blog for more information!

**Comment by cdiaz1971** [comment]
That worked.  Thanks!

**Comment by PHKKAR** [comment]
I am getting the same error , please some one help me ! i tried following all steps
" 2019-08-19 19:20:25,159 [cuckoo] ERROR: IOError: [Errno 13] Permission denied: '/opt/cuckoo/pidfiles/cuckoo.pid'
