### ISSUE TITLE
Couldn't connect to vSphere host

### ISSUE THREAD

**Issue by Nagaev** [cuckoosandbox/cuckoo#1620]
Hi,

I'm currently configuring Cuckoo (latest cuckoo-modified, 1.3-NG) on vSphere ESXi servers. Since the full memory dump feature is not supported with esx machinery, I decided to use the vsphere one. However I have a strange problem : I can reach the server management address from my Cuckoo machine with esx://<IP>/?no_verify=1 in esx.conf and with my browser. However in vsphere.conf, I get a CuckooCriticalError : Couldn't connect to vSphere host. Here is the interesting part of my vsphere.conf : 

```
host = <ESXmanagementIP>
port = 443
user = root
pwd = (password)
unverified_ssl = on
```
Do you have any idea about this problem? 

Thank's

**Comment by doomedraven** [comment]
wrong repo, this is not  `cuckoo-modified, 1.3-NG` repo xD

**Comment by Waffles-2** [comment]
Here you go: https://github.com/spender-sandbox/cuckoo-modified

Note: 

> As of 4/26/2017 I'm handing this repo off to others to fork and continue if they wish. Thanks to doomedraven, KillerInstinct, kevross33, SeanKim77, jgajek, keithjjones, pashashocky, Shane-Carr, seanthegeek, garanews, and all the other contributors I forgot to mention.

**Comment by doomedraven** [comment]
btw check https://github.com/spender-sandbox/cuckoo-modified/issues/455#issuecomment-305454200
