### ISSUE TITLE
Peepdf version conflict on a brand new install

### ISSUE THREAD

**Issue by mvdnes** [cuckoosandbox/cuckoo#1635]
When currently doing a `pip install cuckoo` in a brand new environment I get the following error:

    pkg_resources.ContextualVersionConflict: (peepdf 0.3.4 (/home/cuckoo/venv/lib/python2.7/site-packages), Requirement.parse('peepdf==0.3.5'), set(['sflock']))

After installing `peepdf==0.3.5`:

    pkg_resources.DistributionNotFound: The 'peepdf==0.3.4' distribution was not found and is required by Cuckoo

The current solution is to manually install `sflock==0.2.12`, so that they both require peepdf 0.3.4.

**Comment by jbremer** [comment]
Thanks for reporting! Should be resolved now (see also the commit above) by reinstalling Cuckoo. If for some reason the `peepdf` or `sflock` dependency remains problematic in your setup, also try `pip install -UI cuckoo` rather than just `pip install -U cuckoo`. Closing as resolved!
