### ISSUE TITLE
URLs table in static analysis table is not working as expected when a PDF contains multiple URLs 

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#1640]
A PDF sample (a3da7add39a57998066d83fb9ad2c95dc6d57cd2902f2c20b13050e85cc67308) contains two URLs. For some reason, the Static Analysis page has a separate URLs table for each URL, and the submit URLs button only works for the first table.

Both URLs should be in one table.

I submitted this analysis via the feedback system. Fee free to share the PDF sample for testing. It is not targeted, and is available on VirusTotal. 

![Screenshot of issue](https://i.imgur.com/2lCN9ck.png)

**Comment by jbremer** [comment]
This should be resolved in the commit above. To be included in a release nearby.

**Comment by seanthegeek** [comment]
That was fast!
