### ISSUE TITLE
Cuckoo.py doesn't exist

### ISSUE THREAD

**Issue by anushthakalia** [cuckoosandbox/cuckoo#1658]
After installing all the dependencies and setting up the Virtual machine, when I run cuckoo -d, it says
"command not found".
I have also tried it doing via python cuckoo.py, but no such file exists.Also, I couldn't find anything relevant in the documentation.
I have Ubuntu 15.04 running as host, Python 2.7.9 and installed cuckoo 2.0.3 along with all its dependencies.

**Comment by netpacket** [comment]
I don't particulars super well for your setup... I would try to install the latest version Cuckoo on 16.04. It seems to work fine.

**Comment by anushthakalia** [comment]
Thanks.
After running install cuckoo via pip solved the problem.
