### ISSUE TITLE
Failed to run the processing module "Memory" for task #6:

### ISSUE THREAD

**Issue by nakagit** [cuckoosandbox/cuckoo#1661]
I encountered following error:

Failed to run the processing module "Memory" for task #6: 
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/core/plugins.py", line 238, in process
 data = current.run() 
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/memory.py", line 1118, in run 
    return VolatilityManager(self.memory_path, osprofile).run()
   File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/memory.py", line 1000, in __init__
     self.vol = VolatilityAPI(self.memfile, self.osprofile) 
    File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/memory.py", line 79, in __init__
     self.init_config() 
     File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.3-py2.7.egg/cuckoo/processing/memory.py", line 150, in init_config
     self.addr_space = utils.load_as(self.config) 
    File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error 
AddrSpaceError: No suitable address space mapping found 
Tried to open image as: 
MachOAddressSpace: mac: need base 
LimeAddressSpace: lime: need base 
WindowsHiberFileSpace32: No base Address Space 
WindowsCrashDumpSpace64BitMap: No base Address Space 
WindowsCrashDumpSpace64: No base Address Space 
HPAKAddressSpace: No base Address Space 
VirtualBoxCoreDumpElf64: No base Address Space 
VMWareMetaAddressSpace: No base Address Space 
VMWareAddressSpace: No base Address Space 
QemuCoreDumpElf: No base Address Space 
WindowsCrashDumpSpace32: No base Address Space 
Win10AMD64PagedMemory: No base Address Space 
WindowsAMD64PagedMemory: No base Address Space 
LinuxAMD64PagedMemory: No base Address Space 
AMD64PagedMemory: No base Address Space 
IA32PagedMemoryPae: No base Address Space 
IA32PagedMemory: No base Address Space 
OSXPmemELF: No base Address Space 
MachOAddressSpace: MachO Header signature invalid 
LimeAddressSpace: Invalid Lime header signature 
WindowsHiberFileSpace32: No xpress signature found 
WindowsCrashDumpSpace64BitMap: Header signature invalid 
WindowsCrashDumpSpace64: Header signature invalid 
HPAKAddressSpace: Invalid magic found 
VirtualBoxCoreDumpElf64: ELF error: did not find any PT_NOTE segment with VBCORE VMWareMetaAddressSpace: VMware metadata file is not available 
VMWareAddressSpace: Invalid VMware signature: 0x464c457f 
QemuCoreDumpElf: ELF error: did not find any PT_NOTE segment with CORE WindowsCrashDumpSpace32: Header signature invalid 
Win10AMD64PagedMemory: Incompatible profile Win7SP1x86 selected WindowsAMD64PagedMemory: Incompatible profile Win7SP1x86 selected LinuxAMD64PagedMemory: Incompatible profile Win7SP1x86 selected 
AMD64PagedMemory: Incompatible profile Win7SP1x86 selected 
IA32PagedMemoryPae: Failed valid Address Space check 
IA32PagedMemory: Failed valid Address Space check 
OSXPmemELF: No PT_LOAD segments found 
FileAddressSpace: Must be first Address Space 
ArmAddressSpace: Profile does not have valid Address Space check 

My environment is:
Cuckoo: 2.0.3
Volatility: 2.6 (Profile=WIn7SP1x86)
Machine:  Virtualbox

When I ran, "vol.py -f memory.dmp --profile Win7SP1x86 imageinfo", it looked fine, as following:
# volatility -f ./memory.dmp --profile Win7SP1x86 imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win7SP1x86_23418, Win7SP0x86, Win7SP1x86 (Instantiated with Win7SP1x86)
                     AS Layer1 : FileAddressSpace (/root/.cuckoo/storage/analyses/6/memory.dmp)
                      PAE type : No PAE
                           DTB : 0x185000L
                          KDBG : 0x2963150L
          Number of Processors : 0
     Image Type (Service Pack) : -
             KUSER_SHARED_DATA : 0xffdf0000L

Please let me know, you'd like to know my environment and configurations.

Any ideas or comments to fix are appreciate. 
Thanks in advance,
naka

**Comment by nakagit** [comment]
I found a workaround. That's to install the previous version, volatility 2.5.
http://downloads.volatilityfoundation.org/releases/2.5/volatility-2.5.zip

**Comment by pielco11** [comment]
I had the same problem and solved in the same way. But now cuckoo's stuck at `2017-06-22 19:04:39,790 [cuckoo.processing.memory] DEBUG: Executing volatility 'pslist' module.` and I'm having high CPU usage.
