### ISSUE TITLE
Cuckoo skipping tasks

### ISSUE THREAD

**Issue by anushthakalia** [cuckoosandbox/cuckoo#1662]
On running the following:
`$ cuckoo submit --url google.com`
Cuckoo returns with 
`Skipped: URL "google.com" as it has already been analyzed`
I have tried the same with other URLs and also with malware exes, but cuckoo returns the same output.
I have Ubuntu 15.04, with cuckoo 2.0.3 
Before running this command for the first time, I had also executed the command `$ cuckoo community`.

**Comment by jbremer** [comment]
I think there's something wrong with your database setup which incorrectly prints out the results you've provided above. Can you run `cuckoo -d submit -u google.com`?

**Comment by anushthakalia** [comment]
Thanks.
Running the command with `sudo` makes cuckoo accept the task.

**Comment by jbremer** [comment]
Yes, so the real reason is that the `sqlite3` database is probably `root`-owned now ;-)
You shouldn't need to run Cuckoo as root.
