### ISSUE TITLE
Hello, It's just about curiosity...but help me..

### ISSUE THREAD

**Issue by KeenCat** [cuckoosandbox/cuckoo#1663]
Hi, there. Thank you for making awesome tools.

I analyzed malware file and when I read the reports.json, in network section, there are 'time' keys for every packets.
For example, udp has offset, time, dstip,...etc..  I guessed that time is for timestamp when packet is arrived(or sent), but its value is sometimes less than 0.
Can you tell me why it happens?

**Comment by jbremer** [comment]
Hi, that might indicate a bug. Do you have some screenshots and/or can you share the analysis? Thanks!

**Comment by jbremer** [comment]
Based on checking the code, I think this should work correctly. Please re-open this issue if you have an analysis or PCAP where we can reproduce this issue. Thanks!
