### ISSUE TITLE
Distribute _markerlib incompatibility / Yara-Python license files

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#1664]
Having trouble installing Cuckoo in Ubuntu 17.

I have Python 2.x installed and am in a Python 2.x virtual environment...

```
sudo -H pip2 install virtualenv
#sudo apt-fast -y install python-virtualenv
virtualenv cuckoo_ve
. cuckoo_ve/bin/activate
```

...get an error mid-install likely related to an [incompatibility with recent versions of setuptools and distribute](https://github.com/pypa/setuptools/issues/535), but not clear on that.

```
  Running setup.py bdist_wheel for distribute: finished with status 'error'
  Complete output from command /home/pass/cuckoo_ve/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-B0S17b/distribute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpfsLZoZpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-B0S17b/distribute/setup.py", line 58, in <module>
      setuptools.setup(**setup_params)
    File "/usr/lib/python2.7/distutils/core.py", line 137, in setup
      ok = dist.parse_command_line()
    File "setuptools/dist.py", line 276, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "setuptools/dist.py", line 602, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "setuptools/dist.py", line 406, in get_command_class
      ep.require(installer=self.fetch_build_egg)
    File "pkg_resources.py", line 2254, in require
      working_set.resolve(self.dist.requires(self.extras),env,installer)))
    File "pkg_resources.py", line 2471, in requires
      dm = self._dep_map
    File "pkg_resources.py", line 2682, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "pkg_resources.py", line 2699, in _compute_dependencies
      from _markerlib import compile as compile_marker
  ImportError: No module named _markerlib
```

Distribute seems to be somewhat dated at this point, is it still a critical requirement? I think the distribute requirement may come from androguard, which I think may be unsupported currently anyway,

**Comment by jbremer** [comment]
Yes, good find. This was resolved in 716d1fd41acba971b5e8d21693abb3c27af746ef and https://github.com/jbremer/androguard/commit/f6c140faa0b8be7eb5c442854eb29fd5d055085d. You may find said change applied in `2.0.4a2`. Once we release `2.0.4` this should be resolved completely :-)
I think we can close this, but I'll let it open for additional feedback for now.

**Comment by Kolano** [comment]
OK, that does seemed to have resolved the _markerlib problem. But it also looks like the Yara-Python was bumped up to 3.6.1. Both it, and the prior 3.6.0 release have a problem referencing their license files and don't build properly. Refer [yara-python error: [Errno 2] No such file or directory: 'LICENSE'](https://github.com/VirusTotal/yara/issues/683).

**Comment by jbremer** [comment]
Yes, you're correct - I had been meaning to report the `LICENSE` bug, but it's not a critical bug as far as I've seen. To be honest, we're happy to after all these years be able to ship Yara with Cuckoo by default (I can assure this was not an option earlier). For your information, `3.5.0` doesn't build properly on Windows (nor did `3.6.0`, but `3.6.1` works mostly miracles).

**Comment by Kolano** [comment]
Yara-python was updated to address the license issue today...
https://github.com/VirusTotal/yara-python/commit/21821a39e8ccd5cfe925156eb6404805cdd5ec54

Unclear how long before that makes it into a release build though, since 3.6.1 still seems to be the last release.

**Comment by jbremer** [comment]
Yeah, I'll be bumping to the next version once the `LICENSE` file fix has been included.. Closing issue for now. Will ping the Yara guys.
