### ISSUE TITLE
Sandbox is evaded by On Close macros

### ISSUE THREAD

**Issue by Maurotb** [cuckoosandbox/cuckoo#1669]
Version: 2.0.4a2
Terminate_processes = yes

I have make a sample word file with macro, on end it create a .ps file ,launch powershell and display a msgbox.
When analisys terminate, cuckoo terminate word but my macro is not executed.
If i manually close word on my sandbox, the macro run and cuckoo intercept file creation and powershell launch.

I attach my word file

[test.zip](https://github.com/cuckoosandbox/cuckoo/files/1091849/test.zip)

**Comment by jbremer** [comment]
Thanks, we were actually looking into this as we're speaking. Hope to include an update regarding this in a next release.

**Comment by jbremer** [comment]
Support for this has been included in our `2.0.4a3` release. Please upgrade and give it a try :-) I'm going to close this issue, but let us know any feedback that you have.
(And yes, I'll be looking at your VM-related issues soon'ish).

**Comment by Maurotb** [comment]
Hi,
i have upgraded to 2.0.4a3 but problem persist :(

**Comment by Maurotb** [comment]
pussible /venv/bin/python /venv/bin/cuckoo -d community is my problem?

**Comment by Maurotb** [comment]
resolved.
i need to delete all content of /home/cuckoo/.cuckoo except  /home/cuckoo/.cuckoo/conf and
/home/cuckoo/.cuckoo/web , relaunch cuckoo to recopy analyzer etc and run /venv/bin/python /venv/bin/cuckoo -d
now work

**Comment by jbremer** [comment]
@Maurotb how long is your analysis timeout? The new functionality only kicks in after ~60 seconds.

**Comment by Maurotb** [comment]
Hi,
i have resolved my problem as my previous post
thanks
