### ISSUE TITLE
Behavior log too big

### ISSUE THREAD

**Issue by netpacket** [cuckoosandbox/cuckoo#1677]
Is there a way set the size of the behavior log? I searched the config files. I got a program installing more drivers causing the Error: Behavior log file '2828.bson' is too big, skipped.

**Comment by doomedraven** [comment]
replace your mongo.py with this one https://github.com/doomedraven/doomedraven-cuckoo/blob/master/cuckoo/reporting/mongodb.py

i have replaced/backported it from cuckoo-mod to v2

**Comment by netpacket** [comment]
@doomedraven 
I'll take a look at that. Thanks!

**Comment by doomedraven** [comment]
you are welcome

**Comment by Nwinternights** [comment]
@doomedraven the link gives 404 .

**Comment by doomedraven** [comment]
correct i wiped public access to that repo, it was open for few month, but not now


[mongodb.txt](https://github.com/cuckoosandbox/cuckoo/files/1231671/mongodb.txt)
change ext to .py

**Comment by Nwinternights** [comment]
it worked!!! tks @doomedraven

**Comment by doomedraven** [comment]
you are welcome :)

**Comment by Nwinternights** [comment]
@doomedraven if you take a look on the sample I gave it, try to submit with timeout more than 100 u'll have that error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 599, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 290, in run
    child_key, csize = self.debug_dict_size(report[parent_key])[0]
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 28, in debug_dict_size
    totals = dict((k, 0) for k in dct)
TypeError: unhashable type: 'dict'

sounds like pefile issue https://github.com/spender-sandbox/cuckoo-modified/issues/196

**Comment by doomedraven** [comment]
could be, put there some debugging line and/or try except to see what si it to know exactly, but maybe that is set([]) from some custom module, from my exp

**Comment by Nwinternights** [comment]
Yep, I ll do some tests tomorrow and let u know!
Regards
