### ISSUE TITLE
Install the host and guess machine in separate virtual machine.

### ISSUE THREAD

**Issue by tUn4** [cuckoosandbox/cuckoo#1683]
Hi,
i couldn't find any information about this.
i want to know that can i install host machine (VM1) in a virtual machine and guess in an other one (VM2)?
In VM1 i'll install cuckoo sanbox and i'll create serveral virtual machine (eg: win7) in VM2, can the cuckoo sanbox in VM1 snapshot, poweroff the guess machine (win7) in VM2? 
In this case, i think it's not Physical Machine case.

**Comment by doomedraven** [comment]
no, this question was responded a lot of times in issues, cuckoo is not designed to work in this way

**Comment by jbremer** [comment]
Well, you can do it for VM machineries that work over the network, e.g., ESXi/vSphere/XenServer. Not for regular VirtualBox or VMWare.

**Comment by tUn4** [comment]
@jbremer : could you show me how to do that or point me out to document for that?

**Comment by jbremer** [comment]
Configure the VMs and configure Cuckoo to point to the ESXi/vSphere/XenServer API..
There are docs on all of that ;-)

**Comment by tUn4** [comment]
@jbremer : i've just seen this: https://wiki.fogproject.org/wiki/index.php?title=Installation#Virtualization
is that what you mean?
