### ISSUE TITLE
Submitting dlls to cuckoo with arguments

### ISSUE THREAD

**Issue by Waffles-2** [cuckoosandbox/cuckoo#1684]
So I have a dll called "xxx.dll" and for it to work it must be ran like this otherwise it will not work:

`rundll32.exe xxx.dll, #1`

How would I go about submitting this sample to cuckoo so that it runs? I have looked through the docs and can see information on this but I can't get it to work.

**Comment by jbremer** [comment]
To run petya, just do `cuckoo submit -o function='#1' --package dll sample` ;-) Note the single quotes around the `#1` as otherwise bash will cut 'em off.

**Comment by Waffles-2** [comment]
Haha glad you knew what I was trying to run, fed up with static analysis! Ok I shall give that a go! Thank you!

**Comment by jbremer** [comment]
Closing as resolved :)
