### ISSUE TITLE
Cuckoo that's not compatible with this signature error

### ISSUE THREAD

**Issue by fahrettinf89** [cuckoosandbox/cuckoo#1685]
Hi there.
I have freshly installed cuckoo 2.0.3 with pip. I have one vm on virtualbox and vm's os is xp. 

I have  "**You are running a version of Cuckoo that's not compatible with this signature (either it's too old or too new): cuckoo=2.0.3 signature=powerworm minversion=2.0.4 maxversion=None**" error.

but cuckoo start with "-d" option normally. It loads vm normally with no error. Any help??

**Comment by doomedraven** [comment]
rtm

**Comment by jbremer** [comment]
It's fine. Some newer Signatures will only work once we release the next version, i.e., `2.0.4`. As the comment says it's simply too new ;-) Closing as resolved.
