### ISSUE TITLE
GUI Submit parameters

### ISSUE THREAD

**Issue by mpvillafranca** [cuckoosandbox/cuckoo#1686]
Hi, I'm trying to submit a dll which I need to pass a diferent parameter than DllMain and can't find how I can specify that with the submit gui. I supose it's in the options field but can't get it right. I also would like to know how I can add paramaterers to an exe file.

So, for example:

```
rundll32 mydll.dll,MyEntryPoint
myexe.exe --extract aaa
```

Hope you can help.

Thanks in advance

**Comment by jbremer** [comment]
On the command-line you can submit petya with `cuckoo submit mydll.dll -o function='#1' --package dll` (note the single quotes to prevent bash from interpreting the `#1` part). An executable with arguments may be done as follows; `cuckoo submit myexe.exe --arguments "--extract aaa"`.
We still need to some additional work in the Web Interface to make this fully work, I think.

**Comment by mpvillafranca** [comment]
Great! Yes, I was submitting samples with the terminal alternative but I think it could be a nice feature having that option also in the webui, as we have cuckoo runing on a different server and have to ssh into it each time I want to do it...

Thank you.

**Comment by jbremer** [comment]
There's also the Cuckoo API if you want to automate it. Closing issue as resolved. Let us know if you have additional feedback or questions. Thanks!
