### ISSUE TITLE
err_whitelist_ends in auxiliary/sniffer.py is not complete

### ISSUE THREAD

**Issue by drsmithization** [cuckoosandbox/cuckoo#1692]
tcpdump can print "1 packet received by filter" (captured/dropped). When it happens sniffer.py throws `CuckooOperationalError`:

```2017-07-04 17:36:13,113 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
...
CuckooOperationalError: Potential error while running tcpdump, did not expect the following standard error output: '1 packet received by filter'.```

**Comment by osh2ep** [comment]
After configuring **tcpdump** as documentation, no more error :)

```
sudo aa-disable /usr/sbin/tcpdump
sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
```

**Comment by jbremer** [comment]
@drsmithization Thanks for the feedback. Could you please share more information on your version of Cuckoo as well as a complete log file? :-)

**Comment by jbremer** [comment]
Please find the commit above which should fix the issue presented in this issue :-) To be released soon!

**Comment by jbremer** [comment]
Included in our latest release - closing issue as resolved.
