### ISSUE TITLE
SortCap fails on [almost] empty pcap files

### ISSUE THREAD

**Issue by drsmithization** [cuckoosandbox/cuckoo#1693]
If tcpdump doesn't capture any packet, tcpdump won't write an empty .pcap file. dump.pcap will be 24 bytes in size:
```
$ xxd cap.pcap
00000000: d4c3 b2a1 0200 0400 0000 0000 0000 0000  ................
00000010: 0000 0400 0100 0000                      ........
```
(see `pcap_hdr_s` in [Libpcap File Format](https://wiki.wireshark.org/Development/LibpcapFileFormat))

This leads to the situation when SortCap is trying to call `self.f.close` and `f` is `None`:
```
Failed to run the processing module "NetworkAnalysis" for task #31:
Traceback (most recent call last):
  File "/opt/cuckoo/current/cuckoo/core/plugins.py", line 240, in process
    data = current.run()
  File "/opt/cuckoo/current/cuckoo/processing/network.py", line 883, in run
    sort_pcap(self.pcap_path, sorted_path)
  File "/opt/cuckoo/current/cuckoo/processing/network.py", line 1025, in sort_pcap
    inc, outpath, lambda path: SortCap(path, linktype=inc.linktype)
  File "/opt/cuckoo/current/cuckoo/processing/network.py", line 963, in batch_sort
    output_file.close()
  File "/opt/cuckoo/current/cuckoo/processing/network.py", line 997, in close
    self.f.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by osh2ep** [comment]
Try patching by this commit

[https://github.com/jbremer/cuckoo/commit/d17cb01afaf060cebba61fd005f326d99ced6a18](https://github.com/jbremer/cuckoo/commit/d17cb01afaf060cebba61fd005f326d99ced6a18)

**Comment by jbremer** [comment]
What @osh2ep said! This will be featured in the next alpha or stable release. Closing this issue as resolved (although you're getting a traceback, it isn't all that critical - in fact, the problem most likely lies elsewhere if you're in this scenario where no traffic has been seen).
