### ISSUE TITLE
Cuckoo Feedback server has SSL verification problems

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#1706]
When I tried to submit feedback this morning, I got this error message:

> Invalid response from Cuckoo feedback server: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by jbremer** [comment]
Updated letsencrypt, thanks! Let me put the dates for next time in my agenda :)
