### ISSUE TITLE
Urgent: Cuckoo Mongodb Server Connection Issue

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1711]
Hello guys,

I am facing issue while running the "cuckoo" command or "cuckoo web runserver" command in terminal it's showing following error:

[cuckoo.common.mongo] WARNING: We're attempting to connect to MongoDB, but the connection seems slow or MongoDB is simply offline. Please wait while Cuckoo tries to connect..
CuckooCriticalError: Unable to connect to MongoDB: 127.0.0.1:27017: [Errno 111] Connection refused. In order to operate Cuckoo as per your configuration, a running MongoDB server is required.

I have also tried to change the port to 8000 in mongodb config and and cuckoo --> reporting.conf but still I am facing the same error.
.
Kindly tell me the solution asap please
.
Thanks & Regards
Sean

**Comment by seantree** [comment]
Kindly closed this issue I solved this case

**Comment by jbremer** [comment]
;-)
