### ISSUE TITLE
Parallel analysis problem

### ISSUE THREAD

**Issue by bryannn7** [cuckoosandbox/cuckoo#1727]
I am trying to run parallel analysis on cuckoo. When I start cuckoo, it says that 2  machines are loaded which is right. However, when I perform an analysis, only one machine starts. Why is this so?

My configurations are as attached.

[vbconf.txt](https://github.com/cuckoosandbox/cuckoo/files/1167120/vbconf.txt)
[terminal.txt](https://github.com/cuckoosandbox/cuckoo/files/1167121/terminal.txt)

As shown above only win7 starts even though two machines are loaded.

**Comment by SparkyNZL** [comment]
Hi Bryannn7,

Are you submitting 2 samples at the same time ? if you are just submitting 1 and then waitng for it to complete and these submitting the next, the it will also default to the 1st machine, if you submit 2 samples at the same time both machines should spin up.

How are you submitting the samples are they in the CLI or WGUI ?

CHeers

**Comment by bryannn7** [comment]
Hi SparkyNZL,

I am submitting the samples in the CLI via the terminal
Thanks for your help, I will try it out!
