### ISSUE TITLE
DHCP not enabled problem in Windows7 virtualbox

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1730]
Hi, 

I am facing the problem when I am running cuckoo sandbox and submitting the sample through the browser my machine is not contacting with the sandbox windows machine says DHCP is not enabled, suddenly I don't know from where I got this error I tried again to execute the IP forward commands which is given in the following link:
https://precisionsec.com/virtualbox-host-only-network-cuckoo-sandbox-0-4-2/

Please help me it's urgent

**Comment by doomedraven** [comment]
they should have static ip, how you want to configure the virtualbox.conf? without static ips

**Comment by seantree** [comment]
Hi @doomedraven 
VM have static IP's : 192.168.56.101

Netmask:255.255.255.0
Default Gateway:192.168.56.1

Primary DNS:8.8.8.8
These are my Windows Clone Internet Settings
and I am wondering is there any way to configure the cuckoo on NAT?  Because it's showing me DHCP not enabled problem in my Windows7 Clone.
.
Thanks
Seantree

**Comment by doomedraven** [comment]
dhcp not enabled bcz you using static ips, so not make sense to use dhcp, about nat read the documentation is not suggested way to setup network, review your windows network settings, as if that is static and in standalone it should works just fine

**Comment by seantree** [comment]
Ok Thanks 
Kindly close this issue... problem has been resolved

**Comment by jbremer** [comment]
Ok :)
