### ISSUE TITLE
What happens when you enable cwd?

### ISSUE THREAD

**Issue by gbdavidx** [cuckoosandbox/cuckoo#1731]
I am doing the following (though its not working)
$ virtualenv venv
$ . venv/bin/activate
(venv)$ pip install -U pip setuptools
(venv)$ pip install -U cuckoo
(venv)$ cuckoo --cwd ~/.cuckoo

when i now go into the conf folder, i only have cuckoo, physical, routing, vsphere and xenserver.conf other configuration files don't get copied over and cuckoo wont start

error: cuckoostarterror: config file does not exist at path: /home/david/.cuckoo/conf

**Comment by Hullgj** [comment]
On first run of cuckoo sandbox you need to run
`$ cuckoo -d`

This sets up the default configuration, then you can modify the default settings where required and
start Cuckoo again (by running `cuckoo` or `cuckoo -d`.

Please refer to this page of the installation: 
http://docs.cuckoosandbox.org/en/latest/installation/host/cwd/

**Comment by jbremer** [comment]
That sounds very odd. All related Cuckoo files should be copied over. Can you provide more logs?

**Comment by jbremer** [comment]
Closing issue for lack of additional information. Please reopen if you still have questions ;-)
