### ISSUE TITLE
iptables rules between host and guest

### ISSUE THREAD

**Issue by cheantik** [cuckoosandbox/cuckoo#1741]
Hello.
My question is what type connections should be allowed for cuckoo between result server (host) and vm (windows guest)?
Right now I know two types of connections - TCP 8000 OUTPUT (to guest) and TCP 2042 INPUT (from guest)
Is where are any connections what should be allow?
P.S. All iptables rules mentioned here
http://docs.cuckoosandbox.org/en/latest/installation/host/routing/#simple-global-routing
are also keeped in mind

**Comment by jbremer** [comment]
That's pretty much it for regular Cuckoo usage :-) Indeed there are a couple of per-analysis network routes that may be applied for additional / specific network routing possibilities. Does this answer your question?

**Comment by cheantik** [comment]
@jbremer 
Not exactly but thanks
I mean "service" cuckoo connections betwen cuckoo server and cuckoo agent
I have two accept iptables rules 
INPUT TCP to server with destination port 8000
and
INPUT TCP to guest with destination port 2042
And ofcource RELATED,ESTABLISHED ......:)
And now cuckoo works with no errors such as "guest not ready yet" and etc wich happens because cuckoo server can`t communicate with agent
Maybe it will be usefull for somebody
