### ISSUE TITLE
Documentation discrepancy

### ISSUE THREAD

**Issue by flyingdan** [cuckoosandbox/cuckoo#1744]
In the Requirements section at [https://downloads.cuckoosandbox.org/docs/installation/host/requirements.html](https://downloads.cuckoosandbox.org/docs/installation/host/requirements.html) the instructions say:

> In order to properly function, Cuckoo requires some dependencies. They can all be installed through PyPI like this:
> `$ sudo pip install -r requirements.txt`

But there are no instruction on where to get the _requirements.txt_ file or which Python libraries need to be installed.

In the [requirements.rst file](https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/installation/host/requirements.rst) there is no mention of this step. Which guide should be followed for installation and which libraries need to be installed?

Thanks!

**Comment by doomedraven** [comment]
you dont' need it anymore, just do `pip install cuckoo` and it will install everything for you :)

**Comment by flyingdan** [comment]
Good to know, thanks for the quick reply.

Is the website source code available on git for editing? I'd be willing to make the updates needed to point new users to the correct docs.

Cheers!

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/tree/master/docs

**Comment by jbremer** [comment]
Yes - thanks. We still have to update the original documentation.. :-)

**Comment by jbremer** [comment]
The new website points to up-to-date Cuckoo documentation, closing issue as resolved.
