### ISSUE TITLE
Mac Guest OS

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1749]
Hello Guys,

I want to analyze the mac malware samples on the cuckoo sandbox, is there any way to do that?
Thanks in advance
Seantree

**Comment by jbremer** [comment]
Yes, we have macosx/darwing analysis. This is not one of our better maintained items, but people have reported to us that it still works pretty well.

**Comment by seantree** [comment]
Oh Great @jbremer,
Could you please tell me the way is there any specific config is available for that.

**Comment by jbremer** [comment]
Not that I'm aware of. Just follow our documentation and setup a Mac OS X Guest etc. Closing issue.
