### ISSUE TITLE
 i have given this cmd in ubuntu terminal svn checkout http://yara-project.googlecode.com/svn/trunk/yara

### ISSUE THREAD

**Issue by karikalansaitechnology** [cuckoosandbox/cuckoo#1756]
i have given this cmd in ubuntu terminal svn checkout http://yara-project.googlecode.com/svn/trunk/yara
and i could not fetch below this how to resolve this 
svn: E160013: Unable to connect to a repository at URL 'http://yara-project.googlecode.com/svn/trunk/yara'
svn: E160013: '/svn/trunk/yara' path not found

**Comment by doomedraven** [comment]
why you executing that command? googlecode is dead

**Comment by jbremer** [comment]
Yeah, no need to install Yara from Google Code. A simple `pip install yara-python`, which Cuckoo does for you nowadays, should suffice.

**Comment by jbremer** [comment]
Closing as resolved.

**Comment by hlckalana** [comment]
@jbremer ,

Answer is correct it is worked for me.
