### ISSUE TITLE
Virustotal at the beggining

### ISSUE THREAD

**Issue by TrueDanko** [cuckoosandbox/cuckoo#1757]
HI!

Is it possible to change the logic of the cuckoo so that the virustotal is at the beginning, and if viruses are not detected, cuckoo begins to perform other actions?
i want to built automatic system, because sandboxing takes a long time. Expected about 300 analyzes per hour

**Comment by jbremer** [comment]
As mentioned the easiest to do is doing this manually - before you submit things to Cuckoo. This request is not a trivial change in Cuckoo ;-) Or you can just buy some more hardware, 300 an hour isn't so much really. Closing as resolved.

**Comment by TrueDanko** [comment]
thank you for advice!

Sent with [ProtonMail](https://protonmail.com) Secure Email.
