### ISSUE TITLE
Analysis doesn't work unless I choose a specific timeout value

### ISSUE THREAD

**Issue by Phenomanan** [cuckoosandbox/cuckoo#1760]
So this is a weird issue. If I upload a file/URL, and hit submit with all the default options, I get this output from cuckoo -d:
[cuckoo.core.guest] DEBUG: CuckooServer: not ready yet
[cuckoo.core.guest] DEBUG: CuckooServer: not ready yet
[cuckoo.core.guest] DEBUG: CuckooServer: not ready yet
 ... etc...
[cuckoo.core.scheduler] ERROR: Error from machine 'CuckooServer': it appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest...

HOWEVER, if I simply choose a time (I could literally just click on 120 seconds, which is the default choice anyway) the analysis works properly. This workaround also works via API, if I specify a "timeout" option, the analysis works, otherwise it keeps saying "not ready yet". I am using cuckoo 2.0.3. Is this issue fixed in later versions? If not, I might need to just quick fix this myself. Where in the scripts does it parse the default values?

**Comment by jbremer** [comment]
Ehm, that sounds odd & interesting. We'll have to investigate that.. thanks!

**Comment by jbremer** [comment]
Not sure how to investigate this. Could you please provide additional information @Phenomanan or did you perhaps already resolve the issue in the meanwhile? Thanks!

**Comment by Phenomanan** [comment]
@jbremer I only witnessed this issue when I was trying to get Cuckoo set up on RHEL. Somehow whenever I chose a specific timeout value, the analysis would start quickly, but if I let it just go with the default, it would fail to connect... I've never experienced this on my Ubuntu VM and at this point I've killed my RHEL unit ¯\_(ツ)_/¯. There were a host of issues on RHEL though, so I wouldnt' worry about it if the plan is to only support Ubuntu.

Thanks

**Comment by jbremer** [comment]
Alright, great. Yeah, we have no interest to support RHEL at this point as we'd have to reimplement support for a number of features (adding lots of maintenance work etc). Closing as resolved then, thanks!
