### ISSUE TITLE
VMs Internet access

### ISSUE THREAD

**Issue by norgalades** [cuckoosandbox/cuckoo#1761]
Hi, I used cuckoo for a while without providing the VMs any Internet access and everything worked fine. Now I would like to give my VM full Internet access but it seems that cuckoo is not giving back the replies. 

I have configured the VM to be part of a Host-Only network with this characteristics: 
IP address: 192.168.56.101
Default Gateway: 192.168.56.1
Dns resolver: 8.8.8.8

I also changed the routing.conf file so that:
route = internet
internet  = eth0
rt_table = main 

Has anybody an idea why I cannot access internet from the guest VM?

**Comment by tr4cefl0w** [comment]
You only have access to the internal virtual network when using host-only.

> the virtual machines cannot talk to the world outside the host since they are not connected to a physical networking interface

https://www.virtualbox.org/manual/ch06.html#network_hostonly

**Comment by norgalades** [comment]
Maybe I misunderstood cuckoo's Internet routing option. 

My understanding of this option is that by enabling the internet routing in rounting.conf you are telling cuckoo that it has to use the specified interface (for example eth0) as dirty line to enable the VMs talk with the "external world" even if they are not directly or virtually connected to the "external world". 

So at the end the VMs will be able to connect to Internet by means of the host. 
Where am I wrong? Do I have to add a network adapter in order to complete this setup?

**Comment by norgalades** [comment]
@jbremer is it normal that my VM is not receiving the replies or is there some mistake in the way I configured the internet access?

**Comment by tr4cefl0w** [comment]
You need a second interface if you want to use it as dirty line.

**Comment by norgalades** [comment]
Ok @tr4cefl0w , can you please be more precise on how to configure this second interface and make cuckoo understand that it has to use it as  a dirty line?

**Comment by norgalades** [comment]
Ok guys, I'm really confused at this point... 

From cuckoo's documentation (section Simple Global Routing) I read: 

"In the following setup we’re assuming that the interface assigned to our VirtualBox VM is vboxnet0, the IP address of our VM is 192.168.56.101 (in a /24 subnet), and that the outgoing interface connected to the internet is eth0. **With such a setup**, the following iptables rules will allow the **VMs access to the Cuckoo host machine (192.168.56.1 in this setup) as well as the entire internet** as you would expect from any application connecting to the internet."

So I assume that in order to have my VMs access the internet I just have to setup the Host-Only network with the proper IPs and then the cuckoo instance will take care of route the traffic through Internet. It seems that there is no need for other interfaces to be configured on the VMs (even if theoretically speaking a Host-Only network only allows communication among machines in vboxnet0). 

When I read the comments on routing.conf file (which if I understood correctly should be modified only if you want Per-Analysis routing) I got confused because of this: 

"# Default network routing mode if none is specified by the user.
**# In none mode we don't do any special routing - the VM doesn't have any
# network access** (this has been the default actually for quite a while) aside
# from the subnet it exists in.
# In internet mode by default all the VMs will be routed through the network
# interface configured below (the "dirty line")."

From these lines it seems that the "none" configuration does not provide internet access. 

So at this point: what do I have to do if I want my VMs to communicate with the Internet? Can somebody help me by explaining where I'm wrong? Please help.

**Comment by razuz** [comment]
@norgalades do you have cuckoo rooter up and running ?

**Comment by norgalades** [comment]
@razuz Hi, how can I check it? I just lunched cuckoo from cuckoo's user so I supposed it was enough. But regarding the configuration? Which of the two I mentioned above is the correct one? I tried both and in both cases my VMs are not able to access the internet... Something wrong, I don't know what. Any help is really appreciated

**Comment by norgalades** [comment]
I have started the rooter with the command sudo cuckoo rooter -g cuckoo. Still not able to connect to internet

**Comment by razuz** [comment]
basically you should be able to run that with root or sudo: 
cuckoo --cwd [your $CWD] rooter

I created a systemd init to boot it up on start : 
```
[Unit]
Description=Cuckoo Rooter
After=network.target

[Service]
Type=simple
Restart=on-failure
StandardOutput=tty
ExecStart=/usr/local/bin/cuckoo --cwd /home/cuckoo/cwd rooter
WorkingDirectory=/home/cuckoo/cwd

[Install]
WantedBy=multi-user.target
```

after that you should be able to see it in ```ps auxf|grep rooter```

bare in mind that you have to enable forward aswell atm ... ```echo 1 > /proc/sys/net/ipv4/ip_forward   ```

**Comment by norgalades** [comment]
@razuz I've already tried all this... I've added the ip tables rules, I've enabled the forward, I've checked the configuration of my VMs... So the only thing now is that the idea behind cuckoo's network configuration is wrong. The Host-Only network interface is not sufficient. I will try by adding a bridged adapter to the virtual network card of my VMs. But do you know if I also have to modify cuckoo's config file? I read about this "dirty line" configuration but it seems that nobody is using it so there is really few documentation...

**Comment by doomedraven** [comment]
can you provide log from router when you start analysis to see if the iptables is applied correctly?

**Comment by razuz** [comment]
well yea ... then see aswell if you vbox interface gets all the traffic or not and if it gets passed along ... if vbox interface gets traffic then validate iptables config altho' rooter should take care of that

**Comment by norgalades** [comment]
Ok, and what about routing.conf? Since I'm not using the per-analysis routing can I leave the "none" option or do I have to modify this file?

**Comment by norgalades** [comment]
It's working... It was a network issue in the ip_tables. Just for the sake of completeness I will summarize the configuration below so that other users with same issue can use it: 

**If you want to connect the VMs controlled by cuckoo's sandbox to Internet:** 

Virtualbox Host-Only network: vboxnet0 IP: 192.168.56.0/24
Configure the VMs so that they belong to this network, i.e.

First machine (just an example): 
Static IP 192.168.56.101
DNS - any DNS server (8.8.8.8)
Default Gateway - 192.168.56.1

Second machine: Static IP 192.168.56.102 etc...

Then configure the **host** with the IP address: 192.168.56.1
Add the following IP tables rules by paying really a lot of attention to the interfaces (modify them according to your system): 
iptables -A FORWARD -o eth0 -i vboxnet0 -s 192.168.56.0/24 -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A POSTROUTING -t nat -j MASQUERADE

And then to enable ip forward: 
echo 1 > /proc/sys/net/ipv4/ip_forward

You can leave the routing.conf file untouched (with the "none" option). You don't need any additional network adapter on your virtualbox machines. It is the cuckoo engine that will take care of forwarding packets towards the Internet. 

Good luck ;) And thank you @razuz and @doomedraven.

**Comment by razuz** [comment]
kind of odd tho' that the rooter didn't fix the iptables for you with ```route = internet``` I know that ip_forward issue will remain with rooter, however I'll PR that fix soon.
But glad you worked it out tho'

**Comment by razuz** [comment]
while you gave network via iptables already then you can leave none there as there is no effect.

However my routing.conf looks like that right now : 
```
[routing]
drop = no
route = internet
rt_table = main
auto_rt = yes
internet = ens160
```

and I created a patch #1802 which will make rooter to flip ip_forward value aswell ... so in theory if routing.conf is correct, you bring up rooter and then boot up cuckoo - it should work without additional hacks
