### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by EuByudgHj2Z4bPpPD1gI** [cuckoosandbox/cuckoo#1763]
I have noticed that recent versions of cuckoo (rc1 onwards) does not contain a requirements.txt in the root directory of cuckoo. Has this been moved somewhere else?

**Comment by EuByudgHj2Z4bPpPD1gI** [comment]
I've just noticed Setup.py includes the requirements needed without the requirements.txt. Just out of curiousity was there any reason why this was implimented instead of a requirements.txt file?

**Comment by doomedraven** [comment]
To make setup more easier
