### ISSUE TITLE
mysql cannot connect

### ISSUE THREAD

**Issue by weiqiangdragonite** [cuckoosandbox/cuckoo#1764]
I set the sql connection to mysql, but cuckoo  report error
```
 Cuckoo Sandbox 2.0.3
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

CuckooDatabaseError: Unable to create or connect to database: (_mysql_exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")

```

I find my mysql sock location is on  /home/xxxx/mysql/mysql.sock , and I dont want to chang this socket location. Can I set the cuckoo where to find the mysql socket?

**Comment by jbremer** [comment]
Just make a symlink from one to another, e.g., `ln -s /home/xxx/mysql/mysql.sock /var/lib/mysql/mysql.sock` (after making sure that the related directories exist).

**Comment by weiqiangdragonite** [comment]
ok，i got it，thx ;)
