### ISSUE TITLE
Prescript & Postscript

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1765]
Hello Team,

First of all Thank you for creating the wonderful sandbox,  I just need few help to make cuckoo sandbox better, Below is the 1 Questions it would be very helpful for me if you guide my proper.

1. Is there any way to execute my own created postscript in windows 7 guest machine before the cuckoo turn off the vm machine because cuckoo sandbox (agent.py) poweroff the machine after predefined time. I Just want to execute my own script that will gather some additional information and add it to my db.
.
I am waiting for the positive feedback.
.
Thanks & Regards
Seantree

**Comment by jbremer** [comment]
Sure, just implement a Guest Auxiliary module. There are plenty of examples that should help you in our code base ;-)

**Comment by seantree** [comment]
Hi @jbremer ,

Are you talking about auxiliary conf file?

Thanks & Regards
Seantree

**Comment by RicoVZ** [comment]
Not the auxiliary file. There are modules (Guest Auxiliary) that are executed in the VM during the analysis.

The modules can be found in this folder: https://github.com/cuckoosandbox/cuckoo/tree/master/cuckoo/data/analyzer/windows/modules/auxiliary

If you implement one of these, you could execute your own code.

You said you want to gather additional information. If you want to upload anything from the VM to Cuckoo, you can use the same method as displayed in the screenshot Guest Auxiliary module. Like so: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/analyzer/windows/modules/auxiliary/screenshots.py#L77-L83

**Comment by jbremer** [comment]
What @RicoVZ said. Closing issue as this is certainly possible and without further information we can't do much with the issue anyway.
