### ISSUE TITLE
Is there any Way to make cuckoo wait before executing sample.

### ISSUE THREAD

**Issue by uppusaikiran** [cuckoosandbox/cuckoo#1775]
I have been working on this cuckoo for my malware detonation. I want the cuckoo to stay idle for say 5 min before actually start executing the sample. So within the 5 minutes I wanted to do some operation on the system.

Is there any timeout option which can configure to make cuckoo wait for that timeout seconds before actually executing the sample or starting it's job.

**Comment by jbremer** [comment]
You'll have to write your own Guest Auxiliary module. Please take a look at the existing ones to see what you have to do ;-)
