### ISSUE TITLE
IRP Logger

### ISSUE THREAD

**Issue by bnder321** [cuckoosandbox/cuckoo#1776]
Hi Everybody,
Currently I am working on Ransomware analysis using available cuckoo modules and I wonder if cuckoo has built-in IRP logger? and if not, is there any  IRP logger that could be integrated into cuckoo?

Thanks in advance.

**Comment by shellbombs** [comment]
you can write an auxiliary module to start IRP logger before the ransomware sample start.

**Comment by jbremer** [comment]
We're working on this for our upcoming zer0m0n release. If you have any requests on that topic, please let us know (reopen this issue or reach out to us directly). Closing this issue in the meanwhile. Thanks!
