### ISSUE TITLE
Cuckoo Rooter

### ISSUE THREAD

**Issue by MigliS** [cuckoosandbox/cuckoo#1777]
Hi there!

I've got a problem with starting the Cuckoo Rooter.
The error message is the following:

CuckooStartupError: The rooter is required but we can't connect to it as the rooter is no actually running.

I followed the instructions in the documentation, but it didn't help me...

Kind regards
Michael

**Comment by doomedraven** [comment]
`cuckoo -d rooter --sudo`

**Comment by MigliS** [comment]
Dear doomedraven,
this leads me to the same error. 
Maybe I made a mistake with changing the CWD.

**Comment by doomedraven** [comment]
at least you cold post some logs, versions etc etc as without nothing nobody can help more

**Comment by MigliS** [comment]
There aren't really logs, I'm sorry for that but I could tell you the steps I make.

Cuckoo Version 2.0.3

I start cuckoo with 
``sudo cuckoo -d --cwd /opt/cuckoo``

Then the error message appears and says that the Cuckoo Rooter is required blabla...
After that I tried to start the Rooter with your command but nothing happens there.
The command seems to load something and if I hit CTRL+C it says 

> Aborting the Cuckoo Rooter

**Comment by doomedraven** [comment]
that is your fail, rooter should be started first, as cuckoo says it requires rooter

**Comment by MigliS** [comment]
So I need to let a terminal open in which the cuckoo rooter runs? 
Am I understanding this right?

**Comment by doomedraven** [comment]
in one terminal you first start rooter, and second terminal/tab you run the cuckoo

**Comment by Nwinternights** [comment]
use separate screens One for rooter One for cuckoo. Get into rooter screen and start It, deatch, then work on cuckoo screen.

**Comment by MigliS** [comment]
Thank you it worked!
