### ISSUE TITLE
why the analysis report score is not the same

### ISSUE THREAD

**Issue by weiqiangdragonite** [cuckoosandbox/cuckoo#1780]
I sent the same urls to cuckoo to analyse, but their result score is not the same, 

id|time|-|url|status|score
-- | -- | -- | -- | -- | --
131 | 2017-08-15 21:20 | - | http://www.right.com.cn/forum/portal.php | reported | score: 2
130 | 2017-08-15 21:18 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
129 | 2017-08-15 21:15 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
128 | 2017-08-15 21:13 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
127 | 2017-08-15 21:11 | - | http://www.right.com.cn/forum/portal.php | reported | score: 2.4
126 | 2017-08-15 21:08 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
125 | 2017-08-15 21:05 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
124 | 2017-08-15 21:02 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
123 | 2017-08-15 20:41 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1.8
122 | 2017-08-15 20:39 | - | http://www.right.com.cn/forum/portal.php | reported | score: 2
121 | 2017-08-15 20:37 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
120 | 2017-08-15 20:34 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
119 | 2017-08-15 20:30 | - | http://www.right.com.cn/forum/portal.php | reported | score: 2
118 | 2017-08-15 20:28 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1.8
117 | 2017-08-15 20:26 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
116 | 2017-08-15 20:23 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1.8
115 | 2017-08-15 20:21 | - | http://www.right.com.cn/forum/portal.php | reported | score: 2
114 | 2017-08-15 20:18 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
113 | 2017-08-15 20:16 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
112 | 2017-08-15 20:13 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
111 | 2017-08-15 19:54 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
110 | 2017-08-15 19:45 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1.8
109 | 2017-08-15 19:42 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
108 | 2017-08-15 19:40 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
107 | 2017-08-15 19:36 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1
106 | 2017-08-15 19:30 | - | http://www.right.com.cn/forum/portal.php | reported | score: 1.8

why their scores is not the same, anyone can tell me? thx

**Comment by jbremer** [comment]
Can you see which Signatures were triggered in the different analyses?

**Comment by jbremer** [comment]
Closing for lack of additionally provided information. Yes, we're aware that sometimes more or less Signatures are hit, but this isn't always the fault of Cuckoo.
