### ISSUE TITLE
Generating report 

### ISSUE THREAD

**Issue by git45113** [cuckoosandbox/cuckoo#1782]
hi,
I'm using cuckoo 2.0-dev with the web UI on virtual machine using ubuntu desktop.
I started the server with the script "cuckoo.py" and the web server with "manage.py"

I want to see a report of the files that I'm submitting. can't find a way to do this..

**Comment by hayward6** [comment]
Have you looked at the results in the web UI? Thats all I ever use. Over on the left side you can drill down. You could also just find the reports in the analysis folder though.

**Comment by norgalades** [comment]
@git45113 Why not looking at $CWD/storage/analyses/ ?? You should find here a directory per each analysis you run named according to the analysis number at submission time.

**Comment by jbremer** [comment]
The above should provide the required information. Please also upgrade to latest and greatest releases (`2.0.x`). Closing issue as resolved.
