### ISSUE TITLE
Add www.msftncsi.com to whitelist

### ISSUE THREAD

**Issue by chrisdoman** [cuckoosandbox/cuckoo#1785]
Hi,

 I'm getting lots of traffic to the MS FQDN www.msftncsi.com on win7 hosts.
 Other subdomains are whitelisted but not that one.

Thanks,

**Comment by Nwinternights** [comment]
You Can Simply disabile Active probing on guests HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\NlaSvc\Parameters\Internet
Double-click on EnableActiveProbing and change its value from 1 to 0. Reboot  and then take a snapshot

**Comment by SparkyNZL** [comment]
or if you didnt do this in a load of vms (cough) you can just add it to the whilelist called domain.txt which is located in /usr/local/lib/python2.7/dist-packages/cuckoo/data-private/whitelist

keep in mind when you upgrade cuckoo you will need to re-edit this and add the domains again, i tend to keep another copy which i just copy back after an update :)

**Comment by chrisdoman** [comment]
Yup I added it to domains.txt - thanks :) 

Might want to add it to domains.txt as standard for everyone, or disable it as part of the vmcloak standard build.

**Comment by jbremer** [comment]
I've added it to the whitelist. Closing issue as resolved. Thanks!
