### ISSUE TITLE
missed "tcpdmp" caption on sniffer.py

### ISSUE THREAD

**Issue by uvkruvi** [cuckoosandbox/cuckoo#1790]
im running cuckoo sandbox over ubuntu (both agent and host).
not sure if this is an issue just for linux, but sometimes sniffer module crash uppon stopping.
after digging around, i found out that this happens when the pcap file contain only one packet.
to solve this need to add another string to array "err_whitelist_ends" on sniffer.py (line 114).
need to add "packet captured". (the already existing phrase is plural "packets captured").

**Comment by jbremer** [comment]
Not sure how you'd end up with a PCAP that has only one packet, but I suppose we can add support for this. Thanks for reporting!

**Comment by jbremer** [comment]
Interestingly there was a duplicate issue, #1692. Closing this issue as resolved, please see also e6ec8c425478a4fdcf047f45fb334ff5d8f57642 and our `2.0.4` release. Thanks!
