### ISSUE TITLE
Cuckoo rooter and physical machine

### ISSUE THREAD

**Issue by sxu55** [cuckoosandbox/cuckoo#1792]
I tried to deploy a physical guest machine. Can it also take the advantage of the Cuckoo Rooter (like Tor or Inetsim)?

**Comment by doomedraven** [comment]
no

**Comment by sxu55** [comment]
Since my physical machine has two ethernet adapters, can I configure them so that the communications to the cuckoo host go through one adapter, and other (malware) internet traffics go through the other? (In such case, I can cloak one adapter to avoid exposing my IP)

**Comment by sxu55** [comment]
I've tried the rooter, seems the Tor is working, dirty line also works :)
