### ISSUE TITLE
*.msg and *.eml files

### ISSUE THREAD

**Issue by MigliS** [cuckoosandbox/cuckoo#1795]
Hi! Another one from me...
How can I implement the analyzer packages for *.msg & *.eml files.
In the cuckoo community setup these packages already were implemented.

kind regards

**Comment by doomedraven** [comment]
RTM https://cuckoo.sh/docs/customization/packages.html#getting-started

**Comment by MigliS** [comment]
Thank you!
But there's anothter issue. Should I open a new one?

**Comment by doomedraven** [comment]
without providing details no idea

**Comment by jbremer** [comment]
IMO there's not really a use-case for `.msg` / `.eml` analysis packages. You're only interested in URLs or attachments in those files anyway, right?

**Comment by MigliS** [comment]
@doomedraven It's about the Tor routing..
@jbremer Correct.

**Comment by doomedraven** [comment]
open

**Comment by MigliS** [comment]
If I try to analyze *.eml files, cuckoo gives an error.

`cuckoo1: analysis caught an exception`
`Traceback (most recent call last):`
  `File "C:\tmprhhaew\analyzer.py", line 789, in <module>`
    `success = analyzer.run()`
  `File "C:\tmprhhaew\analyzer.py", line 577, in run`
    `"not exist.".format(package_name))`
`CuckooError: Unable to import package "modules.packages.None", does not exist`

I've installed Microsoft Office with MS Word, Excel, PowerPoint and Outlook. Word, Excel and PowerPoint work properly expect Outlook.
