### ISSUE TITLE
Tor routing not working correctly

### ISSUE THREAD

**Issue by MigliS** [cuckoosandbox/cuckoo#1796]
The next problem is the tor routing. 
I configured everythin as said in the documentation.
Cuckoo Rooter logs show the line `tor_enable` & `tor_disable`.
I made an analysis via **None Routing** and **Tor Routing**. The score of the first analysis had the same value like the second one.

**Comment by doomedraven** [comment]
and why that is the problem lol? :D

that is vm exit, nothing else

**Comment by MigliS** [comment]
The funny thing is, in cuckoo community the score of a tor analysis was much higher than a normal analysis. That's why I am confused a bit.
Even though the score is very low. One analysis with a malicious link only reached a score of 0.4 and imo this is too low.
Is there anything I can change?

**Comment by doomedraven** [comment]
>> I made an analysis via None Routing and Tor Routing. The score of the first analysis had the same value like the second one.

you told it was the same, see signature detected in both analysis they should be different then if you saying the value is different

Write/change community signature to your needs.

**Comment by MigliS** [comment]
Okay thanks! I saw it now.
Where can I find the community signature?

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox

**Comment by SparkyNZL** [comment]
I was just about to say contact Doomedraven ! :)
