### ISSUE TITLE
"current virtual machine"

### ISSUE THREAD

**Issue by hayward6** [cuckoosandbox/cuckoo#1798]
Just a quick question. I want to setup multiple target machines running different operating systems as well as patch levels. Where do I put those different IP addresses? Or do I need to edit this config each time? I see a place to add the naming ie cuckoo, cuckoo2, etc. and a place to add those machines, but the ip of each?

.101 is the ip of cuckoo1

`# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101
`

**Comment by doomedraven** [comment]
RTM! https://cuckoo.sh/docs/index.html

**Comment by hayward6** [comment]
Thanks, I have become quite intimate with the manual. I have read it, printed it, and read it again in my free time to become as familiar with it as possible. I am just confused in the default structure section. I will power through it though, thanks...

**Comment by doomedraven** [comment]
Check you machinery config, it has example inside, so replicate that for many s with different names and ips, done

**Comment by hayward6** [comment]
Not sure the documentation properly explains my config files...

I have this as cuckoo1 but then below I have other settings such as vlan, snapshot, etc. Do I need to go all the way to the bottom to add another machine? Or do I only need these three configurations? You know what, let me go ahead and test some things.

`[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = cuckoo1

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101`

**Comment by hayward6** [comment]
Ok, it really was as simple as it looked... Thank you! I just added the three settings in the config for the new machine and its working fine. I can now choose which machine to use. I was confused because then all the other settings like snapshot name, etc become default for each box, which I guess is ok.
