### ISSUE TITLE
 Error getting access to process: 5!

### ISSUE THREAD

**Issue by sxu55** [cuckoosandbox/cuckoo#1799]
In my physical guest machine, cuckoo 2.0.3 generates " Error getting access to process: 5!" upon running the sample. My physical guest machine is windows 7 x64 + deep freeze, and I've double checked that I've got UAC off and agent run in admin (pythonw is elevated). I've seen people reporting similar issue (#1310), just wondering if this will be resolved sometime?

**Comment by sxu55** [comment]
just commented out that error prompt in the src and replaced the is32bit.exe binary... Hopefully some better solution will appear in the future.

**Comment by jbremer** [comment]
In our `2.0.4` release we slightly simplified this exact scenario, please try it again after upgrading! There's still one or two things that we have to fix to make Cuckoo work without Administrator access, though.

**Comment by sxu55** [comment]
Seems the new binary works. Thanks for the fix!
