### ISSUE TITLE
How do i make multilanguage cuckoo web?

### ISSUE THREAD

**Issue by gz0m** [cuckoosandbox/cuckoo#1800]
Hello!
How do i make multilanguage cuckoo web?

$CWD/web/local_settings.py
------------------------------------
# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
#LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "fr-FR"

For example i need change english UI to french.

**Comment by jbremer** [comment]
We don't support multiple languages at the moment and aren't interested to do so at this point either. It'd just add a *lot* of maintenance / UI / UX / etc work. Closing issue as wontfix. Thanks!
If you're **really** interested in this, then the only way this feature will get in Cuckoo & remain maintained is if somebody is paying for it ;-)
