### ISSUE TITLE
Incorrect OS has been specified - volatility

### ISSUE THREAD

**Issue by norgalades** [cuckoosandbox/cuckoo#1803]
Hi guys, I'm having troubles using volatility on cuckoo. I use virtualbox with a Windows 7 machine. I've run volatility on the memory dump to get the right profile but it is not working. I'm also trying all possible profiles for my VM but none of them seems to be good for cuckoo. I've also tried to leave it empty. Any suggestion? 

**This is the error I'm getting:** 

[cuckoo.processing.memory] ERROR: Error running Volatility on machine 'win7': An incorrect OS has been specified for this machine! Please provide the correct one or Cuckoo won't be able to provide Volatility-based results for analyses with this VM.
 [cuckoo.core.plugins] DEBUG: Executed processing module "Memory" on analysis at "/home/cuckoo/.cuckoo/storage/analyses/18"

Thank you all.

**Comment by doomedraven** [comment]
first of all which profile do you specify?
second one, execute on dump `vol.py -f memory.dmp imageinfo` will tell you which profile to use

**Comment by norgalades** [comment]
I've already lunched this command and I've got this output: 

Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
Suggested Profile(s) : Win7SP1x86_23418, Win7SP0x86, Win7SP1x86
                     AS Layer1 : IA32PagedMemoryPae (Kernel AS)
                     AS Layer2 : VirtualBoxCoreDumpElf64 (Unnamed AS)
                     AS Layer3 : FileAddressSpace (/home/cuckoo/.cuckoo/storage/analyses/18/memory.dmp)
                     PAE type : PAE
                     DTB : 0x185000L
                     KDBG : 0x8296fc68L
                     Number of Processors : 1
                     Image Type (Service Pack) : 1
                     KPCR for CPU 0 : 0x82970d00L
                     KUSER_SHARED_DATA : 0xffdf0000L

So I've tried with the above mentioned profiles: Win7SP1x86_23418, Win7SP0x86, Win7SP1x86

**Comment by doomedraven** [comment]
well if that doesn't work then issue not make any sense %)
try it in terminal with `--profile X malfind` for example

**Comment by norgalades** [comment]
I've tried Win7SP1x86_23418 with pslist and it worked... So i really don't know why cuckoo is complaining. I've just changed the memory.conf file. Do I have to specify other configuration option somewhere?

**Comment by doomedraven** [comment]
if you have many different vms with different SP or win versions
is better to specify in your vm manager config `osprofile`

**Comment by norgalades** [comment]
For now I have only one virtual machine. 

But I have the profile set also there in virtualbox.conf for the win7 machine and it's still giving me this issue. :(

**Comment by doomedraven** [comment]
can you provide as much info as possible? like cuckoo version, debug log from processing etc etc so maybe issue is somewhere there but without everything is difficult to spot

**Comment by norgalades** [comment]
Cuckoo Sandbox 2.0.3
You should find the files here: 

[cuckoo_files.zip](https://github.com/cuckoosandbox/cuckoo/files/1248962/cuckoo_files.zip)

**Comment by doomedraven** [comment]
can you post vbox and memory configs? logs looks ok

**Comment by norgalades** [comment]
[conf.zip](https://github.com/cuckoosandbox/cuckoo/files/1249010/conf.zip)

**Comment by doomedraven** [comment]
why do you specify 3 profiles where should be only one?

`osprofile = Win7SP1x86_23418, Win7SP0x86, Win7SP1x86` ?

**Comment by doomedraven** [comment]
and in memory

`guest_profile = Win7SP0x64, Win7SP0x86, Win7SP1x64, Win7SP1x64_23418, Win7SP1x86, Win7SP1x86_23418`

that is your issue

>> I've tried Win7SP1x86_23418 with pslist and it worked

so specify that one only in all configs

**Comment by norgalades** [comment]
Sorry my bad, it was not working so I started messing up everything by trying all possible options. 

It's working now. The first time I didn't set up osprofile in virtualbox.conf.

**Comment by norgalades** [comment]
Thank you @doomedraven. I'm closing the issue.

**Comment by doomedraven** [comment]
you are welcome, in future when reporting some issues, provide as much info as you can it saves a lot of time for people who trying to help ;)
