### ISSUE TITLE
Get report detail informations 

### ISSUE THREAD

**Issue by norgalades** [cuckoosandbox/cuckoo#1804]
Hi everybody, I'm trying to get a report which is more detailed as possible. For example, if I get: 

-Malfind detects one or more injected processes
How can I know which are these injected processes? Or: 

-PEB modified to hide loaded modules. Dll very likely not loaded by LoadLibrary
How can I retrieve the suspicious dll? 

Basically I would like to enable a sort of verbose form for the report to get the name of these processes. Please help

**Comment by norgalades** [comment]
"Starting from version 1.2, signatures are able to log exactly what triggered the signature." Where is this logged? 

If I look at the bson files inside my logs folder I'm not able to see anything (hooked functions of monitored processes, details about triggered signatures etc...). Is this an error at my side?

**Comment by doomedraven** [comment]
looks like is your side error,
but it better read report.json than bsons directly
read manual how to write signatures, and you will can log whatever you need

**Comment by norgalades** [comment]
@doomedraven but if I want the details about what triggered a particular signature (for example I want to know which are the processes found by malfind) where do I have to look for? I'm not able to find in the documentation any reference to this. 

I just found this: 

**Marks & Helpers**
Starting from version 1.2, signatures are able to log exactly what triggered the signature. This allows users to better understand why this signature is present in the log, and to be able to better focus malware analysis.

For examples on marks and helpers please refer to the Cuckoo Community for now - until we write some thorough up-to-date documentation on that.

**Comment by doomedraven** [comment]
if you have enabled memory in `processing.conf`, and malfind  in `memory.conf` if not enabled, there you will get this results

https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/processing/memory.py#L544
if you missing something, is easy to extend and that will be in json/mongo report/etc so you can write signature to process that data 

in webgui you will have `vm memory processing` and in reports you can see

```
"malfind": {
            "data": [
                {
                    "process_id": 488,
                    "process_name": "lsass.exe",
                    "vad_start": "0x170000",
                    "vad_tag": "VadS"
                },
                {
                    "process_id": 488,
                    "process_name": "lsass.exe",
                    "vad_start": "0x190000",
                    "vad_tag": "VadS"
                },
                {
                    "process_id": 488,
                    "process_name": "lsass.exe",
                    "vad_start": "0x180000",
                    "vad_tag": "VadS"
                },
                {
```

**Comment by norgalades** [comment]
Yes, right. I had an issue generating the json. Just restarted everything and now is working. Thank you @doomedraven .

**Comment by doomedraven** [comment]
you are welcome, if solved, close ;)
