### ISSUE TITLE
*.msg files

### ISSUE THREAD

**Issue by MigliS** [cuckoosandbox/cuckoo#1810]
If I try to analyze *.eml files, cuckoo gives an error.

` [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception`
`Traceback (most recent call last):`
  `File "C:\tmp6pyyki\analyzer.py", line 784, in <module>`
    `success = analyzer.run()` 
  `File "C:\tmp6pyyki\analyzer.py", line 572, in run`
    `"not exist.".format(package_name))`
`CuckooError: Unable to import package "modules.packages.None", does not exist.`

I've installed Microsoft Office with MS Word, Excel, PowerPoint and Outlook. Word, Excel and PowerPoint work properly expect Outlook.

**Comment by jbremer** [comment]
Please submit the `.eml` file to the Cuckoo Web Interface so that it can extract attachments from it, which it can then analyze. Simply opening an email in the VM seems pointless to me.

**Comment by MigliS** [comment]
Cuckoo isn't able to get out links in an email. Is that true?
To check emails for links is extremely significant in our environment. So there's no possibilty to checks those "malicious" links...

**Comment by doomedraven** [comment]
if you care about something what is not handled on cuckoo side you have 2 options:
1. handle it before submit to cuckoo and submit what you extracted/interested in
2. extend cuckoo to do what you need :P

**Comment by jbremer** [comment]
We have plans to develop pretty much what you just mentioned, but we can only focus on so many things at once and for some of us it also depends on what clients want ;-)

**Comment by MigliS** [comment]
Okay, so I'm going to close this task.
Hope you'll implement this feature soon. I will work with the spender-sandbox until there's the new feature.
