### ISSUE TITLE
Include documentation for IPTables configuration for default cuckoo.

### ISSUE THREAD

**Issue by EuByudgHj2Z4bPpPD1gI** [cuckoosandbox/cuckoo#1813]
Currently Cuckoo has documentation for setting up iptables for `Simple Global Routing ` but no rules for a default cuckoo installation without internet access. Would it be possible for documentation to include a version of IPTables rules that includes the agent, vboxnet0 but no access to the internet as a best practice?

Many Thanks

**Comment by doomedraven** [comment]
it's not required, just specify none in route per analysis, in routing.conf and done
