### ISSUE TITLE
Automatic URLs submission to VirusTotal

### ISSUE THREAD

**Issue by norgalades** [cuckoosandbox/cuckoo#1814]
Hi everybody, 

is there a way to automatically submit URLs found by the string processing module to VirusTotal or do I have to write my own signature to do that? In the second case, is it correct/compliant with cuckoo's philosophy to write a new signature that works on the output of strings? 

Thank you for the help.

**Comment by doomedraven** [comment]
no, you should modify vt module for that

**Comment by norgalades** [comment]
But in order to query vt with the found URLs, I need the result from another processing module (strings). How can I be sure that strings will be lunched before the virustotal module? Is there a predefined order in which modules are run?

**Comment by doomedraven** [comment]
read the documentation :)
it order number

**Comment by jbremer** [comment]
Did you make any progress here? Seems like a silly idea as the processing module might find a ton of URLs. If not I'll close this issue, as this isn't something we're especially interested in developing - for the reason above. Thanks!

**Comment by jbremer** [comment]
Doing as mentioned in my last comment. Feel free to create a PR or provide feedback on the matter.
