### ISSUE TITLE
urls getting mangled when submitting via ui

### ISSUE THREAD

**Issue by threathive** [cuckoosandbox/cuckoo#1822]
![screenshot from 2017-09-06 15-56-26](https://user-images.githubusercontent.com/26552841/30138232-fa27bc48-931b-11e7-8638-0798b30ba3b6.png)
 
Using the 2.0.4 latest release I am seeing that urls such as http://ipinfo.io that once being replaced with hxxp://ipinfo.io are now being replaced with the http:&#x2F;&#x2F;ipinfo.io . This is breaking url submissions via the ui. I tested via the command line and it still works as expected. So I suspect some JS is screwing this up.

**Comment by jbremer** [comment]
That's correct! This will be fixed in a few hours (awaiting @automagisch).

**Comment by jbremer** [comment]
Resolved now as part of `2.0.4.4`, please `pip install -U cuckoo` once more! Thanks for reporting.
