### ISSUE TITLE
Development with the Python Package

### ISSUE THREAD

**Issue by rainkin1993** [cuckoosandbox/cuckoo#1828]
Hi I want to clone the cuckoo project and do some developments.

I clone the git by this command: 
`https://github.com/cuckoosandbox/cuckoo.git`

After running the commands in the following tutorial:
http://docs.cuckoosandbox.org/en/latest/development/package/

I run the command `cuckoo -d` and get this error:

IOError: [Errno 2] No such file or directory: '/home/myname/Documents/cuckoo/cuckoo/data-private/.cwd'

And I try to install cuckoo from source code by running this command `python setup.py install`
But I still get the same error.

Thanks

**Comment by jbremer** [comment]
You're correct - I had to change this for the `2.0.4` release as there were some issues popping up and didn't think of this. Will see if there's a better workaround, but for now you can run `python setup.py sdist install` or `python setup.py sdist develop` and it should work. Perhaps that's fine as-is to be included in our documentation.

**Comment by jbremer** [comment]
Updated docs as stated above - will have to do for now. Thanks. Closing as resolved.
