### ISSUE TITLE
coun't open url(bing.com,163.com...)

### ISSUE THREAD

**Issue by zhaoyaochen** [cuckoosandbox/cuckoo#1834]
[www.163.com.zip](https://github.com/cuckoosandbox/cuckoo/files/1295369/www.163.com.zip)

i'm analysis www.163.com ; this is result. i find vm coun't open this url from shots.

i'm used  simple global Routing like this https://cuckoo.sh/docs/installation/host/routing.html#simple-global-routing 

this is normal? or i have some trouble configuration?

**Comment by zhaoyaochen** [comment]
this zip file, i'm removed memory dump files

**Comment by jbremer** [comment]
No analysis was shared, but ehm, probably an internet connectivity issue yes.

**Comment by zhaoyaochen** [comment]
@jbremer i has run this is command：
sudo iptables -t nat -A POSTROUTING -o enp1s0 -s 192.168.56.0/24 -j MASQUERADE
sudo iptables -P FORWARD DROP
sudo iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -s 192.168.56.0/24 -j ACCEPT
sudo iptables -A FORWARD -s 192.168.56.0/24 -d 192.168.56.0/24 -j ACCEPT
sudo iptables -A FORWARD -j LOG
echo 1 | sudo tee -a /proc/sys/net/ipv4/ip_forward
sudo sysctl -w net.ipv4.ip_forward=1

then, how i sure netwrok is normal?
i has test this command:  ping -I vboxnet0 www.baidu.com
but i couldn't get response.

this is iptables rules:
cuckoo@cuckoo:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  192.168.56.0/24      anywhere            
ACCEPT     all  --  192.168.56.0/24      192.168.56.0/24     
LOG        all  --  anywhere             anywhere             LOG level warning

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by seantree** [comment]
can you please share iptables rules for mac os sierra 10.12?

**Comment by zhaoyaochen** [comment]
i'm used mtr check it and success configuration this
