### ISSUE TITLE
Routing options greyed out

### ISSUE THREAD

**Issue by arnydo** [cuckoosandbox/cuckoo#1846]
I have setup inetsim and turned on Cuckoo Rooter but the routing options are still greyed out when submitting files.

Is there something that I am missing?

I have restarted all the cuckoo services after enabling rooter.

![2017-09-15 09_02_20-](https://user-images.githubusercontent.com/11653079/30483390-ce6c3ea0-99f4-11e7-9fe5-c17d0f17a120.png)

**Comment by doomedraven** [comment]
enabled it in routing conf

**Comment by arnydo** [comment]
I did...

route = none

internet = ens160

[inetsim]
enabled = yes
server = 192.168.56.1

**Comment by threathive** [comment]
Did you restart the web interface?

**Comment by arnydo** [comment]
Yes, I have restarted everything and verified configs. Logging doesn't show anything out of the ordinary afik. 
		
		

		Get Outlook for iO
	




On Mon, Sep 18, 2017 at 6:25 PM -0400, "threathive" <notifications@github.com> wrote:












Did you restart the web interface?

**Comment by arnydo** [comment]
I believe there was a rogue process running. Restarted everything in order and options were available.
