### ISSUE TITLE
keyError: 'label'

### ISSUE THREAD

**Issue by djobes31770** [cuckoosandbox/cuckoo#1852]
im getting this error while trying to get the cuckoo sandbox to  talk with physical machine for analysis.

![cuckoo-issue](https://user-images.githubusercontent.com/12225423/30550970-0af39ade-9c67-11e7-89ac-2b7950c8c08b.PNG)

**Comment by jbremer** [comment]
I believe this indicates incorrect configuration. Could you please share your `physical.conf`?

**Comment by RicoVZ** [comment]
Hey, are you still having this issue? If so, could you please share you `physical.conf`? Thanks!

**Comment by jbremer** [comment]
Closing issue for lack of additional information. Feel free to reopen if you have more feedback or questions.
