### ISSUE TITLE
Feature: selectively disable human interaction module (human.py)

### ISSUE THREAD

**Issue by internaldefect** [cuckoosandbox/cuckoo#1853]
Hi.
It would be highly useful if cuckoo had option to selectively disable human.py. 
By that I mean, it does a lot of stuff (mouse moving, mouse clicking, doing operations on clipboard, clicking buttons, interacting with microsoft office windows, ...), but sometimes some of the functionality can malform whole process of analysis.
We should be able to specify which options we want to enable.
It was discussed before, [this](https://github.com/cuckoosandbox/cuckoo/issues/531#issuecomment-100638546) answer looks like convenient solution for dealing with this problem.

**Comment by nicpenning** [comment]
What version are you running?

This is already a feature when you submit a url/file and its called "Enable Simulated Human Interaction" in 2.0 release. You can turn this off or on for each submission.

**Comment by internaldefect** [comment]
The latest one.
I know that it can be enabled, but the point is - it could only operate in boolean mode. On or off.
I want to emulate for example only mouse movement and clipboard operations, an disable automated button clicks. Sometimes it breaks analysis process, depending on environment. 
It just should be more customizable, I think.

**Comment by jbremer** [comment]
If you provide custom analysis options, then you can specify this. E.g., `cuckoo submit -o human=0,human.move_mouse=1 ...`. This is not very well documented (I'll certainly give you that), but is possible. Please see `cuckoo/data/analyzer/windows/modules/auxiliary/human.py` for the other options.

**Comment by internaldefect** [comment]
That is enough for my needs. I didn't knew about that, thanks Jurriaan :)

**Comment by jbremer** [comment]
Closing as resolved.
