### ISSUE TITLE
Feature: Control AWS EC2 instances

### ISSUE THREAD

**Issue by tr4cefl0w** [cuckoosandbox/cuckoo#1854]
This is partly referring to this issue https://github.com/cuckoosandbox/cuckoo/issues/674

To put things in context, let's say I want to use Cuckoo in AWS. I'd create one Cuckoo instance and one Windows instance. From what I understood in the issue above, the Windows instance has to be treated as a physical machine. However, the only way I know do to this, is to use FOG (by looking at physical.conf) which requires a third instance as the FOG server.

So I thought it'd be pretty nice to have a feature that allows to control EC2 instances, like restoring a VM using snapshot by leveraging the AWS API, similarly to the way Cuckoo controls VMs. Would this be considered? Else, is there a workaround?

Thanks!

**Comment by jbremer** [comment]
This has been discussed before (e.g., in #674). For various reasons we don't recommend such cloud practices and (partially) therefore it's not officially supported right now.
For now our advice is simply to get a dedicated machine, it keeps life easy when working with hypervisors/VMs etc.

**Comment by jbremer** [comment]
If you're interested to develop the module to work with AWS, in particular the new `i3.metal` thing, we could consider this. Otherwise for now I'll be closing this issue as we don't have much interest in implementing it (Cuckoo works just fine on a bare metal machine anyway). Thanks!
