### ISSUE TITLE
Analysis machine not popping up

### ISSUE THREAD

**Issue by iyerabhi07** [cuckoosandbox/cuckoo#1857]
Hello,

I upgraded to the new cuckoo version. whenever i start the analysis, the virtualbox and analysis machines do not pop up as it used to do in v2.0 rc1 which i was using. 
Was this discontinued? can i enable it again somehow?

**Comment by jbremer** [comment]
You can set `mode` to `gui` in `$CWD/conf/virtualbox.conf` :-)

**Comment by iyerabhi07** [comment]
Thanks!!

and my Win10 analysis machine keeps running into exceptions like file already exists and access denied Windows Errors. I have disabled the UAC. any reasons you might know?

**Comment by jbremer** [comment]
Yes, a couple. Mostly Windows 10 not being officially supported right now (it requires some more effort from our side).

**Comment by jbremer** [comment]
Closing as resolved for now. Sorry for not supporting Windows 10 yet.
