### ISSUE TITLE
Upgrading from a previous release

### ISSUE THREAD

**Issue by liqingjia** [cuckoosandbox/cuckoo#1869]
i upgrade cuckoo use:
cuckoo import OldCuckoo

cuckoo.common.exceptions.CuckooOperationalError: The path that you specified is not a proper Cuckoo setup. Please point the path to the root of your older Cuckoo setup, i.e., to the directory containing the cuckoo.py script!

but I cann't find the cuckoo.py

how can i confige the oldcuckoo steup path?

**Comment by jbremer** [comment]
The import functionality was designed for legacy Cuckoo setups, i.e., `1.2`, `2.0-rc1`, and `2.0-rc2` mostly (and some `2.0-dev` are also handled). We should probably rework the wording to more accurately mention this.
If you have a CWD you can just upgrade Cuckoo and it will work out of the box.

**Comment by jbremer** [comment]
Closing as resolved. Thanks.
