### ISSUE TITLE
Building cuckoo from source

### ISSUE THREAD

**Issue by ashtonwebster** [cuckoosandbox/cuckoo#1879]
Hello,

How does one install cuckoo from source?

Currently, I git clone the source, run `python stuff.monitor.py`, run `pip install .`, which all succeeds without issue.  However, when I run `cuckoo -d`, I get the following output:

```
 Cuckoo Sandbox 2.0.4
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

=======================================================================
    Welcome to Cuckoo Sandbox, this appears to be your first run!
    We will now set you up with our default configuration.
    You will be able to see and modify the Cuckoo configuration,
    Yara rules, Cuckoo Signatures, and much more to your likings
    by exploring the /home/ubuntu/.cuckoo directory.

    Among other configurable items of most interest is the
    new location for your Cuckoo configuration:
              /home/ubuntu/.cuckoo/conf
=======================================================================
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.4
OS version: posix
OS release: Ubuntu 14.04 trusty
Python version: 2.7.6
Python implementation: CPython
Machine arch: x86_64

No handlers could be found for logger "cuckoo"
```

I have installed using pip install cuckoo without issue, but I need to make some modifications to the source, so that is why I want to install it from source.  

Let me know if there is any other info I can provide to assist in figuring this out.

**Comment by RicoVZ** [comment]
Almost!

When installing Cuckoo manually, use: `$ python setup.py sdist develop`  (or `install` instead of `develop` if you are not going to edit any Cuckoo files) after running `$ python stuff/monitor.py`

Some extra actions need to be performed by the install script when installing manually. This is to create a file used by the working directory. These actiosns are triggered by the `sdist` argument.

**Comment by ashtonwebster** [comment]
Thanks for your help!  Is this worth adding to the documentation, or is this just something obvious I wasn't aware of?

**Comment by RicoVZ** [comment]
It is not obvious, I don't think it is in there. I will add it to the documentation soon. Thanks for the issue!

**Comment by jbremer** [comment]
It's mentioned in the development docs, https://cuckoo.sh/docs/development/package.html, but in a more prominent place would make sense too. @RicoVZ will take care of this, thanks!
