### ISSUE TITLE
So where do you add comments?

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#1881]
Topic...where do you add notes and whatnot like in cuckoo1?  Thank you.

**Comment by doomedraven** [comment]
you mean like in mod?

**Comment by DigiAngel** [comment]
No, I mean like in the old cuckoo you had a tab called "Comments", where you could add a comment.
![2017-10-10 09_39_24-cuckoo sandbox](https://user-images.githubusercontent.com/947191/31395823-f037986e-ad9e-11e7-80b3-83a09564d1e7.png)

**Comment by doomedraven** [comment]
em i don't remember what cuckoo official had statistics and comments, but i can be wrong

**Comment by DigiAngel** [comment]
So looking at old screenshots I don't see this...must have been a spender thing, which I use all the time...I'll close and open a FR thank you.
