### ISSUE TITLE
Submitting one by one and multiple files at once affect the results huge

### ISSUE THREAD

**Issue by mxk177** [cuckoosandbox/cuckoo#1886]
Hi,
I am running cuckoo 2.0.4 and also tried on 2.0.1,
when I submit only one exe at once it produces very good score and report.json is 285MB however when I send multiple samples at the same time produced score is less and report.json is 109MB. (I use the same VM for the same sample in both cases) 
@jbremer

**Comment by jbremer** [comment]
Duplicate of your other issue, thanks for asking though. Closing as duplicate.
