### ISSUE TITLE
Generating a report but not goes to the completed state 

### ISSUE THREAD

**Issue by BhautikRamani** [cuckoosandbox/cuckoo#1892]
Cuckoo is generating a report but its not goes to the "Completed" state. Its throwing an following errors:

1) Error starting Virtual Machine! VM: cuckoo1, error: Timeout hit while for machine cuckoo1 to change status
2) Error processing task #6: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration

What can I do ?

**Comment by jbremer** [comment]
Follow that URL to fix the networking issue that you seem to be having.

**Comment by BhautikRamani** [comment]
I configure my machine as suggested in the link but its not finding virtual machine.
