### ISSUE TITLE
Cuckoo Submit File "Missing" (From Dropped Files - Out of View)

### ISSUE THREAD

**Issue by nicpenning** [cuckoosandbox/cuckoo#1894]
Recently there have been some analyses that contain a dropped file with a comment field with over 400 characters so the Submit File button is in the bottom right of the web page which is off of the page. You have to do a Ctrl-F to find the button.

![image](https://user-images.githubusercontent.com/5582679/31633783-1344074c-b287-11e7-9db6-ab8ef4e69247.png)

![image](https://user-images.githubusercontent.com/5582679/31633736-eedf366a-b286-11e7-9e69-c704a4ee2b4d.png)

![image](https://user-images.githubusercontent.com/5582679/31633768-06b8303e-b287-11e7-8427-537291a8f9c4.png)

**Comment by jbremer** [comment]
:D Seems like something @automagisch can take a quick look at.

**Comment by nicpenning** [comment]
Sounds good, let me know how I can help!

**Comment by automagisch** [comment]
I've staged a fix internally for this issue for the upcoming release @nicpenning @jbremer !

**Comment by jbremer** [comment]
Thanks. This should have been resolved in ae0103544f6e0603a27d7889fd8c2fc08cee1b5c. Will ping once this commit has been released in the next alpha release!

**Comment by jbremer** [comment]
This has been released in `2.0.5.3` (`pip install -U cuckoo`). Closing as resolved, thanks.
