### ISSUE TITLE
install openedx

### ISSUE THREAD

**Issue by AlaaSwedan** [cuckoosandbox/cuckoo#1896]
hey ...
i had this error while installing >>
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
----------------------------------------------------------------------------------------------
TASK [common : Install role-independent useful system packages] ****************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name _unicode
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
	to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

PLAY RECAP *********************************************************************
localhost                  : ok=25   changed=19   unreachable=0    failed=1

**Comment by jbremer** [comment]
Where did you get this ansible playbook? We don't have any (semi-)official ansible playbooks ;-)
We do have some SaltStack configuration, which you can find at https://github.com/jbremer/cuckoo-salt.

**Comment by jbremer** [comment]
Closing for lack of additional information. Please reopen if you have an update.

**Comment by jbremer** [comment]
(Also seems completely irrelevant to our project, lol https://github.com/edx/configuration/blob/master/playbooks/edx_sandbox.yml)
