### ISSUE TITLE
 ERROR: IOError: [Errno 21] Is a directory: '/home/tso/.cuckoo/monitor/latest'

### ISSUE THREAD

**Issue by Mackousko12** [cuckoosandbox/cuckoo#1902]
Hi,

Just updated my cuckoo by running 'pip install -U cuckoo' and it broke. It is giving the following error. Could you please help?

Checking for updates...
 You're good to go!
2017-10-18 12:41:40,725 [cuckoo.apps.apps] WARNING: This is the first time you're running Cuckoo after updating your local version of Cuckoo. We're going to update files in your CWD that require updating. Note that we'll first ensure that no custom patches have been applied by you before applying any modifications of our own.
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.4
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 appdirs:1.4.3 asn1crypto:0.23.0 attrs:15.2.0 beautifulsoup4:4.5.3 beautifulsoup:3.2.1 blinker:1.3 bottle:0.12.8 cairocffi:0.8.0 cairosvg:1.0.22 canari:1.1 capstone:3.0.5rc2 cffi:1.11.2 chardet:2.3.0 cheetah:2.4.4 click:6.6 colorama:0.3.7 cryptography:2.1.1 cssselect:1.0.1 cuckoo:2.0.4.4 cuckooforcanari:1.1 cybox:2.1.0.9 debtags:2.0 defer:1.0.6 defusedxml:0.4.1 dirspec:13.10 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django-ratelimit:1.0.1 django:1.8.4 dnet:1.12 dnspython:1.12.0 dpkt:1.8.7 dumbnet:1.12 duplicity:0.7.6 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 hachoir-core:1.3.3 hachoir-metadata:1.3.3 hachoir-parser:1.3.4 hachoir-urwid:1.1 hachoir-wx:0.3 html5lib:0.999999999 httplib2:0.9.1 httpreplay:0.2.1 idna:2.6 ipaddress:1.0.18 itsdangerous:0.24 jdcal:1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:1.3.1 lockfile:0.12.2 lxml:3.6.0 maec:4.1.0.11 magic-file-extensions:0.2 mako:1.0.7 malformity:1.0 markupsafe:1.0 mechanize:0.2.5 ndg-httpsclient:0.4.2 nose:1.3.7 oauthlib:1.0.3 olefile:0.43 oletools:0.42 oneconf:0.3.9 openpyxl:2.3.0 packaging:16.8 pam:0.4.2 peepdf:0.3.6 pefile2:1.2.11 pefile:1.2.10.post114 pillow:3.2.0 pip:9.0.1 piston-mini-client:0.7.5 ply:3.7 psycopg2:2.6.2 py3compat:0.2 py:1.4.31 pyasn1-modules:0.0.7 pyasn1:0.2.3 pycparser:2.18 pycrypto:2.6.1 pycups:1.9.73 pydeep:0.2 pydot:1.0.29 pyelftools:0.24 pygeoip:0.3.2 pygobject:3.20.0 pyiptools:0.1 pyjwt:1.3.0 pylibpcap:0.6.4 pymisp:2.4.54 pymongo:3.0.3 pynessusrpc:0.3 pyopenssl:17.3.0 pyparsing:2.2.0 pyphen:0.9.4 pyrex:0.9.8.5 pyserial:3.0.1 pytest:2.8.7 python-apt:1.1.0b1 python-dateutil:2.4.2 python-debian:0.1.27 python-editor:1.0.3 python-graph-core:1.8.2 python-graph-dot:1.8.2 python-magic:0.4.12 pythonaes:1.0 pytz:2014.10 pyusb:1.0.0 pyx:0.12.1 pyxdg:0.25 requests:2.13.0 safedexml:0.5.1 scapy:2.3.2 service-identity:16.0.0 setuptools:36.2.7 sflock:0.2.17 six:1.11.0 software-center-aptd-plugins:0.0.0 sploitego:1.2.1 sqlalchemy:1.0.8 suricatasc:0.9 tinycss:0.4 tlslite-ng:0.6.0 twisted:16.0.0 ubuntuone-client-data:14.4 unicorn:1.0.1 unity-lens-photos:1.0 urllib3:1.22 urwid:1.3.1 vboxapi:1.0 volatility:2.6 wakeonlan:0.2.2 weasyprint:0.36 webencodings:0.5.1 werkzeug:0.12.2 wheel:0.29.0 wxpython-common:3.0.2.0 wxpython:3.0.2.0 xenapi:1.2 yara-python:3.6.3 zenmap:7.1 zope.interface:4.1.3

2017-10-18 12:41:41,012 [cuckoo] ERROR: IOError: [Errno 21] Is a directory: '/home/tso/.cuckoo/monitor/latest'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 216, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 117, in cuckoo_init
    migrate_cwd()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/apps.py", line 510, in migrate_cwd
    hash_ = hashlib.sha1(open(cwd(filename), "rb").read()).hexdigest()
IOError: [Errno 21] Is a directory: '/home/tso/.cuckoo/monitor/latest'

Thanks

**Comment by doomedraven** [comment]
```
"You may easily obtain the monitoring binaries by running one of our "
"'python stuff/monitor.py'."
```

**Comment by Mackousko12** [comment]
I have checked the stuff directory and it is empty.

**Comment by Mackousko12** [comment]
I have also tried to copy the 'monitor.py' to 'stuff/monitor.py' however I got the following error.
'This script must be run from Cuckoo repository root!'

**Comment by doomedraven** [comment]
try `cuckoo community -f`

**Comment by Mackousko12** [comment]
Tried this but no joy.

**Comment by Mackousko12** [comment]
Appreciate any workaround for this issue lads.

**Comment by doomedraven** [comment]
reinstall cuckoo, you did something wrong, or download monitor by yourself

**Comment by Mackousko12** [comment]
hmm. It was working totally fine before if typed 'pip install -U cuckoo'. I will give it a try to download monitor manually and then reinstalling cuckoo if it do not work.

**Comment by Mackousko12** [comment]
OK. Issue is resolved now. I had to delete 'cuckoo' folder and re-run the cuckoo.

Thanks for the help.
