### ISSUE TITLE
Create and revert kvm snapshot very slowly

### ISSUE THREAD

**Issue by rainkin1993** [cuckoosandbox/cuckoo#1905]
Hi,

I use KVM to create my virtual machines. But creating and revert snapshots are very slow.

`qemu-img info Win7_EN_64bit-4.qcow` return the following results:
![image](https://user-images.githubusercontent.com/2485043/31755585-cefc0074-b4d1-11e7-8abe-7298d3ed566e.png)

we can see the time of creating a snapshot is over 1 hours.

And when I submit a file to cuckoo, the cuckoo will use the command `virsh revert` to revert the snapshot, which cost several minutes.

After Google,  I found that creating and reverting an internal snapshot using `virsh snapshot-create` and `virsh revert` is actually very slow, and creating an external snapshot is faster but it seems that cuckoo machine doesn't support it. 

I know this is not the issue of the cuckoo sandbox, but I wonder are there any solutions can help me solve this problem?

**Comment by doomedraven** [comment]
Os? Kvm version?

**Comment by rainkin1993** [comment]
Kernel : 3.16.0-51-generic
OS : Ubuntu 14.04.3 LTS
Qemu version : 2.0.0+dfsg-2ubunut1.30
Qemu-kvm version : 2.0.0+dfsg-2ubunut1.34
libvirt-bin version :  1.2.2-0ubuntu13.1.20 

VM config:
[qemu_vm_config.zip](https://github.com/cuckoosandbox/cuckoo/files/1398149/qemu_vm_config.zip)

**Comment by doomedraven** [comment]
try latest 16.04, it has much faster qemu-kvm

**Comment by rainkin1993** [comment]
Thanks for your help!

Can updating qemu-kvm to the latest version in 14.04.3 solve this problem?

Thanks.

**Comment by doomedraven** [comment]
maybe, idk, i prefer latest version of lts ubuntu as they have much more recent version in repo than 14.04.x

**Comment by jbremer** [comment]
Please let us know if that solves your issue.

**Comment by rainkin1993** [comment]
Sorry for the slow reply. For some other reasons, updating to 16.04 is not acceptable for our server.

But I have found some tricks to solve this problem.

1. The RAM size allocated to a virtual machine affects the speed of creating snapshots very seriously.
Thus I change the RAM from 4G to 2G.

2. The first time when you create a snapshot is very fast. But creating a new snapshot again will last several minutes, even 1 hour.
My suggestion is deleting all snapshot before you want to create a new snapshot.

By doing the above two actions, I can create a snapshot within 30s.

Hope this info can help other guys who have the same problem
