### ISSUE TITLE
linux guest installation

### ISSUE THREAD

**Issue by cuckoo-linux** [cuckoosandbox/cuckoo#1907]
****I have created linux VM with ubuntu 17.04 64-bit.but i got following errors:****
E: Failed to fetch http://ddebs.ubuntu.com/dists/${codename}/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ddebs.ubuntu.com/dists/${codename}-security/main/binary-i386/Packages  404  Not Found
E: Failed to fetch http://ddebs.ubuntu.com/dists/${codename}-updates/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ddebs.ubuntu.com/dists/${codename}-proposed/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by daanfs** [comment]
`${codename}` should be the codename of the ubuntu release you are running (`yakkety`), please run the commands as described in the documentation or manually fix your `ddebs.list` file and run `apt get update` again.

```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C8CAB6595FDFF622

$ codename=$(lsb_release -c | awk  '{print $2}')
$ sudo tee /etc/apt/sources.list.d/ddebs.list << EOF
  deb http://ddebs.ubuntu.com/ ${codename}          main restricted universe multiverse
  deb http://ddebs.ubuntu.com/ ${codename}-security main restricted universe multiverse
  deb http://ddebs.ubuntu.com/ ${codename}-updates  main restricted universe multiverse
  deb http://ddebs.ubuntu.com/ ${codename}-proposed main restricted universe multiverse
  EOF

$ sudo apt-get update
$ sudo apt-get install linux-image-$(uname -r)-dbgsym
```

**Comment by cuckoo-linux** [comment]
After replacing codename still getting same error:(
E: Failed to fetch http://ddebs.ubuntu.com/dists/${zesty}/main/binary-i386/Packages  404  Not Found
E: Failed to fetch http://ddebs.ubuntu.com/dists/${zesty}-security/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ddebs.ubuntu.com/dists/${zesty}-updates/main/binary-i386/Packages  404  Not Found
E: Failed to fetch http://ddebs.ubuntu.com/dists/${zesty}-proposed/main/binary-amd64/Packages  404  Not Found

**Comment by doomedraven** [comment]
urls shouldnt contains ${} just name

**Comment by daanfs** [comment]
Your `ddebs.list` file should look like this:

```
deb http://ddebs.ubuntu.com/ zesty          main restricted universe multiverse
deb http://ddebs.ubuntu.com/ zesty-security main restricted universe multiverse
deb http://ddebs.ubuntu.com/ zesty-updates  main restricted universe multiverse
deb http://ddebs.ubuntu.com/ zesty-proposed main restricted universe multiverse
```

**Comment by cuckoo-linux** [comment]
After patching up successfully i got this error:(please help
linux@linux:~$ sudo stap -p4 -r $(uname -r) strace.stp -m stap_ -v
Pass 1: parsed user script and 465 library scripts using 117164virt/49044res/7192shr/42012data kb, in 110usr/0sys/119real ms.
semantic error: while processing probe __nd_syscall.socketcall.accept from: nd_syscall.accept from: nd_syscall.*

semantic error: type definition 'ulong' not found in 'kernel': operator '@cast' at /usr/share/systemtap/tapset/linux/sysc_accept.stp:104:12
        source: 	__args = &@cast(pointer_arg(2), "ulong")
                	          ^

Pass 2: analyzed script: 1118 probes, 205 functions, 104 embeds, 107 globals using 137764virt/71096res/8492shr/62612data kb, in 53780usr/10650sys/80962real ms.
Pass 2: analysis failed.  [man error::pass2]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.

**Comment by daanfs** [comment]
Could you show the output of dpkg -l linux-image-$(uname -r)-dbgsym from inside your guest VM?

**Comment by cuckoo-linux** [comment]
Errors resolved:)thanx for help.have added agent.py to crontab successfully and have taken snapshot of VM.Now can you kindly tell me configurations at host end please.

**Comment by daanfs** [comment]
@cuckoo-linux: see http://docs.cuckoosandbox.org/en/latest/installation/host/configuration/

**Comment by cuckoo-linux** [comment]
I made vM in virtual box with following configuratios:
# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = linux


[linux]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = linux

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = linux

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.56.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = Snapshot 2

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface = vboxnet0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 192.168.56.1

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 2042
But when i perform analysis,I got following errors.nothing happend in VM.:(
2017-10-31 14:46:09,616 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "996666.elf" (task #20, options "")
2017-11-01 10:13:49,487 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "996666.elf" (task #21, options "")
2017-11-01 10:13:49,637 [cuckoo.core.scheduler] INFO: Task #21: acquired machine linux (label=linux)
2017-11-01 10:13:49,641 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 3871 (interface=vboxnet0, host=192.168.56.101)
2017-11-01 10:13:49,642 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2017-11-01 10:13:49,746 [cuckoo.machinery.virtualbox] DEBUG: Starting vm linux
2017-11-01 10:13:49,877 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine linux to Snapshot 2
2017-11-01 10:13:54,624 [cuckoo.core.guest] INFO: Starting analysis on guest (id=linux, ip=192.168.56.101)
2017-11-01 10:13:55,629 [cuckoo.core.guest] DEBUG: linux: not ready yet
2017-11-01 10:13:56,637 [cuckoo.core.guest] DEBUG: linux: not ready yet
2017-11-01 10:13:57,627 [cuckoo.core.guest] DEBUG: linux: not ready yet
2017-11-01 10:13:59,637 [cuckoo.core.guest] DEBUG: linux: not ready yet
2017-11-01 10:14:00,646 [cuckoo.core.guest] DEBUG: linux: not ready yet
2017-11-01 10:14:01,635 [cuckoo.core.guest] DEBUG: linux: not ready yet
2017-11-01 10:14:02,657 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=linux, ip=192.168.56.101)
2017-11-01 10:14:02,719 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=linux, ip=192.168.56.101, monitor=latest, size=30538)
2017-11-01 10:14:02,768 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2017-11-01 10:14:02,769 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm linux
2017-11-01 10:14:04,343 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 698, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 499, in launch_analysis
    self.guest_manage(options)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 394, in guest_manage
    self.guest_manager.start_analysis(options, monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 465, in start_analysis
    self.upload_analyzer(monitor)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 372, in upload_analyzer
    self.determine_analyzer_path()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 350, in determine_analyzer_path
    r = self.post("/mkdtemp", data={"dirpath": systemdrive})
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 311, in post
    r = session.post(url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by cuckoo-linux** [comment]
issue resolved after upgrading agent to 0.8 in guest vM.:)

**Comment by jbremer** [comment]
Sweet! Closing as resolved. Thanks!

**Comment by vikaskarunakaran** [comment]
Can we configure Ubuntu 17.04 as linux guest in VirtualBox with usual network configuration like Windows Guest, instead of using Qemu and tap interfaces to run ELF x86_64 samples on cuckoo?

**Comment by doomedraven** [comment]
yes you can

**Comment by ertzaaafzal** [comment]
@cuckoo-linux How did you solve the following error?

`semantic error: while processing probe __nd_syscall.socketcall.accept from: nd_syscall.accept from: nd_syscall.*`
`semantic error: type definition 'ulong' not found in 'kernel': operator '@cast' at /usr/share/systemtap/tapset/linux/sysc_accept.stp:104:12
        source: 	__args = &@cast(pointer_arg(2), "ulong")`

Output of dpkg -l linux-image-$(uname -r)-dbgsym
`||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  linux-image-4. 4.15.0-20.21 amd64        Signed kernel image generic`

**Comment by doomedraven** [comment]
@ertzaaafzal which ubuntu version do you use?

**Comment by IceM4nn** [comment]
@ertzaaafzal Have you fix those problem? I have same problem as yours. but I doing for mipsel architecture on debian. Any ideas or ways you can guide me is really appreciated.

**Comment by nkd071819** [comment]
> Errors resolved:)thanx for help.have added agent.py to crontab successfully and have taken snapshot of VM.Now can you kindly tell me configurations at host end please.

How did you resolve it?

**Comment by vinceplayer** [comment]
i resolve with debian 9 and follow the guide
