### ISSUE TITLE
Linux guest installation

### ISSUE THREAD

**Issue by cuckoo-linux** [cuckoosandbox/cuckoo#1908]
I have installed ubuntu 17.04 in virtual box and got following errors:
sudo apt-get install linux-image-$(uname -r)-dbgsym
[sudo] password for linux: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-4.10.0-37-generic-dbgsym
E: Couldn't find any package by glob 'linux-image-4.10.0-37-generic-dbgsym'
E: Couldn't find any package by regex 'linux-image-4.10.0-37-generic-dbgsym'

**Comment by daanfs** [comment]
This is because you incorrectly added the ddeb repositories for the kernel debugging symbols as you described in #1907.

**Comment by jbremer** [comment]
Closing as duplicate.
