### ISSUE TITLE
Install Cuckoo 2.4 (Error Yara)

### ISSUE THREAD

**Issue by 1623664** [cuckoosandbox/cuckoo#1910]
Cuckoo Sandbox 2.0.4
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 Error checking for the latest Cuckoo version: HTTPConnectionPool(host='api.cuckoosandbox.org', port=80): Max retries exceeded with url: /checkversion.php (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa9b2244290>: Failed to establish a new connection: [Errno 111] Connection refused',))!
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.4
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 ansible:2.0.0.2 appdirs:1.4.3 asn1crypto:0.23.0 beautifulsoup4:4.5.3 bottle:0.12.7 cairocffi:0.8.0 cairosvg:1.0.22 capstone:3.0.5rc2 cffi:1.11.2 chardet:2.3.0 cheetah:2.4.4 click:6.6 colorama:0.3.7 cryptography:2.1.1 cssselect:1.0.1 cuckoo:2.0.4.4 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 dumbnet:1.12 ecdsa:0.13 egghatch:0.2.1 elasticsearch-dsl:2.1.0 elasticsearch:5.3.0 enum34:1.1.6 et-xmlfile:1.0.1 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 geoip2:2.4.1 html5lib:0.999999999 httplib2:0.9.1 httpreplay:0.2.1 idna:2.6 ipaddress:1.0.18 itsdangerous:0.24 jdcal:1.3 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:1.3.1 lxml:3.6.0 m2crypto:0.24.0 magic-file-extensions:0.2 mako:1.0.7 markupsafe:1.0 maxminddb:1.2.2 meld3:1.0.2 netaddr:0.7.18 olefile:0.43 oletools:0.42 openpyxl:2.4.0 packaging:16.8 paramiko:1.16.0 peepdf:0.3.6 pefile2:1.2.11 pefile:1.2.10.post139 pillow:3.2.0 pip:9.0.1 py:1.4.31 pycparser:2.18 pycrypto:2.6.1 pycurl:7.43.0 pydeep:0.2 pyelftools:0.24 pyliblzma:0.5.3 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.3.0 pyparsing:2.2.0 pyphen:0.9.4 pysqlite:1.0.1 pytest:2.8.7 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pytz:2014.10 pyyaml:3.11 requests:2.13.0 rpm-python:4.12.0.1 scapy:2.3.2 setuptools:35.0.2 sflock:0.2.17 six:1.11.0 sqlalchemy:1.0.8 sqlparse:0.1.18 supervisor:3.2.0 suricatasc:0.9 tinycss:0.4 tlslite-ng:0.6.0 typing:3.5.3.0 ujson:1.35 unicorn:1.0.1 unity-lens-photos:1.0 urlgrabber:3.9.1 urllib3:1.22 vboxapi:1.0 virtualenv:15.0.1 virustotal-api:1.1.2 volatility:2.5 wakeonlan:0.2.2 weasyprint:0.36 webencodings:0.5.1 werkzeug:0.12.2 wheel:0.29.0 xenapi:1.2 yara-python:3.6.3 yara:1.7.7 yum-metadata-parser:1.1.4

2017-10-20 17:24:07,491 [cuckoo] ERROR: AttributeError: Rules instance has no attribute 'save'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 216, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 127, in cuckoo_init
    init_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 259, in init_yara
    File.yara_rules["memory"].save(cwd("stuff", "dumpmem.yarac"))
AttributeError: Rules instance has no attribute 'save'

**Comment by jbremer** [comment]
Please `pip uninstall yara`. It's very outdated and we're using `yara-python==3.6.3` instead.

**Comment by jbremer** [comment]
Closing as fix has been provided.

**Comment by jwilczek** [comment]
I'm seeing the same issue with yara-python==3.6.3 installed.

**Comment by SparkyNZL** [comment]
do you mean Cuckoo 2.0.4 ? if so you might want to look at using 2.0.5.2

Cheers/
