### ISSUE TITLE
Linux Guest Setup: Failed to compile strace.stp

### ISSUE THREAD

**Issue by a3giso** [cuckoosandbox/cuckoo#1911]
Hi, Cuckoo Team 😃 

I followed the guide for the setup and fail at the last command. 
The build of the kernel extensions fails for an unknown reason, which seems to be similar to #1768.
Help please ! 

Greetings 

Software Versions:

> Ubuntu 17.04 x86_64
> linux-image-4.10.0-19-generic-dbgsym is already the newest version (4.10.0-19.21).
> systemtap is already the newest version (3.1-2).

Sources Config..
> cat /etc/apt/sources.list.d/ddebs.list
>   deb http://ddebs.ubuntu.com/ zesty          main restricted universe multiverse
>   #deb http://ddebs.ubuntu.com/ zesty-security main restricted universe multiverse
>   deb http://ddebs.ubuntu.com/ zesty-updates  main restricted universe multiverse
>   deb http://ddebs.ubuntu.com/ zesty-proposed main restricted universe multiverse

Command Output (output is truncated): 
 stap -p4 -r $(uname -r) strace.stp -m stap_ -v &> stap.log

>  parse error: expected statement
>         saw: /usr/share/systemtap/tapset/uconversions.stp EOF
> 
> 1 parse error.
> WARNING: tapset "/usr/share/systemtap/tapset/uconversions.stp" has errors, and will be skipped
> Pass 1: parsed user script and 464 library scripts using 116796virt/48556res/6712shr/42000data kb, in 90usr/0sys/101real ms.
> semantic error: unresolved function (similar: __ulong, __long, set_user_long, log, user_mode): identifier 'user_ulong' at /usr/share/systemtap/tapset/linux/sysc_accept.stp:105:19
>         source: 	sockfd = __int32(user_ulong(&@cast(__args, "ulong")[0]))
> 
> 
>  semantic error: unresolved function (similar:
 set_user_long, __long, user_mode, __ulong, log): identifier 'user_long' at :3914:10
>         source: 		return user_long(data)
>                 		       ^
> 
> semantic error: unresolved function (similar: set_user_string, kernel_string, set_user_string_n, stringat, proc_mem_string): identifier 'user_string' at /usr/share/systemtap/tapset/linux/context.stp:572:13
>         source:     __arg = user_string(__arg_start, ""); // argv[__nr], unquoted
>                             ^
> 
> semantic error: unresolved function (similar: set_user_long, __long, user_mode, __ulong, log): identifier 'user_long' at /usr/share/systemtap/tapset/linux/x86_64/aux_syscalls.stp:97:10
>         source: 		return user_long(addr)
>                 		       ^
> 
> Pass 2: analyzed script: 1118 probes, 503 functions, 103 embeds, 107 globals using 304504virt/237608res/8064shr/229708data kb, in 10870usr/150sys/11033real ms.
> Pass 2: analysis failed.  [man error::pass2]
> Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
>

**Comment by daanfs** [comment]
@a3giso: There was a bug in the patch for that file, which I forgot about. See the fix in https://github.com/daanfs/cuckoo/commit/694b92a10c626ba1326a5fe9560bd7e90dcf2927. I'll try to move this upstream asap, thanks for notifying us of the issue!

**Comment by daanfs** [comment]
See https://github.com/cuckoosandbox/cuckoo/pull/1914 for the proper fixes (of both patchfiles).

**Comment by jbremer** [comment]
We'll be pushing out the merge of @daanfs' #1914 soon, this fixes your issue. Please update soon :-)

**Comment by a3giso** [comment]
thx for the fast response.
works great :+1:
