### ISSUE TITLE
Installing Cuckoo from source

### ISSUE THREAD

**Issue by FatmaUVA** [cuckoosandbox/cuckoo#1924]
Hi,

I'm trying to install Cuckoo from source by running `sudo python setup.py sdist install` I'm getting an error `No handlers could be found for logger "cuckoo"` when I run `cuckoo -d`.

I've looked into this issue (https://github.com/cuckoosandbox/cuckoo/issues/1879), and I ran `python stuff/monitor.py` first. 

Below is some background on how I'm installing Cuckoo since this might be the problem.
I'm installing Cuckoo from source file in a testbed (DeterLab) dedicated for cybersecurity research where experimental nodes are behind a firewall and the nodes cannot reach the internet. So that installing Cuckoo with pip will not be an option for me.

In this testbed, there is a control node that I can access with ssh, and from this node I can access my experimental node where I'm planning to run Cuckoo.

The way I'm installed Cuckoo is as follows, I downloaded all the needed packages and cuckoo source file (with git clone) into the control node (since I can only access the internet form this node).
Then in the control node I ran `python stuff/monitor.py` (if I execute this script in the experimental node I get some errors since I can't reach the internet). Finally, I moved the files (packages tar files and cuckoo source code) from the control node to the experimental node, where I executed `sudo python setup.py sdist install` 

I'm wondering if I'm getting this error because I'm running `python stuff/monitor.py` in the control node. Honestly, I'm not sure what this script is responsible for, if it is just downloading some files that are not dependent on the machine configuration, I think it would be ok to run it in another node, get all the files that will be generated by the script and then move them to the machine where I want to install Cuckoo.

Thanks!

 ```Cuckoo Sandbox 2.0.4
 www.cuckoosandbox.org
 Copyright (c) 2010-2017
=======================================================================
    Welcome to Cuckoo Sandbox, this appears to be your first run!
    We will now set you up with our default configuration.
    You will be able to see and modify the Cuckoo configuration,
    Yara rules, Cuckoo Signatures, and much more to your likings
    by exploring the /users/fha6np/.cuckoo directory.

    Among other configurable items of most interest is the
    new location for your Cuckoo configuration:
              /users/fha6np/.cuckoo/conf
=======================================================================
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.4
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0.1 asn1crypto:0.21.1 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.7.0 click:6.6 colorama:0.3.7 cryptography:1.9 cuckoo:2.0.4.4 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 egghatch:0.2.1 elasticsearch:5.3.0 flask-sqlalchemy:2.1 flask:0.12.2 httpreplay:0.2.1 idna:2.6 itsdangerous:0.21 jinja2:2.9.6 jsbeautifier:1.6.2 mako:0.1.4 myghtyutils:0.52 olefile:0.43 oletools:0.42 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.3.0 pytest-runner:2.9 python-dateutil:2.4.2 python-editor:0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 scapy:2.3.2 setuptools-scm:1.9.0 sflock:0.2.15 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unicorn:1.0.1 urllib3:1.8.3 wakeonlan:0.2.2 werkzeug:0.7 yara-python:3.6.3

No handlers could be found for logger "cuckoo"

**Comment by jbremer** [comment]
Hi, thanks for elaborate explanation and sorry for my late reply. Yes, `stuff/monitor.py` only downloads some files that you can copy manually to the CWD. At this point I can only assume that something went wrong with that. If you add a `logging.basicConfig(level=logging.DEBUG)` to the start of the `main` method in `cuckoo/main.py` then we could see what Cuckoo is trying to log (instead of the `No handlers could be found for logger "cuckoo"` message).
Please let us know.

**Comment by jbremer** [comment]
I think this issue has been resolved in the meantime (the error looks familiar). Otherwise please perform the steps above and let us know. Closing as resolved.
