### ISSUE TITLE
cuckoo2 not seeing libvirt python bindings

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#1926]
When I run cuckoo:
~~~
2017-10-31 06:11:07,808 [cuckoo] CRITICAL: CuckooDependencyError: The libvirt package has not been installed (`pip install libvirt-python`)
~~~

this is installed however:
~~~
ii  python-libvirt                              1.3.1-1ubuntu1                               amd64        libvirt Python bindings
~~~

is there something special I need to do to tell cuckoo where libvirt is?  This is running in a virtual environment.  Thank you.

**Comment by DigiAngel** [comment]
Anything I can do on my end to troubleshoot this?  Thank you.

**Comment by daanfs** [comment]
Looks like the package is installed system-wide, is it also installed in your virtual env?
```
$ . venv/bin/activate
(venv) $ pip freeze | grep libvirt
libvirt-python==3.9.0
```

**Comment by DigiAngel** [comment]
Ah...it is not...and when I attempt to install pip tells me libvirt isn't installed:
~~~
Collecting libvirt-python
  Using cached libvirt-python-3.9.0.tar.gz
Building wheels for collected packages: libvirt-python
  Running setup.py bdist_wheel for libvirt-python ... error
  Complete output from command /home/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zn3uVo/libvirt-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2jtCGrpip-wheel- --python-tag cp27:
  Package libvirt was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libvirt.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libvirt' found
  Package libvirt was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libvirt.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libvirt' found
  running bdist_wheel
  running build
  /usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
  Package libvirt was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libvirt.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libvirt' found
  error: command '/usr/bin/pkg-config' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for libvirt-python
  Running setup.py clean for libvirt-python
Failed to build libvirt-python
Installing collected packages: libvirt-python
  Running setup.py install for libvirt-python ... error
    Complete output from command /home/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zn3uVo/libvirt-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vSIiha-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/venv/include/site/python2.7/libvirt-python:
    Package libvirt was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libvirt.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libvirt' found
    Package libvirt was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libvirt.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libvirt' found
    running install
    running build
    /usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    Package libvirt was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libvirt.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libvirt' found
    error: command '/usr/bin/pkg-config' failed with exit status 1
~~~

libvirt is installed system wide though...thanks for the response...not sure what to do next.

**Comment by daanfs** [comment]
@DigiAngel: To build it, you need the`libvirt-dev` package.

**Comment by DigiAngel** [comment]
Ya that was totally it...thank you!

**Comment by delbs** [comment]
Hi, I am receiving the exact same error on an ubuntu 16.04 system attempting to launch cuckoo using kvm for the first time. I do have the -dev package installed but receive an error when installing pip install libvirt-python which is below 

ollecting libvirt-python
  Downloading libvirt-python-4.1.0.tar.gz (186kB)
    100% |████████████████████████████████| 194kB 3.1MB/s 
Installing collected packages: libvirt-python
  Running setup.py install for libvirt-python ... error
    Complete output from command /home/delbs/venv1/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-FFL113/libvirt-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9TGhre/install-record.txt --single-version-externally-managed --compile --install-headers /home/delbs/venv1/include/site/python2.7/libvirt-python:
    running install
    running build
    /usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    /home/delbs/venv1/bin/python2 generator.py libvirt /usr/share/libvirt/api/libvirt-api.xml
    Found 406 functions in /usr/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 338 wrapper functions
    /home/delbs/venv1/bin/python2 generator.py libvirt-qemu /usr/share/libvirt/api/libvirt-qemu-api.xml
    Found 5 functions in /usr/share/libvirt/api/libvirt-qemu-api.xml
    Found 0 functions in libvirt-qemu-override-api.xml
    Generated 3 wrapper functions
    /usr/bin/pkg-config --atleast-version=1.0.2 libvirt
    /home/delbs/venv1/bin/python2 generator.py libvirt-lxc /usr/share/libvirt/api/libvirt-lxc-api.xml
    Found 3 functions in /usr/share/libvirt/api/libvirt-lxc-api.xml
    Found 0 functions in libvirt-lxc-override-api.xml
    Generated 1 wrapper functions
    running build_py
    creating build/lib.linux-x86_64-2.7
    copying build/libvirt.py -> build/lib.linux-x86_64-2.7
    copying build/libvirt_qemu.py -> build/lib.linux-x86_64-2.7
    copying build/libvirt_lxc.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building 'libvirtmod' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/build
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/include/python2.7 -c libvirt-override.c -o build/temp.linux-x86_64-2.7/libvirt-override.o
    libvirt-override.c:7746:7: error: ‘VIR_MIGRATE_PARAM_PERSIST_XML’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_PERSIST_XML, VIR_TYPED_PARAM_STRING },
           ^
    libvirt-override.c:7751:7: error: ‘VIR_MIGRATE_PARAM_DISKS_PORT’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_DISKS_PORT, VIR_TYPED_PARAM_INT },
           ^
    libvirt-override.c:7752:7: error: ‘VIR_MIGRATE_PARAM_COMPRESSION’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_COMPRESSION, VIR_TYPED_PARAM_STRING },
           ^
    libvirt-override.c:7753:7: error: ‘VIR_MIGRATE_PARAM_COMPRESSION_MT_LEVEL’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_COMPRESSION_MT_LEVEL, VIR_TYPED_PARAM_INT },
           ^
    libvirt-override.c:7754:7: error: ‘VIR_MIGRATE_PARAM_COMPRESSION_MT_THREADS’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_COMPRESSION_MT_THREADS, VIR_TYPED_PARAM_INT },
           ^
    libvirt-override.c:7755:7: error: ‘VIR_MIGRATE_PARAM_COMPRESSION_MT_DTHREADS’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_COMPRESSION_MT_DTHREADS, VIR_TYPED_PARAM_INT },
           ^
    libvirt-override.c:7756:7: error: ‘VIR_MIGRATE_PARAM_COMPRESSION_XBZRLE_CACHE’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_COMPRESSION_XBZRLE_CACHE, VIR_TYPED_PARAM_ULLONG },
           ^
    libvirt-override.c:7757:7: error: ‘VIR_MIGRATE_PARAM_AUTO_CONVERGE_INITIAL’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_AUTO_CONVERGE_INITIAL, VIR_TYPED_PARAM_INT },
           ^
    libvirt-override.c:7758:7: error: ‘VIR_MIGRATE_PARAM_AUTO_CONVERGE_INCREMENT’ undeclared here (not in a function)
         { VIR_MIGRATE_PARAM_AUTO_CONVERGE_INCREMENT, VIR_TYPED_PARAM_INT },
           ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/user/venv1/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-FFL113/libvirt-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9TGhre/install-record.txt --single-version-externally-managed --compile --install-headers /home/delbs/venv1/include/site/python2.7/libvirt-python" failed with error code 1 in /tmp/pip-install-FFL113/libvirt-python/

I have tried to install it globally and within virtualenv. Does anyone have any pointers? 

cheers,
Nathan

**Comment by doomedraven** [comment]
@delbs if you check your output you have errors 
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

google will give you a lot of solutions

**Comment by mix-1009** [comment]
@delbs
https://bugs.launchpad.net/openstack-requirements/+bug/1753539

> So a quick fix is:
pip install libvirt-python==4.0

Cheers

**Comment by reox** [comment]
The documentation should be fixed for this... It says to install `libvirt-python`, but this obviously only works if cuckoo is installed systemwide and not inside a venv. if a venv is used, `libvirt-dev` must be installed first in order to be able to build the module in the venv.

**Comment by baomajesty1458** [comment]
please, help me!. i don't know how to do it

Collecting libvirt (from -r requirements.txt (line 41))
  Could not find a version that satisfies the requirement libvirt (from -r requirements.txt (line 41)) (from versions: )
No matching distribution found for libvirt (from -r requirements.txt (line 41))
