### ISSUE TITLE
Failed to run the processing module ""Memory"

### ISSUE THREAD

**Issue by RealLinkers** [cuckoosandbox/cuckoo#1928]
Hello,

I am having trouble launching analysis.
I am using:
Volatility Foundation Volatility Framework 2.6

ERROR: Failed to run the processing module "Memory" for task #8:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 240, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1039, in run
    results[plugin_name] = getattr(self.vol, plugin_name)()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 950, in netscan
    for net_obj, proto, laddr, lport, raddr, rport, state in commands:
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/netscan.py", line 221, in calculate
    addr_space = utils.load_as(self._config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace: Filename must be specified and exist
 ArmAddressSpace: No base Address Space

Any ideas? 
Currently not having any progress.

**Comment by doomedraven** [comment]
did you specify correct vm vol profile?

**Comment by RealLinkers** [comment]
Yes, I read the related issue. I am using windows7 64 SP1.

2017. gada 31. okt. 17:31, "doomedraven" <notifications@github.com>
rakstīja:

**Comment by RealLinkers** [comment]
I just removed the netstat option it was crashing on, and it started working properly. Without this option it works fine for me.
