### ISSUE TITLE
No antivirus signatures available. 

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#1933]
I've installed and configured ClamAV, but I am not able to find anywhere to configure it within Cuckoo.  

Does Cuckoo just find and use it if its available?

**Comment by hackdefendr** [comment]
Is that all I need to do...install ClamAV and it works or is there some configuration options that need to be changed?

**Comment by thebitbucket123** [comment]
I'm seeing what you're likely seeing, that it's not mentioned in any of the code or docs. So, there isn't an existing ClamAV module for Cuckoo that I'm aware of.

Are you looking to have ClamAV do a local scan of the file and give back AV-sig results: as in hit/no-hit?  If so, I believe you'd need to create your own processing module for this.

ClamAV is one of the engines that Virustotal uses to scan samples, so if you enabled the Virustotal module, you'd get ClamAV results back with the rest of the AV engine results.

**Comment by rehanalam1** [comment]
@hackdefendr I believe you can do the changes in processing.conf to integrate custom module.

```
# If you add a custom processing module to your Cuckoo setup, you have to add
# a dedicated entry in this file, or it won't be executed.
```

**Comment by hackdefendr** [comment]
ClamAV is a module under the Cuckoo-Modified fork of Cuckoo.  Its also integrated with Suricata better, and also supports 64 bit Guest OS's. No one seems to be contributing to this repo much so I am using the modified version.
