### ISSUE TITLE
Error Resubmitting Sample After Rebooting Cuckoo Server: File no longer exists, oh but it does.

### ISSUE THREAD

**Issue by nicpenning** [cuckoosandbox/cuckoo#1938]
After rebooting the Cuckoo server I noticed that re-submissions will not work for analyses that have not been completed since the reboot. However, I can still download the file using Download.

![image](https://user-images.githubusercontent.com/5582679/32469145-fc12b230-c316-11e7-882a-7f24a7da0e0c.png)

![image](https://user-images.githubusercontent.com/5582679/32469020-66d606a4-c316-11e7-8e7a-3df0d5bc6cc1.png)

![image](https://user-images.githubusercontent.com/5582679/32468987-40cefdb2-c316-11e7-9092-c00c33266294.png)

**Comment by doomedraven** [comment]
just change sample storage files from /tmp to something permanent and volia :)

**Comment by nicpenning** [comment]
Oh excellent, let me test that. Did I miss that somewhere in the documentation?

Also, what location is it pulling the sample from when I click on download?

**Comment by nicpenning** [comment]
You must be referencing the cuckoo.conf fie:
# Temporary directory containing the files uploaded through Cuckoo interfaces...

I will modify that.

**Comment by doomedraven** [comment]
there are folder binaries which is linked from analysis folders if you didn't modify cwd
it is under `.cwd/storage/binaries`

**Comment by nicpenning** [comment]
That makes sense.

Is there some underlying reason why it doesn't pull from .cwd/storage/binaries for resubmit?

**Comment by doomedraven** [comment]
that is the question for @jbremer

**Comment by nicpenning** [comment]
Thanks @doomedraven! I changed the directory and that resolved the issue.
