### ISSUE TITLE
Results show previous sample

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#1940]
Process:
analyze al-khaser
delete results
analyze something else
results show al-khaser run

![2017-11-07 08_33_16-cuckoo sandbox](https://user-images.githubusercontent.com/947191/32504381-eafad3c0-c39c-11e7-9003-4ed0538c2242.png)

![2017-11-07 09_19_44-cuckoo sandbox](https://user-images.githubusercontent.com/947191/32504392-f2075c60-c39c-11e7-83f3-0bb38780ed32.png)

![2017-11-07 08_40_49-cuckoo sandbox](https://user-images.githubusercontent.com/947191/32504425-00198fb2-c39d-11e7-97eb-6ce114f13380.png)

**Comment by thebitbucket123** [comment]
When you deleted the results, did you use the "Cuckoo clean" utility or just delete the folder in "CUCKOODIR/storage/analyses/"?

It sounds like your DB still has data from the al-khaser run linked to the task_id for the new binary.

**Comment by DigiAngel** [comment]
Went to the options on the run and deleted it that way.

**Comment by noideal** [comment]
I had this problem before switching to a postgresql database - there may be a table integrity issue with SQLite. Here's the setup for Ubuntu:

apt install -y postgresql
sudo -u postgres psql -c "CREATE USER cuckoo WITH PASSWORD 'SOMEPASSWORD';"
sudo -u postgres psql -c "CREATE DATABASE cuckoo;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE cuckoo to cuckoo;"

- edit cuckoo.conf -
[database]
connection = postgresql://SOMEPASSWORD@localhost:5432/cuckoo

**Comment by DigiAngel** [comment]
Thank you noideal..that worked a treat.
