### ISSUE TITLE
Yara Rule None Match - cuckoo 2.0.4

### ISSUE THREAD

**Issue by rehanalam1** [cuckoosandbox/cuckoo#1944]
Hi There,

I have recently installed cuckoo 2.0.4 and analysis is working fine. Only thing which troubles me is "yara rules: none matched".
FYI - I didn't installed standalone yara as I saw cuckoo 2.0.4 comes with yara. Please do let me know if i need to do so.

Also, I ran "cuckoo community" command as well as cloned few yara rules from github and put in the folder ~/.cuckoo/yara/scripts, but it's still unmatched. I analyzed old locky sample with locky yara rule but no match. Would you be able to guide me to the resolution.

Thanks.

**Comment by rehanalam1** [comment]
I solved it. ;)

**Comment by thevidocq** [comment]
I have the same problem.
How you have solved?

**Comment by rehanalam1** [comment]
@thevidocq 

Didn't do much, just copied few yara rules from github - https://github.com/Yara-Rules/rules/tree/master/malware, place them in the directory [.cuckoo/yara/binary].
I tested with wannacry sample from - https://github.com/ytisf/theZoo/tree/master/malwares/Binaries.

Below was yara match count.

![image](https://user-images.githubusercontent.com/32792786/33476858-7cdde5ec-d6a9-11e7-903a-e9ced9debfc9.png)

**Comment by phutch11** [comment]
@rehanalam1 Thanks so much for breaking it down.

This test worked great - didn't need to change anything on my box but have been scratching my head why nothing was flagging. 

Thanks again.

**Comment by d4n13l4** [comment]
Hi
I have this same issue.
When running cuckoo I can see the rules been loaded but then I get none matched, I even tried the wannacry you mentioned before.
I copied the rules from the github repo to .cuckoo/yara and edited this script /usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py to add the folders as previously instructed in another thread I asked.

I don't get any error on the logs, here are the only relevants to yara other than the debug to the start that lists all the rules.
2018-02-06 11:23:22,910 [cuckoo.processing.memory] DEBUG: Executing volatility 'modscan' module.
2018-02-06 11:23:25,190 [cuckoo.processing.memory] DEBUG: Executing volatility 'yarascan' module.
2018-02-06 11:24:19,010 [cuckoo.processing.memory] DEBUG: Executing volatility 'netscan' module.

was there any config file I should have edited that I forget maybe?

**Comment by ramius1521** [comment]
> @thevidocq
> 
> Didn't do much, just copied few yara rules from github - https://github.com/Yara-Rules/rules/tree/master/malware, place them in the directory [.cuckoo/yara/binary].
> I tested with wannacry sample from - https://github.com/ytisf/theZoo/tree/master/malwares/Binaries.
> 
> Below was yara match count.
> 
> ![image](https://user-images.githubusercontent.com/32792786/33476858-7cdde5ec-d6a9-11e7-903a-e9ced9debfc9.png)

Do you edit any archive or just place the rules on [.cuckoo/yara/binary]

Because i was download the rules and place in the directory but yara None Matched
