### ISSUE TITLE
Cuckoo web access from network.

### ISSUE THREAD

**Issue by rehanalam1** [cuckoosandbox/cuckoo#1945]
Hi There,

I've setup Cuckoo v 2.0.4 on ubuntu machine and it's doing great. Only thing (as of now) not working is the "access to the cuckoo web" from my network (even from my physical machine). Also cuckoo web doesn't listen on Ubuntu interface IP(not sure it if should do or not).

Do I need to any changes at cuckoo end or physical machine/Network to access cuckoo web?

Any help is much appreciated.

Thanks.

**Comment by mattwhatkins** [comment]
Have you configured and started the web interface as per: https://cuckoo.sh/docs/usage/web.html

**Comment by rehanalam1** [comment]
Thanks Matt, I did that. Nginx configuration working great now.
