### ISSUE TITLE
Behavioural Analysis Web UI - Poor Process Tree View

### ISSUE THREAD

**Issue by mattwhatkins** [cuckoosandbox/cuckoo#1946]
The new process tree view in the web UI is really poor in comparison to the older version. 

On first glance, it is difficult to determine the process tree: which processes spawned which.
![image](https://user-images.githubusercontent.com/11374692/32691749-5ee8fb08-c704-11e7-98c1-0d5bb808270c.png)

In comparison, the older version was much nicer and easier to view:
![image](https://user-images.githubusercontent.com/11374692/32691755-752f73ce-c704-11e7-8466-7a572f24da57.png)

Any chance this could be added to the next revision of Web UI changes as a low priority change?

**Comment by automagisch** [comment]
Hey @mattwhatkins. Sorry to hear that you experience these inconveniences with this view, and thanks for pointing out these visual obstructions! I am going to look into it and try to make some changes that will (hopefully) improve the view in the upcoming versions.

**Comment by jbremer** [comment]
This should have been improved in 9d85ae14d53b17f93572ca251d06f40e631121d8, thanks!
Will ping you once this has been shipped in a next (alpha) release.

**Comment by jbremer** [comment]
This has been released as part of `2.0.5.3` (`pip install -U cuckoo`), a minor update on top of `2.0.5`. Closing as resolved and thanks for the feedback.
