### ISSUE TITLE
Is linux binary analysis possible with virtuabox virutal machine

### ISSUE THREAD

**Issue by vivekgupta123** [cuckoosandbox/cuckoo#1949]
I have installed cuckoo 2.0.4 on ubuntu and windows7 guest on VIrtualbox is working fine.

Now i want to install ubuntu 17.0.4 guest on virutalbox so I have gone through linux guest installtion guide then i came through following for host installtion in installation guide:

**Preconfigure network tap interfaces on host, required to avoid have to start as root:

Get list of virtual machines to configure interface per vm from conf/qemu.conf**

I want to know that linux analysis can not be done with virtualbox ?

**Comment by idanagar** [comment]
Listenning...
Trying to figure it out too.

**Comment by sebdg** [comment]
Hi @idanagar,
Sorry for the late reply, you can skip that part when using VirtualBox
Kind Regards

**Comment by jbremer** [comment]
It is possible with VirtualBox, although QEMU makes more sense as it supports more platforms (e.g., arm/sh4/ppc/etc). I think this issue is resolved, but please let us know if you need any more information.

**Comment by idanagar** [comment]
Thanks i have managed to analyze with cuckoo only on ubuntu 17.4. The other versions of ubuntu didnt work as well.

**Comment by doomedraven** [comment]
or you can use this one 
linux.huntingmalware.com
which supports x32/x64/arm/ppc/sparc/mips/mipsel ;)

**Comment by idanagar** [comment]
@doomedraven This site is great for me TNX

**Comment by jbremer** [comment]
Closing as resolved. Check also @doomedraven's website.
