### ISSUE TITLE
cuckoo installation error

### ISSUE THREAD

**Issue by socengsoc** [cuckoosandbox/cuckoo#1950]
hello
i install the cuckoo using the command   
pip install Cuckoo-2.0.4.4.tar.gz
 but i get  the below 
Can't rollback pillow, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zdGkTU/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dZP7p5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-zdGkTU/pillow/

/////////////////////////////  the full installation progress //////////////
Can't rollback pillow, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zdGkTU/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dZP7p5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-zdGkTU/pillow/

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////

could you please help me

**Comment by doomedraven** [comment]
just `pip install Cuckoo`

**Comment by socengsoc** [comment]
i tried but i get the below  error
//////////////////the error ////////////////////////////
Can't rollback pillow, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RB5n6u/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8TmUf8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-RB5n6u/pillow/
//////////////////////////////////////////////////

the full progress of installation  
root@kali:~# pip install Cuckoo
Collecting Cuckoo
Requirement already satisfied: httpreplay<0.3,>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: beautifulsoup4==4.5.3 in /usr/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: dpkt==1.8.7 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: click==6.6 in /usr/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: pymisp==2.4.54 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: scapy==2.3.2; sys_platform == "linux2" in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: django==1.8.4 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: python-dateutil==2.4.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: chardet==2.3.0 in /usr/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: python-magic==0.4.12 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Collecting peepdf==0.3.6 (from Cuckoo)
Collecting pefile2==1.2.11 (from Cuckoo)
Requirement already satisfied: sqlalchemy==1.0.8 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: django-extensions==1.6.7 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: elasticsearch==5.3.0 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Collecting pillow==3.2 (from Cuckoo)
  Using cached Pillow-3.2.0.zip
Requirement already satisfied: oletools==0.42 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Collecting unicorn==1.0.1 (from Cuckoo)
  Using cached unicorn-1.0.1-py2.py3-none-manylinux1_i686.whl
Requirement already satisfied: requests[security]==2.13.0; sys_platform == "linux2" in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Collecting sflock<0.3,>=0.2.15 (from Cuckoo)
Requirement already satisfied: alembic==0.8.8 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: jsbeautifier==1.6.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Collecting wakeonlan==0.2.2 (from Cuckoo)
Requirement already satisfied: androguard==3.0.1 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: egghatch==0.2.1 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: flask-sqlalchemy==2.1 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Collecting yara-python==3.6.3 (from Cuckoo)
Collecting pyelftools==0.24 (from Cuckoo)
Collecting pymongo==3.0.3 (from Cuckoo)
Requirement already satisfied: jinja2==2.9.6 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: flask==0.12.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo)
Requirement already satisfied: tlslite-ng==0.6.0 in /usr/local/lib/python2.7/dist-packages (from httpreplay<0.3,>=0.2.1->Cuckoo)
Requirement already satisfied: jsonschema in /usr/local/lib/python2.7/dist-packages (from pymisp==2.4.54->Cuckoo)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil==2.4.2->Cuckoo)
Requirement already satisfied: pythonaes==1.0 in /usr/local/lib/python2.7/dist-packages (from peepdf==0.3.6->Cuckoo)
Requirement already satisfied: colorama==0.3.7 in /usr/lib/python2.7/dist-packages (from peepdf==0.3.6->Cuckoo)
Requirement already satisfied: urllib3<2.0,>=1.8 in /usr/lib/python2.7/dist-packages (from elasticsearch==5.3.0->Cuckoo)
Requirement already satisfied: idna>=2.0.0; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: cryptography>=1.3.4; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: pycrypto==2.6.1; sys_platform == "linux2" in /usr/lib/python2.7/dist-packages (from sflock<0.3,>=0.2.15->Cuckoo)
Collecting olefile==0.43 (from sflock<0.3,>=0.2.15->Cuckoo)
Requirement already satisfied: python-editor>=0.3 in /usr/lib/python2.7/dist-packages (from alembic==0.8.8->Cuckoo)
Requirement already satisfied: Mako in /usr/lib/python2.7/dist-packages (from alembic==0.8.8->Cuckoo)
Requirement already satisfied: capstone==3.0.5rc2; sys_platform == "linux2" in /usr/local/lib/python2.7/dist-packages (from egghatch==0.2.1->Cuckoo)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python2.7/dist-packages (from jinja2==2.9.6->Cuckoo)
Requirement already satisfied: itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from flask==0.12.2->Cuckoo)
Requirement already satisfied: Werkzeug>=0.7 in /usr/lib/python2.7/dist-packages (from flask==0.12.2->Cuckoo)
Requirement already satisfied: ecdsa in /usr/local/lib/python2.7/dist-packages (from tlslite-ng==0.6.0->httpreplay<0.3,>=0.2.1->Cuckoo)
Requirement already satisfied: functools32; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from jsonschema->pymisp==2.4.54->Cuckoo)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security]==2.13.0; sys_platform == "linux2"->Cuckoo)
Building wheels for collected packages: pillow
  Running setup.py bdist_wheel for pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RB5n6u/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgXwv1Npip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-2.7
  creating build/lib.linux-i686-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/features.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-i686-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-i686-2.7/PIL
  running egg_info
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  copying PIL/OleFileIO-README.md -> build/lib.linux-i686-2.7/PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-RB5n6u/pillow/setup.py", line 767, in <module>
      zip_safe=not debug_build(), )
    File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-build-RB5n6u/pillow/setup.py", line 512, in build_extensions
      ' using --disable-%s, aborting' % (f, f))
  ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
  
  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
Installing collected packages: pillow, peepdf, pefile2, unicorn, olefile, sflock, wakeonlan, yara-python, pyelftools, pymongo, Cuckoo
  Found existing installation: Pillow 4.0.0
    Not uninstalling pillow at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RB5n6u/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8TmUf8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/features.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-i686-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-i686-2.7/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.linux-i686-2.7/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-RB5n6u/pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(), )
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-build-RB5n6u/pillow/setup.py", line 512, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
    
    ----------------------------------------
  Can't rollback pillow, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RB5n6u/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8TmUf8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-RB5n6u/pillow/

**Comment by doomedraven** [comment]
googing errors is useful,https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux

**Comment by socengsoc** [comment]
thank you doomedraveh for your reply .
i solve the issue . but after i installed it i tried to run it  but i get the below error  (error related to virtualbox although i use oracle vmware  workstaion )
/////////////////
CuckooCriticalError: VirtualBox' VBoxManage not found at specified path "/usr/bin/VBoxManage" (as specified in virtualbox.conf). Did you properly install VirtualBox and configure Cuckoo to use it?
2017-11-14 05:12:44,929 [cuckoo] CRITICAL: CuckooCriticalError: VirtualBox' VBoxManage not found at specified path "/usr/bin/VBoxManage" (as specified in virtualbox.conf). Did you properly install VirtualBox and configure Cuckoo to use it?
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-1, stopped daemon -1345823936)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc

**Comment by RicoVZ** [comment]
Hi socengsoc,

The error you are seeing indicates Cuckoo thinks you want to use Virtualbox.

In order to tell Cuckoo you are using another type of machinery, you need edit the **cuckoo.conf** file. It has a field called 'machinery'. Use this to specify the machinery you are using. Default it is `machinery = virtualbox`. Change yours to `machinery = vmware`.

See http://docs.cuckoosandbox.org/en/latest/installation/host/configuration/#cuckoo-conf for more information.

**Comment by socengsoc** [comment]
Thank you Ricovz
i changed the machinary to vmware and i get new error  , but i will close the issue because i opened new one cuckoo running issue with vmware 

the error  is 
CuckooConfigurationError: The configuration value '/usr/bin/vmrun' found for vmware:vmware:path is invalid. Please update your configuration!
2017-11-15 00:17:28,202 [cuckoo] CRITICAL: CuckooConfigurationError: The configuration value '/usr/bin/vmrun' found for vmware:vmware:path is invalid. Please update your configuration!
