### ISSUE TITLE
rooter routing icmp when None selected

### ISSUE THREAD

**Issue by dunlaps** [cuckoosandbox/cuckoo#1952]
**The problem:**
Guests are able to get icmp traffic out to the internet when None is selected for the Network Routing option. e.g. ping 8.8.8.8 is successful.

**Here's the setup:**
Cuckoo 2.0.4 release

esxi
nic 0 - internal network access only - for hitting cuckoo web front end
nic 1 - cuckoo host/guest network - Setup like a VirtualBox Host Only network. This network has no route to the internet.
nic 2 - default internet gateway 

**What i've tested to confirm:**
- Bringing up the guest VM manually when cuckoo is not running at all. i.e. rooter and other cuckoo services not running on the server. The VM is not able to ping 8.8.8.8, as expected.

- The Internet Network Routing option is working as expected.

- With cuckoo running: just upload a .bat file that pings 8.8.8.8. When None is selected, it is able to successfully ping 8.8.8.8. However, doing an nslookup or trying to hit a website directly fails, as expected. The only thing that i've found that escapes is icmp.

**Comment by doomedraven** [comment]
i may misremember,but that happens when you set network interface in config to real interface, for that i wrote drop rule ;) try it

**Comment by dunlaps** [comment]
that doesn't really solve the problem though. If for one analysis, i want internet selected, i don't want anything dropped. However, if None is selected, i would expect it to truly be None.

**Comment by doomedraven** [comment]
but you want to cut all traffic, so for that you have drop rule
try change internet to none and try with none you will see what not even icmp passing, but with interface you should to use drop, that is what you want, cut traffic for some analysis or not?

**Comment by dunlaps** [comment]
Please see my original post. _Guests are able to get icmp traffic out to the internet when None is selected for the Network Routing option._

I have a setup where i want None as an option and Interent as well. The Internet routing option is working fine. The problem is when None is selected. 

So that being said, are you saying i should still try to put a drop rule in place? Unless i'm missing something, that would make the Internet routing option fail.

**Comment by doomedraven** [comment]
yes, you got me wrong, if you go to router and see roules, None is not enforcing cut all traffic, when drop does it, and all that is due what the internet is not None in config, idk why you just don't want to test drop rule when you don't want to have traffic, and forget about the issue

**Comment by dunlaps** [comment]
After re-reading what you're saying, I am unclear what you're wanting me to test. 

Are you recommending that I add a drop rule to iptables directly that drops all icmp traffic on the host-only interface?

**Comment by doomedraven** [comment]
omg, just when you want to __CUT__ network traffic specify `drop` rule instead of `none`.
cuckoo has `Drop` option, you just need to select that instead of `None`. Done!

**Comment by dunlaps** [comment]
I see what you're saying now. I tried the drop option but the problem persists. I tried multiple times to be sure. the sample was able to ping 8.8.8.8 successfully. 

Also, based on the wording on the site, it seems like None and Drop should achieve the same thing. https://cuckoo.sh/docs/installation/host/routing.html 

None Routing | No routing whatsoever, the only option that does not require the Cuckoo Rooter to be run (and therefore also the default routing option).
Drop Routing | Completely drops all non-Cuckoo traffic, including traffic within the VMs’ subnet.

**Comment by doomedraven** [comment]
@jbremer in router in drop there missed the rule from my PR
```
run(s.iptables, "-A", "OUTPUT", "-s", ipaddr, "-j", "DROP")
```

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/1966/files

**Comment by dunlaps** [comment]
i just tested the change multiple times and it is still allowing outbound icmp.

I'm simply running the analysis for a test.bat file that pings 8.8.8.8.

**Comment by doomedraven** [comment]
not make sense, it will drop all what is not allowed and allowed very limtied stuff, i have also tried it on my ubuntu 16.04.3, maybe you have any other iptables or any other software which modifies it on your own

**Comment by dunlaps** [comment]
It was UFW causing the issue! I disabled it, rebooted and everything is now working as expected. Both None and Drop are now dropping the icmp traffic appropriately. The Internet option works fine now as well.

Thanks for your help getting this resolved.

**Comment by doomedraven** [comment]
great :) you can close then issue :)
