### ISSUE TITLE
Score doesn't get updated in the recent list after re-processing

### ISSUE THREAD

**Issue by sebdg** [cuckoosandbox/cuckoo#1959]
Hi all, 

I've analyzed some projects a first time without suricata or snort. 
These are shown in the recent list in the web ui.
When I re-process with snort and suricata, alerts are raised and visible.
The score on the report page itself went from 1 to 2.2, but in the recent list this remains 1.
I'm using 2.0.4. No errors nor warnings during the  re-processing command exection.

Kind Regards

**Comment by sebdg** [comment]
@jbremer you can close this issue as it is about to be merged

**Comment by jbremer** [comment]
You can do that yourself too, btw, but yes, thanks!
