### ISSUE TITLE
Is it mandatory to use FOG? Can I use Deep Freeze ? For Phyiscal Machine

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1961]
Hello Guys,

I have setup one physical machine (Windows) and cuckoo on different machine (Centos7) and I have installed Deep freeze on physical machine, so just want to know will this work or not?

**Comment by cuckool** [comment]
Hi, I am currently using Deep Freeze on a physical machine and everything works fine. As a matter of fact, its been easier to use and to configure than FOG.

**Comment by jbremer** [comment]
Thanks for the feedback @cuckool. Do you have any additional information with regards to special setup instructions (outside of the regular Cuckoo/Deep Freeze stuff)? Also, what kind of changes did you perform in Cuckoo to get this working, could you share them in a PR? Thanks! :-)

**Comment by jbremer** [comment]
Closing for lack of additional information. We're interested in this though, so please open a PR with your code changes @cuckool.
