### ISSUE TITLE
50 Virtual Machines & Cuckoo Sandbox

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1965]
Hello Guys,

I am looking to run 50 Virtual machines Parallel and cuckoo as a HOST is there any way to do that?
Can we use Hyper-V, Is cuckoo support that? Need suggestion.
.
Thanks & Regards
Seantree

**Comment by jbremer** [comment]
Yes, Cuckoo can handle around 50 VMs. I've tested this with VirtualBox. Cuckoo currently doesn't support HyperV.

**Comment by djugurta** [comment]
hello guys,
i don't indurstand how to get the API calls from cuckoo .any explanation 
thanks

**Comment by doomedraven** [comment]
`cuckoo community`

**Comment by jbremer** [comment]
Please take a look at the reports, especially the behavior section @djugurta. Closing this issue, feel free to reopen if there are still relevant questions.

**Comment by netpacket** [comment]
Would want to think about cuckoo sandbox cluster? Just a thought.
