### ISSUE TITLE
Missing MySQL database driver

### ISSUE THREAD

**Issue by Mato-Z** [cuckoosandbox/cuckoo#1971]
Hello,

I need connect Cuckoo 2.0.4 to my MySQL database. 

I set connection string in conf/cuckoo.conf:
`connection = mysql://user:pass@ip:port/DB_name`
I installed all required packages via pip. But when I start Cuckoo I get this error:

`2017-11-19 11:48:47,370 [cuckoo] CRITICAL: CuckooDependencyError: Missing MySQL database driver (install with `pip install mysql-python` on Linux or `pip install mysqlclient` on Windows)`

My pip freeze output:
```
cairocffi==0.8.0
CairoSVG==1.0.22
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
cssselect2==0.2.1
defusedxml==0.4.1
distorm3==3
docutils==0.12
html5lib==0.999999999
lxml==3.4.0
MySQL-python==1.2.3
mysqlclient==1.3.12
ndg-httpsclient==0.3.2
nose==1.3.4
numpy==1.8.2
openpyxl==1.7.0
pdfrw==0.4
Pillow==2.6.1
ply==3.4
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.6.1
pycups==1.9.63
pycurl==7.19.5
pydeep==0.4
Pygments==2.0.1
pygobject==3.14.0
PyMySQL==0.7.11
pyOpenSSL==0.14
Pyphen==0.9.4
pysmbc==1.0.15.3
python-apt==0.9.3.12
python-debian==0.1.27
python-debianbts==1.11
pytz==2012rc0
pyxdg==0.25
reportbug==6.6.3
requests==2.4.3
roman==2.0.0
six==1.8.0
SOAPpy==0.12.22
tinycss2==0.6.1
urllib3==1.9.1
vboxapi==1.0
virtualenv==1.11.6
volatility==2.4
WeasyPrint==0.41
webencodings==0.5.1
wstools==0.4.3
yara-python==3.1
```
I have installed python-mysqldb, libmysqlclient-dev via apt-get too. I use Debian 8.9 x64. 
Thanks for help.

**Comment by Mato-Z** [comment]
Can anyone help me please? :-(

**Comment by SparkyNZL** [comment]
Hi Mato-Z

Can you please supply some more information.

Database location (local or remote)
MySql installed version (not the python module) you need to also install mysql server and client
can you connect to your mysql server  ? mysql -u <username> -p  ?
is the mysql server running and accepting connections ? there is a lot of work to be done before we start to look at cuckoo connection to the server.

Let us know how you get on.

**Comment by Mato-Z** [comment]
@SparkyNZL thanks for help. So:
I use remote location.
I have installed mysql-server via apt-get: version 5.5.58-0+deb8u1, client: 5.5.58-0+deb8u1, remote server: mysql-server 5.5.55-0+deb8u1
Connect to mysql server from bash: `mysql -u {username} -p{password} -h {remote server ip} --port=port_num  {DB name} ` works ok.

**Comment by Mato-Z** [comment]
After update on 2.0.5 it seems be ok... I wil try it. Many thanks for help.

**Comment by Mato-Z** [comment]
By the way, is possible save all details from Cuckoo analysis to MySQL database instead of MongoDB that use Cuckoo web interface too?

**Comment by SparkyNZL** [comment]
Nope sorry




sent from my Pixel 2.







On Thu, Jan 4, 2018 at 7:41 AM +1300, "Mato-Z" <notifications@github.com> wrote:












By the way, is possible save all details from Cuckoo analysis to MySQL database instead of MongoDB that use Cuckoo web interface too?

**Comment by Mato-Z** [comment]
Ok, thanks for help and explanation.

**Comment by jbremer** [comment]
Closing as resolved, thanks.
