### ISSUE TITLE
Cuckoo Notification

### ISSUE THREAD

**Issue by Busbar2297** [cuckoosandbox/cuckoo#1972]
Hi There,
I can see in reporting area a field for notification server/URL, how is it being used and what data are sent and what is required to receive it , it is not documented any where ?!

**Comment by RicoVZ** [comment]
Hi Busbar2297,

The notification reporting module sends a POST request to a URL specified in the reporting.conf file.
In the section `[notification]` you can enable the module, specify a URL to post to, and specify an 'identifier' (Any string that you can use to more easily identify the host sending the notification). 

The request will contain the following form fields: `task_id`, `identifier`, `data`.

**task_id**
    - The task id of the analyses that was reported
**identifier**
    - The identifier string specified in reporting.conf
**data**
    - This field will contain all data that can normally be found in the 'info' block in the JSON report (task options, task category(file/url etc) and others).

So to use this module, there are no real requirements on the receiving side's end. Well, besides it being able to receive a POST request on the URL configured in reporting.conf.

**Comment by jbremer** [comment]
Any additional feedback or questions on this matter @Busbar2297 or has this issue been resolved for you? :)

**Comment by jbremer** [comment]
Closing issue as resolved.
