### ISSUE TITLE
MACOSX package header required

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#1975]
Hi,

Is there any package header available for MACOSX? 
My macosx is showing unable to import the package pdf, generic etc.

waiting for positive reply.
.
Thanks & Regards
Seantree

**Comment by jbremer** [comment]
what is a package header?

**Comment by jbremer** [comment]
Closing for lack of additional information. Feel free to reopen if you have additional information.

**Comment by seantree** [comment]
Hi @jbremer package header is mach-o and app
