### ISSUE TITLE
Cannot find manage.py to run the web interface of cuckoo 

### ISSUE THREAD

**Issue by Ma06RC** [cuckoosandbox/cuckoo#1982]
I have followed through the installation process and everything from the official cuckoo documentation. However, I cannot find the file for manage.py to run the cuckoo web interface. In $CWD/web/ only has the local_settings.py

**Comment by doomedraven** [comment]
that doestn exist anymore, just `cuckoo -d web -H 0.0.0.0 -p 8000`

**Comment by Ma06RC** [comment]
Yes, I just figured that out today. Thank you

**Comment by jbremer** [comment]
Closing as resolved, thanks @doomedraven.
