### ISSUE TITLE
 vmrun path is inviled when run cuckoo

### ISSUE THREAD

**Issue by socengsoc** [cuckoosandbox/cuckoo#1991]
hello 
Hello
when i execute command cuckoo -d to run the cuckoo i get an error as the following line 
please help me.
/////////////////////////////////////the error //////////////////////
Cuckoo Sandbox 2.0.4
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

[2017-12-03 02:06:23] CuckooConfigurationError: The configuration value '/usr/bin/vmrun' found for vmware:vmware:path is invalid. Please update your configuration!
2017-12-03 02:06:23,460 [cuckoo] CRITICAL: CuckooConfigurationError: The configuration value '/usr/bin/vmrun' found for vmware:vmware:path is invalid. Please update your configuration!

**Comment by RicoVZ** [comment]
Hi socengsoc,

Upon Cuckoo startup some checks are performed. This includes checking if the specified binary path for the chosen machinery module exists. This error indicates that this check failed.

I expect that the path `/usr/bin/vmrun` does not exist on the system you are running Cuckoo on.

If you are sure the command `vmrun` is available, you should be able to get its path by running `which vmrun` (`where vmrun` if on Windows).

**Comment by socengsoc** [comment]
thank you RicoVz  for your reply
i have kali linux  2017 32 bit , i explore the path /usr/bin/ and i didn't ge the vmrun 
i tried to execute command of vmrun like vmrun -t or -h or vmrun start and the result was the vmrun not exist
i installed the VMware-VIX-1.12.0-812388.i386  to solve the issue  but it's still in progress for 2 days and .
what  can i do ? i s there any method to download the vmrun on the default path on /usr/bin

**Comment by doomedraven** [comment]
you can create symlink to that path or just change /usr/bin/vmrun to path where vmrun is placed

**Comment by socengsoc** [comment]
hi doomedraven
as i explored the usr/bin path  to search the vmrun  and is not found , itry to installed it via download  the bundle file VMware-VIX-1.12.0-812388.i386 . when i extract the bundle file there is error message that  say there  is issue with  it and told me to change the character (the default utf8) 

  . is there  any method to download the vmurn ?   what can id to complete the road with cuckoo ?

![1](https://user-images.githubusercontent.com/33623704/33802950-e7c2e352-dd94-11e7-9fae-621ddc52bd76.JPG)

**Comment by doomedraven** [comment]
only vmrun no,
do you know how to install bundles? `chmod a+x VMware-VIX* && sudo ./VMware-VIX.....bundle` that will install it
after install vmware you can do `sudo updatedb && which vmrun`

**Comment by socengsoc** [comment]
thank you for all .
the issue of  vmrun  solved .

i faced another issue and i didn't know if necessary to open new issue or continue and what will the title of new issue will be .
i will show the scenerio  that i follow to start with cuckoo 
i have windows 8.1 as main OS  for my station , i decided  to start with cuckoo on separate  Linux environment (kali linux ),   so i installed VMware inside the windows  8.1 and inside it i download and install the cuckoo 2.4 .
when runing the cuckoo by command  cuckoo -d i get the following error 
![error](https://user-images.githubusercontent.com/33623704/33827393-43b74fba-de79-11e7-85a1-4801d7060a2c.JPG)

i opened the machinery vmware.confg file  and i get the below line  👍 
![erro2](https://user-images.githubusercontent.com/33623704/33827468-857fcec2-de79-11e7-8793-4b2a32e2cb78.JPG)

i will show you screen shot for kalilinux VM (vm dedicated for cuckoo )
![error3](https://user-images.githubusercontent.com/33623704/33827589-ec410dec-de79-11e7-8dc6-bc2401740c16.JPG)
i didn't have any additional VM , i try to put the name of kalilinux (Kali-Linux-2017.1-vm-i686) as the VM path as the following line
vmx_path = ../Kali-Linux-2017.1-vm-i686.vmx
i get the same error 
what can i do ? please help me

**Comment by doomedraven** [comment]
you should provide full path, not relative

**Comment by socengsoc** [comment]
the path of vmx file of cuckoo host will be on windows drive  .
i put it as following

vmx_path = H:\Kali-Linux-2017.1-vm-i686\Kali-Linux-2017.1-vm-i686.vmx
and i get the same error .
it's not reasonable to put windows path inside linux

**Comment by doomedraven** [comment]
dude read the documentation, you trying to do what is unsupported, how do you expect to execute vm from outside of the vm? the vm should be inside of the same vm at least, but that will give you very poor perfomance(depend on your hardware)

**Comment by socengsoc** [comment]
hello doomedraven
i thank you for your reply , i feel i bothered you , this is will be the last request .

as i said previous that i have laptop with windows 8.1 , inside the windows i install the VMware workstation  12 app and inside it i  installed Kali linux and inside it i installed  the cuckoo .

so on the machinery file of cuckoo VM, it asked me the path of the VM  . is this path must be the path of Cuckoo VM  (it will be on windows drive G: as on my pc) or path to another guest VM that will be the environment of malware execution .

i want to execute the malware on the same VM of cuckoo , is it possible  ?
please give me the best scenario that will suitable with my environment  ?

**Comment by doomedraven** [comment]
VMs should be executed by host/vm where cuckoo is installed, you could do sharing folders to use vm from another host/vm, but then i wouldn't expect perfomance. 

the best option is install cuckoo on host and use vms over the host

**Comment by socengsoc** [comment]
hello 
sorry for re-open the issue , i want to go with cuckoo 
i'm not expert with Linux , so this is the cause of many issue i have  

the new scenario 

# the Host info : 
-------------------------------
OS : VM (Vmmware) Kali Linux with cuckoo installation inside it 
Hostname : Kali-Linux-2017.1-vm-i686
IP address : 192.168.128.10

# The Guest
------------------------------
the agent installed inside it
OS :  VM Windows 7 professional 
Hostname : WIN7-analysis
IP address : 192.168.128.11
-------------------------------

each VM (Host and Guest ) can ping other 

the VMware.config  as the below 
///////////// vmware.config ////////////

# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = WIN7-analysis
interface = virbr0
[WIN7-analysis]
# Specify the path to vmx file of this virtual machine.
vmx_path = ./WIN7-analysis.vmx
# Specify the snapshot name to use.
snapshot = Snapshot1
platform = windows
# Specify the IP address of the current virtual machine. Make sure that the
# the analysis will fail.
ip = 192.168.128.10
resultserver_ip = 192.168.128.10
////////////////////////////

the cuckoo.config file as the below 
# `resultserver_ip` for all your virtual machines in machinery configuration.
ip = 192.168.128.10

# Specify a port number to bind the result server on.
port = 2042
/////////////////////

when i run the cuckoo  i get the below error 
![vmerror](https://user-images.githubusercontent.com/33623704/33929875-0ed4c046-dffc-11e7-9fb7-d50e5c3def62.JPG)






i

**Comment by doomedraven** [comment]
as i told you, don't use relative path as 'vmx_path = ./WIN7-analysis.vmx' specify whole path `vmx_path = /path/to/this/file/WIN7-analysis.vmx`

**Comment by socengsoc** [comment]
@doomedraven 
i know the issue with path , but i didn't know what i put  on the absolute path
i'm not expert with linux .so please help me to put the correct path as the previous info. 

the two VM Host and guest on the same Vmmware work station Application  as the below screenshot   , and the Vmware  workstation installed inside windows 8  and the harddrive for the VMworkstaion on G: drive 
![twovm](https://user-images.githubusercontent.com/33623704/33932314-b0e5aa74-e003-11e7-8576-af7623c84abe.JPG)

**Comment by doomedraven** [comment]
you can see `H:\......vmx` etc etc that is the path but vm should be inside of the cuckoo host which is kali as far as i remmeber, so kali won't see it if that isn't shared folder, the same what we spoke before

**Comment by socengsoc** [comment]
the guest VM is not inside the Host , the cuckoo  host and guest are two Vm's  and they behind each other  inside the VM workstation  which is installed inside Win8  .

**Comment by RicoVZ** [comment]
@socengsoc 

I missed your reply, sorry.

To be brief: controlling a VMware vm(your Win7) with from another VMware vm (your Kali), is not possible. Cuckoo needs to be able to control the virtual machines.

The easiest solution would be:
Install Cuckoo directly (in a Python virtualenv) on a host and then create the guest VMs on the same host.

**Comment by tthtlc** [comment]
Just to add on some info for my case:
1. Host = Ubuntu1804.
2. VMware used.   Created an VM guest, running Ubuntu1804 - call this GuestVM1.
3. Inside GuestVM1, I install: VMware + Virtualbox + CAPE (a variant of Cuckoo).
4. Started CAPE, and configure it to called VMware/Virtualbox.  All working.    
My desktop CPU is Ryzen 9 3900x and performance of this nested virtualization is really responsive.

**Comment by doomedraven** [comment]
Omg that the worst setup ever 🤣

Why do hou need vmware and vbox? Goodbuy performance and welcome vmdetection

**Comment by kevoreilly** [comment]
It is worth saying that KVM is by far the best, doomedraven is right here.

But I also do run CAPE on VMware in addition just for convenience on a few windows boxes (more instances = better for dev)

You don't need nested virtualisation. I wrote a machinery module for VMware Workstation 15 REST API:

https://github.com/kevoreilly/CAPEv2/blob/master/modules/machinery/vmwarerest.py

Bit of a pain to set up the REST server on the host but surely a lot less pain than nested virtualisation! Once it's working it's solid. VM detection is crap in VMware and Vbox though so KVM for the win!

**Comment by kevoreilly** [comment]
By the way RicoVZ says "it is not possible" to run the cuckoo or cape in one vm and the target in a vm next to it on yet I have been doing this for maybe 5 years... It can be done with VMware Workstation 11 & 12 using vix api, and it can now be done on VMware 15 (Windows & Linux host) & Fusion (Mac host) using the REST api.
