### ISSUE TITLE
[cuckoo] CRITICAL: CuckooCriticalError: Error initializing machines: VBoxManage error listing installed machines: [Error 5] Access is denied

### ISSUE THREAD

**Issue by moveax41h** [cuckoosandbox/cuckoo#1996]
Host Environment info:
Windows 10.0.16299 Build 16299
Also using Ubuntu Linux Subsys for Windows:
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

I've followed the steps outlined [in this video](https://www.youtube.com/watch?v=nLGJHgv6uWA) gotten all the way to the point where I need to fire up Cuckoo and am getting the above error. Basically, cuckoo apparently does not have permissions to get the vm list from VBoxManage but I have no idea why not. I have modified the permissions on VBoxManage in Windows by setting all users/admin to have full permissions to the file. I also checked and the Vbox file for the actual subject VM also has full permissions enabled.

Cuckoo was installed by running pip install cuckoo on a Windows cmd.exe and MySQL, mongodb, apache were installed using the Bash subsystem but I don't think that's a problem since this error is between two components which were both installed using regular cmd.exe as admin. Also, I do run cuckoo as admin and still I get this error. Yes, I did look at the other posts for this error in resolved issues but those solutions have not worked for me.

**Comment by jbremer** [comment]
Sounds like you messed up a bit with Administrator vs non-Administrator. Can you even resume the VM normally?

**Comment by TheOnlyRealTodd** [comment]
I can run the VM and operate it just fine, it's just Cuckoo can't for some reason. Also, I did try to use VBoxManage.exe manually at the commandline. I ran command: `VboxManage list vms` and it works fine.

**Comment by moveax41h** [comment]
@jbremer I can run the VM and operate it just fine, it's just Cuckoo can't for some reason. Also, I did try to use VBoxManage.exe manually at the commandline. I ran command: VboxManage list vms and it works fine.

**Comment by jbremer** [comment]
Not sure, is this still an issue for you? Otherwise try installing Cuckoo on Ubuntu, please.
Will be closing this issue if there's no reply soon'ish :-)
