### ISSUE TITLE
CuckooCriticalError: Unable to connect to MongoDB: 127.0.0.1:27017: [Errno 111] 

### ISSUE THREAD

**Issue by mokkkeakn** [cuckoosandbox/cuckoo#1997]
Hey,
Until yesterday I was able to start MongoDB by using the following commands:

run /etc/init.d/mongodb start.
cuckoo run webserver

Today i tried to change the configuration and from Windows 7 use Windows XP.
After i made the changes am getting the following error:
CuckooCriticalError: Unable to connect to MongoDB: 127.0.0.1:27017: [Errno 111] Connection refused

Some parts of the configurations:
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
# MongoDB authentication (optional).
username =        
password =    

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui" or "headless". Please refer to VirtualBox's official
# documentation to understand the differences.
mode = gui

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = IE6 - WINXP
  
[IE6 - WINXP]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = IE6 - WINXP

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 10.0.2.10

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = XPsnap

If that's a very common issue am sorry in advance am new :)

**Comment by doomedraven** [comment]
that isnot related to vm, is just your mongo not started
if you type `mongo` can you get mongo shell?

**Comment by mokkkeakn** [comment]
I get the following error:
Failed to connect to 127.0.0.1:27017, in checking socket for error after poll, reason errno:111 connection refused

Couldn't connect to server 127.0.0.1:27017 connection attempt failed:

Connect@src/mongo/shell/mongo.js:229:14
@(connect) :1:6
exception failed

Hope that help!

**Comment by jbremer** [comment]
So, if you had to guess, what would you think is the problem here?

**Comment by mokkkeakn** [comment]
At first i thought there is a service stopped but i tried to restart mongodb but nothing change.
 If i had to guess i would say to change the default port at one of the bellow:
27017, 27018, 27019, 28017

Is it an option to use net.port or --port instead of 27017?

**Comment by doomedraven** [comment]
>>  i tried to restart mongodb but nothing change.

you should investigate why mongo doesnt want to start on your system, thats all

**Comment by jbremer** [comment]
Closing as resolved (MongoDB isn't running or so).
