### ISSUE TITLE
Issue with analysis of an exe sample on cuckoo guest, "we are already injected there" and timeout

### ISSUE THREAD

**Issue by nikhilmedapati** [cuckoosandbox/cuckoo#1999]
Hi

Following is my configuration:

- Ubuntu 16.04 as host

- Windows 7 32bit as a guest. 

- Host only network and communication between both the machines is fine.

I submit a sample using _cuckoo submit --machine [label] [path_to_sample]_
The task is successfully added.
Then I run cuckoo. 
The snapshot of guest is also fine, it has the agent running also. Cuckoo starts execution and the sample is sent to the guest

**After a few seconds of waiting, the execution on guest halts when trying to inject a process**
It says, "we are already injected there"

Nothing happens and cuckoo hits the timeout, analysis ends abruptly.

Can someone help me. Thanks in advance.

![2017-12-06-111154_1366x768_scrot](https://user-images.githubusercontent.com/22718949/33646604-674b7d72-da76-11e7-878a-b9179ce29a10.png)

**Comment by nikhilmedapati** [comment]
@jbremer Can you help me out please!!!!

**Comment by jbremer** [comment]
It's not a critical message or anything, but I'll remove it nonetheless.

**Comment by jbremer** [comment]
Oke, done. Will be pushing it in a bit. Closing issue as resolved.
