### ISSUE TITLE
Cuckoo  2.0.5 django web Issue

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2006]
Hello Everyone,

When I am accessing the recent link of web portal it's keep loading instead of showing the results. So, I checked the terminal it's generating the following error:

operation failure: database error: executor error: operationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit

kindly solve this issue.

**Comment by jbremer** [comment]
We've reverted the MongoDB sorting stuff for now and released 2.0.5.1 (`pip install -U cuckoo` as usual). Closing as resolved. Thanks!
