### ISSUE TITLE
Question: does cuckoo clean up at the end of each analysis?

### ISSUE THREAD

**Issue by falcorocks** [cuckoosandbox/cuckoo#2007]
I expected the behaviour of cuckoo sandbox to be the following
- I have a VM with a vanilla Windows7 Snapshot
- I submit a malware for analysis
- Cuckoo starts the vm from the vanilla Snapshot, executes the mw, runs analysis, closes the vm
- If I open the VM all the crap that produced is not found, as it was not saved anywhere

The actual behaviour is the following though:
- submit malware for analysis
- Cuckoo starts the vm from the vanilla Snapshot (maybe), executes the mw, runs analysis, closes the vm
- If I open the VM all the crap that produced is there! Dropped files and all! If I run 10 malware I find the crap that all 10 produced!

Why is this happening? Why is cuckoo saving the state of the vm incrementally?
Why is cuckoo not restoring the snapshot at the end of each run?
I need the system to be perfectly clean and vanilla when the malware is run...
What is going on?

**Comment by doomedraven** [comment]
you should check why your vm snapshot is not restored correctly, bcz cuckoo does it

**Comment by falcorocks** [comment]
I'm using virtualbox, mostly default settings... Ideas on how to check? So it is not normal that these files remain in the in the directories right?

**Comment by doomedraven** [comment]
`cuckoo -d` and see the output. correct isn't normal

**Comment by falcorocks** [comment]
Ok, I will have a look at that. Unfortunately I can't play with the sandbox today or tomorrow. I will let you know over here.
Thanks for the support @doomedraven !

**Comment by doomedraven** [comment]
when you can, good luck :)

**Comment by falcorocks** [comment]
this was solved, everything was working properly
