### ISSUE TITLE
Cuckoo throws [Errno 21] Is a directory: '/home/cuckoo/.cuckoo/monitor/latest' after latetst Update

### ISSUE THREAD

**Issue by hendl** [cuckoosandbox/cuckoo#2008]
Today I updated my Cuckoo Installation to 2.0.5 and after starting the new version cuckoo throws the error.
Can you please help me to fix the problem?

Host is a debian machine.
Update with the command pip install -U cuckoo from 2.0.4

`cuckoo@debian:~$ cuckoo -d

            _       _                   _             _              _            _
          /\ \     /\_\               /\ \           /\_\           /\ \         /\ \
         /  \ \   / / /         _    /  \ \         / / /  _       /  \ \       /  \ \
        / /\ \ \  \ \ \__      /\_\ / /\ \ \       / / /  /\_\    / /\ \ \     / /\ \ \
       / / /\ \ \  \ \___\    / / // / /\ \ \     / / /__/ / /   / / /\ \ \   / / /\ \ \
      / / /  \ \_\  \__  /   / / // / /  \ \_\   / /\_____/ /   / / /  \ \_\ / / /  \ \_\
     / / /    \/_/  / / /   / / // / /    \/_/  / /\_______/   / / /   / / // / /   / / /
    / / /          / / /   / / // / /          / / /\ \ \     / / /   / / // / /   / / /
   / / /________  / / /___/ / // / /________  / / /  \ \ \   / / /___/ / // / /___/ / /
  / / /_________\/ / /____\/ // / /_________\/ / /    \ \ \ / / /____\/ // / /____\/ /
  \/____________/\/_________/ \/____________/\/_/      \_\_\\/_________/ \/_________/

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!

 Our latest blogposts:
 * Cuckoo Sandbox 2.0.5: Office DDE, December 03, 2017.
   Brand new release based on a DDE case study.
   More at https://cuckoosandbox.org/blog/205-office-dde

 * Cuckoo Sandbox 2.0.4, September 06, 2017.
   Introducing Malware Configuration Extraction.
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-204

 * Cuckoo Sandbox 2.0.0, March 30, 2017.
   First Cuckoo package release!
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-v2

2017-12-12 07:52:02,624 [cuckoo.apps.apps] WARNING: This is the first time you're running Cuckoo after updating your local version of Cuckoo. We're going to update files in your CWD that require updating. Note that we'll first ensure that no custom patches have been applied by you before applying any modifications of our own.
2017-12-12 07:52:02,738 [pip.utils] DEBUG: lzma module is not available
2017-12-12 07:52:02,740 [pip.vcs] DEBUG: Registered VCS backend: git
2017-12-12 07:52:02,758 [pip.vcs] DEBUG: Registered VCS backend: hg
2017-12-12 07:52:02,890 [pip.vcs] DEBUG: Registered VCS backend: svn
2017-12-12 07:52:02,891 [pip.vcs] DEBUG: Registered VCS backend: bzr
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: debian 9.3 
Python version: 2.7.13
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0.1 argh:0.26.2 asn1crypto:0.23.0 backports-abc:0.5 beautifulsoup4:4.5.3 capstone:3.0.5rc2 certifi:2017.11.5 cffi:1.11.2 chardet:2.3.0 click:6.6 colorama:0.3.7 configargparse:0.11.0 cryptography:2.1.4 cssutils:1.0.2 cuckoo:2.0.5.1 distorm3:3.3.4 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 h2:2.4.4 hpack:2.3.0 html2text:2016.9.19 httpreplay:0.2.1 hyperframe:4.0.2 idna:2.6 ipaddress:1.0.18 itsdangerous:0.24 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 mako:1.0.7 markupsafe:1.0 olefile:0.43 oletools:0.51 passlib:1.6.5 pathtools:0.1.2 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 psycopg2:2.7.3.2 pyasn1:0.1.9 pycparser:2.18 pycrypto:2.6.1 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.5.0 pyperclip:1.5.32 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pyyaml:3.12 requests:2.13.0 scapy:2.3.2 setuptools:38.2.3 sflock:0.2.17 singledispatch:3.4.0.3 six:1.11.0 sqlalchemy:1.0.8 ssdeep:3.2 tlslite-ng:0.6.0 tornado:4.4.3 unicorn:1.0.1 urllib3:1.22 urwid:1.3.1 volatility:2.6 wakeonlan:0.2.2 watchdog:0.8.3 werkzeug:0.13 yara-python:3.6.3

2017-12-12 07:52:02,968 [cuckoo] ERROR: IOError: [Errno 21] Is a directory: '/home/cuckoo/.cuckoo/monitor/latest'
Traceback (most recent call last):
  File "/home/cuckoo/.local/lib/python2.7/site-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/cuckoo/main.py", line 129, in cuckoo_init
    migrate_cwd()
  File "/home/cuckoo/.local/lib/python2.7/site-packages/cuckoo/apps/apps.py", line 510, in migrate_cwd
    hash_ = hashlib.sha1(open(cwd(filename), "rb").read()).hexdigest()
IOError: [Errno 21] Is a directory: '/home/cuckoo/.cuckoo/monitor/latest'
`

**Comment by hendl** [comment]
The solution was that the latest file was a directory and not the latetest analyzer folder name. 
+ The file creates_exe.py in signatures/windows/ was different?

**Comment by jbremer** [comment]
Before you wander off I have two questions: from which Cuckoo version did you upgrade? And I assume you resolved the issue by removing the `latest` symlink?

**Comment by doomedraven** [comment]
i had the same issue when was updating from 2.0.4.4

**Comment by jbremer** [comment]
Alright, I've fixed this issue for future users. Please find also the commit above & Cuckoo version `2.0.5.2` (i.e., users who will now `pip install -U cuckoo` will automatically get the fixed version). Thanks!
