### ISSUE TITLE
Distributed broken post update to 2.0.5

### ISSUE THREAD

**Issue by iaji** [cuckoosandbox/cuckoo#2009]
I updated to 2.0.5 from 2.0.4 and double checked my uwsgi and nginx configurations for web, api, and distributed and everything seems fine.  I ran a cuckoo clean too.  Webapp is up and submission and sandboxing is OK.  I get a nginx bad gateway error when checking for my nodes via _curl hxxp://IP/api/node_

Update! 
I am getting the following error:
```
2017-12-12 17:48:00,547 [cuckoo.distributed.worker] DEBUG: Starting out with instance: dist.spawner
2017-12-12 17:48:00,550 [cuckoo.distributed.worker] DEBUG: Starting out with instance: dist.scheduler
2017-12-12 17:48:00,561 [cuckoo.distributed.worker] DEBUG: Starting out with instance: dist.status
2017-12-12 17:48:05,556 [cuckoo.distributed.worker] INFO: An exception occurred in instance dist.spawner: (psycopg2.OperationalError) terminating connection due to administrator command
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
 [SQL: 'SELECT node.id AS node_id, node.name AS node_name, node.url AS node_url, node.mode AS node_mode, node.enabled AS node_enabled \nFROM node \nWHERE node.mode = %(mode_1)s'] [parameters: {'mode_1': 'normal'}]
2017-12-12 17:48:10,568 [cuckoo.distributed.worker] INFO: An exception occurred in instance dist.scheduler: (psycopg2.OperationalError) terminating connection due to administrator command
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
 [SQL: 'SELECT node.id AS node_id, node.name AS node_name, node.url AS node_url, node.mode AS node_mode, node.enabled AS node_enabled \nFROM node \nWHERE node.enabled = true AND node.mode = %(mode_1)s'] [parameters: {'mode_1': 'normal'}]
```

Any help/guidance is greatly appreciated!

**Comment by iaji** [comment]
@doomedraven I've poked around the issues pages for at least the past 6 months and you always have helpful insight.

**Comment by doomedraven** [comment]
for distributed cuckoo im using my custom distributed module which saves data to master mongo and all the results can be seen from master node, so here no idea what is wrong wiht psql, @jbremer  any idea?

**Comment by iaji** [comment]
Thanks for the quick response.   It seems like distributed is up and running, I checked and double checked flushed and reset my iptables and I know that connections to my box are not blocked.  Very odd that I get denied access when querying for my cuckoo nodes on the local machine

**Comment by doomedraven** [comment]
but you can open psql shell on host?

**Comment by iaji** [comment]
Yep, already tried switching to new DB's (For both cuckoo and distributed) and running cuckoo clean aswell

**Comment by iaji** [comment]
The problem seems to be in actually contacting the distributed nodes to submit completed analysis.  The database's have proper privileges and look to be functioning properly.

I'm beginning to think this is a problem with nginx's config.  But I'm running what _cuckoo distributed server --nginx_ gives me with a modified IP instead of localhost.

**Comment by jbremer** [comment]
@iaji Did you restart `uwsgi`, `nginx`, *and* the Distributed Worker (see `supervisorctl` from the CWD)? There's a complete migration guide in our documentation https://cuckoo.sh/docs/usage/dist.html#quick-usage. There were some database migrations from `2.0.4` to `2.0.5` so you'll probably want to follow that ;-)

**Comment by iaji** [comment]
@jbremer I've restarted uwsgi, nginx, distributed, and just about every other thing cuckoo is comprised of.  

Here's my cuckoo boot script I run on startup:
`#!/bin/bash
# /etc/init.d/cuckooboot
#
CWD="/home/cuckoo/.cuckoo"
CUCKOO_USER="cuckoo"
VBOX_IP="192.168.56.1"
VBOX_INT="vboxnet0"
#Bring up the virualbox network interface
/usr/bin/VBoxManage hostonlyif ipconfig $VBOX_INT --ip $VBOX_IP --netmask 255.255.255.0 &
#Check if Postgresql is running
if ! /usr/bin/pgrep -x "postgres" > /dev/null
then
     sleep 3
fi
#Start Cuckoo Rooter for Per analysis networking in debug mode
/usr/local/bin/cuckoo -d rooter --sudo &
#Start cuckoo processes for distributed support.  This will launch cuckoo0-3
/usr/bin/supervisord -c $CWD/supervisord.conf
#Start Process Cuckoo0-3
cd $CWD; /usr/bin/supervisorctl start cuckoo:
#Start backend distributed cuckoo
cd $CWD; /usr/bin/supervisorctl start distributed
#Start Cuckoo Webserver, API, distributed submission
/usr/sbin/service uwsgi restart
sleep 3
/usr/sbin/service nginx restart
sleep 3
exit 0`

For now everything is running on one machine, but I plan to expand as soon as I can get distributed talking again.

So checking my uwsgi logs I see:

`Tue Dec 12 19:16:41 2017 - thunder lock: disabled (you can enable it with --thunder-lock)
Tue Dec 12 19:16:41 2017 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/cuckoo-distributed/socket fd 3
Tue Dec 12 19:16:41 2017 - Python version: 2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]
Tue Dec 12 19:16:41 2017 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Tue Dec 12 19:16:41 2017 - Python main interpreter initialized at 0x932440
Tue Dec 12 19:16:41 2017 - your server socket listen backlog is limited to 100 connections
Tue Dec 12 19:16:41 2017 - your mercy for graceful operations on workers is 60 seconds
Tue Dec 12 19:16:41 2017 - mapped 218304 bytes (213 KB) for 2 cores
Tue Dec 12 19:16:41 2017 - *** Operational MODE: preforking ***
Your database is not up-to-date, please upgrade it (run `cuckoo distributed migrate`).`

So I run _cuckoo distributed migrate_ and got some error about an ID being unrecognizable,  well this morning I decided to run that same command with sudo and all of a sudden it works! 

So distributed is running but analyses are still hung on completed for quite some time it seems.

Any tips on improving speed or my boot script?

Also there's one more question I have.  I have old nodes registered before I switched the network the box is sitting on.  Is there any way to delete them without curling to their IP which is no longer accessible?

**Comment by iaji** [comment]
Well I fixed this problem so I'll close this out

**Comment by doomedraven** [comment]
it would good if you could say how, so people with the same problem will fix it also :)

**Comment by iaji** [comment]
> So I run cuckoo distributed migrate and got some error about an ID being unrecognizable, well this morning I decided to run that same command with sudo and all of a sudden it works!

I documented the distributed fix :)

**Comment by doomedraven** [comment]
thanks :)
