### ISSUE TITLE
Question: How can I check if the import from Cuckoo2.0.4 to Cuckoo2.0.5 completed successfully?

### ISSUE THREAD

**Issue by TAKEDA-Yasuhiro** [cuckoosandbox/cuckoo#2010]
Hi.

I used Cuckoo2.0.4 until last week. and I updated to Cuckoo2.0.5 this week.

The update was successfully completed, but there were two errors of import command.

The first error occurred in the import command.
> $ cuckoo --cwd .cuckoo import --symlink /home/cuckoo/.cuckoo.2.0.4
> cuckoo.common.exceptions.CuckooOperationalError: The path that you specified is not a proper Cuckoo setup. Please point the path to the root of your older Cuckoo setup, i.e., to the directory containing the cuckoo.py script!

So I modified `import_.py` as follows.
```
@@ -124,6 +124,8 @@ def sqldump(dburi, dirpath):
 
 def import_cuckoo(username, mode, dirpath):
     version = identify(dirpath)
+    # overwrite to 2.0.4
+    version = "2.0.4"
     if not version:
         raise CuckooOperationalError(
             "The path that you specified is not a proper Cuckoo setup. Please "
```

I tried import again, but the second error occurred.
> $ cuckoo --cwd .cuckoo import --symlink /home/cuckoo/.cuckoo.2.0.4
> OSError: [Errno 17] File exists

So I modified again `import_.py` as follows.
```
@@ -220,6 +222,10 @@ def import_legacy_analyses(mode, dirpath):
         if task_id == "latest":
             continue
 
+        # dealt with .gitignore
+        if task_id == ".gitignore":
+            continue
+
         import_analysis(
             os.path.join(analyses, task_id), cwd(analysis=task_id)
         )
```

Then the import command was successfully completed.

But I have a question.
Does the problem occur when using the imported data as described above?
How can I check if my data has been successfully imported by my work?

**Comment by jbremer** [comment]
You don't have to `cuckoo import` a `2.0.4` setup, that feature is only for importing Cuckoo `1.2`, `2.0-rc1`, `2.0-rc2`, `2.0-dev`, and other legacy versions of Cuckoo. Just upgrade to the latest version of Cuckoo and the rest will happen automatically. I guess we'll have to make this a bit more clear in the `import` command.

**Comment by TAKEDA-Yasuhiro** [comment]
Thank you for your answer.
I will not use the import command from the next update.

If you write your answer at the beginning of the "Upgrading from a previous release" (https://cuckoo.sh/docs/installation/upgrade.html) document, I think that usage will become clearer.
