### ISSUE TITLE
Cuckoo 2.0.5.1 Issue

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2011]
When cuckoo is running for hours after sometime it generates the following errors:
Error: FIXME - exception in resultserver  connection ('192.168.56.101', 62633)
Error: FIXME - exception in resultserver  connection ('192.168.56.102', 62634)
Error: FIXME - exception in resultserver  connection ('192.168.56.103', 62653)
Error: FIXME - exception in resultserver  connection ('192.168.56.104', 62654)

**Comment by jbremer** [comment]
Hi, this isn't necessarily new in the latest version of Cuckoo, but instead has been around since forever. Simply means that some traffic is still coming from one or more VMs after closing 'em down. Just wait a minute or two, I guess ;-)

**Comment by jbremer** [comment]
Do you have more information than just these lines? Otherwise I'll be closing this issue.

**Comment by seantree** [comment]
Kindly close this issue @jbremer
