### ISSUE TITLE
Cuckoo not reading updates from CWD/conf

### ISSUE THREAD

**Issue by iaji** [cuckoosandbox/cuckoo#2012]
Updated to 2.0.5 and I'm seeing some odd things:

1.  In the webapp's "From the Press" Section I see an error message notifying me that version_check has been disabled in cuckoo.conf, when I check cuckoo.conf I have version_check=yes.

2. When running analysis I get a debug message in cuckoo logs notifying me that mitmdump cannot be found: _Mitmdump script doesnt exist at path...._
I have corrected this path to a different one but the error message reads the same path, same error.

I rebooted all services after all my changes.

What is causing cuckoo to not read the conf changes.  

I am running cuckoo distributed, api, and webapp via uwsgi and nginx.

**Comment by iaji** [comment]
@jbremer Any thoughts?  Do you think that a downgrade would smooth things out? 

The weirdest thing about all this is it will read and recognize if I have mitm disabled or not, but will not read my configurations to the sub options for mitm, specifically the path.

**Comment by jbremer** [comment]
I believe the mitmproxy issue was related to #2092. Regarding the 'from the press' thing, perhaps there were some temporary issues retrieving the list of updates from our website.
Any more questions for this issue, otherwise I'll be closing it?

**Comment by jbremer** [comment]
Closing as described above. Feel free to reopen if you have new information.
