### ISSUE TITLE
Suricata returned an error processing pcap.

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#2014]
Has anyone else seen this...fixed this?

`2017-12-14 16:30:23,530 [cuckoo.core.plugins] WARNING: The processing module "Suricata" returned the following error: Suricata returned an error processing this pcap: Command '['/usr/bin/suricata', '-c', '/etc/suricata/suricata.yaml', '-k', 'none', '-l', '/home/cuckoo/.cuckoo/storage/analyses/2/suricata', '-r', '/home/cuckoo/.cuckoo/storage/analyses/2/dump.pcap']' returned non-zero exit status 1`

**Comment by doomedraven** [comment]
execute that in cmd to see why it generate you an error

**Comment by hackdefendr** [comment]
Good suggestion.  Here is what I got:

`cuckoo@cuckoo:~$ /usr/bin/suricata -c /etc/suricata/suricata.yaml -k none -l /home/cuckoo/.cuckoo/storage/analyses/2/suricata -r /home/cuckoo/.cuckoo/storage/analyses/2/dump.pcap
15/12/2017 -- 08:25:04 - <Notice> - This is Suricata version 4.0.3 RELEASE
15/12/2017 -- 08:25:08 - <Error> - [ERRCODE: SC_ERR_CHANGING_CAPS_FAILED(157)] - capng_change_id for main thread failed`

**Comment by hackdefendr** [comment]
Hmm...

If I run the command as sudo it runs perfectly.  So this is a permissions issue against libcap-ng I am guessing.  Any suggestions?

**Comment by doomedraven** [comment]
maybe add cuckoo to suricata group? or any common group for both users?

**Comment by hackdefendr** [comment]
Suricata doesn't create a user/group when installed.  Not for .deb and not from source.  I guess I could try creating one, but I don't know if that is it.
