### ISSUE TITLE
Sending a URL for scanning to distributed cuckoo.

### ISSUE THREAD

**Issue by aghatnekar** [cuckoosandbox/cuckoo#2015]
Hi,

I have set up a working instance of distributed cuckoo successfully. I was wondering if there was any way to send a URL for analysis via the REST APIs of distributed cuckoo. The [document ](http://docs.cuckoosandbox.org/en/latest/usage/dist/#post-api-task) says so. However, `curl http://localhost:9003/api/task -F url=http://example.com` fails to work. I found the below code in /usr/local/lib/python2.7/dist-packages/cuckoo/distributed/views/api.py

`
@blueprint.route("/task", methods=["POST"]
def task_post():
    if "file" not in request.files:
        return json_error(404, "No file has been provided")
`

Can someone guide here?

**Comment by seantree** [comment]
Hi Aghatnekar,

Would you please post a blog or video step by step for setting up a distributed cuckoo, it will be helpful for others if you don't mind please

Thanks & Regards
Seantree

**Comment by aghatnekar** [comment]
Thank you, closing this. I do not require this anymore.
