### ISSUE TITLE
Really Low Scores for Hardcore Malware

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#2019]
First...if you haven't stumbled across theZoo (https://github.com/ytisf/theZoo) well you are really missing out.  That site has live, hardcore malware samples just sitting there ready to be analyzed.

Second...When I throw things like Cerber Ransomware, Wannacry, Petya, Cryptolock, and worse at Cuckoo, I'm expecting no less than scores of 8 or 9, because they are. But despite having Virustotal ratings of 67/69 or worse, despite all the files in my vm being encrypted, and despite the fact that I know these are live samples I am submitting...I'm getting scores of 2.

Am I missing something that would enable better detection?

**Comment by RicoVZ** [comment]
The score is calculated by adding up the severity levels of each matched Cuckoo signature and dividing it by 5.0.

A high score can idicate a file is malicious. To really judge about that, you would also need to see what signatures were matched. The same goes for a low score, it does not mean a file is not malicious.

Which signatures are matched relies on the collected behavioral information. A score of 1-3 when expecting higher might mean some behavior is not being collected. Maybe the sample crashes during the analysis or does not execute at all.

I just tested this Cerber sample https://github.com/ytisf/theZoo/tree/master/malwares/Binaries/Ransomware.Cerber and received a high score.

Have you downloaded all the signatures for your Cuckoo setup? :)
You can do so by executing `cuckoo community`

Could you also post your Cuckoo version and the OS you have installed on your guest machine(s)?

![image](https://user-images.githubusercontent.com/8687431/34086582-2992f3e0-e39d-11e7-8f99-3900880fd8af.png)

![image](https://user-images.githubusercontent.com/8687431/34086597-474ee15a-e39d-11e7-843c-34f05998192b.png)

**Comment by hackdefendr** [comment]
Yep...I did download the community signatures, and have also added additional yara rules from https://github.com/Yara-Rules/rules. Considering I followed the cuckoo documentation to install Cuckoo, I expect to see the same results as you. Even the screenshots from the analysis show the Ransomware message, which makes it appear that the malware ran successfully.

* Cuckoo 2.0.5.2
* XUbuntu 16.04

**Comment by RicoVZ** [comment]
Alright, then we know the signatures are present. Could you start Cuckoo in debug mode, analyse a sample (the Cerber one?), paste the logs and post a link to the logs here?

You can start Cuckoo in debug mode using `cuckoo --debug`

Also, do you mean you have installed XUbuntu 16.04 on the host machine? If so, please also post the OS of the virtual machines used to analyse the malware (the guest machines).

**Comment by hackdefendr** [comment]
Yes the host is XUbuntu 16.04, the guest VM is Windows 10 Pro (1709).

**Comment by hackdefendr** [comment]
Well...not sure if adding all of the rules from the Yara-Rules repository did something. This time running Cerber through Cuckoo I get: **This file is very suspicious, with a score of 12.6 out of 10!** 

Additionally, I get proper results from Suricata now. I'm going to re-submit a few others and see what happens.
