### ISSUE TITLE
Question: Submit File via Network Share

### ISSUE THREAD

**Issue by hillijunior** [cuckoosandbox/cuckoo#2020]
Hi guys, 

I hope I´m right here with my question. 

I created a network share on my Cuckoo Host (running on Ubuntu) and mounted it on my Windows 10 machine. 

Is there a way that cuckoo will automatically start an analysis as soon as I copy some malware samples into this network share? 

Thank you for your Ideas :-)

**Comment by RicoVZ** [comment]
Hi hillijunior,

Cuckoo does not have the ability to do this. But it does have a web API for reasons exactly like this.
See http://docs.cuckoosandbox.org/en/latest/usage/api/ on how to start it and use it.

You can use the call `tasks/create/file` This one: http://docs.cuckoosandbox.org/en/latest/usage/api/#tasks-create-file

I suggest writing a small Bash/Python script reads files from your share and then submits them to the API.

**Comment by christauff** [comment]
.  B.s..   b.      B.
