### ISSUE TITLE
Yara integration

### ISSUE THREAD

**Issue by d4n13l4** [cuckoosandbox/cuckoo#2021]
Hello

So I installed cuckoo and it's working but I don't match any yara rules, probably because I only have 3 on my cuckoo/data/yara folder so I want to add more from https://github.com/Yara-Rules/rules but I don't know how
Should I just copy all this folder into my yara folder? do I need to add something to my config files.

Thanks for your help

**Comment by hackdefendr** [comment]
First...did you run the command: "cuckoo community" ?  This will download several rules and signatures.

Then, yes, all you have to do is copy yara rules into the ~/.cuckoo/yara folder and restart cuckoo.

**Comment by d4n13l4** [comment]
Thanks! this help
