### ISSUE TITLE
Moloch is not enabled! (But it is)

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#2022]
I have Moloch server running on the same system that cuckoo is running.  

Here is my configuration from reporting.conf:

[moloch]
enabled = yes
host = 1.2.3.4
insecure = yes
moloch_capture = /data/moloch/bin/moloch-capture
conf = /data/moloch/etc/config.ini
instance = cuckoo

Yet when I click on any Moloch links in an analysis summary page, I get an error page stating that Moloch is not running.

Any ideas?

**Comment by seantree** [comment]
Which moloch version are you using?

**Comment by SparkyNZL** [comment]
you will need to install moloch from https://molo.ch 

You will need to setup an ES node(s) also
