### ISSUE TITLE
Sniffer Error

### ISSUE THREAD

**Issue by aktibista** [cuckoosandbox/cuckoo#2023]
I am getting this error: (Probably need whitelisting?)

2017-12-18 15:27:01,698 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py",
module.stop()
File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/
self._check_output(out, err)
File "/home/cuckoo/venv/local/lib/python2.7/site-packages/cuckoo/auxiliary/
"the following standard error output: %r." % line
CuckooOperationalError: Potential error while running tcpdump, did not expect the following standard error output: '10 packets dropped by interface'.

**Comment by aktibista** [comment]
Adding the following lines to sniffer.py seems to have fixed the error:

 err_whitelist_ends = (
     "packet captured",
     "packets captured",
     "packet received by filter",
     "packets received by filter",
     "packet dropped by kernel",
     "packets dropped by kernel",
     **"packet dropped by interface", 
     "packets dropped by interface",** 
     "dropped privs to root",
 )

**Comment by SparkyNZL** [comment]
did you disable apparmor and run the follow command to allow the ability to capture traffic as non-root

sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump 

?

**Comment by jbremer** [comment]
Thanks @aktibista. Committed these changes and will be pushing 'em shortly.

**Comment by jbremer** [comment]
This is part of our `2.0.6` release, closing as resolved. Thanks again!
