### ISSUE TITLE
AttributeError: Config instance has no attribute 'cuckoo'

### ISSUE THREAD

**Issue by rvshiva** [cuckoosandbox/cuckoo#2024]
Hi,
First time i install cuckoo. I faced lot of errors while running cuckoo. For other errors i got help from different sites. There is no solution in any site for "AttributeError: Config instance has no attribute 'cuckoo"

For your Info: I installed in Win7 as a host and installed Virtual box inside i installed win7.

while running cuckoo, the below error is displayed
traceback <most recent call last>:
file " cuckoo path\cuckoo.py", line 132, in<module>
cuckoo_main<max_analysis_count=args.max_analysis_count>
file " cuckoo path\cuckoo.py", line 78, in cuckoo_main
sched.start()
file " cuckoo path\lib\cuckoo\core\scheduler.py", line 579, in start
self.initialize()
file "cuckoo path\lib\cuckoo\core\scheduler.py", line 513, in initialize
machinery_name = self.cfg.cuckoo.machinery
AttributeError: Config instance has no attribute 'cuckoo'

Help me to resolve this issue.

**Comment by rvshiva** [comment]
Error 2:
 traceback<most recent call last> :
file " cuckoo path\cuckoo.py", line 129, in <module>
test=args.test)
file "cuckoo path\lib\cuckoo\core\startup.py", line 195, in init_modules
import_plugin(modules.machinery." + Config().cuckoo.machinery)
AttributeError: Config instance has no attribute 'cuckoo'

Help me to resolve this issue also.

**Comment by doomedraven** [comment]
and how do you think it possible to help without config,full log, versions etc etc etc?

**Comment by rvshiva** [comment]
I m new in installing. I don't know. what are the information u need from me?
What should i do now to resolve it.? help me.

**Comment by jbremer** [comment]
Please install a version that's not 1-2 years old ;-)

**Comment by rvshiva** [comment]
Ok..
