### ISSUE TITLE
ERROR: Type of config parameter auxiliary:sniffer:interface not found!

### ISSUE THREAD

**Issue by ddehban** [cuckoosandbox/cuckoo#2026]
I tried cuckoo version 2.0.5
and installed based on:
https://medium.com/@warunikaamali/cuckoo-sandbox-installation-guide-d7a09bd4ee1f

but it starts with Error

> 2017-12-24 11:24:04,187 [cuckoo.common.config] ERROR: Type of config parameter auxiliary:sniffer:interface not found! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.

**Comment by doomedraven** [comment]
why you just not follow the `official up to date` manual?

**Comment by ddehban** [comment]
Maybe bcoz official manual is a little complicated for me as a newbie user.
any way could you help me to solve the issue or you insist to follow manual from beginning?

**Comment by doomedraven** [comment]
as newbie you should read and reread the oficial manual till you understand it, to avoid problem like this. there no interface in  aux config, so don't put in configs values which is not origilanlly there -> again don't use out of date mans

+ read the comments in configs
```
# We used to define the network interface to capture on in auxiliary.conf, but
# this has been moved to the "interface" field of each Virtual Machinery
# configuration.
```

**Comment by ddehban** [comment]
Ok, thanks for you advise

**Comment by CorbinHu** [comment]
How can you solve this problem?I also got the same error.
