### ISSUE TITLE
Cuckoo Web error 500

### ISSUE THREAD

**Issue by joydragon** [cuckoosandbox/cuckoo#2032]
Hello,

I'm havng issues with cuckoo web and trying to check the VM Memory Dump (and also other parts of the cuckoo analysis). Whenever I try to click on the link and get to the URL it comes back with the following error:

![cuckoo error 500](https://user-images.githubusercontent.com/4154219/34415081-783e04f4-ebcb-11e7-932c-da7467988c23.png)

The guest machine is a Windows 7 on a Centos 7 Host (I know I should use Ubuntu, but I had a Centos machine, and everything else was working fine).

I've also attached the analysis.log and the cuckoo.log:
[analysis.log](https://github.com/cuckoosandbox/cuckoo/files/1591505/analysis.log)
[cuckoo.log](https://github.com/cuckoosandbox/cuckoo/files/1591506/cuckoo.log)

Can you point me in the right direction to solve this?

Thanks!

**Comment by SparkyNZL** [comment]
are you running this through a Reverse Proxy  and IIS ?

**Comment by simuset** [comment]
facing the same problem here

**Comment by RicoVZ** [comment]
@joydragon Would it be possible for you to share the memory.dmp?

**Comment by jbremer** [comment]
Closing issue for lack of additional information - feel free to reopen if you have an update for us.
