### ISSUE TITLE
Installing cuckoo on dual-booting PC Ubuntu 16.04 Desktop +Windows 8

### ISSUE THREAD

**Issue by yahyeabukar** [cuckoosandbox/cuckoo#2033]
I have only one computer with windows 8 installed  and i would like to install Ubuntu 16.04 (without hurting my Windows 8 )in order to install cuckoo sandbox.  Installing Ubuntu there are three Options: 
 Option 1: Try before you install . Option 2: Install Ubuntu inside Windows and  Option 3 : Something Else.
What is the best option for my cuckoo usage and performance?? Thanks in advance

**Comment by doomedraven** [comment]
2, best dedicated cuckoo host

**Comment by yahyeabukar** [comment]
Thanks @doomedraven
