### ISSUE TITLE
[cuckoo.common.config] ERROR: Config section cuckoo:Cuck oo not found!

### ISSUE THREAD

**Issue by rvshiva** [cuckoosandbox/cuckoo#2035]
Hi Friends,
I have the below issue while running Cuckoo. First time i m installing it and running it in windows 7 machine. Host & Vbox guest both installed with Windows 7.

C:\Python27\Lib\site-packages>cuckoo -d
                      __
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

2017-12-31 16:03:43,223 [cuckoo.common.config] ERROR: Config section cuckoo:Cuck
oo not found!
2017-12-31 16:03:43,223 [cuckoo] CRITICAL: CuckooConfigurationError: Configurati
on value cuckoo:cuckoo:process_results not present! This may indicate that you'v
e incorrectly filled out the Cuckoo configuration, please double check it.

Can you help me to solve this issue.

**Comment by rvshiva** [comment]
[virtualbox.zip](https://github.com/cuckoosandbox/cuckoo/files/1595126/virtualbox.zip)

This is my config files. Check where i made a mistake. If you wanna any other info,i will share it.

**Comment by doomedraven** [comment]
as error says, in cuckoo there no section `Cuckoo` why did you rename `[cuckoo]` into `[Cuckoo]`?

**Comment by rvshiva** [comment]
OMG...Sorry doomedraven..Thank you so much...
