### ISSUE TITLE
Virus total issue with cuckoo sandbox

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2040]
Hi,

Sometimes cuckoo shows the result for VT detection's & sometimes not. I have analyse same sample 4 times but it doesn't display the VT count.

Kindly fix this issue

**Comment by doomedraven** [comment]
use VT private api key for it, the provided key is common for all cuckoo users, so there could be limit per reqs by key

**Comment by jbremer** [comment]
The public API key is indeed rate limited. Expect results accordingly ;-) Closing as resolved.
