### ISSUE TITLE
Files & Folders bug

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2041]
Hi,

I am testing the some setups on cuckoo by manipulating time and it brings the different output each time.
First I have configured the Default time of 300 seconds & Critical Timeout 60 Seconds,
It display 200 Dropped Files & 0 Folders
Then I Configured Default time of 900 seconds & Critical Time out 60 Seconds..
It display 150 Dropped Files & 3 Folders

Then I Configured Default time of 120 Seconds & Critical Timeout 300 Seconds
It brings 250 Dropped Files & 2 Folders.

I don't understand why each time it's showing the different result.

**Comment by doomedraven** [comment]
study the behavior of the malware by yourself to understand that, it can be affected by tons of things, everything depends of the malware

**Comment by SparkyNZL** [comment]
Reitterate what Doomedraven said, there can be many factors causing these differing results such as the time in which the network is detected, perhaps the malware times out after 300sec and then starts to do its thing. I would suggest that if its an important piece of malware that you start to pull it to bits with IDA or Olly and look at how it works.

**Comment by Vaibs111** [comment]
If this the case can any one please suggest what configuration should be set for the best results?
Please suggest the Timeout and Critical Timeout that seems to be the best.
Thanks!!

**Comment by doomedraven** [comment]
there no magic bullet for it, that you need to put depends on your needs

**Comment by jbremer** [comment]
As mentioned above it basically depends on the sample that you're analyzing. Do some research on it and you'll find useful information ;-) Closing as resolved.
