### ISSUE TITLE
Cuckoo stuck Waiting for analysis tasks

### ISSUE THREAD

**Issue by jmg49** [cuckoosandbox/cuckoo#2044]
hi, 

i've set up cuckoo sandbox, virtualbox , but no analysis starts , cuckoo is waiting ...

i've submitted files with the submit script but nothing happened, 

cuckoo found my seven VM , snapshot too,  mongodb is up 

ubuntu 16.0.4.3 64b
Cuckoo Sandbox 2.0.5

i 'm sure i made confusions with sudo / normal account .... 

thanks in advance

**Comment by doomedraven** [comment]
no logs no problems ;)

**Comment by jmg49** [comment]
sorry, 

cuckoo.log : 

2018-01-05 17:08:12,706 [cuckoo.core.resultserver] DEBUG: ResultServer running on 10.48.54.180:2042.
2018-01-05 17:08:12,707 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-01-05 17:08:13,278 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm seven1
2018-01-05 17:08:13,422 [cuckoo.machinery.virtualbox] DEBUG: Restoring virtual machine seven1 to sn1
2018-01-05 17:08:13,506 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2018-01-05 17:08:13,524 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.

there are no more entries in this log when i submit sample ...

i've tried to launch submit with su account too, and nothing 

cuckoo server user accounts : 
server1
cuckoo

1 virtualbox VM Win Seven 32

in fact i don't know which account i must install cuckoo , virtualbox  ....

**Comment by doomedraven** [comment]
1. provide how you upload web/cli
2. if web web log, if cli, cli error maybe?

**Comment by jmg49** [comment]
i'm using cli python submit.py , 

i dont'have a cuckoo folder with /core and submit.py in my /home/cuckoo ...
it's in /usr/local/lib/python2.7/dist-packages/cuckoo/core/submit.py  i don't know why

**Comment by doomedraven** [comment]
isn't weird, is correct, did you read the manual?

**Comment by jmg49** [comment]
yes i did ....
i 've tried with cuckoo web , my task is pending for ages ....

**Comment by jmg49** [comment]
all is fine now, 
.conf files verified many errors ,  
thanks for your help

**Comment by doomedraven** [comment]
i think you have problems with db pointed by web and by cuckoo, as i saw it in past

**Comment by jbremer** [comment]
Make sure you run everything with the same user & CWD. I think this can be closed?

**Comment by d4n13l4** [comment]
hey @jmg49 what error did you have that cause this error?
I recently change to mysql db and I change the cuckoo.conf file to add the path to my db but my analysis are stucked in pending, no logs error like you also.

basically I did this
    sudo apt-get install mysql-server python-mysqldb -y
    mysql -u root -p
    create database cuckoo;
    grant all privileges on cuckoo.* to cuckoo@localhost identified by 'password' ;
    flush privileges;
    quit;

in the cuckoo.conf add mysql://cuckoo:password@localhost/cuckoo

**Comment by jbremer** [comment]
Closing issue. Please reopen if new information is available.

**Comment by smclinden** [comment]
Same issue. Upgraded to Postgres, changed the connection setting in the cuckoo.conf file. The process log shows that there are postgres processes running but there are now 15 files stuck waiting for analysis. Even stranger, Cuckoo appears to still be updating the cuckoo.db file as well.

Any suggestions would be appreciated!

cirt@cuckoo:/var/log/postgresql$ ps -ef | grep cuckoo
cirt      4423     1  0 Oct31 ?        00:01:09 /usr/sbin/tcpdump -U -q -s 0 -n -i vboxnet0 -Z cirt -w /home/cirt/.cuckoo/storage/analyses/1067/dump.pcap host 192.168.56.101 and not ( dst host 192.168.56.101 and dst port 8000 ) and not ( src host 192.168.56.101 and src port 8000 ) and not ( dst host 192.168.56.1 and dst port 2042 ) and not ( src host 192.168.56.1 and src port 2042 )
cirt      4743  4794  6 Dec05 ?        00:58:24 /usr/bin/python /usr/local/bin/cuckoo -d -m 10000
cirt      4744  4794  1 Dec05 ?        00:13:50 /usr/bin/python /usr/local/bin/cuckoo process p0
cirt      4745  4794  1 Dec05 ?        00:13:53 /usr/bin/python /usr/local/bin/cuckoo process p3
cirt      4746  4794  1 Dec05 ?        00:13:54 /usr/bin/python /usr/local/bin/cuckoo process p2
cirt      4747  4794  1 Dec05 ?        00:13:52 /usr/bin/python /usr/local/bin/cuckoo process p1
postgres  4763 15050  0 Dec05 ?        00:00:59 postgres: cuckoo cuckoo 192.168.100.211(35836) idle
postgres  4764 15050  0 Dec05 ?        00:00:59 postgres: cuckoo cuckoo 192.168.100.211(35834) idle
postgres  4765 15050  0 Dec05 ?        00:00:59 postgres: cuckoo cuckoo 192.168.100.211(35840) idle
postgres  4766 15050  0 Dec05 ?        00:00:59 postgres: cuckoo cuckoo 192.168.100.211(35842) idle
postgres  4787 15050  0 Dec05 ?        00:05:35 postgres: cuckoo cuckoo 192.168.100.211(35880) idle
cirt     15814 15741  0 07:18 pts/0    00:00:00 grep --color=auto cuckoo
cirt     46338     1  0 Nov13 ?        00:00:58 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/cuckoo-api.ini --daemonize /var/log/uwsgi/app/cuckoo-api.log
cirt     46434     1  0 Nov13 ?        03:35:35 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/cuckoo-web.ini --daemonize /var/log/uwsgi/app/cuckoo-web.log
cirt     46445 46338  0 Nov13 ?        00:06:55 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/cuckoo-api.ini --daemonize /var/log/uwsgi/app/cuckoo-api.log
cirt     46446 46338  0 Nov13 ?        00:03:25 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/cuckoo-api.ini --daemonize /var/log/uwsgi/app/cuckoo-api.log
cirt     46452 46434  0 Nov13 ?        03:41:50 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/cuckoo-web.ini --daemonize /var/log/uwsgi/app/cuckoo-web.log
cirt@cuckoo:/var/log/postgresql$
