### ISSUE TITLE
Before and after comparison, cuckoo sandbox

### ISSUE THREAD

**Issue by emmanueltsukerman** [cuckoosandbox/cuckoo#2046]
I'd like to insert a custom module into cuckoo sandbox that allows cuckoo to analyze the guest before executing my sample, analyzes the guest at termination of the sample's run, and then compares "before" and "after". 

I was able to run the "before" function and I was able to run the "after" function. However, I haven't yet figured out how to share their outputs in order to compare. Please advise.

I've read the documentation. However, I didn't find the issue I'm discussing being addressed explicitly. Thanks.

**Comment by doomedraven** [comment]
it called baseline analysis

**Comment by emmanueltsukerman** [comment]
Thanks, that's good to know. I looked up the keyword "baseline" in the documentation. I found this:
Baseline (cuckoo/processing/baseline.py) - baseline results from gathered information
Any suggestions on how to proceed?

**Comment by doomedraven** [comment]
```
cuckoo submit --help
Usage: cuckoo submit [OPTIONS] [TARGET]...

  Submit one or more files or URLs to Cuckoo.

Options:
  -u, --url           Submitting URLs instead of samples
  -o, --options TEXT  Options for these tasks
  --package TEXT      Analysis package to use
  --custom TEXT       Custom information to pass along this task
  --owner TEXT        Owner of this task
  --timeout INTEGER   Analysis time in seconds
  --priority INTEGER  Priority of this task
  --machine TEXT      Machine to analyze these tasks on
  --platform TEXT     Analysis platform
  --memory            Enable full VM memory dumping
  --enforce-timeout   Don't terminate the analysis early
  --clock TEXT        Set the system clock
  --tags TEXT         Analysis tags
  --baseline          Create baseline task <----------------------------------------------
  --remote TEXT       Submit to a remote Cuckoo instance
  --shuffle           Shuffle the submitted tasks
  --pattern TEXT      Provide a glob-pattern when submitting a directory
  --max INTEGER       Submit up to X tasks at once
  --unique            Only submit samples that have not been analyzed before
  --help              Show this message and exit.
```

**Comment by jbremer** [comment]
Currently it's not very trivial to do this, but certainly possible. Could you describe your end goal - perhaps we could give you some pointers.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - feel free to reopen if you have an update for us.
