### ISSUE TITLE
Information in the reports of PDF/Word scanned files

### ISSUE THREAD

**Issue by neonov1y** [cuckoosandbox/cuckoo#2047]
Hello guys.

I want scan PDF and Word files and I want know what kind of information typically for this formats in them reports.

Now I no have information about registry in Behavioral analyses, it must be? (In the reports of exe files I see it)

Thank you.

**Comment by doomedraven** [comment]
dude all that depends of the pdf/word files, which technics they using, etc etc, learn how to analyze them by hand than you will get better idea how it works

**Comment by neonov1y** [comment]
Ok thanx, sorry about topic.

**Comment by jbremer** [comment]
We'll be working on more blogposts this year, each highlighting specific analyses and things to look at. Hopefully we can teach our users some nice tricks. Please stay tuned :-) For now I'll be closing this issue, though.
