### ISSUE TITLE
analysis interrupts with segmentation fault core dumped error

### ISSUE THREAD

**Issue by falcorocks** [cuckoosandbox/cuckoo#2051]
I'm trying to analyse roughly 20000 samples on a Ubuntu 16.04 32GB RAM machine with 5 Windows 7 guests. Cuckoo 2.0.5
Randomly but roughly every 80/100 samples cuckoo abruptly crashes with the message
`Segmentation fault, core dumped`.
Ideas?
I'm not familiar with debugging with cuckoo, if you need me to provide logs or similar let me know explicitly how to retrieve them :)

I would not mind having 1% of my analysis fail, as long as it keeps analysing samples without stopping

PS this is an on purpose machine, nothing else (except for elasticsearch) was installed aside from what is in the instruction of cuckoo

**Comment by doomedraven** [comment]
is it in process or cuckoo ?
enable both in debug mode `-d`

and post logs to see which was last started part

**Comment by falcorocks** [comment]
I believe in cuckoo.
The way i'm using cuckoo is I open one terminal and type
`cuckoo`
and then I open another one and type
`cuckoo submit FOLDER`.
By enabling both in debug mode you mean calling the former as 
`cuckoo -d`?

"and post logs to see which was last started part" where do I find these?

**Comment by doomedraven** [comment]
__i would suggest you read and reread the cuckoo documentation__ if you want to analyze so big numbers of samples and not even use of `cuckoo process`(disabling in cuckoo.conf) to speedup...

start cuckoo with -d and post the log, well where do you see the `core dump` that log you need to post

**Comment by falcorocks** [comment]
https://gist.github.com/falcorocks/ee1d539e3a3db340e977678292e891d3
Here you go, this is the output of cuckoo -d right up to the moment it crashes.
As you can see there are some endless error messages about a font related to the creation of a pdf report but I highly doubt that is responsible for the segmentation fault.

Now I will start it over disabling the pdf reporting, to see if it stops failing.

**Comment by doomedraven** [comment]
well it looks as it generated by font load, try disable pdf generation and let us know

**Comment by falcorocks** [comment]
ok, running another batch now. BTW it is amazing that every time I have an issue one of you guys replies and so quick also!
Thank you for the support!
I will invest in looking at the other options you have suggested.

I want to ask you something else, although unrelated to the issue.
By default, will cuckoo analyse also dropped files during analysis iteratively? Is there a specific setting about it? I can't find a definitive answer

**Comment by doomedraven** [comment]
depends what you mean with analysis dropped, is part of main analysis

**Comment by falcorocks** [comment]
basically I would need an iterative analysis of dropped files.
An example of what I would like:
- I throw 12345.doc in cuckoo
- 12345.doc is opened in Word, a macro downloads the file important.exe in the background, the word file shows "please find your invoice in the file important.exe"
- cuckoo then runs a brand new full analysis on important.exe, which turns out to be ransomware

**Comment by doomedraven** [comment]
why? if you can get all that in one analysis flow

**Comment by falcorocks** [comment]
So I deduce from your answer that the normal behaviour should be that dropped files are executed in the same analysis flow. Correct?
Because this is not what I am observing, dropped files are merely listed and that's it.

**Comment by doomedraven** [comment]
correct, well that can be related to many things, but normally they should be executed, maybe there delay before execution and your analysis timeout, etc etc, you need to investigate, everything depends on how malware behavs

**Comment by jbremer** [comment]
Closing issue for lack of additional information. Feel free to reopen or email me if you have said crash information.
