### ISSUE TITLE
VirusTotal offline analysis

### ISSUE THREAD

**Issue by paulaldana23** [cuckoosandbox/cuckoo#2052]
Hello,

I have my Cuckoo Sandbox setup on an laptop that's going to be used offline. Knowing that VirusTotal needs internet connectivity for it to work, is there any way we could have the VirusTotal's functionality (scanning a file for known malware infection) during offline malware analyses? Any known workarounds?

Any help would be appreciated!

Thanks,

Paul

**Comment by doomedraven** [comment]
clamav ?

**Comment by Nwinternights** [comment]
Maybe IRMA.

**Comment by razuz** [comment]
IRMA will still need some network to update AV-s, but for offline I would suggest that as it can be isolated according to need and you'll still have like a small VT in house ;)

**Comment by paulaldana23** [comment]
Thank you all for replying promptly! 

@doomedraven ClamAV would need to be ran separately from Cuckoo and not integrated with the analysis, am I right? Or is there a way to integrate ClamAV to the analysis and have the result show up on the static analysis part of the report?

@razuz so IRMA should be installed on my machine and updated from time to time in order to work during offline analysis unlike VirusTotal which does not need any installation on my system for it to work since it's purely online, correct?

**Comment by doomedraven** [comment]
you can install it in cuckoo host, but you would need to backport the module from cuckoo-mod to be able to use clamav with cuckoo

**Comment by paulaldana23** [comment]
@doomedraven forgive me for asking this question, but where is the cuckoo-mod file exactly?  I tried looking in the "conf" folder. I assumed it would be something similar as in the processing.conf file just like VirusTotal and IRMA, but it's not.

**Comment by doomedraven** [comment]
https://github.com/spender-sandbox/cuckoo-modified/blob/55bafa2a325379418da9c2cdc66530458d827d17/lib/cuckoo/common/objects.py#L374

**Comment by paulaldana23** [comment]
Thanks @doomedraven !

**Comment by paulaldana23** [comment]
Hello @razuz,

I'm trying to figure out how to integrate IRMA with Cuckoo Sandbox. I'm a little confused since IRMA's installation is talking about its own virtual machine. Is this a different setup than that of Cuckoo's? If you may, could you please point me to the right direction of how to properly integrate IRMA with Cuckoo please? I'll greatly appreciate it.

Thanks,

Paul

**Comment by doomedraven** [comment]
you just need to fill the data in processing.conf
https://github.com/cuckoosandbox/cuckoo/blob/6fb0b0fd17ebd0a08424166287aca88fee53c117/cuckoo/private/cwd/conf/processing.conf#L162

**Comment by jbremer** [comment]
Closing issue as resolved. Thanks.
