### ISSUE TITLE
Where does the information analyzed by cuckoo sandbox exist?

### ISSUE THREAD

**Issue by PointerWild** [cuckoosandbox/cuckoo#2056]
Could you please tell me , where does the information analyzed by cuckoo sandbox exist?

**Comment by paulaldana23** [comment]
You could access it from the web interface. You need to run "cuckoo web" on a terminal first then you could access the Cuckoo Sandbox GUI through a browser by typing "localhost:8000" on the address bar.

**Comment by PointerWild** [comment]
3Q.   I want to transport this information to another system , how could i deal with this issue?

**Comment by doomedraven** [comment]
mongo sync?

**Comment by jbremer** [comment]
Check `~/.cuckoo` and you might check MongoDB, too. Closing as resolved.
