### ISSUE TITLE
When adding a new reporting model the config section is not auto-detected.

### ISSUE THREAD

**Issue by KasperskyZiv** [cuckoosandbox/cuckoo#2057]
As far as i could see, and correct me if i'm wrong, but my new section in the reporting config wasn't detected automatically. I had to go over some of the config code before i added a new "schema" to **Config.configuration** field like this:
```
"reporting": {
            "myModel": {
                "field": Boolean(False),
                "another_field": Path(
                        exists=True, writable=False, readable=True
                ),
                "url": String(sanitize=True),
                "username": String(),
                "password": String()
    }
}
```
Is this how i'm to make it work?
If so why is it not updated in the manual..

Thanks!
ziv

**Comment by doomedraven** [comment]
is to verify what a user has correct config values

**Comment by krisleonard-mcafee** [comment]
Would it be possible for Cuckoo to add a required configuration definition method to the abstract Report object? This would allow developers adding new reporting modules to define the configuration requirements in their own code and not require modification of Cuckoo's config.py.

**Comment by jbremer** [comment]
Yes, that'd make sense and we've considered in the past already, but simply didn't have the time to implement it yet. Feel free to do a PR ;-)

**Comment by jbremer** [comment]
Closing issue as there's a PR now. Merging the PR will require some more thoughts, though. To be done in the future.
