### ISSUE TITLE
Issue when deleting reports

### ISSUE THREAD

**Issue by patrika** [cuckoosandbox/cuckoo#2058]
While using the method mentioned in #1515  to delete multiple reports, mongod cpu load increase drastically and the webgui will shortly after become slow and return HTTP code 504.

The deletion works fine if you sleep about 60 seconds between every delete although this will take forever if you would like to delete 10,000 reports. 

The reason for this is that I am running out of disk and would like to remove specific reports and not all.

**Comment by doomedraven** [comment]
your link points to this issue

**Comment by patrika** [comment]
Yes sorry updated :)

**Comment by doomedraven** [comment]
do search on the issues i posted code how to do whole cleanup using that rest api

**Comment by patrika** [comment]
@doomedraven I not able to find the issues you are mentioning, could you be so kind and post a link?

**Comment by doomedraven** [comment]
no time to search the adapted version
you will need to readapt it if needed

```
FULL_DB = False
if repconf.mongodb.enabled:
    import pymongo
    results_db = pymongo.MongoClient(
                     repconf.mongodb.host,
                     repconf.mongodb.port
                 )[repconf.mongodb.db]
    FULL_DB = True

@route("/tasks/delete_many", method="POST")
@route("/v1/tasks/delete_many", method="POST")
def tasks_delete():
    response = {}
    tasks = request.forms.get("ids", "")
    tasks = tasks.split(",")
    for task_id in tasks:
        task = db.view_task(task_id)
        if task:
            if task.status == TASK_RUNNING:
                response.setdefault(task_id, "running")
                continue
            if db.delete_task(task_id):
                delete_folder(os.path.join(CUCKOO_ROOT, "storage",
                                           "analyses", "%d" % task_id))
            if FULL_DB:
                task = results_db.analysis.find_one({"info.id": task_id})
                if task is not None:
                    for processes in task.get("behavior", {}).get("processes", []):
                        [results_db.calls.remove(call) for call in processes.get("calls", [])]

                    results_db.analysis.remove({"info.id": task_id})
            else:
                response.setdefault(task_id, "deletion failed")
        else:
            response.setdefault(task_id, "not exists")
    response["status"] = "OK"
    return jsonize(response)
```

**Comment by jbremer** [comment]
I suppose the real reason for the slow Cuckoo Web Interface is the fact that you're simply running `cuckoo web`? If so, only one HTTP request is handled at any given time. Please use the `uwsgi`+`nginx` (see our documentation) setup, I think that would improve your situation.
Let us know!

**Comment by patrika** [comment]
Hi,

I am already using the uwsgi + nginx setup, so that is not the problem. Made a workaround that connects directly to mongodb and removes the content that way. Seems to be working better so I guess this issue could be closed, unless someone else is experiencing this.

**Comment by jbremer** [comment]
Thanks, closing issue as sort of resolved. I agree that this could be improved, though.
