### ISSUE TITLE
VM XP sp3x86 error or not ?

### ISSUE THREAD

**Issue by jmg49** [cuckoosandbox/cuckoo#2060]
hello, 

when analysing sample on a xp sp3 x86 i obtain the following message in dashboard : 

It appears that the environment of your Virtual Machine is partially unknown to us in the sense that we haven't added special support for it yet (for 95% of the time the analysis will work perfectly fine, though)

i've setup profile in memory.conf to WinXPSP3x86 and in virtualbox.conf too osprofile = WinXPSP3x86

is the analyse result reliable in spite of this error message ?

thanks

**Comment by doomedraven** [comment]
that is your system internals, as can be lang etc etc

**Comment by jbremer** [comment]
Yes, it's fine. It just means that, e.g., https decryption of traffic doesn't work for your VM. Closing as resolved.
