### ISSUE TITLE
 Error fetching configuration file!

### ISSUE THREAD

**Issue by saasthavasan** [cuckoosandbox/cuckoo#2062]
I am using windows 7 32bit as my machine, I am not getting any process tree results or anything in the behavior analysis section of the cuckoo report . But in one of the screenshots that was taken during the analysis it is showing that,
" Cuckoo Error: Error fetching configuration file! This is a serious error. if encountered, please notify the Cuckoo developers as this error prevents analysis." 

![nofetch](https://user-images.githubusercontent.com/20906661/35042533-19e1eaee-fbaf-11e7-8f9c-a8c346f68af1.jpeg)

I referred to issue [#1388](https://github.com/cuckoosandbox/cuckoo/issues/1388) where same error was addressed and I tried disabling UAC but still I am getting same error.

**Comment by saintxseiya** [comment]
Hi,

I have the same result on Windows 10 with the 0.8 agent.

In addition, i have deactivated the UAC.

I still also get the message that the agent is has not been executed as admin, but i started the script in an admin CMD, so what could be the issue?

Cheers,

Saint

**Comment by saintxseiya** [comment]
Created a workaround for win10 by executing the Python IDLE as administrator and loading the agent from there. I do not know if this fix the whole problem, but at least it starts the analysis.

**Comment by saasthavasan** [comment]
How did you run IDLE as administrator? 
Did you run CMD as administrator and then run idle.py and loaded agent.py in it?

**Comment by saintxseiya** [comment]
Hi,

no, you can have to run python IDLE tool itself as Administrator, from there you can open the agent.py and from the menu, you can then run the agent.py.

it will open a white window, now you can snapshot the vm.

**Comment by d4n13l4** [comment]
Hi, 
I have the same error from this thread so I've been following you.
I have a guest win7 and when I made changes to run python as administrator y get this error

2018-01-19 13:15:31,517 [cuckoo.core.guest] INFO: Virtual Machine /status failed (CuckooGuestError('Cuckoo Agent failed without error status, please try upgrading to the latest version of agent.py (>= 0.8) and notify us if the issue persists.',))
@saasthavasan Did you got it working for win7 after @saintxseiya's replies?

**Comment by saintxseiya** [comment]
your error is clear, you are not using the latest client agent.py replace it with the latest one.

**Comment by d4n13l4** [comment]
dah! I know but I have version 0.8 so it doesn't apply
so, did you make it work?

**Comment by saasthavasan** [comment]
hey,
No I was not able to apply the changes told by @saintxseiya as now all of a sudden I am getting the error: "Error from machine 'cuckoo1': it appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration"
I am not able to find why am I getting this error as I have checked virtualbox.conf and cuckoo.conf all the IP's are correctly written and I am also able to ping my guest from host and vice versa, I have also used the curl [ip]:8000 command to check my agent.py and it is also working properly.
So ya I am stuck with solving this issue at the moment.
 can this issue be related to version of agent.py?

**Comment by nice9uy** [comment]
same with me 

[IMG]http://i67.tinypic.com/4gg0o8.jpg[/IMG]

Any idea? @jbremer

**Comment by saasthavasan** [comment]
Hi,
As I mentioned I suddenly started facing another error which stated virtual machine has not been configured properly so I deleted cuckoo and reinstalled it and everything worked fine after that and I also did not get the error fetching configuration file. So if you have already deactivated UAC and tried running python Idle as administrator and It didn't work then you can try reinstalling cuckoo once. Although reinstalling is not a solution to this issue but it worked in my case.
