### ISSUE TITLE
Win 7x64 analysis 

### ISSUE THREAD

**Issue by ahmad67** [cuckoosandbox/cuckoo#2078]
hi people why when i make analysis using Win7SP1x86 on virtualbox i got full result but when i use Win7SP1x64 it refuse to analysis and hit timeout and terminate ?  and does not back behavior result for example

**Comment by doomedraven** [comment]
no logs no help :P

**Comment by jbremer** [comment]
Some logs would help, yes.

**Comment by jbremer** [comment]
Closing for lack of information, feel free to reopen if you have new information.
