### ISSUE TITLE
more than 1 memory dump

### ISSUE THREAD

**Issue by 02gaurav** [cuckoosandbox/cuckoo#2084]
how can i modify cuckoo sandbox to take more than 1 memory dump? i mean interval based memory dump

**Comment by doomedraven** [comment]
you will need to add your code in sheduler.py

**Comment by 02gaurav** [comment]
@doomedraven thanks i will try

**Comment by 02gaurav** [comment]
@doomedraven but it does not exist in cuckoo where will i find it?

**Comment by doomedraven** [comment]
sorry had a typo
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/core/scheduler.py

**Comment by 02gaurav** [comment]
@doomedraven i have changed the code. now what are the steps to get the modified report?

**Comment by doomedraven** [comment]
write a processing/reporting module to see the differences between memdumps

**Comment by 02gaurav** [comment]
@doomedraven actually i have cuckoo installed on my ubuntu but i want to use modified cuckoo how can i use that one

**Comment by 02gaurav** [comment]
@doomedraven actually my question is i am using a version of cuckoo but i have cloned cuckoo and have modified some code their now i want to use that cuckoo . So what should i do. For this do i need to remove older version( actually latest but not modified by me) to use my version . i mean what are steps to use modified code?

**Comment by doomedraven** [comment]
that is up to you how you want to use it
