### ISSUE TITLE
Android running successfully  But it is no static analysis and behavioral analysis results

### ISSUE THREAD

**Issue by w0r1dhe110** [cuckoosandbox/cuckoo#2086]
1. no static analysis result,but apkinfo is enabled.

![default](https://user-images.githubusercontent.com/35865922/35544636-6c1e8ea6-05a6-11e8-9e92-b04115e93ebb.PNG)
![1](https://user-images.githubusercontent.com/35865922/35544639-742bbff6-05a6-11e8-9ecb-064e7f658d18.PNG)

2. droidmon.log is not empty ,but no behavioral analysis result.
![2](https://user-images.githubusercontent.com/35865922/35544827-548034d8-05a7-11e8-948a-c60992c78eaf.PNG)

[132.zip](https://github.com/cuckoosandbox/cuckoo/files/1676155/132.zip)

**Comment by doomedraven** [comment]
you know what 2.x doesn't support android no?

**Comment by w0r1dhe110** [comment]
@doomedraven  I know,but Mentioned in the document
![default](https://user-images.githubusercontent.com/35865922/35601753-af3db544-066f-11e8-9c4a-4aabddb9e647.PNG)

**Comment by doomedraven** [comment]
will be, but not done

**Comment by jbremer** [comment]
Hopefully sometime this year ;-) Closing issue for now though.
