### ISSUE TITLE
cuckoo distributed submit a folder

### ISSUE THREAD

**Issue by falcorocks** [cuckoosandbox/cuckoo#2087]
This is very weird, I am checking the Distributed APIs http://docs.cuckoosandbox.org/en/latest/usage/dist/
and I can't find a way to submit more than a file at once to the distributed master node.
Is it just missing from the documentation or I have to write a script?

**Comment by jbremer** [comment]
That's correct, yes. Feel free to send a PR. I completely understand the confusion, but we simply didn't require such functionality up until now.

**Comment by falcorocks** [comment]
Thank you for your reply, unfortunately I don't have the time nor the knowledge :(

Let me ask you something though: how would you analyse 40000 samples?

The way I did it is very naive: I set up a cuckoo dedicated machine and then cloned it to two more computers. I then split the 40k samples in 3 folders and submitted one for each machine locally by using the cuckoo daemon. 
`cuckoo` on one terminal tab
`cuckoo submit <FOLDER>` on another terminal tab

I actually did set up the 3 machines in a distributed way first, but then when I realised a "submit all at once" command was missing I gave up.

How would you do properly though? I fail to understand how one can do this since also the web interface is not an option for distributed set up.
The only way I can think of is by using a bash script that manually calls the distributed API submit for each file in a folder...

**Comment by doomedraven** [comment]
quick tip, bash + curl ;) for i in `ls`; do curl -X post @file=$i url; done something like that

**Comment by falcorocks** [comment]
god bless bash eh? Thanks! Closing
