### ISSUE TITLE
api sequence checking

### ISSUE THREAD

**Issue by 02gaurav** [cuckoosandbox/cuckoo#2088]
where should i write my code to check whether given api sequence or given api has been used in windows? Actually what i want to do is : 
I want to trigger memory dump if any api sequence or api appears.
Someone plz help ASAP

**Comment by doomedraven** [comment]
plz read documentation ASAP

**Comment by jbremer** [comment]
Also check the Cuckoo Monitor, https://github.com/cuckoosandbox/monitor.

**Comment by jbremer** [comment]
Closing as no additional information has been provided.
