### ISSUE TITLE
[mitmproxy] script is not found

### ISSUE THREAD

**Issue by LetMeR00t** [cuckoosandbox/cuckoo#2093]
Hello guys,

I'm using the last version of cuckoo (v2-0-5) and I needed to use the last release of mitmproxy (r3-RC2) because the configuration file of mitmproxy was not used.

We found out a bug that I've just detailed here : https://github.com/mitmproxy/mitmproxy/issues/2824

I think the problem is linked to the way on how we give the parameters to mitmproxy here :

https://github.com/cuckoosandbox/cuckoo/blob/dc1c674b7ca5e0cda8338c82b9e46a2d7300cb83/cuckoo/auxiliary/mitm.py#L57-L62

It could be great to resolve this for the next release.

Let me know if you need something else.

**Comment by mhils** [comment]
A fix for this is in https://github.com/cuckoosandbox/cuckoo/pull/2092, sorry for not communicating that on our end. :) We do the rest in mitmproxy with https://github.com/mitmproxy/mitmproxy/pull/2833 so that you can keep one calling convention for any mitmproxy versiom.

**Comment by LetMeR00t** [comment]
FYI, another issue concerning cuckoo/mitmproxy was opened here : https://github.com/cuckoosandbox/cuckoo/issues/2095
It concerns the transparent mode :) It's not the fault of mitmproxy, it's a setting always set on cuckoo's code.

**Comment by jbremer** [comment]
I've merged the #2092 (and will push it in a bit), so this issue can be closed, right? :-)

**Comment by LetMeR00t** [comment]
Yes, I agree :)
