### ISSUE TITLE
Showing error while running cuckoo log is attached

### ISSUE THREAD

**Issue by 02gaurav** [cuckoosandbox/cuckoo#2096]
File "/usr/local/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/__init__.py", line 10, in <module>
    __file__, "cuckoo.reporting", globals(), Report
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at feedback.py: cannot import name u. Please review its contents and/or validity!

**Comment by doomedraven** [comment]
are you sure you not modified that file?
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/reporting/feedback.py

**Comment by 02gaurav** [comment]
@doomedraven I reinstalled cuckoo but still I am getting error

**Comment by doomedraven** [comment]
How? Pip uninstall + remove the rest from dist-packages?

**Comment by 02gaurav** [comment]
Pip uninstall cuckoo

**Comment by doomedraven** [comment]
do uninstall and remove the folder

**Comment by jbremer** [comment]
The original `cuckoo/reporting/feedback.py` doesn't import any `u`. Could you post your version of the file?

**Comment by RicoVZ** [comment]
@02gaurav Are you still have stil issue? If yes, could you post your version of the file?

**Comment by jbremer** [comment]
Closing issue for lack of additional information - feel free to reopen if you have an update for us.
