### ISSUE TITLE
json report - hash submitted file (info)

### ISSUE THREAD

**Issue by reynas** [cuckoosandbox/cuckoo#2097]
How could I add the md5 hash of the submitted file in the "info" part of the json report?

**Comment by RicoVZ** [comment]
Hi reynas,

You can add the information to it in the processing module:
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/processing/analysisinfo.py#L65

More information on custom processing and reporting can be found here:
https://cuckoo.sh/docs/customization/processing.html

**Comment by jbremer** [comment]
Isn't it already in there? Or elsewhere at least?

**Comment by jbremer** [comment]
Closing issue for lack of additional information - feel free to reopen if you have an update for us.
