### ISSUE TITLE
error while lunching cuckoo (VBox manage not found)

### ISSUE THREAD

**Issue by nemahabdullah** [cuckoosandbox/cuckoo#2101]
I installed VirtualBox on a windows 8  and installed the malware sandbox with it under Kali linux ...

Issue I'm having is this...

 [root] CRITICAL: CuckooCriticalError: VirtualBox VBoxManage not found at specified path "/usr/bin/VBoxManage"
i try to update the Virtualbox extension to last but the same issue still found

**Comment by doomedraven** [comment]
`ls -lah /usr/bin/VBoxManage` ?

**Comment by nemahabdullah** [comment]
the output

ls : cannot access  /usr/bin/VBoxManage

**Comment by doomedraven** [comment]
`which VBoxManage`?

**Comment by nemahabdullah** [comment]
![vbox](https://user-images.githubusercontent.com/35217463/35774549-e631f1f2-0983-11e8-91a6-aa6510c6e02d.JPG)

**Comment by SparkyNZL** [comment]
Try ‘which vboxmanage‘

 

(its all lowercase , in ubuntu)

**Comment by nemahabdullah** [comment]
i tried on lower case the same output as on the previous screenshot

**Comment by SparkyNZL** [comment]
You have installed virtual box aye ?

**Comment by jbremer** [comment]
And don't install Cuckoo in a Kali VM, install it on the host.

**Comment by nemahabdullah** [comment]
as i told you 
i  installed the virtual box on windows 8 , and installed the cuckoo as VM inside the virtuallbox

**Comment by nemahabdullah** [comment]
![cuc](https://user-images.githubusercontent.com/35217463/35775700-efa9ecba-099e-11e8-9aea-2f91d7f6c6f5.JPG)

**Comment by nemahabdullah** [comment]
@jbremer 
i want to separate the cuckoo from my host because this is for business task  , i installed the cuckoo inside Kali linux  as VM and i install another windows 7 as VM to be as guest .

**Comment by jbremer** [comment]
Well, we don't provide support for nested VM setups because they very often come with problems.. as right now.. ;-)

**Comment by SparkyNZL** [comment]
Ok your setup is all garks , read the docos , it will not be a reliable cuckoo setup








From: Jurriaan Bremer


Sent: Sunday, 4 February, 21:25


Subject: Re: [cuckoosandbox/cuckoo] error while lunching cuckoo (VBox manage not found) (#2101)


To: cuckoosandbox/cuckoo


Cc: SparkyNZL, Comment






And don't install Cuckoo in a Kali VM, install it on the host.

**Comment by SparkyNZL** [comment]
So you want a nested hypervisor ? 




sent from my Pixel 2.







On Sun, Feb 4, 2018 at 9:35 PM +1300, "nemahabdullah" <notifications@github.com> wrote:












@jbremer

i want to separate the cuckoo from my host because this is for business task  , i installed the cuckoo inside Kali linux  as VM and i install another windows 7 as VM to be as guest .

**Comment by nemahabdullah** [comment]
@jbremer 
not nested , the cuckoo as VM inside virtualbox and the guest behind it , the two vm behinde each other on the virtualbox

**Comment by jbremer** [comment]
That's literally nested ;)

**Comment by SparkyNZL** [comment]
Ok




Can u answers these questions as Im confused




Host os :


HyperVisor :


VM os :




I think I know what your trying to do, but this will clarify it.




You can run cuckoo in a nested environment as I do with ESXi - Ubuntu / cuckoo  - Virtual box with 15 vms. 








sent from my SpaceShip...













On Sun, Feb 4, 2018 at 9:39 PM +1300, "nemahabdullah" <notifications@github.com> wrote:












@jbremer

not nested , the cuckoo as VM inside virtualbox and the guest behind it , the two vm behinde each other on the virtualbox

**Comment by nemahabdullah** [comment]
thank you SparkyNZL for your reply 
i have laptop with OS windows 8.1 , it's for business task

i want to create separate lab environment inside Virtualization platform 

so , i installed Virtual box  inside it , i created two VM's inside the virtual box
the first as Host for cuckoo analysis and the OS is Kali linux 2017
the second is for guest and the OS is Win7 64 bit  .
please guide me if this correct , what can i do for my situation ?

**Comment by SparkyNZL** [comment]
Ok to answer your original question, you cant find vboxmanage in the Kali install as you don't have it install on that VM, it's not going to break out of the Kali VM and look for files on your windoze box, could you imagine if it could do just that, your host would get infected in seconds and you don't want that.

I strongly do not recommend that you do not run this on a Windows host, it carries my risk of infection should a "mistake" happen, and even the most experienced ppl make mistakes, being human sucks sometimes !

There are a number of ways you can proceed.

1. Dump windows and setup as the documentation
2. Keep windws and run in a nested setup .
3. Do it the way you are now,  I can't say I've setup cuckoo this way ever. And I'm not sure u actually can.someone else will have to chip in on that.

There are some limitations

1. What processor is in the Windozs 8 machine as this will limit the ability to nest and run 64bit machines

2. Ran, if you don't have a lot don't host it in windoze .

I suppose, playing with malware is kinda fun, but learn to sandbox first, or it could end in tears. There are some great resources on the internet. Where u can don't host a malware lab where it can execute on the host, vm breakouts do occur vbox just patched a bunch

Eg if I was looking at Mac malware my host would not be a Mac. If I'm looking a Linux malware I'd host it on windows. Etc 

Hope this helps and you take some time to think about what you are trying to accomplish.

**Comment by nemahabdullah** [comment]
many thanks  SparkyNZL for your clarification .
