### ISSUE TITLE
VMs won't run simultaneously

### ISSUE THREAD

**Issue by AMKpeacemaker** [cuckoosandbox/cuckoo#2107]
Ahoi,
my cuckoo works fine and I can analyze files with my VMs (I got 2 at the moment - Win7 and XP).
But it only starts up both of them, if I submit more than 1 file. Can I change that somehow, or did I configure something wrong (missed something) ?

virtualbox.conf
```
machines = Windows7,WindowsXP


[Windows7]
label = Windows7
platform = windows
ip = 192.168.156.2
snapshot = SnapWin7
osprofile = Win7SP1x64

[WindowsXP]
label = WindowsXP
platform = windows
ip = 192.168.156.3
snapshot = SnapXP
osprofile = WinXPSP3x86
```
I left the guest_profile within the memory.conf blank, because I am using osprofile (virtualbox.conf), is that causing my issue ?

memory.conf
```
# Basic settings
[basic]
# Profile to avoid wasting time identifying it
guest_profile =
# Delete memory dump after volatility processing.
delete_memdump = no
```
I found a closed Issue regarding this "problem" ( https://github.com/cuckoosandbox/cuckoo/issues/2059 ) but the "solution" was to simply submit 2 files. But I would like to analyze one file with two different VMs per default, if that's possible.

Best regards
peacemaker

**Comment by RicoVZ** [comment]
Hi AMKpeacemaker,

Thanks for creating an issue, and sorry for the late reply.

From what I understand you want is: submitting one file to multiple machines.

At this time, Cuckoo task creation is always per task, meaning only a single task is created each time. If you want a file to be executed on multiple VMs, you should create multiple tasks. For each task, you should then specify a different machine using the `--machine` option.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
