### ISSUE TITLE
can't found processing folder

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2114]
in which folder i can found processing modules ?

**Comment by doomedraven** [comment]
RTM

**Comment by RicoVZ** [comment]
Hi rayenmessaoudi,

The processing modules can be found in `cuckoo/processing`.
https://github.com/cuckoosandbox/cuckoo/tree/master/cuckoo/processing

This page will also tell you this and more information about creating custom modules.
https://cuckoo.sh/docs/customization/processing.html
