### ISSUE TITLE
supervisord requires minfds parameter to increase open files limit for cuckoo processes

### ISSUE THREAD

**Issue by crahan** [cuckoosandbox/cuckoo#2122]
The guide to increase the max open file limit (mentioned at http://docs.cuckoosandbox.org/en/latest/faq/#openfiles24) does not appear to increase the open files limit for Processing Utility instances spawned by `supervisord`. Neither does adding `pam_limits.so` in either `/etc/pam.d/common-session` or `/etc/pam.d/common-session-noniteractive`.

The way to increase the open files limit for daemon processes spawned through `supervisord` is by adding the `minfds` parameter to the `[supervisord]` section in `supervisord.conf` and setting it to an acceptable value.

From the supervisord documentation (http://supervisord.org/configuration.html):

> minfds
The minimum number of file descriptors that must be available before supervisord will start successfully. A call to setrlimit will be made to attempt to raise the soft and hard limits of the supervisord process to satisfy minfds. The hard limit may only be raised if supervisord is run as root. supervisord uses file descriptors liberally, and will enter a failure mode when one cannot be obtained from the OS, so it’s useful to be able to specify a minimum value to ensure it doesn’t run out of them during execution. These limits will be inherited by the managed subprocesses. This option is particularly useful on Solaris, which has a low per-process fd limit by default.

**Comment by doomedraven** [comment]
theck prs, i pushed that

**Comment by crahan** [comment]
Thanks for pointing that out @doomedraven. I missed that pull request (https://github.com/cuckoosandbox/cuckoo/pull/2004). I'll go ahead and close this issue ticket!

**Comment by doomedraven** [comment]
@jbremer  you know what this mean :P
