### ISSUE TITLE
Unable to check running status for /root/vmware/cuckoo1/cuckoo1.vmx.

### ISSUE THREAD

**Issue by techchetn** [cuckoosandbox/cuckoo#2123]
Hi 

I've submitted files for analysis cuckoo then ran the cuckoo, below are the instances let me know what changes i need to make cuckoo running and VMware workstation opens and prompts error "Unable to open Virtual Machine : File not found."

root@kali:~# sudo cuckoo -d submit --package pdf /root/Desktop/Invo-3433.pdf
Success: File "/root/Desktop/Invo-3433.pdf" added as task with ID #9
root@kali:~# sudo cuckoo

                               ),-.     /
  Cuckoo Sandbox              <(a  `---','
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.0.4
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
2018-02-13 23:49:48,794 [cuckoo.core.startup] INFO: Updated running task ID 2 status to failed_analysis
2018-02-13 23:49:48,814 [cuckoo.core.scheduler] INFO: Using "vmware" as machine manager
2018-02-13 23:49:57,953 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2018-02-13 23:49:57,963 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2018-02-13 23:49:59,063 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "FileZilla_3.30.0_win64-setup_bundled.exe" (task #3, options "")
2018-02-13 23:49:59,231 [cuckoo.core.scheduler] INFO: Task #3: acquired machine cuckoo1 (label=/root/vmware/cuckoo1/cuckoo1.vmx)
2018-02-13 23:49:59,240 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 9153 (interface=eth0, host=192.168.73.129)
2018-02-13 23:50:14,489 [cuckoo.core.scheduler] ERROR: Error starting Virtual Machine! VM: cuckoo1, error: Unable to check running status for /root/vmware/cuckoo1/cuckoo1.vmx. No output from `vmrun list`
2018-02-13 23:50:22,190 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run

**Comment by RicoVZ** [comment]
Hi techchetn,

Can you please post your vmware.conf? (Preferably on a pasting service).
This is to help us to see your configuration so that we can verify if it is correct.

**Comment by techchetn** [comment]
[vmware]
# Specify which Vmware Workstation mode you want to run your machines on.
# Can be "gui" or "nogui". Refer to VMware's official
# documentation to understand the differences.
mode = gui

# Path to the local installation of the vmrun utility.
path = /usr/bin/vmplayer

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1

# Specify the name of the default network interface that should be used
# when dumping network traffic with tcpdump.
# Example (virbr0 is the interface name):
interface = eth0


[cuckoo1]
# Specify the path to vmx file of this virtual machine.
vmx_path = /root/vmware/cuckoo1/cuckoo1.vmx

# Specify the snapshot name to use.
snapshot = Snapshot1

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.73.129

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump.
# Example (virbr0 is the interface name):
interface = eth0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 0.0.0.0

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags = 

# (Optional) Specify the OS profile to be used by volatility for this
# virtual machine. This will override the guest_profile variable in
# memory.conf which solves the problem of having multiple types of VMs
# and properly determining which profile to use.
osprofile =

**Comment by RicoVZ** [comment]
Thanks. The `path = ` field should have the path to the `vmrun` binary. If you can't find it, you can use `which vmrun` to find the path.

Currently, your config has `path = /usr/bin/vmplayer`.
It should be `path = somepathhere/vmrun`.

vmrun is the tool Cuckoo uses to start, stop, restore virtual machines for VMware.

**Comment by techchetn** [comment]
somepathhere/vmrun

vmrun isn't available in the host, any help ?

**Comment by RicoVZ** [comment]
It should be there if you installed VMware Workstation. I can't say why it is not. 😄 
What is the exact output of the command `which vmrun`?

**Comment by techchetn** [comment]
It's empty - no output at all.

**Comment by RicoVZ** [comment]
It seems I was wrong, vmrun is not always shipped with VMware. It is obtained by installing the VMware VIX API.

**Comment by RicoVZ** [comment]
Did you try installing that to get vmrun and place vmrun in the`path =` in your vmware.conf?

**Comment by techchetn** [comment]
Yes, i did tried installing VMware Workstation pro, now cuckoo does connect to VM.

Thanks
