### ISSUE TITLE
Powershell crashing

### ISSUE THREAD

**Issue by Angelill0** [cuckoosandbox/cuckoo#2125]
,Hello,

When analysing some document with macros which spawns a powershell, the powershell process crashes.

System: 
VirtualBox 5.2.6
Win7-x64 
 python2.7.14 64 bits
cuckoo 2.0.5

The dump with the crash is as follow:
[2716.bson.log](https://github.com/cuckoosandbox/cuckoo/files/1729723/2716.bson.log)

RaiseException+0x3d FreeEnvironmentStringsW-0x373 kernelbase+0xa49d @ 0x7fefd3ba49d
CoUninitializeEE+0x16565 CreateAssemblyNameObject-0x2b2ff clr+0x22105 @ 0x7fef08b2105
TranslateSecurityAttributes+0x25e43 PostErrorVA-0x1c1d91 clr+0x3b7777 @ 0x7fef0c47777
CreateHistoryReader+0xb5424 GetAssemblyMDImport-0x1a3a8 clr+0x339f54 @ 0x7fef0bc9f54
DllCanUnloadNowInternal-0x49eb clr+0x3055 @ 0x7fef0893055
mscorlib+0x4dabd1 @ 0x7fee649abd1
mscorlib+0x4da43e @ 0x7fee649a43e
mscorlib+0x4c404f @ 0x7fee648404f
mscorlib+0x444c84 @ 0x7fee6404c84
DllCanUnloadNowInternal-0x42ed clr+0x3753 @ 0x7fef0893753
DllCanUnloadNowInternal-0x4424 clr+0x361c @ 0x7fef089361c
GetMetaDataInternalInterface+0x1b00b CopyPDBs-0x2cc9d clr+0x8877f @ 0x7fef091877f
GetMetaDataInternalInterface+0x1afe5 CopyPDBs-0x2ccc3 clr+0x88759 @ 0x7fef0918759
_CorExeMain+0x2641c _AxlPublicKeyBlobToPublicKeyToken-0x7a3d4 clr+0x184cfc @ 0x7fef0a14cfc
GetMetaDataInternalInterface+0x1aadf CopyPDBs-0x2d1c9 clr+0x88253 @ 0x7fef0918253
GetMetaDataPublicInterfaceFromInternal+0xf0bf PreBindAssembly-0x37339 clr+0xc56bb @ 0x7fef09556bb
mscorlib+0x4e9ff5 @ 0x7fee64a9ff5
mscorlib+0x4e9ca8 @ 0x7fee64a9ca8
mscorlib+0xe3515c @ 0x7fee6df515c
system+0x15b9e5e @ 0x7fee3dd9e5e
microsoft+0x1f810 @ 0x7fee49bf810
DllCanUnloadNowInternal-0x42ed clr+0x3753 @ 0x7fef0893753
DllCanUnloadNowInternal-0x4424 clr+0x361c @ 0x7fef089361c
GetMetaDataInternalInterface+0x31766 CopyPDBs-0x16542 clr+0x9eeda @ 0x7fef092eeda
GetMetaDataInternalInterface+0x31550 CopyPDBs-0x16758 clr+0x9ecc4 @ 0x7fef092ecc4
mscorlib+0x4598d0 @ 0x7fee64198d0
mscorlib+0x460dd2 @ 0x7fee6420dd2
DllCanUnloadNowInternal-0x42ed clr+0x3753 @ 0x7fef0893753
DllCanUnloadNowInternal-0x4424 clr+0x361c @ 0x7fef089361c
DllCanUnloadNowInternal-0x356d clr+0x44d3 @ 0x7fef08944d3
ClrCreateManagedInstance+0x3122 _CorExeMain-0x227d2 clr+0x13c10e @ 0x7fef09cc10e
ClrCreateManagedInstance+0x3bba _CorExeMain-0x21d3a clr+0x13cba6 @ 0x7fef09ccba6
ClrCreateManagedInstance+0x394c _CorExeMain-0x21fa8 clr+0x13c938 @ 0x7fef09cc938
ClrCreateManagedInstance+0x3522 _CorExeMain-0x223d2 clr+0x13c50e @ 0x7fef09cc50e
ClrCreateManagedInstance+0x3389 _CorExeMain-0x2256b clr+0x13c375 @ 0x7fef09cc375
ClrCreateManagedInstance+0x32ce _CorExeMain-0x22626 clr+0x13c2ba @ 0x7fef09cc2ba
powershell+0x19f8 @ 0x13f6a19f8
powershell+0x3b03 @ 0x13f6a3b03
powershell+0x7bcd @ 0x13f6a7bcd
BaseThreadInitThunk+0xd CreateThread-0x53 kernel32+0x1652d @ 0x772a652d
RtlUserThreadStart+0x21 strchr-0x3df ntdll+0x2c521 @ 0x773dc521

exception.instruction_r: 48 81 c4 c8 00 00 00 c3 48 85 f6 74 08 83 3b 00 
exception.symbol: RaiseException+0x3d FreeEnvironmentStringsW-0x373 kernelbase+0xa49d 
exception.instruction: add rsp, 0xc8 
exception.module: KERNELBASE.dll 
exception.exception_code: 0xe0434352 
exception.offset: 42141 
exception.address: 0x7fefd3ba49d 
registers.r14: 0 
registers.r15: 0 
registers.rcx: 51539673089 
registers.rsi: 0 
registers.r10: 0 
registers.rbx: 0 
registers.rsp: 2293056 
registers.r11: 2277824 
registers.r8: 40082152 
registers.r9: 40 
registers.rdx: 2 
registers.r12: 0 
registers.rbp: 0 
registers.rdi: 0 
registers.rax: 2002997342 
registers.r13: 0 

Thanks

**Comment by Angelill0** [comment]
PowerShell Version:

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by jbremer** [comment]
Hi @Angelill0, thanks for reporting this issue!
Could you please try the following version of Cuckoo Monitor to see if that resolves your issue?
https://cuckoo.sh/6dd8e646c7269630/monitor-x64.dll
It includes the following commit https://github.com/cuckoosandbox/monitor/commit/f8c2b22ad8d5bb1f64e1aae3ef737fd25e2875d5. Thanks in advance.

**Comment by Angelill0** [comment]
Hello @jbremer, 
I tested and now there is no crash. it looks good. Thanks :)

Still I do not get the results I expected. It seems the powershell command doesn't fully executed, but this is other issue anyway. 
Regards,

**Comment by jbremer** [comment]
This is part of our `2.0.6` release, closing as resolved. Thanks!
