### ISSUE TITLE
Move from Ubuntu to Debian issue.

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2126]
So after testing I've copied my install of .cuckoo and venv to a Debian box.  Ubuntu has libjpeg8, Debian does not.  Here's the error:
~~~
Traceback (most recent call last):
  File "/home/jlay/venv/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/home/jlay/venv/local/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/home/jlay/venv/local/lib/python2.7/site-packages/cuckoo/processing/__init__.py", line 10, in <module>
    __file__, "cuckoo.processing", globals(), Processing
  File "/home/jlay/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at screenshots.py: libjpeg.so.8: cannot open shared object file: No such file or directory. Please review its contents and/or validity!
~~~

I tried deleting all the screenshot.pyc files, but that did not fix it.  Can anyone lend a hand on what I need to do to fix this?  Thank you.

**Comment by doomedraven** [comment]
you should read the error
`libjpeg.so.8: cannot open shared object file: No such file or directory` -> first result in google https://ubuntuforums.org/showthread.php?t=2040704

**Comment by DigiAngel** [comment]
I did read the error...and you should read the post :P  I've moved an instance FROM ubuntu TO Debian.  Debian does not have libjpeg8:
~~~
apt-cache search libjpeg
gem-plugin-jpeg - Graphics Environment for Multimedia - JPEG support
imgsizer - Adds WIDTH and HEIGHT attributes to IMG tags in HTML files
jp2a - converts jpg images to ascii
libjpeg-dev - Development files for the JPEG library [dummy package]
libjpeg-turbo-progs - Programs for manipulating JPEG files
libjpeg62-turbo - libjpeg-turbo JPEG runtime library
libjpeg62-turbo-dev - Development files for the libjpeg-turbo JPEG library
libturbojpeg0 - TurboJPEG runtime library - SIMD optimized
libturbojpeg0-dev - Development files for the TurboJPEG library

dpkg -l | grep libjpeg
ii  libjpeg-dev                                    1:1.5.1-2                                 all          Development files for the JPEG library [dummy package]
ii  libjpeg62-turbo:amd64                          1:1.5.1-2                                 amd64        libjpeg-turbo JPEG runtime library
ii  libjpeg62-turbo-dev:amd64                      1:1.5.1-2                                 amd64        Development files for the libjpeg-turbo JPEG library
~~~

So now what :)  Should I just reinstall cuckoo in my venv?  I've done a pip install -U cuckoo and all looks good.  Thank you!

**Comment by doomedraven** [comment]
`has libjpeg8` but `have libjpeg8 fail` that isn't the same ;)

btw ni idea, the recommended os is ubuntu 16.04 lts, so maybe someone who had that can help who uses debian, but google should be fine, 

check this `sudo apt-get install libjpeg-turbo8`
http://forums.fast.ai/t/solved-importerror-libjpeg-so-8-cannot-open-shared-object-file-on-wsl/8303/2

anyway if that doesn't work i would suggest search for any libjpeg.so and try to create symlink to .8

**Comment by doomedraven** [comment]
ah i see you have installed that, no idea dude, i have fly so can't help too much

**Comment by doomedraven** [comment]
https://packages.debian.org/wheezy/amd64/libjpeg8/download check which is your version

**Comment by DigiAngel** [comment]
Thanks...looks like stretch does not have libjpeg8...so I'll have to compile from source I guess; will update with findings.

**Comment by doomedraven** [comment]
as curiosity why did you change from ubuntu to debian?

**Comment by DigiAngel** [comment]
Ya looks like just a download and dpkg -i the libjpeg8 worked like a champ.  And as for the move, I have a rockin spender setup on a Debian box...figured I should consolidate them and repurpose the Ubuntu box :)  Thanks as always...I think I see you in a certain slack channel sometimes ;)

**Comment by doomedraven** [comment]
feel free to ping me, and don't get me grumpy, it's just stupid flu

**Comment by DigiAngel** [comment]
LoL...will do :)
