### ISSUE TITLE
ERROR: Cannot take screenshot: screen grab failed

### ISSUE THREAD

**Issue by Tux-Panik** [cuckoosandbox/cuckoo#2133]
Hello,
I submit here my issue related to screenshots.

##### My issue is:
Cuckoo is not able to take a screenshot to the guest.

##### My Cuckoo version and operating system are:
Cuckoo: 2.0.5.3
Virtualbox: 5.2.6
Host OS: CentOS 7
Agent: 0.8
Guest OS: Win7 64B
Pillow: 3.2.0

##### This can be reproduced by:
N/A

##### The log, error, files etc can be found at:
In "analysis.log" of the task, I have the following record:
`[modules.auxiliary.screenshots] ERROR: Cannot take screenshot: screen grab failed`
The screenshots are, indeed, missing in the reports.

But, it is amazing, this feature works perfectly in my Cuckoo-dev, using same versions and the same .ova file except the two following things:
- Virtualbox version is 5.2.4 in dev
- WebUI is enabled in dev

I think the problem is similar with the one @pskmsc is facing:
[https://github.com/cuckoosandbox/cuckoo/issues/1561](https://github.com/cuckoosandbox/cuckoo/issues/1561)

Thanks again for your time,
Kind regards,
Julien

**Comment by doomedraven** [comment]
`screen grab failed` if you google for it you will see what that is pillow problem, not cuckoo's, so i would sugget google around, maybe someone had that and will be able to help, but maybe google will bring you solution faster

**Comment by Tux-Panik** [comment]
Thanks, Google searches already done but they didn't help.
I will persist.

**Comment by doomedraven** [comment]
you may try to change dependecy version and install latest, maybe that solves

**Comment by Tux-Panik** [comment]
In progress... I let you know the result soon!

**Comment by Tux-Panik** [comment]
All depencies, especially Pillow have been updated on both sides and no change.

Do you think screenshots need a server X should be installed on serveur side?

**Comment by doomedraven** [comment]
that is client-side only dependency

**Comment by Tux-Panik** [comment]
Several additional tests made this week.
Cuckoo core is hosts on a server without any GUI and it didn't help for troubleshooting.
We finally found what was wrong... our VM's snapshot was made while the session was locking.
Once locked, no way to perform any screenshot.

Issue can be closed.
Sorry and thanks for your time.
Regards,
Julien

**Comment by jwilczek** [comment]
Can you elaborate on what you mean by "session was locking". I'm seeing a similar issue with a physical setup.

**Comment by Tux-Panik** [comment]
Hi @jwilczek 
Actually, I didn't have a GUI on our host server.
So, it seems Iwaited too long before to take the snapshot that will be run with Cuckoo.
And this too long delay (about 5 min) was enough to lock the Windows session.
In this context, Cuckoo ran a snapshot where the session was locked.
So I had a very important loss on Cuckoo report, including snapshots.

I hope it helps,
Kind regards,
Julien
