### ISSUE TITLE
Cuckoo license

### ISSUE THREAD

**Issue by emmanueltsukerman** [cuckoosandbox/cuckoo#2142]
Hello,

- Is there a link to the license?
- Can cuckoo be used commercially?
- Can cuckoo sandbox be white labeled?

**Comment by emmanueltsukerman** [comment]
Don't appreciate the comment, but appreciate the link

**Comment by jbremer** [comment]
Cuckoo is licensed under GPLv3 and you can use it commercially, although depending on use-case you might indeed require a white label version. We can provide such a white label version, however, this process isn't cut in stone and really depends on whatever you'd like to achieve - in most cases it isn't even necessary/
If you're looking for commercial goals, you may also be interested in our commercial / consultancy services where we can help you out with everything in and around Cuckoo.
Feel free to contact us privately if you're looking for further advice on said possibilities.

**Comment by maynardflies** [comment]
If you guys move/copy the LICENSE file to the root, Github will pick it up and display it in your repo's top bar, much easier for people to see and get a link to the details automagically.  Just a thought!

**Comment by jbremer** [comment]
Thanks @maynardflies, that does indeed seem to help, see also https://github.com/cuckoosandbox/cuckoo/commit/9e08c7c8b652925c61cd5a66ebc925a6b7628b71.

**Comment by jbremer** [comment]
I guess this issue can be closed. Feel free to reach out to us regarding the questions above.
