### ISSUE TITLE
--machine

### ISSUE THREAD

**Issue by liqingjia** [cuckoosandbox/cuckoo#2145]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by liqingjia** [comment]
I use --machine like this:cuckoo submit --machine cuckoo1 /home/yellow/calc.exe
in virtualbox.conf:machines = cuckoo1
but Cannot acquire machine: No machines match selection criteria.
how can I do? Weather I write "--machine cuckoo1" wrong?
help,  thank you.

**Comment by liqingjia** [comment]
OK, I try.

**Comment by liqingjia** [comment]
OK, I try.

**Comment by liqingjia** [comment]
I try.
It's right.
Thank you very much.

**Comment by doomedraven** [comment]
you are welcome, if solved press close button ;)
