### ISSUE TITLE
API only accepting calls to localhost

### ISSUE THREAD

**Issue by vkuehn** [cuckoosandbox/cuckoo#2146]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html
yes
##### My issue is:
Can't call the Cuckoo api from another machine with the ip adress of the server

##### My Cuckoo version and operating system are:
Version 2.0.4

##### This can be reproduced by:
following the simple example in documentation here https://cuckoo.sh/docs/usage/api.html#cuckoo-status
does work only for me when using the localhost adress from the cuckoo machine. 
Using the proper ip adress causes an error "Connection refused"

##### The log, error, files etc can be found at:
there is no log entry when trying in var/log/uwsgi/cuckoo-api.log
just a connection refused when trying curl http://localhost:8090/cuckoo/status but with the ip adress of the server

**Comment by doomedraven** [comment]
check api --help ;)

**Comment by RicoVZ** [comment]
Hi vkuehn,

This sounds like your API server is listening on localhost only. Please make sure you bind the API to an IP of a network interface that can be accessed from outside the machine.

Also, see: https://cuckoo.sh/docs/usage/api.html#starting-the-api-server

**Comment by vkuehn** [comment]
thanks alot for the quick reply, 
did look at the docs and yes it works when giving the hostip to the start command.
I hoped for a more persistent solution. Would it be right to put the ip to the nginx setup where localhost is mentioned in the documentation ??

**Comment by vkuehn** [comment]
some how after a view reboots API is accessible from outside
