### ISSUE TITLE
cuckoo report.json

### ISSUE THREAD

**Issue by kma94dz** [cuckoosandbox/cuckoo#2149]
##### My issue is: i want to know what is the meaining of my report.json file : how the score works, and if the machine status "stopped" is okey!?

{
    "info": {
        "added": 1519065901.425231, 
        "started": 1519065916.244693, 
        "duration": 27, 
        "ended": 1519065943.307894, 
        "owner": null, 
        "score": 1.2, 
        "id": 23, 
        "category": "file", 
        "git": {
            "head": "59d32361c1636b2b3802a1746f480a7768f6384f", 
            "fetch_head": "59d32361c1636b2b3802a1746f480a7768f6384f"
        }, 
        "monitor": "e19c4b4b529be2e90b3c5a3dfaad96f71c4fd54b", 
        "package": "", 
        "route": "none", 
        "custom": null, 
        "machine": {
            "status": "stopped", 
            "name": "controller", 
            "label": "controller", 
            "manager": "VirtualBox", 
            "started_on": "2018-02-19 18:45:16", 
            "shutdown_on": "2018-02-19 18:45:43"
        }, 
        "platform": null, 
        "version": "2.0.5", 
        "options": ""
    }, 

##### My Cuckoo version and operating system are:2.0.5

thanks!

**Comment by doomedraven** [comment]
hey there,
if you check the documentation it says, __machine status__ should be running

**Comment by kma94dz** [comment]
But it happens after the annalyses ends
I submit a file(virus) to annalyse
The VM starts normaly. The agent is 
Runing 
After that i get the analyses folder containing the analyses report
In the report.json
There is this machine status stopped
I want to know if this status is normal
And what are all the possible status that i can get ? 
Thanks!

**Comment by doomedraven** [comment]
ah, in that case, that fine, that is post analysis, so stopped is correct, for post analysis only stopped. for different analysis states see `database.py`

**Comment by kma94dz** [comment]
Ok. I understand now
Thanks for your time :)

**Comment by doomedraven** [comment]
you are welcome :) 
close if solved
