### ISSUE TITLE
WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by Mokatsu** [cuckoosandbox/cuckoo#2150]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Hi on my windows 10 VM, when I run analysis I keep seeing this error:

2018-03-05 13:03:20,447 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpeihrxm/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpeihrxm/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmpeihrxm\modules\packages\ie.py", line 127, in start
    iexplore, args=[target], maximize=True, mode="iexplore"
  File "C:\tmpeihrxm\lib\common\abstracts.py", line 159, in execute
    self.init_regkeys(self.REGKEYS)
  File "C:\tmpeihrxm\lib\common\abstracts.py", line 121, in init_regkeys
    SetValueEx(key_handle, key, 0, REG_DWORD, value)
WindowsError: [Error 5] Access is denied

the cuckoo user is in the VirtualBox user group and I created the VM's with the cuckoo user.

##### My Cuckoo version and operating system are:
Host: Ubuntu 16.04
Guest: Windows 10
Virtualization Software: VirtualBox

##### This can be reproduced by:
No idea

**Comment by doomedraven** [comment]
is agent started with admin privileges?

**Comment by Mokatsu** [comment]
No, I do not believe so.

**Comment by doomedraven** [comment]
cuckoo agent should be started as admin, if no not make any sense ;)

**Comment by Mokatsu** [comment]
The guide states to place it into startup folder, shouldn't that run it as admin?

**Comment by doomedraven** [comment]
depends if that is system startup or user startup

**Comment by Mokatsu** [comment]
you were right that fixed it but now a differnt issue is showing up when I submitted eicar.zip file:

WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpwsjyr2/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpwsjyr2/analyzer.py", line 533, in run
    self.prepare()
  File "C:/tmpwsjyr2/analyzer.py", line 505, in prepare
    zipfile.ZipFile(zip_path).extractall(os.environ["TEMP"])
  File "C:\Python27\lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 22] invalid mode ('rb') or filename: u'C:\\Users\\ADMIN-~1\\AppData\\Local\\Temp\\eicar_com.zip'


and: 

cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpwsjyr2/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpwsjyr2/analyzer.py", line 580, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.None", does not exist.

**Comment by doomedraven** [comment]
with that no idea, win10 not officially supported, so you need to try to check what is wrong by yourself, or wait till someone who uses win10 help you, btw can you provide python version which is installed in win10?

**Comment by Mokatsu** [comment]
Seems to only do it on zip files and csv (which Ik know cuckoo does not support). And thanks for the help,
The VM uses 2.7.14

**Comment by doomedraven** [comment]
which cuckoo version? as you not provided that in main issue description

**Comment by Mokatsu** [comment]
2.0.5

**Comment by doomedraven** [comment]
from quick google search looks like python's zipfile on win10 not dealing correctly with path

```
File "C:\Python27\lib\zipfile.py", line 756, in init
self.fp = open(file, modeDict[mode])
IOError: [Errno 22] invalid mode ('rb') or filename: u'C:\Users\ADMIN-~1\AppData\Local\Temp\eicar_com.zip'
```

looks like

**Comment by Mokatsu** [comment]
Thanks

**Comment by jbremer** [comment]
Closing as resolved for now. We have yet to add Windows 10 support though, but this will come eventually.

**Comment by AndyCorreas** [comment]
I have the same problem, but I dont know how to run agent as administrator to the system startup

**Comment by doomedraven** [comment]
go to start -> startup -> right click open for all users, thats it, reboot, done :)

**Comment by AndyCorreas** [comment]
is the same in Windows 7 ?

**Comment by doomedraven** [comment]
Yep if you cant do that by yourself you have a lot of manuals in google

**Comment by AndyCorreas** [comment]
thank you a lot for your help :)

**Comment by doomedraven** [comment]
You are welcome
