### ISSUE TITLE
Only one volatility plugin run at the same time

### ISSUE THREAD

**Issue by cmderpt** [cuckoosandbox/cuckoo#2151]
Hi,
I noticed that only one volatility run at the same time.
That means if I submit 2 samples into 2 vm at the same time. Volatility plugins of the second vm only run when the first one has done. Otherwise, the second vm will wait.

I want they run parallel to improve report time. Can I do it?

**Comment by jbremer** [comment]
What @doomedraven said :-) Closing as resolved, thanks.
