### ISSUE TITLE
cuckoo web running error

### ISSUE THREAD

**Issue by muhammad2321** [cuckoosandbox/cuckoo#2154]
i run cockoo web in command line, using command (cuckoo web)
output 
root@kali:~# cuckoo web
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
help me :(

**Comment by doomedraven** [comment]
please read the msg
```
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
```

http://cuckoo.readthedocs.io/en/latest/installation/

**Comment by RicoVZ** [comment]
Hi muhammad2321,

As doomedraven states, this message indicates you have to have a running MongoDB, and enabled the MongoDB reporting module in reporting.conf.

https://cuckoo.sh/docs/installation/host/configuration.html#reporting-conf
Change `enaled = no` to `enabled = yes`
```
[mongodb]
enabled = no
```

**Comment by jbremer** [comment]
Cockoo gives the error that you're having quite clearly, closing issue as resolved.
