### ISSUE TITLE
Suggestion for URL Analysis

### ISSUE THREAD

**Issue by seantree** [cuckoosandbox/cuckoo#2155]
Hello Guys,

I would like to suggest some idea for improvement of URL analysis in cuckoo sandbox, kindly implement the splinter (https://github.com/cobrateam/splinter) in this, so that cuckoo handle the URL analysis also. For handling these kind of URL's:
hxxp://watchingnewsonline.com/
hxxp://yourmapview.com/
hxxp://easycouponsaccess.com/
hxxp://www.propdfconverter.com/index.jhtml
hxxp://www.gamesquest.co/
hxxp://loginemailsfast.com/
hxxp://emailloginnow.com/Email?

hxxp://www.searchtuner.com/download/?offer_id=712&aff_id=5&url_id=962&source=1319268&aff_sub2=425312588801&ot=1&sah=728&cw=1366&nw=0

hxxp://screenwatch.yournewtab.com/?chid=127&oid=706&pubid=1319268&subid=425321025281&sah=728&cw=1366&nw=0

hxxp://watchmoretvnow.com/
hxxp://www.todaysnewsreporter.com/
hxxp://www.checknetspeed.online/li1tg?t1=test&t5={Browser}&cid=clk_id

hxxp://www.checkmyspeed.co/bir14?t1=S_Restructure_Test&t2={adgroup_name}&t3=speedtest%20net&t4=1t1&t5=250999826041&gclid=EAIaIQobChMIo_Wuq--72QIVl7rACh1tQAnzEAAYASAAEgIBkPD_BwE

hxxp://www.watchtvinstantly.com/?r=3&kw=Weather%20Season&gclid=EAIaIQobChMIhvatk7Of1gIVDLcbCh11UgoiEAAYAyAAEgJ9APD_BwE

hxxp://www.getsports.net/
hxxp://www.moviesearch.today/

Thanks & Regards 
Seantree

**Comment by Nwinternights** [comment]
I was thinking about Thug: https://github.com/buffer/thug it uses Api for external calls: https://buffer.github.io/thug/doc/api.html
regards

**Comment by seantree** [comment]
@Nwinternights I know about it but it won't work in that way thug will only analyze the URL but if someone implement URL + File Behaviour that would be awesome think about it of Addons Analysis where they create entries in Registry, temp, drives etc. I hope you got my point :)

**Comment by Nwinternights** [comment]
@seantree Actually thug downloads also "interesting"files that finds during its crawling. I found it very useful especially when , for example, you want to analyze an Office Document, Pdf, Email with embedded links used for download the payload(cuckoo actually doesn't go to href ). Making part of cuckoo processing core(resubmit task in case of download file) can be very useful. By the way I'll take a deeper look at Splinter and Im sure it's very interesting. regards

**Comment by seantree** [comment]
@Nwinternights Ok I will check thug also, just want to know one thing have you installed thug on the docker or without using any docker

**Comment by Nwinternights** [comment]
I use it without docker. Regards

**Comment by seantree** [comment]
Hi @Nwinternights I have also setup thug on my VM lets see how it works :)

**Comment by seantree** [comment]
Does anyone knows how to submit multiple URL in thug at one time?

**Comment by jbremer** [comment]
Closing issue as irrelevant (and no, I don't know if that's possible).
