### ISSUE TITLE
Multiple routing settings issue(VPN)

### ISSUE THREAD

**Issue by hakawati** [cuckoosandbox/cuckoo#2156]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:

Multiple routing setting issue.

I would like to install and run both inetsim, tor and vpn. 
I installed inetsim and tor, that works well.
But when I installed vpn, I could not use any network other than vpn.

##### My Cuckoo version and operating system are:

Cuckoo - 2.0.5.3
OS - Ubuntu 16.04

##### This can be reproduced by:

1. It seems that cuckoo should be running before vpn is run.
2. For this reason, all networks in the operating system use vpn.
3. Getting cuckoo version information or getting malware detection information through virustotal does not work. (Using port 443)
4. The idea is that when cuckoo starts analyzing(enabled & selected vpn routing), vpn is executed. When the analysis is finished, run reporting after the vpn is shut down.

**Comment by doomedraven** [comment]
hello, do search in issues I posted the solution to this few times

**Comment by hakawati** [comment]
@doomedraven hello, I've looked at the issue to mention the 2.0 RC, but I'm not sure what the solution is. If you do not mind, ask for a link.

**Comment by doomedraven** [comment]
you just need to provide the args to openvpn when you start it, to not force routing to vpn all the stuff

**Comment by vladbrinzea** [comment]
Hi doomedraven, could you be more specific when you say you posted the solution to this a few times, maybe link to it? Having similar problems and struggling to find a fix.

**Comment by doomedraven** [comment]
Sorry i dont, im on vacations and from phone till next week

Search for “route.py” or openvpn in issues

**Comment by RicoVZ** [comment]
Hi @vladbrinzea, I see you have replied on https://github.com/cuckoosandbox/cuckoo/issues/2118. It seems your issue is fixed, can we close this issue?

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
