### ISSUE TITLE
How to get the time point of the virtual box analysis completed

### ISSUE THREAD

**Issue by PointerWild** [cuckoosandbox/cuckoo#2157]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

#####My issue is:
   I want to know when the Guest (virtual box) executes the end of the analysis. Then ,at this time , I will begin to executes another program.
How could I make the machine know the time as descripted above, and then executes another program. 
#####My Cuckoo version and operating system are:
Ubuntu 16.0.4 / Cuckoo 2.0.5

**Comment by doomedraven** [comment]
check the db for task `reported status` and check the rest fields, you have the date there

**Comment by PointerWild** [comment]
Hi  doomedraven :+1: 
Thank you very much! I get it!

**Comment by doomedraven** [comment]
glad to hear that :)

**Comment by PointerWild** [comment]
This can be reproduced by:
1. As doomedraven said.
    check the rest fields.   at the path :  .cuckoo/storage/analyses/1/reports . there are some files when task starts, and when the task is end, there are some new files and one of them is named as reports.
   At local MongoDB ,  database name : cuckoo  , collections name : analysis  ,  option name: info 
there is the time which the task start and end.
The log, error, files etc can be found at:

**Comment by PointerWild** [comment]
Hi doomedraven 
Thank you very much !
