### ISSUE TITLE
How do you create a baseline?

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2163]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Attempting to create a baseline

##### My Cuckoo version and operating system are:
2.0.5, Debian Stretch

##### This can be reproduced by:
cuckoo --baseline

##### The log, error, files etc can be found at:
Error: no such option: --baseline

http://cuckoo.readthedocs.io/en/latest/usage/submit/

**Comment by najashark** [comment]
Try 
```
cuckoo submit --machine cuckoo1 --baseline
```
cuckoo1 is the machine name

**Comment by DigiAngel** [comment]
Worked a treat thanks.
