### ISSUE TITLE
VBoxManage failed starting the machine in HEADLESS mode

### ISSUE THREAD

**Issue by choiwj1216** [cuckoosandbox/cuckoo#2166]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html
Yes,
##### My issue is:
Did not change anything in Vbox, but testing the cuckoo instance with an submission for an url and a file I get the following error.

##### My Cuckoo version and operating system are:
Ubuntu running Win7 vbox
##### The log, error, files etc can be found at:

Error: Machinery error: VBoxManage failed starting the machine in HEADLESS mode: VBoxManage: error: cpum#1: “CPU model” mismatch: host=0x4f saved=0xf [ver=17 pass=final] (VERR_SSM_LOAD_CPUID_MISMATCH) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

**Comment by doomedraven** [comment]
that is the vbox error, not cuckoo's

**Comment by jbremer** [comment]
Seems like you've copied the VM over from another computer or so. Please setup your environment properly. Closing as resolved.
