### ISSUE TITLE
Documentation is not accessible via readthedocs

### ISSUE THREAD

**Issue by reox** [cuckoosandbox/cuckoo#2170]
##### My issue is:

Looks like there is some misconfiguration with https and readthedocs:

Going to https://readthedocs.org/projects/cuckoo/ and click on latest gives me

> The owner of docs.cuckoosandbox.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 
> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

See also ssltest: https://www.ssllabs.com/ssltest/analyze.html?d=docs.cuckoosandbox.org

Workaround: Use this link: http://cuckoo.readthedocs.io/en/latest/

**Comment by appleorange1** [comment]
Further information: This URL is given as a reference in some error messages, e.g.
> CuckooCriticalError: Unable to bind ResultServer on 192.168.56.1:2042 [Errno 99] Cannot assign requested address. This usually happens when you start Cuckoo without bringing up the virtual interface associated with the ResultServer IP address. Please refer to http://docs.cuckoosandbox.org/en/latest/faq/#troubles-problem for more information.

I can confirm that reox's workaround works.

**Comment by jbremer** [comment]
Thanks - we're aware of this, but this isn't something I can fix on my own (unfortunately).
Next release has working URLs embedded, see also cc3f1f632880448ba26ad93cd76badee164eeae4.
Closing as resolved.

**Comment by reox** [comment]
Not sure if you can do something about this, but if you search on RTD for something, the found pages link to http://docs.cuckoosandbox.org/... even though I was on https://cuckoo.readthedocs.io

**Comment by RicoVZ** [comment]
@reox Ah, for a slightly more updated version of the docs, see https://cuckoo.sh/docs. That issue will not happen on there. :smile:
