### ISSUE TITLE
compare analysis

### ISSUE THREAD

**Issue by d4n13l4** [cuckoosandbox/cuckoo#2171]
I was wondering how the compare analysis part should work.

I have running cuckoo and I wanted to compare two files and the picture is all I see, if I hover the mouse in the white rectangle and it shows some percentages that appear at the bottom of the screen also.
![image](https://user-images.githubusercontent.com/28959974/37340143-c9f621f2-26c5-11e8-90d6-7bdde2d259c0.png)

what is the intended results of this comparison part? I couldn't find much information so I figured asking here might help
I'm using cuckoo 2.0.5
ubuntu 16.04

thanks

**Comment by jbremer** [comment]
Yeah, this feature isn't really maintained or anything. We should probably comment it out for "the time being". Closing as wontfix, sorry.
