### ISSUE TITLE
Cuckoo is not finding my VM's

### ISSUE THREAD

**Issue by k142094** [cuckoosandbox/cuckoo#2172]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Cuckoo is not able to find the VMs i have made on my virtual box:
2018-03-14 11:33:20,496 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-03-14 11:33:21,106 [cuckoo] CRITICAL: CuckooCriticalError: Please update your configuration. Unable to shut 'STOCK' down or find the machine in its proper state: The virtual machine 'STOCK' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!

##### My Cuckoo version and operating system are:
OS: Ubuntu 16.04.1
Cuckoo Version: 2.0.5
VirtualBox: 5.1.34
VM: Windows7x86Sp1

everything running as root
##### This can be reproduced by:
https://www.youtube.com/watch?v=Y34uvi8-e18&disable_polymer=true

##### The log, error, files etc can be found at:
here are the complete config info
#Auxillary.conf
[sniffer]
enabled = yes
tcpdump = /usr/sbin/tcpdump
bpf = 

[mitm]
enabled = yes
mitmdump = /usr/local/bin/mitmdump
port_base = 50000
script = stuff/mitm.py
certificate = bin/cert.p12

[services]
enabled = no
services = honeyd
timeout = 0

[reboot]
enabled = yes

#Cuckoo.conf
[cuckoo]
version_check = yes
delete_original = no
delete_bin_copy = no
machinery = virtualbox
memory_dump = yes
terminate_processes = no
reschedule = no
process_results = yes
max_analysis_count = 0
max_machines_count = 0
max_vmstartup_count = 10
freespace = 1024
tmppath = 
rooter = /tmp/cuckoo-rooter

[feedback]
enabled = no
name = 
company = 
email = 

[resultserver]
ip = 192.168.56.1
port = 2042
force_port = no
upload_max_size = 134217728

[processing]
analysis_size_limit = 134217728
resolve_dns = yes
sort_pcap = yes

[database]
connection = 
timeout = 60

[timeouts]
default = 120
critical = 60
vm_state = 60

#Memory.conf
[basic]
guest_profile = Win7SP1x86
delete_memdump = no

[malfind]
enabled = yes
filter = yes

[apihooks]
enabled = no
filter = yes

[pslist]
enabled = yes
filter = no

[psxview]
enabled = yes
filter = no

[callbacks]
enabled = yes
filter = no

[idt]
enabled = yes
filter = no

[timers]
enabled = yes
filter = no

[messagehooks]
enabled = no
filter = no

[getsids]
enabled = yes
filter = no

[privs]
enabled = yes
filter = no

[dlllist]
enabled = yes
filter = yes

[handles]
enabled = yes
filter = yes

[ldrmodules]
enabled = yes
filter = yes

[mutantscan]
enabled = yes
filter = yes

[devicetree]
enabled = yes
filter = yes

[svcscan]
enabled = yes
filter = yes

[modscan]
enabled = yes
filter = yes

[yarascan]
enabled = yes
filter = yes

[ssdt]
enabled = yes
filter = yes

[gdt]
enabled = yes
filter = yes

[sockscan]
enabled = yes
filter = no

[netscan]
enabled = yes
filter = no

[mask]
enabled = no
pid_generic =

#Physical.conf
[physical]
machines = physical1
user = username
password = password
interface = eth0

[fog]
hostname = none
username = fog
password = password

[physical1]
label = physical1
platform = windows
ip = 192.168.56.101
osprofile =

#Processing.conf
[analysisinfo]
enabled = yes

[apkinfo]
enabled = no
decompilation_threshold = 5000000

[baseline]
enabled = no

[behavior]
enabled = yes

[buffer]
enabled = yes

[debug]
enabled = yes

[droidmon]
enabled = no

[dropped]
enabled = yes

[dumptls]
enabled = yes

[extracted]
enabled = yes

[googleplay]
enabled = no
android_id = 
google_login = 
google_password = 

[memory]
enabled = yes

[misp]
enabled = no
url = 
apikey = 
maxioc = 100

[network]
enabled = yes
whitelist_dns = no
allowed_dns = 

[procmemory]
enabled = yes
idapro = no
extract_img = yes
extract_dll = no
dump_delete = no

[procmon]
enabled = yes

[screenshots]
enabled = yes
tesseract = no

[snort]
enabled = no
snort = /usr/local/bin/snort
conf = /etc/snort/snort.conf

[static]
enabled = yes
pdf_timeout = 60

[strings]
enabled = yes

[suricata]
enabled = no
suricata = /usr/bin/suricata
conf = /etc/suricata/suricata.yaml
eve_log =  eve.json
files_log = files-json.log
files_dir = files
socket = 

[targetinfo]
enabled = yes

[virustotal]
enabled = no
timeout = 60
scan = no
key = a0283a2c3d55728300d064874239b5346fb991317e8449fe43c902879d758088

[irma]
enabled = no
timeout = 60
scan = no
force = no
url =

#Reporting.conf
[feedback]
enabled = no

[jsondump]
enabled = yes
indent = 4
calls = yes

[singlefile]
enabled = yes
html = yes
pdf = yes

[misp]
enabled = no
url = 
apikey = 
mode = maldoc ipaddr hashes url

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
username = 
password = 

[elasticsearch]
enabled = no
hosts = 127.0.0.1
timeout = 300
calls = no
index = cuckoo
index_time_pattern = yearly
cuckoo_node = 

[moloch]
enabled = no
host = 
insecure = no
moloch_capture = /data/moloch/bin/moloch-capture
conf = /data/moloch/etc/config.ini
instance = cuckoo

[notification]
enabled = no
url = 
identifier = 

[mattermost]
enabled = no
url = 
myurl = 
username = cuckoo
show_virustotal = no
show_signatures = no
show_urls = no
hash_filename = no
hash_url = no

#Routing.conf
[routing]
route = none
internet = none
rt_table = main
auto_rt = yes
drop = no

[inetsim]
enabled = no
server = 192.168.56.1

[tor]
enabled = no
dnsport = 5353
proxyport = 9040

[vpn]
enabled = no
vpns = vpn0

[vpn0]
name = vpn0
description = Spain, Europe
interface = tun0
rt_table = tun0

[virtualbox]
mode = gui
path = /usr/bin/VBoxManage
interface = vboxnet0
machines = STOCK

[STOCK]
label = STOCK
platform = windows
ip = 192.168.56.101
snapshot = snapshot1
interface = vboxnet0
resultserver_ip = 
resultserver_port = 
tags = 
options = 
osprofile = 

[honeyd]
label = honeyd
platform = linux
ip = 192.168.56.1
tags = service, honeyd
options = nictrace noagent

**Comment by k142094** [comment]
the video was the tutorial i was following and i have zero idea why it works as it should in the video

**Comment by doomedraven** [comment]
so far your conf is fine
 check in terminal

post output of `vboxmanage list vms`

**Comment by k142094** [comment]
ran everything with under cuckoo user everything is fine now apparently cuckoo itself wasnt root
sorry for the bother
