### ISSUE TITLE
Windows7: analysis caught an exception

### ISSUE THREAD

**Issue by Cry0k** [cuckoosandbox/cuckoo#2177]
every time i'm trying to run any malware on my sandbox i get the following error:
2018-03-17 12:41:02,057 [cuckoo.core.guest] WARNING: Windows7: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpphzfmp/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpphzfmp/analyzer.py", line 650, in run
    pids = self.package.start(self.target)
  File "C:\tmpphzfmp\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmpphzfmp\lib\common\abstracts.py", line 166, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

i am using cuckoo 205 and guest python version is 2.7.14 
i have tried every solution that i found including rebuilding cuckoo from scratch and reinstalling guest vm and nothing helps.

any help will be appreciated

**Comment by Cry0k** [comment]
![screenshot from 2018-03-17 13-24-53](https://user-images.githubusercontent.com/37481568/37558210-dc5fb488-29e6-11e8-9c98-c18d2d1002ee.png)
 that is the error that i've got on the guest VM when trying to run an analysis

**Comment by doomedraven** [comment]
Without sample impossible to help

**Comment by Cry0k** [comment]
the sample that made the error in the screen shot in a basic installation of python 2.7.14
 and the second sample that gives the main issue is : 
ed8761e11d819e6794cbcf9b9661f316ff5cc8bdbf8dfca614fb555ec228fd71
this is a ransomware sample named Cancer

**Comment by av-gantimurov** [comment]
Please read screenshot carefully.
You are not running Cuckoo Agent as administrator at sandbox.

**Comment by Cry0k** [comment]
Ok thanks that's one problem but what do I do with the second one ?(the one in the original post)

**Comment by av-gantimurov** [comment]
Did you try rerun analysis with agent started with admin priv?

**Comment by Cry0k** [comment]
Hi I did try to run the sample with agent as admin still got the same issue and the firewall is disabled and as far as the sample goes please see my second comment I put the hash there you can download it from hybrid-analysis.com

**Comment by Cry0k** [comment]
i close this issue cuz i found out the problem.. the name of the user in guet machine wasn't Administrator even thou he had admin privileges apperently cuckoo is sensetive tio the user name of the guest...
