### ISSUE TITLE
Using Cuckoo module in YARA to detect network traffic

### ISSUE THREAD

**Issue by srikwit** [cuckoosandbox/cuckoo#2179]
##### My issue is:
I am writing my YARA rules to detect network traffic as per http://yara.readthedocs.io/en/v3.6.3/modules/cuckoo.html.

I have placed the rules within yara/urls folder and have also tried placing it in yara/binaries folder.

My rules work only on files and hashes but none get triggered for network based traffic.

Kindly let me know if this is the right approach for analyzing network traffic to add into the report or if I should be using any other alternative approach such as Snort/Suricata.

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.5
Operating system: Ubuntu 16.04

##### This can be reproduced by:
1. Setting up Cuckoo
2. Placing YARA rules for traffic towards a malware domain in the URLs folder as per http://yara.readthedocs.io/en/v3.6.3/modules/cuckoo.html
3. Running cuckoo with the malware that sends traffic towards the said domain
4. No YARA rule being triggered.

**Comment by jbremer** [comment]
Closing as resolved - IMO Suricata is the way to go here.

**Comment by srikwit** [comment]
Yes it answers my question, sorry for the late reply.
