### ISSUE TITLE
Discussion processing modules 

### ISSUE THREAD

**Issue by vcahkjsa** [cuckoosandbox/cuckoo#2187]
Hi everyone! 

I'm creating a processing module, I know that all information generated by the processing modules are sent to the Global Container, but I want to know if I can access to the information stored in Global Container to perfom some action in my module?

Thanks in advance.

**Comment by RicoVZ** [comment]
Hi vcahkjsa,

Yes, you sure can. Each processing module implements the abstract class `Processing`, which has the attribute `results`. Each processing module getting executed receives all results processed until that point inside that attribute.

Now, to actually make that more useful, you would likely want to have a say about when your processing module gets executed. This is possible by using the `order` class attribute of your processing module. Set it to a number higher than any of the other processing modules.

This will cause your module to be sorted at the end and also be processed last.

**Comment by vcahkjsa** [comment]
Hi @jbremer, 

Based on @RicoVZ answer, the last week I created a new module using the Global Container `results` member. I appreciate a lot your attention.

**Comment by jbremer** [comment]
Sounds like this issue can be closed - doing so. Thanks!
