### ISSUE TITLE
API sequence

### ISSUE THREAD

**Issue by kma94dz** [cuckoosandbox/cuckoo#2190]

**Comment by doomedraven** [comment]
Documentation ;)

**Comment by RicoVZ** [comment]
Hi kma94dz,

You can find all API call sequences in the Cuckoo web interface `Behavioral analysis` tab. In here, a process tree can be found containing all api sequences per process. You can browse through them, search etc.

For the web interface to work, you will need to enable MongoDB.
See https://cuckoo.sh/docs/usage/web.html for more information on how to enable this and start the web interface.

 You can also find them in the JSON report (`$CWD/storage/analyses/<id>/reports/report.json`).

**Comment by kma94dz** [comment]
Hi thanks for the info
In report.json  they are in [behavior] [processes] [calls]?

**Comment by RicoVZ** [comment]
Yes, that is correct @kma94dz.

**Comment by kma94dz** [comment]
Ok thanks
Issue closed
