### ISSUE TITLE
Unable to use Suricata in socket mode - cuckoo cannot find suricatasc

### ISSUE THREAD

**Issue by vladbrinzea** [cuckoosandbox/cuckoo#2193]
##### My issue is: 
Trying to use Suricata in Socket mode but unable to because Cuckoo cannot find suricatasc (which is available). 

##### My Cuckoo version and operating system are:
Cuckoo 2.0.5 running in a python virtualenv on Ubuntu 16.04 LTS

##### This can be reproduced by:
Configure suricata in unix socket mode. Configure cuckoo to use suricata in socket mode

##### The log, error, files etc can be found at:

![image](https://user-images.githubusercontent.com/15797863/37915718-0cb6c1a8-3112-11e8-9ebe-d40e38c144fb.png)

![image](https://user-images.githubusercontent.com/15797863/37915822-5022bcb2-3112-11e8-8f3d-b76db31b45a0.png)

![image](https://user-images.githubusercontent.com/15797863/37915926-704a528e-3112-11e8-841c-13f1ae75bd3c.png)

![image](https://user-images.githubusercontent.com/15797863/37915957-89703332-3112-11e8-91ad-78ae3af56d68.png)

**Comment by doomedraven** [comment]
weird, i have it working just fine on 16.04, which is Suricata version?
try to start python and do `import suricatasc`

**Comment by vladbrinzea** [comment]
(cuckoo-env1) cuckoo@cuckoo-01:~$ suricata -V
This is Suricata version 4.0.4 RELEASE

(cuckoo-env1) cuckoo@cuckoo-01:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import suricatasc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named suricatasc
>>>

Suricata was installed on the system via sudo add-apt-repository ppa:oisf/suricata-stable and sudo apt-get install suricata. Cuckoo 2.0.5 was installed on the system in a python virtual environment using pip install cuckoo. 

I believe Suricata was installed **after** cuckoo, should that make any difference?

**Comment by doomedraven** [comment]
maybe idk, try to install `suricatasc` inside of the venv, maybe it not picks the system wide suricatasc

**Comment by vladbrinzea** [comment]
Just found that the issue is caused by the use of a python virtual environment... When I try to start python outside the venv and import suricatasc there, it works...

cuckoo@cuckoo-01:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
">>> import suricatasc
">>>

So in summary, when installing suricata on the system using apt-get, that does not update the python libraries inside any of the venvs, just the python libraries on the actual system.

**Comment by doomedraven** [comment]
solved? btw check https://github.com/cuckoosandbox/cuckoo/pull/2183

**Comment by vladbrinzea** [comment]
Solved at this point although I would consider this a workaround since all I did was copy the suricatasc folder from /usr/lib/python2.7/dist-packages/ to (venv)/lib/python2.7/site-packages. Although this is not something to blame on cuckoo directly, anyone following the documentation at this point will be faced with the exact problem.

Do you know of a more "official" method to get suricatasc recognised by a python venv that does not require copying the folder over?

Regarding #2183 - since I have cuckoo working inside of a venv, there is no /stuf folder and no suricata.sh file present anywhere in the venv or CWD directory structure. I know that file is not mandatory, it's just a nice wrapper to get suricata started correctly at every boot, but anyone following the docs currently and using a venv will not be affected by that change. Am I missing something here?

**Comment by doomedraven** [comment]
just add suricatasc to setup.py of cuckoo or install in directly inside of the venv, i pointed to that not for the stuff or suricata.sh, i pointed to help you set rule reload as that wasn't mentioned in docu
