### ISSUE TITLE
Choosing which machine is default

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2203]
##### My issue is:
Just wanting to know how to choose the default machine

##### My Cuckoo version and operating system are:
Latest cuckoo, Debian stretch

##### This can be reproduced by:
I have this in my my file:
machines = win732cuckoo2,win764cuckoo2
with cuckoo 1 it was the first machine specified, but right now win764 gets ran unless I manually change it.

**Comment by doomedraven** [comment]
change that on webgui source to set that to default vm, but be avare to select another later if no all samples will go to the same

**Comment by DigiAngel** [comment]
Hrmm.....each time I have to set it to that win732 one...is there no way to set a default and have it stay set?

**Comment by doomedraven** [comment]
if that always pics another, check how it loads the vms in code, maybe playing with filenames it solves that to you

**Comment by DigiAngel** [comment]
Ok...originally I had the 64 bit first, and then swapped them...for some reason that didn't work.  Let you know what my results are thanks.

**Comment by DigiAngel** [comment]
So after testing indeed...the last picked machine is the one that is used.  Thank you!
