### ISSUE TITLE
Can cuckoo provide us some infomation of the apis aggregated in the same code block or function?

### ISSUE THREAD

**Issue by yiranxijie** [cuckoosandbox/cuckoo#2207]
##### My issue is:
I want to know more about the malware's behavior. Suppose I've got a JSON Report like this:
![image](https://user-images.githubusercontent.com/12460007/38090571-9c801796-3395-11e8-873b-9ea24c3b9b0a.png)
I just want to know which of these API are gathered together?They may belong to the same code block or function. Can cuckoo provide us some infomation of the group of api in codeblock? I guess it is easy to record those apis with group when hook run.

**Comment by jbremer** [comment]
No, Cuckoo can't do grouping based on code blocks. This is purely based on behavioral information captured at runtime. Does that answer your question?

**Comment by yiranxijie** [comment]
Ok,Thanks!

**Comment by jbremer** [comment]
Closing as the question has been answered. Feel free to create a new issue if you have another question. Thanks.
