### ISSUE TITLE
API Report very slow

### ISSUE THREAD

**Issue by vkuehn** [cuckoosandbox/cuckoo#2210]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
That calling the report api is a very slow for me as the lab is behind some firewalls. However view ist pretty fast. would it be possible to get score a part of the view result ?
##### My Cuckoo version and operating system are:
Cuckoo version 2.04
##### This can be reproduced by:
call api and compare the size of the returned json's
/tasks/view
/tasks/report
##### The log, error, files etc can be found at:
no log error

**Comment by RicoVZ** [comment]
Hi vkuehn,

By default the `tasks/view` does not return the score. It just contains the basic task info. It is possible to add it, but you would need to pull the score from MongoDB. By default, the score is only stored in the jsonreport, and MongoDB if this is enabled.

My recommendation would be to disable storing all API calls in the json report. It usually greatly decreases the report size. This way, you could still pull the report from your lab, and you would not have to edit any code.

You can disable the json api call section per analysis, and also entirely by performing one of these actions:

The option `json.calls=0` can be added when submitting a task. It is  also possible to completely disable API calls in the json report. You can do this by changing `calls = yes` in reporting.conf to `calls = no`, This setting is located under `[jsondump]`.

**Comment by vkuehn** [comment]
Hi RicoVZ,

thanks for the explenations. Thought it is merely a confiruation topic not really an issue
Therfore closed

Thanks
V

**Comment by vkuehn** [comment]
Sorry have to reopen that...
would it be possible only for the url submits to disable API calls (thought there is not much sense ?)  ?
if so where could I do that ?

**Comment by doomedraven** [comment]
`The option json.calls=0 can be added when submitting a task`
in webgui you have field options, and with `cuckoo submit` you can do that also, check `--help`

**Comment by RicoVZ** [comment]
`json.calls=0` is an option in Cuckoo. Options can be submitted to each task. It does not matter how it is submitted.

Submitting options to the web API is certainly possible. Just add your options as a single string, seperated by comma's into a form field called `options`. The option should be given when submitting a task. The report will then be generated without the api calls.

Example:
`curl -F file=@/path/to/file http://localhost:8090/tasks/create/file -F options="json.calls=0"`

**Comment by vkuehn** [comment]
it's about submitted urls ! However I tried it but there is no diference in the report sizes
Maybe urls analyses don't create a difference even if json.calls=0!?
Our LAB is behind a firewall and an old dsl connection. An Url report can be a view megabytes which is than a pain to get back....any advice ?

**Comment by doomedraven** [comment]
it should work everywhere as url analysis still opened in browser so grabs behav. if you don't wanna use that check pull request there an iocs endpoint to simplify report

**Comment by vkuehn** [comment]
closed as not responded after 10 days...probably personal destiny
