### ISSUE TITLE
Submit Malware Folder

### ISSUE THREAD

**Issue by Andre-Bryan** [cuckoosandbox/cuckoo#2214]
##### My issue is:
How do I submit a zip folder with malware and run the file that is needed to activate the malware? 
I am running cuckoo submit and cuckoo in order to see what the malware is doing.
##### My Cuckoo version and operating system are:
Cuckoo 2.0.5
Uubuntu 16.04
VirtualBox Windows 7 32 Bit

**Comment by jbremer** [comment]
Please try our Web Interface, it has support for exactly that. Closing as resolved.
