### ISSUE TITLE
Add Email Upload File Type Support

### ISSUE THREAD

**Issue by markconover** [cuckoosandbox/cuckoo#2219]
Disregard this feature request as I now realized that the latest code for Cuckoo Sandbox supports .msg file uploads (and also extracts the email attachments from the email).

**Comment by jbremer** [comment]
Just asking to make sure: did you try submitting a `.msg` to Cuckoo? :-P

**Comment by markconover** [comment]
I guess my Cuckoo Sandbox was not fully updated.  I apologize for making this feature request.  I will remove it.

**Comment by jbremer** [comment]
@thevidocq Sure thing! And if it doesn't, please share a sample and we'll fix it ;-)

**Comment by jbremer** [comment]
Closing as resolved.
