### ISSUE TITLE
Cuckoo1 not ready yet problem !! 

### ISSUE THREAD

**Issue by yesb0919** [cuckoosandbox/cuckoo#2222]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:
2018-04-06 18:23:50,266 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:51,270 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:52,274 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:53,279 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:54,284 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:55,288 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:56,293 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:57,296 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:58,300 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:23:59,306 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:24:00,310 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:24:01,315 [cuckoo.core.guest] DEBUG: cuckoo1: not ready yet
2018-04-06 18:24:02,317 [cuckoo.core.scheduler] ERROR: Error from machine 'cuckoo1': it appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2018-04-06 18:24:02,356 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: MITM
2018-04-06 18:24:02,381 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-04-06 18:24:02,381 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuckoo1
2018-04-06 18:24:03,981 [cuckoo.core.scheduler] DEBUG: Released database task #11
2018-04-06 18:24:04,116 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #11
2018-04-06 18:24:04,118 [cuckoo.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/yesb/.cuckoo/storage/analyses/11/logs'.
2018-04-06 18:24:04,119 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #11
2018-04-06 18:24:04,120 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #11
2018-04-06 18:24:04,121 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #11
2018-04-06 18:24:04,125 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #11
2018-04-06 18:24:04,126 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #11
2018-04-06 18:24:04,126 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #11
2018-04-06 18:24:04,127 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #11
2018-04-06 18:24:04,143 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #11
2018-04-06 18:24:04,146 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #11
2018-04-06 18:24:04,159 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #11
2018-04-06 18:24:04,161 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #11
2018-04-06 18:24:04,161 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #11
2018-04-06 18:24:04,162 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #11
2018-04-06 18:24:04,162 [cuckoo.processing.debug] ERROR: Error processing task #11: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2018-04-06 18:24:04,181 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #11
2018-04-06 18:24:04,182 [cuckoo.core.plugins] DEBUG: Running 0 signatures
2018-04-06 18:24:04,188 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"

**Comment by yesb0919** [comment]
i already read  and triple - checked it.
but still have a problem

**Comment by doomedraven** [comment]
that looks like you have problems with agent in vm, do `curl vm_ip:8000`  and see if no response than your agent isn't started correctly + snapshot

**Comment by yesb0919** [comment]
when i type the curl ip:8000(i also typed cuckoo -d and cuckoo web -H #ip -p), it show this log 
>> curl 192.168.56.1:8000

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Cuckoo Sandbox</title>
        <link rel="shortcut icon" type="image/png" href=" /static/favicon-64x64.png" sizes="64x64" />
        <link rel="shortcut icon" type="image/png" href=" /static/favicon-32x32.png" sizes="32x32" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Cuckoo Sandbox" />
        <meta name="author" content="Cuckoo Sandbox" />

        <link href="/static/css/vendor.css" rel="stylesheet" type="text/css" />
        <link href="/static/css/main.css" rel="stylesheet" type="text/css" />

        

        <script src="/static/js/vendor.js"></script>
        <script src="/static/js/handlebars-templates.js"></script>
        <script src="/static/js/hexdump.js"></script>
        <script src="/static/js/cuckoo/loader.js"></script>
        <script src="/static/js/cuckoo/sticky.js"></script>
        <script src="/static/js/cuckoo/analysis_sidebar.js"></script>
        <script src="/static/js/cuckoo/submission.js"></script>
        <script src="/static/js/cuckoo/process_tree.js"></script>
        <script src="/static/js/cuckoo/recent.js"></script>
        <script src="/static/js/cuckoo/analysis_network.js"></script>
        <script src="/static/js/cuckoo/app.js"></script>

    </head>

    <body

        

        id="dashboard.views.index"

    >

    

<nav class="app-nav" id="primary-nav">

	<a href="/" class="logo">
		<img src="/static/graphic/cuckoo_inverse.png" />
	</a>

	<ul class="app-nav__nav--primary">
		<li class="active"><a href="/dashboard/"><i class="fa fa-tachometer"></i> Dashboard</a></li>
		<li ><a href="/analysis/"><i class="fa fa-th-list"></i> Recent</a></li>
		<li ><a href="/analysis/pending/"><i class="fa fa-cogs"></i> Pending</a></li>
		<li ><a href="/analysis/search/"><i class="fa fa-search"></i> Search</a></li>
	</ul>

	<ul class="app-nav__nav--right">
		<li>
			<a href="/submit/" class="button outline">Submit</a>
		</li>
		<li>
			<a href="/analysis/import/" class="button outline">Import</a>
		</li>
		<li class="app-nav__dropdown--parent">
			<a href="#" id="select-theme">
				<i class="fa fa-paint-brush"></i>
			</a>
			<div class="app-nav__dropdown">
				<h5>Select theme</h5>
				<ul class="flex-distribute theme-selection">
					<li><a class="active" href="theme:default">Default</a></li>
					<li><a  href="theme:cyborg">Cyborg</a></li>
					<li><a  href="theme:night">Night</a></li>
				</ul>
			</div>
		</li>
	</ul>

</nav>

<div class="app">
	

	<div class="app-message hidden" data-message="browser-recommendation">
		<h5><i class="fa fa-warning"></i> Browser recommendation</h5>
		<p>Hello, we noticed that you are using <span class="browser"></span>. For the best performance of this application, we recommend to use <a href="https://www.google.com/chrome/browser/desktop/index.html" title="Chrome" target="_blank">Chrome</a>, <a href="https://www.mozilla.org/nl/firefox/new/" title="Firefox" target="_blank">Firefox</a> or any browser that supports <a href="https://webkit.org/" title="WebKit" target="_blank">WebKit</a>.</p>
		<div class="clearfix">
			<a href="#dismiss" class="button pull-left">Dismiss</a>
			<a href="#hide" class="button inversed pull-right">Don't show again</a>
		</div>
	</div>

	

<div id="cuckoo-dashboard" class="hidden"></div>

<div class="flex-grid__horizontal--grow dashboard">
    <div class="flex-grid__column dashboard__left">
        <h2 class="dashboard__col-title">Insights</h2>

        <div class="dashboard-module" data-dashboard-module="installation">
            <header class="dashboard-module__header">
                <h4>Cuckoo Installation</h4>
            </header>
            <section class="dashboard-module__body">
                <table class="simple">
                    <tbody>
                        <tr>
                            <td>Version</td>
                            <td>2.0.5</td>
                        </tr>
                        <tr class="up-to-date">
                          <td class="stretch" colspan="2"><em class="show-loaded">You are up to date.</em></td>
                        </tr>
                        <tr class="latest-version">
                            <td>Available</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </section>

            <footer class="dashboard-module__footer">
                <p><i class="fa fa-exclamation-triangle"></i> A new version has been released. <a href="#">Update now</a></p>
            </footer>

        </div>

        <div class="dashboard-module">
            <header class="dashboard-module__header">
                <h4>Usage statistics</h4>
            </header>
            <section class="dashboard-module__body">
                <table class="simple">
                    <tbody data-populate="statistics">
                        <tr>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </section>
            
        </div>

        
        <div class="dashboard-module" data-dashboard-module="blogposts">
          <header class="dashboard-module__header">
            <h4><i class="fa fa-newspaper-o icon-left"></i> From the press:</h4>
          </header>
          <section class="dashboard-module__body">

            
            
            <template id="blogpost-template">
              {{#if posts}}
                <ul class="content-list">
                  {{#each posts}}
                    <li>
                      <a href="{{url}}" title="Read '{{title}}' on cuckoosandbox.org" target="_blank">
                        {{#if important}}
                          <i class="fa fa-star"></i>
                        {{/if}}
                        {{title}}
                          <time>{{date}}</time>
                        {{#if oneline}}
                          <blockquote>&ldquo;{{oneline}}&rdquo;</blockquote>
                        {{/if}}
                      </a>
                    </li>
                  {{/each}}
                </ul>
              {{else}}
                <p class="dashboard-module__body--text">No blogposts have been loaded <small>(this indicates version_check has been disabled in cuckoo.conf)</small>.</p>
              {{/if}}
            </template>
            

          </section>
          <footer class="dashboard-module__footer">
            <p><a href="http://www.cuckoosandbox.org/blog" target="_blank" title="Full list of our literature on cuckoosandbox.org">Click here for more</a></p>
          </footer>
        </div>

    </div>
    <div class="flex-grid__column dashboard__right">

        <h2 class="dashboard__col-title">Cuckoo</h2>

        <div class="dashboard-module__lg" data-dashboard-module="upload">
            <div class="dashboard-module__body omni-uploader">

                <div class="dashboard-module__body--left">

                    <div class="stack">
                        <div class="uploader-area" id="dashboard-submit"></div>
                        <div class="hidden csrf_placeholder" id="analysis_token"><input type='hidden' name='csrfmiddlewaretoken' value='7HppEp9vtXHF8aKlXC0hYeNX0Txol4RV' /></div>
                    </div>

                    

                </div>

                <div class="dashboard-module__body--right">
                    <div id="submit-with-link">
                        <form>
                            <h5>Submit URLs/hashes</h5>
                            <textarea rows="6" class="form-control" placeholder="Submit URLs/hashes"></textarea>
                            <div class="text-center">
                                <button type="submit" class="button--lg">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

            <div class="dashboard-module__footer">
                <p class="align-left"><i class="fa fa-info-circle"></i> Drag your file into the left field or click the icon to select a file.</p>
            </div>

        </div>

        <div class="dashboard-module" data-dashboard-module="system">
            <header class="dashboard-module__header">
                <h4 class="align-left clearfix">
                    System info
                    <div class="pull-right">
                        <span class="label label-free">free</span>
                        <span class="label label-used">used</span>
                        <span class="label label-total">total</span>
                    </div>
                </h4>
            </header>
            <section class="dashboard-module__body free-disk-space">

                <div class="dashboard-module__body--flex">
                    <h5>Free disk space</h5>
                    <div class="free-disk-space__chart" id="ds-stat">
                        <canvas></canvas>
                        <div class="free-disk-space__legend">
                            <p><strong data-populate="free-disk-space"></strong></p>
                            <p data-populate="total-disk-space"></p>
                        </div>
                    </div>
                </div>

                <div class="dashboard-module__body--flex">
                    <h5>CPU Load</h5>
                    <div class="free-disk-space__chart" id="cpu-stat">
                        <canvas></canvas>
                        <div class="free-disk-space__legend">
                            <p><strong data-populate="cpu-load"></strong></p>
                            <p data-populate="total-cores"></p>
                        </div>
                    </div>
                </div>

                <div class="dashboard-module__body--flex">
                    <h5>Memory usage</h5>
                    <div class="free-disk-space__chart" id="memory-stat">
                        <canvas></canvas>
                        <div class="free-disk-space__legend">
                            <p><strong data-populate="memory-used"></strong></p>
                            <p data-populate="memory-total"></p>
                        </div>
                    </div>
                </div>

            </section>
            
        </div>

    </div>

</div>

<div class="flex-grid__horizontal--grow dashboard bottom">

    <div class="flex-grid__column" id="dashboard-tables">

        <h2 class="dashboard__col-title">Recent analyses</h2>

        
        <div class="dashboard-module__lg" data-dashboard-module="processes">
            <header class="dashboard-module__header">

                <div class="flex-tabs__tabs dashboard-module__tabs">

                    

                    <div class="flex-tabs__tab--right">
                        <div class="custom-select" data-custom="select">
                            <span>Show: </span>
                            <select data-select="limit">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3" selected="selected">3</option>
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="50">50</option>
                            </select>
                        </div>
                    </div>

                </div>

            </header>
            <section class="dashboard-module__body">
                <div class="dashboard-module__body--left" data-populate="dashboard-table-recent">
                </div>

                
            </section>

            <footer class="dashboard-module__footer">
                <p><a href="/analysis/">Show all recent analyses</a></p>
            </footer>

        </div>

    </div>

</div>


	
</div>

    
    <footer>
        <div class="container-fluid center">
            <a href="#">Back to the top</a>
        </div>
    </footer>
    <div id="footer-extra">
        <div class="container-fluid center">
            <div>&copy;2010-2017 <a href="http://www.cuckoosandbox.org" target="_blank">Cuckoo Sandbox</a></div>
        </div>
    </div>

    
    

<script src="/static/js/cuckoo/analysis_export.js"></script>
<script src="/static/js/cuckoo/analysis_feedback.js"></script>

<style>
    .modal p{
        font-size: 14px;
    }
</style>


<div id="modal_feedback" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="panel-title" id="contactLabel"><span style="color:white" class="glyphicon glyphicon-info-sign"></span> Feedback Form</h4>
            </div>

            <div class="modal-body" style="padding: 18px;">
                <p>
                    Expecting different results? Share this analysis report with us and we will investigate it.
                    Please include a brief message of what you had expected to see and what you got instead.

                    <br><br><small><b>The Cuckoo Sandbox team</b></small>
                </p>

                <hr>

                <form method="post">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                            <input class="form-control" id="name" name="name" placeholder="Your name" type="text" value="" required autofocus />
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                            <input class="form-control" id="company" name="company" placeholder="Company" type="text" value="" required />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12" style="padding-bottom: 10px;">
                            <input class="form-control" id="email" name="email" placeholder="E-mail" type="text" value="" required />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <textarea style="resize:vertical;" id="message" class="form-control" placeholder="Message..." rows="6" name="comment" required></textarea>
                        </div>
                    </div>

                    <div class="row">
                        <div class="cuckoo-box" style="padding: 16px; padding-top: 10px; padding-bottom: 0px;">
                            <div class="cuckoo-box-primary">
                                <input type="checkbox" id="analysis" name="analysis" value="analysis">
                                <label for="analysis">Include analysis</label>
                            </div>
                            <div class="cuckoo-box-primary">
                                <input type="checkbox" id="memory" name="memory" value="memory">
                                <label for="memory">Include memory dump</label>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <br>
                        <small id="export_estimate_size" style="margin-left: 10px;color: #adadad;"></small>
                    </div>

                </form>
            </div>

            <div class="panel-footer clearfix">
                <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
                <input id="submit" disabled type="submit" class="btn btn-success" value="Send"/>
                <span id="result"></span>
            </div>
        </div>
    </div>
</div>


    
    <div class="page-freeze" id="page-freeze-container">
        <div class="page-freeze__graphic">
            <img src="/static/graphic/cuckoo-coffee-cup.png" alt="Cuckoo" />
        </div>
        <div class="page-freeze__animation">
            
            <div class="page-freeze__spinner">
                <div class="page-freeze__spinner--c1"></div>
                <div class="page-freeze__spinner--c2"></div>
            </div>
        </div>
        <div class="page-freeze__context">
            <p class="page-freeze__message">We're processing your submission... This could take a few seconds.</p>
            <div class="page-freeze__options hidden">
                <button class="btn btn-default btn-lg close-page-freeze">Close</button>
            </div>
        </div>
    </div>

    
     <script>

        // unless set elsewhere, define task_id as an empty variable of type String
        if(!task_id)
            var task_id = false;

        var taken_files = [];
        var taken_dirs = [];
        var cb_analysis = true;

        $(document).ready(function() {

            var sel = $('#modal_feedback');

            sel.on("shown.bs.modal", function() {
                $("input:text:visible:first").focus()
            });

            function send_feedback_callback(data){
                if(data['status'] == true){
                    sel.find("span#result").html("Successfully sent feedback");

                    setTimeout(function(){
                        location.reload();
                    }, 1000);
                } else {
                    sel.find("span#result").html("error: " + data["message"]);
                }
                feedbackFormSubmitted = false;
                send_button_toggle();
            }

            function send_feedback(){

                send_button_toggle();

                var email = sel.find("input#email").val();
                var company = sel.find("input#company").val();
                var message = sel.find("textarea#message").val();
                var name = sel.find("input#name").val();

                var include_analysis = sel.find("input#analysis").is(":checked");
                var include_memory = false;

                if(include_analysis){
                    if(sel.find("input#memory").is(":checked")) include_memory = true;
                }

                feedback_send(task_id, name, email, company, message, include_analysis, include_memory, send_feedback_callback)
            }

            function initFeedbackForm(data){

                if(!data) {
                    var data = {
                        files: [],
                        dirs: []
                    }
                }

                taken_files = data['files'];

                function estimate_size(){
                    var dirs = [];
                    var files = [];

                    if(sel.find("input#analysis").is(":checked")){
                        dirs = taken_dirs;
                        files = taken_files;
                    }

                    var memory = sel.find("input#memory").is(":checked");

                    export_estimate_size(task_id, dirs, files, "#modal_feedback small#export_estimate_size", "Estimated size: ");
                }

                sel.find("input#analysis").change("click", function() {

                    if(!this.checked){
                        cb_analysis = false;

                        var memory = sel.find("input#memory");
                        if(memory.is(":checked")) $(memory).removeAttr("checked");
                    } else {
                        cb_analysis = true;
                    }

                    estimate_size();
                });

                sel.find("input#memory").on("click", function(e) {
                    if(!cb_analysis) {
                        e.preventDefault();
                        e.stopPropagation();

                        return;
                    }

                    if(this.checked) {
                        taken_dirs.push("memory");
                    } else {
                        taken_dirs.pop();
                    }

                    estimate_size();
                });

                // Dont include the memory dump by default
                data["dirs"].forEach(function(obj, i){
                    if(obj[0] != "memory") taken_dirs.push(obj[0]);
                });

                sel.find("input#submit").prop("disabled", false);

                sel.find("input#submit").click(function(){
                    if(feedbackFormSubmitted) return false;
                    feedbackFormSubmitted = true;
                    send_feedback();
                });

                if(task_id) {
                    sel.find('input#analysis').prop('checked','checked');
                }

                estimate_size();
            }

            if(task_id) {
                export_get_files(task_id, initFeedbackForm);
            } else {
                initFeedbackForm();
            }
        });
    </script>

    
    <script>
        $(document).ready(function() {
            hljs.initHighlightingOnLoad();
        });
    </script>

    
    <script>

        $(document).ready(function() {

            // only do this if we are on the recent page
            if(!$('table#recent').length) return;

            var recent;

            $('body').on('click', 'div.nav_container>div', function() {

                var btn_id = $(this).find("a").attr("data-filter");
                var btn_active = $(this).attr('class');
                var btn_categories = ["cat_files", "cat_urls"];

                if($('a[data-filter^="score"]', this).length) {
                    var score_choice = $(this).find('a').attr('data-filter');

                    $('.nav_container>div#item>a[data-filter^="score"]').each(function(i, obj){
                        obj = $(obj);
                        var uid = obj.attr('data-filter');

                        if(uid != score_choice){
                            obj.parent().removeClass('active');
                        }
                    });
                }

                if(!btn_active){
                    // when a category button is clicked, force deselection of adjacent categories
                    if(btn_id.startsWith("cat_")){
                        btn_categories.forEach(function (category) {
                            if (category != btn_id) {
                                category = $('.nav_container>div#item>a[data-filter="' + category + '"]').parent();

                                if (category.hasClass("active")) { category.removeClass("active"); }
                            }
                        });
                    }

                    $(this).addClass('active');
                    var filter = $(this).attr('data-filter');
                    recent.load();
                } else {
                    $(this).removeClass('active');
                    recent.load();
                }
            });

            recent = new Recent();
            recent.load();

            // Detect end of page scroll
            $(window).scroll(function() {
               if($(window).scrollTop() + $(window).height() == $(document).height()) {
                    if(!recent.empty_results) recent.lazy_load();
               }
            });

        });
    </script>

    
    <script type='text/javascript'>

        if(document.getElementById('analysis/import') !== null) {

            $(document)
                .on('change', '.btn-file :file', function() {
                    var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                    input.trigger('fileselect', [numFiles, label]);
            });

            $(document).ready( function() {
                $('.btn-file :file').on('fileselect', function(event, numFiles, label) {

                    var input = $(this).parents('.input-group').find(':text'),
                        log = numFiles > 1 ? numFiles + ' files selected' : label;

                    if( input.length ) {
                        input.val(log);
                    } else {
                        if( log ) alert(log);
                    }

                });
            });

        }

    </script>

    
    <script>

        $(document).ready(function(){

            $("#btn_screenshots_toggle").click(function(){
                $(this).parent().parent().parent().find('.panel-body').toggleClass("minified");
            });

            if($("table#network-hosts, table#network-dns").length) {

                setTimeout(function () {
                    ["network_hosts", "network_dns"].forEach(function (x) {
                        $('#' + x).DataTable({
                            responsive: true,
                            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                            "pageLength": 10,
                            "language": {
                                "lengthMenu": "Show _MENU_ results",
                                "zeroRecords": "No results",
                                "info": "_PAGE_/_PAGES_"
                            }
                        });
                    });
                }, 200);

            }

        });

    </script>

</body>
</html>

**Comment by doomedraven** [comment]
lol, .1 is iface address, not the vm

**Comment by yesb0919** [comment]
ooooh  my mistake 
I tried address 10.0.2.15, but it doesnt work either :(

**Comment by yesb0919** [comment]
okay!!! i tried it and conntact u later

**Comment by jbremer** [comment]
Looks like this issue can be closed - doing so. Let us know if you have more feedback.
