### ISSUE TITLE
Behaviour log file is too big

### ISSUE THREAD

**Issue by k142094** [cuckoosandbox/cuckoo#2223]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html
My issue is:
2018-04-10 08:46:10,740 [cuckoo.processing.behavior] CRITICAL: Behavior log file '3144.bson' is too big, skipped.

My Cuckoo version and operating system are:
OS: Ubuntu 16.04.1
Cuckoo Version: 2.0.5
VirtualBox: 5.1.34
VM: Windows7x86Sp1

This can be reproduced by:
trying to analyze the jigsaw sample on high priority and for 300 seconds

**Comment by RicoVZ** [comment]
Hi k142094,

Your issue can be resolved by increasing the maximum file processing size limit.
This can be done by increasing the value of `analysis_size_limit` under `[processing]` in your `cuckoo.conf` file.

**Comment by jbremer** [comment]
Assuming this fixes your issue (it should), @k142094, closing the issue. Thanks @RicoVZ.
Feel free to let us know if you have more feedback.
