### ISSUE TITLE
Proper startup script

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2224]
##### My issue is:
No issue...would just like to know how folks are starting up their instances

##### My Cuckoo version and operating system are:
2.0.5, Debian Stretch

Pretty much the topic.  I have cuckoo setup in a virtual environment as the user cuckoo.  My current process:
~~~
already logged in as myself
screen -S cuckoo2
sudo su cuckoo
cd /home/cuckoo
. cuckoo2-venv/bin/activate
sleep 1
export LIBVIRT_DEFAULT_URI="qemu:///system"
sleep 1
cd cuckoo2-venv
cuckoo rooter --sudo &
sleep 8
cuckoo web -H <ip> -p <port> &
sleep 3
cuckoo &
ctrl-a ctrl-d
~~~

This works, but these, are all manually typed in (ok after cd home/cuckoo copy/pasted).  Some challenges I faced are:
1.  su'd to a different user screen didn't work so had to start screen as myself first
2.  not using screen caused cuckoo to not take samples after a couple runs (red x on submission)
3.  activating a virtual environment via bash script su'd to a different user didn't appear to work

So there you go...I'm all eyes if someone has a better way thank you.

**Comment by doomedraven** [comment]
supervisor

**Comment by DigiAngel** [comment]
potato salad.  What?  :)

**Comment by doomedraven** [comment]
http://supervisord.org/introduction.html

**Comment by DigiAngel** [comment]
Thanks I'll give it a look.

**Comment by DigiAngel** [comment]
Awesome...thank you!

**Comment by doomedraven** [comment]
;)

**Comment by DigiAngel** [comment]
Hrmm...I do not have a supervisord.conf file...is there a way to force creation of it?  Thank you.

**Comment by doomedraven** [comment]
replace X with your user and place it in ~/.cuckoo/supervisord.conf
```
~/.cuckoo using
╰─○ cat supervisord.conf
[supervisord]
logfile = /home/X/.cuckoo/supervisord/log.log
pidfile = /home/X/.cuckoo/supervisord/pidfile
user = tracker

[supervisorctl]
serverurl = unix:///home/X/.cuckoo/supervisord/unix.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file = /home/X/.cuckoo/supervisord/unix.sock

[program:cuckoo-daemon]
command = cuckoo -d -m 10000
user = tracker
startsecs = 30
autorestart = true

[program:cuckoo-process]
command = cuckoo process p%(process_num)d
process_name = cuckoo-process_%(process_num)d
numprocs = 4
user = tracker
autorestart = true

[group:cuckoo]
programs = cuckoo-daemon, cuckoo-process

[program:distributed]
command = python -m cuckoo.distributed.worker
user = tracker
autostart = false
autorestart = true
environment = CUCKOO_APP="worker",CUCKOO_CWD="/home/X/.cuckoo"
```

**Comment by jbremer** [comment]
Closing as resolved, thanks @doomedraven.
