### ISSUE TITLE
Unable to import package "modules.packages.None"

### ISSUE THREAD

**Issue by d4n13l4** [cuckoosandbox/cuckoo#2225]
My issue is: exception caught when running a clean txt file. My cuckoo works but someone tried to run a txt file and got an exception that terminates the analysis.

My Cuckoo version and operating system are: version 2.0.5 ubuntu 16.04

This can be reproduced by: analyzing a clean txt file

The log, error, files etc can be found at:
win7: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpy21k1m/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmpy21k1m/analyzer.py", line 580, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.None", does not exist.

I found several posts related with this but since people had also other problems for this particular exception I didn't get a proper answer from older posts so I'm posting this.

Thanks

**Comment by doomedraven** [comment]
that is normal, cuckoo doesn't know which package to use for it

**Comment by d4n13l4** [comment]
I see
is there a solution for analyzing txt files when using web-gui to submit samples?

**Comment by doomedraven** [comment]
txt files are not executable, so they are not dangerous, if you speak about .txt, and not .js or similar

**Comment by d4n13l4** [comment]
I understand, a colleague was trying to test my cuckoo with a txt file with a "suspicious" link inside and complained it didn't work. 
I had only try real malware on it so I didn't have a good answer as to the error.
Thanks for your help.

if you have a moment could you help me with this [post](https://github.com/cuckoosandbox/cuckoo/issues/2171) I posted a while ago

**Comment by doomedraven** [comment]
if that is .txt it can contain whatever you want but it wasn't executed without trick some policy/extension associations

**Comment by d4n13l4** [comment]
got it 
thanks for the clarification!
