### ISSUE TITLE
def add_config may cause error with “Unable to import package modules.packages.None”

### ISSUE THREAD

**Issue by segulee** [cuckoosandbox/cuckoo#2228]
##### My issue is:
def add_config may cause error with “Unable to import package modules.packages.None”

##### My Cuckoo version and operating system are:
version: Cuckoo Sandbox 2.0.5
os: Ubuntu 14.04 
5 vm_machines, (VirtualBox 5.1)

##### This can be reproduced by:
put any .hwp file through web interface

##### The log, error, files etc can be found at:

To state the conclusion first, in the code below,
```
[guest.py, line in 396] (in my guest.py file)
def add_config(self, options):
        """Upload the analysis.conf for this task to the Virtual Machine."""
        config = [
            "[analysis]",
        ]
        for key, value in options.items():
            # Encode datetime objects the way xmlrpc encodes them.
            if isinstance(value, datetime.datetime):
                config.append("%s = %s" % (key, value.strftime("%Y%m%dT%H:%M:%S")))
            else:
                config.append("%s = %s" % (key, value))
            ...
```
**Because the “value” in the “for” statement CAN BE the null and when it comes to “config.append("%s = %s" % (key, value))” statement, it inserts “None” which is string not None python object.**
It causes 
```
[analyzer.py, line=542] 
if not self.config.package:
        log.debug( "No analysis package specified, trying to detect "
                          "it automagically."
)
…
else:
	package = self.config.package
```
The value of “self.config.package” becomes “None” which is not python object None that we expected. Therefore, package = “None” which causes ERROR with “Unable to import package “modules.packages.None” message.

These are 
http://localhost:8080/submit/api/filetree/” ,
```
{
	"status": true,
	"files": [
		{
			"relaname": null,
			"extrpath": [],
			"password": null,
			"children": [],
			"size": 9216,
			"preview": true,
			"package": null,
			"selected": false,
			"filename": "hwp2014_hwp2014_hwp2014",
			"platform": null,
			"duplicate": false,
			"finger": {
				"mime_human": "hwp",
				"magic": "Hangul (Korean) Word Processor File 5.x",
				"mime": "application/x-hwp",
				"magic_human": "Hangul (Korean) Word Processor File 5.x"
			},
			"relapath": null,
			"type": "file"
		}
	],
	"errors": [],
	"defaults": {
		"priority": 2,
		"package": null,
		"machine": [
                ...
```
MongoDB,
```
> use cuckoo
switched to db cuckoo
> db.analysis.findOne({"info.id":76},{"info.package":true, "target.file.type":true})
{
        "_id" : ObjectId("5acf0e48298ad8cda9cdadbf"),
        "info" : {
                "package" : null
        },
        "target" : {
                "file" : {
                        "type" : "Hangul (Korean) Word Processor File 5.x"
                }
        }
}
```

Schedule DB,
```
cuckoo=> select id, package, target from tasks where id=76;
 id | package |                      target
----+---------+---------------------------------------------------
 76 |         | /tmp/cuckoo-tmp/tmpCr5MGd/hwp2014_hwp2014_hwp2014
(1 row)
```

Due to the statement of “config[“package”] = self.tasks.package” in scheduler.py, the value config[“package”] should be None which is python object, but when it comes to analyzer.conf, while writing config(includeing package field) on analyzer.conf,
```
config.append("%s = %s" % (key, value))
```
Because the “value” in the “for” statement is null and when it comes to “config.append("%s = %s" % (key, value))” statement, **it inserts “None” which is string because of “%s” not None which is python object.
Finally, it causes ERROR with “Unable to import package modules.packages.None” message.**

To solve this problem, I made #2227. Please check this link .

**Comment by RicoVZ** [comment]
Hi segulee,

Thanks for reporting the issue! :smile: 
This was fixed recently in this commit https://github.com/cuckoosandbox/cuckoo/commit/0eabfc467c6cbd317ee19c25a7a09a2a1f0e2395

**Comment by jbremer** [comment]
Thanks indeed. Closing as resolved as per @RicoVZ' comment.
