### ISSUE TITLE
benign samples

### ISSUE THREAD

**Issue by kma94dz** [cuckoosandbox/cuckoo#2230]

**Comment by doomedraven** [comment]
system32?

**Comment by kma94dz** [comment]
Yes im using windows xp 32 bit as virtual machine

**Comment by doomedraven** [comment]
c:\windows\system32 i mean

**Comment by doomedraven** [comment]
a lot of them there

**Comment by kma94dz** [comment]
mmmm yeah thanks, i think i will use them

**Comment by jbremer** [comment]
Cool, closing as resolved.
