### ISSUE TITLE
Installing Cuckoo using pip 

### ISSUE THREAD

**Issue by ishaansharma** [cuckoosandbox/cuckoo#2231]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:

Collecting cuckoo
  Downloading https://files.pythonhosted.org/packages/bb/a9/c8b6f47dc5aeb7aa0efdeb67fdac0091f3ebbc9dbe3a551fc19d56438556/Cuckoo-2.0.5.3.tar.gz (3.4MB)
    100% |████████████████████████████████| 3.4MB 358kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j2/djqnj6sx2sbfp9bqwsgwzb3r0000gn/T/pip-install-m1ul_ji7/cuckoo/setup.py", line 107
        print "  This particular error may be resolved as follows:"
                                                                  ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "  This particular error may be resolved as follows:")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j2/djqnj6sx2sbfp9bqwsgwzb3r0000gn/T/pip-install-m1ul_ji7/cuckoo/

**Comment by doomedraven** [comment]
cuckoo is py2 not py3, so you should `sudo pip2 install cuckoo`

**Comment by ishaansharma** [comment]
Thank You @doomedraven
