### ISSUE TITLE
Run a Custom Volatility Plugin on a Memdump

### ISSUE THREAD

**Issue by Res260** [cuckoosandbox/cuckoo#2235]
##### My issue is:
I want to run a custom volatility plugin (developped in-house) when analyzing a sample, is there a way to do that? I looked in the documentation but couldn't find anything interesting.

##### My Cuckoo version and operating system are:
Cuckoo: Latest
OS: Ubuntu 16.04 64bit

**Comment by doomedraven** [comment]
add it to vol plugin folder and add it to memory.conf

**Comment by Res260** [comment]
Will try that, thank you!

**Comment by Res260** [comment]
Should I see the output of my plugin in the "Vm Memory Dump" section of the report?

**Comment by doomedraven** [comment]
for that i think you need to extend html template

**Comment by Res260** [comment]
Oh, and where can I find documentation for that?

**Comment by doomedraven** [comment]
documentation is refered in readme + https://www.adlice.com/cuckoo-sandbox-customization-v2/

**Comment by Res260** [comment]
Many thanks, will check for this!
