### ISSUE TITLE
Cuckoo not launching - Option windows7 is not in configuration

### ISSUE THREAD

**Issue by lionrushton** [cuckoosandbox/cuckoo#2236]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Upon launching Cuckoo i receive the following error code:

 /_____/\ /_/\/_/\ /_____/\ /___/\/__/\ /_____/\ /_____/\
  \:::__\/ \:\ \:\ \\:::__\/ \::.\ \\ \ \\:::_ \ \\:::_ \ \
   \:\ \  __\:\ \:\ \\:\ \  __\:: \/_) \ \\:\ \ \ \\:\ \ \ \
    \:\ \/_/\\:\ \:\ \\:\ \/_/\\:. __  ( ( \:\ \ \ \\:\ \ \ \
     \:\_\ \ \\:\_\:\ \\:\_\ \ \\: \ )  \ \ \:\_\ \ \\:\_\ \ \
      \_____\/ \_____\/ \_____\/ \__\/\__\/  \_____\/ \_____\/

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!

 Our latest blogposts:
 * Cuckoo Sandbox 2.0.5: Office DDE, December 03, 2017.
   Brand new release based on a DDE case study.
   More at https://cuckoosandbox.org/blog/205-office-dde

 * Cuckoo Sandbox 2.0.4, September 06, 2017.
   Introducing Malware Configuration Extraction.
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-204

 * Cuckoo Sandbox 2.0.0, March 30, 2017.
   First Cuckoo package release!
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-v2

2018-04-17 09:49:35,119 [cuckoo] WARNING: It appears that you haven't loaded any Cuckoo Signatures. Signatures are highly recommended and improve & enrich the information extracted during an analysis. They also make up for the analysis score that you see in the Web Interface - so, pretty important!
2018-04-17 09:49:35,119 [cuckoo] WARNING: You'll be able to fetch all the latest Cuckoo Signaturs, Yara rules, and more goodies by running the following command:
2018-04-17 09:49:35,119 [cuckoo] INFO: $ cuckoo community
2018-04-17 09:49:35,122 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-04-17 09:49:35,219 [cuckoo] CRITICAL: CuckooConfigurationError: Option windows7 is not found in configuration

My Cuckoo version and operating system are:
Cuckoo 2.0.5 running on Ubuntu 16.04

This can be reproduced by:
running command 'cuckoo' or 'sudo cuckoo', virtual machine created in virtualbox called 'windows7' initially, the virtualbox.conf file was filled out to contain windows7 but then i swapped those to cuckoo1 and updated the VM name to be cuckoo1 also.

##### The log, error, files etc can be found at:

My virtualbox.conf file is as follows:

cuckoo@ubuntu:~$ cat /usr/local/lib/python2.7/dist-packages/cuckoo/private/cwd/conf/virtualbox.conf
[virtualbox]
Specify which VirtualBox mode you want to run your machines on.
Can be "gui" or "headless". Please refer to VirtualBox's official
documentation to understand the differences.
mode = {{ virtualbox.virtualbox.mode }}

Path to the local installation of the VBoxManage utility.
path = {{ virtualbox.virtualbox.path }}
If you are running Cuckoo on Mac OS X you have to change the path as follows:
path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

Default network interface.
interface = vboxnet0

Specify a comma-separated list of available machines to be used. For each
specified ID you have to define a dedicated section containing the details
on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines =  cuckoo1

{% for machine in config("virtualbox:virtualbox:machines") %}
[{{ machine }}]
Specify the label name of the current machine as specified in your
VirtualBox configuration.
label = cuckoo1

Specify the operating system platform used by current machine
[windows/darwin/linux].
platform = windows

Specify the IP address of the current virtual machine. Make sure that the
IP address is valid and that the host machine is able to reach it. If not,
the analysis will fail.
ip = 192.168.56.2

(Optional) Specify the snapshot name to use. If you do not specify a snapshot
name, the VirtualBox MachineManager will use the current snapshot.
Example (Snapshot1 is the snapshot name):
snapshot = snapshot1

(Optional) Specify the name of the network interface that should be used
when dumping network traffic from this machine with tcpdump. If specified,
overrides the default interface specified in auxiliary.conf
 Example (vboxnet0 is the interface name):
interface = {{ virtualbox[machine].interface }}

 (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
 The Result Server will always bind to the address and port specified in cuckoo.conf,
 however you could set up your virtual network to use NAT/PAT, so you can specify here
 the IP address for the Result Server as your machine sees it. If you don't specify an
 address here, the machine will use the default value from cuckoo.conf.
 NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
 Example:
resultserver_ip = {{ virtualbox[machine].resultserver_ip }}

 (Optional) Specify the port for the Result Server, as your virtual machine sees it.
 The Result Server will always bind to the address and port specified in cuckoo.conf,
 however you could set up your virtual network to use NAT/PAT, so you can specify here
 the port for the Result Server as your machine sees it. If you don't specify a port
 here, the machine will use the default value from cuckoo.conf.
 Example:
resultserver_port = {{ virtualbox[machine].resultserver_port }}

 (Optional) Set your own tags. These are comma separated and help to identify
 specific VMs. You can run samples on VMs with tag you require.
tags = {{ virtualbox[machine].tags }}

 Mostly unused for now. Please don't fill it out.
options = {{ virtualbox[machine].options }}

 (Optional) Specify the OS profile to be used by volatility for this
 virtual machine. This will override the guest_profile variable in
 memory.conf which solves the problem of having multiple types of VMs
 and properly determining which profile to use.
osprofile = {{ virtualbox[machine].osprofile }}
{% endfor %}

[honeyd]
 For more information on this VM please refer to the "services" section of
 the conf/auxiliary.conf configuration file. This machine is a bit special
 in the way that its used as an additional VM for an analysis.
 *NOTE* that if this functionality is used, the VM should be registered in
 the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
 The tags should at least contain "service" and the name of this service.
 This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
 Not all services actually have a Cuckoo Agent running in the VM, for those
 services one can specify the "noagent" option so Cuckoo will just wait until
 the end of the analysis instead of trying to connect to the non-existing
 Cuckoo Agent. We can't really intercept any inter-VM communication from the
 host / gateway so in order to dump traffic between VMs we have to use a
 different network dumping approach. For this machine we use the "nictrace"
 functionality from VirtualBox (which is basically their internal tcpdump)
 and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by doomedraven** [comment]
omg read documentation plz, the conf is in $CWD/.cuckoo like $HOME/.cuckoo not in `/usr/local/lib/python2.7/dist-packages/cuckoo/private/cwd/conf/virtualbox.conf`

**Comment by lionrushton** [comment]
Sincerest apologies, thank you very much for pointing this out! Couldnt find directory but didnt notice it was a hidden one.... THank you !

**Comment by jbremer** [comment]
Please configure the VMs correctly in the file(s) mentioned by @doomedraven. Closing as resolved.
Let us know if you have more feedback.

**Comment by pareshjsr** [comment]
Hi I am getting similar error when I run cuckoo -d command. I tried with cuckoo1 as the machine name but still the same issue. I am running Windows 7 on virtualbox within Ubuntu. Please assist.
Cuckooconfigurationerror: OPtion Windows 7 is not in configuration

**Comment by nadianrzhm** [comment]
getting the same error as @lionrushton . and still haven't get the solution. please help with more details?

**Comment by doomedraven** [comment]
did you read the documentation? + post configs but use markdown code block escape 

\`\`\`
 config goes here
\`\`\`

**Comment by nadianrzhm** [comment]
yes, of course i read the documentation

which conf i should show you?

**Comment by doomedraven** [comment]
which hypervisor do you use? virtualbox? vmware? kvm? that conf, but please use code escape as i showed before

**Comment by nadianrzhm** [comment]
virtual box

```
[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui" or "headless". Please refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = Local Area Connection 2

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1

# If remote control is enabled in cuckoo.conf, specify a port range to use.
# Virtualbox will bind the VRDP interface to the first available port.
controlports = 5000-5050


[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = cuckoo1

# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.0.13

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = Snapshot2

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface =

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 192.168.0.10

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface =

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 192.168.0.10

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port =

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags =

# Mostly unused for now. Please don't fill it out.
options =

# (Optional) Specify the OS profile to be used by volatility for this
# virtual machine. This will override the guest_profile variable in
# memory.conf which solves the problem of having multiple types of VMs
# and properly determining which profile to use.
osprofile =


[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.0.18
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent


```

**Comment by doomedraven** [comment]
You have uncommented a lot of stuff like resultservers pirts etc, that
breaks your setup

**Comment by doomedraven** [comment]
this is epic dude

```
# Default network interface.
interface = Local Area Connection 2
```

it should be virtnet0 or something like that, check ifconfig

**Comment by nadianrzhm** [comment]
my interface is enp0s8. ive commented unnecessary configuration.
it still pending and when i run cuckoo, still the same output as above. 

p/s: yeahhh i'm still have to learn a lot. this is my school project and i still can't figure out my problem. maybe still dumb

```
[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui" or "headless". Please refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = enp0s8

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1

# If remote control is enabled in cuckoo.conf, specify a port range to use.
# Virtualbox will bind the VRDP interface to the first available port.
controlports = 5000-5050


[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = cuckoo1

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 192.168.0.13

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = Snapshot2

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = Snapshot2

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
#interface = 

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 192.168.0.10

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
#resultserver_port = 

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
#tags = 

# Mostly unused for now. Please don't fill it out.
#options = 

# (Optional) Specify the OS profile to be used by volatility for this
# virtual machine. This will override the guest_profile variable in
# memory.conf which solves the problem of having multiple types of VMs
# and properly determining which profile to use.
#osprofile = 


[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.0.18
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent


```

**Comment by doomedraven** [comment]
nah that `enp0s8 ` isn't vbox network interface
resultserver_ip = 192.168.0.10 <- im pretty sure that is wrong, if you use brindge is ok, but if nat or hostonly is bad, comment that out and set that in `cuckoo.conf` as it should be set there

also is your vm name is cuckoo1? if no label=X where X is vm name

i would suggest to play with netowrking and learn how that works before start creating more stuff on that, but go again to the documentation and reread it

duplicated fields why?

```
# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = Snapshot2

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = Snapshot2

```

**Comment by nadianrzhm** [comment]
im confuse, which one is vm name?

**Comment by doomedraven** [comment]
Label
