### ISSUE TITLE
Cuckoo exporting informations as pdf

### ISSUE THREAD

**Issue by Nihsa** [cuckoosandbox/cuckoo#2238]
Hello,

When cuckoo exporting the informations as pdf, i have only the summary informations in the pdf like the file informations, screenshots, rules that matched, and some other informations but i don't have ALL the informations. What can i do to include all the informations like the static analysis, network analysis, virus total, etc... in the pdf ? 

Thank you. :)

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/reporting/singlefile.py

**Comment by Nihsa** [comment]
Are you sure that i have to modify singlefile.py and not https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/reporting/reportpdf.py ?

**Comment by doomedraven** [comment]
you are in wrong repository

**Comment by jbremer** [comment]
Please take a look at the Jinja2 template, that should give you enough information to add something to the report. https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/private/html/report.html
Closing as resolved, feel free to reopen if you have more concrete feedback.
