### ISSUE TITLE
Cuckoo1 problem and Running MongoBD in Cuckoo

### ISSUE THREAD

**Issue by alyazia123** [cuckoosandbox/cuckoo#2239]
How can I fix this problem ? 

<img width="712" alt="screen shot 2018-04-20 at 8 27 28 pm" src="https://user-images.githubusercontent.com/38566928/39063271-965922a2-44db-11e8-959f-055aa7272c89.png">
2018-04-20 19:49:53,014 [cuckoo.core.scheduler] INFO: Using "virtual box" as machine manager 
2018-04-20 19:49:54,014 [cuckoo.machinery.virtualbox] DEBUG: Stopping vm cuck oo1 
2018-04-20 19:49:54,075 [cuckoo] CRITICAL: CuckooCriticalError: Please update proper state: The virtual machine 'cuckoo1' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the cuckoo configuration!
(venv) root@alyazia-VirtualBox:~# apt-get install mongodb
Reading package lists... Done
Building dependency tree
Reading state information... Done
mongodb is already the newest version (1:3.4.7-1).
0 upgrade, 0 newly installed, 0 to remove and 157 not upgraded.

**Comment by doomedraven** [comment]
read your error and follow the documentation

**Comment by doomedraven** [comment]
it says cuckoo1 doesnt exists, so your vbox conf is wrong than

**Comment by RicoVZ** [comment]
Hi alyazia123,

I see two issues here. First the missing guest vm:
Have you created a vm and added it to `virtualbox.conf`? It says the vm `cuckoo1` is not found, is yours actually called that?

You can see all available vms when you run `vboxmanage list vms`.

Your other issue: web is not starting.
As the error says: MongoDB should be running, and configured to be used in your `reporting.conf` file.
All configuration files can be found at `$YOURCWD/conf`.

Also see https://cuckoo.sh/docs/usage/web.html

In your `reporting.conf`, there is a section `[mongodb]`, which has some configuration falling under it.
Set `enabled = no` to `enabled = yes`, and configure the host ip and port to the ones matching your MongoDB instance (the default values are correct if nothing was changed about your MongoDB).

After this, the web interface can be used.

**Comment by jbremer** [comment]
Closing issue for lack of response, feel free to reopen if you have new information for us.
