### ISSUE TITLE
cuckoo analyses takes a lot of time

### ISSUE THREAD

**Issue by kma94dz** [cuckoosandbox/cuckoo#2240]
##### My issue is: cuckoo analyses takes a lot of time than usual in Finding appropriate address space for tables... , i had to make analyses on another PC (INTEL pentium cpu, 4 GB of RAM) and its faster even if this one is more powerful(AMD A4 cpu, 8 GB of RAM)
is it have something to do with Intel and AMD????

**Comment by doomedraven** [comment]
it has to see with the size of memdump

**Comment by kma94dz** [comment]
can i reduce it or its OK ( it goes for 7 minutes of analyzing time)

**Comment by jbremer** [comment]
This can be closed I assume. Please reopen if that's not the case.
