### ISSUE TITLE
CuckooCriticalError

### ISSUE THREAD

**Issue by arabin-android** [cuckoosandbox/cuckoo#2244]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
 CuckooCriticalError: VirtualBox' VBoxManage not found at specified path "/usr/bin/VBoxManage" (as specified in virtualbox.conf). Did you properly install VirtualBox and configure Cuckoo to use it? Where i have changed the virtual.conf like 

path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

but i am getting the same cuckoocriticalerror

##### My Cuckoo version and operating system are:

Cuckoo version is 2.0.5
OS macOs 10.13.4

**Comment by RicoVZ** [comment]
Hi arabin-android,

Could you post your `virtualbox.conf` here please? Preferably a link to a paste (pastebin) of it.

**Comment by doomedraven** [comment]
you are using incorrect config file, yo should use `$CWD/conf/virtualbox.conf`

**Comment by arabin-android** [comment]
but this is the virtualbox.conf file. could you please suggest me how to find the $CWD/conf/virtualbox.conf file in macbook

**Comment by doomedraven** [comment]
that is vbox, but that is template file, not real config, if you installed without `--cwd`, then it is in `$HOME/.cuckoo/conf/virtualbox.conf`

**Comment by arabin-android** [comment]
i have installed cuckoo without --cwd, but could not find $HOME/.cuckoo/conf/virtualbox.conf file. if you dont mind could you please guide me in case of installing and editing virtualbox.conf file

**Comment by doomedraven** [comment]
+ read the documentation!

**Comment by RicoVZ** [comment]
Hi arabin-android,

Did you find the virtualbox.conf file?
If you use the latest Cuckoo version and install it as @doomedraven stated, and you
have started it without `--cwd`, then the default cwd will be `.cuckoo` in your user home.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
