### ISSUE TITLE
Error: Analysis failed: The package "modules.packages.ie" start function raised an error: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by MirrorFeng** [cuckoosandbox/cuckoo#2246]
My issue is:Error: Analysis failed: The package "modules.packages.ie" start function raised an error: Unable to execute the initial process, analysis aborted.

 My Cuckoo version and operating system are:2.0.1 and Ubuntu16.04，my client Machine is win7

hi， I encountered the same problem as you：

**_Error: Analysis failed: The package "modules.packages.ie" start function raised an error: Unable to execute the initial process, analysis aborted._**

and in analysis.log:

**_2018-04-25 08:35:13,280 [lib.api.process] ERROR: Failed to execute process from path 'C:\Program Files\Internet Explorer\iexplore.exe' with arguments ['bin\inject-x64.exe', '--app', u'C:\PROGRA1\INTERN1\iexplore.exe', '--args', 'www.jd.com', '--apc', '--dll', 'C:\wjxsjj\bin\monitor-x64.dll', '--config', 'c:\users\mirror\appdata\local\temp\tmpn9qul2', '--curdir', u'C:\Users\mirror\AppData\Local\Temp', '--maximize'] (Error: The pipe has been ended (ERROR_BROKEN_PIPE))_**

I have already run：python community.py -wafb monitor however, this problem still exists！Can you help me solve this problem?

**Comment by jbremer** [comment]
Please upgrade your Cuckoo version :)

**Comment by jbremer** [comment]
Closing as resolved / lack of answer.
