### ISSUE TITLE
Analysis Exception: The system cannot find the file specified

### ISSUE THREAD

**Issue by doria90** [cuckoosandbox/cuckoo#2248]
Hi guys,
I've installed cuckoo on Windows 10 following some guides online, using VMWare Workstation as my virtualization provider.
Everything worked fine until for some reason, I've started to receive errors on my analyses.. I think the file I submit isn't being uploaded to the guest machine somehow.

The guest machine is a Windows 10 with the Administrator account active. I've placed the agent.pyw under **shell:startup**. Defender,Firewall, Windows updates, OneDrive - are all disabled

This is the cuckoo log:
`
2018-04-25 14:52:33,667 [cuckoo.core.scheduler] INFO: Task #82: acquired machine win10_x64 (label=C:\virtualMachines\win10_x64\win10_x64.vmx)`
`
2018-04-25 14:52:33,691 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 1476 (interface=\Device\NPF_{2CE62467-4C18-4AE7-BC72-5E4A120934B9}, host=192.168.56.23)`
`2018-04-25 14:52:33,693 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer`
`2018-04-25 14:52:34,095 [cuckoo.machinery.vmware] DEBUG: Revert snapshot for vm C:\virtualMachines\win10_x64\win10_x64.vmx`
`2018-04-25 14:52:37,851 [cuckoo.machinery.vmware] DEBUG: Starting vm C:\virtualMachines\win10_x64\win10_x64.vmx`
`2018-04-25 14:52:49,815 [cuckoo.core.guest] INFO: Starting analysis on guest (id=win10_x64, ip=192.168.56.23)
2018-04-25 14:52:50,819 [cuckoo.core.guest] DEBUG: win10_x64: not ready yet
2018-04-25 14:52:50,829 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=win10_x64, ip=192.168.56.23)`
`2018-04-25 14:52:50,867 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=win10_x64, ip=192.168.56.23, monitor=latest, size=3814549)
2018-04-25 14:52:53,265 [cuckoo.core.guest] DEBUG: win10_x64: analysis still processing
2018-04-25 14:52:54,029 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2018-04-25 14:52:54,270 [cuckoo.core.guest] DEBUG: win10_x64: analysis still processing`

`2018-04-25 14:52:55,275 [cuckoo.core.guest] WARNING: win10_x64: analysis caught an exception`

`Traceback (most recent call last):
  File "C:/tmpfkzipi/analyzer.py", line 798, in <module> success = analyzer.run()
  File "C:/tmpfkzipi/analyzer.py", line 650, in pids = self.package.start(self.target)
  File "C:\tmpfkzipi\modules\packages\xls.py", line 62, in excel, args=[path], mode="office", trigger="file:%s" % path
  File "C:\tmpfkzipi\lib\common\abstracts.py", line 164, in maximize=maximize, env=env, trigger=trigger):
  File "C:\tmpfkzipi\lib\api\process.py", line 275, in execute output = subprocess_checkoutput(argv, env)
  File "C:\tmpfkzipi\lib\api\process.py", line 32, in subprocess_checkoutput
    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
  File "C:\Python27\lib\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)`

WindowsError: [Error 2] The system cannot find the file specified
`

`2018-04-25 14:52:55,289 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2018-04-25 14:52:55,289 [cuckoo.machinery.vmware] DEBUG: Stopping vm C:\virtualMachines\win10_x64\win10_x64.vmx
2018-04-25 14:52:59,125 [cuckoo.core.scheduler] DEBUG: Released database task #82
2018-04-25 14:52:59,157 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #82
2018-04-25 14:52:59,158 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #82
2018-04-25 14:52:59,161 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #82
2018-04-25 14:52:59,181 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #82
2018-04-25 14:52:59,183 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #82
2018-04-25 14:52:59,184 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #82
2018-04-25 14:52:59,186 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #82
2018-04-25 14:52:59,194 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #82
2018-04-25 14:52:59,201 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #82
2018-04-25 14:52:59,217 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #82
2018-04-25 14:53:10,532 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #82
2018-04-25 14:53:10,535 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #82
2018-04-25 14:53:10,536 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #82
2018-04-25 14:53:10,542 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #82
2018-04-25 14:53:10,546 [cuckoo.core.plugins] DEBUG: Running 473 signatures
2018-04-25 14:53:10,673 [cuckoo.core.plugins] DEBUG: Analysis matched signature: network_http
2018-04-25 14:53:10,678 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
`

I'd love your help on this one! As far as I can tell, nothing has suddenly changed, not that I'm aware of at least.. so I'm quite stuck at the moment, trying to figure out what the heck.

**Comment by doria90** [comment]
I've done some more digging, installed a new analysis machine and the problem persists.
I've also tried to submit an analysis using the "cuckoo submit" feature and have received another error. here's the cuckoo log (the analyzer log contains nothing!):

`2018-05-01 13:57:40,555 [cuckoo.core.scheduler] INFO: Task #84: acquired machine win10_x64_2 (label=C:\Users\Votiro\Documents\Virtual Machines\win10_x64_2\win10_x64_2.vmx)`
`2018-05-01 13:57:40,578 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7140 (interface=\Device\NPF_{2CE62467-4C18-4AE7-BC72-5E4A120934B9}, host=192.168.56.142)`
`2018-05-01 13:57:40,579 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer`
`2018-05-01 13:57:40,959 [cuckoo.machinery.vmware] DEBUG: Revert snapshot for vm C:\Users\Votiro\Documents\Virtual Machines\win10_x64_2\win10_x64_2.vmx`
`2018-05-01 13:57:44,661 [cuckoo.machinery.vmware] DEBUG: Starting vm C:\Users\Votiro\Documents\Virtual Machines\win10_x64_2\win10_x64_2.vmx`
`2018-05-01 13:57:52,743 [cuckoo.core.guest] INFO: Starting analysis on guest (id=win10_x64_2, ip=192.168.56.142)`
`2018-05-01 13:57:53,747 [cuckoo.core.guest] DEBUG: win10_x64_2: not ready yet`
`2018-05-01 13:57:53,757 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=win10_x64_2, ip=192.168.56.142)`
`2018-05-01 13:57:53,796 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=win10_x64_2, ip=192.168.56.142, monitor=latest, size=3814549)`
`2018-05-01 13:57:54,043 [cuckoo.core.guest] DEBUG: win10_x64_2: analysis still processing`
`2018-05-01 13:57:54,211 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.`
`2018-05-01 13:57:55,048 [cuckoo.core.guest] WARNING: win10_x64_2: analysis caught an exception`
`Traceback (most recent call last):`
`  File "C:/tmpiwq9ks/analyzer.py", line 798, in <module>`
`    success = analyzer.run()`
`  File "C:/tmpiwq9ks/analyzer.py", line 564, in run`
`    "type: {0}".format(self.config.file_type))`
`CuckooError: No valid package available for file type: `

`2018-05-01 13:57:55,059 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer`
`2018-05-01 13:57:55,061 [cuckoo.machinery.vmware] DEBUG: Stopping vm C:\Users\Votiro\Documents\Virtual Machines\win10_x64_2\win10_x64_2.vmx`
`2018-05-01 13:57:57,499 [cuckoo.core.scheduler] DEBUG: Released database task #84`
`2018-05-01 13:57:57,526 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #84`
`2018-05-01 13:57:57,526 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #84`
`2018-05-01 13:57:57,528 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #84`
`2018-05-01 13:57:57,546 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #84`
`2018-05-01 13:57:57,549 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #84`
`2018-05-01 13:57:57,549 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #84`
`2018-05-01 13:57:57,552 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #84`
`2018-05-01 13:57:57,559 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #84`
`2018-05-01 13:57:57,568 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #84`
`2018-05-01 13:57:57,582 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #84`
`2018-05-01 13:57:57,881 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #84`
`2018-05-01 13:57:57,882 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #84`
`2018-05-01 13:57:57,884 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #84`
`2018-05-01 13:57:57,888 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #84`
`2018-05-01 13:57:57,891 [cuckoo.core.plugins] DEBUG: Running 473 signatures`
`2018-05-01 13:57:58,007 [cuckoo.core.plugins] DEBUG: Analysis matched signature: dead_host`
`2018-05-01 13:57:58,009 [cuckoo.core.plugins] DEBUG: Analysis matched signature: network_http`
`2018-05-01 13:57:58,015 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"`


Has anyone encountered this thing before? I guess something is wrong with the cuckoo installation by now..

Thanks,
Amit.

**Comment by jbremer** [comment]
Right, Windows 10 isn't officially supported by us currently. Please try Windows 7 to start out ;-)

**Comment by doria90** [comment]
Actually It worked great on Windows 10! I don't know what happened as I gave the machine to someone and now it malfunctions as I described.

To your comment, I've got a windows 7 guest machine as well, This is the cuckoo log:
`2018-05-01 14:11:32,015 [cuckoo.core.scheduler] INFO: Task #85: acquired machine win7_x86_2 (label=C:\virtualMachines\Win7_x86_2\Win7_x86.vmx)`
`2018-05-01 14:11:32,039 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 8032 (interface=\Device\NPF_{2CE62467-4C18-4AE7-BC72-5E4A120934B9}, host=192.168.56.22)`
`2018-05-01 14:11:32,039 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer`
`2018-05-01 14:11:32,415 [cuckoo.machinery.vmware] DEBUG: Revert snapshot for vm C:\virtualMachines\Win7_x86_2\Win7_x86.vmx`
`2018-05-01 14:11:35,844 [cuckoo.machinery.vmware] DEBUG: Starting vm C:\virtualMachines\Win7_x86_2\Win7_x86.vmx`
`2018-05-01 14:11:41,948 [cuckoo.core.guest] INFO: Starting analysis on guest (id=win7_x86_2, ip=192.168.56.22)`
`2018-05-01 14:11:42,039 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=win7_x86_2, ip=192.168.56.22)`
`2018-05-01 14:11:42,088 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=win7_x86_2, ip=192.168.56.22, monitor=latest, size=3814549)`
`2018-05-01 14:11:42,568 [cuckoo.core.guest] DEBUG: win7_x86_2: analysis still processing`
`2018-05-01 14:11:42,766 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.`
**`2018-05-01 14:11:43,572 [cuckoo.core.guest] WARNING: win7_x86_2: analysis caught an exception`
`Traceback (most recent call last):`
`  File "C:/tmpqzoqx8/analyzer.py", line 798, in <module>`
`    success = analyzer.run()`
`  File "C:/tmpqzoqx8/analyzer.py", line 650, in run`
`    pids = self.package.start(self.target)`
`  File "C:\tmpqzoqx8\modules\packages\xls.py", line 62, in start`
`    excel, args=[path], mode="office", trigger="file:%s" % path`
`  File "C:\tmpqzoqx8\lib\common\abstracts.py", line 164, in execute`
`    maximize=maximize, env=env, trigger=trigger):`
`  File "C:\tmpqzoqx8\lib\api\process.py", line 275, in execute`
`    output = subprocess_checkoutput(argv, env)`
`  File "C:\tmpqzoqx8\lib\api\process.py", line 32, in subprocess_checkoutput`
`    args, stdin=subprocess.PIPE, stderr=subprocess.PIPE, env=env,`
`  File "C:\Python27\lib\subprocess.py", line 212, in check_output`
`    process = Popen(stdout=PIPE, *popenargs, **kwargs)`
`  File "C:\Python27\lib\subprocess.py", line 390, in __init__`
`    errread, errwrite)`
`  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child`
`    startupinfo)`
`WindowsError: [Error 2] The system cannot find the file specified`**

`2018-05-01 14:11:43,585 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer`
`2018-05-01 14:11:43,586 [cuckoo.machinery.vmware] DEBUG: Stopping vm C:\virtualMachines\Win7_x86_2\Win7_x86.vmx`
`2018-05-01 14:11:46,286 [cuckoo.core.scheduler] DEBUG: Released database task #85`
`2018-05-01 14:11:46,329 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #85`
`2018-05-01 14:11:46,332 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #85`
`2018-05-01 14:11:46,335 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #85`
`2018-05-01 14:11:46,351 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #85`
`2018-05-01 14:11:46,352 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #85`
`2018-05-01 14:11:46,355 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #85`
`2018-05-01 14:11:46,357 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #85`
`2018-05-01 14:11:46,367 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #85`
`2018-05-01 14:11:46,374 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #85`
`2018-05-01 14:11:46,388 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #85`
`2018-05-01 14:11:46,490 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #85`
`2018-05-01 14:11:46,492 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #85`
`2018-05-01 14:11:46,493 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #85`
`2018-05-01 14:11:46,496 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #85`
`2018-05-01 14:11:46,502 [cuckoo.core.plugins] DEBUG: Running 473 signatures`
`2018-05-01 14:11:46,622 [cuckoo.core.plugins] DEBUG: Analysis matched signature: dead_host`
`2018-05-01 14:11:46,624 [cuckoo.core.plugins] DEBUG: Analysis matched signature: network_icmp`
`2018-05-01 14:11:46,628 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"`

And the analyzer log:
`2018-05-01 14:11:32,000 [analyzer] DEBUG: Starting analyzer from: C:\tmpqzoqx8`
`2018-05-01 14:11:32,000 [analyzer] DEBUG: Pipe server name: \??\PIPE\wOFfwujWlgWxxwIkNvsYpMfxLlv`
`2018-05-01 14:11:32,000 [analyzer] DEBUG: Log pipe server name: \??\PIPE\muoEwKdPkOLDmLRjkMbpQMY`
`2018-05-01 14:11:32,171 [analyzer] DEBUG: Started auxiliary module DbgView`
`2018-05-01 14:11:32,404 [analyzer] DEBUG: Started auxiliary module Disguise`
**`2018-05-01 14:11:32,436 [lib.api.process] ERROR: Failed to inject 32-bit process with pid None and process name lsass.exe`**
`2018-05-01 14:11:32,436 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets`
`2018-05-01 14:11:32,436 [analyzer] DEBUG: Started auxiliary module Human`
`2018-05-01 14:11:32,436 [analyzer] DEBUG: Started auxiliary module InstallCertificate`
`2018-05-01 14:11:32,436 [analyzer] DEBUG: Started auxiliary module Reboot`
`2018-05-01 14:11:32,483 [analyzer] DEBUG: Started auxiliary module RecentFiles`
`2018-05-01 14:11:32,483 [analyzer] DEBUG: Started auxiliary module Screenshots`
`2018-05-01 14:11:32,483 [analyzer] DEBUG: Started auxiliary module LoadZer0m0n`

As I said, something must have gone wrong with the machine. I'm curious if anyone has seen something like this..
This is a weird case as Cuckoo and it's modules are all functioning, calling the guest machine (reverting / shutting down etc.) but fails to analyze file (and it worked before).

:\

**Comment by doria90** [comment]
it's called tryMe.xlsm.
The error persists on TXT(TODO.txt) files as well - cuckoo log (analyzer is empty):

`2018-05-01 14:26:30,145 [cuckoo.core.scheduler] INFO: Task #88: acquired machine win7_x86_2 (label=C:\virtualMachines\Win7_x86_2\Win7_x86.vmx)`
`2018-05-01 14:26:30,168 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 7932 (interface=\Device\NPF_{2CE62467-4C18-4AE7-BC72-5E4A120934B9}, host=192.168.56.22)`
`2018-05-01 14:26:30,170 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer`
`2018-05-01 14:26:30,551 [cuckoo.machinery.vmware] DEBUG: Revert snapshot for vm C:\virtualMachines\Win7_x86_2\Win7_x86.vmx`
`2018-05-01 14:26:34,081 [cuckoo.machinery.vmware] DEBUG: Starting vm C:\virtualMachines\Win7_x86_2\Win7_x86.vmx`
`2018-05-01 14:26:40,045 [cuckoo.core.guest] INFO: Starting analysis on guest (id=win7_x86_2, ip=192.168.56.22)`
`2018-05-01 14:26:41,049 [cuckoo.core.guest] DEBUG: win7_x86_2: not ready yet`
`2018-05-01 14:26:41,059 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.8 (id=win7_x86_2, ip=192.168.56.22)`
`2018-05-01 14:26:41,096 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=win7_x86_2, ip=192.168.56.22, monitor=latest, size=3814549)`
`2018-05-01 14:26:41,381 [cuckoo.core.guest] DEBUG: win7_x86_2: analysis still processing`
`2018-05-01 14:26:41,549 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.`
`2018-05-01 14:26:42,385 [cuckoo.core.guest] WARNING: win7_x86_2: analysis caught an exception`
`Traceback (most recent call last):`
`  File "C:/tmpqzoqx8/analyzer.py", line 798, in <module>`
`    success = analyzer.run()`
`  File "C:/tmpqzoqx8/analyzer.py", line 580, in run`
`    "not exist.".format(package_name))`
`CuckooError: Unable to import package "modules.packages.None", does not exist.`

`2018-05-01 14:26:42,398 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer`
`2018-05-01 14:26:42,400 [cuckoo.machinery.vmware] DEBUG: Stopping vm C:\virtualMachines\Win7_x86_2\Win7_x86.vmx`
`2018-05-01 14:26:44,801 [cuckoo.core.scheduler] DEBUG: Released database task #88`
`2018-05-01 14:26:44,828 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #88`
`2018-05-01 14:26:44,829 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #88`
`2018-05-01 14:26:44,831 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #88`
`2018-05-01 14:26:44,845 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #88`
`2018-05-01 14:26:44,845 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #88`
`2018-05-01 14:26:44,846 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #88`
`2018-05-01 14:26:44,848 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #88`
`2018-05-01 14:26:44,848 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #88`
`2018-05-01 14:26:44,857 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #88`
`2018-05-01 14:26:44,871 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #88`
`2018-05-01 14:26:44,973 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #88`
`2018-05-01 14:26:44,973 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #88`
`2018-05-01 14:26:44,974 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #88`
`2018-05-01 14:26:44,977 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #88`
`2018-05-01 14:26:44,980 [cuckoo.core.plugins] DEBUG: Running 473 signatures`
`2018-05-01 14:26:45,119 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"`

**Comment by doomedraven** [comment]
bcz there is no package for .txt, not make sense push .txt to cuckoo, what do you expect from .txt to be executed?

**Comment by doria90** [comment]
@doomedraven It was only a test, All I'm saying is that nothing works for me now and I wonder if anyone has seen something like this

**Comment by doomedraven** [comment]
i love this part 
>> Actually It worked great on Windows 10! I don't know what happened as I gave the machine to someone and now it malfunctions as I described.

maybe reinstall and don't give it to nobody else?

**Comment by doria90** [comment]
Yeah mate that will be the final step I'm afraid. I'm not so eager to reinstall as the host is a Windows 10 with the Linux subsystem running for support. not that fun

**Comment by doomedraven** [comment]
ouch that is pervert way to do the things, any way you theoretically should only reinstall cuckoo, the rest should be fine, and as it uses separated conf, it will be "autoconfigured". i hope they didn't touch your vms snapshots?

**Comment by doria90** [comment]
Yeah the vms should be fine I think, I'll try to reinstall it.

Is there something I should avoid?
And is it as simple as delete -> install -> import previous conf?

**Comment by doomedraven** [comment]
yes, but after delete verify what it was uninstalled correctly and no files left, to be sure what it will be clean install

**Comment by doria90** [comment]
Just to be sure, Once i reinstall I don't do to cuckoo init, as I already have the previous environment in place.. right?

**Comment by doomedraven** [comment]
yes

**Comment by doomedraven** [comment]
there is no `remove`, you should use `uninstall`

**Comment by doria90** [comment]
Yeah thanks! :)

**Comment by doria90** [comment]
I'll update if re-installing helped.

**Comment by doria90** [comment]
AAAAND it WORKS!
Dunno what happend or why this fixed it, but thanks for all the help!

Can close

**Comment by doomedraven** [comment]
maybe they changed something in code, close if solved ;)
