### ISSUE TITLE
api monitoring accuracy

### ISSUE THREAD

**Issue by KZEE07** [cuckoosandbox/cuckoo#2250]
Hi everyone, 

I am working on a small project and I am trying to test and verify “Cuckoo  API calls monitoring mechanism ” is it giving me the accurate api calls or not! of what has been invoked by the submitted sample. For example, I want to submit and (app, file , script or whatever) with full knowledge of what my sample is going to invoke “for example, I already know that my sample will make 3 api calls exactly”. So I can look into what cuckoo result is telling me and then compare, if cuckoo reporting what I know already then I can say that cuckoo is accurate.

The problem is I have zero programing skills and I hope someone can suggest a way of doing this experiment!? To experimentally prove that cuckoo api monitoring is accurate etc! 

BTW, I am running Cuckoo Sandbox 2.0.5 and everything seems to be  running smoothly. I have submitted number of  samples and its also working perfectly! Thanks

**Comment by doomedraven** [comment]
if you know which api your app calls, see the behavior log, and if you miss some apis, checks in monitor repo if that apicall is hooked in sigs

**Comment by KZEE07** [comment]
"_if you know which api your app calls_" I don’t. I was hoping if you can help me to find a simple app with a documented behaviour (api calls) so I can run it in cuckoo and see if cuckoo does report the same "thing" documented calls, so I can confirm the accuracy of what cuckoo is reporting . My point is, when you submit a sample (EXE or whatever) for a behaviour analysis, and then cuckoo gives you a list of api calls that was triggered by that sample, why should I trust what cuckoo is reporting!? how can I confirm that !?

**Comment by doomedraven** [comment]
but you told :
>>  I want to submit and (app, file , script or whatever) with full knowledge of what my sample is going to invoke

learn how to use procmon/spymonitor, etc, but all of them can be fooled, but anyway, this isn't a malware forum

**Comment by RicoVZ** [comment]
Hi KZEE07,

You can do what @doomedraven suggested: find out what calls are used in some existing executable, submit it, and verify.

You could also create small programs that test specific API calls. If you are doing this as a research assignment, I would suggest to use the latter. As this way it would be easier to prove/verify your test data set is actually what you expect it to be.

**Comment by jbremer** [comment]
Closing issue.
