### ISSUE TITLE
I can't find tcpdump auxiliary modules on new cuckoo versions

### ISSUE THREAD

**Issue by tal-shoshana** [cuckoosandbox/cuckoo#2253]
Hi,

I used to use cuckoo version 2.0-rc2 and I had a proprietary folder named "modules"  with all the relevant modules I have in the auxiliary.conf file.

Now I upgraded to 2.0.5 stable version but the tcpdump and other auxiliary modules I used are not exists on cuckoo folder at all.

Please help

**Comment by tal-shoshana** [comment]
Hi,

The attached file my cuckoo (2.0.5 version)  directory structure.  I don't have auxiliary filder at all under the $CWD directory as you wrote. 

For some reason the only place I could find some auxiliary modules is: 
"/opt/cuckoo/analyzer/windows/modules/auxiliary"

[dir.log](https://github.com/cuckoosandbox/cuckoo/files/1958584/dir.log)


Thanks in advance!

**Comment by jbremer** [comment]
Sorry, what I meant to say is that the Cuckoo installation and CWD are separate from each other now.
If you have proprietary Auxiliary modules, then you'll have to integrate those yourself into the Cuckoo package system and install it accordingly - for various reasons (e.g., future backwards compatibility, configuration validation, and support for automated upgrading of Cuckoo) this isn't as "plug and play" as it was before.
This may change again in the future (to be more loose), but for now our advice is to upstream any modules that may be useful to the rest of the community. Of course we can also help with said work ;-)

**Comment by tal-shoshana** [comment]
In past I could mention and control the Guest/VM auxiliary modules thourh the configuration at config/auxiliary.conf. Today I see the auxiliary.conf file is only control the auxiliary modules at "/use/local/lib/python2.7/dist-packages/cuckoo/auxiliary" and not thise at "$CWD/analyzer/windows/modules/auxiliary". Am I right?
