### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by elig0n** [cuckoosandbox/cuckoo#2257]
On windows:
`pip install -U cuckoo`

>Collecting cuckoo
  Using cached https://files.pythonhosted.org/packages/bb/a9/c8b6f47dc5aeb7aa0efdeb67fdac0091f3ebbc9dbe3a551fc19d56438556/Cuckoo-2.0.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Temp\pip-install-9omvjvvl\cuckoo\setup.py", line 107
        print "  This particular error may be resolved as follows:"
                                                                  ^
    SyntaxError: Missing parentheses in call to 'print'
    ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in D:\Temp\pip-install-9omvjvvl\cuckoo\

This is obviously python3 print command incompatibility

**Comment by jbremer** [comment]
That's correct! We recently added 73332b809370056489c7646ce222749244af6a79, see also #2231. Python 3 is on the longer term TODO plan, but will takes months of work ;-)

**Comment by jbremer** [comment]
Closing issue as resolved, BTW. Thanks for reporting and let us know if you have any other questions.
