### ISSUE TITLE
Calling non-existent pip function

### ISSUE THREAD

**Issue by ttufts** [cuckoosandbox/cuckoo#2269]
https://github.com/cuckoosandbox/cuckoo/blob/cee4f2fd8084a988db8c0a1c3017ecedd0d541db/cuckoo/common/utils.py#L262

I think you meant _get_installed_distributions()

But that would be terrible practice, so probably using setuptools is a better option. A similar thread in pypa is here: https://github.com/pypa/pip/issues/5243

-------
(venv) bash-3.2$ python -V
Python 2.7.14

(venv) bash-3.2$ pip freeze
alembic==0.8.8
androguard==3.0.1
asn1crypto==0.24.0
beautifulsoup4==4.5.3
capstone==3.0.5rc2
cffi==1.11.5
chardet==2.3.0
click==6.6
colorama==0.3.7
cryptography==2.2.2
Cuckoo==2.0.5.3
Django==1.8.4
django-extensions==1.6.7
dpkt==1.8.7
ecdsa==0.13
egghatch==0.2.1
elasticsearch==5.3.0
enum34==1.1.6
Flask==0.12.2
Flask-SQLAlchemy==2.1
functools32==3.2.3.post2
HTTPReplay==0.2.3
idna==2.6
ipaddress==1.0.22
itsdangerous==0.24
Jinja2==2.9.6
jsbeautifier==1.6.2
jsonschema==2.6.0
libmagic==1.0
Mako==1.0.7
MarkupSafe==1.0
olefile==0.43
oletools==0.51
peepdf==0.3.6
pefile2==1.2.11
Pillow==3.2.0
pycparser==2.18
pyelftools==0.24
pymisp==2.4.54
pymongo==3.0.3
python-dateutil==2.4.2
python-editor==1.0.3
python-magic==0.4.12
pythonaes==1.0
requests==2.13.0
SFlock==0.2.20
six==1.11.0
SQLAlchemy==1.0.8
tlslite-ng==0.6.0
unicorn==1.0.1
urllib3==1.22
wakeonlan==0.2.2
Werkzeug==0.14.1
yara-python==3.6.3

**Comment by jbremer** [comment]
This has been "resolved" within our latest commits.  See also b1abf228e6774f529d3843dbf161d10d16ff7fca. I think we can close this issue?

**Comment by jbremer** [comment]
The commit above is included in the new `2.0.6` release, closing as resolved.
