### ISSUE TITLE
Secure achitecture setup

### ISSUE THREAD

**Issue by geekscrapy** [cuckoosandbox/cuckoo#2271]
Yet to build a cuckoo instance however I have throughly read the docs about setup (I hope!) but I'm slightly confused about the architecture.

I'm mainly referring the segregation of the dirty vms to the cuckoo instance. The way I understand it the cuckoo instance pretty much acts as a bridge between the analysis network and the dirty network?

I'm looking at building an environment within ESX where the dirty lan (where the malware is executed) only has access to the agent reporting ports on the clean lan, and have all network comms and pcap capture go out via a separate egress point (maybe over vpn, inetsim etc.) within the dirty lan.
Is there currently an easy way to do this? Would it the best to create an auxiliary module to setup the external pcap capture + to obtain the pcap after execution?

I guess what would help if someone could point me in the direction of a low-level network diagram for the different elements of cuckoo, that'd be great!

**Comment by RicoVZ** [comment]
Hi geekscrapy,

Thanks for posting an issue.

Cuckoo vms usually are in a virtual network that is connected to the Cuckoo machine. This way, Cuckoo can make network dumps etc.

It might be interesting for you to look at the Cuckoo Rooter: https://cuckoo.sh/docs/usage/rooter.html
This allows for per-analysis routes, and still have the network dumps. This does require the network interface for which to make the network dump is accessible for Cuckoo.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
