### ISSUE TITLE
Unhandled exception: No handlers could be found for logger "cuckoo"

### ISSUE THREAD

**Issue by Shockmeister** [cuckoosandbox/cuckoo#2276]
Hi,

I followed the install as per the instructions in the manual, but when I run cuckoo, I get the above exception. The output is below:

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:0.8.8 androguard:3.0.1 asn1crypto:0.24.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.11.5 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.2.2 cuckoo:2.0.5.3 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 httpreplay:0.2.3 idna:2.6 ipaddress:1.0.22 itsdangerous:0.24 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 mako:1.0.7 markupsafe:1.0 olefile:0.43 oletools:0.51 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 pip:9.0.3 pkg-resources:0.0.0 pycparser:2.18 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:18.0.0 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 requests:2.13.0 scapy:2.3.2 setuptools:39.2.0 sflock:0.2.20 six:1.11.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unicorn:1.0.1 urllib3:1.22 wakeonlan:0.2.2 werkzeug:0.14.1 wheel:0.31.1 yara-python:3.6.3

No handlers could be found for logger "cuckoo"

Anyone come across this problem before?

Thanks

**Comment by jbremer** [comment]
How did you install Cuckoo? Thanks.

**Comment by Shockmeister** [comment]
I used pip install -U cuckoo.

Initially I had a pip error when I ran it: 

AttributeError: 'module' object has no attribute 'get_installed_distributions'

So I reverted back to pip 9x
