### ISSUE TITLE
Cuckoo update fail - Likely server down

### ISSUE THREAD

**Issue by vicky-ray** [cuckoosandbox/cuckoo#2277]
Hi, Looks like the server is down-

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 Error checking for the latest Cuckoo version: HTTPSConnectionPool(host='cuckoosandbox.org', port=443): Max retries exceeded with url: /updates.json?version=2.0.5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f95b4642950>, 'Connection to cuckoosandbox.org timed out. (connect timeout=6)'))!

**Comment by vicky-ray** [comment]
Hi @RicoVZ ,

Great, thanks!

**Comment by RicoVZ** [comment]
Update: the servers went up again about 10 hours ago.
