### ISSUE TITLE
Not regarding lsass.exe as the first malware process in the decision of sleep skip

### ISSUE THREAD

**Issue by y-oyama** [cuckoosandbox/cuckoo#2280]
Hi,

Cuckoo's module intercepts lsass.exe to monitor HTTPS traffic. But, I am afraid that intercepting
lsass.exe may affect the behavior of sleep skip. In my environment, Cuckoo does not skip any sleep,
and it seems to be caused by lsass.exe. Cuckoo seems to judge the target malware creates multiple
processes even when the malware does not actually create a process, because Cuckoo counts the
lsass.exe process as the first process of the malware, and creation of a malware process makes
Cuckoo consider that the malware dynamically created a process and it should stop to skip sleeps.

I disabled the dumptls module by modifying processing.conf, but Cuckoo continued to intercept lsass.exe. So, I removed dumptls.py to prevent the insertion of the DumpTLSMasterSecrets module.

Can I have another method to stop Cuckoo to intercept lsass.exe?
Or, is it possible to modify Cuckoo to prevent lsass.exe from being judged as the first process of the
malware?

My Cuckoo version is 2.0.5 and my operating systems are:
Host: Ubuntu  18.04 (Linux 4.15.0-22-generic)
Guest: Windows XP
I used the latest Cuckoo modules.

Thanks,

Yoshihiro

**Comment by jbremer** [comment]
Hi @y-oyama, excellent catch! Could you verify the following patch for me? Thanks.
```
diff --git a/cuckoo/data/analyzer/windows/lib/api/process.py b/cuckoo/data/analyzer/windows/lib/api/process.py
index 063d3ef..81f462a 100644
--- a/cuckoo/data/analyzer/windows/lib/api/process.py
+++ b/cuckoo/data/analyzer/windows/lib/api/process.py
@@ -514,7 +514,12 @@ class Process(object):
             os.write(fd, "%s=%s\n" % (key, value))
 
         os.close(fd)
-        Process.first_process = False
+
+        # Only change the first_process attribute for processes that we
+        # "track", i.e., the lsass.exe injection doesn't count.
+        if track:
+            Process.first_process = False
+
         return config_path
 
     def dump_memory(self, addr=None, length=None):
```

**Comment by y-oyama** [comment]
Perfect! The patch works well. Thank you.

**Comment by jbremer** [comment]
Thanks, I've committed the fix. Will be pushing this patch among a few others for a brief interim release shortly. More news on that soon!

**Comment by jbremer** [comment]
This is part of our `2.0.6` release, closing as resolved. Thanks!
