### ISSUE TITLE
Customize Analysis Submit Web Page

### ISSUE THREAD

**Issue by alxhrck** [cuckoosandbox/cuckoo#2282]
Cuckoo Version: 2.0.5
Is there a documented way to customize the default settings on the presubmit page of Cuckoo Web? For example, changing the default Timeout from 120 to 60 or disabling Injection.

**Comment by RicoVZ** [comment]
Hi alxhrck,

Thanks for posting your issue.

The way to change this would be to change those values in the config files.
However, not all values are present in the config.

The default timeout can be configured in the `[timeouts]` section in your `cuckoo.conf`. The one that is presented in the web interface read from there. The injection, enforce timeout, process memory dump, and simulate human interaction settings are static.

If other default options are desired, these can be change in this web controller: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/web/controllers/submission/api.py#L39

Currently, one of the features we are working on are analysis profiles. These will be profiles containing settings that can be chosen for an anlysis. It will allow you to save your desired settings. I cannnot tell anything about an ETA for this yet, though :smile:.

**Comment by alxhrck** [comment]
Thank you for the quick response. The configurations inside api.py was exactly what I was looking to find.
