### ISSUE TITLE
How does Cuckoo work?

### ISSUE THREAD

**Issue by thanhtunghcm** [cuckoosandbox/cuckoo#2289]
Hi everyone, 

I don't know how cuckoo does work so,
Could someone please explain to me how it works?

Thank you so much.

**Comment by doomedraven** [comment]
Read the documentation

**Comment by RicoVZ** [comment]
Hi thanhtunghcm,

It kind of depends on what part you are talking about. 
An explanation of the general operation of Cuckoo Sandbox can be found here:

https://cuckoo.sh/docs/introduction/what.html#architecture
https://cuckoo.sh/docs/introduction/what.html

**Comment by thanhtunghcm** [comment]
Oh thank you @doomedraven @RicoVZ 
It's my mistake
Regards.
