### ISSUE TITLE
cuckoo web need mongodb.

### ISSUE THREAD

**Issue by DragonQuestHero** [cuckoosandbox/cuckoo#2292]
Hey,all.
I configured cuckoo,reporting.conf n mongodb.But it's still dose not work.

Ubuntu 16.04
`ock@ubuntu:~$ cuckoo

  eeee e   e eeee e   e  eeeee eeeee
  8  8 8   8 8  8 8   8  8  88 8  88
  8e   8e  8 8e   8eee8e 8   8 8   8
  88   88  8 88   88   8 8   8 8   8
  88e8 88ee8 88e8 88   8 8eee8 8eee8

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017
`

`ock@ubuntu:~$ mongo
MongoDB shell version: 2.6.10
connecting to: test
> ^C
bye
`

`[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes 
paginate = 100
# MongoDB authentication (optional).
username = 
password = 
`
What's wrong in here?
Thanks

**Comment by DragonQuestHero** [comment]
I forget say.cuckoo -d will work

**Comment by DragonQuestHero** [comment]
I seed this.https://github.com/cuckoosandbox/cuckoo/issues/1724
But i can't found any other reporting.conf

**Comment by doomedraven** [comment]
Without log impossible to say something

**Comment by doomedraven** [comment]
cuckoo -d web ....

**Comment by RicoVZ** [comment]
Hi DragonQuestHero,

Yes, the `cuckoo.log` is also useful. 

Try starting web like this: `cuckoo web -H 0.0.0.0 -p 777`, instead of using `runserver`. Using that is not required. Verify if it does work after this, if not, please post the output generated by starting it this way.

**Comment by doomedraven** [comment]
One thing if you dont have authbind, you meed to start as root as till port 1024 you cant use

**Comment by DragonQuestHero** [comment]
@doomedraven @RicoVZ 
Thx two guys.
but does not work.
The output in here:
`
ock@ubuntu:~$ cuckoo web runserver 0.0.0.0:777
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
ock@ubuntu:~$ cuckoo --debug web -H 0.0.0.0 -p 777
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
ock@ubuntu:~$ cuckoo --debug web -H 0.0.0.0 -p 7777
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
ock@ubuntu:~$ cuckoo --debug web -H 0.0.0.0 -p 8080
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.
`

**Comment by RicoVZ** [comment]
Thanks @DragonQuestHero for the update. :smile: 

Mhmm,, `cuckoo --debug web -H 0.0.0.0 -p 8080` should work if MongoDB was enabled in the file `/home/<youruser>/.cuckoo/conf/reporting.conf`.

At what file path have you edited the `reporting.conf` file?

It looks like your Cuckoo is using a working directory (CWD) at which MongoDB was not configured.

**Comment by DragonQuestHero** [comment]
@RicoVZ thank u response
The reporting.conf file path is:/home/username/.cuckoo/conf
And MongoDB working.
When i modify reporting.conf file,nothing changed.Maybe somewhere have other reporting.conf file?

**Comment by RicoVZ** [comment]
> When i modify reporting.conf file,nothing changed.Maybe somewhere have other reporting.conf file?

The file you have edited is the correct `reporting.conf`. But only if you do not start Cuckoo web with the `--cwd` argument and Cuckoo is not being run as a different user. The latter would cause the reporting.conf to be read from the user home of the user Cuckoo is being run by.

Please try the following to start Cuckoo web
`cuckoo --cwd ~/.cuckoo --debug web -H 0.0.0.0 -p 8080`

**Comment by DragonQuestHero** [comment]
@RicoVZ 
Can not.
Did i have something wrong???
![qq 20180607093010](https://user-images.githubusercontent.com/21189903/41073410-b404abc6-6a35-11e8-9fc9-0f19a1db93bd.jpg)

**Comment by doomedraven** [comment]
yes enabled=no

**Comment by RicoVZ** [comment]
@DragonQuestHero 

Change `enabled = no` to `enabled = yes`

**Comment by DragonQuestHero** [comment]
@RicoVZ @doomedraven 
Think u guys.
I forget that lol.cuckoo web working now
