### ISSUE TITLE
question about analysis about linux files

### ISSUE THREAD

**Issue by littleqt** [cuckoosandbox/cuckoo#2297]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at: 
Thank you for your help!

**Comment by doomedraven** [comment]
Post logs, cuckoo and process if you have separated instance

**Comment by RicoVZ** [comment]
Hi @littleqt,

Thanks for posting an issue.

Could you: start Cuckoo using the `--debug` flag, submit an analysis, and let it process. After that, post the `cuckoo.log` file here? That would greatly help to find a possible reason for this.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
