### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by imaginesecure** [cuckoosandbox/cuckoo#2298]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I have installed Cuckoo 2.0.5.3 numerous times, and I seem to be missing all of the modules
##### My Cuckoo version and operating system are:
Cuckoo 2.0.5.3 / Ubuntu 18.04 bionic

Pretty straight forward question.

I have tried a global installation, as well as in a virtual env, and also installed from a file. Each time, the modules seem to be missing

**Comment by doomedraven** [comment]
Without logs - impossible to help, pr provide better description

**Comment by imaginesecure** [comment]
which logs would be beneficial to solving this?

**Comment by jbremer** [comment]
Which modules are you missing..?

**Comment by imaginesecure** [comment]
All of them, it looks like when I did the install, regardless of how I did it, the modules just did not come with

**Comment by jbremer** [comment]
Ah, I didn't realize you meant *all* of the modules.. did you fetch the modules from the Cuckoo Community (see our docs)?
