### ISSUE TITLE
How to configure yara rules in cuckoo

### ISSUE THREAD

**Issue by vikaskarunakaran** [cuckoosandbox/cuckoo#2299]
I have installed cuckoo in my linux with 3 VMs and all the analysis are performed well.
No my issue is to configure custom yara rules in cuckoo from github repo 
https://github.com/Yara-Rules/rules/archive/master.zip

I have changed my cwd to "/opt/cuckoo" and at this location I cannot see "/data" directory. Do I need to create it?

After installing cuckoo community "/yara" directory is created with default rules under "/opt/cuckoo/"

Now where do I download and include the custom yara rules to make it match against the samples I submit for analysis ?

Where will these default yara rules be included for scan ? 

Which module of cuckoo calls these yara rules to scan it against the samples ?

Kindly help with these issues and queries

**Comment by doomedraven** [comment]
Dont integrate them, it will break yor cuckoo! Only use that which you need, check in your cwd or do 

locate memory.yar to find the location

**Comment by vikaskarunakaran** [comment]
@doomedraven I can see index_memory.yar in "/opt/cuckoo/stuff/". Should I include the path of all my other yara rules in this file? 

I think this file will match the yara rules against the process memory.

If other yara rules are included can it be matched against the file in static scan ?

**Comment by capnspacehook** [comment]
@doomedraven what problems have you gotten when using the rules from https://github.com/Yara-Rules/rules? 

I have also been trying to add yara rules from this repo, and per commit https://github.com/jbremer/cuckoo/commit/2eeb10e8134bd5636484fff01ffe93e2a6ccf506, Cuckoo should just grab the yara rules in the CWD/yara dir. Why doesn't this happen?

**Comment by doomedraven** [comment]
do searches in issues and you will see tons of issues related to this

**Comment by capnspacehook** [comment]
I see. So really extra yara rules don't enhance as much as you might think? Because they depend on additional Cuckoo signatures as well?

**Comment by jbremer** [comment]
That's correct. We'd be happy if somebody steps up to isolate the useful Yara rules and create Cuckoo Signatures, though ;-)

**Comment by doomedraven** [comment]
totally agree

**Comment by SparkyNZL** [comment]
see, i  learn something new every day ! :(

**Comment by doomedraven** [comment]
the problem what useful is different for every usercase

**Comment by benrau87** [comment]
FWIW, you can get a good base of rules from https://github.com/Yara-Rules/rules
ONLY use CVE_Rules, Crypto and Packers though. Most of the malware rules work too except for MALW_AZORULT.yar

**Comment by capnspacehook** [comment]
I was just playing with the rules today, and it seems MAL_AZORUKT.yar only works if you compile yara to use the Cuckoo module

**Comment by jbremer** [comment]
Closing issue.
