### ISSUE TITLE
Why is my Cuckoo.log empty?

### ISSUE THREAD

**Issue by jel-n** [cuckoosandbox/cuckoo#2300]
Simple enough title

**Comment by doomedraven** [comment]
COuld you provide more reach descriptions? Line i run cuckoo -d and there now output at all?

Describe what you have started etc etc as issue requires. In that way you save us time and we will be able to help ypu faster :)

**Comment by imaginesecure** [comment]
I run cuckoo -d, and it runs, but nothing goes to the cuckoo.log

**Comment by doomedraven** [comment]
but is there an output in console? it hard to help you in this way

**Comment by RicoVZ** [comment]
Hi @imaginesecure,

As @doomedraven asked, is there any output to the console when you start Cuckoo in debug mode? (`cuckoo --debug`)

Do you specify a custom working directory? (`--cwd <path>`)
What cuckoo.log do you mean? Cuckoo has an overal cuckoo.log and a per-analysis cuckoo.log file at `$CWD/storage/analyses/<taskid>/cuckoo.log`.

It might also help to specify what Cuckoo version you are using and the OS the Cuckoo host is running on.

It would be helpful if you follow our issue template next time, it has default questions for a reason. :smile:

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
