### ISSUE TITLE
Can't Find cuckoo.py

### ISSUE THREAD

**Issue by Irfan-Luthfi** [cuckoosandbox/cuckoo#2303]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I cant find "cuckoo.py" even after I do all of requirements, do "sudo pip install -U pip setuptools", and "sudo pip install -U cuckoo"

##### My Cuckoo version and operating system are:
I use Cuckoo 2.0.6 and my OS is Ubuntu 16.04.3

##### The log, error, files etc can be found at:

![image](https://user-images.githubusercontent.com/35715103/40893810-d840ff1c-67ce-11e8-99b5-eb968b2de2de.png)

**Comment by doomedraven** [comment]
there no cuckoo.py but you can use `cuckoo` command to start cuckoo

**Comment by Irfan-Luthfi** [comment]
I can't

![image](https://user-images.githubusercontent.com/35715103/40902197-5f7ee1b4-67fd-11e8-8fdd-5bd426606fc6.png)

**Comment by doomedraven** [comment]
`locate cuckoo`?

**Comment by Irfan-Luthfi** [comment]
Its has problem with "pillow" but when i check, i have "pillow"

![image](https://user-images.githubusercontent.com/35715103/40902253-a18352de-67fd-11e8-91a0-44d02a9454d1.png)

**Comment by doomedraven** [comment]
well if you read the errors you have how to fix it ;) google for that valueError and fix it before continue

**Comment by RicoVZ** [comment]
Hi @Irfan-Luthfi, how is this going now? Was your issue resolved?

**Comment by RicoVZ** [comment]
Hi @d4n13l4,

What exactly do you mean by checking the working directory?

About the `import` command:
This is only for "importing" old/legacy Cuckoo setups (`< 2.0.0` versions).

When upgrading from a `> 2.0.0` to a higher version, you can simply use `pip install -U cuckoo`.
After doing this, you can start Cuckoo. It will then detect a version change and, if needed, copy new files to your CWD.

The default CWD is `/home/<youruser>/.cuckoo`. You can also specify another by using the `--cwd <path to other cwd>` when using Cuckoo.

**Comment by d4n13l4** [comment]
Well I read the documentation http://docs.cuckoosandbox.org/en/latest/installation/upgrade/ and it said use this import command so I tried that and then it was that problem with the working directory, I specified the one you write as default and it keep saying it's not correct

I also tried with pip and upgrade option but it didn't upgrade it, some packages were updated but the overall cuckoo wasn't because when I run it again I still got the message that I was using old version
I'll try again later if you say this is the way to upgrade then it should work.

Thanks.

**Comment by Irfan-Luthfi** [comment]
@RicoVZ Still not, I've tried to repeat again and again, but still no Cuckoo.py file

**Comment by RicoVZ** [comment]
@d4n13l4 

Can you post the log/message where you are seeing that tells you that you still have an old version? This should not happen if you have the latest version. Did you run `pip install -U cuckoo`? :smile: 

@Irfan-Luthfi 
As doomedraven stated, there is no `cuckoo.py` file. When you install Cuckoo using `pip install -U cuckoo`, the `cuckoo` command should be available. I suggest you install Cuckoo in a virtualenv.

You can do that like this:
```
$ virtualenv venv
$ . venv/bin/activate
(venv)$ pip install -U pip setuptools
(venv)$ pip install -U cuckoo
```
Cuckoo will then only be available in this virtualenv.  Make sure you do `not` use `sudo` when installing Cuckoo in a virtualenv. :smile:

**Comment by d4n13l4** [comment]
@RicoVZ this time doing pip command updated the cuckoo ;)
