### ISSUE TITLE
Difference from cuckoo-modified

### ISSUE THREAD

**Issue by capnspacehook** [cuckoosandbox/cuckoo#2305]
Hi! So I noticed that a fork of Cuckoo, https://github.com/spender-sandbox/cuckoo-modified exists and seems to have lots of features that Cuckoo doesn't. But since cuckoo-modified has stopped active development by the devs, I was wondering how much, if any, is/has Cuckoo worked to try and incorporate the advances of cuckoo-modified?

**Comment by RicoVZ** [comment]
Hi capnspacehook,

Thanks for your question.

We would have to discuss individual features, as there are many. Cuckoo Sandbox is constantly improving, adding new features, etc. We follow our own roadmap. But there is a general goal of adding features that users want.

When a user has a specific feature requests, we consider it and add it to our todo list.

If we get requests, and code for it exists, this often will be used. However, most things/ideas that are added are changed a lot. So it is hard to say what specifically came from/was inspired by Cuckoo-modified and what did/was not.

**Comment by capnspacehook** [comment]
Makes sense. Guess that was too broad a question. I'm wondering specifically if the anti-anti-sandboxing or anti-anti-debugging techniques have been integrated into Cuckoo main

**Comment by RicoVZ** [comment]
Good question :smile:  I would have to check this for each anti-anti technique, though.

I am sure we do not have all of them.

If any new anti-sandbox/debugging behavior is found in working samples, we will add mitigation for it to our todo list. For this, we also rely upon the community to report these kinds of behaviors to us.
