### ISSUE TITLE
No CWD

### ISSUE THREAD

**Issue by imaginesecure** [cuckoosandbox/cuckoo#2312]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I had to reinstall Cuckoo, and just noticed that I do not have a CWD, will that cause any issues on my system in the future, and if so what are my solutions?
##### My Cuckoo version and operating system are:
Cuckoo 2.0.5 // Ubuntu bionic 18.04

**Comment by doomedraven** [comment]
no cwd no config, generate it, but check $HOME/.cuckoo

**Comment by imaginesecure** [comment]
Well that's what is odd - I have all the files that are contained within the CWD, just no CWD. I can generate it, I was unsure if that would be sufficient or not. 

As for the location, yeah, it is not there

**Comment by imaginesecure** [comment]
@RicoVZ 

It's weird.. because my install on another machine was fine. 

So my /home/user/.cuckoo - within this, there is a conf folder containing the configuration files, along with all of the other folders that should be there. 

There is a .cwd file

**Comment by RicoVZ** [comment]
@imaginesecure 

Alright, so you are missing the `.cwd` file?
This is the file used to determine what version of Cuckoo your CWD folder is.

Yes, you can manually created it. You can create it, and Cuckoo will detect it next startup. It will then try to set your CWD folder to the version of your Cuckoo.
