### ISSUE TITLE
Unable to start auxiliary module mitm

### ISSUE THREAD

**Issue by iboow38** [cuckoosandbox/cuckoo#2313]
##### The error:
`018-06-07 20:11:10,345 [cuckoo.core.plugins] ERROR: Unable to start auxiliary module mitm
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 123, in start
    current.start()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/mitm.py", line 68, in start
    stdout=open(cwd("mitm.log", task_id=self.task.id), "wb"),
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 59, in cwd
    "Invalid arguments provided to cwd(): %r %r" % (args, kwargs)
RuntimeError: Invalid arguments provided to cwd(): ('mitm.log',) {'task_id': 19}`

**Comment by RicoVZ** [comment]
Hi @iboow38,

Thanks for posting an issue. :smile: 

This was an error in the released and was just patched in commit https://github.com/cuckoosandbox/cuckoo/commit/9a1cd18a079de49cc5279631c04995313e2b509e

This was not pushed to the Pypi package yet, but should be soon.

**Comment by iboow38** [comment]
Hi @RicoVZ  updated the mitm.py file now it is working. !

**Comment by JReming85** [comment]
@RicoVZ Hey just wanted to say thanks, this also resolved my issue.

Lets just hope its smooth sailing from here on out and I dont have any of the issues I did before a year ago (I think I see where I went wrong back then with using cuckoo rooter + mitm + snort+ suricata, no rooter and I can see network traffic now)
