### ISSUE TITLE
new update cuckoo 2.0.6 start error

### ISSUE THREAD

**Issue by thevidocq** [cuckoosandbox/cuckoo#2314]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:

Hi, I have updated cuckoo with pip command "pip install cuckoo --upgrade" but now the start process fail, the error:

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.5.3', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/__init__.py", line 10, in <module>
    __file__, "cuckoo.reporting", globals(), Report
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 41, in enumerate_plugins
    "%s.%s" % (module_prefix, module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/elasticsearch.py", line 8, in <module>
    import elasticsearch.helpers
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/__init__.py", line 15, in <module>
    logger.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'

Python 2.7

Thanks.

**Comment by RicoVZ** [comment]
Hi thevidocq,

Thanks for posting an issue. :smile: 

I cannot yet say why this is happening. But I will try to reproduce it.
Can you use `pip freeze`, and post the output here?
This can help me to reproduce and find the error.

**Comment by thevidocq** [comment]
abuse-finder==0.1
alembic==0.8.8
androguard==3.0.1
apt-xapian-index==0.45
asn1crypto==0.24.0
Beaker==1.9.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
bottle==0.12.0
bottle-beaker==0.1.3
bottle-cork==0.12.0
bs4==0.0.1
capstone==3.0.5rc2
censys==0.0.8
certifi==2018.1.18
cffi==1.11.5
chardet==2.3.0
click==6.6
click-plugins==1.0.3
colorama==0.3.7
configobj==4.7.2
cortexutils==1.2.4
cryptography==2.1.4
Cuckoo==2.0.6
cybercrimetracker==0.0.2
DateTime==4.2
diskcache==3.0.6
distorm3==3.3.4
Django==1.8.4
django-extensions==1.6.7
dnspython==1.15.0
domaintools-api==0.2.2
dpkt==1.8.7
ecdsa==0.13
egghatch==0.2.2
elasticsearch==5.3.0
enum34==1.1.6
et-xmlfile==1.0.1
ez-setup==0.9
Flask==0.12.2
Flask-SQLAlchemy==2.1
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
html5lib==0.999
HTTPReplay==0.2.2
idna==2.6
ipaddr==2.2.0
ipaddress==1.0.19
ipwhois==1.0.0
itsdangerous==0.24
jdcal==1.3
Jinja2==2.9.6
jsbeautifier==1.6.2
jsonschema==2.6.0
Landscape-Client==14.12
libvirt-python==1.2.2
logging==0.4.9.6
logutils==0.3.5
Magic-file-extensions==0.2
Mako==1.0.7
MarkupSafe==1.0
meld3==0.6.10
nessrest==0.40
netaddr==0.7.19
olefile==0.43
oletools==0.51
openpyxl==2.5.1
PAM==0.4.2
passivetotal==1.0.30
peepdf==0.4.1
pefile==1.2.9.1
pefile2==1.2.11
Pillow==3.2.0
progressbar2==3.38.0
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.3
pydeep==0.2
pyelftools==0.24
pyeti==0.0.1
pyeupi==1.0
pyexifinfo==0.4.0
pyguacamole==0.6
pymisp==2.4.54
pymongo==3.0.3
pyOpenSSL==17.5.0
pypdns==1.3
pypssl==2.1
pyserial==2.6
python-apt===0.9.3.5ubuntu2
python-dateutil==2.4.2
python-debian===0.1.21-nmu2ubuntu2
python-editor==1.0.3
python-magic==0.4.12
python-utils==2.3.0
pythonaes==1.0
pythonwhois==2.4.3
pytz==2018.3
requests==2.13.0
requests-cache==0.4.13
requests-file==1.4.3
roach==0.1.2
scapy==2.3.2
SFlock==0.3.5
shodan==1.8.1
simplejson==3.15.0
six==1.11.0
SQLAlchemy==1.0.8
ssh-import-id==3.21
supervisor==3.0b2
timesketch-api-client==20170815
tldextract==2.2.0
tlslite-ng==0.6.0
tqdm==4.23.4
Twisted-Core==13.2.0
ujson==1.35
unicorn==1.0.1
urllib3==1.22
vboxapi==1.0
virtualenv==1.11.4
volatility==2.6
wakeonlan==0.2.2
Werkzeug==0.14.1
XlsxWriter==1.0.5
yara-python==3.6.3
zope.interface==4.0.5

Thanks!

**Comment by thevidocq** [comment]
I reinstalled cuckoo and now work ok. Thanks for the support.
