### ISSUE TITLE
unverified_ssl=yes breaks on recent vCenter versions that doesn't support TLSv1

### ISSUE THREAD

**Issue by ivocarv** [cuckoosandbox/cuckoo#2318]
##### The log, error, files etc can be found at:
in the vsphere.py code these lines manage unverified ssl setting: 
        # Workaround for PEP-0476 issues in recent Python versions
        if self.options.vsphere.unverified_ssl:
            sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
            sslContext.verify_mode = ssl.CERT_NONE
            self.connect_opts["sslContext"] = sslContext
            log.warn("Turning off SSL certificate verification!")

In this case, forcing ssl protocol to TLSv1 in not a good idea because probably vSphere 6.7 does not support this version (probably because of POODLE attack: https://www.globalsign.com/en/blog/poodle-vulnerability-expands-beyond-sslv3-to-tls/). Solved it on my installation changing the second line to:  sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2), but it does not seem to be the right way to solve this. In https://www.python.org/dev/peps/pep-0476/ it recommends using: 
 . context = ssl._create_unverified_context() 

update: changed this part of the code to:
     # Workaround for PEP-0476 issues in recent Python versions
        if self.options.vsphere.unverified_ssl:
            sslContext = ssl._create_unverified_context()
            self.connect_opts["sslContext"] = sslContext
            log.warn("Turning off SSL certificate verification!")

**Comment by RicoVZ** [comment]
Hi ivocarv,

Thanks for posting/reporting this! :smile: 

To confirm:
You are currently using `sslContext = ssl._create_unverified_context()` instead of `sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)`, and this works for you with vSphere 6.7?

And you have changed this line:
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/machinery/vsphere.py#L99

**Comment by ivocarv** [comment]
Hello Ricardo,

  Yes this is correct, but this line is no longer needed:
     .
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/machinery/vsphere.py#L100

    Ivo.

**Comment by RicoVZ** [comment]
Thanks for the confirmation! :smile:
