### ISSUE TITLE
Cuckoo says VM can't connect After it closes the VM

### ISSUE THREAD

**Issue by pyro57** [cuckoosandbox/cuckoo#2321]
##### The log, error, files etc can be found attached:
![selection_001](https://user-images.githubusercontent.com/13994663/41356781-32e3d472-6eea-11e8-9e2c-3ce2eaabb6c2.png)

**Comment by pyro57** [comment]
it finishes the analysis and gives good data, but it gives me this error every time, why would the VM be able to connect back to the host after the VM has been closed?

**Comment by doomedraven** [comment]
start analysis and do `curl vm_ip:8000`, post output

**Comment by pyro57** [comment]
{"message": "Cuckoo Agent!", "version": "0.8", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}

**Comment by pyro57** [comment]
it connects fine and runs the analysis, until the very end there, then it errors out, and the analysis still gives good results I was just wondering why it would expect the VM to connect after it has been closed.

**Comment by RicoVZ** [comment]
Hi pyro57,

Thanks for posting an issue.

The agent responds, this is good. :smile: 
The error you are receiving is likely because there are no behavioral logs, meaning the VM itself could not connect to the resultserver. Could you please post the full `cuckoo.log` file from `$CWD/storage/analyses/<taskid>/cuckoo.log`?

**Comment by pyro57** [comment]
This was in a test/dev environment so I just reinstalled cuckoo, and now it works fine, not sure what I did differently, but it is working, so I'm just gonna take it as one of those magical computer things that went away on its own haha.  Thanks for your help.
