### ISSUE TITLE
Cuckoo download and installetion issue

### ISSUE THREAD

**Issue by Cry0k** [cuckoosandbox/cuckoo#2326]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

My issue is: Can not download or install cuckoo with pip commands

My Cuckoo version and operating system are: cuckoo 2.0.6 ubuntu 14 

while i run the sudo pip install -U cuckoo command i get the following error: 
![screenshot from 2018-06-14 09 50 27](https://user-images.githubusercontent.com/37481568/41433414-9bbe4f8a-7021-11e8-8d6c-218e233a2632.png)

will be happy for any kinds of assistance

**Comment by RicoVZ** [comment]
Hi Cry0k,

It seems an existing installation of `chardet` is causing this. The Cuckoo (2.0.6.1) package requires version `2.3.0`.

Can you try installing Cuckoo in a `virtualenv`? We recommend using a virtualenv, as this should prevent any existing packages from interfering. :smile: 

```
$ mkdir somedir
$ cd somedir
$ virtualenv .
$ source bin/activate
$ pip install -U cuckoo
```

https://cuckoo.sh/docs/installation/host/installation.html#install-cuckoo

**Comment by Cry0k** [comment]
Hi Rico i have already deleted the previous installation of chardet and managed to install cuckoo thanks :)
