### ISSUE TITLE
TrID File Identifier 

### ISSUE THREAD

**Issue by capnspacehook** [cuckoosandbox/cuckoo#2328]
I would like to start working on a pull request for a feature I'd like to see in Cuckoo: integration of TrID. The reason I'm posting this as an issue is I would like to discuss how you would prefer me go about adding TrID, as TrID isn't written in Python, nor is it accessible from a Python library.

You could just run TrID and parse the output, but since Cuckoo doesn't really use non-python projects, I just wanted to make sure you guys would be interested in me adding this.

Also, since TrID can't be installed from pip, would you like me to just update the documentation to include instructions as how to install TrID, or just write a shell script to do it?

**Comment by jbremer** [comment]
Most importantly, what would be your use-case for TrID?

**Comment by capnspacehook** [comment]
It's come in handy identifying what language a binary was written in, or revealing useful information might might be hard to come by otherwise. For example, given a Win32 PE, you know it's a PE but not much else. But TrID will tell you if the binary is compiled with Visual C++, is written in dotnet, or is written in Delphi, etc. It also could clue you in if the file you are analyzing isn't what it seems, ie the malware author messed with the magic number/header to appear as another type of file.

**Comment by doomedraven** [comment]
sound like just userdb.txt

**Comment by capnspacehook** [comment]
Yeah, I guess you're right. Closing issue.
