### ISSUE TITLE
Scoring always at 0.0

### ISSUE THREAD

**Issue by Cry0k** [cuckoosandbox/cuckoo#2331]
Hi guys,
i am running cuckoo 2.0.6 and for some reason the score of the files is always at 0 even if the submitted file is a 100% malware.
i tried to do the community package update but it didn't work as well as far as i recal i am using the python version of cuckoo (installed with the pip command)

**Comment by doomedraven** [comment]
__did you read the output when you start cuckoo__? there is you didn't have any signature please run `cuckoo community`

**Comment by RicoVZ** [comment]
Hi Cry0k,

Thanks for posting an issue.

Can you share some more information on how you noticed updating the signatures did not work well? Did you run `cuckoo --debug community`? :smile: 

If so, what was the output?

**Comment by Cry0k** [comment]
Hi guys,

i've managed to fix the issue after i did apt-get update &apt-get upgrade once again apparently there was some process stuck at the background that did not allow me to run this command properly
