### ISSUE TITLE
Firewall Service stopped signature : Due to the cuckoo configuration

### ISSUE THREAD

**Issue by LetMeR00t** [cuckoosandbox/cuckoo#2333]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### This can be reproduced by:
Start a VM with a classic configuration
The signature will appears in the Cuckoo GUI report

##### The log, error, files etc can be found at:
This is an example of what we have (on the bottom) :
![capture d ecran de 2018-06-19 17-20-49](https://user-images.githubusercontent.com/10530375/41607289-fbca1e78-73e5-11e8-9dc4-6af95b70138d.png)

I suppose that these signatures affect the score or well, it can be great to remove them because it's something we know because it's due to the way how Cuckoo is configured.
Did you have something concerning this "issue" ?

**Comment by doomedraven** [comment]
well if you don't like that score you can modify signature inside to set it to lower score or remove it

**Comment by LetMeR00t** [comment]
Well, I was just wondering if it's was normal ...
But the signature is contained in volatility isn't ?
So, it's normal to have them regarding the Cuckoo configuration ... well ok :)

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/community/blob/40bcd3b798487e66fbeb2a69389da174f39ef2ac/modules/signatures/windows/volatility_sig.py#L85 yes
