### ISSUE TITLE
Cuckoo Host wasn't able to connect to the Guest and the other way around

### ISSUE THREAD

**Issue by Emparla** [cuckoosandbox/cuckoo#2334]
Hi there, I got a few issues with setting up cuckoo properly.

I can start up cuckoo and cuckoo web without any problems but if I start the analysis  i get the following error(s):

_ERROR: Error from machine 'windows7': it appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration

2018-06-20 10:44:29,191 [cuckoo.processing.behavior] WARNING: Analysis results folder does not exist at path '/home/sandbox/.cuckoo/storage/analyses/3/logs'.

2018-06-20 10:44:29,728 [cuckoo.processing.debug] ERROR: Error processing task #3: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration_

PLUS: if i restart the computer cuckoo should be running on i always get "could not bind the result server"; this works after i run the following:

If the hostonly interface vboxnet0 does not exist already.
$ VBoxManage hostonlyif create

 Configure vboxnet0.
$ VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1 --netmask 255.255.255.0_

even tho the seen gui-vm-settings are like "vboxnet0" "hostonly"...

cuckoo log comes up with:

_2018-06-20 11:03:31,718 [cuckoo.core.guest] DEBUG: windows7: not ready yet
2018-06-20 11:03:33,725 [cuckoo.core.guest] DEBUG: windows7: not ready yet
2018-06-20 11:03:34,730 [cuckoo.core.guest] DEBUG: windows7: not ready yet
2018-06-20 11:03:35,734 [cuckoo.core.guest] DEBUG: windows7: not ready yet
2018-06-20 11:03:35,778 [cuckoo.core.guest] DEBUG: windows7: not ready yet_

Cuckoo setting:

virtualbox.conf:
- mode = headless
- machines = windows7
[windows7]
- label = windows7
- ip = 192.168.56.10
- snapshot = snapshot6

Windows7-Guest setting:
- UAC turned off
- firewall turned off
- updates turned off
- host-only networking
- static ip = 192.168.56.10
- result server is default 192.168.56.1

~ they can ping eachother.
~ i did reset the iptables and configured them again
~ sudo curl 192.168.56.10:8000 ends up with "**no route to host**" so I guess this is what causes the problem probably but i dont know how to solve this.

**Comment by doomedraven** [comment]
if no route to host, than your agent isn't running correctly as ping works, how did you start agent?

**Comment by Emparla** [comment]
I did copy agent.pyw into the windows startup folder

**Comment by doomedraven** [comment]
and did you restart the vm after that?

**Comment by Emparla** [comment]
multiple times by now..^^

**Comment by doomedraven** [comment]
what about `netstat -nlp` inside of windows?

**Comment by Emparla** [comment]
this are the snapshots of netstat -a (active connections)
![virtualbox_windows7_20_06_2018_12_04_55](https://user-images.githubusercontent.com/40424657/41652026-50eb86b6-7482-11e8-946e-9a21894311b9.png)
![virtualbox_windows7_20_06_2018_12_05_10](https://user-images.githubusercontent.com/40424657/41652033-527f122c-7482-11e8-80bc-2e43ce17824a.png)

**Comment by doomedraven** [comment]
so as you can see there is no listening for :8000, mean your agent doesn't start, you need to investigate why

**Comment by Emparla** [comment]
well i didnt start cuckoo web as i took the snapshot, i just realized that and did it again. i now have 0.0.0.0:8000 Listening.

**Comment by doomedraven** [comment]
we speaking about agent not webserver

**Comment by Emparla** [comment]
so there should be something listening for :8000 even if cuckoo web isnt running?

**Comment by doomedraven** [comment]
dude we speak about stuff inside of vm, not the cuckoo server, cuckoo server doesn't have nothing to see here, don't cross the concepts ;)

**Comment by Emparla** [comment]
yeah well thats what my question was about: if i would have started cuckoo web before posting the screenshot you would have seen the listening on :8000.. ^^ sorry for my confusion

**Comment by doomedraven** [comment]
np, try to run agent directly to see if it starts or return an error

**Comment by Emparla** [comment]
curl throws "connection refused"; should the networking icon be connected if the networking is set on host-only?

**Comment by doomedraven** [comment]
yes, see your another screens

**Comment by Emparla** [comment]
ah ye, i took the shot too early, mb.

**Comment by Emparla** [comment]
*edit: forgot to tell curl the :8000; its throwing
"{"message": "Cuckoo Agent!", "version": "0.8", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}" now when windows and python are started, the startup by cuckoo still fails.

**Comment by doomedraven** [comment]
well you need to investigate why, but now at least you know the root of the problem :P

**Comment by Emparla** [comment]
so, virtualbox took a snapshot where the agent wasnt already running. Thx for the aid. :)

**Comment by doomedraven** [comment]
you are welcome, close if solved
