### ISSUE TITLE
Cuckoo install egghatch error =>  packages may not be found!

### ISSUE THREAD

**Issue by secusoc** [cuckoosandbox/cuckoo#2336]
Hello cuckoo's community,

Issue:
####
I follow cuckoo's doc but impossible to install cuckoo (out or in virtualenv) because of "egghatch"

My config: 
########
 OS:	Ubuntu 16.04
	Python 2.7.12
	pip list (in virtualenv)
		pip        10.0.1
		setuptools 39.2.0
		wheel      0.31.1

My command and error:
##################
(venv)$ pip --proxy "xxxxx" install -U cuckoo		
				Collecting cuckoo
				  Using cached https://files.pythonhosted.org/packages/00/b4/7184539cf7c68ad37aa367a6ac9f956cc1fac49bec026248a104d16ff920/Cuckoo-2.0.6.1.tar.gz
				Collecting alembic==0.8.8 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/93/16/d3a04f576a666582da368de60ba09a33e6711377775fd330d0a43bebacc5/alembic-0.8.8.tar.gz
				Collecting androguard==3.0.1 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/0e/eb/278e1bca7c073b25e4bed0fbaa0d5d9caaa3cee6c99cde711f8ff361fa9f/androguard-3.0.1.tar.gz
				Collecting beautifulsoup4==4.5.3 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/cf/9b/8a6891f8c349431ee94669ce592fc375a19d4e3f4273a01a47207c7990b2/beautifulsoup4-4.5.3-py2-none-any.whl
				Collecting chardet==2.3.0 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/7e/5c/605ca2daa5cf21c87690d8fe6ab05a6f2278c451f4ede6456dd26453f4bd/chardet-2.3.0-py2.py3-none-any.whl
				Collecting click==6.6 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/1c/7c/10b4132dd952b6a04e37626258825b8aa8c1eb99545f2eb26a77c21efb55/click-6.6-py2.py3-none-any.whl
				Collecting django==1.8.4 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/7e/c3/2574a681af30d99b8fd60008c3e56f4ab0acad2af70fea6c135b8bff60a2/Django-1.8.4-py2.py3-none-any.whl
				Collecting django_extensions==1.6.7 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/c5/b8/b0a563f18548168492afa9786f2b9d26774d75b578969488effa1f4061c0/django_extensions-1.6.7-py2.py3-none-any.whl
				Collecting dpkt==1.8.7 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/c6/78/3baab9f9cbf06a416e0bdd9b95268abe2b2faab4a1cc6d8ae83251bf915f/dpkt-1.8.7-py2-none-any.whl
				Collecting egghatch==0.2.2 (from cuckoo)
				  Using cached https://files.pythonhosted.org/packages/08/86/e966e2a1821daf3da6ac244cfe13288f13ac092d0da5bd18e57e263c0ae8/egghatch-0.2.2.tar.gz
				  Complete output from command python setup.py egg_info:
					Download error on https://pypi.org/simple/pytest-runner/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
					Couldn't find index page for 'pytest-runner' (maybe misspelled?)
					Download error on https://pypi.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
					No local packages or working download links found for pytest-runner
					Traceback (most recent call last):
					  File "<string>", line 1, in <module>
					  File "/tmp/pip-install-OnqLaq/egghatch/setup.py", line 57, in <module>
						"mock==2.0.0",
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
						_install_setup_requires(attrs)
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
						dist.fetch_build_eggs(dist.setup_requires)
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
						replace_conflicting=True,
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
						replace_conflicting=replace_conflicting
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1053, in best_match
						return self.obtain(req, installer)
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in obtain
						return installer(requirement)
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
						return cmd.easy_install(req)
					  File "/home/admin06n/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
						raise DistutilsError(msg)
					distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

					----------------------------------------
				Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-OnqLaq/egghatch/

No problem to download it:
######################
	$ wget https://files.pythonhosted.org/packages/08/86/e966e2a1821daf3da6ac244cfe13288f13ac092d0da5bd18e57e263c0ae8/egghatch-0.2.2.tar.gz
			Proxy request sent, awaiting response... 200 OK
			Length: 4417 (4,3K) [binary/octet-stream]
			Saving to: ‘egghatch-0.2.2.tar.gz.1’
			egghatch-0.2.2.tar.gz.1         100%[===================>]   4,31K  --.-KB/s    in 0s
			2018-06-21 18:48:35 (77,3 MB/s) - ‘egghatch-0.2.2.tar.gz.1’ saved [4417/4417]

Thanks for your help

**Comment by jbremer** [comment]
Thanks - that was on our TODO list to resolve for upcoming minor version (2.0.6.2). Expect it soon!

**Comment by secusoc** [comment]
Thanks jbremer for your quick answer.
Do i have an alternative to resolve and go ahead ?

**Comment by jbremer** [comment]
Just run `pip install pytest-runner` before doing the rest. I'm actually not sure why it won't get downloaded correctly.

**Comment by secusoc** [comment]
Thanks a lot for your help
Regards

**Comment by jbremer** [comment]
Cuckoo 2.0.6.2 has now been released, avoiding this issue with any future installations. Thanks for reporting.
