### ISSUE TITLE
Where can I find Processing folder?

### ISSUE THREAD

**Issue by thanhtunghcm** [cuckoosandbox/cuckoo#2338]
Hi everyone,

I'm installed Cuckoo but I find out I don't have Processing folder,

So Where can I find Prcessing folder?
Thank you.
Regards.
![image](https://user-images.githubusercontent.com/25952818/41809284-2aef709a-7715-11e8-875e-8aa73aca7e9d.png)

**Comment by doomedraven** [comment]
with processing you mean scripts or where results are stored?

**Comment by thanhtunghcm** [comment]
@doomedraven : 
I wanna access folder: https://github.com/cuckoosandbox/cuckoo/tree/master/cuckoo/processing

**Comment by doomedraven** [comment]
`locate analysisinfo.py`

**Comment by thanhtunghcm** [comment]
Thank you so much @doomedraven
