### ISSUE TITLE
'Critical ErrorUnable to shut 'Window7-64' down or find the machine in its proper state: The virtual machine 'Window7-64' doesn't exist!'

### ISSUE THREAD

**Issue by quantm1366** [cuckoosandbox/cuckoo#2340]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

I have been through the documentation, the agent is installed on the guest, snapshot taken with the agent running on guest, and the agent.py being added to the startup folder, then powered off. I think I have the config below correct, but still getting the error. Am I missing something?

##### My Cuckoo version and operating system are: Cuckoo Sandbox 2.0.6 DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

##### This can be reproduced by: When trying to launch Cuckoo

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui" or "headless". Please refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = eno1

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1

# If remote control is enabled in cuckoo.conf, specify a port range to use.
# Virtualbox will bind the VRDP interface to the first available port.
controlports = 5000-5050

[cuckoo1]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = Window7-64

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = x.x.x.x

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot =Snapshot 1 

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface = eno1

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags = 

# Mostly unused for now. Please don't fill it out.
options = 

# (Optional) Specify the OS profile to be used by volatility for this
# virtual machine. This will override the guest_profile variable in
# memory.conf which solves the problem of having multiple types of VMs
# and properly determining which profile to use.
osprofile = 

[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by littlejob** [comment]
See below - if your VM name is "Window7-64," make sure this is defined in your config. See the below for example.. 

```
# Default network interface.
interface = vboxnet0

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = Window7-64


[Window7-64]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = Window7-64

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

```

**Comment by RicoVZ** [comment]
Hi quantm1366,

Thanks for posting an issue.

What @littlejob says is right. Also can you tell us what the output of `vboxmanage list vms` is? :smile:

**Comment by quantm1366** [comment]
Made the specified changes and still getting:

CuckooCriticalError: Please update your configuration. Unable to shut 'Window7-64' down or find the machine in its proper state: The virtual machine 'Window7-64' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!
$ vboxmanage list vms
"Windows7-64" {622df74a-acd8-470c-8715-7ec2e3628b90}

virtualbox.conf:

[virtualbox]
# Specify which VirtualBox mode you want to run your machines on.
# Can be "gui" or "headless". Please refer to VirtualBox's official
# documentation to understand the differences.
mode = headless

# Path to the local installation of the VBoxManage utility.
path = /usr/bin/VBoxManage
# If you are running Cuckoo on Mac OS X you have to change the path as follows:
# path = /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

# Default network interface.
interface = eno1

# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = Windows7-64

# If remote control is enabled in cuckoo.conf, specify a port range to use.
# Virtualbox will bind the VRDP interface to the first available port.
controlports = 5000-5050


[Windows7-64]
# Specify the label name of the current machine as specified in your
# VirtualBox configuration.
label = Window7-64

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 172.21.0.14

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the VirtualBox MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot =Snapshot 1 

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (vboxnet0 is the interface name):
interface = eno1

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
tags = 

# Mostly unused for now. Please don't fill it out.
options = 

# (Optional) Specify the OS profile to be used by volatility for this
# virtual machine. This will override the guest_profile variable in
# memory.conf which solves the problem of having multiple types of VMs
# and properly determining which profile to use.
osprofile = 


[honeyd]
# For more information on this VM please refer to the "services" section of
# the conf/auxiliary.conf configuration file. This machine is a bit special
# in the way that its used as an additional VM for an analysis.
# *NOTE* that if this functionality is used, the VM should be registered in
# the "machines" list in the beginning of this file.
label = honeyd
platform = linux
ip = 192.168.56.102
# The tags should at least contain "service" and the name of this service.
# This way the services auxiliary module knows how to find this particular VM.
tags = service, honeyd
# Not all services actually have a Cuckoo Agent running in the VM, for those
# services one can specify the "noagent" option so Cuckoo will just wait until
# the end of the analysis instead of trying to connect to the non-existing
# Cuckoo Agent. We can't really intercept any inter-VM communication from the
# host / gateway so in order to dump traffic between VMs we have to use a
# different network dumping approach. For this machine we use the "nictrace"
# functionality from VirtualBox (which is basically their internal tcpdump)
# and thus properly dumps inter-VM traffic.
options = nictrace noagent

**Comment by RicoVZ** [comment]
@quantm1366 Thanks for the update.

How are you starting Cuckoo? Do you use `sudo`? If you do, it will try to find your VM on the `root` user, instead of your own user. So if using `sudo`, try it without.

**Comment by littlejob** [comment]
You also changed the default IP for your guest VM on the cuckoo instance. 
On your Win7 host, did you confirm your IP is actually 172.21.0.14? And is this statically set on your host? Or did you run the vboxmaange commands to create the vlan/adapter? 

You should be able to ping the win7 host form your cuckoo box, when powered up..

**Comment by quantm1366** [comment]
not running as root, running as the same user that owns vm's

**Comment by quantm1366** [comment]
I statically set the vbox guest, and I can ping back and forth between the guest and the host

**Comment by littlejob** [comment]
Is the vbox guest powered down prior to starting cuckoo? If you run in developer mode, do you see the vbox guest initializing and restoring the snapshot you have defined? This may also be a long shot, but is your snapshot name exactly "Snapshot 1"? Maybe try to rename without a blank space? or put in quotes? 
<p>
Once again... a long shot... but based on the info you have provided... things should be working..

**Comment by RicoVZ** [comment]
@quantm1366 I read the error and your config again. There seems to be a typo in your `label` field. It says `label = Window7-64`. It should be `label = Widows7-64`. The **s** is missing.

**Comment by quantm1366** [comment]
HOLY CRAP. A Typo. RicoVZ way to pay attention to detail!

**Comment by littlejob** [comment]
@quantm1366 - this was a new issue - you did not have "Window7-64" in your config prior to me suggesting to modify your entries. I still suspect it was your config file, your VM name did not match what you had defined. :)

regardless, I am glad it is working now!!

**Comment by quantm1366** [comment]
I had actually gone back and forth between the two places cuckoo1 was on the first config and having it set to Windows7-64, the one thing I never switched around before posting was the label = Window7-64 variable. But yes, who cares. It starts now...now if I could just get it to analyze, lol.

**Comment by quantm1366** [comment]
This issue can be closed, I opened a separate issue for the analysis problems. Thank you all so much for your help!!

**Comment by doomedraven** [comment]
Its your issue you can close it
