### ISSUE TITLE
Android Configurations

### ISSUE THREAD

**Issue by Cry0k** [cuckoosandbox/cuckoo#2343]
Hi guys,

Could you please provide me with a step by step android configuration because i tried many time and had to reinstall the whole cuckoo due to mistakes I've did while trying to configure the android analysis.
also could you please advise from where can i download a reliable AVD for the analysis?

Best Regards,
Alex.

**Comment by zentavr** [comment]
@Cry0k - I had used to set up https://github.com/idanr1986/cuckoo-droid for that. It works with cuckoo 1.2

**Comment by Cry0k** [comment]
@zentavr thanks do u know by any chance if it works with cuckoo 2.0.6?

**Comment by zentavr** [comment]
I had setup the cuckoodroid which is based on 1.2 version of cuckoo.

**Comment by Cry0k** [comment]
ok thanks i'll try to run it on cuckoo 2.0

**Comment by Cry0k** [comment]
@zentavr the problem is that i also run windows analysis so i must have the lastest version of cuckoo if you can tag someone from the cuckoo devs it would be awsome

**Comment by zentavr** [comment]
We do Windows, Linux, OS X and Android.

We have 2.x setups for Windows/Linux and 1.2 for Android. OS X we try to set up with Cuckoo 2.0.6, but still no luck.

We use Virtualenv in order to share the different packages at the same box.

**Comment by Cry0k** [comment]
@zentavr could you please send me a documentation to how properly configure the two sandboxes on Virtualenv?
and is it possible to reconfigure my 2.0.6 sandbox to work on Virtualenv or do i have to reinstall it? 
Because i tried to configure it but something went wrong especially with the Java for some reason it always gives me some errors..

**Comment by zentavr** [comment]
@Cry0k - could you remind me: do you have the problem with setting up the guest OS or the host system?

In the organization which needs the set up we use ansible to prepare the nodes and some manual work to bake the guests.

**Comment by Cry0k** [comment]
@zentavr hi so can you help me with some working documentations that i can use to set up the virtual env android analysis ?

**Comment by zentavr** [comment]
@Cry0k if you will submit a PR to the cuckoodroid project as the result - we can do that.
Unfortunately I have not too much free time, but lets try. You can find me on Telegram with the same nickname as on Github and lets coordinate our efforts there.

I speak English, Russian and Ukrainian.
