### ISSUE TITLE
CRITICAL: CuckooConfigurationError: The configuration value '~/Documents/tmp' found for cuckoo:cuckoo:tmppath is invalid. Please update your configuration!

### ISSUE THREAD

**Issue by marcmuta** [cuckoosandbox/cuckoo#2344]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:
(venv) my_name_and_computer_name:~$ cuckoo 

 Cuckoo Sandbox 2.0.6
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

2018-06-26 10:51:02,811 [cuckoo] CRITICAL: CuckooConfigurationError: The configuration value '~/Documents/tmp' found for cuckoo:cuckoo:tmppath is invalid. Please update your configuration!

**Comment by RicoVZ** [comment]
Hi marcmuta,

Thanks for posting an issue.

The error is probaly thrown because what you specified is not a full path. :smile:  In the config, full paths should be used. So `/home/<youruser>/Documents/tmp`, instead of `~/Documents/tmp`.

**Comment by marcmuta** [comment]
But if you read the comments above well. I did not put that there. The ~/Document/tmp was auto generated. I have the setting to just /tmp which is what the documentation directs to do.

**Comment by RicoVZ** [comment]
@marcmuta That is odd, this does not seem to be somewhere in the code. 

> My aim is not to go to the /home//Documents/tmp but to go to the actual /tmp directory in linux

In that case, you can leave it empty (`tmppath =`). Cuckoo should automatically determine the tmp folder for your operating system.

**Comment by marcmuta** [comment]
To resolve this issue I was able to just use the locate fucntions
thus I located the cuckoo.conf file to see where it has the tmppath = ~/Document/tmp
And I found the confi file to be in the opt/cuckoo/conf/cuckoo.conf dir
Thus just sudo nano /opt/cuckoo/conf/cuckoo.conf
and changed tmppath = /tmp and now all works
