### ISSUE TITLE
Cuckoo with KVM won't start due to interface not found

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#2350]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:

cuckoo

> 2018-07-02 12:39:37,905 [cuckoo] CRITICAL: CuckooConfigurationError: Configuration value kvm:kvm:interface not present! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.

ip a

> 3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
>     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
>        valid_lft forever preferred_lft forever

kvm.conf
> [kvm]
> machines = win10
> 
> [win10]
> label = win10
> platform = windows
> ip = 192.168.122.101
> snapshot = snapshot1
> interface = virbr0
> tags = windows_10,64_bit,acrobat_reader,java,office

##### My Cuckoo version and operating system are:

Ubuntu 16.04.4
Cuckoo 2.0.6.2

##### This can be reproduced by:

Starting cuckoo after configuring for KVM

##### The log, error, files etc can be found at:

Error presents itself when starting cuckoo from the command line.

**Comment by doomedraven** [comment]
it looks like mised in kvm in `[kvm]` interface = virbr0

**Comment by hackdefendr** [comment]
Doh! Yeah that seems to have done it.  Thanks!
