### ISSUE TITLE
How to write our machinery module for openstack or azure?

### ISSUE THREAD

**Issue by rajksbth** [cuckoosandbox/cuckoo#2352]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by doomedraven** [comment]
check PRs there is one for openstack

**Comment by RicoVZ** [comment]
Hi @rajksbth 

I believe @doomedraven is referring to this PR: https://github.com/cuckoosandbox/cuckoo/pull/1585

See https://cuckoo.sh/docs/customization/machinery.html for more information on how to create machinery modules.

**Comment by rajksbth** [comment]
Thanks @RicoVZ @doomedraven . I have written my own machinery module for openstack with the help of the mentioned PR.
