### ISSUE TITLE
run-detectors: unable to find an interpreter

### ISSUE THREAD

**Issue by azfarhalim** [cuckoosandbox/cuckoo#2353]
Hi my issue is i cant submit the malware to analyze using command line

My cuckoo version 1.3-NG

when i run this command -
cuckoo@debian:~$ sudo /opt/cuckoo/utils/submit.py /home/cuckoo/Desktop/807d2dff72386e72bb07f9945a4fbd317eeb35e96357c143020e97a1e11434b4 

this error is popped up
run-detectors: unable to find an interpreter for /opt/cuckoo/utils/submit.py

**Comment by azfarhalim** [comment]
@doomedraven err i dont understand.

**Comment by doomedraven** [comment]
here is cuckoo v2 repo, here is https://github.com/spender-sandbox/cuckoo-modified your cuckoo version

**Comment by azfarhalim** [comment]
@doomedraven OMG IM SORRY
