### ISSUE TITLE
moloch with cuckoo integration

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2361]
My issue is:
cuckoo blocked in Executed reporting module "JsonDump" when moloch is enabled.

My Cuckoo version and operating system are:
version : 2.0.5
OS : ubuntu 16.04

**Comment by RicoVZ** [comment]
Hi rayenmessaoudi,

Thanks for posting an issue.

Mhm, that seems odd. :sweat_smile: 

Cuckoo blocks, as in it freezes when running JsonDump? Does this happen for all analyses? If not, please also share any files (or their hashes) you were analyzing. :smile: 

Can you share your `reporting.conf` with us and tell us how much disk space you have left?

**Comment by rayenmessaoudi** [comment]
[feedback]
# Automatically report errors that occurred during an analysis. Requires the
# Cuckoo Feedback settings in cuckoo.conf to have been filled out properly.
enabled = no

[jsondump]
enabled = yes
indent = 4
calls = yes

[singlefile]
# Enable creation of report.html and/or report.pdf?
enabled = no
# Enable creation of report.html?
html = no
# Enable creation of report.pdf?
pdf = no

[misp]
enabled = yes
url = http://127.0.0.1:5000/
apikey = OWx4WTlfhvfl1xV0hddhGmOJWzg8RbokExTMNANC

# The various modes describe which information should be submitted to MISP,
# separated by whitespace. Available modes: maldoc ipaddr hashes url.
mode = maldoc ipaddr hashes url

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
# MongoDB authentication (optional).
username = 
password = 

[elasticsearch]
enabled = no
# Comma-separated list of ElasticSearch hosts. Format is IP:PORT, if port is
# missing the default port is used.
# Example: hosts = 127.0.0.1:9200, 192.168.1.1:80
hosts = 127.0.0.1
# Increase default timeout from 10 seconds, required when indexing larger
# analysis documents.
timeout = 300
# Set to yes if we want to be able to search every API call instead of just
# through the behavioral summary.
calls = no
# Index of this Cuckoo instance. If multiple Cuckoo instances connect to the
# same ElasticSearch host then this index (in Moloch called "instance") should
# be unique for each Cuckoo instance.
index = cuckoo

# Logging time pattern.  This sets how elasticsearch creates indexes
# by default it is yearly in most instances this will be sufficient
# valid options: yearly, monthly, daily
index_time_pattern = yearly

# Cuckoo node name in Elasticsearch to identify reporting host. Can be useful
# for automation and while referring back to correct Cuckoo host.
cuckoo_node = 

[moloch]
enabled = yes
# If the Moloch web interface is hosted on a different IP address than the
# Cuckoo Web Interface then you'll want to override the IP address here.
host = localhost:8005
# If you wish to run Moloch in http (insecure) versus https (secure) mode,
# set insecure to yes.
insecure = yes

# Following are various configurable settings. When in use of a recent version
# of Moloch there is no need to change any of the following settings as they
# represent the defaults.
moloch_capture = /data/moloch/bin/moloch-capture
conf = /data/moloch/etc/config.ini
instance = cuckoo

[notification]
# Notification module to inform external systems that analysis is finished.
# You should consider keeping this as very last reporting module.
enabled = no

# External service URL where info will be POSTed.
# example : https://my.example.host/some/destination/url
url = 

# Cuckoo host identifier - can be hostname.
# for example : my.cuckoo.host
identifier = 

[mattermost]
enabled = no

# Mattermost webhook URL.
# example : https://my.mattermost.host/hooks/yourveryrandomkey
url = 

# Cuckoo host URL to make analysis ID clickable.
# example : https://my.cuckoo.host/
myurl = 

# Username to show when posting message
username = cuckoo

# What kind of data to show apart from default.
# Show virustotal hits.
show_virustotal = no

# Show matched cuckoo signatures.
show_signatures = no

# Show collected URL-s by signature "network_http".
show_urls = no

# Hide filename and create hash of it
hash_filename = no
# Hide URL and create hash of it
hash_url = no

**Comment by RicoVZ** [comment]
@rayenmessaoudi Thanks for sharing the config. Can you run process/reporting for a task that locks again and post the full log?

Also, please try executing this command and post back the output and if it froze or not.
`/data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -r <PCAP path of freezing task> -n cuckoo`

**Comment by rayenmessaoudi** [comment]
@RicoVZ Thanks for your answer i fixed the issue with moloch but still have a problem to see report.

to see moloch result cuckoo redirect me to this link http://localhost:8000/analysis/moloch/ip//////
error 404.

this is the log file 
https://gist.github.com/rayenmessaoudi/7bde836f3b58d467b377d6aa0f801e7a
and this is the result of your command 
https://gist.github.com/rayenmessaoudi/cec3c144bb6a27ada8ec21ab0b60b994

**Comment by RicoVZ** [comment]
@rayenmessaoudi Good to see you fixed it! :smile: And thanks for posting the output.

In your config, I see you filled in `host = localhost:8005`. If moloch runs on the same machine, the `host = ` field should be empty. :smile: Assuming your moloch is running on the same machine, change the host field to `host = `. After that, restart Cuckoo web.

**Comment by rayenmessaoudi** [comment]
Thank you :) problem solved
