### ISSUE TITLE
Cuckoo Forwarding Rules & "VM hasn't been able to contact back to the Cuckoo Host" error

### ISSUE THREAD

**Issue by saxenakanishk** [cuckoosandbox/cuckoo#2366]
##### My issue is:
Questions I want to ask.

1. What is the difference between the commands in the two photos attached below?
2. What is the purpose of running these commands? Is it for my VM to connect to internet? because I guess that is done via a NAT adapter.
3. Which of these 2 set of commands should I execute? because I am getting error [attached at last] and I guess it is due to these commands only.
4. Without running these commands I am able to ping from host to guest successfully. Why is that?

At first I just blindly copied these commands and ran it. After that I wasn't able to use Wired or Wireless network on my computer. Then I tried to reset the iptables and changed some configurations of the Network Manager file. Now sometimes my internet works fine but sometimes it shows that I am connected to the internet but it doesn't work. So I am trying to understand what these commands do and to execute them properly.

**INSTRUCTIONS FROM ORIGINAL DOCUMENTATION -**

![screenshot from 2018-07-11 18-42-01 1](https://user-images.githubusercontent.com/19509131/42573893-f1012dae-853a-11e8-9c39-30a2a6eabbaa.png)

**INSTRUCTIONS FROM SOME RANDOM BLOG -**
(Please enlarge the photo)

![screenshot from 2018-07-11 18-43-30](https://user-images.githubusercontent.com/19509131/42573903-f6247e44-853a-11e8-99bb-7dd15365b7bb.png)

##### My Cuckoo version and operating system are:
Cuckoo Version - 
Cuckoo Sandbox 2.0.6

Operating System -
Host - Ubuntu 18.04 LTS (Bionic Beaver) 
Guest (VM) - Windows 7 Ultimate SP1 - x64 bit.

**ifconfig details (my port is enp0s25 and NOT eth0) -**

![screenshot from 2018-07-11 19-25-11](https://user-images.githubusercontent.com/19509131/42576710-a963e2a6-8540-11e8-8633-a90e132de69a.png)

##### The log, error, files etc can be found at:
![upload_new](https://user-images.githubusercontent.com/19509131/42575623-a182a754-853e-11e8-8d90-bb5660d2d6ed.png)

I don't know much about iptables. So please help with proper commands which I should execute to remove all the above mentioned errors. Thanks in advance.

**Comment by doomedraven** [comment]
Try to comment out drop rules

**Comment by saxenakanishk** [comment]
@doomedraven Sorry, I didn't get you. What are drop rules?

**Comment by doomedraven** [comment]
In rooter.py

**Comment by saxenakanishk** [comment]
Check rooter.py file here - http://pasted.co/bb5d392e

**Comment by doomedraven** [comment]
Im on vacation with phone so maybe someone will can help you

**Comment by RANGERBEE** [comment]
I am running into this issue and have spent a whole day working it. Found all the other closed tickets with some variant of a solution relating to networking , iptables, vboxnet0, etc.

I have it all set clean, no iptables, vboxnet0 only for the hostOnly net, and no firewalls anywhere. i have reboot the server also and restartex virtualbox. 9Virtualbox 4.x)

Any ideas? I am so tired of It - looking to revert back to old version 2.03 with my hacked together inetsim, nginx and iptables that works.
