### ISSUE TITLE
How many guest VMs does a Cuckoo host supports?

### ISSUE THREAD

**Issue by giveitatry168** [cuckoosandbox/cuckoo#2368]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:

This is a question only. How many guest VMs does a Cuckoo host support? Thanks.

**Comment by RicoVZ** [comment]
Hi giveitatry168,

Thanks for posting an issue.

There is no limit to how many guest VMs Cuckoo supports. You can add as many as you want (as long as your hardware can run it). :smile:

**Comment by giveitatry168** [comment]
Thanks!
