### ISSUE TITLE
Cuckoo only injects child processes

### ISSUE THREAD

**Issue by BlueCh** [cuckoosandbox/cuckoo#2371]
##### My issue is:
To test Cuckoo's new extracting module we prepared a test sample which consist of embedding an Word file which contains DDE to pptx file as OLE object. Winword process did not execute from Powerpoint. As Cuckoo only injects to child processes, word file's DDE behaviour didn't appear on the report.

##### My Cuckoo version and operating system are:
Cuckoo version is 2.0.5 and runs on Ubuntu 16.04.

##### This can be reproduced by:
This is the app.any.run analysis result, you may download the sample from this site.
https://app.any.run/tasks/7acc399f-0e49-4adc-b516-db2dc3333c26

##### The log, error, files etc can be found at:
Cuckoo results:
No child processes in the behaviour report:
![emb1](https://user-images.githubusercontent.com/7416119/42637508-053af16a-85f4-11e8-8f3e-3d162702877d.png)

Calculator can be seen in the analysis screenshot:
![calc](https://user-images.githubusercontent.com/7416119/42637423-d3e70838-85f3-11e8-8223-916a42e61e13.jpeg)

**Comment by raveneous** [comment]
Same with services, COM objects...
