### ISSUE TITLE
How to upgrade/update right?

### ISSUE THREAD

**Issue by belia2** [cuckoosandbox/cuckoo#2372]
First i have to admid again its not a real issue but may it help others (who may dont see the obvious like me? =)
i saw the new update on the web page. -> snapshot the whole system.

##### My issue is:
so looked into the docs and some threads and found this: 
`pip update -U cuckoo`
it did something but on the dashboard is still the red box whats telling me im on 2.0.5 and 2.0.6 is available
i guess this is only an option if i installed cuckoo via pip . and not if you installed it from file (downloaded from the web page.) so if i did the latter, i think i also have to update from file. right? 
(The next step, import the CWD is very well explained and I think it can not done wrong - so that's not part of the actual question - btw this doc can be found [here!](https://docs.cuckoosandbox.org/en/latest/installation/upgrade/))

(if this is normal behaivor a single yes is more than enough =) 
[i think more of people who can not easily save their system - and desperately consider what they should do exactly =)]

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.5
OS: Linux Debian 8

**Comment by doomedraven** [comment]
Just restart all cuckoo services

**Comment by RicoVZ** [comment]
Hi belia2,

Thanks for posting an issue.

`pip install -U cuckoo` is the correct way of upgrading Cuckoo, it should also work if you have installed it using the setup.py from the download.

Is your setup in a virtualenv?

**Comment by jbremer** [comment]
Closing for lack of additional information - feel free to reopen if you have an update for us.
