### ISSUE TITLE
ImportError: No module named lib.cuckoo.core.rooter

### ISSUE THREAD

**Issue by nice9uy** [cuckoosandbox/cuckoo#2379]
I want to active InetSim Routing in cuckoo and setting Using Per-Analysis Network Routing.
When I run it, cuckoo needs to active Cuckoo Rooter with command cuckoo rooter --sudo. 

I got the problem with this. 

in according to https://github.com/spender-sandbox/cuckoo-modified/issues/121 i need to active vpn. 
when i add library to cuckoo/lib/cuckoo/core/startup.py (cuckoo@cuckoo-lab:~/cuckoo-env/lib/python2.7/site-packages/cuckoo/core$ )
and add some scripts i got error like this

(cuckoo-env) cuckoo@cuckoo-lab:~$ cuckoo 
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-env/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/home/cuckoo/cuckoo-env/local/lib/python2.7/site-packages/cuckoo/main.py", line 15, in <module>
    from cuckoo.apps import (
  File "/home/cuckoo/cuckoo-env/local/lib/python2.7/site-packages/cuckoo/apps/__init__.py", line 5, in <module>
    from .apps import (
  File "/home/cuckoo/cuckoo-env/local/lib/python2.7/site-packages/cuckoo/apps/apps.py", line 34, in <module>
    from cuckoo.core.startup import init_console_logging
  File "/home/cuckoo/cuckoo-env/local/lib/python2.7/site-packages/cuckoo/core/startup.py", line 14, in <module>
    from lib.cuckoo.core.rooter import rooter, vpns
ImportError: No module named lib.cuckoo.core.rooter
(cuckoo-env) cuckoo@cuckoo-lab:~$

My questions are
1) I can not find cuckoo/cuckoo.py
2) I can not find cuckoo/web/submission/views.py 
3) I can not find web/templates/submission/index.html

can you help me, where are locate folder/file or i have to create each file of them?

Thanks.

**Comment by doomedraven** [comment]
lol cuckoo-mod != cuckoov2, the structure is totally different now, use `locate filename_here`
which cuckoo do you use?

**Comment by nice9uy** [comment]
Cuckoo 2.0.6

**Comment by jbremer** [comment]
You can't just copy files around from one project to another ;-) What is the problem with existing functionality as provided by Cuckoo 2.0.6?

**Comment by nice9uy** [comment]
Oh i see, thanks  @jbremer @doomedraven
