### ISSUE TITLE
Suricata rules not loading

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2387]
My issue is:
i can't properly integrate suricata with cuckoo.

My Cuckoo version and operating system are:
version : 2.0.5
OS : ubuntu 16.04

log file 
https://gist.github.com/rayenmessaoudi/8d0ad3a0041da31d2092d552c37abdb6

**Comment by Nwinternights** [comment]
Create /etc/suricata/rules/cuckoo.rules:
#echo "alert http any any -> any any (msg:\"FILE store all\"; filestore; noalert; sid:15; rev:1;)"  | sudo tee /etc/suricata/rules/cuckoo.rules
# Edit /etc/suricata/suricata.yaml
# Add " - cuckoo.rules" to the list under "rules-files:"

**Comment by doomedraven** [comment]
and don't forget to restart suricata, or use command from pull requests how to reload ruels without restart suricata

**Comment by rayenmessaoudi** [comment]
i think it's okay now but how i can test suricata with cuckoo ?

**Comment by doomedraven** [comment]
Why not?
