### ISSUE TITLE
malheur 

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2391]
My question is:
I am asking if i can integrate malheur with cuckoo ?

My Cuckoo version and operating system are:
version : 2.0.5
OS : ubuntu 16.04

**Comment by doomedraven** [comment]
you can everything :P but it pretty useless for big amounts of data, takes a lot of time to compare

**Comment by rayenmessaoudi** [comment]
thanks but how ? :p

**Comment by doomedraven** [comment]
```
cd /tmp/
git clone https://github.com/rieck/malheur.git
cd malheur
./bootstrap
./configure --prefix=/usr
make
sudo checkinstall
dpkg -i malheur_0.6.0-1_amd64.deb
```

the rest is here
https://www.adlice.com/cuckoo-sandbox-customization-v2/

**Comment by doomedraven** [comment]
You cant use one plugin on another project, see how all procesing modules are done here and adjust ;)
