### ISSUE TITLE
Cuckoo deployment hardware requirements and performance numbers

### ISSUE THREAD

**Issue by rajiv2790** [cuckoosandbox/cuckoo#2395]
##### My issue is: 

I am planning to deploy a cuckoo instance and would like to know some details on hardware requirements, and the amount of samples it can handle per day. For eg, if I have a machine with 128GB RAM, 8 Cores 2.1 GHZ, is there a way to calculate how many samples I can process approximately. Also, Can one instance of cuckoo analyze multiple binaries in parallel?

**Comment by doomedraven** [comment]
Search in issues that was asked 3 times already ;)

**Comment by jbremer** [comment]
Yes, you can run multiple analyses in parallel. Feel free to experiment with how many VMs are possible. Hint: 1 or 2 per CPU. Closing issue.
