### ISSUE TITLE
Cuckoo windows7 temporary files

### ISSUE THREAD

**Issue by asukaev** [cuckoosandbox/cuckoo#2405]
Hello! I see that in C:/ a temporary folder with preffix "tmp" is created. And after "tmp" there also 6 random chars. Where can I choose other name for this folder? For example "testing" instead of "tmp******".

**Comment by RicoVZ** [comment]
Hi asukaev,

Thanks for posting an issue.

Do you mean on your Cuckoo host or guest VM?

Assuming you mean on your Windows 7 guest VM, this path is where the analyzer is uploaded by default. While you cannot control the random characters (Without modifying the code. 

The Cuckoo agent does support it), you can provide a custom analyzer folder name for on the 'C:\' drive. This is an option that you provide per analysis. The option is called 'analpath'.

If you submit a task with `--options "analpath=something"`. The analyzer will be uploaded to `C:\something`.

**Comment by asukaev** [comment]
@RicoVZ Hello! Thank you for your answer! I meant Windows 7 guest VM and your advice to add "--options ...." worked!
