### ISSUE TITLE
get processing folder path

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2406]
Hi guys,

i m trying to add a new processing module ,i don't understand why os.getcwd() in my python code return the home directory instead of processing folder ?

**Comment by doomedraven** [comment]
bcz it is there where your CWD is, if you could be more specific what you wanna try to do we could help you with that maybe

**Comment by rayenmessaoudi** [comment]
my processing module needs to run external python script in cuckoo/processing/new_folder

**Comment by doomedraven** [comment]
maybe then get `os.path.dirname(os.path.abspath(__file__))` stackoverflow/google can help with that :P

**Comment by rayenmessaoudi** [comment]
same problem
log :
python3: can't open file '/home/user/classifier/checkpe.py': [Errno 2] No such file or directory
os.path.dirname(os.path.abspath(__file__)) return the home directory not the current directory

**Comment by doomedraven** [comment]
first of all, you can't use py3 with python
create better that folder in CWD so later on updated that won't wiped, and you will can use your plugin
