### ISSUE TITLE
runprocessing module for pe files

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2407]
Hi,
i m asking what is the best approach to run processing module & reporting only for pe files ?

**Comment by doomedraven** [comment]
you can trick the code to run processing modules only for pe files https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/core/plugins.py#L176

**Comment by rayenmessaoudi** [comment]
not all processing module just one  that I created

**Comment by doomedraven** [comment]
than on start of your module check file if is a PE if no return
