### ISSUE TITLE
Tesseract and cuckoo

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2408]
Hi ,
i m asking how to see Tesseract result when this feature is enabled with cuckoo ?

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/blob/7329be9aa048c8e33dd9d6da3d0ea95700bd3ba4/cuckoo/processing/screenshots.py

the source can response sometime, but make sure there is no errors in logs
