### ISSUE TITLE
suricata config for cukoo

### ISSUE THREAD

**Issue by rayenmessaoudi** [cuckoosandbox/cuckoo#2410]
Hi ,

i am asking if i need to set the HOME_NET variable in suricata config file to my host only interface ( vboxnet0) to work properly with cuckoo ?

**Comment by doomedraven** [comment]
is depend how/what you want to filter, check suricata man for more details about fields

**Comment by RicoVZ** [comment]
Hi rayenmessaoudi,

What @doomedraven says. Also, Cuckoo itself does not care about how that is set. Cuckoo uses suricata by feeding it a pcap file.

I would suggest setting HOME_NET to your Cuckoo VM subnet, as it is the actual home subnet.
