### ISSUE TITLE
when i run cuckoo,A mistake has been made

### ISSUE THREAD

**Issue by Raul1718** [cuckoosandbox/cuckoo#2421]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
when i run cuckoo,open 127.0.0.1:8000 in my browser,a mistake  has been made.
##### My Cuckoo version and operating system are:
My Cuckoo version is the latest version.And my system is Ubuntu 16.04.
##### The log, error, files etc can be found at:
[02/Aug/2018 15:13:20] "GET /static/images/next.png HTTP/1.1" 304 0
[02/Aug/2018 15:13:20] "GET /static/images/loading.gif HTTP/1.1" 304 0
[02/Aug/2018 15:13:20] "GET /static/images/close.png HTTP/1.1" 304 0
[02/Aug/2018 15:13:20] "POST /analysis/api/tasks/recent/ HTTP/1.1" 200 13
2018-08-02 15:13:20,239 [django.request] ERROR: Internal Server Error: /cuckoo/api/status
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/utils.py", line 55, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/cuckoo/api.py", line 45, in status
    temp_file = Files.temp_put("")
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/files.py", line 97, in temp_put
    prefix="upload_", dir=path or temppath()
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/tmp/cuckoo-tmp-root/upload_EG3vyq'
[02/Aug/2018 15:13:20] "GET /cuckoo/api/status HTTP/1.1" 500 12976

The picture is as follows:
[![QQ_20180802225236.png](https://s22.postimg.cc/rq21vcxn5/QQ_20180802225236.png)](https://postimg.cc/image/mrejgttu5/)

**Comment by doomedraven** [comment]
user?version?

**Comment by Raul1718** [comment]
@doomedraven My Cuckoo version is the latest version.And my system is Ubuntu 16.04.
And system user is root.

**Comment by doomedraven** [comment]
what if you restart webgui? is that still fails? it might be related what you run some of the cuckoo services with different user

as if you check it fails due to permissions(0600) on folder X

**Comment by Raul1718** [comment]
@doomedraven restart many times.It's still fails.
what is 'folder X'?
and how can i check??

**Comment by doomedraven** [comment]
read your error where " no such file or directory...."

**Comment by RicoVZ** [comment]
Hi Raul1718,

Restarting Cuckoo web will likely solve this issue. I suspect the upload dir got deleted while Cuckoo web was still using it.

Note: we do not recommend running any Cuckoo processes (except Cuckoo Rooter) as root.

**Comment by Raul1718** [comment]
@RicoVZ 
Hi RicoVZ，
I have restarted my Cuckoo web,The error is as follows:
[QQ_20180808171215.png](https://postimg.cc/image/fx3i44n1z/)
Still can't find the uoload directory.

**Comment by Raul1718** [comment]
@RicoVZ 
Hi RicoVZ， 
I have restarted my Cuckoo web,The error is as follows:
[![QQ_20180808171215.png](https://s15.postimg.cc/gmmaghnln/QQ_20180808171215.png)](https://postimg.cc/image/fx3i44n1z/)
Still can't find the uoload directory.

**Comment by RicoVZ** [comment]
@Raul1718

What are the permissions on the /tmp folder? Can you post the output of `ls -lah /`?
Also, can you try to manually create the `/tmp/cuckoo-tmp-ubuntu` folder, restarting Cuckoo web after that and then submitting again?

**Comment by jbremer** [comment]
Please run `cuckoo` or `cuckoo -d` before running `cuckoo web`. Closing as resolved for now, although we should perhaps also `mkdir()` on `cuckoo web`. Last but not least, don't run Cuckoo as `root`.

**Comment by codelh7** [comment]
> Please run `cuckoo` or `cuckoo -d` before running `cuckoo web`. Closing as resolved for now, although we should perhaps also `mkdir()` on `cuckoo web`. Last but not least, don't run Cuckoo as `root`.
I solve it in this way!
Thank U!
