### ISSUE TITLE
Agent Not Responding

### ISSUE THREAD

**Issue by k142094** [cuckoosandbox/cuckoo#2423]
Thanks for creating an issue! But first: did you read our community guidelines? Yes, of course
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
2018-08-03 09:41:55,451 [cuckoo.processing.debug] ERROR: Error processing task #3: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration

##### My Cuckoo version and operating system are:
running cuckoo version 2.0.6
host OS Ubuntu 18.04
guest OS windows 7 x86
running under Virtual Box 5.2.16

##### This can be reproduced by:
doing exactly as the docs suggest on ubuntu 18.04
i have been able to ping from the vm to host and vice versa
i have already setup my ip tables as mentioned in the simple routing page of the docs
##### The log, error, files etc can be found at:
configs:
https://shrib.com/#auxiliary.conf
https://shrib.com/#cuckoo.conf
https://shrib.com/#memory.conf
https://shrib.com/#processing.conf
https://shrib.com/#reporting.conf
https://shrib.com/#virtualbox.conf

logs: (cuckoo -d)
https://shrib.com/#cuckoo%20-d

**Comment by k142094** [comment]
alive?

**Comment by k142094** [comment]
reopening a new one

**Comment by doomedraven** [comment]
no! your problem is your empty values in configs! they overwrites generic one, comment them out or fill correctly!

**Comment by k142094** [comment]
ill try that!

**Comment by k142094** [comment]
tried it nothing changed

**Comment by doomedraven** [comment]
try https://github.com/cuckoosandbox/cuckoo/pull/2132
