### ISSUE TITLE
false positive and whitelist IP

### ISSUE THREAD

**Issue by secusoc** [cuckoosandbox/cuckoo#2427]
Hello,

My conf:
Host = Ubuntu 16.04
Cuckoo 2.0.6 

In "summary" for every analysis, i always have 3 signatures rely to my Python's agent and not linked to the file:
```

**HTTP traffic contains suspicious features which may be indicative of malware related traffic** 
	suspicious_features 	POST method with no referer header, Connection to IP address 	suspicious_request 	POST http://127.0.0.1:8000http://127.0.0.1:8000/status
	suspicious_features 	Connection to IP address 	suspicious_request 	GET http://10.10.10.2http://10.10.10.2/

**Performs some HTTP requests (2 events)**
	request 	POST http://127.0.0.1:8000http://127.0.0.1:8000/status/
	request 	GET http://10.10.10.2http://10.10.10.2/

**Sends data using the HTTP POST Method (1 event)**
	request 	POST http://127.0.0.1:8000http://127.0.0.1:8000/status
```
	
I try to put 127.0.0.1 and 10.10.10.2 in domain whitelist but don't change anything.
In auxiliary.conf i use bpf =  !(ip.addr == 127.0.0.1) but error in summary "unable to stop auxiliary module: sniffer

How could i hide this requests (whitelist IP, whitelist user-agent Python Urllib...?)

Thanks

PS: In #1493: "you shouldn't use the nictrace option, that one is capturing all nic traffic" 
But i don't use this option

**Comment by doomedraven** [comment]
in which interface do you sniff? i not have this problem

**Comment by secusoc** [comment]
Hi dommedraven, 

Thanks for quick answer

Don't specify interface in virtualbox.conf
```
[Win7]
label = Win7
...
interface = 
```

or in auxiliary.conf
```
[sniffer]
enabled = yes
tcpdump = /usr/sbin/tcpdump
bpf = 
```

**Comment by doomedraven** [comment]
why not? you should!

**Comment by secusoc** [comment]
Ok i do not know it was necessary.
What interface do you define: internet's one or vboxnet0 ?
And you put it only on virtualbox.conf ?

**Comment by doomedraven** [comment]
if you using host only use vboxnet0 yes, it is there by default, so someone removed if from your conf i think, or my memory failing to me

**Comment by secusoc** [comment]
I check my conf and i have an interface = vboxnet0 in 3rd line but not in my VM parameter

Here was my vitualbox.conf
```
[virtualbox]
mode = headless
path = /usr/bin/VboxManage
interface = vboxnet0
machines = Win7
controlports = 5000-5050

[Win7]
label = Win7
platform = windows
ip = 192.168.56.10
snapshot = snap_win
interface = 
resultserver_ip = 192.168.56.1
resultserver_port = 2042


```
I add interface = vboxnet0 in [win7]  but got the error "unable to stop auxiliary module: sniffer"

**Comment by doomedraven** [comment]
if you not setting value, comment it out to use the general one, never leave empty values

**Comment by secusoc** [comment]
I delete "interface =  " in VM parameter but always the same signature as my first post 

[virtualbox]
mode = headless
path = /usr/bin/VboxManage
interface = vboxnet0
machines = Win7
controlports = 5000-5050

[Win7]
label = Win7
platform = windows
ip = 192.168.56.10
snapshot = snap_win
resultserver_ip = 192.168.56.1
resultserver_port = 2042

**Comment by easyboy72** [comment]
@doomedraven: How do I whitelist the urls in signature? Where is the signature path? I need to add the urls to the signatures. Thank you.

**Comment by doomedraven** [comment]
@secusoc weird, my suggestion remove .cuckoo folder and recreate all configs, something is broken in configs

@easyboy72 seach here by name under which that urls popups en webgui
https://github.com/cuckoosandbox/community/tree/master/modules/signatures/windows

**Comment by easyboy72** [comment]
Sorry I am not exactly sure what I am going to searching in the link. I am completely new to this , you mentioned webgui, I am not sure if you are referring to the Cuckoo report in the web gui interface. Please tell me where the signature is located in the cuckoo directory and where to add the urls that I want to whitelist. Below is the result of the analysis. 
 **Signatures**
 HTTP traffic contains suspicious features which may be indicative of malware related traffic (2 events)
suspicious_features	POST method with no referer header	suspicious_request	POST https://update.googleapis.com/service/update2?cup2key=8:730400011&cup2hreq=8ce72bd4c313593fed54a93b55049dfc960a1eef3a4f16987c16763afe31ce4e
suspicious_features	POST method with no referer header	suspicious_request	POST https://nexus.officeapps.live.com/nexus/upload/%7b2562DF1E-6DF5-4134-9D61-350F670CBB85%7d
 Performs some HTTP requests (12 events)
request	HEAD http://officecdn.microsoft.com/pr/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/v32_16.0.9126.2259.cab
request	HEAD http://officecdn.microsoft.com.edgesuite.net/pr/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/v32_16.0.9126.2259.cab
request	GET http://officecdn.microsoft.com/pr/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/v32_16.0.9126.2259.cab
request	GET http://officecdn.microsoft.com.edgesuite.net/pr/7ffbc6bf-bc32-4f92-8982-f9dd17fd3114/Office/Data/v32_16.0.9126.2259.cab
request	POST https://update.googleapis.com/service/update2?cup2key=8:730400011&cup2hreq=8ce72bd4c313593fed54a93b55049dfc960a1eef3a4f16987c16763afe31ce4e
request	GET https://nexusrules.officeapps.live.com/nexus/rules?Application=officec2rclient.exe&Version=16.0.9126.2259&ClientId=%7bA3B082AF-932C-492F-929E-5D92505DE7C8%7d&OSEnvironment=10&MsoAppId=37&AudienceName=Production_DC&AudienceGroup=Production&AppVersion=16.0.9126.2259&
Potentially malicious urls found in the pocess memory dump (50 out of 557 events)
url	http://www.e-szigno.hu/RootCA.crt0
url	http://ns.adobe.com
![cuckoo-urls](https://user-images.githubusercontent.com/31357730/43741773-1b74d964-9995-11e8-89f8-0a11789b7eee.JPG)
/Acrobat/RSS/Reviews/:reviewID
url	http://static-global-s-msn-com.akamaized.net/hp-eus/_h/4c59fa2c/webcore/externalscripts/jquery/jquery-1.11.1.min.js
url	http://static-global-s-msn-com.akamaized.net/img-resizer/tenant/amp/entityid/AAgE5hz.img?h=16
url	http://static-global-s-msn-com.akamaized.net/img-resizer/tenant/amp/entityid/BBs8kB2.img?h=250
Thank you for your time, I really appreciate it.

**Comment by doomedraven** [comment]
@easyboy72 see `Potentially malicious URLs were found in the process memory dump` you put it in search and getting https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/memdump_urls.py

**Comment by easyboy72** [comment]
@ doomedraven: Thank you for your response, I still did not know how you were able to match he signature. But I do like to whitelist the urls. Please guide me through the steps I should take to whitelist the urls in a layman terms. I appreciate your help and time.

**Comment by doomedraven** [comment]
see in yellow in screen what yo posted `Potentially malicious URLs were found in the process memory dump` <- now open file which i mentioned and see description, tadan, magia :P

**Comment by secusoc** [comment]
Hello Doomedraven,

I delete and reinstall cuckoo and modify conf as you tell (interface = xxx) 
No more false positive in signature
You can close the case (solution1 = no interface empty) (solution2 = resintall .cuckoo)

Thanks a lot for you precious help
Regards

**Comment by doomedraven** [comment]
is your issue you can close it. i don't have permission to close. No empty values at all, they breaking ;)

**Comment by secusoc** [comment]
1) No empty values in virtualbox.con
2) Delete and reinstall cuckoo => No more false positive in signature
Thanks doomedraven

**Comment by secusoc** [comment]
Sorry doomedraven i was to quick

"No more false positive" in signature because there were no signatures 
After doing $ cuckoo community, and reload an analysis => same false positive than before.

Then reinstall cuckoo and no "interface=" were not the solution

When i check in Network analysis
```
POST -> 301 http://127.0.0.1:8000http://127.0.0.1:8000/status
	REQUEST
		POST http:			//127.0.0.1
		Accept-Encoding:	        identity
		Content-Length:		        32
		Host:				127.0.0.1
		Content-Type:		        application/x-www-form-urlencoded
		Connection:			close
		User-Agent:			Python-urllib/2.7
		
	RESPONSE
		:			        HTTP/1.1 301 Moved Permanently
		Server:				Security-Appliance
		Location:			http
		Connection:			Close

GET -> 0 http://10.10.10.2http://10.10.10.2/
	REQUEST
		GET http:			//10.10.10.2/ HTTP/1.1
		Accept-Encoding:	        identity
		Host:				10.10.10.2
		Connection:			close
		User-Agent:			Python-urllib/2.7
		
	RESPONSE
              (empty)

```
Hopes it help!

**Comment by doomedraven** [comment]
idk, you have something bad in your setup, you need to dig and find it

**Comment by secusoc** [comment]
Exclude host and localhost in proxy to be sure python's agent not use proxy to communicate with cuckoo

Thanks to doomedraven
