### ISSUE TITLE
cuckoo monitor folder contains malware

### ISSUE THREAD

**Issue by cuckoo-linux** [cuckoosandbox/cuckoo#2428]
Kindly tell function of monitor in latest cuckoo?

**Comment by doomedraven** [comment]
ROFL, if malware.so on vt is original monitor, then ignore it,  monitor does hooks etc, so many can consider it as malware bcz it invasive

**Comment by cuckoo-linux** [comment]
[monitor.zip](https://github.com/cuckoosandbox/cuckoo/files/2265530/monitor.zip)
this is my monitor.

**Comment by doomedraven** [comment]
i won't analyze it, but if you doubt, remove and do `cuckoo community` to get the clean one, and if your spark still detect it, you have 2 ways, ignore it or remove spark :D

**Comment by cuckoo-linux** [comment]
virus total scan detects **36/58** for monitor.zip
And after cuckoo community when i re analyzed it it shows **36/60**
i removed spark but what about virus total??:)

**Comment by RicoVZ** [comment]
@cuckoo-linux 
>i removed spark but what about virus total??:)

Cuckoo is a malware analysis sandbox. It uses various techniques similar to malware to track process behavior. This only happens inside your guest virtual machines (the VMs Cuckoo uses to run submitted files on). The Cuckoo monitor is the component that does this for Windows analysis.

When you submit a file, Cuckoo starts it inside a VM. While starting it, the Cuckoo monitor is injected into the started process.

It should be detected by anti virus solutions. It has abilities like injecting into processes, API hooking, etc. The files for the Cuckoo monitor can be downloaded and updated by running `cuckoo community`.

To read more about it, see https://cuckoo-monitor.readthedocs.io/en/latest/

These are the latest monitor files: https://github.com/cuckoosandbox/community/tree/master/data/monitor/e071e63a66e831163a40abc45109fdf71fee829e

**Comment by jbremer** [comment]
Closing issue as resolved.
