### ISSUE TITLE
Which virtual machine will cuckoo sandbox select to run samples if it runs several machines including windows XP,windows7 32bit,windows7 64bit and linux?

### ISSUE THREAD

**Issue by douwanhu** [cuckoosandbox/cuckoo#2434]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by doomedraven** [comment]
it will pick first free, if you want to specify an exact, use tags in configs to send to correct vm

**Comment by douwanhu** [comment]
Thank you very much
