### ISSUE TITLE
 Internal Server Error for url: http:/192.168.56.101:8000/mkdtemp

### ISSUE THREAD

**Issue by daleprice10** [cuckoosandbox/cuckoo#2435]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at: attached in the ticket.
[cuckoo.log](https://github.com/cuckoosandbox/cuckoo/files/2277952/cuckoo.log)
[conf.zip](https://github.com/cuckoosandbox/cuckoo/files/2277953/conf.zip)

**Comment by RicoVZ** [comment]
Hi daleprice10,

Thanks for posting an issue.

What is the OS of your guest VM? And are you running the Cuckoo Agent as administrator?

**Comment by daleprice10** [comment]
Thank you so much for your response. The Cuckoo Agent was not running as an administrator. 

I misunderstood guest. I thought that I had to enable the guest account and assign the guest account the adminstrator's role. No, the guest VM is my Windows 7 VM and the account used to access the VM must be an administrator.

The software is working really well. Please close this issue.

Best.

**Comment by daleprice10** [comment]
The software is working as expected. The tool is great.
