### ISSUE TITLE
VirtualBox agent.py in Cuckoo Startup Error

### ISSUE THREAD

**Issue by SubhasisMukh** [cuckoosandbox/cuckoo#2438]
##### My issue is:
I am new to the Malware Analysis field. I installed Cuckoo and VirtualBox and did all the necessary configuration that is required. However the problem I am facing is that when I run cuckoo after submitting an exe file, I have to run the **agent.py** file manually in **VirtualBox**. I have pasted the agent.py file in the startup folder of the Windows 7(in VirtualBox), also made a .bat file which runs the agent.py file and placed it in the startup folder. What may be the problem that the agent.py is **not starting automatically**? Can anyone help me regarding this?

##### My Cuckoo version and operating system are:
Cuckoo Version: 2.0.5.2
OS in Host: Ubuntu
OS in Guest: Windows 7

**Comment by doomedraven** [comment]
did you reboot the vm after place it there?

**Comment by SubhasisMukh** [comment]
@doomedraven Yes I did so. 
The error I am getting is:
INFO: this is the function which waits for agents to come alive
1534098820.36
1534098820.36
1534098820.37
1534098820.38
1534098820.39
.
.
.
.
.
.
.
.
.
.
.
.
.
1534098820.9
ERROR: Error from machine 'cuckoo': it appears that this virtual machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest.

**Comment by RicoVZ** [comment]
Hi SubhasisMukh,

Thanks for posting an issue.

Can you try making a registry (HKLM) key that automatically starts the Cuckoo agent on boot?
After this, create a new snapshot for your analysis machine following these instructions: https://cuckoo.sh/docs/installation/guest/saving.html#saving-the-virtual-machine

**Comment by SubhasisMukh** [comment]
The error is fixed. It was a network issue which was causing the error. vboxnet0 is used in cuckoo configuration by default. However, in Virtualbox setup, the network adapter was set to vboxnet0, still it was causing the error. After deleting vboxnet1, the error is solved. The new version of VirtualBox takes vboxnet1 as default, and does not works even it is changed to vboxnet0 (didn't work for me atleast)

If you get this error, try deleting vboxnet1. After that in Windows 7/XP in the VM, run cmd and type ipconfig. Put the same IPV4 address of ipconfig in the virtualbox.conf file of cuckoo. Hopefully your problem will be resolved.

**Comment by doomedraven** [comment]
thanks for updates about that vboxnet1
