### ISSUE TITLE
A couple yara questions.

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2443]
My questions:

1.  When are yara rules loaded?  So...for example, after starting cuckoo, can I put additional rules in the memory directory and have it work?

2.  Does symlinking work in the yara directory, or do the files there need to be legit files.

I'm asking because I wasn't able to get some rules to work after trying the above.  Thank you!

**Comment by doomedraven** [comment]
1. 
https://github.com/cuckoosandbox/cuckoo/blob/32c9026f80fd93b1f9c4877a2d89f79ba2bec604/cuckoo/main.py#L150
https://github.com/cuckoosandbox/cuckoo/blob/fa830a88b6b0d83dff117d2985cc8ab03e0b98f5/cuckoo/core/startup.py#L201

basically it started in processing, so if you updated yaras, you need restart processing module

2. no idea, you can try it, but you will need restart processing module anyway

**Comment by DigiAngel** [comment]
Thanks as always my friend...I'll run some test and see :)
