### ISSUE TITLE
error running cuckoo

### ISSUE THREAD

**Issue by fadhilkadir** [cuckoosandbox/cuckoo#2445]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:

New to this :(

**Comment by doomedraven** [comment]
omg why the .cwd is in that path and not in $HOME?
+ you didn't specified how you executed so there i suppouse is the bug

**Comment by fadhilkadir** [comment]
apologies for not being clear.

it was my second time running the cuckoo command.

i did: cuckoo --cwd ~/.cuckoo

then i ran: cuckoo

then that error came up :/

**Comment by doomedraven** [comment]
so no error with --cwd?

**Comment by fadhilkadir** [comment]
no errors. then when i ran just cuckoo, the no such file error came out.

On the other hand, I've re-installed - using the guide from cuckoo.sh - and got a different error: unable to bind ResultServer. I guess its the vb. At least its a different issue :) 

anyways, thanks!

**Comment by doomedraven** [comment]
can't bind is bcz interface/port isn't available

**Comment by jbremer** [comment]
If you create your own Cuckoo package, please run `python setup.py sdist` before `pip install -e .`. Closing issue as resolved.
