### ISSUE TITLE
Cuckoo not working with Internet (cuckoo rooter routing)

### ISSUE THREAD

**Issue by Mokatsu** [cuckoosandbox/cuckoo#2446]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I am trying to utilize cuckoo rooter to allow the internet to my VM (but at this time I only have 1 interface (Eth0)). I can use Drop, Inetsim, None Options fine but when I use the Internet, no traffic gets through. 

##### My Cuckoo version and operating system are:
Host: Ubuntu 16.04
Guest: Windows 7
Cuckoo version: 2.0.6

##### This can be reproduced by:
No internet every time I select internet routing from either configuration file or web UI

##### The log, error, files etc can be found at:
No error logs except for the iptables output before/and during analysis.
BEFORE:
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED

Chain FORWARD (policy DROP)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination    
DURING:
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     tcp  --  192.168.1.120        192.168.1.1          tcp dpt:5841
DROP       all  --  192.168.1.120        anywhere            

Chain FORWARD (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  192.168.1.120        anywhere            
ACCEPT     all  --  anywhere             192.168.1.120       

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  192.168.1.1          192.168.1.120        tcp dpt:8000
DROP       all  --  192.168.1.120        anywhere   
DURING with packet count:
Chain INPUT (policy ACCEPT 34 packets, 2040 bytes)
 pkts bytes target     prot opt in     out     source               destination         
54286  354M ACCEPT     all  --  any    any     anywhere             anywhere             state RELATED,ESTABLISHED
   12   624 ACCEPT     tcp  --  any    any     192.168.1.120        192.168.1.1          tcp dpt:5841
  135 26966 DROP       all  --  any    any     192.168.1.120        anywhere            

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  vboxnet0 eth0    192.168.1.120        anywhere            
    0     0 ACCEPT     all  --  eth0   vboxnet0  anywhere             192.168.1.120       

Chain OUTPUT (policy ACCEPT 4557 packets, 920K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 3406 4047K ACCEPT     tcp  --  any    any     192.168.1.1          192.168.1.120        tcp dpt:8000
    0     0 DROP       all  --  any    any     192.168.1.120        anywhere  

Summary:
Even though the forward policy is accpeting traffic from my VM somehow it never gets forwarded, it is getting dropped at the INPUT, Any help would be appreciated.

Other Configs: Forwarding is on, and /etc/iproute2/rt_tables is set to eth0

**Comment by Mokatsu** [comment]
cuckoo rooter log: 

`2018-08-23 11:03:00,052 [cuckoo] INFO: Starting Cuckoo Rooter (group=cuckoo)!
2018-08-23 11:03:28,940 [cuckoo.apps.rooter] DEBUG: Processing command: nic_available eth0 
2018-08-23 11:03:28,944 [cuckoo.apps.rooter] DEBUG: Processing command: drop_enable 192.168.1.120 192.168.1.1 5841 
2018-08-23 11:03:28,956 [cuckoo.apps.rooter] DEBUG: Processing command: forward_enable vboxnet0 eth0 192.168.1.120 
2018-08-23 11:03:28,962 [cuckoo.apps.rooter] DEBUG: Processing command: srcroute_enable main 192.168.1.120 
2018-08-23 11:05:42,298 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable vboxnet0 eth0 192.168.1.120 
2018-08-23 11:05:42,310 [cuckoo.apps.rooter] DEBUG: Processing command: srcroute_disable main 192.168.1.120 
2018-08-23 11:05:42,321 [cuckoo.apps.rooter] DEBUG: Processing command: drop_disable 192.168.1.120 192.168.1.1 5841 `

**Comment by doomedraven** [comment]
Try comment out the drop rules and try again

**Comment by Mokatsu** [comment]
Where would I do that? the rooter.py?

**Comment by doomedraven** [comment]
yes

**Comment by SparkyNZL** [comment]
So I have got this working on 18:04. But not with TOR.

if u issues the following IPtables rules

iptables -A FORWARD -o eth0 -i vboxnet0 -s 192.168.56.0/24 -m conntrack
--ctstate NEW -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
sysctl -w net.ipv4.ip_forward=1

This allowed the internet work work from the VW's in virtualbox.

**Comment by doomedraven** [comment]
i make tor works with commenting our drop rules

**Comment by doomedraven** [comment]
@SparkyNZL but that without rooter!, with roouter did you finally try disable drop?

**Comment by SparkyNZL** [comment]
thats with rooter going.

**Comment by Mokatsu** [comment]
I disabled the drop rules within rooter, and when I ran a test analysis (even when I selected Internet routing) it utilized my inetsim service.

**Comment by doomedraven** [comment]
I dont have pc here but check rooyer there only few drop rulez all of them breaks it

**Comment by Mokatsu** [comment]
So commit the actually iptables command not the functions?

**Comment by doomedraven** [comment]
Exactly with few lines you will get rooter back to life

**Comment by SparkyNZL** [comment]
is this for routing TOR taffic ? or normal traffic, I have normal "Out to
the internet" traffic working just with runing cuckoo rooter and some
IPtables rules. But i dont have TOR taffic going :(

A.

**Comment by doomedraven** [comment]
From my last setup i was need to fix internet/tor
