### ISSUE TITLE
HELP) I want to analysis in Physical Machine.

### ISSUE THREAD

**Issue by hiblackbear** [cuckoosandbox/cuckoo#2447]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Physical mahcinery doens't work.

##### My Cuckoo version and operating system are:
Host
- Cuckoo Sandbox version 2.0.1
- Fog project version 1.5.4
Guest
- Windows 7 32bit
- AGENT_VERSION = "0.7"
- python version 2.7.15

##### This can be reproduced by:
Hmmm..... It is very difficult work.

##### The log, error, files etc can be found at:
![1](https://user-images.githubusercontent.com/27399764/44562298-85425180-a748-11e8-896a-1b1ee61f0269.png)
![2](https://user-images.githubusercontent.com/27399764/44562299-85425180-a748-11e8-97f4-03290e1d1219.png)
![3](https://user-images.githubusercontent.com/27399764/44562301-85425180-a748-11e8-9243-dc33d8ad5d3e.png)
![4](https://user-images.githubusercontent.com/27399764/44562302-85dae800-a748-11e8-9c08-a58c73f44b96.png)

**Comment by hiblackbear** [comment]
It works well in a virtual environment.
However, in the physical environment, I don't know if it is right to write even the name of the physical environment like the fog_client.

**Comment by RicoVZ** [comment]
Hi @hiblackbear,

Thanks for posting an issue. At the moment, the physical machinery module is only compatible with the legacy Cuckoo Agent.

That agent can be found here: https://github.com/cuckoosandbox/cuckoo/blob/2.0-rc2/agent/agent.py

**Comment by hiblackbear** [comment]
Thank you very much.
very very Thanks.
