### ISSUE TITLE
CuckooStartupError

### ISSUE THREAD

**Issue by ebolanoso** [cuckoosandbox/cuckoo#2450]
Hi, how you doing?

I have this issue when I try to startup cuckoo:

"CuckooStartupError: The rooter is required but it is either not running or it has been configured to a different Unix socket path. Please refer to the documentation on working with the rooter."

I'm using Cuckoo Sandbox 2.0.6 on Ubuntu 18.04.1 LTS; guest VM on VirtualBox 5.2.18

**Comment by doomedraven** [comment]
`cuckoo -d rooter --sudo ` and in another console start the rest of the services `--help` is your friend ;)

**Comment by doomedraven** [comment]
just in case if you coming from https://github.com/kojibhy/cuckoo-yara-auto and you installed all yaras, prepare for more errors, you can see them in issues by searching `yara` so i suggest to don't integrate it if you want a funcional cuckoo only integrate what you really need

**Comment by ebolanoso** [comment]
Thanks @doomedraven
