### ISSUE TITLE
Adding custom modules

### ISSUE THREAD

**Issue by saranyarajesh** [cuckoosandbox/cuckoo#2451]
Hi,
I would like to get help in adding custom modules in cuckoo. I need to execute my custom code after cuckoo finished the submitted sample analysis. By reading cuckoo docs I came to know that I have to add custom processing module. I have added it and it is not working. Kindly help me on this.
I am using Cuckoo Sandbox 1.2-dev

**Comment by doomedraven** [comment]
Check official documentation for customization , anyway 1.2 is dead now we have 2.0.6

**Comment by saranyarajesh** [comment]
Thanks for your comment. I have already gone through the customization document. Is it because of cuckoo older version? Let me try with cuckoo 2.0.6

**Comment by doomedraven** [comment]
yes 1.2<2.0.6

**Comment by doomedraven** [comment]
that is good article :)

**Comment by jbremer** [comment]
Presumably you have a better understanding now, closing issue as resolved - thanks! Also don't forget to share back modules.
