### ISSUE TITLE
How to snapshot with FOG (running agent.py)

### ISSUE THREAD

**Issue by hiblackbear** [cuckoosandbox/cuckoo#2452]
##### My issue is:
How do I run agent.py and snapshot it?
os capture works well.
But I do not know how to run agent.py and capture it.

##### My Cuckoo version and operating system are:
Fog version is 1.5.4

##### This can be reproduced by:
used fog latest version.(1.5.4)

**Comment by hiblackbear** [comment]
Should I use the snapin function?

**Comment by doomedraven** [comment]
google is a good one ;) 
https://www.oodlestechnologies.com/blogs/Creating-An-Image-In-FOG

**Comment by hiblackbear** [comment]
hmm.. 
OS image capture was great. However, I want to run Agent.py and then capture it.
I need to reboot when capturing, can I capture it without rebooting?

**Comment by hiblackbear** [comment]
I want the snapshot agent.py to run like a virtual machine.
Do I have to run agent.py again after the physical machine has been rebooted by cuckoo host?

**Comment by hiblackbear** [comment]
@doomedraven help plz..

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/blob/c41c7c5cb09416b7cfc6159811792679e20762f2/docs/book/installation/guest_physical/saving.rst

**Comment by hiblackbear** [comment]
@doomedraven 
I wanted to know how to run agent.py.
I thought I would run agent.py and snapshot it like a virtual environment.

I was wrong.
Run the agent.py when the window is running.

I wanted to know how to do it.

It took a long time.

But, I solved the problem.

Thank you.
