### ISSUE TITLE
web interface with nginx and  provide authentication

### ISSUE THREAD

**Issue by ESL482** [cuckoosandbox/cuckoo#2456]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Hi ,
i am new to cuckoo sandbox, i installed cuckoo and it's running fine when i run the cuckoo web runserver my ip_adreess:port but now i want to connect my cuckoo with nginx and i want provide authentication using nginx to access my cuckoo in others system.please suggest

**Comment by RicoVZ** [comment]
Hi ESL482,

Thanks for posting an issue. :smile: 

We have documented the steps to set up Cuckoo with uWSGI and Nginx. This should probably help you get started. https://cuckoo.sh/docs/usage/web.html#uwsgi-setup

The authentication can be achieved with Nginx using htpasss. See https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication

**Comment by ESL482** [comment]
Hi, 
Thanks for above but i am running the cuckoo web by giving command as cuckoo web initially.
now after configuring the files like you said i am getting error like below 

nginx: [emerg] unknown directive "status" in /etc/nginx/sites-enabled/cuckoo:6
nginx: configuration file /etc/nginx/nginx.conf test failed


i don't have any status.html to access cuckoo , i am accessing by giving command cuckoo web

**Comment by doomedraven** [comment]
status referers to string in `etc/nginx/sites-enabled/cuckoo`
 post it here

**Comment by ESL482** [comment]
status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

**Comment by doomedraven** [comment]
is that your nginx config?

**Comment by ESL482** [comment]
no.....below one is my nginx.conf

user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##
	#My custom settings
 
        fastcgi_buffers 8 16k;
        fastcgi_buffer_size 32k;
 
        client_max_body_size 24M;
        client_body_buffer_size 128k;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

**Comment by doomedraven** [comment]
isn't cuckoo generated config
use `cuckoo --help` to generate ngixn and uwsgi configs

**Comment by ESL482** [comment]
may i know that your asking about below files

 for uwsgi
[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = cuckoo
gid = cuckoo
static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
# If you're getting errors about the PYTHON_EGG_CACHE, then
# uncomment the following line and add some path that is
# writable from the defined user.
# env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/cuckoo/.cuckoo







for nginx

upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}
server {
    listen localhost:8000;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
    }
}

**Comment by doomedraven** [comment]
yes this is what you need to use to set uwsgi and nginx + please use code escape when posting code/logs

**Comment by ESL482** [comment]
when i post my query here ,  RicoVZ  commented this 
The authentication can be achieved with Nginx using htpasss. See https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication , so i followed that link

but i got doubt there ,like what i have to give instead of status to access my cucckoo.

**Comment by doomedraven** [comment]
ok if you said what you don't have idea at all you could save time you you and us ;)

that just is an example
add this after `location / {`
```
auth_basic           “Administrator’s Area”;
auth_basic_user_file /etc/apache2/.htpasswd; 
```

**Comment by ESL482** [comment]
Hi , i done the all the part as said but when i run the **cuckoo web** it is giving localhost:8000 , it is opening cuckoo webpage but not asking any credentials to login that page it is directly opening the page.
If i run **cuckoo web runserver 10.201.74.87:8000** ,
it showing like below 

Network Error (tcp_error)
--
A communication error occurred: "Connection refused"
The Web Server may be down, too busy, or experiencing other problems  preventing it from responding to requests. You may wish to try again at a  later time.
For assistance, contact your network support team.
![network error](https://user-images.githubusercontent.com/42828058/44894817-4ba4b400-ad0f-11e8-9ea6-54234f7ada02.png)

**Comment by doomedraven** [comment]
Yes and its correct behavior, as you should use nginx and uwsgi for that and not cuckoo web, plz lear what is uwsgi and nginx

**Comment by ESL482** [comment]
Yes,
But i started the service before cuckoo ,please see below 

c**uckoo@cuckoo-ThinkCentre-M79:~$ sudo ln -s /etc/uwsgi/apps-available/cuckoo-web.ini /etc/uwsgi/apps-enabled/**
[sudo] password for cuckoo: 
ln: failed to create symbolic link '/etc/uwsgi/apps-enabled/cuckoo-web.ini': File exists
**cuckoo@cuckoo-ThinkCentre-M79:~$ sudo service uwsgi restart**
**cuckoo@cuckoo-ThinkCentre-M79:~$ sudo uwsgi**
*** Starting uWSGI 2.0.12-debian (64bit) on [Sat Sep  1 02:58:38 2018] ***
compiled with version: 5.4.0 20160609 on 31 August 2017 21:02:04
os: Linux-4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017
nodename: cuckoo-ThinkCentre-M79
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/cuckoo
detected binary path: /usr/bin/uwsgi-core
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30464
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
The -s/--socket option is missing and stdin is not a socket.

**Comment by ESL482** [comment]
I checked status for uwsgi , but when i restared  nginx it is showing error

c**uckoo@cuckoo-ThinkCentre-M79:~$ sudo service uwsgi status**
[sudo] password for cuckoo: 
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; bad; vendor preset: enabled)
   Active: active (exited) since Sat 2018-09-01 03:48:38 IST; 11min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3599 ExecStop=/etc/init.d/uwsgi stop (code=exited, status=0/SUCCESS)
  Process: 3639 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCESS

Sep 01 03:48:38 cuckoo-ThinkCentre-M79 systemd[1]: Starting LSB: Start/stop uWSG
Sep 01 03:48:38 cuckoo-ThinkCentre-M79 uwsgi[3639]:  * Starting app server(s) uw
Sep 01 03:48:38 cuckoo-ThinkCentre-M79 uwsgi[3639]:    ...done.
Sep 01 03:48:38 cuckoo-ThinkCentre-M79 systemd[1]: Started LSB: Start/stop uWSGI
lines 1-11/11 (END)

**cuckoo@cuckoo-ThinkCentre-M79:~$ sudo service nginx restart**
[sudo] password for cuckoo: 
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
**cuckoo@cuckoo-ThinkCentre-M79:~$ journalctl -xe**
Sep 01 03:57:26 cuckoo-ThinkCentre-M79 gnome-session[2000]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Sep 01 03:57:31 cuckoo-ThinkCentre-M79 polkitd(authority=local)[1053]: Operator of unix-session:c2 successfully authenticated as unix-user:cuck
Sep 01 03:57:43 cuckoo-ThinkCentre-M79 gnome-session[2000]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Sep 01 03:57:48 cuckoo-ThinkCentre-M79 polkitd(authority=local)[1053]: Operator of unix-session:c2 successfully authenticated as unix-user:cuck
Sep 01 03:58:30 cuckoo-ThinkCentre-M79 org.gnome.zeitgeist.Engine[1859]: ** (zeitgeist-datahub:2363): WARNING **: zeitgeist-datahub.vala:212: E
Sep 01 03:59:55 cuckoo-ThinkCentre-M79 sudo[4230]:   cuckoo : TTY=pts/26 ; PWD=/home/cuckoo ; USER=root ; COMMAND=/usr/sbin/service uwsgi statu
Sep 01 03:59:55 cuckoo-ThinkCentre-M79 sudo[4230]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 04:01:07 cuckoo-ThinkCentre-M79 sudo[4274]:   cuckoo : TTY=pts/27 ; PWD=/home/cuckoo ; USER=root ; COMMAND=/usr/sbin/service nginx resta
Sep 01 04:01:07 cuckoo-ThinkCentre-M79 sudo[4274]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 04:01:07 cuckoo-ThinkCentre-M79 systemd[1]: Stopped A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has finished shutting down.
Sep 01 04:01:07 cuckoo-ThinkCentre-M79 systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has begun starting up.
Sep 01 04:01:07 cuckoo-ThinkCentre-M79 nginx[4286]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Sep 01 04:01:07 cuckoo-ThinkCentre-M79 nginx[4286]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Sep 01 04:01:08 cuckoo-ThinkCentre-M79 nginx[4286]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Sep 01 04:01:08 cuckoo-ThinkCentre-M79 nginx[4286]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 nginx[4286]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 nginx[4286]: nginx: [emerg] still could not bind()
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 systemd[1]: nginx.service: Control process exited, code=exited status=1
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 systemd[1]: nginx.service: Unit entered failed state.
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 systemd[1]: nginx.service: Failed with result 'exit-code'.
Sep 01 04:01:09 cuckoo-ThinkCentre-M79 sudo[4274]: pam_unix(sudo:session): session closed for user root
Sep 01 04:01:19 cuckoo-ThinkCentre-M79 sudo[4290]:   cuckoo : TTY=pts/27 ; PWD=/home/cuckoo ; USER=root ; COMMAND=/usr/sbin/nginx -t
Sep 01 04:01:19 cuckoo-ThinkCentre-M79 sudo[4290]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 01 04:01:19 cuckoo-ThinkCentre-M79 sudo[4290]: pam_unix(sudo:session): session closed for user root
lines 2469-2510/2510 (END)

**Comment by doomedraven** [comment]
please use markdown code escape when posting stuff like that

1. uwsgi isn't started, did you do ` sudo service uwsgi start` and then ` sudo service uwsgi status`

**Comment by ESL482** [comment]
Hi,
 the below path is not present & the uwsgi folder also not created in run directory.remaing all configuration and linking is done.  
**/run/uwsgi/app/cuckoo-web/socket**;

**Comment by doomedraven** [comment]
neans uwsgi isn't correctly installed/configured, uwsgi docuemntation is your friend

**Comment by doomedraven** [comment]
now you need to create .ini in `/etc/uwsgi/apps-enabled/cuckoo_wer.ini` and stop and start uwsgi, that all then go for nginx configuration, pretty similar but in nginx folder + always check logs for errors

**Comment by ESL482** [comment]
i followed the all and please look below
$ sudo ln -s /etc/uwsgi/apps-available/cuckoo-web.ini /etc/uwsgi/apps-enabled/
$ sudo service uwsgi start cuckoo-web 
$ cuckoo web --nginx
$ sudo adduser www-data test
$ sudo ln -s /etc/nginx/sites-available/cuckoo-web /etc/nginx/sites-enabled/
$ sudo service nginx start 
 but i am not able to find the above mentioned path and there are no logs file and the log path is there /var/log/uwsgi/app/
 and when i start uwsgi service its fine, but in uwsgi status it is showing below 
test@test-PowerEdge-R710:~$ sudo service uwsgi start
[sudo] password for test: 
test@test-PowerEdge-R710:~$ sudo service uwsgi status
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; bad; vendor preset: enabled)
   Active: active (exited) (Result: exit-code) since Wed 2018-09-05 10:07:38 IST
     Docs: man:systemd-sysv-generator(8)
  Process: 19415 ExecReload=/etc/init.d/uwsgi reload (code=exited, status=1/FAIL

Sep 05 10:07:38 test-PowerEdge-R710 uwsgi[17102]:  * Starting app server(s) uwsg
Sep 05 10:07:38 test-PowerEdge-R710 uwsgi[17102]:    ...done.
Sep 05 10:07:38 test-PowerEdge-R710 systemd[1]: Started LSB: Start/stop uWSGI se
Sep 05 10:17:48 test-PowerEdge-R710 systemd[1]: Started LSB: Start/stop uWSGI se
Sep 05 11:28:07 test-PowerEdge-R710 systemd[1]: Reloading LSB: Start/stop uWSGI 
Sep 05 11:28:07 test-PowerEdge-R710 uwsgi[19415]:  * Reloading app server(s) uws
Sep 05 11:28:07 test-PowerEdge-R710 uwsgi[19415]:    ...fail!
Sep 05 11:28:07 test-PowerEdge-R710 systemd[1]: uwsgi.service: Control process e
Sep 05 11:28:07 test-PowerEdge-R710 systemd[1]: **Reload failed for LSB: Start/sto
Sep 05 12:08:59 test**

**Comment by doomedraven** [comment]
well there is an error as you can see `Process: 19415 ExecReload=/etc/init.d/uwsgi reload (code=exited, status=1/FAIL` you need to investigate, i can't help, what i can suggest is to generate config as this

```
[uwsgi]
    plugins = python
    module = cuckoo.web.web.wsgi
    static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
    env = CUCKOO_APP=web
    env = CUCKOO_CWD=/home/test/.cuckoo
    master = true
    threads = 5
    workers = 1
    manage-script-name = true
    ; if you will use with nginx, comment next line
    socket = 0.0.0.0:800
    pidfile = /tmp/web.pid
    protocol=http
    enable-threads = true
    lazy = true
    timeout = 600
    chmod-socket = 664
    chown-socket = test:test
    gui = test
    uid = test
```

and exec it as `uwsgi --ini filename.ini` it should give you webgui without nginx, may require an improvement, but if you get errors, go to google im pretty sure there tons of solutions

**Comment by ESL482** [comment]
Thanks for help @doomedraven 
i am still struggling with uwsgi  and i searched in google i find some solutions but nothing worked for me, when i check the uwsgi status after starting it is giving like below 

 test@test-PowerEdge-R710:/opt/cuckoo$ sudo service uwsgi status cuckoo-web
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; bad; vendor preset: enabled)
   **Active: active (exited)** since Thu 2018-09-06 13:54:44 IST; 9s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 10227 ExecStop=/etc/init.d/uwsgi stop (code=exited, status=0/SUCCESS)
  Process: 10268 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCES

Sep 06 13:54:44 test-PowerEdge-R710 systemd[1]: Starting LSB: Start/stop uWSGI s
Sep 06 13:54:44 test-PowerEdge-R710 uwsgi[10268]:  * Starting app server(s) uwsg
Sep 06 13:54:44 test-PowerEdge-R710 uwsgi[10268]:    ...done.
Sep 06 13:54:44 test-PowerEdge-R710 systemd[1]: Started LSB: Start/stop uWSGI se
and in /var/nginx/error.log
2018/09/06 15:33:39 [error] 13108#13108: *2 connect() to unix:/run/uwsgi/app/cuckoo-web/socket failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-web/socket:", host: "localhost:8000"
when i access localhost:8000 it showing 302 bad gate way, i think it is because of uwsgi and when i access only localhost it showing like welcome to nginx page 

please someone  in cuckoo community  help me to solve this issue i have to solve this.

**Comment by ESL482** [comment]
Hi , my cuckoo is working fine with authentication now.but i want to know how to set domain name instead of my ip like server_name mydns.com:8000/submit
in my nginx conf , i gave the conf like below
server
{
 listen 80;
server_name mydns.com:8000/submit/;

    # Cuckoo Web Interface
    location / {
         proxy_pass http://localhost:8000;
}
}
can any one suggest how to do that , i followed many sites in google , but still i am unable to access my dns.

**Comment by ESL482** [comment]
Hi , now i configured cuckoo and authentication also working fine.thanks for help.
I just followed the documentation "cuckoosandbox.org" , that fixed all and middle i got some configuration errors regarding nginx and uwsgi .For that also i searched in google and that is also fixed.so i am closing this issue now.

my nginx config
upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}

server {
 #   listen localhost:8000;
 listen IP:8080;

    # Cuckoo Web Interface
    location / {
  
        client_max_body_size 1G;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
      auth_basic          "Authentication Required";
        auth_basic_user_file /etc/apache2/.htpasswd;  
	# time out settings 
  proxy_connect_timeout 400;
  proxy_send_timeout   400;
  proxy_read_timeout   400;
 send_timeout          400;
  proxy_buffer_size    128k;
  proxy_buffers     32 64k;
  proxy_busy_buffers_size 128k;
  proxy_temp_file_write_size 128k; 
   }
}

my uwsgi config 
[uwsgi]
plugins = python
virtualenv = /home/smit/venv
module = cuckoo.web.web.wsgi
uid = smit
gid = smit
static-map = /static=/home/smit/venv/local/lib/python2.7/site-packages/cuckoo/web/static
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/smit/.cuckoo
enable-threads = true
chmod-socket = 660
chown-socket = %(uid):www-data

**Comment by AkhtarKamal1** [comment]
> Hi ESL482,
> 
> Thanks for posting an issue. 
> 
> We have documented the steps to set up Cuckoo with uWSGI and Nginx. This should probably help you get started. https://cuckoo.sh/docs/usage/web.html#uwsgi-setup
> 
> The authentication can be achieved with Nginx using htpasss. See https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication

sir is there any vedio tutorial for this step? please
