### ISSUE TITLE
how i understand the report.json

### ISSUE THREAD

**Issue by noideanopaper** [cuckoosandbox/cuckoo#2458]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:ubuntu16.04  cuckoo 2.0.6

how i find the detail mean of every section in the report.json

what is the apistates?

**Comment by SubhasisMukh** [comment]
@noideanopaper If you understand basic concepts of Computer Science, then you can easily decode the meaning of every line in report.json by simply just googling it. Basically it is a file which provides us information about how the malwares behaved during analysis.

**Comment by jbremer** [comment]
Closing as resolved.

**Comment by firezdog** [comment]
I think it would be valuable to update the documentation to include a brief explanation of the information found in each section of the report.  For instance, references to registry keys are found both when expanding particular items in "processes" and under the "registry keys" sections -- it would be helpful if you explained the distinction between references in the different sections.

**Comment by anandguddu** [comment]
Hi, I'm using Ubuntu 18.04 and Cuckoo 2.0.7 with MongoDB. 

I was trying to understand the sequence of api calls for a particular analysis. While viewing the web interface, under _Behavioral Analysis_ tab, there is a process-wise paginated sequence of api calls being listed with options to filter using categories like _registry_, _file_, _network_ etc. I would like to export that into a file. 

But while viewing the report.json, under apistats, it is simply giving a dictionary of api calls and frequency. I would like to view the time-sorted order of api calls. Should I be digging into the MongoDB or is there a way with the report.json?

**Comment by TStark76** [comment]
Agree with above post, would be nice to know what these reports are telling us
