### ISSUE TITLE
Dynamic Data Exchange turn off

### ISSUE THREAD

**Issue by thegrillmaster** [cuckoosandbox/cuckoo#2460]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
hello, which rule is responsible for detecting Dynamic Data Exchange in Cuckoo? We have some false-positive and would like to turn them off. Thank you

**Comment by doomedraven** [comment]
Go to community repo and do search by thay string

**Comment by thegrillmaster** [comment]
that's it, thank you!

**Comment by doomedraven** [comment]
you are welcome :)
