### ISSUE TITLE
KeyError: 'label' when using linux vritual machine

### ISSUE THREAD

**Issue by xiangdaww** [cuckoosandbox/cuckoo#2461]
im getting this error while trying to use linux virtual machine for analysis, but it works fine when using windows virtual machine.

![image](https://user-images.githubusercontent.com/8286782/44896511-068e7b00-ad2b-11e8-8b06-f924447ace2c.png)

my physical.conf:
![image](https://user-images.githubusercontent.com/8286782/44896597-4ead9d80-ad2b-11e8-98bc-265b0d1a87e1.png)

**Comment by RicoVZ** [comment]
Hi xiangdaww,

Thanks for posting an issue.

I am not entirely sure if you are trying to use virtual machine or physical analysis machines.

Assuming you are using VMs, can you post your full `cuckoo.log`, `cuckoo.conf` and the conf of the machinery other than physical (if you are using a different one).

**Comment by xiangdaww** [comment]
[cuckoo_conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2342118/cuckoo_conf.txt)
[cuckoo_log_.txt](https://github.com/cuckoosandbox/cuckoo/files/2342119/cuckoo_log_.txt)
[virtualbox_conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2342120/virtualbox_conf.txt)

**Comment by RicoVZ** [comment]
@xiangdaww Thanks, I will take a look!
