### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by ESL482** [cuckoosandbox/cuckoo#2471]
Hi, 
when i am opening my localhost:8000 i am getting the **502 Bad Gateway
nginx/1.9.15 (Ubuntu)**
My nginx logs are :

2018/09/10 11:03:00 [error] 13673#13673: *8 **upstream prematurely closed connection while reading response header from upstream**, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-web/socket:", host: "localhost:8000"

My cuckoo-web logs are :`

Mon Sep 10 11:02:15 2018 - SIGINT/SIGQUIT received...killing workers...
Mon Sep 10 11:02:16 2018 - worker 1 buried after 1 seconds
Mon Sep 10 11:02:16 2018 - goodbye to uWSGI.
Mon Sep 10 11:02:16 2018 - *** Starting uWSGI 2.0.12-debian (64bit) on [Mon Sep 10 11:02:16 2018] ***
Mon Sep 10 11:02:16 2018 - compiled with version: 5.4.0 20160609 on 31 August 2017 21:02:04
Mon Sep 10 11:02:16 2018 - os: Linux-4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018
Mon Sep 10 11:02:16 2018 - nodename: test-PowerEdge-R710
Mon Sep 10 11:02:16 2018 - machine: x86_64
Mon Sep 10 11:02:16 2018 - clock source: unix
Mon Sep 10 11:02:16 2018 - pcre jit disabled
Mon Sep 10 11:02:16 2018 - detected number of CPU cores: 8
Mon Sep 10 11:02:16 2018 - current working directory: /
Mon Sep 10 11:02:16 2018 - writing pidfile to /run/uwsgi/app/cuckoo-web/pid
Mon Sep 10 11:02:16 2018 - detected binary path: /usr/bin/uwsgi-core
Mon Sep 10 11:02:16 2018 - setgid() to 1000
Mon Sep 10 11:02:16 2018 - set additional group 4 (adm)
Mon Sep 10 11:02:16 2018 - set additional group 24 (cdrom)
Mon Sep 10 11:02:16 2018 - set additional group 27 (sudo)
Mon Sep 10 11:02:16 2018 - set additional group 30 (dip)
Mon Sep 10 11:02:16 2018 - set additional group 46 (plugdev)
Mon Sep 10 11:02:16 2018 - set additional group 113 (lpadmin)
Mon Sep 10 11:02:16 2018 - set additional group 128 (sambashare)
Mon Sep 10 11:02:16 2018 - setuid() to 1000
Mon Sep 10 11:02:16 2018 - your processes number limit is 31714
Mon Sep 10 11:02:16 2018 - your memory page size is 4096 bytes
Mon Sep 10 11:02:16 2018 - detected max file descriptor number: 1024
Mon Sep 10 11:02:16 2018 - building mime-types dictionary from file /etc/mime.types...Mon Sep 10 11:02:16 2018 - 552 entry found
Mon Sep 10 11:02:16 2018 - lock engine: pthread robust mutexes
Mon Sep 10 11:02:16 2018 - thunder lock: disabled (you can enable it with --thunder-lock)
Mon Sep 10 11:02:16 2018 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/cuckoo-web/socket fd 3
Mon Sep 10 11:02:16 2018 - Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Mon Sep 10 11:02:16 2018 - Python main interpreter initialized at 0x13e0590
Mon Sep 10 11:02:16 2018 - python threads support enabled
Mon Sep 10 11:02:16 2018 - your server socket listen backlog is limited to 100 connections
Mon Sep 10 11:02:16 2018 - your mercy for graceful operations on workers is 60 seconds
Mon Sep 10 11:02:16 2018 - mapped 227968 bytes (222 KB) for 5 cores
Mon Sep 10 11:02:16 2018 - *** Operational MODE: threaded ***
Mon Sep 10 11:02:16 2018 - *** uWSGI is running in multiple interpreter mode ***
Mon Sep 10 11:02:16 2018 - spawned uWSGI master process (pid: 13632)
Mon Sep 10 11:02:16 2018 - spawned uWSGI worker 1 (pid: 13638, cores: 5)
**ImportError: No module named 'cuckoo'**
Mon Sep 10 11:02:16 2018 - unable to load app 0 (mountpoint='') (callable not found or import error)
Mon Sep 10 11:02:16 2018 - *** no app loaded. going in full dynamic mode ***

**my nginx config :**

upstream _uwsgi_cuckoo_web {
   server unix:/run/uwsgi/app/cuckoo-web/socket;
	#server 127.0.0.1:8001;
}

server {
    listen localhost:8000;
    #server_name 10.201.74.46;
    client_max_body_size 75M;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        uwsgi_pass _uwsgi_cuckoo_web;
        include     uwsgi_params;
	fastcgi_buffers 8 128k;
	fastcgi_buffer_size 256k;
	uwsgi_read_timeout 600;
    }
}
**my uwsgi config :**

[uwsgi]
#plugins = python
module = cuckoo.web.web.wsgi
uid = test
gid = test
static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
# If you're getting errors about the PYTHON_EGG_CACHE, then
# uncomment the following line and add some path that is
# writable from the defined user.
# env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/test/.cuckoo
master = true
threads = 5
workers =  1
protocol = http
enable-threads = true
lazy = true
timeout = 600
chmod-socket = 664
#chown-socket = test:test
socket = /run/uwsgi/app/cuckoo-web/socket

my uwsgi status :

● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi; **bad**; vendor preset: enabled)
   Active: active (running) since Mon 2018-09-10 10:43:30 IST; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 12438 ExecStop=/etc/init.d/uwsgi stop (code=exited, status=0/SUCCESS)
  Process: 12589 ExecStart=/etc/init.d/uwsgi start (code=exited, status=0/SUCCES
   CGroup: /system.slice/uwsgi.service
           ├─12699 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini 
           └─12705 /usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini 

Sep 10 10:43:30 test-PowerEdge-R710 systemd[1]: Starting LSB: Start/stop uWSGI s
Sep 10 10:43:30 test-PowerEdge-R710 uwsgi[12589]:  * Starting app server(s) uwsg
Sep 10 10:43:30 test-PowerEdge-R710 uwsgi[12589]:    ...done.
Sep 10 10:43:30 test-PowerEdge-R710 systemd[1]: Started LSB: Start/stop uWSGI se

please help to clear this issue.

**Comment by doomedraven** [comment]
that is uwsgi not cuckoo, issue, google can also help you ;)

**Comment by ESL482** [comment]
#2456
