### ISSUE TITLE
Does cuckoo support analyzing of xx.dmp memory dump.

### ISSUE THREAD

**Issue by AdithyaSankaran** [cuckoosandbox/cuckoo#2472]
I have been trying to parse a memory dump with cuckoo, but I want to first understand whether cuckoo supports parsing of memory dump. I had taken a dump using a dumpit tool by Comae.

Thanks.

**Comment by doomedraven** [comment]
dumpit is proc dump so use yara

**Comment by AdithyaSankaran** [comment]
@doomedraven I am new to Cuckoo Sandbox, please elaborate.

**Comment by doomedraven** [comment]
https://github.com/VirusTotal/yara

**Comment by AdithyaSankaran** [comment]
@doomedraven hey but isn't yara already built into cuckoo sandbox?

**Comment by doomedraven** [comment]
yes, now you can use `search in this repository` by pattern `yara` ;)

**Comment by jbremer** [comment]
DumpIt is completely separate software from Cuckoo. Please read up on what the different tools allow you do. Closing issue.
