### ISSUE TITLE
a problem about cuckoo droid

### ISSUE THREAD

**Issue by GoatYoung** [cuckoosandbox/cuckoo#2479]
why can't  i make a config for an android vm,by the way, can you give some installations way for me,thank you.
![_ls24c56ry0n5dgpb b 6ti](https://user-images.githubusercontent.com/41860150/45627675-08936080-bac5-11e8-8e40-4ecb65bcb490.png)

**Comment by doomedraven** [comment]
cuckoo droid doesn't work with cuckoo, you should use cuckoo-droid for that
