### ISSUE TITLE
Cuckoo Web does not run

### ISSUE THREAD

**Issue by MrVenomous** [cuckoosandbox/cuckoo#2481]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Cuckoo Web not running

##### My Cuckoo version and operating system are:
Cuckoo Sandbox on Windows 10 1803

##### This can be reproduced by:
Cuckoo starts fine. When opening Cuckoo Web I first got this error:

```
H:\>cuckoo web
c:\python27\python.exe: can't open file 'C:\Python27\Scripts\cuckoo': [Errno 2] No such file or directory
```
I then went to C:\Python27\Scripts, copied cuckoo.exe, pasted into the same directory, then renamed to "cuckoo" with no extension.  This gives the following results:

```
H:\>cuckoo web
  File "C:\Python27\Scripts\cuckoo", line 1
SyntaxError: Non-ASCII character '\x90' in file C:\Python27\Scripts\cuckoo on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by RicoVZ** [comment]
Hi @MrVenomous,

Thanks for posting an issue.

Another user seems to have the same problem. You might want to try this answer: https://github.com/cuckoosandbox/cuckoo/issues/2439#issuecomment-412807790

**Comment by jbremer** [comment]
Closing for lack of additional information - feel free to reopen if you have an update for us.

**Comment by Tigzy** [comment]
Hey, I have the exact same issue. Kinda big blocked for me, I've been too far on setting Cuckoo on this machine :/ Any direction to look at?
