### ISSUE TITLE
Cuckoo-Rooter Startup Error

### ISSUE THREAD

**Issue by SubhasisMukh** [cuckoosandbox/cuckoo#2489]
##### My issue is:
In routing.conf whenever I set route=internet and internet=eno1 (this is correct), it gives this error

cuckoo

                      __
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0.6
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

2018-09-20 18:07:48,321 [cuckoo] CRITICAL: CuckooStartupError: The rooter is required but it is either not running or it has been configured to a different Unix socket path. Please refer to the documentation on working with the rooter.

I have internet on my VirtualBox in working state and it is working in every case, but when routing is set to this, it just stops working. What could be the possible solution to this?

Note: The resultserver_ip, port, VM ip port and all are correct, it is working except for this particular case.

##### My Cuckoo version and operating system are:
Cuckoo Version: 2.0.6.2
Cuckoo OS: Ubuntu 18.04
VirtualBox OS: Windows 7

**Comment by doomedraven** [comment]
`cuckoo --help`

**Comment by SubhasisMukh** [comment]
This was easy. Closing the issue. Keeping this if it is helpful to anyone facing this issue.
You just need to type this command in a terminal
sudo cuckoo rooter -g 'Current_Username_where_you_are_using _cuckoo'
and run cuckoo in another terminal.

I am stupid to not try this. Sorry!

**Comment by doomedraven** [comment]
that all is in ___cuckoo documentation!___ RTM

**Comment by emiloo** [comment]
Not sure if anyone still has issues with this, but I found that when I made a typo in routing.conf, it resulted in this error. So you may want to check out your routing.conf if it was recently changed as well.
