### ISSUE TITLE
Extend Report for Url analysis

### ISSUE THREAD

**Issue by vkuehn** [cuckoosandbox/cuckoo#2491]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
           when submitting an url would it be possible to get reported infos about the target url ?
            e.g. Server Version, Meta Tags as generator....
           I have a script to get these information's, is it possible to extend the report ?

##### My Cuckoo version and operating system are:
            2.0.6

**Comment by doomedraven** [comment]
feel free to push PR with improvements :)

**Comment by vkuehn** [comment]
once I know how for sure :-)
