### ISSUE TITLE
Issue with .rtf analysis processing

### ISSUE THREAD

**Issue by LarsBehrens** [cuckoosandbox/cuckoo#2492]
##### My issue is: 
processing analysis with .rtf files. 

##### My Cuckoo version and operating system are:  
2.0.6, ubuntu 18.04, latest agent

##### This can be reproduced by: 
Not entirely sure if this is easily reproducible. 

##### The log, error, files etc can be found: 
In this post. 

So, i've ran into a strange problem. Everything works fine, except analyzing .rtf documents. Basically, on the analysis machine everyting goes according to plan and it finished the execution on the malware VM. During processing it gets stuck somehow. Most of the times around the suricata processing (which is completely finished by looking at the suricata logs, also attached). However it also got stuck at BehaviorAnalysis. 

I can't find a way to debug this error (cuckoo is already running with debugging verbosity). looks like it gets stuck somewhere and keeps the processor on 100%. 

All other analyses (for example .doc and docx) which are also executed on office 2013 32-bit are doing fine and finishes processing within a minute. 

I closed the cuckoo process after an hour and provided all the logs of this incident (storage/analyses/1/*) except the memdumps (due to the size 800mb). can provide if needed. 
I also included three binaries (CAREFUL, THIS IS MALWARE) in the zip file with the password infected.

Hope someone has a clue about whats happening. 
[cuckoo-logs.zip](https://github.com/cuckoosandbox/cuckoo/files/2414635/cuckoo-logs.zip)
[malware-binaries.zip](https://github.com/cuckoosandbox/cuckoo/files/2414636/malware-binaries.zip)

**Comment by doomedraven** [comment]
strace is good for debug or https://github.com/uber/pyflame

do you have have a lot of yaras? the problem could be in static where it uses re instead of re2, on strings i saw that in past

**Comment by LarsBehrens** [comment]
Thanks for the reaction.

I do not have that much yara rules. First thought i had was to get my rules out of the yara folder and have disabled yara processing in the config temporarily. none fixed the problem. Will give pyflame a try, thanks.

If anything poppes to mind, let me know :)

**Comment by doomedraven** [comment]
try tris

install this
```
apt-get install libre2-dev -y
pip install re2
```
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/processing/static.py#L17
modify that to:

```
try:
     import re2 as re
except ImportError:
     import re
```

**Comment by LarsBehrens** [comment]
Fixed for me!

Could've been the code edit above or some config edits.

**Comment by doomedraven** [comment]
So you confirm that is re2 does the trixk?
