### ISSUE TITLE
How does cuckoo recognize an anti-vm virus file

### ISSUE THREAD

**Issue by ChenJhua** [cuckoosandbox/cuckoo#2493]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by doomedraven** [comment]
that is your work, not cuckoo, you should RE/analyze it and set all cuckoo settings

**Comment by ChenJhua** [comment]
Manual analysis? Or cuckoo provides a better setting?

**Comment by doomedraven** [comment]
cuckoo is opensource, so you can configure cuckoo for everything, but for that you need to know all what your malware do, or wait till someone implement that for you lol

**Comment by ChenJhua** [comment]
I see. I'll be waiting for you. Thank you. lol

**Comment by noideal** [comment]
There's already a ton of signatures that detect AntiVM that come included. While doomedraven is right, you do need to tune Cuckoo to your own needs, the default install with the community repo will detect most of this.
