### ISSUE TITLE
Does not ends itself after analysis completed successfully

### ISSUE THREAD

**Issue by SubhasisMukh** [cuckoosandbox/cuckoo#2494]
##### My issue is:
After the analysis is completed cuckoo does not ends itself. It is to be done manually by keyboard interrupt. Is there any way out to end the process automatically after it completes all the analysis?

It stops at this point

###### 2018-09-26 11:19:29,971 [cuckoo.core.scheduler] INFO: Task #6: analysis procedure completed

and a keyboard interrupt is to be made to end the process

###### ^Ccuckoo_special@subhasis-BM1AF-BP1AF-BM6AF:~$ 
Can someone help me with this? @doomedraven @jbremer 

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.6.2

**Comment by doomedraven** [comment]
lol it shouldn't exit, it should be running as it waits for more analysis to process

**Comment by SubhasisMukh** [comment]
It means I will have to kill the process manually if I want it to stop after a certain analysis is completed?

**Comment by doomedraven** [comment]
correct, that not make sense to stop processing, as it should work automatically and process all incoming data

**Comment by SubhasisMukh** [comment]
Well, I wanted to perform some operations after the analysis is completed, like run some python files or so. If the process does not ends, it is not going to the next command in shell file.

**Comment by doomedraven** [comment]
dude and why not to check the cuckoo documentation and add reporting modules which are executed at the end of processing all data?

**Comment by KehindeOloye** [comment]
Hello @SubhasisMukh, how were you able to tackle the problem. I have the same issue and the other commands in my shell script won't run because cuckoo doesn't end itself

**Comment by doomedraven** [comment]
what do you cuckoo cuckoo doesn't end?

**Comment by KehindeOloye** [comment]
I am unable to gain back control of the terminal after the task has completed and so I cannot run any other commands from a shell script

**Comment by doomedraven** [comment]
you want' get it, it isnt' how cuckoo work, read the manual

**Comment by KehindeOloye** [comment]
Isn't there a work around that can help, I'm sure others might have encountered something similar, I do not feel this should be closed as someone might have a useful hint. I have read the manual and it doesn't provide any help with this problem in my opinion

**Comment by doomedraven** [comment]
dude that isn't how cuckoo works at all, cuckoo should be started and not exited, if you want to exec something as post analysis/processing, write processing/reporting module, thats all, if no, jsut do code modification, but which is the sense to exit and start cuckoo over and over? reporting/processing is the key here

**Comment by doomedraven** [comment]
i didnt' close nothing as this isnt my thread, and im didn't say anything __unfriendly__, just told you what cuckoo doen't working in that way as you want to

**Comment by KehindeOloye** [comment]
Thanks so much @SubhasisMukh  for this comprehensive and prompt response. I am very grateful. 

Many thanks.
