### ISSUE TITLE
Volatility problem

### ISSUE THREAD

**Issue by lokibroki** [cuckoosandbox/cuckoo#2497]
I got the memory dump with `Dumpit`, and when I tried to achive this dump profile with `kdbgscan` I encountered with this problem:

> WARNING : volatility.addrspace: Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow

Why does it happening and how do I fix it?
I have vol2.5*

**Comment by doomedraven** [comment]
Ask that in vol repo and google ;)

**Comment by jbremer** [comment]
Also update your Volatility version. Closing for lack of additional information - feel free to reopen if you have an update for us.
