### ISSUE TITLE
How to disable Post-Analysis Lookup

### ISSUE THREAD

**Issue by w0r1dhe110** [cuckoosandbox/cuckoo#2498]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by doomedraven** [comment]
check cuckoo.conf

**Comment by RicoVZ** [comment]
Hi @w0r1dhe110 

Thanks for posting an issue.

To disable this, set the following option in `cuckoo.conf` to `no`

```
# Enable or disable DNS lookups.
resolve_dns = yes
```

**Comment by w0r1dhe110** [comment]
Thanks
