### ISSUE TITLE
Cannot run volatility module: the volatility library is not available. Please install it according to their documentation.

### ISSUE THREAD

**Issue by cyjcyjcyj** [cuckoosandbox/cuckoo#2500]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:
Cuckoo2.0.6 ，Volatility2.6，unbuntu18.0.4，vmware：win7enterprise64

##### The log, error, files etc can be found at:
ERROR: Cannot run volatility module: the volatility library is not available. Please install it according to their documentation.

Except the error above, I can't get any traceback errors. 
I can run vol.py -h successfully.

**Comment by jbremer** [comment]
Hi @cyjcyjcyj, are you running `vol.py` in the same virtualenv/environment as Cuckoo? Can you also do `import volatility` in that same directory?

**Comment by jbremer** [comment]
Did that work for you?

**Comment by cyjcyjcyj** [comment]
I have tried some ways and it seems that the error has disappeared. But I got another error and submitted in #2503.

**Comment by doomedraven** [comment]
well that are different errors, close this one then
