### ISSUE TITLE
Analysis doesn't respond

### ISSUE THREAD

**Issue by gillo89** [cuckoosandbox/cuckoo#2541]
hello everybody, I'm using Cuckoo 2.0.6 on Ubuntu 16.04 LTS. 

I try to start analyses from web interface,  I'm choosing the file I want to analyse and pressing enter but nothing happens.  Cuckoo is still in "waiting for analysis tasks." state.

what could be the reason

**Comment by gillo89** [comment]
Thank's for respond RicoVZ,

Nope there are no tasks pending. 

I'm starting cuckoo and web interface without sudo and without path either.
I'm just typing "cuckoo" and "cuckoo web runserver" in terminal.

**Comment by gillo89** [comment]
I can't start cuckoo from root user, I guess guest vm belongs another user because I'm gating error message   
"CuckooCriticalError: Please update your configuration. Unable to shut 'Windows 7' down or find the machine in its proper state: The virtual machine 'Windows 7' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!"

Can you tell me how can I change vm owner user, or directory where cuckoo and web interface runs?

P.S. sorry if my questions sounds Boring. I'm new user of Linux and just trying to figure out.

**Comment by doomedraven** [comment]
never use cukoo as root user, it will give it a lot of problem, and if that says vm doesn't exist, that means your hypervisor config is incorrect, as root has permission in the whole universe ;)

**Comment by RicoVZ** [comment]
@gillo89 

Not using root is good. As you said, it will cause Cuckoo to use a different cwd, as the user would be different, causing it it also use a different db. Ok, this is not the case now.

> Nope there are no tasks pending.

Curious, what happens when you submit a task through web. Any errors? Do you receive a task id?
Can you also try to submit over command line? 

`cuckoo submit <path to file>`

**Comment by gillo89** [comment]
I don't know how but somehow I made it worse (( and cant run cuckoo any more.

this is message I receive 

Cuckoo Sandbox 2.0.6
 www.cuckoosandbox.org
 Copyright (c) 2010-2018


=== Exception details ===
Cuckoo version: 2.0.6
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 asn1crypto:0.24.0 beautifulsoup4:4.5.3 capstone:3.0.5rc2 cffi:1.11.5 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.3.1 cuckoo:2.0.6.2 distorm3:3.3.0 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 future:0.16.0 html5lib:0.999 httpreplay:0.2.4 idna:2.7 ipaddress:1.0.22 itsdangerous:1.0.0 jdcal:1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 lxml:3.5.0 mako:1.0.7 markupsafe:1.0 olefile:0.43 oletools:0.51 openpyxl:2.3.0 peepdf:0.4.2 pefile2:1.2.11 pillow:3.2.0 pip:8.1.2 py:1.4.31 pycparser:2.19 pycrypto:2.6.1 pycurl:7.43.0 pyelftools:0.24 pyguacamole:0.6 pyliblzma:0.5.3 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:18.0.0 pysqlite:1.0.1 pytest:2.8.7 python-dateutil:2.4.2 python-dmidecode:3.12.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pytz:2014.10 requests:2.13.0 roach:0.1.2 rpm-python:4.12.0.1 scapy:2.3.2 setuptools:36.6.0 sflock:0.3.6 six:1.11.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0 unicorn:1.0.1 unity-lens-photos:1.0 urlgrabber:3.9.1 urllib3:1.24 virtualenv:16.0.0 volatility:2.5 wakeonlan:0.2.2 werkzeug:0.14.1 wheel:0.29.0 yara-python:3.6.3 youtube-dl:2016.2.22 yum-metadata-parser:1.1.4

2018-10-25 15:35:56,036 [cuckoo] ERROR: IOError: [Errno 13] Permission denied: '/home/cuckoo/.cuckoo/pidfiles/cuckoo.pid'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 233, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 125, in cuckoo_init
    pidfile.create()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 229, in create
    with open(self.filepath, "wb") as f:
IOError: [Errno 13] Permission denied: '/home/cuckoo/.cuckoo/pidfiles/cuckoo.pid'

**Comment by doomedraven** [comment]
easy as i todl many times in issues, __NEVER RUN CUCKOO AS ROOT__ you will f**ckup a lot of stuff, nwo you need to fo and change that pid file permission with `sudo chown cuckoo:cuckoo /home/cuckoo/.cuckoo/pidfiles/cuckoo.pid`

**Comment by gillo89** [comment]
OK thank you. it works again ))
