### ISSUE TITLE
URL analysis using a lot of disk space. Cuckoo server with 900GB running out of space in 2 weeks.

### ISSUE THREAD

**Issue by morriscode** [cuckoosandbox/cuckoo#2549]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html
Yes
##### My Cuckoo version and operating system are:

Version | 2.0.6
Ubuntu 16.04.5 LTS

##### This can be reproduced by: Submitting any URL for analysis. For example, I submitted www.google.com, and the results folder shows 762MB. I have configured the memory.conf to delete the dumps after analysis, but that doesn't appear to be happening. 

cuckoo@cuckoo:~/.cuckoo/storage/analyses/4$ du -sh *
20K     analysis.log
4.0K    buffer
28K     cuckoo.log
187M    dump.pcap
187M    dump_sorted.pcap
4.0K    extracted
1.1M    files
8.0K    files.json
2.3M    logs
205M    memory
170M    network
0       reboot.json
12M     reports
192K    shots
76K     suricata
4.0K    task.json
4.0K    tlsmaster.txt

**Comment by doomedraven** [comment]
That are memdumps, clean useless memdumps when you dont need them for exemple crom with find older than 3 hours and delete

**Comment by morriscode** [comment]
Thanks! I just didn't know if there was an option to automatically do this. I cron'd it and it'll work fine! Thanks

**Comment by doomedraven** [comment]
well that "automatic" isn't part of cuckoo ;)
but 
` 0 */3 * * * cd $HOME/.cuckoo/storage/analyses && find */memory.dmp -mmin +180 -delete`
