### ISSUE TITLE
cuckoo doesn't execute malware

### ISSUE THREAD

**Issue by Vidhu211** [cuckoosandbox/cuckoo#2552]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by doomedraven** [comment]
Poor cuckoo then lol, best issue ever n2

**Comment by foolishhare** [comment]
> Poor cuckoo then lol, best issue ever n2

Thats was test issue)

**Comment by doomedraven** [comment]
xDDD yes but after test this should be closed :P
