### ISSUE TITLE
the analysis is not reported as compledted successfully even if there aren't any errors

### ISSUE THREAD

**Issue by Clevero** [cuckoosandbox/cuckoo#2567]
#### My issue is:
The analysis is not reported as "analysis completed successfully" in the log even if there aren't any errors according to Analysis and Cuckoo log of the analysis

#### My Cuckoo version and operating system are:
Cuckoo 2.0.6 on 18.04

#### This can be reproduced by:
1. Submitting the attached clean sample (Guest is Windows 7 x86)

#### The log, error, files etc can be found at:
Sample (clean): [f.docx](https://github.com/cuckoosandbox/cuckoo/files/2628871/f.docx)
Exported analysis: [143.zip](https://github.com/cuckoosandbox/cuckoo/files/2629399/143.zip)
[virtualbox.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2629140/virtualbox.conf.txt)
[cuckoo.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2629141/cuckoo.conf.txt)
[auxiliary.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2629142/auxiliary.conf.txt)
[reporting.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2629143/reporting.conf.txt)
[processing.conf.txt](https://github.com/cuckoosandbox/cuckoo/files/2629144/processing.conf.txt)

I could not find an issue related to mine
Do I have any config errors? Or is there a error in the logs that I oversaw?

**Comment by doomedraven** [comment]
if not reported but completed your system missing
`cuckoo -d process a2` to processs analyzed data

**Comment by Clevero** [comment]
I created a fresh 18.04 VM and installed a new cuckoo instance to reproduce it

Sadly the error persists :/

**Comment by paldana** [comment]
Just to piggy back on this, it's not clear to me what's the difference between completed and reported. From my understanding, it's kind of the same, but we can see the report from the tasks list in the Cuckoo web. But whenever I check the status of my Cuckoo set up, it always shows that there's 1 completed, and the rest are reported. Mind to shed some light on this one @doomedraven?

**Comment by doomedraven** [comment]
Completed is completed analysis in vm
Reported is when processing processed all data generated from data in vm as signatures/reporting modules

**Comment by doomedraven** [comment]
To generate reported from completed start cuckoo -d process a1
cuckoo -h for help

**Comment by Clevero** [comment]
To clarify on my issue:


My files are "reported", they do not hang in "completed". The log just doesn't contain ```analysis completed successfully```
See the log above:
```2018-12-09 00:23:37,252 [cuckoo.apps.apps] INFO: Task #162: reports generation completed```

**Comment by doomedraven** [comment]
they i don't really see an issue, do you use separated processing or cuckoo itself process analyzed data from vm?

**Comment by Clevero** [comment]
I use [PeekabooAV](https://github.com/scVENUS/PeekabooAV) for automated analyses via Cuckoo.

Peekaboo checks if there are any errors during the analysis. Normally reports without errors contain the string "analysis completed successfully", so Peekaboo knows everything is alright. If it doesn't contain the string, the analysis is considered as failed.

But in my case there aren't any errors, but the string "analysis completed successfully" is not in the output

**Comment by doomedraven** [comment]
as you told, that isn't a cuckoo error, that is 3rd party tool error, open issues there

**Comment by Clevero** [comment]
Okay, thanks for your time!

I already opened an issue there, I just thought it could also be possibly a bug on Cuckoo side, because normaly the reports contain "analysis completed successfully"
