### ISSUE TITLE
Cuckoo web with MongoDB error

### ISSUE THREAD

**Issue by Sanch091** [cuckoosandbox/cuckoo#2572]
Hi together,
after starting MongoDB with command /etc/init.d/mongodb start

MongoDB starts, because I receive this message in terminal:
[ ok ] Starting mongodb (via systemctl): mongodb.service.

Trying to start cuckoo web
(Win7) cuckoo@Det-Chamb1:~$ cuckoo web
this error appears:
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

At the host, it is the same error, when I type in the command cuckoo web.

My Cuckoo-Version is 2.0.6.2 (should be latest)
OS Host: Ubuntu 18.10
OS Guest Win 7 and Win 10.

This is my reporting.conf for MongoDB:
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
MongoDB authentication (optional).
username = 
password = 

Request #2154 didn't helped me, sorry.

Thx!

Johannes

**Comment by doomedraven** [comment]
1. start mongo shell to verify what mongo works fine
2. how you execute everything? maybe wrong user or something so it not loading correct $CWD

**Comment by Sanch091** [comment]
1. It seems, that the MongoDB which I installed with help of the Cuckoo Documentation is too old. There is no mongod.conf file, but a mongodb.conf file, which means, that the installation is too old (refer to https://medium.com/mongoaudit/how-to-enable-authentication-on-mongodb-b9e8a924efac   Point 4)
I used commad sudo apt-get install mongodb, which installed version 3.6.3.

Starting Mongo-Shell:
I navigate to the folder, from mongodb (in Home directoy where i unzipped i) and start mongo. This is the result:
MongoDB shell version v3.6.3
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.6.3
Server has startup warnings: 
2018-12-10T14:34:36.379+0100 I STORAGE  [initandlisten] 
2018-12-10T14:34:36.379+0100 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2018-12-10T14:34:36.382+0100 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2018-12-10T14:34:37.742+0100 I CONTROL  [initandlisten] 
2018-12-10T14:34:37.742+0100 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-12-10T14:34:37.742+0100 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-12-10T14:34:37.742+0100 I CONTROL  [initandlisten] 

The default mongodb.conf  is located in /etc/mongodb.conf

2. I execute every command with the cuckoo user (sudoers group)

**Comment by doomedraven** [comment]
no sudo no, never sudoers, well you can create the mongod file

**Comment by Sanch091** [comment]
Ok i removed it. 
Created mongod.conf in /etc/

**Comment by Sanch091** [comment]
So, here an update:
mongod and mongo are running successfully, when typing "mongo" and "mongod" in terminal. 
Confirmation for mongod:
2018-12-12T14:39:01.295+0100 I NETWORK  [initandlisten] waiting for connections on port 27017

Confirmation for Mongo:
MongoDB shell version v3.6.3
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.6.3

In Browser I cant open the database. Proxy is off.
cuckoo web has still he same error.

**Comment by doomedraven** [comment]
did you restart web/cuckoo after that? web won't work that is not a http protocol

**Comment by Sanch091** [comment]
Sorry for the dumb questions but I never worked before with cuckoo / mongodb :)
I restarted cuckoo and cuckoo web after, yes.
I work as follows:
1st terminal: mongod (starts)
2nd terminal: mongo (just for trial) (starts)
3rd terminal: cuckoo (starts)
4th terminal: cuckoo web (error)

How can I open the web interface of cuckoo, when it is not an http based protocol? Some tutorials start the interface with browser as well

**Comment by doomedraven** [comment]
ah i thought you tried to open mongo in browser, my confusion

**Comment by doomedraven** [comment]
Yes looks like is the service problme

**Comment by Sanch091** [comment]
Soooooo
I installed the complete machine new. 
cuckoo runs, mongod and mongo works fine and in the browser I get this notification:
#**"It looks like you are trying to access MongoDB over HTTP on the native driver port."**
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

BUT: if i want to start cuckoo web, this error appears again:
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

The reporting.conf is the same error as mentioned in the topic.

**Comment by doomedraven** [comment]
can you post reporting.conf?

**Comment by Sanch091** [comment]
# Enable or disable the available reporting modules [on/off].
# If you add a custom reporting module to your Cuckoo setup, you have to add
# a dedicated entry in this file, or it won't be executed.
# You can also add additional options under the section of your module and
# they will be available in your Python class.

[feedback]
# Automatically report errors that occurred during an analysis. Requires the
# Cuckoo Feedback settings in cuckoo.conf to have been filled out properly.
enabled = no

[jsondump]
enabled = yes
indent = 4
calls = yes

[singlefile]
# Enable creation of report.html and/or report.pdf?
enabled = no
# Enable creation of report.html?
html = no
# Enable creation of report.pdf?
pdf = no

[misp]
enabled = no
url = 
apikey = 

# The various modes describe which information should be submitted to MISP,
# separated by whitespace. Available modes: maldoc ipaddr hashes url.
mode = ipaddr

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
# MongoDB authentication (optional).
username = 
password = 

[elasticsearch]
enabled = no
# Comma-separated list of ElasticSearch hosts. Format is IP:PORT, if port is
# missing the default port is used.
# Example: hosts = 127.0.0.1:9200, 192.168.1.1:80
hosts = 127.0.0.1
# Increase default timeout from 10 seconds, required when indexing larger
# analysis documents.
timeout = 300
# Set to yes if we want to be able to search every API call instead of just
# through the behavioral summary.
calls = no
# Index of this Cuckoo instance. If multiple Cuckoo instances connect to the
# same ElasticSearch host then this index (in Moloch called "instance") should
# be unique for each Cuckoo instance.
index = cuckoo

# Logging time pattern.  This sets how elasticsearch creates indexes
# by default it is yearly in most instances this will be sufficient
# valid options: yearly, monthly, daily
index_time_pattern = yearly

# Cuckoo node name in Elasticsearch to identify reporting host. Can be useful
# for automation and while referring back to correct Cuckoo host.
cuckoo_node = 

[moloch]
enabled = no
# If the Moloch web interface is hosted on a different IP address than the
# Cuckoo Web Interface then you'll want to override the IP address here.
host = 
# If you wish to run Moloch in http (insecure) versus https (secure) mode,
# set insecure to yes.
insecure = no

# Following are various configurable settings. When in use of a recent version
# of Moloch there is no need to change any of the following settings as they
# represent the defaults.
moloch_capture = /data/moloch/bin/moloch-capture
conf = /data/moloch/etc/config.ini
instance = cuckoo

[notification]
# Notification module to inform external systems that analysis is finished.
# You should consider keeping this as very last reporting module.
enabled = no

# External service URL where info will be POSTed.
# example : https://my.example.host/some/destination/url
url = 

# Cuckoo host identifier - can be hostname.
# for example : my.cuckoo.host
identifier = 

[mattermost]
enabled = no

# Mattermost webhook URL.
# example : https://my.mattermost.host/hooks/yourveryrandomkey
url = 

# Cuckoo host URL to make analysis ID clickable.
# example : https://my.cuckoo.host/
myurl = 

# Username to show when posting message
username = cuckoo

# What kind of data to show apart from default.
# Show virustotal hits.
show_virustotal = no

# Show matched cuckoo signatures.
show_signatures = no

# Show collected URL-s by signature "network_http".
show_urls = no

# Hide filename and create hash of it
hash_filename = no
# Hide URL and create hash of it
hash_url = no

**Comment by doomedraven** [comment]
your mongo config is correct, which port you tried to access and got that msg 8000?

**Comment by Sanch091** [comment]
Oh, you got it? I deleted i :)
I used port 27017 (127.0.0.1:27017 in browser)

**Comment by doomedraven** [comment]
yes i got, no you can't use it, that is mongo "protocol" cuckoo should listen on 8000 (cuckoo -d 
web -H 0.0.0.0 -p 8000)

**Comment by Sanch091** [comment]
maybe you are right.
this is the logfile path: /home/cuckoo/mongodb_logs/mongod.log

but its empty.
I am wondering because mongod and mongo works in my opinion, or am I wrong?

**Comment by doomedraven** [comment]
if you type mongo and you get console then yes, but something is wrong and i don't have access to tell you what iswrong, the log of cuckoo/web is useful also not only mongo

**Comment by Sanch091** [comment]
Is the cuckoo/web log usually in the cwd/log folder? this one is empty as well.

**Comment by doomedraven** [comment]
its in console where you started in aka stdin

**Comment by Sanch091** [comment]
This is the error (log, that you mean?) sorry i am nooby...
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

**Comment by doomedraven** [comment]
no, that you posted already, sorry in this way is hard to help, can you check the reporting.conf if mongo enabled i already forgot lol. and make sure you edit and run in the $CWD of the same user

**Comment by Sanch091** [comment]
IT WORKS! Thanks a fucking lot! the problem was the $cwd!
I close the issue
Thank you very much.

**Comment by doomedraven** [comment]
you are welcome :) you got the cuckoo xmas gift lol :D

**Comment by Sanch091** [comment]
Idd. This is a big gift for me :D

**Comment by VinayKumar-G** [comment]
> IT WORKS! Thanks a fucking lot! the problem was the $cwd!
> I close the issue
> Thank you very much.

Please elaborate! I have the same issue..

**Comment by Abadeolu** [comment]
> IT WORKS! Thanks a fucking lot! the problem was the $cwd!
> I close the issue
> Thank you very much.

Can you Help me with how you solved the $cwd
I have this same issue now.

**Comment by doomedraven** [comment]
`systemct status mongod` or `systemct status mongodb`

**Comment by Abadeolu** [comment]
> systemct status mongod

Unit mongo.service could not be found

**Comment by doomedraven** [comment]
that is your problem, you don't have mongo or installed it incorrectly

**Comment by Abadeolu** [comment]
> that is your problem, you don't have mongo or installed it incorrectly

I guess I need to reinstall it again from the start.

However, I have mongodb enabled in reporting.conf

**Comment by doomedraven** [comment]
enabled != installed/configured

**Comment by Abadeolu** [comment]
Yes, I understand you.
Thanks.
Let me go over it again.

**Comment by doomedraven** [comment]
close another issue

**Comment by BASSEXE** [comment]
> IT WORKS! Thanks a fucking lot! the problem was the $cwd!
> I close the issue
> Thank you very much.

Hi so I'm having the same issue, can you elaborate on what do you mean by $CWD was the issue?

I've edited my report.conf in the same manner,
Enabled mongo db
 and ran the commands in a virtualenvironment venv

**Comment by R42E** [comment]
You have to change the working directory 
`cuckoo` --cwd `/your_Path/cuckoo`, so the datas are in this folder

if you want to start cuckoo, then you have to navigate in the terminal via cd ~/cuckoo (or your path) into the main folder of cuckoo. That is the starting point for cuckoo to run.
