### ISSUE TITLE
Tor routing issues.

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2581]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Tor routing seems off...captures capture the redirected 9040 traffic

##### My Cuckoo version and operating system are:
Latest cuckoo, Debian Stretch

##### This can be reproduced by:
Any run

##### The log, error, files etc can be found at:
My routing.conf tor section:
~~~
[tor]
# Route a VM through Tor, requires a local setup of Tor (please refer to our
# documentation).
enabled = yes
dnsport = 5353
proxyport = 9040
~~~

![2018-12-13 15_46_52-wireshark follow http stream tcp stream eq 2 1cd5dd41a3bf7d6a4dbc472fecac9](https://user-images.githubusercontent.com/947191/49972322-831a2380-feee-11e8-878a-d0b9223b2296.png)
![2018-12-13 15_45_55-cuckoo sandbox](https://user-images.githubusercontent.com/947191/49972323-831a2380-feee-11e8-99b2-95c7f87c3415.png)
![2018-12-13 15_45_41-cuckoo sandbox](https://user-images.githubusercontent.com/947191/49972324-831a2380-feee-11e8-8cce-d3c1948cd912.png)

**Comment by doomedraven** [comment]
i had this issues due to the docker on the same host,

my fix
https://github.com/doomedraven/Tools/blob/master/Networking/fix_iptables.sh

source of fix for me
https://forums.fedoraforum.org/showthread.php?312824-Bridge-broken-after-docker-install&s=ffc1c60cccc19e46c01b9a8e0fcd0c35&p=1804899#post1804899

**Comment by DigiAngel** [comment]
Ok cool..of interest I don't have a br0 interface, but a docker0 one :)  Will test and let you know how it goes thank you.

**Comment by doomedraven** [comment]
well it should be virbr0 if no br0, so yeah is the docker problem, docker breaks everything lol

**Comment by DigiAngel** [comment]
Interesting..here's all the interfaces:
~~~
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255

enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.9  netmask 255.255.255.0  broadcast 192.168.1.255

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.100.1  netmask 255.255.255.0  broadcast 192.168.100.255

virbr0-nic: flags=4098<BROADCAST,MULTICAST>  mtu 1500
~~~
and brctl output:
~~~
bridge name	bridge id		STP enabled	interfaces
docker0		8000.<redacted>c	no		
virbr0		8000.<redacted>c	yes		virbr0-nic
~~~

So I'm assuming I need to change the br0 to docker0 in the script?  And the command would be:
~~~
fix_iptables.sh 192.168.100.0 virbr0 enp0s31f6
~~~
For testing I removed all firewall rules, started cuckoo rooter, and did a test run of a malware....still got the same results, so now I'm confused.  in kvm.conf I have interface = virbr0, I'm starting cuckoo rooter with cuckoo rooter --sudo, but I still see:
![screenshot from 2018-12-28 10-10-25](https://user-images.githubusercontent.com/947191/50522573-deb8e500-0a88-11e9-93d3-5c0fc78e2469.png)

are there any other settings I need to check?  The malware runs as we see...but none of the ids rules fire as 192.168.100.1 is in the same network.  Thank you!

**Comment by doomedraven** [comment]
obviously, it won't match any IDs rules on it as that port is "weird"/not watched. idk i had this issue 1 year ago and that worked for me but i wiped docker on that host after that and no problems, so you will need to investigate on your own this

**Comment by DigiAngel** [comment]
Ok cool...I'll see what I can find and then report my findings.
