### ISSUE TITLE
"storage/analyses/[test#]/network" is empty

### ISSUE THREAD

**Issue by RansomwareThreatHunting** [cuckoosandbox/cuckoo#2596]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

My issue is:
I created a .EXE file that simply pings a domain and shows True or False in Console. Afterward, I submitted my sample to Cuckoo. Cuckoo launched the sample and terminated successfully after 60 seconds timeout. The main problem is that the "network" folder is empty!, however, I have two pcap files in the output folder of Cuckoo (named dump.pcap and dump_sorted.pcap). Note that I can see the ICMP traffics generated by my sample in these two files but these files also contain traffics from other processes while I only want to have traffics generated by my own sample. I think it should be in "network" folder of "storage/analyses/[test#]".

My Cuckoo version: 2.0.6,
operating system are: Ubuntu 16.04 (Host), Win10 (Guest)

**Comment by doomedraven** [comment]
that is your work to disable all vm noise

**Comment by doomedraven** [comment]
https://github.com/doomedraven/Tools/blob/master/Windows/disable_win7noise.bat

or just change tcpdump filters for capturing

**Comment by RansomwareThreatHunting** [comment]
Thank you @doomedraven , I will disable all Windows noises and then the captured network is only generated by testing sample!
