### ISSUE TITLE
Odd Error /w MySQL Driver

### ISSUE THREAD

**Issue by Kolano** [cuckoosandbox/cuckoo#2667]
##### My issue is:
I'm having trouble starting Cuckoo's web interface. It reports the database driver is missing though it seems to be installed; and is reported oddly.

`cuckoo -d web -H 0.0.0.0 -p 8100`
or
`cuckoo web runserver 0.0.0.0:8100`
...both result in...
```
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 573, in web
    Database().connect()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 448, in connect
    self._connect_database(dsn)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/database.py", line 540, in _connect_database
    "Missing unknown database driver, unable to import %s" % lib
cuckoo.common.exceptions.CuckooDependencyError: Missing unknown database driver, unable to import 1)
```

I'm using a MySQL DB...
cuckoo.conf: `connection = mysql://cuckoo:XXX@XXX.XXX.XXX.XXX/cuckoo`

Within the Cuckoo venv, PIP shows the MySQL connector as installed...
```
source ~/cuckoo_ve/bin/activate
pip2 freeze | grep mysql
```
...outputs...
`mysql-connector-python==8.0.15`

Taking a closer look at cuckoo's database.py...
```
        except ImportError as e:
            lib = e.message.split()[-1]

            if lib == "MySQLdb":
                raise CuckooDependencyError(
                    "Missing MySQL database driver (install with "
                    "`pip install mysql-python` on Linux or `pip install "
                    "mysqlclient` on Windows)"
                )

            if lib == "psycopg2":
                raise CuckooDependencyError(
                    "Missing PostgreSQL database driver (install with "
                    "`pip install psycopg2`)"
                )

            raise CuckooDependencyError(
                "Missing unknown database driver, unable to import %s" % lib
            )
```

It would seem that "lib" is expected to be a string and not the "1" seen in the error message.

Any suggestions on the appropriate MySQL connector setup for Cuckoo, or commentary on the odd number returned by the error message would be appreciated.

##### My Cuckoo version and operating system are:
Cuckoo 2.0.6
Ubuntu 18.10

##### This can be reproduced by:
Unclear, I'd need to pare out the Cuckoo install steps from a larger integrated install.

**Comment by Kolano** [comment]
The capitalization is also a bit odd there, it seems everywhere else in code MySQLdb is referenced it's all lower case "mysqldb".

**Comment by Kolano** [comment]
The DB issue was resolved, though I'm unclear what changed specifically to resolve it.

In general I think I'm seeing a problem with Cuckoo not installing into it's virtual environment correctly. For instance the exe is installed to...
/usr/local/bin/cuckoo
...rather than...
/home/XXX/cuckoo_ve/bin/cuckoo
...Supervisor is unable to start Cuckoo due to that, I have a feeling it may result in some Cuckoo config files not being found, which might have also not exposed my database config correctly.

**Comment by vnkazna** [comment]
Unfortunately, I could not resolve this problem.
