### ISSUE TITLE
nginx  in https can't render page completely for cuckoo web

### ISSUE THREAD

**Issue by Raghavendran-Muthusamy** [cuckoosandbox/cuckoo#2669]
##### My Cuckoo version and operating system are: cuckoo latest - 
![screenshot from 2019-02-26 14-01-16](https://user-images.githubusercontent.com/25314387/53452214-4b4b5400-39e6-11e9-8e3c-8cc61d468cba.png)
Ubuntu 16

**Comment by Rooobaaat** [comment]
Without config files no one can help you. We need at least your nginx and uwsgi config.

**Comment by Raghavendran-Muthusamy** [comment]
This is my ngnix config:

server {
    listen 172.16.2.11:443 ssl http2;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;
    # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;
    auth_basic "Login required";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /storage/analysis {
       alias /opt/cuckoo/storage/analyses/;
       autoindex on;
       autoindex_exact_size off;
       autoindex_localtime on;
    }

    location /static {
      alias /opt/cuckoo/web/static/;
    }
}

server {
    listen 172.16.2.11:80;
    return 301 https://$server_name$request_uri;
}



}

# Host the upstream legacy API 
server {
    listen 172.16.2.11:4343 ssl http2;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
   # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Restrict access
       allow 172.16.2.11;
      #allow 192.168.1.0/24;
      deny all;
    }
}

**Comment by Raghavendran-Muthusamy** [comment]
BTW. I have created self signed cert also wondering if that's a reason behind this

**Comment by Rooobaaat** [comment]
What‘s your cuckoo CWD? Whats your uwsgi config?

**Comment by Raghavendran-Muthusamy** [comment]
I made few changes in the configuration. My cwd is one instance type i am running it for user cuckoo.Below are my updated configs. Now i am able to get full screen using uwsgi and nginx but it's not taking me to next page when i submit a file for analysis. My nginx error log shows nothing. I am attaching all logs and screenshots.

Nginx
`upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}


server {

    listen 172.16.2.11:443 ssl http2;

    ssl_certificate /etc/nginx/ssl/cuckoo.crt;

    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;

    ssl_dhparam /etc/nginx/ssl/dhparam.pem;

    ssl_protocols TLSv1.2;

    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-$

    ssl_prefer_server_ciphers on;

    # Uncomment this next line if you are using a signed, trusted cert

    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";

    add_header X-Frame-Options SAMEORIGIN;

    add_header X-Content-Type-Options nosniff;

    root /usr/share/nginx/html;

    index index.html index.htm;

    client_max_body_size 101M;

    auth_basic "Login required";

    auth_basic_user_file /etc/nginx/htpasswd;



    location / {
#proxy_pass http://127.0.0.1:8000;
        client_max_body_size 1G;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;

    }
}
`
Uwsgi
`

[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = cuckoo
gid = cuckoo
static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
# If you're getting errors about the PYTHON_EGG_CACHE, then
# uncomment the following line and add some path that is
# writable from the defined user.
# env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/cuckoo/.cuckoo
#socket  = 0.0.0.0:8080
#protocol=http
`
Cuckoo Web Page:
![screenshot from 2019-03-01 11-13-55](https://user-images.githubusercontent.com/25314387/53654759-2b997300-3c14-11e9-83d4-52ea1eddf423.png)

 Access log:
![screenshot from 2019-03-01 11-15-55](https://user-images.githubusercontent.com/25314387/53654855-5daad500-3c14-11e9-9649-5461d4978330.png)

Cuckoo web server log:
![screenshot from 2019-03-01 11-15-18](https://user-images.githubusercontent.com/25314387/53654865-669ba680-3c14-11e9-820a-1f2a755c69db.png)

**Comment by Raghavendran-Muthusamy** [comment]
Thank you @Rooobaaat  for helping me out.  It got resolved so i will close this issue
