### ISSUE TITLE
Unsupported pip interface should not be used, use interface provided by setuptools

### ISSUE THREAD

**Issue by deliciouslytyped** [cuckoosandbox/cuckoo#2678]
I've run into an error from https://github.com/cuckoosandbox/cuckoo/blob/df551778eb319558be450d977113a2dacb81407d/cuckoo/common/utils.py#L265 caused by a pip internal api change.

The following issue describes why this is a bad idea and directly provides an alternative in setuptools:
https://github.com/pypa/pip/issues/5243

(anecdotally; on NixOS, downgrading pip gives a version that's not in the binary caches, and results in needing to recompile almost every python dependency involved with Cuckoo, which is reasonable given how NixOS works, it just takes a while.)

**Comment by jbremer** [comment]
In the latest (unreleased) version of Cuckoo this has been resolved. Thanks for reporting it and thanks to @Luis-Hebendanz for the fix.
