### ISSUE TITLE
Web UI does not function properly

### ISSUE THREAD

**Issue by Mokatsu** [cuckoosandbox/cuckoo#2688]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
My cuckoo instance starts up fine, the server throws no errors, I have a nginx reverse proxy on the external IP and the webserver is running on localhost. When I go to my web page I get the cuckoo dashboard but nothing else is filled in (e.i. version number, past analysis, etc)
<img width="1437" alt="Screen Shot 2019-03-14 at 7 28 57 PM" src="https://user-images.githubusercontent.com/15014768/54401013-b017d700-4693-11e9-98da-a16a9c996ac3.png">
here are the server logs
<img width="738" alt="Screen Shot 2019-03-14 at 7 56 28 PM" src="https://user-images.githubusercontent.com/15014768/54401024-b8701200-4693-11e9-9e42-04b66d7711e0.png">

##### My Cuckoo version and operating system are:
Cuckoo 2.0.6
Host Ubuntu 18.04
VM windows 7

##### This can be reproduced by:
Not sure how
##### The log, error, files etc can be found at:
No error logs didnt see anything in nginx logs

**Comment by Mokatsu** [comment]
It looks like nginx is not forwarding everything.

**Comment by thomaspickup** [comment]
Was there any fix to this?

**Comment by Mokatsu** [comment]
Not really, all I did was:
1) shutdown nginx
2) stop cuckoo
3) run: cuckoo clean
4) start nginx
5) start cuckoo

And it started working fine again.

**Comment by thomaspickup** [comment]
sorry should have specified, i'm using Apache, i've found the issue on my end: 

_C:\Python27\Lib\site-packages\cuckoo\web\web\headers.py_ 

needs to have all the headers specified removed so it functions as below:
```
# Copyright (C) 2010-2013 Claudio Guarnieri.
# Copyright (C) 2014-2016 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file 'docs/LICENSE' for copying permission.

from cuckoo.misc import version

class CuckooHeaders(object):
    """Set Cuckoo custom response headers."""

    def process_response(self, request, response):
        return response
```
This then needs to be compiled using the following command:
`python -m py_compile C:\Python27\Lib\site-packages\cuckoo\web\web\headers.py
`
Then cuckoo web needs to be restarted.

**Comment by Mokatsu** [comment]
Not on my end, I restarted the next day and it started working again...
