### ISSUE TITLE
the guest machine will turn off before finishing the analysis

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2714]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:
2.0.6

**Comment by SparkyNZL** [comment]
Ni Nadir3392

You really need to give us some more information than what you have supplied "The geus machine will turn off before finishing analysis"

How are you submitting the item for analysis?
what timeout are you using ?
What hypervisor are you using ?

Help us help you but supplying detail.

Thanks.

**Comment by nadir3392** [comment]
thank you, it's fixed, and it's work verry well.
