### ISSUE TITLE
No signatures 

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2717]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### Cuckoo version : 2.0.6  , Host : Ubuntu 16.04  , guest : Windows 7

cuckoo sandbox runing wthout error, but the is no signatures in sammary , I did several tests with different known malware, can you help me 
thanks

**Comment by nadir3392** [comment]
it's solved with the command cuckoo --debug to see the debugging issues
and then cuckoo cummunity

**Comment by doomedraven** [comment]
@jbremer  close as solved
