### ISSUE TITLE
Cuckoo Web Deployment common issue with uWSGI and Nginx

### ISSUE THREAD

**Issue by Ma780aPar** [cuckoosandbox/cuckoo#2719]
Hello.
Ubuntu 18.04, Cuckoo version 2.0.6 
I installed successfully Cuckoo without uWSGI and Nginx. Works fine for now. 
At the moment I want to add uWSGI+Nginx as explained in official Cuckoo Docs. But something goes wrong:

UWSGI and NGINX configs:
![image](https://user-images.githubusercontent.com/26720030/56969128-31a4c500-6b6d-11e9-8715-3041b29f4702.png)

SERVICE are running:
![image](https://user-images.githubusercontent.com/26720030/56968923-b80cd700-6b6c-11e9-9387-efba08d68637.png)

RESULT:

![image](https://user-images.githubusercontent.com/26720030/56973300-3b322b00-6b75-11e9-9fbd-1c982ba09569.png)

Please help me with that issue.

**Comment by Ma780aPar** [comment]
No I am getting an 504 
![image](https://user-images.githubusercontent.com/26720030/56973227-1b026c00-6b75-11e9-8aa5-5bfb872c091f.png)

**Comment by reox** [comment]
what says
```
$ ls -al /run/uwsgi/app/cuckoo-web/socket
```
?

I would guess the path is wrong.

**Comment by Ma780aPar** [comment]
Hi. 
mparpaley@cuckoovm:~$ ls -al /run/uwsgi/app/cuckoo-web/socket
srwxrwxrwx 1 mparpaley mparpaley 0 May  2 13:22 /run/uwsgi/app/cuckoo-web/socket

But I have solved the issue. I have added  chmod-socket = 777 in the end of file /etc/uwsgi/apps-available/cuckoo-web.ini and it works now. 

May be someone can explain me why neginx works after I added  chmod-socket = 777  ?

**Comment by reox** [comment]
Ahh ok, so the socket path is ok. But nginx needs access to the socket. chown the group to www-data should do the same
