### ISSUE TITLE
Windows 32 bit

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2730]
salus, it is possible to configure Windows 32 bit guests for cuckoo sandbox (Version 2.0.6)
thank you

**Comment by Evert0x** [comment]
Hi, yes this is possible. We recommend to use https://github.com/hatching/vmcloak for creating virtual machines. 

Do you have any specific questions about creating virtual machines?

**Comment by nadir3392** [comment]
thank you, it's work verry well (for Windows 64bit and 32 bit)
