### ISSUE TITLE
multiple guest

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2734]
cockoo version 2.0.6 instaled on ubuntu 16.04
my Guests Win 7 64 bit, Win 7 32 bit, Win 10 64 bit and win XP.
I want to run more than on guest in the same time, but my probleme is on guest only is march in the same time (if i run Win 7 64bit, Win 732 bit dosent run)
thank you for your response

**Comment by Evert0x** [comment]
Hi, thank you for creating the issue. As I understand, you are not able to submit multiple samples at the same time, is that right?

Are you using virtualbox?

**Comment by nadir3392** [comment]
thank you, it's work verry well.
