### ISSUE TITLE
Completely broken after update today to 2.0.7

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2759]
##### My issue is:
After updating I get:
~~~
2019-06-24 05:22:41,066 [cuckoo] CRITICAL: CuckooConfigurationError: Configuration value routing:inetsim:ports not present! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.
~~~

##### My Cuckoo version and operating system are:
Ubuntu 18, Cuckoo Sandbox 2.0.7

##### This can be reproduced by:
Starting cuckoo

##### The log, error, files etc can be found at:
No logs present

**Comment by DigiAngel** [comment]
And after commenting out yes for inetsim in routing.conf I get:
~~~
2019-06-24 05:42:52,424 [cuckoo] CRITICAL: CuckooCriticalError: Error initializing machines: KVM(i) DSN is missing, please add it to the config file
~~~

Looks like the upgrade has completely hosed my setup.

**Comment by DigiAngel** [comment]
Anything?

**Comment by wroersma** [comment]
So you can either runs the Cuckoo upgrade to migrate your configuration or
add dsn to the kvm.conf file.

**Comment by DigiAngel** [comment]
Thanks...I have no idea how to do either...any pointers?

**Comment by wroersma** [comment]
https://cuckoo.readthedocs.io/en/latest/customization/machinery/#libvirt
this is the documentation of what you would need to add to the kvm file
which is normally located in the cwd conf/kvm.conf or something like that.
If you can't find it let me know and I'll get on my cuckoo container when I
have a second.

**Comment by wroersma** [comment]
Sorry just the docs don't look updated it's documented here
https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/customization/machinery.rst

**Comment by DigiAngel** [comment]
So....this has been working fine before on 2.0.6 and I'm not seeing what's different.  Here's what I have currently:
~~~
[kvm]
machines = win732cuckoo2
interface = virbr0

[win732cuckoo2]
label = win732cuckoo2
platform = windows
ip = 192.168.100.101
snapshot = Running
interface = 
resultserver_ip = 
resultserver_port = 
tags = 
osprofile = Win7SP1x86
~~~
Thank you.

**Comment by DigiAngel** [comment]
So adding:
~~~
dsn = qemu:///system
~~~

my question is why is this suddenly needed?  Where was that change documented?  Thank you.

**Comment by wroersma** [comment]
That change was documented in the docs I linked you but not in the read the
docs site. It should've auto upgraded I'm not sure why it didn't work.

I did the change to make cuckoo be able to work with containers and kvm. Or
just use kvm that's not local to the system it runs on. Sorry about the
trouble I'll take a look and see if I can replicate and fix the auto
upgrade bug.

**Comment by Nwinternights** [comment]
For inetsim issue add lines this to routing.conf : 
# Redirect TCP ports (should we also support UDP?). If specified, this should
# represent whitespace-separated src:dst pairs. E.g., "80:8080 443:8080" will
# redirect all 80/443 traffic to 8080 on the specified InetSim host.
ports = [port to redirect]

**Comment by KlausItem** [comment]
> For inetsim issue add this line and fill it to routing.conf :
> ports = [port to redirect]
> 
> take a look here : https://github.com/cuckoosandbox/cuckoo/blob/df551778eb319558be450d977113a2dacb81407d/cuckoo/private/cwd/conf/routing.conf

That works perfect THX

**Comment by DigiAngel** [comment]
So two things @Nwinternights ...1)  Oddly your actual text doesn't show here, but does show in the email:
~~~
Redirect TCP ports (should we also support UDP?). If specified, this should
represent whitespace-separated src:dst pairs. E.g., "80:8080 443:8080" will
redirect all 80/443 traffic to 8080 on the specified InetSim host. 

ports = [port to redirect]
~~~
2)  Inetsim will respond with with whatever we want to a dns request.....is this not the case now if UDP redirect isn't supported?   Because if UDP redirect isn't supported, then inetsim is practically worthless as no names will be resolved...please tell me that's not the case :D

**Comment by Nwinternights** [comment]
I didn't touch UDP redirection and the Inetsim Dns module works without issues. My Inetsim is installed on te cuckoo host.

**Comment by RicoVZ** [comment]
@DigiAngel 

The `ports = ` field are additional TCP ports that should be redirected the specified IP. It is called InetSim, which might be a bit misleading, as it can basically be used for any redirection needed.

By the `(should we also support UDP?)`, we mean that it might be useful to also specify custom UDP ports in the future.

By default, when InetSim mode is used, UDP 53 will always be redirected to the IP specified in `server =`.

**Comment by DigiAngel** [comment]
Ok cool...same setup as myself then thank you.
