### ISSUE TITLE
Failed to start - 2.0.7

### ISSUE THREAD

**Issue by myrinx** [cuckoosandbox/cuckoo#2762]
Hi,

I'm trying to start cuckoo like always after the update to the latest version.

##### My issue is:

Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.7
OS version: posix
OS release: debian 8.11
Python version: 2.7.9
Python implementation: CPython
Machine arch: x86_64
Modules: alembic:1.0.10 androguard:3.0.1 appdirs:1.4.3 argparse:1.2.1 asn1crypto:0.24.0 attrs:19.1.0 beautifulsoup4:4.5.3 cairocffi:0.8.0 cairosvg:1.0.22 capstone:3.0.5rc2 cffi:1.12.3 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.7 cssselect:1.0.1 cuckoo:2.0.7 defusedxml:0.4.1 distorm3:3.3.4 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 docutils:0.12 dpkt:1.8.7 ecdsa:0.13.2 egghatch:0.2.3 elasticsearch:5.3.0 enum34:1.1.6 et-xmlfile:1.0.1 flask-sqlalchemy:2.4.0 flask:0.12.2 functools32:3.2.3.post2 future:0.17.1 gevent:1.2.2 greenlet:0.4.15 html5lib:0.999999999 httpreplay:0.2.6 idna:2.8 ipaddress:1.0.22 itsdangerous:1.1.0 jdcal:1.3 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:3.0.1 lxml:3.4.0 m2crypto:0.24.0 mako:1.0.12 markupsafe:1.1.1 ndg-httpsclient:0.3.2 numpy:1.8.2 olefile:0.43 oletools:0.51 openpyxl:2.4.7 packaging:16.8 peepdf:0.4.2 pefile2:1.2.11 pillow:3.2.0 pip:9.0.1 ply:3.4 pyasn1:0.1.7 pycparser:2.19 pycrypto:2.6.1 pycups:1.9.63 pycurl:7.19.5 pydeep:0.2 pyelftools:0.24 pygments:2.0.1 pygobject:3.14.0 pyguacamole:0.6 pymisp:2.4.106 pymongo:3.0.3 pyopenssl:19.0.0 pyparsing:2.2.0 pyphen:0.9.4 pyrsistent:0.15.2 pysmbc:1.0.15.3 python-apt:0.9.3.12 python-dateutil:2.4.2 python-debian:0.1.27 python-debianbts:1.11 python-editor:1.0.4 python-magic:0.4.12 python:2.7.9 pythonaes:1.0 pyxdg:0.25 reportbug:6.6.3 requests:2.13.0 roach:0.1.2 roman:2.0.0 scapy:2.3.2 setuptools:41.0.1 sflock:0.3.10 six:1.12.0 soappy:0.12.22 sqlalchemy:1.3.3 tinycss:0.4 tlslite-ng:0.6.0 ujson:1.35 unicorn:1.0.1 urllib3:1.25.3 vboxapi:1.0 volatility:2.6 wakeonlan:0.2.2 weasyprint:0.36 webencodings:0.5.1 werkzeug:0.15.4 wheel:0.24.0 wsgiref:0.1.2 wstools:0.4.3 yara-python:3.6.3 yara:1.7.7

2019-06-25 14:29:21,885 [cuckoo] ERROR: AttributeError: Rules instance has no attribute 'save'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 297, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 192, in cuckoo_init
    init_yara()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 358, in init_yara
    File.yara_rules["dumpmem"].save(cwd("stuff", "dumpmem.yarac"))
AttributeError: Rules instance has no attribute 'save'

**Comment by myrinx** [comment]
my bad. yara issue, not cuckoo

**Comment by ishirleyforever** [comment]
> my bad. yara issue, not cuckoo

How to fix it?
