### ISSUE TITLE
Cuckoo Host freezes after analysis procedure completes

### ISSUE THREAD

**Issue by Redorhcs** [cuckoosandbox/cuckoo#2763]
##### This can be reproduced by: 

- Start the virtualbox network (hostonlyif)
- launch `cuckoo --debug`, 
- launch `cuckoo web runserver 192.168.56.1:8080`
- Upload sample using 160 second timeout, no inetsim or internet for sample
- Debug will report `reports generation completed` and `Task #X analysis procedure completed`
- Host machine will freeze, stop responding to any/all input.

##### The log, error, files etc can be found at: 

I have ran cuckoo in debug mode, and it does not report any issues at this time. It's an airgapped machine, so log files may take time to extract if needed (so let me know asap!)

=====
P.S. I have tried letting it run overnight to see if that would clear the machine, however a soft reboot is required from Openstack to regain functionality.

**Comment by RicoVZ** [comment]
Hi Redorhcs,

Thanks for reporting an issue.

> I have ran cuckoo in debug mode, and it does not report any issues at this time. It's an airgapped machine, so log files may take time to extract if needed (so let me know asap!)

Yes, please share the full Cuckoo log from `$CWD/logs/cuckoo.log`.

To be clear: you are using nested virtualization? And the complete host system freezes. SSH connection not possible etc?

Can you share some files you were analyzing?

**Comment by Redorhcs** [comment]
Hi Rico,

I am running a _bare metal_ provisioning Openstack cluster (so no nested virtualization IIRC). The Ubuntu image deploys two Windows 7 machines w/ agent running (32 and 64 bit). 

> And the complete host system freezes. SSH connection not possible etc?


SSH and RDP completely cut out after the task finishes. A manual restart of the host machine is required to recover.

Any file I've tried seems to have worked. I was just using a generic pdf malware file, don't have a vt hash on hand.

> Log files

Please see [cuckoo.log](https://github.com/cuckoosandbox/cuckoo/files/3325349/cuckoo.log). I have corrected the issues for tasks before 6 with sniffer.

**Comment by Redorhcs** [comment]
Also - machine is running the followings specs:

- 16 Gb Ram
- 8 Core (V)CPU
- 160 Gb Disk (ssd)

**Comment by RicoVZ** [comment]
Thanks :slightly_smiling_face: 

I see a lot of null bytes in the log. This might indicate failing hardware?
https://stackoverflow.com/questions/46122062/python-logger-inserting-null-control-characters-into-file

It might be that a high CPU/memory/disk load causes a crash.
What happens if you don't run Cuckoo, but run a stress test for a while?

Something like this, for example: 
`$ stress --cpu 8 --io 4 --vm 4 --vm-bytes 4096M --hdd 2`

**Comment by Redorhcs** [comment]
@RicoVZ Question: is there any recommended set up for MongoDB? I don't recall what I've done to set it up so far.

Running stress now, and will update.

**Comment by RicoVZ** [comment]
> Question: is there any recommended set up for MongoDB

Nothing besides filling in the correct port/ip if the default is changed. By default it connects to localhost:27017 and will try to create a database name `cuckoo`.

By letting it run, I meant for a litte while, maybe like 15-30 mins. Especially the disk stress.
Can you try:
`stress --hdd 128 --hdd-bytes 8M --vm 4 --vm-bytes 4096M`

**Comment by Redorhcs** [comment]
Updates:

- I've disabled Mongodb and the web interface
- Stress test finished w/o issues

Still running into the hangup issue over SSH (so with or without rdp access).

**Comment by Redorhcs** [comment]
Additional update:

- Cuckoo will run through multiple samples ( X > 1) without issue, and properly create reports. It locks up at the end of all the samples and the last report being generated. Requires reboot to access reports.

**Comment by RicoVZ** [comment]
Thanks for posting updates @Redorhcs 

Are there any other physical machines available where you can run the Cuckoo host?

I have not been able to reproduce this. It still bothers me that your log file writes errors for other services and has random \x00 bytes, precisely at the moment the system freezes.

If other people are experiencing this, please comment here.

**Comment by Redorhcs** [comment]
Hi Rico,

I meant to close this issue last night actually. I have reasonable suspicion of the error:

- The machine image was created in Oracle VM VIrtualbox 5.2.x, and later converted to RAW and lastly to QCOW2 before deployment in Openstack
_ This conversion process does not always work 100%
- Virutalbox fragments were left behind during the conversion (i.e. guest additions and other packages were still installed).

I made the call last night to destroy the broken image and started from a new clean image using the available cuckoo documentation.

I now have a fully working instance (minus Elasticsearch, I'm planning an _attempt_ to convert ES5 to ES6 as we already leverage that here) on 16.04.02 LTS Xenial Server. No more lockups!
