### ISSUE TITLE
on_signature example is error in doc

### ISSUE THREAD

**Issue by qux-bbb** [cuckoosandbox/cuckoo#2765]
##### My issue is:
In https://cuckoo.sh/docs/customization/signatures.html#creating-your-new-signature, There is a example to explain the usage of on_signature:  
```python
required = ["creates_exe", "badmalware"]

def on_signature(self, matched_sig):
    if matched_sig in self.required:
        self.required.remove(matched_sig)

    if not self.required:
        return True

    return False
```
But it is wrong. We should use matched_sig.name to search, for example：  
```python
required = ["creates_exe", "badmalware"]

def on_signature(self, matched_sig):
    if matched_sig.name in self.required:
        self.required.remove(matched_sig.name)

    if not self.required:
        return True

    return False
```
##### My Cuckoo version and operating system are:
2.0.6  
ubuntu win7  
##### This can be reproduced by:
Just usage wrong.  
##### The log, error, files etc can be found at:
No.

**Comment by RicoVZ** [comment]
Hi @qux-bbb,

Thanks for posting an issue.

You're right. It should be `matched_sig.name`. Thanks! :)

**Comment by qux-bbb** [comment]
You can fix it. I will close the issue. Thanks!
