### ISSUE TITLE
Any other surprises we need to be aware of going from 2.0.6 to 2.0.7?

### ISSUE THREAD

**Issue by DigiAngel** [cuckoosandbox/cuckoo#2766]
Just checking....after yesterday's excitement I'm hoping to that all the breakage has stopped.  I did see that MISP is now pushing comments and adding a Cuckoo tag, but I don't see any new options in reporting.conf, nor in:

[reporting.conf[(https://github.com/cuckoosandbox/cuckoo/blob/df551778eb319558be450d977113a2dacb81407d/cuckoo/private/cwd/conf/reporting.conf)

Also, is there a mailing list or something I can get on?  Would be nice to get an email when breaking changes are introduced...thank you.

**Comment by RicoVZ** [comment]
Hi DigiAngel,

Thanks for posting an issue.

>  I did see that MISP is now pushing comments and adding a Cuckoo tag, but I don't see any new options in reporting.conf, nor in:

There are new reporting.conf options for MISP: https://github.com/cuckoosandbox/cuckoo/blob/2.0.7/cuckoo/private/cwd/conf/reporting.conf

Unfortunately, new options are not written to existing configs. New options should have a default value that Cuckoo knows, preventing breakage. Unfortunately, the `ports =` in the routing conf was not set to optional. It will only require this option when a specific module is enabled, however.

There is no mailing list, you can join our Slack, however. There are a more Cuckoo users on there.
If you mail me at ricardo@cuckoo.sh, I'll send you an invite.

**Comment by DigiAngel** [comment]
Really appreciate it Ricardo....will close this out...thank you!
