### ISSUE TITLE
ERROR: Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by testgitaaron** [cuckoosandbox/cuckoo#2767]
My issue is:
  When i run  "cuckoo submit file" , My cuckoo will run the following results.

<img width="363" alt="擷取" src="https://user-images.githubusercontent.com/43289336/60382583-af1a8200-9a97-11e9-8a0e-d63d59aa1189.PNG">

**Comment by RicoVZ** [comment]
Hi testgitaaron,

Thanks for posting an issue.

This error indicates the Cuckoo agent failed to create a temporary directory on the VM. The most likely reason for this is the agent not having permission to do so.

Can you verify the agent can create a directory?
