### ISSUE TITLE
Remote control via Guacd not working after upgrade to 2.0.7.

### ISSUE THREAD

**Issue by tcannon9132** [cuckoosandbox/cuckoo#2771]
##### The log, error, files etc can be found at: I cannot locate any errors indicating problems with guacd in logs from cuckoo or anywhere in syslog.

After upgrading to 2.0.7 I cannot get guacd remote control to work and only receive the static screen with "An error occured". I have since built a second instance from scratch (No reused configs, guest instances, or resources) and I am still experiencing this problem with 2.0.7. I will be happy to provide logs, but I am honestly unsure which logs to provide as I could not find anything from cuckoo or in syslog that indicate problems with guacd or the remote control feature. Attached are all applicable config files for my deployment. I'm a bit out of ideas on how to resolve this issue so any advice or ideas are greatly appreciated.
[conf.zip](https://github.com/cuckoosandbox/cuckoo/files/3346836/conf.zip)

**Comment by RicoVZ** [comment]
Hi tcannon9132,

Thanks for posting an issue.

We recently found this out and are aware of it. We are looking into solving this issue.

**Comment by leniwiec16** [comment]
Same here on Ubuntu Desktop 18.04 and KVM.

**Comment by ne1llee** [comment]
I have temporarily closed the CSRF authentication of the two interfaces:
api/tasks/info
analysis/control/tunnel

![image](https://user-images.githubusercontent.com/12810839/60563775-c1463a00-9d8f-11e9-868d-0830eee69546.png)

**Comment by tcannon9132** [comment]
> I have temporarily closed the CSRF authentication of the two interfaces:
> api/tasks/info
> analysis/control/tunnel
> 
> ![image](https://user-images.githubusercontent.com/12810839/60563775-c1463a00-9d8f-11e9-868d-0830eee69546.png)

Can you please elaborate on this? Is this a workaround for this issue? Where can I find urls.py in my install to make these changes if this is the case?

**Comment by micscoob** [comment]
Can you go into a bit more detail of how to fix this?

**Comment by tcannon9132** [comment]
@micscoob Edit  /usr/local/lib/python2.7/dist-packages/cuckoo/web/analysis/urls.py to reflect the changes listed above by ne1llee's post (comment out what is in red and add what is in green)and restart. No other changes are needed.

**Comment by micscoob** [comment]
Worked like a charm! Thanks.

**Comment by leniwiec16** [comment]
Is it fair to call it a fix? Sounds more like a workaround to me. Doesn't it introduce some CSRF vulnerabilities?

**Comment by 1earch** [comment]
In my mind, duplicate of #2720 
And a PR is developed but not working for now, I think: #2721
