### ISSUE TITLE
Cuckoo Sandbox Program Main Entry Point

### ISSUE THREAD

**Issue by Jon045** [cuckoosandbox/cuckoo#2802]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I just wanted to know where is the main entry point located in cuckoo python files. I have been looking for it to understand the flow of program but have only found class definitions yet. Kindly let me know. Thanks.

**Comment by RicoVZ** [comment]
Hi John045,

Thanks for creating an issue.

The main entry point is located in this file: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/main.py#L259

We use [Click](https://click.palletsprojects.com/en/7.x/), a Python library for argument parsing etc. It creates a real main entry point somewhere in the install directory. This is a generated file and should not be edited. However, that file calls the method in the link above.

**Comment by Jon045** [comment]
Hey RicoVZ,

Thank you so much the quick response. I have been trying to find it for some time. I am actually trying to create my own signatures and integrate them with the current Cuckoo Sandbox. So I was wondering if there are any other changes need to be made or any program functionality that needs to be understood other than what is already specified in the cuckoo documentation. Kindly let me know.

**Comment by RicoVZ** [comment]
You're welcome :slightly_smiling_face: 

If your signatures implement the Signature abstract class, no code changes are required: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/common/abstracts.py#L825 

You can then just copy your signatures to `$CWD/signatures/<platform/type>`, and restart Cuckoo to load them.

**Comment by Jon045** [comment]
Helo RicoVZ,

Thanks for the clarification. I tried creating a cuckoo signature, but ran into some issues. Kindly let me know what I could be doing wrong.

Here is what I did:

I wrote a program in C++, compiled and executed its exe release. It calls the FindWindowA function to find a running window. I grepped the window names using EnumWindows function and then matched a particular string with the list of running windows. 

The above program works fine. Then I tried writing the signature for it, to detect the cuckoo agent.py on the guest machine. below is my code.

`class AntiSandboxDetector(Signature):
    name = "anti_debugger_sandbox_detection"
    description = "Checks if Cuckoo Agent or OllyDbg is running"
    severity = 2
    categories = ["injection"]
    authors = ["NCCS Team"]
    minimum = "2.0"
    ttp = ["T1600"]

    filter_apinames = [
        "FindWindowA",
    ]

    #windowhandle = ""
    

    def on_call(self, call, process):
	#substr="Test1.exe"
	print "My Signature Test"
        if call["api"] == "FindWindowA":
	    print "FindWindowA Api Test"
	    print call["arguments"]["window_name"]
	    print call["arguments"]["class_name"]
            if call["arguments"]["window_name"]=="C:\Users\guestwindows\AppData\Local\Temp\Test1.exe" or call["arguments"]["class_name"]=="C:\Users\guestwindows\AppData\Local\Temp\Test1.exe":
		print "Test1.exe Test"
                self.mark_call()
		return True`

Can you please let me know where did I go wrong? Thanks.

**Comment by Jon045** [comment]
Hello RicoVZ,

My Apologies. kindly ignore the code given in previous comment and consider the one below:


`filter_apinames = [
        "FindWindowA",
    ]

    #windowhandle = ""
    

    def on_call(self, call, process):
	substr="agent.py"
	print "My Signature Test"
        if call["api"] == "FindWindowA":
	    print "FindWindowA Api Test"
	    print call["arguments"]["window_name"]
	    print call["arguments"]["class_name"]
            if substr in call["arguments"]["window_name"]
		print "agent.py test"
                self.mark_call()
		return True`

On printing the **window_name** and **class_name** attributes I get a newline and #0 printed. Can you help me identify why the arguments do not contain the matched value?
