### ISSUE TITLE
Malware sample score issues

### ISSUE THREAD

**Issue by ebolanoso** [cuckoosandbox/cuckoo#2807]
My cuckoo don't shows the same score than the web version "cuckoo.cert.ee", my cuckoo shows the score 2.4 (This is very low) and the web version shows 22.0, I compared the results of my cuckoo with the web version to confirm the correct operation of my cuckoo, but the results are not the same.

I used a sample of PETYA malware, this is the MD5 hash (af2379cc4d607a45ac44d62135fb7015) this is the results of the web version :
https://cuckoo.cert.ee/analysis/1151638/summary

My cuckoo version are 2.0.7 and my operating system are UBUNTU 18

**Comment by ryanbekabe** [comment]
I will try with my Cuckoo server too: http://148.72.214.65:8010/dashboard/
Score of cuckoo.cert.ee I think was modified by it owner, coz it score too big.

**Comment by ebolanoso** [comment]
Thank you @ryanbekabe, I modified this:
- show_virustotal = yes in the file "reporting.conf"
- scan = yes in the file "procesing.conf"

And I used my VirusTotal API key, my new score is 5.6 to 10; it is more real, it's okay for me.

**Comment by RicoVZ** [comment]
Hey @ebolanoso,

Thanks for posting an issue.

Cuckoo.cert.ee seems to be using modified scoring calculation code or signature weights. Most of their scores are quite a bit higher than the usual Cuckoo score.

**Comment by ebolanoso** [comment]
Thank you @RicoVZ ...!
