### ISSUE TITLE
Cuckoo won't install with updated owtf, mitm6, nosqlmap packages

### ISSUE THREAD

**Issue by Loki-Chaser** [cuckoosandbox/cuckoo#2837]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### This can be reproduced by:
loki@ubuntu:~$ pip install Cuckoo-2.0.7.tar.gz 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/masandl/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/masandl/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./Cuckoo-2.0.7.tar.gz
Requirement already satisfied: alembic==1.0.10 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.0.10)
Requirement already satisfied: androguard==3.0.1 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (3.0.1)
Requirement already satisfied: beautifulsoup4==4.5.3 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (4.5.3)
Requirement already satisfied: chardet==2.3.0 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (2.3.0)
Requirement already satisfied: click==6.6 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (6.6)
Requirement already satisfied: django==1.8.4 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.8.4)
Requirement already satisfied: django_extensions==1.6.7 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.6.7)
Collecting dpkt==1.8.7 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/c6/78/3baab9f9cbf06a416e0bdd9b95268abe2b2faab4a1cc6d8ae83251bf915f/dpkt-1.8.7-py2-none-any.whl (112kB)
     |████████████████████████████████| 122kB 3.6MB/s 
Collecting egghatch<0.3,>=0.2.3 (from Cuckoo==2.0.7)
Collecting elasticsearch==5.3.0 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/37/88/692a8ece505675a62f542f06fb3c0b10f2271605576114c992b34a60492e/elasticsearch-5.3.0-py2.py3-none-any.whl (66kB)
     |████████████████████████████████| 71kB 15.8MB/s 
Collecting flask==0.12.2 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/77/32/e3597cb19ffffe724ad4bf0beca4153419918e7fa4ba6a34b04ee4da3371/Flask-0.12.2-py2.py3-none-any.whl (83kB)
     |████████████████████████████████| 92kB 19.6MB/s 
Collecting flask-sqlalchemy==2.4.0 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/08/ca/582442cad71504a1514a2f053006c8bb128844133d6076a4df17117545fa/Flask_SQLAlchemy-2.4.0-py2.py3-none-any.whl
Collecting httpreplay<0.3,>=0.2.4 (from Cuckoo==2.0.7)
Requirement already satisfied: ipaddress>=1.0.22 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.0.22)
Collecting gevent<1.3,>=1.2 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/74/fe/1d681dc31f61cb95fcc55e9c3baf7117e52db78270aa1bf169262f86707e/gevent-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl (1.6MB)
     |████████████████████████████████| 1.6MB 17.3MB/s 
Collecting jinja2==2.9.6 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/5e/73/10c45b82a88ed6b7751bd40da31eeefd7b362e07b56a99aa6e56655a0794/Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
     |████████████████████████████████| 348kB 19.3MB/s 
Requirement already satisfied: jsbeautifier==1.6.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.6.2)
Collecting oletools==0.51 (from Cuckoo==2.0.7)
Requirement already satisfied: peepdf<0.5,>=0.4.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (0.4.2)
Requirement already satisfied: pefile2==1.2.11 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.2.11)
Requirement already satisfied: pillow==3.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (3.2.0)
Collecting pyelftools==0.24 (from Cuckoo==2.0.7)
Collecting pyguacamole==0.6 (from Cuckoo==2.0.7)
Collecting pymisp==2.4.106 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/72/85/a4afc64be6c00311075cd8006fe2a47edac024f09838b60f8693b996af63/pymisp-2.4.106-py2-none-any.whl (202kB)
     |████████████████████████████████| 204kB 32.4MB/s 
Collecting pymongo==3.0.3 (from Cuckoo==2.0.7)
Requirement already satisfied: python-dateutil==2.4.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (2.4.2)
Requirement already satisfied: python-magic==0.4.12 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (0.4.12)
Requirement already satisfied: roach<0.2,>=0.1.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (0.1.2)
Requirement already satisfied: sflock<0.4,>=0.3.10 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (0.3.10)
Requirement already satisfied: sqlalchemy==1.3.3 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.3.3)
Requirement already satisfied: unicorn==1.0.1 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (1.0.1)
Requirement already satisfied: wakeonlan==0.2.2 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (0.2.2)
Requirement already satisfied: yara-python==3.6.3 in /usr/local/lib/python2.7/dist-packages (from Cuckoo==2.0.7) (3.6.3)
Collecting requests[security]==2.13.0 (from Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl (584kB)
     |████████████████████████████████| 593kB 28.9MB/s 
Collecting scapy==2.3.2 (from Cuckoo==2.0.7)
Requirement already satisfied: python-editor>=0.3 in /usr/local/lib/python2.7/dist-packages (from alembic==1.0.10->Cuckoo==2.0.7) (1.0.4)
Requirement already satisfied: Mako in /usr/local/lib/python2.7/dist-packages (from alembic==1.0.10->Cuckoo==2.0.7) (1.0.8)
Requirement already satisfied: six>=1.2 in /usr/local/lib/python2.7/dist-packages (from django_extensions==1.6.7->Cuckoo==2.0.7) (1.11.0)
Requirement already satisfied: capstone==3.0.5rc2; sys_platform == "linux2" in /usr/local/lib/python2.7/dist-packages (from egghatch<0.3,>=0.2.3->Cuckoo==2.0.7) (3.0.5rc2)
Requirement already satisfied: urllib3<2.0,>=1.8 in /usr/local/lib/python2.7/dist-packages (from elasticsearch==5.3.0->Cuckoo==2.0.7) (1.22)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask==0.12.2->Cuckoo==2.0.7) (1.1.0)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask==0.12.2->Cuckoo==2.0.7) (0.15.2)
Requirement already satisfied: tlslite-ng==0.6.0 in /usr/local/lib/python2.7/dist-packages (from httpreplay<0.3,>=0.2.4->Cuckoo==2.0.7) (0.6.0)
Requirement already satisfied: greenlet>=0.4.10 in /usr/local/lib/python2.7/dist-packages (from gevent<1.3,>=1.2->Cuckoo==2.0.7) (0.4.15)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2==2.9.6->Cuckoo==2.0.7) (1.1.1)
Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python2.7/dist-packages (from peepdf<0.5,>=0.4.2->Cuckoo==2.0.7) (0.17.1)
Requirement already satisfied: pythonaes==1.0 in /usr/local/lib/python2.7/dist-packages (from peepdf<0.5,>=0.4.2->Cuckoo==2.0.7) (1.0)
Requirement already satisfied: colorama==0.3.7 in /usr/local/lib/python2.7/dist-packages (from peepdf<0.5,>=0.4.2->Cuckoo==2.0.7) (0.3.7)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from pymisp==2.4.106->Cuckoo==2.0.7) (1.1.6)
Collecting jsonschema (from pymisp==2.4.106->Cuckoo==2.0.7)
  Downloading https://files.pythonhosted.org/packages/54/48/f5f11003ceddcd4ad292d4d9b5677588e9169eef41f88e38b2888e7ec6c4/jsonschema-3.0.2-py2.py3-none-any.whl (54kB)
     |████████████████████████████████| 61kB 10.8MB/s 
Collecting functools32; python_version < "3.0" (from pymisp==2.4.106->Cuckoo==2.0.7)
Requirement already satisfied: cryptography>=2.1 in /usr/local/lib/python2.7/dist-packages (from roach<0.2,>=0.1.2->Cuckoo==2.0.7) (2.6.1)
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages (from roach<0.2,>=0.1.2->Cuckoo==2.0.7) (2.6.1)
Requirement already satisfied: olefile==0.43 in /usr/local/lib/python2.7/dist-packages (from sflock<0.4,>=0.3.10->Cuckoo==2.0.7) (0.43)
Requirement already satisfied: idna>=2.0.0; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]==2.13.0->Cuckoo==2.0.7) (2.6)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]==2.13.0->Cuckoo==2.0.7) (17.2.0)
Requirement already satisfied: ecdsa in /usr/local/lib/python2.7/dist-packages (from tlslite-ng==0.6.0->httpreplay<0.3,>=0.2.4->Cuckoo==2.0.7) (0.13.2)
Collecting pyrsistent>=0.14.0 (from jsonschema->pymisp==2.4.106->Cuckoo==2.0.7)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python2.7/dist-packages (from jsonschema->pymisp==2.4.106->Cuckoo==2.0.7) (19.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from jsonschema->pymisp==2.4.106->Cuckoo==2.0.7) (41.1.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/dist-packages (from cryptography>=2.1->roach<0.2,>=0.1.2->Cuckoo==2.0.7) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1->roach<0.2,>=0.1.2->Cuckoo==2.0.7) (1.12.2)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1->roach<0.2,>=0.1.2->Cuckoo==2.0.7) (2.19)
Building wheels for collected packages: Cuckoo
  WARNING: Building wheel for Cuckoo failed: [Errno 13] Permission denied: '/home/masandl/.cache/pip/wheels/91'
Failed to build Cuckoo
ERROR: dropbox 9.3.0 has requirement requests>=2.16.2, but you'll have requests 2.13.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement cffi==1.10.0, but you'll have cffi 1.12.2 which is incompatible.
ERROR: owtf 2.6.0 has requirement dnspython==1.15.0, but you'll have dnspython 1.16.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement future==0.16.0, but you'll have future 0.17.1 which is incompatible.
ERROR: owtf 2.6.0 has requirement pexpect==4.6.0, but you'll have pexpect 4.7.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement pyOpenSSL==17.5.0, but you'll have pyopenssl 17.2.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement PyYAML==3.13, but you'll have pyyaml 5.1 which is incompatible.
ERROR: owtf 2.6.0 has requirement requests==2.18.4, but you'll have requests 2.13.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement selenium==3.4.3, but you'll have selenium 3.141.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
ERROR: owtf 2.6.0 has requirement SQLAlchemy==1.1.13, but you'll have sqlalchemy 1.3.3 which is incompatible.
ERROR: owtf 2.6.0 has requirement tornado==5.0.2, but you'll have tornado 5.1.1 which is incompatible.
ERROR: mitm6 0.2.2 has requirement scapy>=2.4, but you'll have scapy 2.3.2 which is incompatible.
ERROR: nosqlmap 0.7 has requirement ipcalc==1.1.3, but you'll have ipcalc 1.99.0 which is incompatible.
ERROR: nosqlmap 0.7 has requirement pymongo==2.7.2, but you'll have pymongo 3.0.3 which is incompatible.
ERROR: nosqlmap 0.7 has requirement requests==2.5.0, but you'll have requests 2.13.0 which is incompatible.
Installing collected packages: dpkt, egghatch, elasticsearch, jinja2, flask, flask-sqlalchemy, httpreplay, gevent, oletools, pyelftools, pyguacamole, requests, pyrsistent, functools32, jsonschema, pymisp, pymongo, scapy, Cuckoo
  Found existing installation: dpkt 1.8
ERROR: Cannot uninstall 'dpkt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by doomedraven** [comment]
use virtualenv, thats all, it requires specific versions to not break and works correctly

**Comment by doomedraven** [comment]
@jbremer another dead issue
