### ISSUE TITLE
Failed to load Volatility Library

### ISSUE THREAD

**Issue by stianroen** [cuckoosandbox/cuckoo#2846]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is: 
Like OP states, Cuckoo is having an issue launching Volatility during analysis.

##### My Cuckoo version and operating system are:
Cuckoo version: 2.0.7
Ubuntu 18.04.3 (fully updated)

##### This can be reproduced by:
What I have tried is using Volatility from apt. It doesnt seem to make a difference whether or not I install from Source or from Ubuntu Repositories. 
- Installing from apt: `sudo apt install volatility` (tried this with installing `volatility tools` aswell)
- Installing from source (1): 
`git clone https://github.com/volatilityfoundation/volatility.git`
`cd volatility`
`sudo python setup.py build`
`sudo python setup.py install`

- Installing from source (2): 
`git clone https://github.com/volatilityfoundation/volatility.git`
`cd volatility`
`sudo python setup.py install`

Cuckoo is installed to virtualenv at /opt/cuckoo running as the user 'cuckoo'. I have been very sure to set the permissions accordingly, so that both the user cuckoo and it's respective group(cuckoo) has every permission needed to execute, read and write to the directory and its subdirectories.
Installing Volatility from virtualenv doesn't make a difference - it still fails to load. 

I've also been able to reproduce the error with Cuckoo version 2.0.6, which worked for me on a previous installation that I did on VMware vSphere. 

Right now I'm trying to build Cuckoo on top of an Ubuntu 18.04.3 as the host, using KVM as the machinery. Everything seems to work just fine, except from Volatility. The error is reproduced using both Windows 7 and Windows 10. Having set the correct osprofiles in memory.conf respectively. What I have tried:

`$ python`
`import volatility`
`import volatility.conf as conf`

This works both from virtualenv and outside of virtualenv. No errors thrown at me.

##### The log, error, files etc can be found at:
I can provide logs later if wanted, but the error thrown during analysis is the following: 
`The volatility library is not available. Please install it according to their documentation.`

I have been doing my research looking through previous issues in this repository, but I have felt that the information provided by the 'issuer' has been lackluster, and so I'm willing to provide all the information available to me to try and resolve this issue. It is vital in my work that I get this to work using KVM(don't even know if that is the issue).

**Comment by doomedraven** [comment]
well vmware/kvm shouldn't be an issue, can you check where volatility was installed? maybe it wasn't installed in virtenv for some reason even from inside of virtenv, i had similar issue in diff project, and was just need to specify the path where to install to be able to use it inside of venv

**Comment by doomedraven** [comment]
wait why you just not install it with pip from venv? `pip install git+https://github.com/volatilityfoundation/volatility.git`

**Comment by stianroen** [comment]
Hi doomedraven,
Thank you for your quick reply. I will rebuild environment and install Volatility as per your suggestion. I will get back to you :)

**Comment by stianroen** [comment]
Hi again,

The way to install Volatility provided by you seems to have solved my issue, installing volatility directly into venv. Thank you so much for your help! :)

**Comment by doomedraven** [comment]
you are welcome! close if solved ;)

**Comment by doomedraven** [comment]
use that in future intead of setup.py build/setup.py install
