### ISSUE TITLE
MISP Integration with Cuckoo.

### ISSUE THREAD

**Issue by Jon045** [cuckoosandbox/cuckoo#2849]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I am trying to integrate MISP with Cuckoo Sandbox. I have installed **MISP** on the machine and **PYMISP version 2.4.112**.  

my processing.conf looks like

```
[misp]
enabled = yes
url = https://localhost
apikey = bRKXUFosaOROLxV8dWNpwb17cVzEkuLMFPC6gsSn

# Maximum amount of IOCs to look up (hard limit).
maxioc = 100
```
and 

reporting.conf looks like:
```

enabled = yes
url = https://localhost
apikey = bRKXUFosaOROLxV8dWNpwb17cVzEkuLMFPC6gsSn
distribution = 0
analysis = 0
threat_level = 4
min_malscore = 0
tag = Cuckoo
upload_sample = no
```

Kindly let me know what else I need to do order for misp to run with Cuckoo. thanks

**Comment by doomedraven** [comment]
check pull requests there some about that, i think endpoints changed, but not sure as im not using misp since a lot
