### ISSUE TITLE
Can't start cuckoo web runserver web server but cuckoo -d will work fine

### ISSUE THREAD

**Issue by frozenn1** [cuckoosandbox/cuckoo#2852]
Hello all, 

What should I do ? My reporting.conf looks like this:
enabled = no
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100

Cuckoo sandbox works fine, but when i want to run cuckoo web i got this message:

(venv) cuckoo@CuckooSandbox:~$ cuckoo web
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

Cuckoo Sandbox 2.0.7
Kali Linux 32-bit

(venv) cuckoo@CuckooSandbox:/opt/cuckoo/conf$ service mongodb status
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; disabled; vendor preset:
   Active: inactive (dead)
     Docs: man:mongod(1)
lines 1-4/4 (END)...skipping...
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:mongod(1)

**Comment by doomedraven** [comment]
you have problems with mongo as you can see, you need to investigate why

**Comment by frozenn1** [comment]
So should I install other version mongodb? How can i do this on 32-bit version?

**Comment by doomedraven** [comment]
you should investigate what is wrong with your mongo, it already installed

**Comment by frozenn1** [comment]
Configuration of my mongodb file looks like: (sudo nano mongodb.service)
[Unit]
Description=An object/document-oriented database
Documentation=man:mongod(1)
After=network.target

[Service]
User=mongodb
Group=mongodb
RuntimeDirectory=mongodb
RuntimeDirectoryMode=0755
EnvironmentFile=-/etc/default/mongodb
Environment=CONF=/etc/mongodb.conf
Environment=SOCKETPATH=/run/mongodb
ExecStart=/usr/bin/mongod --quiet --config /etc/mongodb.conf

[Install]
WantedBy=multi-user.target


>systemctl list-unit-files --type=service
      mongodb.service                            enabled  


When I tried to do systemctl enable mongod.service
I got: Failed to enable unit: Unit file mongod.service does not exist.

**Comment by doomedraven** [comment]
bcz its mongodb not mongod

**Comment by frozenn1** [comment]
Ok, i change this and now it looks like:
cuckoo@CuckooSandbox:~$ systemctl status mongodb
Warning: The unit file, source configuration file or drop-ins of mongodb.service
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: 
   Active: active (running) since Wed 2019-08-28 15:18:01 CEST; 14min ago
     Docs: man:mongod(1)
 Main PID: 4166 (mongod)
    Tasks: 13 (limit: 4915)
   Memory: 45.3M
   CGroup: /system.slice/mongodb.service
           └─4166 /usr/bin/mongod --quiet --config /etc/mongodb.conf

**Comment by frozenn1** [comment]
But i still cant start cuckoo web :<
(venv) cuckoo@CuckooSandbox:/opt/cuckoo$ cuckoo web
In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf file.

**Comment by doomedraven** [comment]
what about if you type `mongo`? did you enabled mogno in `$CWD/conf/reporting.conf` ?

**Comment by frozenn1** [comment]
I enabled mongodb in $CWD/conf/reporting.conf and it is now working fine, Cuckoo web started, 
@doomedraven thank bro

**Comment by doomedraven** [comment]
you are welcome :) just friendly suggestion, read the output, you have answers in there in 99.9% cases ;)
