### ISSUE TITLE
cuckoo sandbox database 

### ISSUE THREAD

**Issue by AlexKim100** [cuckoosandbox/cuckoo#2855]
hellow,

I accessed mongodb and looked up the data but it didn't exist.

Is it correct to read json analysis results directly without storing them in mongodb?
If not, is it stored in a table like RDB and exists via a query?

I wonder how cuckoo sandbox analysis results are loaded into the web

thank you for reading.

**Comment by doomedraven** [comment]
Enable mongo in reporting.conf and you will have it

**Comment by AlexKim100** [comment]
This is my setting
[mongodb]
enabled = yes
host = 192.168.100.251
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
# MongoDB authentication (optional).
username = cuckoo
password = 123

 using robomongo, analysis data is not saved

**Comment by doomedraven** [comment]
What do you mean not saved? Yoyr modification or there is no data? Check
logs of mongo and cuckoo something is wrong maybe mongo listens only on
local host, without logs idk

**Comment by AlexKim100** [comment]
After confirming that there are no problems with the cuckoo and mongo logs, I directly connected to the mongodb server and queried the data. My robo 3T seems to have had a problem with ubuntu 16.04
thank you for helping.
