### ISSUE TITLE
Network logs when using inetsim

### ISSUE THREAD

**Issue by noweileen** [cuckoosandbox/cuckoo#2856]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
tcpdump doesn't capture all the traffic when using inetsim as a routing option. I (think I) understand why this happens, but I don't know how to fix it (or what it is that I'm doing wrong). 

* I use inetsim on a REMnux VM
* Cuckoo, Windows analysis VM and REMnux VM are all on the same network
* Cuckoo is set as default gateway for the Windows VM
* Tcpdump is capturing traffic from the Cuckoo interface

When using inetsim, all interesting traffic (basically anything other than ARP and DNS requests) will go directly to the REMnux VM since they're both on the same network and the traffic won't go through the gateway (Cuckoo). This means the traffic won't pass through the interface tcpdump is monitoring, so I won't see it in the Network Analysis results.

Not sure how to fix this without moving the REMnux VM to another network.

##### My Cuckoo version and operating system are:
Cuckoo version 2.0.6
Ubuntu 18.04

##### This can be reproduced by:
Using a different VM for running inetsim and having it on the same network as Cuckoo and the analysis VM.

##### The log, error, files etc can be found at:
N/A

**Comment by doomedraven** [comment]
it should works, i fixed inetsim so many times, are your vms are in host only?

**Comment by noweileen** [comment]
Erm, yeah, kind of? I don't really have host only / bridged / NAT, I just add them to certain networks.

Not sure if this is relevant, but all VMs are part of 2 networks: one used for analysis and one used for Internet access. Usually I keep the network card for the one with Internet access disabled for the Windows VM and REMnux and enabled for Cuckoo. So most of the time (and at the time of analysis), they are all in a contained local network.

**Comment by doomedraven** [comment]
well basically that is the problem, if that would be host only, then rooter would route traffic from vm to inetsim box, bcz in nat they can speak directly

**Comment by noweileen** [comment]
So the issue is that Cuckoo is on 2 networks at the time of analysis?

**Comment by doomedraven** [comment]
kinda, try put windows vm and inetsim in hostonly mode and test it again and you will get the answer

**Comment by noweileen** [comment]
I'm sorry, I don't think I actually understand this.

You're basically saying that the Windows VM and inetsim need to be on the same host and set to host only networking? Overall, for inetsim to work, it needs to be on a different network than Cuckoo and the Windows VM, right? So they can't all be in some 192.168.x.x/24 network?

I cannot set any of the VMs to host only. I can only add them to specific networks.

**Comment by doomedraven** [comment]
They should be in the same network

**Comment by noweileen** [comment]
For whoever else has a similar issue - I deleted the route to the local network on the Windows VM, so it doesn't know 192.168.x.x/24 is on-link and all traffic goes through the gateway (Cuckoo).

**Comment by doomedraven** [comment]
Thanks for your solution
