### ISSUE TITLE
Automating Cuckoo Analysis

### ISSUE THREAD

**Issue by Jon045** [cuckoosandbox/cuckoo#2857]
Hello Team,

I have a Cuckoo Sandbox deployment scenario that I need help with. Basically what I want is that, whenever a user on the network attempts to download a file within a corporate network. That file should not be downloaded directly to a user's endpoint and it should first be passed to cuckoo sandbox (deployed in network) for analysis. After that, if the score is above or below a defined threshold, the file should be blocked or allowed to be download on the user's endpoint. As far as I understand, the file submission mechanism to cuckoo is not controlled at network level and only possible once the file is downloaded on the endpoint. Can you help in figuring out if these controls will be place on network gateway (NGFW maybe) or any other possible solution.

Any help in above matter will be highly appreciated, please let me know. Thanks.

Regards,
Asim Sattar

**Comment by doomedraven** [comment]
i would suggest to go to https://hatching.io/ for that kind of help

**Comment by Jon045** [comment]
Hey @doomedraven,

Thanks. I will reach them out.

**Comment by Jon045** [comment]
Hey @doomedraven 

I emailed at info@hatching.io. I have not received any response from them. Is there any kind of help you can provide me?

**Comment by doomedraven** [comment]
cc @jbremer
