### ISSUE TITLE
Weasyprint

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#2864]
##### The log, error, files etc can be found at:
![image](https://user-images.githubusercontent.com/15255470/64636934-42eebf80-d3f2-11e9-9b31-822932bcf87d.png)

- I have tried install weasyprint and it errors out stating weasyprint for python 2.7 is deprecated.
- I installed python pip3 and all setup libraries.
- I installed weasyprint with pip3
- error captured in image above still persists.

Any ideas how to fix?   Is there a download string to use to get old python 2.7 version of weasyprint that is compatible with cuckoo?

Thanks Guys!!!

**Comment by doomedraven** [comment]
cuckoo is python 2, you can ignore deprication warnings they are totally not related to cuckoo so just use normal pip

**Comment by RANGERBEE** [comment]
found it::  https://github.com/Kozea/WeasyPrint/issues/834


- pip install "weasyprint<43"

**Comment by doomedraven** [comment]
thanks for posting solution
