### ISSUE TITLE
Weasyprint errors

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#2865]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
![image](https://user-images.githubusercontent.com/15255470/64649061-b7822800-d40b-11e9-83b8-68eb6af9f677.png)

##### This can be reproduced by:enabling PDF reporting and installing Weasyprint for Python 2.7,   pip install 'weasyprint<43'

![image](https://user-images.githubusercontent.com/15255470/64649183-ef896b00-d40b-11e9-956a-517b68bb06aa.png)

- Font face awesome can not be loaded.

** Do we have a trick to make it all work? missing installs?  missing a setting?**

Thank you!

**Comment by doomedraven** [comment]
you should use `weasyprint==0.36`
`sudo pip install weasyprint==0.36` if you search by lib name in repo it will get you to correct place

**Comment by RANGERBEE** [comment]
Perfect!  0.36 solves it!   Thanks   @doomedraven

**Comment by doomedraven** [comment]
you are welcome!
