### ISSUE TITLE
Unable to stop auxiliary module: Sniffer/ [tcpdump: Ethernet: No such device exists]

### ISSUE THREAD

**Issue by flycows01** [cuckoosandbox/cuckoo#2871]
##### My issue is:
     My cuckoo Guest is a physical machine,and  OS with windows7.When the analysis is complete, an error like this is prompted .  I think this might be [physical:interface] Configuration error.How should this parameter be configured in Windows 7 physical matchine.

------Sniffer StopProc ID :<subprocess.Popen object at 0x7f123ab81250> self.proc
------Sniffer StopProc Poll() :1 poll 
2019-09-16 13:27:15,011 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/core/plugins.py", line 164, in stop  module.stop()   File "/usr/local/lib/python2.7/dist-packages/Cuckoo-2.0.7-py2.7.egg/cuckoo/auxiliary/sniffer.py", line 159, in stop
    (out, err, faq("permission-denied-for-tcpdump"))
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = '`**tcpdump: Ethernet: No such device exists\n(SIOCGIFHWADDR: No such device)**`\n'. Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor, see also https://cuckoo.sh/docs/faq/index.html#permission-denied-for-tcpdump)?
    
##### My Cuckoo version and operating system are:
Cuckoo version 2.0.7 ,Host :ubuntu 18 LTS

**Comment by doomedraven** [comment]
which iface did you set?
from what i see it should be default whihc you using to connect to internet 
https://github.com/cuckoosandbox/cuckoo/blob/c41c7c5cb09416b7cfc6159811792679e20762f2/cuckoo/private/cwd/conf/physical.conf#L11

**Comment by doomedraven** [comment]
+ duplicated of https://github.com/cuckoosandbox/cuckoo/issues/2860

**Comment by flycows01** [comment]
filepath : /opt/cuckoo/conf/physical.conf
default value is :
# Default network interface.
interface = eth0
I didn't change the file where the filepath is cuckoo/cuckoo/private/cwd/conf/physical.conf,

**Comment by doomedraven** [comment]
can you post ouput of `ip addr`?

**Comment by flycows01** [comment]
guest IP ？
ip = 192.168.12.21

**Comment by doomedraven** [comment]
show me the output of that command, i need all info not only ip

**Comment by flycows01** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:3e:82:c2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.12.30/27 brd 192.168.12.31 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::864a:11d0:100b:f57/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

**Comment by doomedraven** [comment]
and there is answer to your problem, you should use `ens33` and not `eth0`

**Comment by doomedraven** [comment]
and side node, please stay with 1 issue, as you opened this one when you have this one https://github.com/cuckoosandbox/cuckoo/issues/2860, close one

**Comment by flycows01** [comment]
Forgive me for my poor English。
I always think that this interface should be the network interface of the physical machine, because the packet capture should be on the physical machine, and the physical machine can surf the Internet independently.I may not understand this sniffing logic.Can you briefly introduce the process of bag catching?
yes，I will close one

**Comment by doomedraven** [comment]
lang isn't the problem :)

well cuckoo is running on host X, to be able to sniff, you can't sniff on interface to which you don't have access, lets say remote, it requires local where cuckoo is installed, so you need to enable sniffing on interface which connects cuckoo and physical guest, but then once you have that done

**Comment by doomedraven** [comment]
let me know if now it works for you with correct iface

**Comment by flycows01** [comment]
yes, it works well.The warning is gone.

**Comment by doomedraven** [comment]
great

**Comment by flycows01** [comment]
You are a genius. Thank you very much for your help

**Comment by doomedraven** [comment]
you are welcome :)

**Comment by doomedraven** [comment]
close if solved
