### ISSUE TITLE
Problems with debian libcurl4 and mongodb to install Cuckoo

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [cuckoosandbox/cuckoo#2876]
##### The log, error, files etc can be found at: no error logs yet 

I n requierements page before install i see:

 `In order to use the Django-based Web Interface, MongoDB is required:

$ sudo apt-get install mongodb`

With the licencing problems that mongodb has with linux distributions ... there's a way to install cuckoo in debian 10 avoiding using mongodb????

**Comment by doomedraven** [comment]
which is the problem of mongodb with linux? without mongo you won't have webgui, so it will be 90% useless to deal with all processed information, but for best performance and works cuckoo is done for ubuntu 18.04 lts.

**Comment by BernaldoPenasAntelo** [comment]
Hi:
First of all thanks for your reply, the problem with mongo and linux, as far as i have read,  is related with licences, all linux distributions had remove the mongo packages from repositories ... i supouse you know about the issue ... but anyway ...

My problem with Debian 10 is that looks like debian it's using libcurl4 and .deb packages that provides mongo, im triying to follow the original mongo installation steps provided by mongo.

So i get errors like:

   mongodb-org : Depends: mongodb-org-shell it's not going to be installed
               Depends: mongodb-org-server it's not going to be installed
               Depends: mongodb-org-mongos it's not going to be installed

 mongodb-org-server : Depends: libcurl3 (>= 7.16.2) not installable.

So .. it's my only option use an ubuntu18.04 as linux .deb distribution ??
Or there's any way/walktrhough to install it on my choosen distribution?

Best regards.

**Comment by doomedraven** [comment]
i had that in past, with google i have solved that, but i don't remember the steps, on stackoverflow you have the answer for this, that isn't debian problem,but yes if you want the best experience i would you suggest move to ubuntu 18

+ you can use https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh
./cuckoo.sh v2 all

that will install you all dependencies with performance tweaks, works only on ubuntu

**Comment by BernaldoPenasAntelo** [comment]
Thanks for your response, im going to keep triying to find a way to solve this dependencies problems with mongo, and still count on a stable debian.
I'm going to leave this issue open to see if someone else can help with it, but anyway thanks again, as always, all help is usefull.

**Comment by doomedraven** [comment]
well you will have a lot of different libraries problems, you know debian stable bcz a lot of libraries are outdated

**Comment by BernaldoPenasAntelo** [comment]
Hi:

I have recently discover that mongo had updated their repositories, now and finally mongo works fine again in debian 10.

U can follow the official installation link:

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/

testes and working.

Best regards.
