### ISSUE TITLE
Issue with Pillow and Screenshots - PIL/Pillow is not installed

### ISSUE THREAD

**Issue by connor-craig** [cuckoosandbox/cuckoo#2885]
Hey guys, hoping someone can help, i've read all the cuckoo + pillow docs but havent managed to fix this
##### My issue is:

I have configured cuckoo 2.0.7 on an ubuntu install, using a windows 7 guest and i can currently not get screenshots from analysis. I have verified that both host and guest have python (2.7) and pillow (3.2.0) installed (using pip), and running a test screenshot in the guest works perfectly. 

All other analysis is reporting properly it is just the screenshots. Ive tried with different versions of pillow on both host and guest and still the same issue. 

When looking in the analyser log for a sample, i get the error message that PIL/Pillow is not installed. 

##### My Cuckoo version and operating system are: 
Cuckoo 2.0.7, Ubuntu Host, Windows 7 Guest

**Comment by d4n13l4** [comment]
Did you modify processing.conf file? there is a part that says [screenshots] enabled=no

**Comment by connor-craig** [comment]
I have modified processing.conf and screenshots are set to enabled in that file.

**Comment by chavezn** [comment]
Are you using 32bit python and pillow?

I just checked and I have Pillow-6.1.0.win32-py2.7.  I did not install Pillow with pip, fyi.

**Comment by connor-craig** [comment]
Yes, i am using 32 bit python and pillow.

Would installing Pillow manually change anything?

**Comment by connor-craig** [comment]
I've still been unable to resolve this issue. If anyone has any other ideas it would be greatly appreciated

**Comment by RicoVZ** [comment]
Hi @connor-craig,

Thanks for posting the issue.

I tried to reproduce, but have not been able to (yet). Could you try installing the following version of Pillow in your analysis VM? https://pypi.python.org/packages/2.7/P/Pillow/Pillow-2.9.0.win32-py2.7.exe

This is the version I use.

**Comment by connor-craig** [comment]
Hey @RicoVZ  i was also unable to reproduce the issue after redeploying a fresh install of cuckoo and a fresh windows 7 VM, might have been something corrupt that wasn't working but doing a redeploy fixed the issue. 

Closing as there isnt really anything to fix if its not reproducible.
