### ISSUE TITLE
emotet-malware which is not recognized by cuckoo

### ISSUE THREAD

**Issue by thegrillmaster** [cuckoosandbox/cuckoo#2888]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
Hello everyone, I have a question. I received an emotet-malware which is not recognized by cuckoo. As a supplement the malware, password "infected". Does anyone have an idea what you have to adjust at Cuckoo, so that this malware is detected? Thank you very much for the answer.

##### This can be reproduced by:
[Anhang_Q-723-NGI3699.zip](https://github.com/cuckoosandbox/cuckoo/files/3705874/Anhang_Q-723-NGI3699.zip)

**Comment by thegrillmaster** [comment]
[analyzer.txt](https://github.com/cuckoosandbox/cuckoo/files/3706004/analyzer.txt)
[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/3706005/cuckoo.txt)

**Comment by thegrillmaster** [comment]
[analyzer.txt](https://github.com/cuckoosandbox/cuckoo/files/3706047/analyzer.txt)
[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/3706048/cuckoo.txt)

**Comment by doomedraven** [comment]
pretty simple, cuckoo is opensource so here is work which you need to do, to be able to detect everything, you can read docs and write your own signatures

**Comment by thegrillmaster** [comment]
Thanks for your support, that helps a lot.
