### ISSUE TITLE
  Cuckoo Android

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2898]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are: 2.0.6

Hi,
it is possible to integrate or installed cuckoo Android to scan android malware via android emulator
thank you

**Comment by Evert0x** [comment]
Hi, android analysis is not integrated in this version of cuckoo, but you can take a look at this repo https://github.com/muhzii/cuckoo/wiki/Cuckoo-Android-analysis. This fork is supporting android analysis.

**Comment by RicoVZ** [comment]
Hi nadir3392,

Thanks to @muhzii, there is a recent fork of Cuckoo supporting Android analysis. :tada: 
A PR (https://github.com/cuckoosandbox/cuckoo/pull/2845) was made and will be merged in the future (we are working on lots of internal changes first). 

Meanwhile, the PR does work well.

**Comment by nadir3392** [comment]
thank you for all.
