### ISSUE TITLE
cuckoo with a scan by a multitude of antivirus

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2900]
Hi,
I want to integrate in cuckoo sandbox, installed on my offline server, antivirus which are installed each in a vmware, to scan offline the sample that must be scanned by cuckoo by several antivirus and display the scan results in the cukkoo interface (in the space of IRMA and VirusTotal) 
can you help me!!!!!!!!!
thanks.

**Comment by Evert0x** [comment]
Hi, cuckoo does not support this functionality out of the box. With the cuckoo api you are able to create this workflow. Do you have any questions about the api?

**Comment by RicoVZ** [comment]
Hi @nadir3392,

Thanks for posting an issue.

From what I understand, you want to integrate extra information into the Cuckoo web interface?

To do so, you have to first make it available by creating a processing module or expanding an existing processing module, such as the IRMA module. See https://cuckoo.sh/docs/customization/processing.html for more information about that.

To then display this in the web interface at the IRMA section, you can expand the IRMA (or another) web template with the information you want to add: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/web/templates/analysis/pages/static/_irma.html

**Comment by nadir3392** [comment]
thank's i'm trying to do.
