### ISSUE TITLE
install process(using pip -U cuckoo ) stopped

### ISSUE THREAD

**Issue by yiiq** [cuckoosandbox/cuckoo#2905]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:
![Screenshot from 2019-11-20 11-00-59](https://user-images.githubusercontent.com/45310996/69205503-18a14700-0b85-11ea-806c-ff1353eced74.png)

**Comment by noideal** [comment]
you need a version of python that is greater than 3 installed on the machine for the 'more-itertools' package.  Cuckoo requires 2.7 so that won't work.
You can have both installed at the same time.

**Comment by yiiq** [comment]
> you need a version of python that is greater than 3 installed on the machine for the 'more-itertools' package. Cuckoo requires 2.7 so that won't work.
> You can have both installed at the same time.

I did installed more-itertools with pip3, but when I install cuckoo using pip2, it still says the error I posted
