### ISSUE TITLE
strange DrawTextExA arguments strings

### ISSUE THREAD

**Issue by qux-bbb** [cuckoosandbox/cuckoo#2906]
##### My issue is:
If call an api like this:  
```c
DrawTextExA(hdc, LPSTR("你好"), -1, &rect, DT_SINGLELINE | DT_CENTER | DT_VCENTER, NULL);
```
The output is:  
```json
{
    "category": "ui",
    "status": 1,
    "stacktrace": [],
    "api": "DrawTextExA",
    "return_value": 179,
    "arguments": {
        "string": "\u00c4\u00e3\u00ba\u00c3"
    },
    "time": 1574315902.0465,
    "tid": 3436,
    "flags": {}
}
```
The `"string": "\u00c4\u00e3\u00ba\u00c3"` is strange. The expected result should be `"string": "\u4f60\u597d"`  
##### My Cuckoo version and operating system are:
2.0.6  
ubuntu win7  
##### This can be reproduced by:
Check the attachment.    
##### The log, error, files etc can be found at:
Refer to the above  
[DrawTextExA_chinese.zip](https://github.com/cuckoosandbox/cuckoo/files/3873048/DrawTextExA_chinese.zip)

**Comment by Evert0x** [comment]
Hi, thank you for creating the issue. I can confirm that your sample is not displaying the right characters. Are you able to share the source code of the sample?

**Comment by qux-bbb** [comment]
Just like this:  
![image](https://user-images.githubusercontent.com/18598419/70300396-5fa06500-1832-11ea-99bc-6f7277badea5.png)

**Comment by qux-bbb** [comment]
Sorry for so long time to write to you.
The code is:
	case WM_PAINT:
	{
		PAINTSTRUCT ps;
		RECT&nbsp; &nbsp; &nbsp; &nbsp; rect;
		HDC hdc = BeginPaint(hWnd, &amp;ps);
		// TODO: 在此处添加使用 hdc 的任何绘图代码...
		GetClientRect(hWnd, &amp;rect);
		DrawTextExW(hdc, LPWSTR(L"你好"), -1, &amp;rect, DT_SINGLELINE | DT_CENTER | DT_VCENTER, NULL);
		EndPaint(hWnd, &amp;ps);
	}
You can also check the attachment.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Evert0x"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 晚上6:28
收件人:&nbsp;"cuckoosandbox/cuckoo"<cuckoo@noreply.github.com&gt;;
抄送:&nbsp;"rvy"<1147635419@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuckoosandbox/cuckoo] strange DrawTextExA arguments strings (#2906)




Hi, thank you for creating the issue. I can confirm that your sample is not displaying the right characters. Are you able to share the source code of the sample?

**Comment by qux-bbb** [comment]
The code is:  
```c
	case WM_PAINT:
	{
		PAINTSTRUCT ps;
		RECT        rect;
		HDC hdc = BeginPaint(hWnd, &ps);
		// TODO: 在此处添加使用 hdc 的任何绘图代码...
		GetClientRect(hWnd, &rect);
		DrawTextExW(hdc, LPWSTR(L"你好"), -1, &rect, DT_SINGLELINE | DT_CENTER | DT_VCENTER, NULL);
		EndPaint(hWnd, &ps);
	}
```
You can also check the attachment.  
[WindowCreate.zip](https://github.com/cuckoosandbox/cuckoo/files/3943807/WindowCreate.zip)

**Comment by RicoVZ** [comment]
Hi qux-bbb,

Thanks for sharing the code. The logged result seems to depend on the system language. Our VMs are set to US English.

Thanks for reporting this, but so far, we can't really solve it, as it seems to be simply how Windows works internally.

**Comment by qux-bbb** [comment]
I see. Thanks.
