### ISSUE TITLE
yara rules probleme 

### ISSUE THREAD

**Issue by nadir3392** [cuckoosandbox/cuckoo#2908]
Hi,
My cuckoo 2.0.7, guest Windows 7 64 bits, 
I have a problem during the installation of Yara Rules, knowing that I integrate the rules exist in the github project via the link https://github.com/Yara-Rules/rules/, and I copy the rules in the folder .cuckoo/yara /binaries, 
but a problem appears during the initialization of yara after launching cuckoo (cucko -d)
Thanks for your help.

> here is the log that contains the error

2019-11-23 10:26:32,018 [cuckoo.core.startup] DEBUG: Checking for locked tasks..
2019-11-23 10:26:32,139 [cuckoo.core.startup] DEBUG: Checking for pending service tasks..
2019-11-23 10:26:32,221 [cuckoo.core.startup] DEBUG: Initializing Yara...
2019-11-23 10:26:32,579 [cuckoo] CRITICAL: CuckooStartupError: There was a syntax error in one or more Yara rules: /home/cuckoo/.cuckoo/yara/binaries/malware/MALW_AZORULT.yar(23): invalid field name "sync"

**Comment by Evert0x** [comment]
Hi, thank you for creating the issue. This issue treats the same question: https://github.com/cuckoosandbox/cuckoo/issues/2299

Please let me know if you need more information

**Comment by nadir3392** [comment]
the problem is fixed for the yara rules, but I have another problem when the size of the analysis report exceeds 16M.
"bson document too large mongodb"

**Comment by Evert0x** [comment]
Good to hear! This is a common known issue in cuckoo. I noticed you already posted it on https://github.com/cuckoosandbox/cuckoo/issues/877. This issue is giving more info about it https://github.com/cuckoosandbox/cuckoo/issues/358, and provides a solution from @doomedraven

**Comment by doomedraven** [comment]
yep people never search before post :D thanks @Evert0x for point him

search in issues can save a lot of time

**Comment by RicoVZ** [comment]
Duplicate. Please see and use issue #358 for potential solutions.

**Comment by nadir3392** [comment]
Hi
I want a configuration of my cuckoo similar to that of https://cuckoo.cert.ee/
since it gives a good result with YARA, and all the tools installed and operated by couckoo.
see WannaCry results https://cuckoo.cert.ee/analysis/1434120/dropped_buffers/
thank's.
