### ISSUE TITLE
Untracked Bootstrap Operations in Analysis Package?

### ISSUE THREAD

**Issue by dasfreak** [cuckoosandbox/cuckoo#2917]
##### My issue is:
I am currently trying to add my own analysis package.
It performs some preparations before the actual launch of the process I want to track.
Is it possible to do bootstrap operations on the guest that are not tracked, i.e. excluded from the report?
I need the path variable for that but it is not available in `__init__`.

##### My Cuckoo version and operating system are:
2.0.7 with Ubuntu 18.04 guest

##### This can be reproduced by:
Adding new analysis package. Everything called in `start(self, path)` like Popen is tracked.

**Comment by RicoVZ** [comment]
Hi @dasfreak,

Thanks for posting an issue.

Yes, it is possible to perform actions before starting the tracked process/sample. Guest Auxiliary modules are meant for this. These are examples of some of those: https://github.com/cuckoosandbox/cuckoo/tree/master/cuckoo/data/analyzer/windows/modules/auxiliary.

They are started before the sample is started. The screenshots module is one of them, and so is the human interaction simulation module.

Another example which installs a certificate: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/analyzer/windows/modules/auxiliary/installcert.py.

**Comment by dasfreak** [comment]
Hi @RicoVZ,

thank you very much for the hints!
I will now close this issue.

Best,
dasfreak
