### ISSUE TITLE
https://cuckoosandbox.org site has been down for 3 days.

### ISSUE THREAD

**Issue by djigga80** [cuckoosandbox/cuckoo#2919]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at:  This issue doesn't allow me to get updated cuckoo signatures:

Checking for updates...
 Error checking for the latest Cuckoo version: HTTPSConnectionPool(host='cuckoosandbox.org', port=443): Max retries exceeded with url: /updates.json?version=2.0.7 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f41204568d0>, 'Connection to cuckoosandbox.org timed out. (connect timeout=6)'))!
2019-12-06 12:14:56,780 [cuckoo] WARNING: It appears that you haven't loaded any Cuckoo Signatures. Signatures are highly recommended and improve & enrich the information extracted during an analysis. They also make up for the analysis score that you see in the Web Interface - so, pretty important!
2019-12-06 12:14:56,781 [cuckoo] WARNING: You'll be able to fetch all the latest Cuckoo Signatures, Yara rules, and more goodies by running the following comman

Please advise

**Comment by djigga80** [comment]
I have ran cukoo community command and it resolved that error. However,  why did the site go down??

**Comment by Evert0x** [comment]
Hi, we are currently working to get cuckoosandbox.org back up again.

**Comment by RicoVZ** [comment]
Hi @djigga80,

As @Evert0x points out, we are indeed currently working on getting it online again. Still thanks for reporting it, though! :slightly_smiling_face:  Unfortunately, we are experiencing some issues with this. We will let you know when it is back online.

**Comment by djigga80** [comment]
Evert0x and RicoVZ.  Thank you for the heads up.  Is there an ETA or time frame the site is expected to come back up?  If not thats ok I'll wait.

**Comment by RicoVZ** [comment]
The website is back online. :slightly_smiling_face: 
I'll be closing this issue, feel free to re-open it if there is another related question.
