### ISSUE TITLE
Is Cuckoo supported under Windows WSL running Ubuntu 18.04LTS or 16.04LTS

### ISSUE THREAD

**Issue by iq-sciental** [cuckoosandbox/cuckoo#2935]
Hi,
Environment is:
Main host operating system is Windows 10 64 bit with Ubuntu 18.04 linux subsystem
Cuckoo version: 2.0.6
Virtual machine: Win10 64 bit using the Windows 10 above as host

I'm trying to help a friend to get cuckoo working using the above configuration. I wanted to know if it is possible to run cuckoo under the above configuration?
After installation, when we configure tcpdump, apparmor seems to install but the command:

$ sudo aa-disable /usr/sbin/tcpdump

results in an error:
ERROR: Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.

Is this because of the configuration we are using and a limitation of the WSL running Ubuntu under Windows?
Thanks,
iq

**Comment by SparkyNZL** [comment]
Hi,

 

The windows subsystems doest not currently support the required access to network ports which is required for cuckoo to be of any use.

 

Unless of course MS have recently changed this recently.

 

Thanks.

**Comment by doomedraven** [comment]
nah WLS isn't supported 

@jbremer merge docs update about this https://github.com/cuckoosandbox/cuckoo/pull/2820

**Comment by iq-sciental** [comment]
How so? This person claims to be able to use cuckoo under Windows & WLS using Ubuntu:

http://www.sanjaysaha.info/blog/installation-of-cuckoo-sandbox-in-windows-10/

**Comment by doomedraven** [comment]
well you can run it but not all feature will be accesible and nobody knows what wil lfail and when, and never trust to nobody in internet, is easy to claim stuff :D

**Comment by doomedraven** [comment]
@jbremer  can be closed as not supported
