### ISSUE TITLE
Vm has no internet access

### ISSUE THREAD

**Issue by gmndz90** [cuckoosandbox/cuckoo#2940]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are:

Cuckoo : 2.0.7
OS: Linux Mint 19.2

**Comment by IceM4nn** [comment]
When you setting up your VM guest (before the snapshot) can you get access to the internet?

**Comment by RicoVZ** [comment]
Hi gmndz90,

Thanks for posting an issue.

Do you have Cuckoo Rooter running? Options such as the internet one cause Cuckoo to send a message to Cuckoo Rooter just before the analysis. Rooter will then create iptables rules for the analysis VM and remove them afterwards.

For this to work, Rooter must be running.
https://cuckoo.sh/docs/usage/rooter.html?highlight=rooter#cuckoo-rooter

**Comment by gmndz90** [comment]
@IceM4nn Correct. I can access the internet. Currently it is set with a static IP and is only talking with the host. If I perform a Curl from the Host OS to the VM, I get results indicating that the cuckoo agent is up. If I change the network settings to bridge, or NAT, and IP to Dynamic, then it can access the internet. 

@RicoVZ  Correct, I am running Rooter. I have used rooter the following ways: 
_sudo ~/venv/bin/cuckoo rooter_
_cuckoo rooter --sudo_  (Within the virtualenv)
![image](https://user-images.githubusercontent.com/48963891/72539881-ddde2700-3834-11ea-813b-412e6b782cc3.png)

**Comment by RicoVZ** [comment]
@gmndz90 

Thanks for the reply. It looks like Rooter is receiving the commands, this is good. :slightly_smiling_face: .

Have you enabled forwarding on your `vboxnet0` and outgoing interface?
```
sysctl -w net.ipv4.conf.vboxnet0.forwarding=1
sysctl -w net.ipv4.conf.<outgoing interface>.forwarding=1
```

**Comment by gmndz90** [comment]
@RicoVZ 
I did. I ran both commands and ensured I used the proper interface for the outgoing interface. My vm still gets no internet access. None of my URL submissions resolve.
