### ISSUE TITLE
Suricata 5.01 no longer supports file-log

### ISSUE THREAD

**Issue by andyrat33** [cuckoosandbox/cuckoo#2956]
#### My issue is:
The file-log is no longer supported in suricata
 [ERRCODE: SC_ERR_NOT_SUPPORTED(225)] - file-log is no longer supported, use eve.files instead (see https://redmine.openinfosecfoundation.org/issues/2376 for an explanation)
See the upgrade notes in suricata
https://suricata.readthedocs.io/en/suricata-5.0.1/upgrade.html#upgrading-4-1-to-5-0

file-log, the non-EVE JSON file log. Use EVE.files instead.

##### My Cuckoo version and operating system are:
Cuckoo 2.0.7
Ubuntu 18.0.4.3

The solution would be to use eve.files as the Suricata manual suggests or to create the correct settings for eve.files and override the default filename.

**Comment by noideal** [comment]
I don't believe v5 is supported as it would require a bunch of modifications to the processing script.
I've done a bit of work on this, but mostly in a private branch - here's a bit of an example of what would need to be changed (not complete at all): https://github.com/noideal/cuckoo/commit/febbbfd2471ef2dfcb5a4d8c18331b3cb5474db9#diff-7016e169854cfaf3ec567d564efea29c

**Comment by andyrat33** [comment]
Had not noticed it wasn’t supported.
