### ISSUE TITLE
List of Signatures

### ISSUE THREAD

**Issue by AliAlnuaimi** [cuckoosandbox/cuckoo#2991]
Hi guys,

Is there any place where i can find list of ALL signatures in Cuckoo please?

**Comment by nadir3392** [comment]
what type of signature you need, there are many signatures, if you want the signature of cummunity or  signature of yara rules, please specify more detail.
thanks

**Comment by doomedraven** [comment]
community repository thats all ;)

**Comment by nadir3392** [comment]
hi @doomedraven ,

**Comment by AliAlnuaimi** [comment]
Guys, this is resolved!

**Comment by PassKa** [comment]
@AliAlnuaimi , how do you find all signatures?  now I only found them in community!
