### ISSUE TITLE
IT WORKS! Thanks a fucking lot! the problem was the $cwd!

### ISSUE THREAD

**Issue by Abadeolu** [cuckoosandbox/cuckoo#2996]
IT WORKS! Thanks a fucking lot! the problem was the $cwd!
I close the issue
Thank you very much.

_Originally posted by @R42E in https://github.com/cuckoosandbox/cuckoo/issues/2572#issuecomment-446945707_

Can you help me out with this?
I do not know how to edit the CWD as you said.

**Comment by doomedraven** [comment]
lol you can close this

**Comment by Abadeolu** [comment]
Can I reach you via Email for any help, if yes let me know before I close this.
Thanks.

**Comment by doomedraven** [comment]
no sorry im not doing support anymore
