### ISSUE TITLE
Distributed cuckoo configuration

### ISSUE THREAD

**Issue by CiraciNicolo** [cuckoosandbox/cuckoo#3027]
We're trying to create a distributed cuckoo configuration, but I'm missing some key ideas behind the correct configuration. We set up different machine already, explained below. Is this configuration in the specifications? Which node should I add to the distributed instance? All of them, including the web and rest api or just the workers? Do I need both REST and Distributed apis running?

```
+=========================+         
|      Host: db01         |
+-------------------------+
| PSQL Databases:         | 
|    cuckoo               |
|    distributed          |
+-------------------------+
| Mongo Databases:        | 
|    cuckoo               |
+=========================+ 

+=========================+
|      Host: cuckoo01     |
+-------------------------+ 
| Services:               |  
|    Cuckoo Web           |
|    Cuckoo REST API      |
|    Distributed REST API |
+=========================+ 

+=========================+          +=========================+
|     Host: cuckoo-w01    |          |     Host: cuckoo-w02    |
+-------------------------+          +-------------------------+
| Services:               |          | Services:               |
|    Cuckoo Deamon        |          |    Cuckoo Daemon        |
|    KVM                  |          |    KVM                  |
+=========================+          +=========================+
```

**Comment by nadir3392** [comment]
Hi
thank's 
first, for the configuration of the cuckoo distributed, you must configure a Master node which manages the other nodes, this node carries the cuckoo-daemo + cuckoo-distributed + Distributed REST API + cuckoo distributed instance name-instance, the other nodes carries the cuckoo-daemo + Cuckoo REST API.
if you want something about cuckoo distributed mache very well.

**Comment by nadir3392** [comment]
finally
it's work for me, but i can submit the samples in CLI only. (cuckoo distributed)
