### ISSUE TITLE
Run cuckoo without VBOX GUI

### ISSUE THREAD

**Issue by ByamB4** [cuckoosandbox/cuckoo#3046]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
I want to install `cuckoo` in my ubuntu server which is no GUI, So i can't simply run VBOX with GUI, is it possible to run cuckoo without having VBOX GUI ?

**Comment by BlastyCZ** [comment]
Sure, it is possible. VBoxManage is what you are looking for.

https://www.virtualbox.org/manual/ch08.html
