### ISSUE TITLE
Cuckoo stuck on still processing 

### ISSUE THREAD

**Issue by D0C1P** [cuckoosandbox/cuckoo#3061]
Hello,

I have a little problem when I try to  a sample my cuckoo stuck at "analysis #N still processing"

> 2020-07-02 10:34:31,653 [cuckoo.core.startup] WARNING: Missing Yara directory: /opt/cuckoo/yara/dumpmem?                                       
> 2020-07-02 10:34:31,654 [cuckoo.core.startup] WARNING: Missing Yara directory: /opt/cuckoo/yara/office?                                        
> 2020-07-02 10:34:31,655 [cuckoo] WARNING: It appears that you haven't loaded any Cuckoo Signatures. Signatures are highly recommended and impro
> ve & enrich the information extracted during an analysis. They also make up for the analysis score that you see in the Web Interface - so, pret
> ty important!                                                                               
> 2020-07-02 10:34:31,655 [cuckoo] WARNING: You'll be able to fetch all the latest Cuckoo Signatures, Yara rules, and more goodies by running the
>  following command:                                                                           
> 2020-07-02 10:34:31,655 [cuckoo] INFO: $ cuckoo --cwd /opt/cuckoo community              
> 2020-07-02 10:34:31,658 [cuckoo.core.scheduler] INFO: Using "kvm" as machine manager                       
> 2020-07-02 10:34:31,691 [cuckoo.common.abstracts] DEBUG: Getting status for win10                                             
> 2020-07-02 10:34:31,721 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s                                       
> 2020-07-02 10:34:31,732 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.                     
> 2020-07-02 10:34:56,724 [cuckoo.core.scheduler] DEBUG: Processing task #16                                  
> 2020-07-02 10:34:56,748 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41
> aa.exe" (task #16, options "procmemdump=yes,route=none")                                                    
> 2020-07-02 10:34:56,871 [cuckoo.core.scheduler] INFO: Task #16: acquired machine cuckoo1 (label=win10)
> 2020-07-02 10:34:56,871 [cuckoo.core.resultserver] DEBUG: Now tracking machine 192.168.122.216 for task #16
> 2020-07-02 10:34:56,872 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Replay                
> 2020-07-02 10:34:56,883 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 5951 (interface=virbr0, host=192.168.122.216)
> 2020-07-02 10:34:56,884 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer                   
> 2020-07-02 10:34:57,034 [cuckoo.common.abstracts] DEBUG: Starting machine win10                               
> 2020-07-02 10:34:57,034 [cuckoo.common.abstracts] DEBUG: Getting status for win10                       
> 2020-07-02 10:34:57,081 [cuckoo.common.abstracts] DEBUG: Using snapshot 1593677135 for virtual machine win10   
> 2020-07-02 10:35:03,898 [cuckoo.common.abstracts] DEBUG: Getting status for win10                   
> 2020-07-02 10:35:03,955 [cuckoo.core.guest] INFO: Starting analysis #16 on guest (id=cuckoo1, ip=192.168.122.216)
> 2020-07-02 10:35:04,003 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.10 (id=cuckoo1, ip=192.168.122.216)
> 2020-07-02 10:35:04,127 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.122.216, monitor=latest, size=1720485)
> 2020-07-02 10:35:05,224 [cuckoo.core.resultserver] DEBUG: Task #16: live log analysis.log initialized.
> 2020-07-02 10:35:09,960 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:15,025 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:20,095 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:25,174 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:30,254 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:35,331 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:40,418 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 2020-07-02 10:35:45,499 [cuckoo.core.guest] DEBUG: cuckoo1: analysis #16 still processing
> 
> [...]
> 2020-07-02 10:38:05,865 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Replay
> 2020-07-02 10:38:05,934 [cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
> 2020-07-02 10:38:05,935 [cuckoo.common.abstracts] DEBUG: Stopping machine win10
> 2020-07-02 10:38:05,935 [cuckoo.common.abstracts] DEBUG: Getting status for win10
> 2020-07-02 10:38:06,617 [cuckoo.common.abstracts] DEBUG: Getting status for win10
> 2020-07-02 10:38:06,650 [cuckoo.core.resultserver] DEBUG: Stopped tracking machine 192.168.122.216 for task #16
> 2020-07-02 10:38:06,650 [cuckoo.core.resultserver] DEBUG: Cancel <Context for LOG> for task 16
> 2020-07-02 10:38:06,669 [cuckoo.core.scheduler] DEBUG: Released database task #16
> 2020-07-02 10:38:06,724 [cuckoo.core.plugins] DEBUG: Executed processing module "AnalysisInfo" for task #16
> 2020-07-02 10:38:06,732 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
> 2020-07-02 10:38:06,734 [cuckoo.core.plugins] DEBUG: Executed processing module "BehaviorAnalysis" for task #16
> 2020-07-02 10:38:06,735 [cuckoo.core.plugins] DEBUG: Executed processing module "Dropped" for task #16
> 2020-07-02 10:38:06,735 [cuckoo.core.plugins] DEBUG: Executed processing module "DroppedBuffer" for task #16
> 2020-07-02 10:38:06,854 [cuckoo.core.plugins] DEBUG: Executed processing module "MetaInfo" for task #16
> 2020-07-02 10:38:06,855 [cuckoo.core.plugins] DEBUG: Executed processing module "ProcessMemory" for task #16
> 2020-07-02 10:38:06,855 [cuckoo.core.plugins] DEBUG: Executed processing module "Procmon" for task #16
> 2020-07-02 10:38:06,856 [cuckoo.core.plugins] DEBUG: Executed processing module "Screenshots" for task #16
> 2020-07-02 10:38:08,439 [cuckoo.core.plugins] DEBUG: Executed processing module "Static" for task #16
> 2020-07-02 10:38:08,806 [cuckoo.core.plugins] DEBUG: Executed processing module "Strings" for task #16
> 2020-07-02 10:38:08,923 [cuckoo.core.plugins] DEBUG: Executed processing module "TargetInfo" for task #16
> 2020-07-02 10:38:11,121 [cuckoo.core.plugins] DEBUG: Executed processing module "NetworkAnalysis" for task #16
> 2020-07-02 10:38:11,122 [cuckoo.core.plugins] DEBUG: Executed processing module "Extracted" for task #16
> 2020-07-02 10:38:11,122 [cuckoo.core.plugins] DEBUG: Executed processing module "TLSMasterSecrets" for task #16
> 2020-07-02 10:38:11,125 [cuckoo.core.plugins] DEBUG: Executed processing module "Debug" for task #16
> 2020-07-02 10:38:11,125 [cuckoo.core.plugins] DEBUG: Running 0 signatures
> 2020-07-02 10:38:11,142 [cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
> 2020-07-02 10:38:11,528 [cuckoo.core.plugins] DEBUG: Executed reporting module "MongoDB"
> 2020-07-02 10:38:11,530 [cuckoo.core.scheduler] INFO: Task #16: reports generation completed
> 2020-07-02 10:38:11,551 [cuckoo.core.scheduler] INFO: Task #16: analysis procedure completed

My environment is the follow:
* XUBUNTU 18.04 for physical hardware
* KVM
* Windows 10 as guest 

At network  I tested the Host isolation and nat network and I have the same problem

> 
> -A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
> INPUT ACCEPT [3426:5803750]
> FORWARD DROP [0:0]
> OUTPUT ACCEPT [2233:111135]
> COMMIT
> *nat
> :PREROUTING ACCEPT [156:59694]
> :INPUT ACCEPT [15:5556]
> :OUTPUT ACCEPT [500:36324]
> :POSTROUTING ACCEPT [500:36324]
> -A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
> -A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
> -A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
> -A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
> -A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
> COMMIT

# From the agents sides:

> cuckoo@bryan-UX305CA:/opt/cuckoo/storage/analyses/latest$ tail -f analysis.log 
2020-07-02 10:08:31,038 [analyzer] DEBUG: Starting analyzer from: C:\tmpwqpwgx
2020-07-02 10:08:31,038 [analyzer] DEBUG: Pipe server name: \??\PIPE\LbBmnDhiTFWPaVncryZE
2020-07-02 10:08:31,038 [analyzer] DEBUG: Log pipe server name: \??\PIPE\TQqOzTMxULxZVPTNkrALgDKwpoH
2020-07-02 10:08:31,349 [analyzer] DEBUG: Started auxiliary module DbgView
2020-07-02 10:08:31,819 [analyzer] DEBUG: Started auxiliary module Disguise

I can reach my agent using : curl 192.168.122.126

> cuckoo@LAB1:/opt/cuckoo/storage/analyses/latest$ curl 192.168.122.216:8000
{"message": "Cuckoo Agent!", "version": "0.10", "features": ["execpy", "pinning", "logs", "largefile", "unicodepath"]}

##### My Cuckoo version and operating system are:
My cuckoo version is : Cuckoo Sandbox 2.0.7
My OS is : Xubuntu 18.04

Thanks.

**Comment by doomedraven** [comment]
read the docs, you need to start processing

**Comment by D0C1P** [comment]
Hello,

Thanks for your answer, but I found my problem I had the IP in the kvm.conf and it's work.
