### ISSUE TITLE
No more uploads of IOCs to MISP due to outdated PyMISP

### ISSUE THREAD

**Issue by icepaule** [cuckoosandbox/cuckoo#3144]
##### My issue is:
That I can't upload the Cuckoo results to MISP as the version of pymisp of cuckoo is outdated. But it cannot be upgraded due to that py2 is not supported at pymisp any more.

Is there a way of only using py3 for the MISP reporting and py2 for all the other cuckoo stuff. (Question might be stupid, so pls excuse)

##### My Cuckoo version and operating system are:
2.0.7 / UBuntu 18.0.4 LTS

##### This can be reproduced by:
Running an analysis.

##### The log, error, files etc can be found at:

_The version of PyMISP recommended by the MISP instance (2.4.135) is newer than the one you're using now (2.4.106). Please upgrade PyMISP._

**Comment by likescam** [comment]
The version of PyMISP recommended by the MISP instance (2.4.135) is newer than the one you're using now (2.4.106). Please upgrade PyMISP.<= this just a warning message. you can ignore it. All IOC send to MISP server!

**Comment by icepaule** [comment]
Hi @likescam,

thx a lot for your reply. Pls see the complete error message below. In my bad, I thought the error was related to the version mismatch, but while you are right (i's only a warning) the actual error seems to have another source.

Is there any chance you could help with the actuall error as well?

Thanks a lot for your help and stay healthy.  ;-)
Marcus

_2020-12-07 06:22:33,200 [pymisp] WARNING: The version of PyMISP recommended by the MISP instance (2.4.135) is newer than the one you're using now (2.4.106). Please upgrade PyMISP.
2020-12-07 06:22:34,147 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MISP
Traceback (most recent call last):
  File "/home/analyst/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 659, in process
    current.run(self.results)
  File "/home/analyst/venv/local/lib/python2.7/site-packages/cuckoo/reporting/misp.py", line 185, in run
    mispresult = self.misp.tag(event["Event"]["uuid"], tag)
KeyError: 'Event'_

**Comment by likescam** [comment]
> Hi @likescam,
> 
> thx a lot for your reply. Pls see the complete error message below. In my bad, I thought the error was related to the version mismatch, but while you are right (i's only a warning) the actual error seems to have another source.
> 
> Is there any chance you could help with the actuall error as well?
> 
> Thanks a lot for your help and stay healthy. ;-)
> Marcus
> 
> _2020-12-07 06:22:33,200 [pymisp] WARNING: The version of PyMISP recommended by the MISP instance (2.4.135) is newer than the one you're using now (2.4.106). Please upgrade PyMISP. 2020-12-07 06:22:34,147 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MISP Traceback (most recent call last): File "/home/analyst/venv/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 659, in process current.run(self.results) File "/home/analyst/venv/local/lib/python2.7/site-packages/cuckoo/reporting/misp.py", line 185, in run mispresult = self.misp.tag(event["Event"]["uuid"], tag) KeyError: 'Event'_

Hi, 
The log show that you dont have the MISP key or your API key invaild,
You just need to replace your right MISP API key in cuckoo config file, so cuckoo can send IOC to MISP.

**Comment by icepaule** [comment]
Hi @likescam,

the API was the hint...

After using the right API (need to be a "publisher") AND the correct distribution ID it's now working again.

The help others, you'd rather check **/var/www/MISP/app/tmp/error.log** for:
020-12-20 13:51:46 Error: [MethodNotAllowedException] **Invalid Sharing Group** or not authorised.
Request URL: /events
Stack Trace:

Again, thx a lot to @likescam for pointing me in the right direction.
