### ISSUE TITLE
OpenIOC report request

### ISSUE THREAD

**Issue by dewiestr** [cuckoosandbox/cuckoo#344]
I was wondering of an OpenIOC report was considered by anyone in the near future. My plan is to use it in this  project: https://github.com/MISP/MISP. A lot of organisations use both tools, so I think this would be a great feature.

**Comment by jbremer** [comment]
I'll get in touch with the guys behind MISP later. But yeah, this doesn't count as *in the near future* anymore o/
Still could be interesting, though. To be continued.

**Comment by jbremer** [comment]
Closing this issue as I haven't heard of anyone using OpenIOC in a while. In addition to that we now have rudimentary MISP support in Cuckoo.
