### ISSUE TITLE
process memory dump is not contiguous

### ISSUE THREAD

**Issue by freetink3r** [cuckoosandbox/cuckoo#372]
The process memory dump (generated by procmemdump=yes) does not indicate the starting base address of the dumped memory and the dumped memory is not necessarily a contiguous chunk.  I'm baffled as to how this memory dump would be useful to anyone, but it is possible I am misunderstanding the intentions of the feature.  I would expect the process memory dump file to at least include the starting address as well as a map of the address ranges included in the dump.  Without that, it's not possible to tell what you're analyzing.

**Comment by hahadaxia** [comment]
freetink3r ,I meet the same question.can you tell me your suggestion?
i want to get the memdump from cuckoo.and try to auto analysis the malware code with my python script.
