### ISSUE TITLE
'nogui' mode for workstation 11 not working properly

### ISSUE THREAD

**Issue by jcannell** [cuckoosandbox/cuckoo#469]
Hello,

I've used vmware WS as my machine manager for awhile with cuckoo. I upgraded to vmware WS11, but I noticed that there is an issue with running cuckoo VMs in the 'nogui' mode.

Here is what I've observed:
1. If I have at least one vmware window open, a new window is created for each new new analysis task submitted to cuckoo. This obviously creates a ridiculous amount of windows if you're processing large volumes.
1. If I don't have any vmware windows open, no new windows are created for new cuckoo analysis tasks.

I've doubled checked to make sure that 'nogui' mode is enabled in vmware.conf.

I know WS11 is a fairly new product, so it could be a bug on their end or perhaps there is an option I'm missing in WS11.

I will post updates here if I figure something out.

**Comment by jekil** [comment]
Thanks for reporting it. If you are able to investigate this will help a lot.

**Comment by jbremer** [comment]
Any update on this issue?

**Comment by jbremer** [comment]
Closing this issue as it has been abandoned and no other users have reported similar issues.
