### ISSUE TITLE
Add file path of dropped files

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#493]
In the HTML report when a file is dropped we currently only have the file name, the size, various hashes and VT link. 

Could be very valuable to also have the file path.

**Comment by jekil** [comment]
Thanks for this feature request, we will take care of it.

**Comment by jbremer** [comment]
This feature has finally been implemented. Although the information is currently not available in the HTML report, you should be able to obtain it in the Django Web Interface. Closing this issue as resolved for now.

**Comment by Tigzy** [comment]
Great! Thanks.
