### ISSUE TITLE
Sandbox is evaded by On Close macros 

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#509]
As documented here:
https://www.proofpoint.com/us/threat-insight/post/Run-on-Close-Macros-Try-to-Shut-the-Door-on-Sandboxes
A number of malware deployed through Macros are making use of the On Close event to execute only when the application is closed. This is done to evade sandboxes, and it does in fact evade ours.

**Comment by midnightcoder13** [comment]
So, is this issue solved by just closing all running processes in Package.finish() in cuckoo/analyzer/windows/lib/common/abstracts.py, or am I just way too new at this and missing something obvious?

**Comment by jhg** [comment]
Is possible that before of shutdown machine Cuckoo close document and wait a little more time? It maybe mitigate this problem

**Comment by jbremer** [comment]
This has been included in our `2.0.4a3` release, closing issue.
