### ISSUE TITLE
Deprecation of web.py and/or HTML reports

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#511]
Let's discuss here what is to do with HTML reports and the `web.py` utility.
As we currently stand, both of them are largely abandoned as all the development is being done on the Django web interface.

The Django web interface provides a much better view of the single reports as well as extended search and comparison capabilities. From our point of view, it is definitely the preferred choice.

Before taking any decision, we should get some feedback from our users on what is the best course of action. HTML reports in particular might still have a significant value, and we maybe we should revive them instead of abandoning them.

**Comment by jbremer** [comment]
Generally I think people would rather see a PDF report than a HTML report. So maybe start deprecating HTML reports and create a PDF reporting module which people can use as replacement. Of course this means actually making a PDF which is kind of a pain (i.e., either use some unknown library or use something bloated like LaTeX).

Maybe an idea to ask people on the mailing list about this issue, @botherder?

**Comment by gtback** [comment]
It might be possible to use something like [`weasyprint`](http://weasyprint.org/docs/), keeping the HTML report and supporting conversion to PDF. I've never used it personally, though.

**Comment by g-clef** [comment]
Right now I'm using both the html and json reports. I have a custom front-end that submits files to both Cuckoo and another malware tester simultaneously & collects the results from both. The Cuckoo json results go to ElasticSearch, and the html results are shown to the user. I could deal with deprecating the html report, since I can always scrape the django front-end if I have to.

One side-note: I pretty strongly disagree with the idea that people would prefer PDFs. I hate them because getting data out of a PDF to present to the user is annoying & embedding a PDF to a user is a bit of a cop-out.

**Comment by jbremer** [comment]
@g-clef You're not supposed to get data out of a PDF nor a HTML document, for that purpose there's the JSON report which contains all the information (if not more) that you can also find in the HTML (and possibly in the future PDF) report.

**Comment by g-clef** [comment]
@jbremer for my purpose, embedding a PDF is a very bad user-interface option. Embedding HTML is fine even if I only rip part of the HTML out & display it to the user. But I at least have that option with HTML, and can preserve some of  the original layout & appearance with HTML. With PDF, I have no choice but to present the user with a foreign thing, breaking the user's interaction with my site (can't preserve visual appearance, can't ensure links back to my system, etc).

(But this is a derail of the original conversation. I'll stop here, and just register my vote that I do use the HTML web.py interface.)

**Comment by botherder** [comment]
@g-clef That is useful conversation, don't stop.

I agree that PDF might be useful for easier distribution, although I agree there is a value in HTML. The problem really is that we're failing at maintaining both the web interface and the HTML report at the same time, since most of the code should duplicate while it doesn't now.

Also keep in mind that most modern browsers can easily take an HTML page and convert it to PDF.

**Comment by gaelmuller** [comment]
I think that it would be good to keep the HTML report. However, this is too difficult to maintain both the HTML report and the django interface. Maybe we should find a way to build one from the other.

**Comment by g-clef** [comment]
@botherder 'k. 

I guess my use-case boils down to "Do you have a preference for how people embed Cuckoo results in other apps?"

I'd assumed that the HTML reports were offered as a way to display those results to users (even embedded in other things), and the JSON results were offered for more backend things like ElasticSearch (or for sites that want to put their own styling on the results). That is an assumption on my part, though, so I might have read that wrong. If that's not the case, and you all would prefer we use the JSON results with our own styling, I'll adapt.

**Comment by gtback** [comment]
Would be be possible/easy to reuse the current Django templates and create a "single page HTML report" with all the data concatenated together?

**Comment by botherder** [comment]
Potentially it could be possible, but it might require some restructuring to do.
It's certainly something that would help keeping the HTML report alive.

**Comment by KillerInstinct** [comment]
Instead of deprecating a reporting module, I'd suggest migrating it to community. The directory structure supports this already and it allows for the user to still be able to download it, while not requiring further 'development support'. (Just my 2cents re: html report)

**Comment by jhg** [comment]
https://github.com/cuckoobox/cuckoo/pull/566 remove HTML reports and change web.py to a shortcut of manage.py runserver for run Django web

**Comment by jbremer** [comment]
Closing issue as resolved - it's still WIP, but we have standalone HTML & PDF reports yet again.
