### ISSUE TITLE
2 feature requests. Install script to make config easier :)

### ISSUE THREAD

**Issue by tysonmax20042003** [cuckoosandbox/cuckoo#538]
Since Cuckoo has a lot of configs that need to be changed for the correct response from cuckoo. Could your team or the community create an install script to enable all required changes depending on the setup for Cuckoo. 

This could be a menu based bash script that just askes a few questions, IE: Will you be using VirtualBox? What Interface do you need to be monitored by TCPDUMP? How Many VM's are you using, etc........ and the conf's that will be changed will be IE Virtualbox, Physical, reporting, etc...? Also add the correct IPTABLES rules, etc...Just a thought ;) 

Also could the Cuckoo.py call the basic and or the Django interface so only one command is required to simplify the process?

Thanks and keep up the great work!!!!!!!!!!!

**Comment by jpsenior** [comment]
Tysonmax, it seems like you would be more interested in a prebuilt cuckoo virtual appliance for this sort of request?

**Comment by botherder** [comment]
The request makes sense. The configuration files are many and getting through all the options might be intricate. I'm not sure what is the best solution to this, but it needs to be addressed.

**Comment by jbremer** [comment]
We're continuously improving on this matter, so just wait and see and life will become much easier this year. Closing this issue as we're working on this, but the full request is kind of big, as in, months and months of work ;-)
