### ISSUE TITLE
Provide option to disable color output in CLI commands

### ISSUE THREAD

**Issue by dspruell** [cuckoosandbox/cuckoo#540]
Is it possible to add an option to cuckoo.py to disable output of the color sequences?

In some setups, such as when running the Cuckoo commands from Upstart jobs and redirecting stdout/stderr to a log using _console log_, command output is placed as is in a log file. Other process managers can behave this way as well.

Log files then look as follows:

```
 Cuckoo Sandbox ESC[33m1.2ESC[0m
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
ESC[32m Good! ESC[0mYou have the latest version available.

2015-05-08 01:27:00,803 [root] CRITICAL: ESC[31mCuckooCriticalError: Unable to bind ResultServer on 192.168.56.1:9000: [Errno 99] Cannot assign requested addressESC[0m
```

Disabling color in output could increase readability in these cases.

**Comment by jbremer** [comment]
Are you sure? I've been using Upstart scripts as well without issues. See also https://github.com/cuckoobox/cuckoo/blob/master/utils/service.sh
Then just read `/var/log/upstart/cuckoo.log`.

**Comment by dspruell** [comment]
Not totally sure. :) My log file snippet is the result of using `console log` in Upstart job configs, which causes the stderr/stdout from the job to be redirected to the log file. If the output contains control characters, those are entered into the log file. 

That said, I'm using a different Upstart setup than what `utils/service.sh` creates. What I'm seeing may be related to my setup. If there's no issue with the project's recommended setup, it's of course fine to close this issue accordingly.

**Comment by jbremer** [comment]
I'm definitely not saying that `utils/service.sh` represents Cuckoo's recommended setup, but it's what I have been using and it does the job for me. If you can share your Upstart scripts, perhaps there's something useful in there :)

**Comment by jbremer** [comment]
This should definitely be resolved now, closing issue.
