### ISSUE TITLE
Proposal: remove utils/web.py web and that it run Django web with development server

### ISSUE THREAD

**Issue by jhg** [cuckoosandbox/cuckoo#564]
That utils/web.py not run other web interface and that run Django development server, for only develop a web user interface. Merge two webs in one.

**Comment by jbremer** [comment]
Could do for the upcoming version.

**Comment by jhg** [comment]
If all right, I can help with this and merge webs in only Django web and utils/web.py run development server and do pull request.

**Comment by jhg** [comment]
Pull request 566 do this @jbremer

**Comment by botherder** [comment]
This isn't an immediate thing to do and it will need some discussion.

**Comment by jhg** [comment]
Yes, I know it @botherder only do this for keep this until finish discussion. After, this can be pull or reject. And I can change https://github.com/cuckoobox/cuckoo/pull/542 from HTML report to Django report, I only need https://github.com/cuckoobox/cuckoo/issues/524 fixed for I can do a human check of the report before of push it, I want remain https://github.com/cuckoobox/cuckoo/pull/542 of course.

**Comment by jbremer** [comment]
Closing issue as it is irrelevant now.
