### ISSUE TITLE
Migrate HTML report to use Django template

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#578]
We don't want to maintain the HTML report as it is. It is out of date. We want to use Django's HTML report.

**Comment by jhg** [comment]
When this will be done I will merge with my `master` branch and push to https://github.com/cuckoobox/cuckoo/pull/566 with any conflict solved.

**Comment by jbremer** [comment]
Using the Django templates for creating a single-page HTML file is pretty much impossible if you ask me. We should probably reconsider this issue or simply close it :-)

**Comment by jhg** [comment]
Django can create a single-page HTML but is more usefull has a PDF if don't want use web, if use a HTML then I can enter to web interface.

**Comment by jbremer** [comment]
A newly designed & simplified standalone HTML report is featured in the 2.0.0 release, closing this issue as resolved.
