### ISSUE TITLE
Need to initialize network with VirtualBox Machinery module 

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#579]
When starting Cuckoo, if VirtualBox network isn't active already, we get that error with the resultserver not binding. It is quite annoying, so let's try to either initialize the network or start and stop a VM to make VirtualBox do it for us.

**Comment by jbremer** [comment]
If you have `vmcloak` installed you can just run `vmcloak-vboxnet0`: https://github.com/jbremer/vmcloak/blob/master/bin/vmcloak-vboxnet0

**Comment by jhg** [comment]
I like this, is a common problem. I think is good the `vmcloak` vboxnet code use in `cuckoo` or integrate `vmcloak` in `cuckoo` by default.

**Comment by jbremer** [comment]
I think it would make sense to catch the exception and to present the user with a proper error - one that informs exactly what it is about, perhaps with a URL to the documentation around it.
After all, you can't really create vboxnet0 for the user - what if they want to use a custom IP range?

**Comment by jhg** [comment]
And, also, in /utils a script like as https://github.com/jbremer/vmcloak/blob/master/bin/vmcloak-vboxnet0 for easy configuration of vboxnet and in deploy easy of call before of run cuckoo.

**Comment by jbremer** [comment]
Closing this as about-to-be-resolved through #683.
