### ISSUE TITLE
[Proposal] Legacy DB for use Cuckoo DB from Django

### ISSUE THREAD

**Issue by jhg** [cuckoosandbox/cuckoo#605]
With Legacy DB is possible that Django make models for tables in Cuckoo DB without manager (not create, drop, migrate table; only access to data) and this allow that other Django apps can do relationship with  Cuckoo tasks, etc. Also allow use Django ORM for query tasks, search tasks from other models with relationship, extend Django of Cuckoo with other Django Apps, etc. This is easy, only is a Django managemen command and commit models that it generate, and with migrations in Cuckoo DB re-generate this models with the same Django manager command. Also with legacy DB Django not depend of internal cuckoo modules and not need add path of cuckoo to sys path from Python scritps.

If this like, I think a good place for this is in a module "cuckoo" in web folder, as a cuckoo Django app, and merge in this module the main of integration of cuckoo and Django. With this, will be easy integrate Cuckoo with others web in Django and others Django projects; also make easy build a Cuckoo web interface easy of custimize with only edit local settings and can use mongodb for get report or other report type.

**Comment by jbremer** [comment]
I'm not completely sure what your goal is, but it sounds like it'll involve a great deal of moving around code with the possibility of introducing many new bugs whereas the current approach is still working quite fine.
What is the goal of this proposal?

**Comment by KillerInstinct** [comment]
The goal is to allow for the conversion of the main Cuckoo DB (non mongo) into something that Django can use so that proper models can be created and used. EG for class based views, we could simply make calls around the model instead of involving direct calls to sqlalchemy. Django would manage the database connection as specified in settings.py (typically)

**Comment by jbremer** [comment]
Although an interesting goal, I don't think this is going to happen anytime soon, so I'm going to close this issue - thanks.
