### ISSUE TITLE
Add pagination to analysis list in Django UI

### ISSUE THREAD

**Issue by ghost** [cuckoosandbox/cuckoo#631]
Using manage.py, Cuckoo doesn't show all the analysis tasks. Only the recent 50. How can I see all of them like the web interface in utils?

**Comment by KillerInstinct** [comment]
At the current moment, it can't with exception to using the search. This may be a good time to add/feature request pagination.

For a cheap solution, modify the following lines to fit what you want, keep in mind though the larger the number the more performance will decrease loading the page.

https://github.com/cuckoobox/cuckoo/blob/master/web/analysis/views.py#L34

**Comment by mweeek** [comment]
Thank you. How do I make this a feature request?

**Comment by jbremer** [comment]
This has been implemented as part of our upcoming Web Interface. Closing as resolved.
