### ISSUE TITLE
errors generated by agent

### ISSUE THREAD

**Issue by pch3** [cuckoosandbox/cuckoo#637]
fresh cuckoo cloned today. Agent running on windows 7 64 bit, python 2.7 64 bit binaries.

Error resolving function ncrypt!Ssl3GenerateKeyMaterial
![0af08c86594ce20574717c249f9fbce9b37da81751d8dacb51174211dd60b9ff_0001](https://cloud.githubusercontent.com/assets/13233057/9553512/d9b41086-4dbf-11e5-81c6-3f8b94fee10c.jpg)

Unicode to ascii translation:
![b21e14b19d3bc856e290922bbb102d4fde5115f92b8fe453f8254dced7abeaa9_0008](https://cloud.githubusercontent.com/assets/13233057/9553529/e7b4b3ca-4dbf-11e5-9a74-d2330fdebc34.jpg)

**Comment by jbremer** [comment]
The first one is not critical (as its functionality doesn't work on Windows XP anyway), but I'll prune the message.
The second error is a genuine error, though. Could you perhaps share the sample you're analyzing? I have a good idea how to fix this error (it's one of those unicode errors obviously), but being able to test it properly usually helps.

**Comment by pch3** [comment]
Sure, I got it from malwr:
https://malwr.com/analysis/MmYzOWMxZmVhMWQyNGJiOGFiNTRkNzFkMWRlNjBmNWU/ but
I can send it to you as well.
Basicaly what I am trying to achive is to have the same (or similar) result
on my cuckoo instance like the one on malwr.
So far it is far from being even similar :(

2015-08-28 20:32 GMT+02:00 Jurriaan Bremer <notifications@github.com>:

**Comment by botherder** [comment]
@jbremer updates on this?

**Comment by jbremer** [comment]
I believe both of these issues were resolved, so closing this issue.
