### ISSUE TITLE
Memory dump only readable by root

### ISSUE THREAD

**Issue by kjakan** [cuckoosandbox/cuckoo#643]
We are running cuckoo from git on ubuntu 14.04, and when a memory dump is taken by libvirt the file is only readable by root, which causes problems for volatility.

Just creating the file before calling libvirt seems to solve the problem. 

My ugly hack in cuckoo/lib/common/abstracts.py from line 422:

    def dump_memory(self, label, path):
        """Takes a memory dump.
        @param path: path to where to store the memory dump.
        """
        log.debug("Dumping memory for machine %s", label)

        #Creating file before call to libvirt to get read permissions for user after dump
        open(path,'w').write('')

        conn = self._connect()
        try:
            self.vms[label].coreDump(path, flags=libvirt.VIR_DUMP_MEMORY_ONLY)
        except libvirt.libvirtError as e:
            raise CuckooMachineError("Error dumping memory virtual machine "
                                     "{0}: {1}".format(label, e))
        finally:
            self._disconnect(conn)

**Comment by brad-accuvant** [comment]
Can confirm this works, I made the same change last year: https://github.com/brad-accuvant/cuckoo-modified/commit/eb3058de8de3b9310b8c3c4a8e25a8bf19847b09

**Comment by jbremer** [comment]
Thanks for reporting @kjakan and the bugfix @brad-accuvant.
