### ISSUE TITLE
Django issue

### ISSUE THREAD

**Issue by jbremer** [cuckoosandbox/cuckoo#647]
As reported by BigBobbyTable on irc there is an issue in the following configuration:
- MySQL as backend
- New database
- Submitted a file to _all_ machines

Under these conditions Django would throw the following issue:

```
NoReverseMatch: reverse for 'analysis.views.file' with arguments  ('sample', '') and key arguments '{}' not found. 1 pattern tried, file/(?P<category>\\w+).
```

**Comment by jhg** [comment]
It's possible will be like https://github.com/cuckoobox/cuckoo/issues/524

**Comment by botherder** [comment]
Updates?

**Comment by jbremer** [comment]
Probably resolved or unrelated now. Closing the issue.
