### ISSUE TITLE
Adoption of django logging handlers for analysis output (e.g. syslog)

### ISSUE THREAD

**Issue by jpsenior** [cuckoosandbox/cuckoo#658]
Adoption of django logging handlers for analysis output (e.g. syslog)

Integration of analysis-related information (Eg. analysis.log, cuckoo.log) in the django/python handlers module will permit output to flatfile text/syslog/etc.

**Comment by jekil** [comment]
Django supports different logging handlers, users should just configure logging section in settings.py according to their needs.

**Comment by KillerInstinct** [comment]
Any documentation to this?

**Comment by jekil** [comment]
Django logging is very flexible https://docs.djangoproject.com/en/1.9/topics/logging/
We coulf provide a commented template in settings.py in the future.

**Comment by jekil** [comment]
Added an example of logging to file; in my opinion it is enough for the scope of our web settings, I leave to django documentation for more complex setups.

**Comment by botherder** [comment]
Is this to be considered resolved?

**Comment by KillerInstinct** [comment]
I am happy with it, but I'm not the OP. :)

**Comment by jekil** [comment]
We got no feedback on the proposed solution, so I am closing this issue.
@jpsenior feel free to re-open this issue or to further comment on.
Thanks so much for the feedback to all.
