### ISSUE TITLE
Web-based Zip file exporting with options

### ISSUE THREAD

**Issue by jpsenior** [cuckoosandbox/cuckoo#660]
On the admin page, add an 'export' functionality that can select various parts of an analysis: Log file, screenshots, memory, payload sample, dropped files, analysis json exports.  Add optional password fields to evade antiviruses.

**Comment by jbremer** [comment]
That was also on the todo list :p thanks for the suggestion though.

**Comment by jbremer** [comment]
The export/import functionality has been implemented already a while ago. I'll leave this issue open for adding the password protection though, that's a good suggestion.

**Comment by jbremer** [comment]
I did actually implement something that resembles password protection, but it was extremely slow (which is not so weird provided that it was implemented in Python). One day, once https://github.com/jbremer/sflock/issues/5 is implemented, we'll be able to continue on the password feature.

**Comment by jbremer** [comment]
Closing issue as resolved. Password encryption may be done at a later stage.
