### ISSUE TITLE
comparing two analysis produce the following error in django:

### ISSUE THREAD

**Issue by GelosSnake** [cuckoosandbox/cuckoo#671]
Environment:
Request Method: GET
Request URL: http://127.0.0.1:8000/compare/2/1/
 
Django Version: 1.8.4
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'analysis',
 'compare')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'web.headers.CuckooHeaders')
 
 
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py" in inner
  45.             return func(request, *args, **kwargs)
File "/cuckoo/web/compare/views.py" in both
  96.     counts = compare.helper_percentages_mongo(results_db, left_id, right_id)
File "/cuckoo/web/../lib/cuckoo/common/compare.py" in helper_percentages_mongo
  85.         for pdoc in pids_calls["behavior"]["processes"]:
 
Exception Type: KeyError at /compare/2/1/
Exception Value: 'behavior'\

using cuckoo commit: 7fac495ca8f9ce37c7194d1d923eb741ed440378"

**Comment by botherder** [comment]
That's right. The interface hasn't been yet updated with latest report structure changes.

**Comment by botherder** [comment]
This seems to have been resolved.
