### ISSUE TITLE
Zip Bomb Detection

### ISSUE THREAD

**Issue by haydenk** [cuckoosandbox/cuckoo#676]
Maybe this is handled already but I am not certain.

In the [agent.py](/cuckoobox/cuckoo/blob/master/agent/agent.py#L150), I see it is wrapped in a try...catch but how it would handle if a Zip Bomb were uploaded to the server and it attempted to unzip it?

**Comment by jbremer** [comment]
Well, it's not really handled, but it will result in the guest VM to you know, unpack the file until it runs out of resources. So basically it will fail to analyze properly and then after one or two minutes it will simply quit and Cuckoo will have a happy life afterwards.
Not sure if Cuckoo is supposed to handle it any better? :-)

**Comment by jbremer** [comment]
Going to close this issue as irrelevant for now. In the future when we have Host-side pre-analysis of submitted files this might be a small issue todo item, but other than that it's nothing too special.
