### ISSUE TITLE
Cuckoo API returns Error 500

### ISSUE THREAD

**Issue by alxhrck** [cuckoosandbox/cuckoo#679]
The API resource /tasks/lists returns error 500 when there is more than 290 tasks in Cuckoo, or when more than 290 tasks are being requested.

**Comment by jbremer** [comment]
That sounds very likely. Can you please share the error that you get when running `api.py` in debug mode? For this you'll have to change the last line into the following: `app.run(host=args.host, port=int(args.port), debug=True)`

**Comment by alxhrck** [comment]
Error message from api.py is attached.
[error.txt](https://github.com/cuckoobox/cuckoo/files/32259/error.txt)

**Comment by jbremer** [comment]
Interestingly enough you have some string in your analysis that sets off the JSON encoding. Could you please elaborate on whether there's any unicode filenames going on here or something?

**Comment by jbremer** [comment]
@alxhrck Any update from your side regarding my question? :)

**Comment by alxhrck** [comment]
Sorry for the delay. It does appear I have an analysis with a URL containing hex ascii characters. I use a tool that adds non-printable characters to suspicious URLs as a way to 'handle them safely'. This task was entered before stripping out those characters. 

Attached is the task that is causing return jsonify(response) to throw and exception.

[error_task.txt](https://github.com/cuckoosandbox/cuckoo/files/73433/error_task.txt)

**Comment by jbremer** [comment]
Yeah, that makes sense :-) Please verify that the commit above fixes the issue and feel free to close the issue afterwards.
Thanks again!

**Comment by alxhrck** [comment]
The commit seems to have taken care of the issue. Thanks for the fix!
