### ISSUE TITLE
API not honoring unique submission

### ISSUE THREAD

**Issue by housemusic42** [cuckoosandbox/cuckoo#690]
I'm wondering if this is intended behavior or if I'm might be missing something.

I'm attempting to make sure submissions through the API are unique and while other parameters are being honored, I have not found a way to have --unique verify the sample is indeed unique. Thanks for any light you can shed on the issue!

``` python
import requests
import json

REST_URL = "http://192.168.1.10/api/tasks/create/file/"
SAMPLE_FILE = "test.txt"

with open(SAMPLE_FILE, "rb") as sample:
    params = {'machine': 'cuckoo1', 'options': 'unique'}
    multipart_file = {"file": ("test.txt", sample)}
    request = requests.post(REST_URL, files=multipart_file, data=params)
```

**Comment by jbremer** [comment]
`--unique` is a feature that was implemented in `utils/process.py` a few years ago - this feature is not implemented elsewhere, at the moment. Personally I'm not sure if it should anyway, one could also take care of that functionality on the outside of Cuckoo of course :-)

**Comment by housemusic42** [comment]
i found it in the ```utils/submit.py``` but i see what you're saying. 

i think this may be a similar request though to #483

**Comment by jbremer** [comment]
This has been implemented in the Cuckoo API now, not yet in the Cuckoo Web Interface, though.
