### ISSUE TITLE
setup.sh script enforcing an outdated version of VirtualBox

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#713]
We should enforce using VirtualBox 5.0 since it is now out.
https://github.com/cuckoobox/cuckoo/blob/8b5aad90b9e8aff1f645528ebde3e2fd7e1e1538/utils/setup.sh#L245-L248

Part of #712.

**Comment by jbremer** [comment]
The `setup.sh` script has since been deprecated and removed in #863. There's now `SaltStack`-based deployment available which works just fine. See also https://github.com/jbremer/cuckoo-salt. Closing as resolved.
