### ISSUE TITLE
UnicodeWarning in abstract.py pattern comparison

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#714]
```/cuckoo/lib/cuckoo/common/abstracts.py:721: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if item.lower() == pattern.lower():```

**Comment by pashashocky** [comment]
Confirmed. This bug also crashes the web interface with 2.0-dev and rc1 when running with WinXP. Doesnt crash with Windows 7. I was running a doc sample.

**Comment by Titotix** [comment]
This warning comes from the signature ddos_darkdos_mutex.py.
This patch fix it, but I am not sure if it is a clean one : 

```
--- a/modules/signatures/windows/ddos_darkddos_mutex.py
+++ b/modules/signatures/windows/ddos_darkddos_mutex.py
@@ -16,7 +16,7 @@ class DarkddosMutexes(Signature): 
     mutexes_re = [
         "DARKDDOSER",
-        "\xc3\x81G\xc3\x9bP\xc3\xb2y\xc3\xbdF\xc3\x80N\xc3\x96S",
+        u"\xc3\x81G\xc3\x9bP\xc3\xb2y\xc3\xbdF\xc3\x80N\xc3\x96S",
     ]
 
     def on_complete(self):
```

**Comment by jbremer** [comment]
Nice catch, @Titotix! Will check it out.

**Comment by pashashocky** [comment]
Thank you Titotix, but that doesnt remove the web crash

**Comment by jbremer** [comment]
I'm pretty sure that's a different bug, @pashashocky.

**Comment by jbremer** [comment]
The issue is an incorrect reference, should've pointed it to the `cuckoo` repository.
Anyway, thanks @Titotix! See also https://github.com/cuckoosandbox/community/commit/b172d6ca08bd427dfba340f649f5d6e31286ee02
