### ISSUE TITLE
Is libssl-dev a dependency of Cuckoo or mitmproxy?

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#715]
From other tickets, users pointed out the dependency of libssl-dev and libffi-dev. Can anyone pinpoint exactly what is requiring such dependencies?
We should review all the dependencies, their documentation in the guide, and if they are correctly reflected in the setup scripts and travis-ci configuration.

**Comment by jbremer** [comment]
I imagine that it could also be a dependency of `M2Crypto` which we're currently still using.

**Comment by KillerInstinct** [comment]
@jbremer in my experience, M2Crypto only needs swig and libssl-dev. libffi-dev is not in my install notes -- but that was a while back.

**Comment by jbremer** [comment]
The documentation has been updated to reflect these packages a while ago. Closing as resolved.
