### ISSUE TITLE
False positive "Found URLs (potentially malicious URLs)"

### ISSUE THREAD

**Issue by stiandre** [cuckoosandbox/cuckoo#717]
This URL was found to be potentially malicious: http://www.w3.org/2001/XMLSchema-instance

**Comment by botherder** [comment]
Was found potentially malicious by what exactly?

**Comment by stiandre** [comment]
It was found during analysis of process dumps for a malicious executable.
The process with pid = 452 was not listed in the "Behaviour Analysis" ->
"Process Tree", so unfortunately I do not have any context info
for the process dump containing the URL. Please tell me if you need / know
how to get more context info.

[image: Innebygd bilde 1]


2015-12-29 15:34 GMT+01:00 Nex <notifications@github.com>:

**Comment by jbremer** [comment]
Thanks @stiandre, will add it to the whitelist later.

**Comment by stiandre** [comment]
It's a pleasure!

2015-12-29 22:06 GMT+01:00 Jurriaan Bremer <notifications@github.com>:

**Comment by jbremer** [comment]
Thanks again!
