### ISSUE TITLE
Signatures don't appear to be working

### ISSUE THREAD

**Issue by CSIRTUK** [cuckoosandbox/cuckoo#728]
I'm not seeing any firings against the commnunity signatures, even simple ones such as one or more hits on VirusTotal.  The VirusTotal results are populated as I would expect.

Regards
Andy D

**Comment by jbremer** [comment]
When you start `./cuckoo.py -d`, do you see the signatures being loaded? Which version of Cuckoo are you using?

**Comment by CSIRTUK** [comment]
It's the new 2.0-dev version.  I was having a look to see how it was shaping up.  Looks fantastic on the whole.  Great work!

**Comment by jbremer** [comment]
Did you get the appropriate signatures? That is, by running `./utils/community.py -wafb 2.0`? :-)

**Comment by CSIRTUK** [comment]
Ah OK.  I didn't realise you could specify the version like that.  Please close.  Sorry for being an idiot ;)

**Comment by jbremer** [comment]
No worries. If you have any other questions let us know.
