### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by patilswapnilb** [cuckoosandbox/cuckoo#729]
i am trying to run cuckoo but it's showing this error-
Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
Segmentation fault (core dumped)

**Comment by jbremer** [comment]
Wow, that's quite the edge case that you've found. Could you share a full log of running `./cuckoo.py -d`?

**Comment by patilswapnilb** [comment]
how to get logs of cuckoo.

**Comment by PatriciaInfante** [comment]
Run ./cuckoo.py -d then get the log from the log folder.

**Comment by botherder** [comment]
Updates @patilswapnilb ?

**Comment by patilswapnilb** [comment]
@botherder i have tried installation in ESX environment that time i faced this error.
now i reinstall everything in normal environment as per cuckoo docs . and it's working fine except some error in analysis.

**Comment by botherder** [comment]
I'll close this ticket then, if it reoccurs make sure to have logs and coredump.
