### ISSUE TITLE
Magic numbers in signatures score 

### ISSUE THREAD

**Issue by m-messiah** [cuckoosandbox/cuckoo#732]
When Cuckoo plugin calculates score for report, it sums all matched severities and divide them by 5.
This is the first magic number here. Why is it 5? What does it mean?

in lib/cuckoo/core/plugins.py:

``` python
score = 0
for signature in self.signatures:
    if signature.matched:
        self.matched.append(signature.results())
        score += signature.severity
self.results["info"]["score"] = score / 5.0
```

And the second magic number appears in web/templates/analysis/overview/index.html:

``` html
<strong>{{ analysis.info.score }} out of 10.</strong>
```

So, while amount of signatures is variable and new signatures can be easily added to instance - these magic numbers can broke all your logic and write something like:

> This file is definitely malicious with a score of 13.8 out of 10! You should NOT open this file on a production system. 

So, can you easily normalize score or define rules between score and severity?

**Comment by jbremer** [comment]
I'd give our current rating system a 5/7. No really, it's just a first start on the topic. If you'd like to improve it - be my guest ;-) It's not perfect but it will remain fairly arbitrary anyway.

https://twitter.com/cuckoosandbox/status/690197805751746560

**Comment by jbremer** [comment]
Closing this issue as not much has been suggested in the meanwhile :-) It's still on our todo list, though ;-)
