### ISSUE TITLE
request: use of newer windows VMs

### ISSUE THREAD

**Issue by LogoiLab** [cuckoosandbox/cuckoo#733]
A lot of malware now a days is leveraging powershell...which XP doesn't support. Even thought XP is just recommended it seems to be the only distro that works well with cuckoo.

**Comment by jcannell** [comment]
I use Windows 7 with Cuckoo and it works fine.

**Comment by jbremer** [comment]
I was just going to post the same. If you have any issues, please upgrade ;-)
https://cuckoosandbox.org/2016-01-21-cuckoo-sandbox-20-rc1.html
