### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by danielgindi** [cuckoosandbox/cuckoo#735]
Hi!

I haven't found any statement regarding the license terms and usage for commercial applications.

Can anyone please clarify?

Thanks!

**Comment by jbremer** [comment]
Depending on your application and requirements we offer various tailor-made options.
Please refer to the following blogpost - you can also find our email address for such services etc there.

https://cuckoosandbox.org/2015-05-15-consultancy-services.html

**Comment by danielgindi** [comment]
Well it still does not clarify anything about licensing terms...
This project is stated as "open source", which is amazing!
But we need to know what are the license terms. Whether it's free for all, pay X $ and get Y licenses...

The blog post you are referring to is just vaguely stating that there were some consultancy jobs in the past which helped fund. It's not even easy to understand if it implies that we must pay for such work in order to receive some kind (what kind?) of license.

Excuse me if I'm taking too much of your time but I'm involved in a project with a need for such a platform, and considering our options. Being a very active open-source community member, it's important to me to not violate open-source licenses, and to contribute to the community effort as much as possible (not always being an option depending on the organization you are working for, the budgets etc.).

**Comment by jbremer** [comment]
Sorry, you're correct, the blogpost doesn't really focus on commercial licenses.
The license requirements (and options) are related to the way you'd like to leverage Cuckoo in your company.
I think it'd be easiest if you could reach out to us in private, at `cuckoo@cuckoofoundation.org`, to describe your situation and goals etc.
Is that oke for you? :-)

**Comment by danielgindi** [comment]
Yes of course :-)

I'll do so soon after we review all our options for the project. Thank you!

**Comment by jbremer** [comment]
Ok. I'll close this issue then - looking forward to your email.
