### ISSUE TITLE
mDNS breaks cuckoo Analysis

### ISSUE THREAD

**Issue by jmdevince** [cuckoosandbox/cuckoo#736]
Capturing mDNS (Bonjour Service) packets from analysis break cuckoo. This was done on 2.0-RC1.

```
2016-01-24 20:29:06,980 [modules.processing.network] ERROR: Failed to process packet: 'type'
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 621, in run
    self._udp_dissect(connection, udp.data)
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 212, in _udp_dissect
    self._add_dns(data)
  File "/home/cuckoo/cuckoo/modules/processing/network.py", line 351, in _add_dns
    reqtuple = query["type"], query["request"]
KeyError: 'type'
```

Also breaks webUI:
```
Error during template rendering

In template /home/cuckoo/cuckoo/web/templates/analysis/network/_dns.html, error at line 14
Reverse for 'analysis.views.moloch' with arguments '()' and keyword arguments '{u'host': u'_sleep-proxy._udp.local'}' not found. 1 pattern(s) tried: ['analysis/moloch/(?P<ip>[\\d\\.]+)?/(?P<host>[a-zA-Z0-9-\\.]+)?/(?P<src_ip>[a-zA-Z0-9\\.]+)?/(?P<src_port>\\d+|None)?/(?P<dst_ip>[a-zA-Z0-9\\.]+)?/(?P<dst_port>\\d+|None)?/(?P<sid>\\d+)?']
```

**Comment by jbremer** [comment]
Thanks for reporting :-) The error is pretty self-explanatory, however, in order to properly fix it - could you please share the `dump.pcap` file?

**Comment by jmdevince** [comment]
Here's a link to the dump.pcap file. 

https://owncloud.hexhost.net/index.php/s/akXp5WYwXfzBkvV

**Comment by jekil** [comment]
It seems an error related to how dpkt parse the packet. In case of MDNS packet the resource record for the request is not set.

**Comment by jbremer** [comment]
I've tested @jekil's fix as working, thanks! Thanks for reporting @jmdevince.
Please let us know if you run into any other issues etc.

**Comment by jmdevince** [comment]
I think this should be re-opened and the 255 value should be addressed for what it is, a request type of 'All Records'. Then all others should be 'Unknown'.

Thanks!

**Comment by jekil** [comment]
It makes sense, thanks.
