### ISSUE TITLE
Connectivity Issue between Cuckoo 2.0RC1 and Agent.py?

### ISSUE THREAD

**Issue by L4mbo** [cuckoosandbox/cuckoo#739]
Hey there,

I was very happy to see Cuckoo 2.0 released recently and tried to upgrade to the newest version right away. So far everything runs fine (Analysis VM gets recognized, started, webinterface works etc.) but I can't get an analysis to finish. About 10 to 20 seconds after starting the analysis VM cuckoo shuts it down again without any results. The analysis is then marked as failed.

I am able to ping from the Analysis machine to the host and from the host to the analysis machine without any problem. I can also write content to the agent.py by using telnet successfully. The same network setup also worked fine with my previous cuckoo 1.2 installation.

The attached file contains the output of a cuckoo -d run, "ConnectionError: ('Connection aborted.', BadStatusLine("''",))" beeing the final error line.

I hope you can help me fix this. :)
Regards.

[Cuckoo2.0_Error.txt](https://github.com/cuckoosandbox/cuckoo/files/104952/Cuckoo2.0_Error.txt)

**Comment by jbremer** [comment]
Do you have any firewalls that might act up in place? Could you share the `dump.pcap` file, that would greatly help? :-)

**Comment by L4mbo** [comment]
Hey,

sorry for the delay, unfortunately I couldn't access my laptop untill today. I attached the dump.pcap file below, thanks in advance. :)

[dump.zip](https://github.com/cuckoosandbox/cuckoo/files/112021/dump.zip)

**Comment by jbremer** [comment]
This is an empty pcap file, chances are high you have filled out incorrect IP addresses in the configuration or so. Closing this issue as out of scope for us ;-) Please refer to our documentation as well while configuring Cuckoo.
