### ISSUE TITLE
Office XP is not recognized

### ISSUE THREAD

**Issue by gitevo** [cuckoosandbox/cuckoo#743]
This old Office Version is not recognized. 

In the files:
cuckoo/analyzer/windows/modules/packages/doc.py
cuckoo/analyzer/windows/modules/packages/ppt.py
cuckoo/analyzer/windows/modules/packages/xls.py

the path to 
("ProgramFiles", "Microsoft Office", "Office11",  XXX ...

Needs to be added.

Thanks in advance

**Comment by botherder** [comment]
I  don't understand what you mean. Office11 does exist in those files.

**Comment by gitevo** [comment]
Hi,

too much copy & paste :-(

I mean "office10" 


Please also check the Evonik CERT Intranet for latest IT security 
Information http://cert.intranet.evonik.com

Mit freundlichen Grüßen - Yours sincerely 
Christian Janßen
Global IT & Processes 
IT Service Management
Risk & Quality 
Telefon +49 201 173-1357
Mobil +49 172 2694865
christian.janssen@evonik.com
Evonik Industries AG
Goldschmidtstraße 100
45127 Essen
Germany
www.evonik.de

Aufsichtsrat
Dr. Werner Müller, Vorsitzender
Vorstand
Dr. Klaus Engel, Vorsitzender
Christian Kullmann, Thomas Wessel, Patrik Wohlhauser, Ute Wolf

Sitz der Gesellschaft ist Essen
Registergericht Amtsgericht Essen
Handelsregister B 19474




Von:    Nex <notifications@github.com>
An:     cuckoosandbox/cuckoo <cuckoo@noreply.github.com>, 
Kopie:  gitevo <christian.janssen@evonik.com>
Datum:  02.02.2016 16:06
Betreff:        Re: [cuckoo] Office XP is not recognized (#743)



I don't understand what you mean. Office11 does exist in those files.

**Comment by botherder** [comment]
Done, thank you.
