### ISSUE TITLE
Improved static analysis

### ISSUE THREAD

**Issue by jbremer** [cuckoosandbox/cuckoo#757]
(Although not necessary at all, #755 would be a nice improvement for this issue).

There's plenty of static analysis to be implemented:
- Extract PDF metadata and embedded Javascripts
- Extract Office document metadata and embedded macros
- Extract SWF/JAR metadata etc
- Probably some more formats..

For any embedded scripts - and standalone VBA/VBS scripts etc - some deobfuscation probably doesn't hurt either.

**Comment by Titotix** [comment]
I am in to implement the PDF extraction stuff.
To implement this, the best tool according to me is [peepdf](https://github.com/jesparza/peepdf). Thoughts and different point of view ?
As I have already read on some issues, you want a proper agreement from the author to integrate his tool ? (as the tool is not on pypi but only on github). It is licence under GNUv3 btw.

**Comment by jbremer** [comment]
Agreed at going for PeePDF. @botherder what are your thoughts on the licensing issues?

**Comment by Titotix** [comment]
Hi,
@jbremer Thanks for proviging feedback  for [peepdf PRf](https://github.com/jesparza/peepdf/pull/52) 
Btw I don't see any licensing issues ? It is the same than Cuckoo.
Anyway, I will invite @jesparza to give his thought to include peepdf to the project.

**Comment by jesparza** [comment]
Hi there!

No problems with that, I will try to check your PR this week, @Titotix, so it will be easier to import.

**Comment by jbremer** [comment]
@Titotix @jesparza Any status update on the `peepdf` Python package?

**Comment by jbremer** [comment]
Not fully implemented yet, but that will come at some point. Closing issue regardless - we have separate issues for the remaining things / they're common sense anyway.
