### ISSUE TITLE
Monitoring API calls

### ISSUE THREAD

**Issue by yoonack** [cuckoosandbox/cuckoo#760]
Hi, 

I saw there are many APICALLS in the report. Those APIs are mainly from Kernel32.dll. However, is there a way to monitor other dll APIs call such as VB? (DllfunctionCall that calls certain APIs)

**Comment by jbremer** [comment]
As-is we have not integrated such instrumentation, although I agree that would be useful. Two to three years ago I implemented exactly that, although as separate functionality.. perhaps if there's interest to merge it, we should go for it. https://github.com/jbremer/vb6tracer

**Comment by KillerInstinct** [comment]
In my analysis, with office 2010 we are always importing from vb7.dll. May have a few tweaks there.

**Comment by yoonack** [comment]
It would be nice that if we can merge the vb tracer. By the way, is that only for p-code tracing or it can trace the native code as well? Thanks a lot for the help

**Comment by yoonack** [comment]
hmm..I tried using that VBtracer according to the instruction. However, I can't see any output in the file directory. Is there anything wrong with the compatibility?

**Comment by jbremer** [comment]
Well, quite some work is required to properly integrate it with Cuckoo. The tracer is focused on P-Code, so as-is you won't get much from native analysis I believe.
Why it doesn't work as promoted I don't know at the moment, it's been a while I worked on/used it. Are you sure you tried all steps etc?
Did you also change the `pipe` thing as the documentation says (you can do this without modifying the code nowadays by providing `pipe=cuckoo` as option to the analysis).

**Comment by jbremer** [comment]
Closing as issue has expired. I've added p-code instrumentation to our internal todo list, but I wouldn't expect it anytime soon ;-)
