### ISSUE TITLE
Type exceptions Memory Error

### ISSUE THREAD

**Issue by shaahint** [cuckoosandbox/cuckoo#764]
Hi,
I'm using cuckoo sandbox version 2.0, it works well but when I want to analyze a large file (e.g 85 MB), an error occurs : unable to upload malware to analysis machine (type exceptions Memory Error)
Although I changed the upload-max-size and analysis-size-limit in the file cuckoo.conf, an error still occurs

Extra information:
Host: Ubuntu version 14.04 (run on ESX)
Python version 2.7
Guest: Windows7 32 bit
Using submit.py for uploading the file 

Any suggestion please?
Thanks,
Shaahin.

**Comment by jekil** [comment]
I confirm this issue, alhtough it is really weird to analyze samples so big.

```
2016-02-13 11:11:21,560 [lib.cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=cuckoo1, ip=192.168.56.101)
2016-02-13 11:13:10,199 [lib.cuckoo.core.scheduler] ERROR: cuckoo1: unable to upload malware to analysis machine: <Fault 1: "<type 'exceptions.MemoryError'>:">
2016-02-13 11:13:10,217 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
```

**Comment by bbailey1024** [comment]
+1 on this. I don't normally have a need to analyze large files like this, but something did come up today.

**Comment by jbremer** [comment]
Please test if this issue still persists when using the new Cuckoo Agent https://github.com/jbremer/agent (this is a drop-in replacement for Cuckoo `2.0-rc1` and later). Although I imagine situations where it will still not be able to handle larger files, I believe it is capable of handling ~100mb files.

**Comment by jbremer** [comment]
This will be resolved by our upcoming release where much bigger files have been tested as working. There will still be some performance limitations for certain types (e.g., files embedded in `zip` archives and alike), but, e.g., a 1 GB `.exe` file works properly. Closing this issue as resolved for now.
