### ISSUE TITLE
Getting rid of MongoDB and GridFS completely

### ISSUE THREAD

**Issue by jbremer** [cuckoosandbox/cuckoo#766]
I'd like to discuss the following proposal which gets rid of MongoDB and GridFS usage completely. One of the reasons for me to move away from MongoDB is that I have no idea what's actually happening not to mention that I have absolutely no clue which and how data is actually stored in MongoDB or if there are any leftovers that are not properly garbage collected after deleting tasks both as-is as well as in the future (i.e., because of missing removal logic on Cuckoo's side).

Over the years I've heard several arguments come by on why MongoDB is a good or bad idea - I'll try to address most of them here (that I remember anyway), including my thoughts on those arguments. I'll also address work-in-progress ideas on how to fully replace MongoDB and all of its use-cases in our current setup.

If we were to continue with this transition it would be a fairly large change requiring quite a lot of changes in various parts of Cuckoo. Luckily we're currently working on our `2.0-rc2` release and should have enough time to get the full transition going by the time we hit our official `2.0` release; a release for which not being completely backwards compatible in favour of improving the project should be fine.

MongoDB is web-scale
==================

Yes, and Cuckoo is a dinosaur.

Two Cuckoo One Web Interface
=========================

One of the bigger and more important arguments that I've heard and want to work towards; being able to have multiple Cuckoo instances talk to the same Cuckoo Web Interface.
Unlike popular belief this is not actually possible at the moment. The problem lies in the fact that the [Web Interface uses the Task ID to lookup a particular analysis][taskid0] and that [it uses the same Task ID for retrieving the behavioral analysis][taskid1]. As you can imagine, your two Cuckoo instances both start with Task ID 1, making a collision. This collision isn't an issue for MongoDB, it just makes MongoDB return the first instance, or the last one, or.. who knows ;-)

Although I'm not aware of any such instances being used in production at the moment (with multiple Cuckoo instances and one Web Interface), there is plenty of use for it in the near future. As an example; in order to run both *regular* analyses in the sense of Windows VMs as well as a Bare Metal instance (which talks to one or more actual laptops for running samples in a non-VM environment) or Linux VMs / Mac OS  X VMs / Android Emulator at least two Cuckoo instances are required (and this is not something that will be changed for various reasons that I won't go into too much detail about here).

In order to resolve this issue two solutions come to mind.
* Make the Web Interface so that it doesn't look for the Task ID but generate some other random value.
* Utilize Distributed Cuckoo in-between the various Cuckoo instances and the Web Interface.

The first solution is actually fairly easy to resolve, however, it doesn't help much in the bigger scheme of things. E.g., when you submit a sample through the Web Interface; to which Cuckoo instance should it go? ;-)

The second solution helps in both directions. It can accept reports from Cuckoo instances and it can propagate tasks to the Cuckoo instances. As you may imagine for a project called *Distributed Cuckoo* this is pretty much the only thing it's good at (at the moment anyway).

[taskid0]: https://github.com/cuckoosandbox/cuckoo/blob/master/web/analysis/views.py#L233
[taskid1]: https://github.com/cuckoosandbox/cuckoo/blob/master/web/analysis/views.py#L93

But I want to download dropped files through the Web Interface!
===================================================

So here's the thing. Currently we duplicate most of the data that we generate. A Cuckoo instance will store all files for a task in the `storage/analyses/task_id` directory. This data contains an analysis log, a network dump, some behavioral logs, dropped files, reports, and some more stuff.
Now that's all fully functional and working nicely. But then you have the Web Interface; the Web Interface can't interact with that data, it needs a copy on its own. So the `MongoDB` reporting module sends a copy of almost all of the files into the Private Web-Scale MongoDB Cloud.

I hear you asking; how is the Web Interface using all of that data? Some files are served on-demand. Some files are generally speaking never ever touched. Some files get searched through. And that's about it.

Now imagine Cuckoo reports, where 1mb of screenshots, 10mb of dropped files, and 100mb of behavioral logs is nothing unheard of. All of this data is stored in `storage/analyses/` and in MongoDB.

Following is a small breakdown of which data is stored in MongoDB and how it is used in practice.
* Screenshots; retrieved in order to be displayed when an analysis report is opened.
* Dropped files; retrieved only when somebody decides to download it, untouched otherwise.
* Behavioral logs; retrieved on-demand. Stored in chunks of 100 API calls so that it is kind of easy to paginate the results. When somebody *searches* for a string in a task, *all* behavioral logs are retrieved, enumerated, and only the matching API calls are returned to be shown in the Web Interface.

There is some more data indexed into MongoDB, but not with much more purpose or different use-cases than outlined in the examples above.

New solution proposal
==================

**Wouldn't it make much more sense to store all just in `storage/analyses/` and not in MongoDB/GridFS?**

All of the files are already on the filesystem. The only thing that would be required is splitting the behavioral data from the rest of the report, as this part of the data is usually orders of magnitude larger than the rest.
It could even be stored in chunks of, say, 1000 API calls per file on the filesystem (rather than one big file), so that paginating is still somewhat trivial. Or alternatively keep the BSON files as we have them as-is and simply keep offsets into the files for certain steps (e.g., one offset for every 1000th API call entry).
Searching in this case naturally involves going through all of the files (much like we do right now with MongoDB) or alternatively may be offloaded to ElasticSearch, if it is enabled, but that's a different topic.

With this in mind - keeping the directory structure as we've had it for years - we keep the analysis data easy to access and use.

But the Web Interface and Distributed Cuckoo?
=====================================

Yes, by removing MongoDB from the Web Interface we'll have to provide the Web Interface access to the analysis data on the filesystem. For *normal* setups this shouldn't be any problem to setup - it would be the default setup.
For setups with multiple Cuckoo instances this implies that, as part of processing a file, Distributed Cuckoo will basically *collect* all files from each analysis. The Web Interface should then be configured to use the directory structures provided by Distributed Cuckoo - something which is very similar to the current directory structure aside from the fact that the base path is somewhere else (i.e., not `cuckoo/storage/analyses/`).

How does this affect storage and CPU?
===============================

I'm glad you asked! For regular setups (just one Cuckoo instance) not much will happen. Except that rather than duplicating the data (once in `storage/analyses` and once in the MongoDB cloud) it will now only be available on the filesystem - as it should have been in the first place.
For bigger setups, i.e., either setups with multiple Cuckoo nodes/machines or setups with multiple Cuckoo instances on one machine (e.g., Windows VM + Linux VM), the results from the various Cuckoo instances will be gathered and stored at the Distributed Cuckoo / Web Interface side. It should be noted that this allows the Cuckoo instances to have a limited amount of harddisk space and then to have the real storage capabilities at the Distributed Cuckoo / Web Interface part.

Regarding CPU and performance. The real CPU intensive computations will be done at the various Cuckoo instances and then Distributed Cuckoo and the Web Interface are mostly there to gather all of that data and to represent it. The only part where some CPU performance is required is when searches take place.

Integrate Distributed Cuckoo and the Web Interface?
==========================================

Could do, could do. Perhaps should have the ability to do so, although there are use-cases for requesting everything through the simple Distributed Cuckoo API. What comes to mind here is the part where the Web Interface may be hosted on an external facing server or VPS with limited resources. In that case there is something to be said for talking to Distributed Cuckoo which would be a machine with - perhaps - 2 or 4 cores and a **whole lot** of storage.

Conclusion
=========

I hope it is clear why I'd like to transition away from MongoDB onto something that's arguably easier to manage (e.g., `rm -rf storage/analyses/1234` removes pretty much of all the data associated with that task - except for a couple of database rows and any indexed ElasticSearch documents).
As we're using it right now there is no real reason to use MongoDB. Unlike our new ElasticSearch integration - which provides us with instant search results - there's nothing special about our usage for MongoDB, we're literally using it just for storage. But then of course it's more of a pain to manage in case you want to remove parts of the data, e.g., all screenshots older than a month, or want to do like, anything else that you can do with standard linux shell commands.

Furthermore this solution will make setting up multiple Cuckoo instances - something which is getting more and more of a *thing* now that we have multiple analysis targets (Linux, Mac OS X, etc) available - an easier to manage process. **As-is you'll require two Cuckoo instances and Web Interfaces to be able to use two different analysis targets!** (unless you're lucky that they share the same machinery module, but still there are cases where this is not desired).

Having said all of that, it'd be nice to hear some opinions and thoughts about why this is a bad or a good idea.

Thanks,
Jurriaan

**Comment by jekil** [comment]
I want to go back in the history and to the requirements we used writing the web interface:

1. Web interface should be able to run on another host (one cuckoo server, one web server, one mongodb server)
1. The data storage technology used should be able to scale on more than one host (for storage size issues but also for performance)
1. People are used to frequently clean the cuckoo storage, so data should persists on another storage (i.e. mongo)

During the time some of these initial "good intentions" were not respect by code committed by many people.

In my opinion the point is not only mongodb yes or no, but also:

- In fact, we have 3 web interfaces, we django one, API and distributed cuckoo. I would like to merge in one.
- We should fix the web interface to really be decoupled from the cuckoo host.
- The local SQL db. I will be happy if we would get rid of it. 
- I am ok to separate binary data from text one, for example writing binary data in Hadoop and text data in anything fashion you like 
- ES use: it is great we started with a module, we should improve it. (BTW technically ES could just index data in mongo).

Your description is really detailed and dissect the issue really well, i read it quickly so what I wrote is just my first impression, more will come :)

**Comment by KillerInstinct** [comment]
Getting rid of Mongo may hinder searching. Unless you plan on switching that to ES and making that a requirement with Django. Or at least I can't see an easy way to keep searching speedy, if you move to just FS storage. Personally I just recommend getting rid of GridFS

**Comment by jbremer** [comment]
How so? As outlined above; instead of retrieving **all** logs from MongoDB you would now be retrieving them from the filesystem (in the form of the raw bson files).

**Comment by KillerInstinct** [comment]
I would recommend testing having 1000 tasks and searching for something like mutex:<some_mutex>

Something that requires a Mongo search would be much more difficult to implement in a filesystem. I'm not sure how you would search for summary logs efficiency of all tasks without Mongo or ES.

**Comment by jbremer** [comment]
Sorry, I meant to say there's a difference between doing a search for one analysis task, and for many or all tasks.
I.e., if you want to do a quick search in one task then going through the logs is fine. For global search ElasticSearch would be required and that one has two modes currently; only the summary (minimal amounts of data) or all behavioral logs.

**Comment by KillerInstinct** [comment]
Exactly, so some search love will need to be had. Otherwise in order to remove Mongo, you will also remove some search view functionality (EG VT)

**Comment by jbremer** [comment]
Well, non ElasticSearch-based search functionality has already been removed from our Web Interface, so I guess that ship has sailed already anyway.

**Comment by jbremer** [comment]
Well, this is not going to work out as MongoDB turns out to be Web Scale in the end.
Going to close this issue although I'm still interested to see benchmarks with regards to storage size of Cuckoo reports in MongoDB. Pinging @rep for the benchmarking.
