### ISSUE TITLE
Which password should I fill in？

### ISSUE THREAD

**Issue by Ryuchen** [cuckoosandbox/cuckoo#771]
# Credentials to access the machine
user = 
password = 
I tried many many times , using the guest's username and password or host's username and password, but I still get error tips below:
2016-02-17 02:21:25,184 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/leanne/cuckoo/lib/cuckoo/core/scheduler.py", line 447, in run
    self.launch_analysis()
  File "/home/leanne/cuckoo/lib/cuckoo/core/scheduler.py", line 379, in launch_analysis
    machinery.stop(self.machine.label)
  File "/home/leanne/cuckoo/modules/machinery/physical.py", line 111, in stop
    output = subprocess.check_output(args)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['net', 'rpc', 'shutdown', '-I', u'192.168.59.128', '-U', 'Ryuchen%Ryuchen', '-r', '-f', '--timeout=5']' returned non-zero exit status 255

so I want to know which machine 's password and username !!!!!!!

**Comment by jekil** [comment]
I am sorry but this really a messed up issue, please try to describe in order and with more info you can it.

In the physical.conf there are two couples of credential, one for fog and one for the physical machine, you should follow the comments.
I suppose you are referring to the username and password of the physical host where you want to run an analysis, so the credentials you put in windows. Also check to have your firewall disabled and double check our documentation.

**Comment by jbremer** [comment]
And make sure that `rpc` is enabled on that physical machine. Return code 255 doesn't sound too promising to me. Please try the `net rpc shutdown` command on the command-line and make sure it works before continuing with Cuckoo.

**Comment by Ryuchen** [comment]
Thanks.Finally,I find the way to solve this problem.This is my own problem,the physical machines have to allow other accounts to logon themselves but I didn't grant it.
And I have another problem.I use the fog project with cuckoo,it is useful but spend 2 minutes to download the image.It seems a little slow,is there any solution to make it download faster?

**Comment by jbremer** [comment]
Actually you're lucky with just two minutes - I find it to be much slower usually ;-) Do realize that the OS on the machine is restored completely for each analysis.
Closing this issue as resolved.
