### ISSUE TITLE
Import Yara Rules for YaraScan Recursively

### ISSUE THREAD

**Issue by MiquelT** [cuckoosandbox/cuckoo#773]
For import _yarascan_ rules you have to edit the file `cuckoo/data/yara/memory/index_memory.yar` and insert all yara rules there.

It's tedious to copy all YARA rules to an unique file if you have your yara rules organized by directories.

So I propose to permit to insert your YARA rules directory at  `cuckoo/data/yara/memory/` and import all YARA rules that you can find recursively at this directory.

You could modify `cuckoo/data/yara/index_memory.yar`  and set an other path where you have all your YARA rules and it will import all of them.

What do you think?

**Comment by jbremer** [comment]
Isn't this already what's happening? E.g., all the `.yar` files in `data/yara/binaries` are embedded into the `index_binary.yar` file. I somewhat assume the same is the case for memory-related Yara rules.
Please correct me if I'm wrong.

**Comment by KillerInstinct** [comment]
I believe if you dump your rule files into that directory (binary or memory) it adds a yara import statement to the index files respectively via https://github.com/cuckoosandbox/cuckoo/blob/b2475980d75d06ca9f35424192c55e022e46952f/lib/cuckoo/core/startup.py#L252

For this to work you must restart cuckoo after dumping your files.

**Comment by certau-davidg** [comment]
It does not appear to recursively add yara files from subdirectories, however a simple work around is to create a second index file:

> cd <cuckoo>/data/yara/binaries/
> find `pwd`/binaries/*/* -type f | sed -r 's/(.*)/include \"\1\"/g' > /opt/cuckoo/data/yara/binaries/other_index.yar
> (verify access permissions are correct)
> (restart Cuckoo to generate fresh index)

**Comment by jbremer** [comment]
I guess adding recursive directory support for Yara files isn't a lot of effort, I'll put it on my todo list as well @certau-davidg ;-)

**Comment by jbremer** [comment]
This has now been resolved and will be available in the next alpha or stable Cuckoo release. I'll be closing this issue though. Thanks again and sorry for the long delay.
