### ISSUE TITLE
May it be a code error ?

### ISSUE THREAD

**Issue by WangLei1993** [cuckoosandbox/cuckoo#777]
In `cuckoo/lib/cuckoo/common/utils.py`, decorator classlock, line 262, I think it may add a "`not`" in this sentence "`if calframe[1][1].endswith("database.py"):`". Is it right? If not, could give me some simple reason about it? Thanks, I'm just a learner!

**Comment by jbremer** [comment]
Thanks for reporting, @WangLei1993. @rep thoughts?

**Comment by jbremer** [comment]
Sorry for not properly reviewing this issue any earlier. I think the check is related to recursive calls, i.e., if one of the `Database` functions calls another such `Database` function you don't want to hold the lock twice, as it probably doesn't support that. So.. that! It should be correct - closing this issue.
