### ISSUE TITLE
Exception Handler

### ISSUE THREAD

**Issue by yoonack** [cuckoosandbox/cuckoo#780]
I am trying to implement something like Olly memory guard stuff. I set a newly allocated memory page to be PAGE_GUARD. I also created UnhandledExceptionFilter using SetUnhandledExceptionFilter() API. However, when it tried to ReadFile, it should trigger the exception handler, but it didn't it cause the ReadFile to fail. I am wondering is there any other exception handler implemented in the monitor? Or am I doing this in a wrong way? 

Thanks, I would appreciate any help!

**Comment by jbremer** [comment]
The monitor intercepts exceptions, but doesn't modify it in any way really - aside from logging it. You should keep in mind that `ReadFile` goes directly into a system call and in turn the kernel decides that the pointer is invalid and simply returns an error code; rather than crashing anything.
It's probably easier to get a pointer to your page and write to it, i.e., `uint8_t *ptr = addr; *ptr = 0;`.

Jurriaan

**Comment by yoonack** [comment]
My purpose of doing this is monitoring the location of the code that writes the byte into the memory. In MSDN document, it says if a page is set as protection Page_Guard, any writing or reading from that memory would trigger Status_Guard_Page_Violation exception. I am trying to use UnhandledExceptionFilter to capture this type of exception like Olly does. However, it seems like my exception handler is not being triggered.
Here is my Exception Handler Code: 
LONG WINAPI GuardExceptionHandler(LPEXCEPTION_POINTERS pe)
{
    log_debug("the exception is happening at %x, with exception code: %x, and NTSTATUS: %x", pe->ExceptionRecord->ExceptionAddress, pe->ExceptionRecord->ExceptionCode, pe->ExceptionRecord->ExceptionInformation[2]);
    if(GetLastError() == STATUS_GUARD_PAGE_VIOLATION)
    {
        log_debug("the created memory at address: %x is accessed", pe->ExceptionRecord->ExceptionAddress);
        return EXCEPTION_EXECUTE_HANDLER;
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

I use lastExceptionHandlerAddress = setUnhandledExceptionFilter(GuardExceptionHandler); to create my exception handler, and then use:
DWORD dwNewProtect;
    dwNewProtect = Protect | PAGE_GUARD;
    virtual_protect(*BaseAddress, (uintptr_t)RegionSize, dwNewProtect);
    log_debug("The baseaddress at %x is set with new protect: %x", &BaseAddress, dwNewProtect);
to set memory page. The program itself would call ReadFile() API. In Theory, it should call my unhandledExceptionFilter. I am wondering if my exception handler is being replaced.

**Comment by jbremer** [comment]
Your code looks fine, just don't use ReadFile as I mentioned ;-)

**Comment by yoonack** [comment]
I am not using ReadFile, its the malware program that would call ReadFile to read data from the original file. Hence, this type of exception cannot catch the ReadFile?

**Comment by jbremer** [comment]
I suggest you try running an example binary that you implement and compile yourself to test if what you'd like to achieve works in the first place.

**Comment by yoonack** [comment]
Thanks for the help

**Comment by jbremer** [comment]
I guess I can close this issue. Feel free to reopen if you have additional feedback and/or code etc, @yoonack.
