### ISSUE TITLE
REST API using uWSGI setup

### ISSUE THREAD

**Issue by yoonack** [cuckoosandbox/cuckoo#781]
I followed the documentation listed on the website to setup uWSGI.
when I start the service, its returning OK. Then I use the following command to submit file:
 curl -F file=@/home/kc/sample http://localhost:8090/tasks/create/file,
it gave me: curl: (7) Failed to connect to localhost port 8090: Connection refused
Then I checked the log file for uwsgi at /var/log/uwsgi/app/cuckoo-api.log,
The following log appears:
Tue Feb 23 17:42:08 2016 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Tue Feb 23 17:42:08 2016 - Python main interpreter initialized at 0x1e2d070
Tue Feb 23 17:42:08 2016 - your server socket listen backlog is limited to 100 connections
Tue Feb 23 17:42:08 2016 - your mercy for graceful operations on workers is 60 seconds
Tue Feb 23 17:42:08 2016 - mapped 218376 bytes (213 KB) for 2 cores
Tue Feb 23 17:42:08 2016 - *** Operational MODE: preforking ***
Tue Feb 23 17:42:08 2016 - unable to find "application" callable in file utils/api.py
Tue Feb 23 17:42:08 2016 - unable to load app 0 (mountpoint='') (callable not found or import error)
Tue Feb 23 17:42:08 2016 - *** no app loaded. going in full dynamic mode ***
Tue Feb 23 17:42:08 2016 - *** uWSGI is running in multiple interpreter mode ***
Tue Feb 23 17:42:08 2016 - spawned uWSGI master process (pid: 30023)
Tue Feb 23 17:42:08 2016 - spawned uWSGI worker 1 (pid: 30036, cores: 1)
Tue Feb 23 17:42:08 2016 - spawned uWSGI worker 2 (pid: 30037, cores: 1)

looks like, it cannot find the api.py. I am not sure what went wrong. However, i followed instruction step by step.

**Comment by doomedraven** [comment]
@yoonack is app, not application
https://github.com/cuckoosandbox/cuckoo/blob/master/utils/api.py#L34

try something like this in standalone mode
uwsgi --http 0.0.0.0:8090  --wsgi-file utils/api.py --callable app --master --processes 2 --threads 2

**Comment by jbremer** [comment]
Indeed, what @doomedraven said should resolve the issue here. Closing the issue.
