### ISSUE TITLE
Error with MongoDB

### ISSUE THREAD

**Issue by seifreed** [cuckoosandbox/cuckoo#784]
Hi,

Seems exists a problem with the last Cuckoo version generating the report to MongoDB

/home/remnux/tools/malware/cuckoo/lib/cuckoo/common/abstracts.py:731: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if item.lower() == pattern.lower():
**2016-02-26 05:47:04,768 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":**

Pymongo version

pymongo (3.0.3)

**Comment by jbremer** [comment]
The `UnicodeWarning` has been resolved recently in the development version of Cuckoo.
Could you please post the entire stacktrace that you retrieved? As-is there's not much to work with ;-)

**Comment by bit111** [comment]
I have the same issue. How can I solve it?

**Comment by jbremer** [comment]
At the time, I guess not really. Closing this issue as resolved, though.
