### ISSUE TITLE
VirtualBox 5.0 vboxnet0 interface shutdown after VM shutdown

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/cuckoo#786]
In newer versions of VirtualBox it appears that the host-only interface is shutdown the moment a VM is shutdown. This causes issues with Cuckoo where following analyses fail to initialize properly.
If verified, we need to automatically reinitialize the interface like `VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1`.

**Comment by sachinkamath** [comment]
I can confirm the bug. Happens to me too.

**Comment by botherder** [comment]
Weirdly, the ResultServer doesn't seem to be affected. However, tcpdump isn't able to initialize properly unless it's wrapped by a monitor bash script. We need to incorporate a better solution for this. The problem is that initializing the hostonlyif through VBoxManage requires root privileges.

**Comment by jbremer** [comment]
> The problem is that initializing the hostonlyif through VBoxManage requires root privileges.

Are you sure about that? On VirtualBox 4 this is definitely not the case, I haven't tried VirtualBox 5 though.

**Comment by lehmz** [comment]
At least on Ubuntu 14.04 and Virtualbox 5.0.14r105127 you don't need root privileges to initialize interfaces through VBoxManage. 

On my setup hostonlyifs are left up after VM shutdown the same way they did in the previous version of VirtualBox. Could this be happening only on a specific OS & VirtualBox 5 combination?

**Comment by snemes** [comment]
I can confirm this bug too, if I recall correctly I started to see this happening after upgrading to Ubuntu 15.04 or 15.10, so I think this is more likely related to the Linux version than the VirtualBox version.

**Comment by jbremer** [comment]
Anyone have any updates on this matter? There haven't been any updates on the Cuckoo side regarding the VirtualBox module, so I guess this issue is still present?
@razuz you are running VirtualBox 5, right?

**Comment by Higgsz** [comment]
I've this issue. I have Debian "jessie" and Virtualbox 5.0.22r108108. vboxnet0 interface is being shutdown after vm shutdown.

**Comment by seifreed** [comment]
I never saw this with Debian.. You have any log, example or something?

--
Marc Rivero López | @seifreed | www.ecrime.info

2016-06-29 12:31 GMT+02:00 Lasha <notifications@github.com>:

**Comment by razuz** [comment]
I'm running on ubuntu 14.04 LTS without issues
ii  virtualbox-5.0                       5.0.22-108108~Ubuntu~trusty             amd64        Oracle VM VirtualBox

**Comment by Lindi16** [comment]
same issue on my Ubuntu - TestEnv. 
i added an "start.sh" script ->
```
VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1.
#python cuckoo.py --clean
python cuckoo.py -d
```

**Comment by jbremer** [comment]
This doesn't seem to be an issue anymore. Closing this issue.
