### ISSUE TITLE
virustotal via proxy

### ISSUE THREAD

**Issue by AntonAsssssa** [cuckoosandbox/cuckoo#790]
Could yuo help me to configure proxy for virustotal modul.

I configured proxy in env.

2016-02-29 16:54:48,248 [modules.processing.virustotal] WARNING: Error fetching results from VirusTotal for "03f0074251b5a23d303eec24e7ec4f6fe44f5a548be511c756836fdabb6c4ce7": Unable to fetch VirusTotal results: MaxRetryError("HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcd28cb51d0>: Failed to establish a new connection: [Errno 111] Connection refused',))"

**Comment by botherder** [comment]
Why would you proxy that?

**Comment by AntonAsssssa** [comment]
My server with the cuckoo obtains the Internet only through the proxy.

**Comment by AntonAsssssa** [comment]
Please F1

**Comment by jbremer** [comment]
Might as well just add an internal IP address for `www.virustotal.com` into `/etc/hosts` and go for some proxying black magic from there.

**Comment by jbremer** [comment]
Or proxy the whole machine through the proxy..

**Comment by AntonAsssssa** [comment]
Hi, Jurriaan!

Virustotal.py module only. I found that it using urllib3 for connention but I cannot send it via proxy server. I tried to do like here http://public.honeynet.org/pipermail/cuckoo/2012-December/001142.html but it doesn't work for me.(

**Comment by shiryu92** [comment]
Add:
     proxy = urllib2.ProxyHandler({'https': 'http://proxy:port'})
     opener = urllib2.build_opener(proxy)
     urllib2.install_opener(opener)
Before:
  request = urllib2.Request(url, data)
  response = urllib2.urlopen(request, timeout=int(timeout))
  response_data = response.read()

in modules/processing/virustotal.py

**Comment by AntonAsssssa** [comment]
I have no these rows in modules/processing/virustotal.py:
request = urllib2.Request(url, data)
response = urllib2.urlopen(request, timeout=int(timeout))
response_data = response.read()

**Comment by garanews** [comment]
#       r = requests.get(url, params=data, verify=True, timeout=int(timeout))
     #added proxy
            proxies = {"http": "http://proxy.lab:3128/", "https": "http://proxy.lab:3128/"}
            r = requests.get(url, params=data, verify=True, timeout=int(timeout), proxies=proxies)

**Comment by jbremer** [comment]
What @garanews said. I don't think that we have interest in maintaining such proxy support ourselves, but if you have a PR, preferably with a `proxy.conf` configuration file, then we can discuss integrating it. Closing the issue for now though.
