### ISSUE TITLE
[Errno 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by iurnah** [cuckoosandbox/cuckoo#791]
After upgrade from 1.2 to 2.0-dev. I came across this wired problem that after the analysis packages have been uploaded to guest machine and start the analyzer, a socket related exception happened. After the exception, the guest is still able to transfer screenshot to result server, but nothing else. It is wired because the update initially works fine for a single sample, then the error appears. I've tried a new vm snapshot and download cuckoo again. The problem persists. Please see the attached pictures. Thank you.
Here is the pcap: [dump.pcap.zip](https://github.com/cuckoosandbox/cuckoo/files/152064/dump.pcap.zip)
![0002](https://cloud.githubusercontent.com/assets/3065779/13405983/24dd0b56-deef-11e5-9773-772293de2058.jpg)
![0013](https://cloud.githubusercontent.com/assets/3065779/13406079/a50e5438-deef-11e5-92f2-2d4ef759107b.jpg)

**Comment by jbremer** [comment]
No traffic is going out of the VM, did you correctly configure the network including gateway/netmask/etc?

**Comment by iurnah** [comment]
Thank you for your time @jbremer. I think my network configuration is works. 

I tested both version 1.2 (everything is normal) and 2.0-dev (with the error message) to execute a single sample and compared the reports, It seems the error doesn't effect the analysis results, because the two reports are of the similar length. 

What make me post this issue is that when using 2.0-dev, I run in to this error. The sample won't start UI. I thought the analysis failed, while in fact it may not.? Version 1.2 produce no error message and the application UI start, the human.py module works alright, everything works ok. Anyway, I will temporarily revert back to version 1.2 and will look into why this happened for the new version. when get familiar with the code base.

**Comment by doomedraven** [comment]
@iurnah did you updated agent.py to last version in your vm? or you use from v1.2? i had some issues in  past but with update to last version of agent.py everything now works fine on my v2-dev

**Comment by kholbrook1303** [comment]
Agent version reported by @iurnah was both 2.0 and 1.2, so should be moot.  Guest manager should be temporarily legacy (according to the code comments), so should be compatible @ minimum on 1.2 till further renditions.

**Comment by iurnah** [comment]
@jbremer @doomedraven @kholbrook1303. Thank you for your replies. I have solved the problem. The root cause is my virtual network settings. I have both NAT and Host-only adapter enabled in my virtualbox. After creating the snapshot and starting Cuckoo, all the IP settings in my Win7 guest are gone. The Errno 10054 plagued me because, with same network setting problem, the old 1.2 version worked fine. My current setting only uses Host-only network. The IP setting in guest keeps and everything works for the 2.0-rc1. Moreover, both agent.py in 1.2 and 2.0 works fine for me now.

**Comment by JSkier21** [comment]
I am also having this issue, although the network is fully functional and confirmed working. However no files are actually analyzed, seems like the agent on the guest doesn't work out the gate. Running xp and win7 guest, on version 2 of cuckoo and virtualbox. 
![cuckoofail](https://cloud.githubusercontent.com/assets/3190223/14388013/9c6d3718-fd71-11e5-9cc8-090087943d3f.jpg)

**Comment by iurnah** [comment]
Are you using NAT? Check your IP settings in your guest. The problem with
me is because the entered static IP in the guest will be reset when I
create the snapshot and run cuckoo. I was using both NAT and host-only
adapter. I think A DHCP IP is assigned for the guest so the network somehow
appeared to be working. I disable the NAT, the problem doesn't exist
anymore. My suggestion is to check you have the correct IP/DNS/gateway
settings in your guest network settings.

It seems to me the NAT can reset settings in guest machine, I don't know
why/how is that.

**Comment by JSkier21** [comment]
> Are you using NAT? Check your IP settings in your guest.

No nat on either machine, solely host-only adapter. I am able to communicate manually between host and guests (ping, port 8000). All IP settings appear to be correct and intact. 

Although, not related to cuckoo, I've seen this problem with NAT before and static IPs. Probably a VBox bug.

I'm running python 2.7.11, 64-bit on the host, 32-bit on the guests; don't think this could be the issue, but maybe it is? 

Might be related to #846, I see the 501 error in the traffic upon connect as well.

**Comment by limited-root** [comment]
i get this error, after analyzing around 130 samples. i tried for several times, always after around 130, VMs start working and report: an existing connection was forcibly closed by the remote host  .
cuckoo not giving any error

**Comment by deem0n** [comment]
Hopefully it might be interesting: I've got the same error in VirtualBox running pgc written in Python 2.7 https://www.bigsql.org/package-manager.jsp

I guess it is VirtualBox or Windows Python issue ?

**Comment by deem0n** [comment]
Upgrade Virtual Box to the latest version VirtualBox-5.0.30, it fixed the problem for me.

**Comment by jbremer** [comment]
Closing issue as resolved. Not 100% sure, but I believe some improvements have been made on our side regarding this bug, too. Please reopen if you have relevant information on this matter.
