### ISSUE TITLE
CRITICAL:cuckoo.process:Task X: exception in reports generation: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#793]
Hello all, 

start getting this few days ago after one of the git pull, and just made new deploy and reconfiguration of all the stuff, but still getting this error, tried to solve that, but can't find where it fails

* from cuckoo.py(with -d nothing interesting apart of this data)

```
2016-03-02 17:35:28,239 [lib.cuckoo.core.scheduler] INFO: Using "kvm" as machine manager
2016-03-02 17:35:28,638 [lib.cuckoo.core.scheduler] INFO: Loaded 8 machine/s
2016-03-02 17:35:28,652 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-03-02 17:39:20,722 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "1.docm" (task #1, options "route=none,procmemdump=yes")
2016-03-02 17:39:20,757 [lib.cuckoo.core.scheduler] INFO: Task #1: acquired machine cuckoo32 (label=W7x32)
2016-03-02 17:39:20,761 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 8950 (interface=virbr0, host=X, pcap=/opt/cuckoo/storage/analyses/1/dump.pcap)
tcpdump: listening on virbr0, link-type EN10MB (Ethernet), capture size 65535 bytes
2016-03-02 17:39:22,640 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo32, ip=192.168.122.101)
2016-03-02 17:40:08,222 [lib.cuckoo.core.resultserver] WARNING: Uploaded file length larger than upload_max_size, stopping upload.
2016-03-02 17:40:09,820 [lib.cuckoo.core.guest] INFO: cuckoo32: analysis completed successfully
21 packets captured
21 packets received by filter
0 packets dropped by kernel
2016-03-02 17:40:19,830 [lib.cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed
````

* and from process.py, debug mode says all stuff executed fine, so short log

```
python process.py -p5 auto
INFO:cuckoo.process:Task #1: queueing for reporting
CRITICAL:cuckoo.process:Task #1: exception in reports generation: 'NoneType' object is not callable
```

* with process -r 1 everything is ok, but cant' get report, no warning, no errors

any point what it can be?
Thanks in advance

**Comment by jbremer** [comment]
So this is the latest version of Cuckoo from Git? And you don't get the exception when running `./utils/process.py -r 1`? I'm honestly not sure how to help :)

**Comment by doomedraven** [comment]
It happens with process.py -pX(5in my case) auto, with -r analysis_id works but it not update mongo/EK

i start getting this from last week, but removing everything and with new install with lastest version still have this issue %)

**Comment by razuz** [comment]
what's your upload_max_size in cuckoo.conf under [resultserver] ? I needed to raise that, but I'm not sure if your case is similar. Can check that tomorrow.
Currently I run :
upload_max_size = 314572800

**Comment by doomedraven** [comment]
@razuz my one is default 100mb, but I had that stuff before, and everything worked just fine.
with your size limit i got more limit messages, and the same behaviour, probably will put 2.0-rc1 and done.

but this happened once an analysis is compleated by cuckoo.py and passed to process.py -p5 auto

just did quick test, @jbremer  i don't know the flow deep difference, but with __process_results = on__ and without process.py it works perfectly, with off and process.py fails

**Comment by jbremer** [comment]
Well, `process.py` is kind of broken.. if you're using PostgreSQL as database you should try out `process2.py`.. Or you can indeed just process the results in Cuckoo itself.
But unfortunately we can't really figure out what the actual issue was now..

**Comment by doomedraven** [comment]
I using mongo, i will try to do more deeper debug then log.debug, as with process.py -r X working fine

**Comment by razuz** [comment]
tried to reproduce that and cannot ...

only thing I can is :
2016-03-02 17:40:08,222 [lib.cuckoo.core.resultserver] WARNING: Uploaded file length larger than upload_max_size, stopping upload.

this is due to the fact that default upload_max_size under [resultserver] is 10M

if you can drop your conf I can try again

**Comment by doomedraven** [comment]
@razuz config is default only changed db connection,  machinery to kvm, and __process_results = off__, result server ip,  in processing activated mongo, and in memory activated memory analysis and changed vm vol profile, nothing else

i just grabbed v2-rc1 and moved configs. everything works fine

**Comment by consen** [comment]
I encountered the same problem with latest cuckoo.

**Comment by jbremer** [comment]
Me too.. I didn't locate the issue when I was debugging the issue earlier.. :|

**Comment by consen** [comment]
I found this is caused by `Dictionay` and `pool.apply_async`:

`lib/cuckoo/common/objects.py:68`
```python
class Dictionary(dict):                                                                                                                                                                                       
    """Cuckoo custom dict."""                                                                                                                                                                                 
                                                                                                                                                                                                              
    def __getattr__(self, key):                                                                                                                                                                               
        return self.get(key, None)                                                                                                                                                                            
                                                                                                                                                                                                              
    __setattr__ = dict.__setitem__                                                                                                                                                                            
    __delattr__ = dict.__delitem__
```

`utils/process.py:141`
```python
kwargs = dict(report=True, auto=True, task=task.to_dict())
result = pool.apply_async(process_wrapper, args, kwargs)
```` 

If use `dict`, it works well.

But I haven't found why.

**Comment by jbremer** [comment]
Wow, thanks @consen! I definitely did not expect that to be the issue.

**Comment by jbremer** [comment]
To all those involved in this issue, please try the fix in the commit above (https://github.com/cuckoosandbox/cuckoo/commit/7cc53957111d10fb32883e96a13c40e93a4b166d).
I'm closing this issue as fixed now - please open a new one or reopen this one if similar or related issues are found!

**Comment by doomedraven** [comment]
@jbremer this bug is patched :)
but there now is new one
as dict is changed, [this changed](https://github.com/cuckoosandbox/cuckoo/blob/master/lib/cuckoo/core/scheduler.py#L319)

`if self.task.category == "file":`

must be 

`if self.task['category'] == "file":`
 the same for others self.task values

if not raising errors of AttributeError

**Comment by doomedraven** [comment]
@jbremer  found the [bug] and solution(https://github.com/cuckoosandbox/cuckoo/blob/master/lib/cuckoo/core/scheduler.py#L133)
fi you remove .to_dict()

everything working fine

**Comment by jbremer** [comment]
Ah, yeah, thanks for locating the bug. I thought this would happen, yeah, but didn't have time to test it properly earlier.
Will fix it differently then, because we do want to keep the attribute-style way of using `self.task`. Also otherwise a *lot* of code should be changed in `scheduler.py`. Give me a few while I test it.

**Comment by doomedraven** [comment]
i think you referer to my previous not last comment, to solve it with one line only, just don't do .to_dict() in line [133](https://github.com/cuckoosandbox/cuckoo/blob/master/lib/cuckoo/core/scheduler.py#L133) and done, no bugs :)

**Comment by jbremer** [comment]
@doomedraven Please test the fix above! :)

**Comment by doomedraven** [comment]
@jbremer works perfectly :) thanks all to help patch this, will close this issue :)
