### ISSUE TITLE
is32bit.exe returning non-zero status causing analysis to terminate

### ISSUE THREAD

**Issue by yoonack** [cuckoosandbox/cuckoo#795]
I ran a sample recently which is gzip compressed. When I passed into cuckoo, it is giving me this error:
Error: Analysis failed: The package "modules.packages.exe" start function encountered an unhandled exception: Error returned by is32bit: Command '['bin\\is32bit.exe', '-f', u'C:\\DOCUME~1\\ADMINI~1\\LOCALS~1\\Temp\\1D0DC530.vsc']' returned non-zero exit status 1. I checked the decompressed file, its not 64bit, is there something else that may cause the error?
sample MD5:a08dea1e0b2453347f793be9c5f6872b
Thanks

**Comment by jbremer** [comment]
We don't actually gzip decompress your files for you as this is not a general use case. Please do so on your own ;-)

**Comment by yoonack** [comment]
Oh sorry for asking. I thought all the compressed file are decompressed and then being analyzed.

**Comment by jbremer** [comment]
No worries :-) Zips are unpacked etc, but as you can imagine `gzip` is not a very common compression format under Windows. Even on Linux `gzip -d` won't take it unless the file has a file extension, hehe.

**Comment by yoonack** [comment]
hmm. I am experiencing a lot of files that are zipped either with ace archive or gzip. I gonna find a way to add in automatic decompression for those files in cuckoo. Thanks for the help

**Comment by jbremer** [comment]
Really, where are those files/samples coming from? If it's something that's valuable to Cuckoo I don't mind helping out. It's just that I haven't seen that before.

**Comment by yoonack** [comment]
It's from some malware research source. Many malwares are ACE packed recently.
