### ISSUE TITLE
unroute_table crashes when machine startup is broken

### ISSUE THREAD

**Issue by XayOn** [cuckoosandbox/cuckoo#796]
If Machinery.start() raises an exception, we don't get to execute code on route_network, and sice interface and rt_table are not defined on __init__, it fails nongracefully.

This can be easily fixed by putting self.interface = None and self.rt_table = None in __init__ on AnalysisManager class

**Comment by jbremer** [comment]
Thanks for reporting! Should be fixed :)

**Comment by XayOn** [comment]
Perfect, thanks!

**Comment by jbremer** [comment]
Ok :-) Thanks again.
