### ISSUE TITLE
Display screenshots as low-quality thumbnails

### ISSUE THREAD

**Issue by heipei** [cuckoosandbox/cuckoo#798]
In the analysis overview, screenshots are loaded with their full resolution whenever the report is open. For some runs, this means that 10-20MB of screenshots have to be downloaded.

To avoid this, store the screenshots resized and compressed and only download the full-res version when the user clicks on it.

**Comment by jekil** [comment]
Nice feature

**Comment by jbremer** [comment]
This has been implemented as part of #863. Closing as such.
