### ISSUE TITLE
NameError: name 'httpreplay' is not defined

### ISSUE THREAD

**Issue by omers** [cuckoosandbox/cuckoo#802]
Clean installation of Cuckoo sand box on top of CentOS 7.

When I start the Cuckoo service I get the following:

[root@dev cuckoo]# ./cuckoo.py

                      __
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Outdated! Cuckoo Sandbox version 2.0-rc1 is available now.
Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0-dev
OS version: posix
OS release: CentOS Linux 7.1.1503 Core
Python version: 2.7.5
Machine arch: x86_64
Git version: b00588630298e9fd6172a29b5b15ba1076c186db
Modules: alembic:0.8.0 backports.ssl-match-hostname:3.4.0.2 beautifulsoup4:4.4.1 cffi:1.2.1 chardet:2.3.0 configobj:4.7.2 cryptography:1.0 decorator:3.4.0 django:1.8.4 dpkt:1.8.6.2 ecdsa:0.13 elasticsearch:2.2.0 enum34:1.0.4 flask:0.10.1 httpreplay:0.1.10 idna:2.0 iniparse:0.4 ipaddress:1.0.14 itsdangerous:0.24 jinja2:2.8 jsbeautifier:1.5.10 kitchen:1.1.1 langtable:0.0.31 mako:1.0.1 markupsafe:0.23 micropython-pystone:3.4.2-1 ndg-httpsclient:0.4.0 oletools:0.42 pefile:1.2.10-139 pip:7.1.0 pyasn1:0.1.8 pycparser:2.14 pycurl:7.19.0 pygobject:3.8.2 pygpgme:0.3 pyliblzma:0.5.3 pymongo:3.0.3 pyopenssl:0.15.1 python-augeas:0.5.0 python-dateutil:2.4.2 python-dmidecode:3.10.13 python-editor:0.3 python-magic:0.4.6 pyudev:0.15 pyxattr:0.5.1 requests:2.7.0 setuptools:0.9.8 six:1.9.0 slip.dbus:0.4.0 slip:0.4.0 sqlalchemy:1.0.8 tlslite-ng:0.6.0a3 urlgrabber:3.10 urllib3:1.14 wakeonlan:0.2.2 werkzeug:0.10.4 yum-langpacks:0.4.2 yum-metadata-parser:1.1.4

Traceback (most recent call last):
  File "./cuckoo.py", line 120, in <module>
    test=args.test)
  File "./cuckoo.py", line 68, in cuckoo_init
    init_modules()
  File "/usr/local/cuckoo/lib/cuckoo/core/startup.py", line 225, in init_modules
    import_package(modules.processing)
  File "/usr/local/cuckoo/lib/cuckoo/core/plugins.py", line 69, in import_package
    import_plugin(name)
  File "/usr/local/cuckoo/lib/cuckoo/core/plugins.py", line 59, in import_plugin
    module = __import__(name, globals(), locals(), ["dummy"], -1)
  File "/usr/local/cuckoo/modules/processing/network.py", line 56, in <module>
    _v = getattr(httpreplay, "__version__", None)
NameError: name 'httpreplay' is not defined

**Comment by omers** [comment]
python-test package was missing.

yum install python-test -y

fixed the issue

**Comment by jbremer** [comment]
Regardless of your workaround this was still an actual issue, thanks!
