### ISSUE TITLE
analysis not completed yet (status=2) 

### ISSUE THREAD

**Issue by jlems** [cuckoosandbox/cuckoo#809]
Hello,

I am trying to setup cuckoo sandbox on my machine and I keep getting this message. It keeps going until cuckoo times out and then it continues with the analysis process but it doesn't produce and analysis log file.

Another anomally that I have noticed is that when I run cuckoo.py and I submit it a malware sample for analysis, the virtual machine doesn't "open" on my desktop -- I know it is running because cuckoo is giving feedback and I can see it in the preview screen shot from the virtualbox main screen -- so from that preview screen I can see the real time updates of the agent.py running etc. 

I've been trying to trouble shoot this problem for a while but I can't figure out what the problem could be. Any help would be appreciated. If you need me to post some conf files or anything up here just let me know.

Thanks!

Edit 1:

So I changed the vm mode from headless to sdl and now the vm runs where I can see it and interact with it. It turns out that I'm getting an error message that says "error getting access to process: 5!" Cuckoo was getting hung up here and needed user interaction to hit ok. After I hit ok I get this, which I screened shot because it goes away fast. 

![screenshot from 2016-03-13 10 49 05](https://cloud.githubusercontent.com/assets/9592645/13729370/dd268bf0-e909-11e5-9a19-80c1cbc8942f.png)

gonna keep trying more trouble shooting, will update if anything changes. 

Edit 2:
After reading around the web I found out that you should launch agent.py on the host machine using admin rights. So what I did was start up cmd.exe with admin priveleges and then ran agent.py from the command line. Once agent.py ran, I took a new snapshot and ran cuckoo again and it worked. 
So that solved that problem and it seems like cuckoo is working for the most part.

Now I am having issues with the manage.py runserver script. My latest error is "NoReverseMatch at /analysis/24/". I get this error when I click on one of the submitted jobs. I'll try to debug this and get back with results.

**Comment by jbremer** [comment]
Thanks for figuring it out yourself and sorry for the late reply. The `NoReverseMatch` issue you can workaround as documented here http://docs.cuckoosandbox.org/en/latest/faq/#error-during-template-rendering. Closing as resolved.
