### ISSUE TITLE
Import/Export error

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#812]
Hello

* in case of analysis export I get error target key not exists [here](https://github.com/cuckoosandbox/cuckoo/blob/master/web/analysis/views.py#L600)

I solved that for me with `if report.get('target', None)` but i don't know if it will be correct solution for project

```
Django Version: 	1.8.4
Exception Type: 	KeyError
Exception Value: 	
'target'
Exception Location: 	/opt/cuckoo_git/web/analysis/views.py in export, line 603
Python Executable: 	/usr/bin/python
Python Version: 	2.7.11
```

* In case of export I getting all the time bug [line](https://github.com/cuckoosandbox/cuckoo/blob/master/web/analysis/views.py#L659):

```
Django Version:	1.8.4
Exception Type:	KeyError
Exception Value:	
"There is no item named 'analysis.json' in the archive"
Exception Location:	/usr/lib/python2.7/zipfile.py in getinfo, line 909
Python Executable:	/usr/bin/python
```

**Comment by jbremer** [comment]
Makes one wonder, why don't you have the `target` in the report? And what do you import when you weren't able to export an analysis?
I'm definitely up for improving this to make it less error-prone, but going to need some more info :)

**Comment by doomedraven** [comment]
I tried to import all files(marked by defaul) and only few of them, no idea why i don't have target, i had similar issues today with [this](https://github.com/cuckoosandbox/cuckoo/blob/master/modules/reporting/mongodb.py#L113) no info key

**Comment by jbremer** [comment]
You'll probably want to enable `analysisinfo` and `targetinfo` in your `processing.conf`. Other than that I'll workaround those issues later :)

**Comment by doomedraven** [comment]
`analysisinfo ` was enabled, targetinfo not. now works, with both enabled, thanks

**Comment by jbremer** [comment]
Will keep it open until your tracebacks have been resolved. Some warnings could be useful.
Especially since this will be used to help users debug their setups in the future.

**Comment by doomedraven** [comment]
i think this also related, start getting this errors during this week, if an analysis was very short like 20 sec and terminated, but all options was activated this time, which this change works fine
https://github.com/cuckoosandbox/cuckoo/blob/master/modules/reporting/mongodb.py#L113

i changed `report["info"]["analysis_path"] = self.analysis_path` to 

```
if not "info in report:
    report.setdefault("info", dict())
report["info"].setdefault("analysis_path", self.analysis_path)
```

**Comment by jbremer** [comment]
@doomedraven Do you have `analysisinfo` disabled in `processing.conf`? If so, why? :-P

**Comment by doomedraven** [comment]
@jbremer hehe no, this time everything was anabled, but analysis was like 18 seconds(probably some packer or something), and i got this error with few samples, as info key not presented mongodb reported fails and i can't see nothing on webgui, as report not generated, but i patched it to check key and if not exists to create it and it works now fine, even with failed samples

**Comment by jbremer** [comment]
I believe all of the issues here have been resolved, could you please verify @doomedraven?

**Comment by doomedraven** [comment]
i will check in a bit

**Comment by doomedraven** [comment]
@jbremer just did pull with overwrite everything by default, export everything fine, import zip fails

```
UnboundLocalError at /analysis/import/
local variable 'info' referenced before assignment
Request Method:	POST
Request URL:	http://192.168.1.46:8000/analysis/import/
Django Version:	1.9.5
Exception Type:	UnboundLocalError
Exception Value:	
local variable 'info' referenced before assignment
Exception Location:	/opt/cuckoo/web/analysis/views.py in import_analysis, line 732
Python Executable:	/usr/bin/python
Python Version:	2.7.11
```

**Comment by jbremer** [comment]
You're right @doomedraven, fixed it straight away.

**Comment by doomedraven** [comment]
now everythign works just fine :) closing

**Comment by jbremer** [comment]
Cool, thanks for the quick feedback.
