### ISSUE TITLE
Specifying options with '.' in name result in InvalidDocument from Mongo

### ISSUE THREAD

**Issue by arbor-jjones** [cuckoosandbox/cuckoo#814]
With mongo reporting enabled, specifying an option value that contains "." in the key will result in an insertion failure to mongo - existing module that can cause this is the human module.

Setting check_keys=False in the various .insert() and .save() functions fixes the issue, but the preferred fix I found investigating the issue seems to replace the '.' with a different character to avoid possible mongo issues in the event that option becomes deprecated. Other option seems to be to deprecate option values with '.' in them inside of cuckoo

    ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
    Traceback (most recent call last):
      File "/data/cuckoo2/utils/../lib/cuckoo/core/plugins.py", line 506, in process
        current.run(self.results)
      File "/data/cuckoo2/utils/../modules/reporting/mongodb.py", line 225, in run
        self.db.analysis.save(report)
      File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
        check_keys, manipulate, write_concern)
      File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
        self.codec_options, sock_info)
    InvalidDocument: key 'human.move_mouse' must not contain '.'
    DEBUG:lib.cuckoo.core.plugins:Executed reporting module "ReportHTML"`

http://api.mongodb.org/python/1.7/api/pymongo/collection.html#pymongo.collection.Collection.insert

> Parameters:	
> doc_or_docs: a SON object or list of SON objects to be inserted
> manipulate (optional): manipulate the documents before inserting?
> safe (optional): check that the insert succeeded?
> **check_keys (optional): check if keys start with ‘$’ or contain ‘.’, raising pymongo.errors.InvalidName     in either case**
>

**Comment by jbremer** [comment]
Yes, you're right. Thanks for reporting. I'll consider a workaround soon - a related issue is also present in one or two other places.

**Comment by jbremer** [comment]
This should now be fixed @arbor-jjones, thanks for reporting! Closing as fixed but feel to re-open or create a new issue if that's not the case for you.
