### ISSUE TITLE
ESXi SessionTimeOut

### ISSUE THREAD

**Issue by mike-veal** [cuckoosandbox/cuckoo#816]
HyperVisor: ESXi 

If Cuckoo doesn't have a sample submitted to it for 120 minutes the ESXi HTTP Session times-out. Obviously you can remove the timeout from within VSphere, however in our environment we are unable to. Can Cuckoo/Libvirt send keep-alive requests to maintain sessionstate?

Copy of the error received
"internal error: HTTP response code 500 for call to 'SessionIsActive' Fault: ServerFaultCode - The Session is not authenticated"

**Comment by KillerInstinct** [comment]
What version of ESXi?

Also, you mentioned libvirt, which is the esx machinery. I personally recommend you install the pyvmomi python library (and C headers / etc) as those are supported by VMware and the community. We have a vSphere machine module which is much more capable than the esx machinery.

**Comment by mike-veal** [comment]
we are using 5.5.0 at the moment. I've just updated our settings to use the vsphere.conf file, I am now getting a issue with module object has no attribute 'SSLContext'. I know there is the following work around when using Python 2.7.6 (which we are)

> "requests.packages.urllib3.disable_warnings()
>   
> import ssl
>    
> 
>try:
>     _create_unverified_https_context = ssl._create_unverified_context
>except AttributeError:
>     # Legacy Python that doesn't verify HTTPS certificates by default
> pass
> else:

However, were would I put the work around in? Thats got me at the moment...

**Comment by KillerInstinct** [comment]
Can you post the full traceback?

**Comment by mike-veal** [comment]
File "/home/cuckoo/cuckoo/lib/cuckoo/core/scheduler.py", line 517, in initialize machinery.initialize(machinery_name)
File "/home/cuckoo/cuckoo/lib/cuckoo/common/abstracts.py", line 97, in initialize self._initialize_check()
File "/home/cuckoo/cuckoo/modules/machinery/vsphere.py", line 88 in _initialize_check
sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module object has no attribute 'SSLContext'

**Comment by KillerInstinct** [comment]
Ahh -- this is because the updated code that the original author proposed never got merged.
https://github.com/cuckoosandbox/cuckoo/pull/656

Try implementing the commits in that PR.

**Comment by mike-veal** [comment]
Thanks - That's got rid of the SSL error... I'm getting "Couldn't connect to vSphere host", is there away of getting a more helpful error message back? :)! I've tried using --debug but that doesn't give me anything more.

**Comment by mike-veal** [comment]
Sorry - please ignore... it was fat finger issue!

**Comment by KillerInstinct** [comment]
@jbremer Consider re-evaluating that PR since the updated pyvmomi release? seemed to have been needed for older python installs.

**Comment by BlackyFox** [comment]
Just to give some complementary information on this one.
I am setting a cuckoo instance with an ESXi 6 and I didn't encountered this issue once.
If you have the opportunity to upgrade you ESXi, this could solve your issue.

**Comment by mike-veal** [comment]
At the moment I'm stuck with ESXi 5.5. Sadly I still haven't got it working using the VSphere Machinery file.

One thing that I wanted to check.... should the host which is specified in the vsphere.conf be the ESXi host which is running the VM or should it be the IP of the VCentre server.

**Comment by KillerInstinct** [comment]
ESXi host is fine, so long as it has a license that supports the vSphere API (don't need vSphere for that feature, just a license requirement)

**Comment by BlackyFox** [comment]
I agree with @KillerInstinct, you don't need to use the VSphere machinery. With the ESX one it works fine if you have the license.
And actually, I don't think it will cause some HTTP Session Time-out with it. It uses virsh to access to the ESXi's API, so I think you'll be fine with this (if you have correctly configured and installed libvirt).

**Comment by KillerInstinct** [comment]
I mean you can use vSphere machinery with an ESXi host, it doesn't need to interact with vCenter. I believe that libvirt still does not fully support vSphere 6.

**Comment by BlackyFox** [comment]
Oh my bad, I didn't understood that point well.
But about vSphere 6, everything is working great on my hand. I just can't use volatility since libvirt doesn't support the API call _virDomainCoreDump_ for ESXi ([ref libvirt support](https://libvirt.org/hvsupport.html)).

**Comment by mike-veal** [comment]
I've checked the licencing and its all good.... 

When using the esx.conf file, I'm using a VPX over HTTPS.. Which i think is the reason I'm getting HTTPS session timeouts. How are you connecting to the ESX host?

**Comment by BlackyFox** [comment]
This is strange...

On my hand, the configuration looks like this :
```
[esx]
dsn = esx://the.esx.IP.address/?no_verify=1
# no_verify=1 to disable certificate checks
username = YOUR_USERNAME
password = YOUR_PASSWORD

machines = list,of,your,machines

interface = eth2
# the guest only network
...
```
For the IP address, I give the one I use when I connect through the VSphereClient.
Make sure you are giving Cuckoo a user with enough rights.
If you want to check if you are able to connect to the ESXi API, you can use virsh like this:
`virsh -c esx://the.esx.IP.address/?no_verify=1`

**Comment by jbremer** [comment]
Sorry for the really late response, is this issue still a thing? Should #656 be merged?

**Comment by KillerInstinct** [comment]
Do it. :+1:

**Comment by jbremer** [comment]
Closing issue as related PR was merged.
