### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by shiryu92** [cuckoosandbox/cuckoo#817]
I use cuckoo droid with cuckoo 1.2 branch. My system have 50 virtual machines. After run about 1 hours the memory of cuckoo machine is full. Please help me.

**Comment by consen** [comment]
Wow, 50 virtual machines? On one physical host? what's the os? how many cpus and how much memory ? what's your virtual platform, xen, kvm, virtualbox, vmware or other? :)

**Comment by jbremer** [comment]
Any update here? Is this still an issue for you? Does Cuckoo still behave properly even though it seems a lot of memory is allocated etc?

**Comment by jbremer** [comment]
There are plenty of performance improvements to be done in Cuckoo, but this issue is a bit too generic and no additional information has been provided, so closing it ;-)
