### ISSUE TITLE
Invalid binary symlink causes /tasks/report/<id>/all to fail

### ISSUE THREAD

**Issue by knifeyspoony** [cuckoosandbox/cuckoo#818]
When cuckoo.conf specifies delete_bin_copy, scheduler.py will delete the copy upon completion. On *nix this will invalidate the symlink in the analysis directory. When the report for this analysis is requested through the api /tasks/report/id/all, tarfile's add function will raise an OSError when it hits the invalid symlink. 

Two proposed solutions are:
1. In scheduler.py if the delete_bin_copy flag is present, check to see if you're left with an invalid symlink after deleting self.binary, and os.unlink() it if so.
2. Just swallow the OSError raised by tar.add() in the /tasks/report/id api calls.

I would have just issued a pull request, but didn't know which solution (if any) was preferred!

Cheers

**Comment by jbremer** [comment]
We should probably implement both methods. Delete the symlink if the binary copy is removed (through the options) and make sure the file still exists before adding it to the tar.
Would you like to try to implement this or should I?
Thanks for reporting!

**Comment by knifeyspoony** [comment]
I can give it a go. I'll send up a pull request asap. No problem!

**Comment by jbremer** [comment]
Merged the PR, thanks!
