### ISSUE TITLE
Error: Windows7: the guest initialization hit the critical timeout, analysis aborted

### ISSUE THREAD

**Issue by bit111** [cuckoosandbox/cuckoo#823]
Hello,
I installed last Cuckoo version on my physical machine Ubuntu Mate 15.10 and I configured cuckoo following official guide. 
I installed Windows 7 32 bit SP1 on VirtualBox and I configured Windows network in this way:
- IP: 192.168.56.101
- Subnet: 255.255.255.0
- Gateway: 192.168.56.1
- DNS: 192.168.56.1

So, when I try to launch an analysis passing a simple PDF or an exe file (such as IE8 installation), It returns error **Error: Windows7: the guest initialization hit the critical timeout, analysis aborted.**.
No screenshot is taken. No static analysis is available, only network analysis with some results in DNS and in UDP tabs.

**Comment by doomedraven** [comment]
@bit111 do next checks
* run vm and check netstat to see if agent is runned and listening on port 8000
* make curl req to your vm to see if your connection works
    * curl 192.168.56.101:8000

if you get ths then connection ith client works fine, if not check your network setting and if forwarding is enabled
````
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 501.
<p>Message: Unsupported method ('GET').
<p>Error code explanation: 501 = Server does not support this operation.
</body>
```

**Comment by bit111** [comment]
Hi @doomedraven,
I think is an issue due to agent.py.
I put it in startup folder and I made a snapshot without start it.
Is it normal that cuckoo doesn't boot Windows7 but simply restores it?

**Comment by doomedraven** [comment]
@bit111 yes, is normal, because if not you will have infected vm after first malware run, agent must be take  snapshot with run agent and verify conectivity

**Comment by nujozet** [comment]
Hi,
I have the exact same issue. Curl has the good output and agent.py is installed. Everything is good but I still have the timeout issue.

**Comment by alabiana** [comment]
check telnet from windows on your cuckoo machine on port 8000 maybe there is something blocking it

**Comment by samreenk** [comment]
Were you ever able to fix this issue? Running into the same one...

**Comment by mattwatkins93** [comment]
I have the exact same issue... Have checked comms between Cuckoo and guest VM. I see the connections and POSTs to the physical box, but nothing ever happens. Any way to debug this?

**Comment by mattwatkins93** [comment]
This turned out to be a firewalld issue for me (CentOS). Traffic was randomly being dropped. Having reviewed the pcaps to work out why... Check iptables on Ubuntu!

**Comment by jbremer** [comment]
Closing as resolved - this is indeed usually a firewall issue or something similar. In our upcoming release we hope to inform the user slightly better regarding this class of issues.
