### ISSUE TITLE
Analysis crashed cuckoomon

### ISSUE THREAD

**Issue by lpaine** [cuckoosandbox/cuckoo#825]
Got a signature popping on a piece of malware with the message "Crashed cuckoomon during analysis. Report this issue to the github repo"

pid: 2388
message: Exception reported at offset 0xf241 in cuckoomon itself

**Comment by jbremer** [comment]
Well, you're not using upstream Cuckoo, and we don't provide support for forks. Please open an issue at your fork :-)
