### ISSUE TITLE
TemplateDoesNotExist at /

### ISSUE THREAD

**Issue by bit111** [cuckoosandbox/cuckoo#826]
Hi,
I installed last Cuckoo version on my physical machine Ubuntu 15.10 and I configured cuckoo following official guide. When I run _manage.py wunserver_ from _~/cucko/web/_ I have a problem with web gui: **TemplateDoesNotExist at /**. it tries to search **dashboard template** in usr/lib/python2.7/dist-packages/django/contrib/auth/templates/dashboard/index.html (with _File does not exist_ error) instead of to search it in ~/cuckoo/web/templates/dashboard/

**Comment by jedisct1** [comment]
Same here.

**Comment by bit111** [comment]
I solved my issue installing all _requirement.txt_ content in recursive way

**Comment by dmreddy1** [comment]
Could some one help me where to add in settings.py file for cuckoo
