### ISSUE TITLE
An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by hegusung** [cuckoosandbox/cuckoo#830]
Hi,
I was using cuckoo sandbox and I hit the following error message :
Analysis failed: [Errno 10053] An established connection was aborted by the software in your host machine

It seems cuckoo doesn't wait long enough after the VM resumed its snapshot before establishing a connection. (Even with a static IP configuration, it takes some time before Windows sets the interface as up)

How can I resolve this issue ? (add a delay in the configuration ? change the virtual machine settings ?)

**Comment by jbremer** [comment]
Cuckoo simply waits until a connection can be made. Generally speaking that particular error you can ignore, though. Does the analysis itself work properly? Or otherwise, could you share some logs with us?

**Comment by jbremer** [comment]
Closing this for lack of feedback / not a critical issue, thanks!

**Comment by MatthewNunes** [comment]
@jbremer I experience this error A LOT, I was wondering, how come you can ignore this error? As it seems quite serious
