### ISSUE TITLE
Issues running Cuckoo Web Interface

### ISSUE THREAD

**Issue by adimenia** [cuckoosandbox/cuckoo#833]
just finishes installing cuckoo, and having issues starting the web interface.
here is the error message.

sudo /opt/cuckoo/web/manage.py  runserver
Traceback (most recent call last):
  File "/opt/cuckoo/web/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/cuckoo/web/web/settings.py", line 16, in <module>
    from lib.cuckoo.common.config import Config
ImportError: No module named lib.cuckoo.common.config

**Comment by KillerInstinct** [comment]
Make sure your cwd is where manage.py is. Also you don't need to sudo. If you want to bind to port 80, use something like apache/nginx with a wsgi module to bind to a low port.

try:
`
cd /opt/cuckoo/web/ && python manage.py runserver 0.0.0.0 8080
`

**Comment by adimenia** [comment]
Yeah that looks to solve the issue, but any ideas why all the CSS are not loaded?

**Comment by adimenia** [comment]
here are some of the errors
![static 404 error](https://cloud.githubusercontent.com/assets/5006200/14231940/9123ab98-f99e-11e5-85d9-e07699c8001e.jpg)
![dir listing](https://cloud.githubusercontent.com/assets/5006200/14231941/9124511a-f99e-11e5-8aca-d7de4979f5a5.jpg)

**Comment by adimenia** [comment]
Solved the CSS issues. but now have another issue. it seems that every time i submit a sample i get this Error.
![permission issue](https://cloud.githubusercontent.com/assets/5006200/14232415/e67ce612-f9b3-11e5-8791-71434be7f404.jpg)

and then the task just hangs there and never finishes.
here is the permissions on the /temp/cuckoo-tmp/ directory.
![folder permissions](https://cloud.githubusercontent.com/assets/5006200/14232424/24fd5872-f9b4-11e5-9e93-71195e6e8274.jpg)

**Comment by jbremer** [comment]
Please make the permissions for the `/tmp/cuckoo-tmp` directory a bit more loose, e.g., `chmod a+rw /tmp/cuckoo-tmp` (or is this *too* loose? :-P).
Or did you already fix this issue in the meantime?

**Comment by adimenia** [comment]
the /tmp/cuckoo-tmp dir permissions are 777 the thing is that cuckoo generate an upload_random folder with those default (rwx) for each sample.

**Comment by jekil** [comment]
I am going to close this issue because it is related to a user misconfiguration. Feel free to reopen it or comment further if needed.
