### ISSUE TITLE
VirusTotal shows "Search for analysis" instead of virus rating

### ISSUE THREAD

**Issue by bit111** [cuckoosandbox/cuckoo#834]
Hi,
I installed Cuckoo 2.0-RC version and I obtained a key after being a user of Virus Total.
When I run a malware analysis the field _Virus Total_ in _Dropped File_ only shows a link to "Search for analysis" instead of to show rating generated from others antivirus.
Is it normal?
Another question: why _Virus Total_ is not showed in _Quick Overview_ tab?
Thanks

**Comment by jbremer** [comment]
If you have 100 dropped files this would translate in 100 virustotal queries (or, well, for just the score you might get less queries). Something that takes up quite some resources from your premium virustotal api key and as such not feasible for free users of virustotal ;-)
For those reasons I don't think it really makes sense to implement this, so I'm closing this issue. Please reopen if anyone feels differently about it.
