### ISSUE TITLE
When starting Cuckoo reschuedling of brocken tasks does not work anymore

### ISSUE THREAD

**Issue by ChriDr** [cuckoosandbox/cuckoo#836]
Hi everyone, 

recently I run into an issue where broken tasks seems not to rescheduled by the startup process of cuckoo. All necessary settings are enabled.

Once Cuckoo is started again, it says that a specific tasks has been rescheduled. My understanding is that when a brocken task is rescheduled, the broken task get "recovered" as status and a new task is added to the database. 

In my case the second step does not happen, so the new task will not added to the database and cuckoo does not process the broken task again. 

I tried it also with a new system and a new cuckoo installation, but the tasks will also not rescheduled by cuckoo. My guess is that something went wrong with def add() function in the database class file. I haven't found the error yet, so I am reporting the 
![2016-04-02 11-50-07](https://cloud.githubusercontent.com/assets/6873184/14225605/199b040c-f8c9-11e5-8948-be87236fb5ac.png)
issue now.

Best regards,

**Comment by ChriDr** [comment]
Is this a general issue or have someone run into the same issue since I have reported it? Please let me know :)

**Comment by jbremer** [comment]
Thanks @ChriDr for reporting, this was related to a change on our side with the `options` field of a task. It should now behave properly again (if you're running the latest development version).
Closing this as fixed, but feel free to re-open or create a new issue if other issues arise.
