### ISSUE TITLE
AttributeError: Config instance has no attribute 'routing'

### ISSUE THREAD

**Issue by xulifan** [cuckoosandbox/cuckoo#837]
Hi, when I start cuckoo, I got this error, does anyone have any clue? Here is the error:

                               ),-.     /
  Cuckoo Sandbox              <(a  `---','
     no chance for malwares!  ( `-, ._> )
                               ) _>.___/
                                   _/

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0-dev
OS version: posix
OS release: Ubuntu 14.04 trusty
Python version: 2.7.6
Machine arch: x86_64
Git version: 4bdf14da41b34e75ebb3c945e00813eccdf58cad

Traceback (most recent call last):
  File "cuckoo.py", line 120, in <module>
    test=args.test)
  File "cuckoo.py", line 72, in cuckoo_init
    init_rooter()
  File "/home/ubuntu/github/cuckoo_latest/cuckoo/lib/cuckoo/core/startup.py", line 323, in init_rooter
    if not Config("vpn").vpn.enabled and cuckoo.routing.route == "none":
AttributeError: Config instance has no attribute 'routing'

**Comment by jbremer** [comment]
Did you update your Cuckoo instance without taking into account the new configuration options?

**Comment by xulifan** [comment]
I am not sure what do you mean by the "new configuration options".
But here is what my physical.conf looks like:

[physical]
machines = i-6b068aa8,i-600589a3,i-de068a1d,i-df068a1c,i-68068aab,i-69068aaa,i-cf078b0c,i-c0078b03,i-c1078b02,i-c6078b05
user = Administrator
password = password
[i-6b068aa8]
label = i-6b068aa8
platform = windows
ip = 172.31.16.125
[i-600589a3]
label = i-600589a3
platform = windows
ip = 172.31.29.166
[i-de068a1d]
label = i-de068a1d
platform = windows
ip = 172.31.21.131
[i-df068a1c]
label = i-df068a1c
platform = windows
ip = 172.31.21.42
[i-68068aab]
label = i-68068aab
platform = windows
ip = 172.31.16.240
[i-69068aaa]
label = i-69068aaa
platform = windows
ip = 172.31.24.96
[i-cf078b0c]
label = i-cf078b0c
platform = windows
ip = 172.31.22.16
[i-c0078b03]
label = i-c0078b03
platform = windows
ip = 172.31.30.229
[i-c1078b02]
label = i-c1078b02
platform = windows
ip = 172.31.26.228
[i-c6078b05]
label = i-c6078b05
platform = windows
ip = 172.31.20.13

**Comment by jbremer** [comment]
Ah, I see what's going wrong. Will fix it later - thanks!

**Comment by xulifan** [comment]
Hi, have you fixed the problem? Thanks.

**Comment by jbremer** [comment]
Well, basically you're missing this part of the configuration; https://github.com/cuckoosandbox/cuckoo/blob/master/conf/cuckoo.conf#L68-L103. I think I wasn't really clear - the only fix I can add is by improving the error message :)

**Comment by xulifan** [comment]
Thanks.
