### ISSUE TITLE
Cukoo volatility runtime error

### ISSUE THREAD

**Issue by avinashx11** [cuckoosandbox/cuckoo#840]
Hi,
I infer "Generic error executing volatility",please help me on this.
Thanks in advance.
![screenshot from 2016-02-29 15_18_02](https://cloud.githubusercontent.com/assets/18083850/14254093/dfaa1ec4-faab-11e5-9bf1-8043ab9e000e.png)

**Comment by doomedraven** [comment]
@avinashx11 can you provide version of volatility and yara?

**Comment by jbremer** [comment]
It looks like you're using an outdated version of Volatility. Please upgrade :-)
