### ISSUE TITLE
Permission denied Error when submitting file for analysis

### ISSUE THREAD

**Issue by adimenia** [cuckoosandbox/cuckoo#842]
Hello

when submitting a file for analysis via the web UI im getting the following Permission denied Error
![permission issue](https://cloud.githubusercontent.com/assets/5006200/14275112/0d4bc3d8-fb1e-11e5-875b-5122f40c1853.jpg)

i tried to be aggressive and gave 777 permissions on all the folders under the cuckoo-temp dir
but still get the same error on every new folder created by a new submission

**Comment by adimenia** [comment]
help anyone?

**Comment by jbremer** [comment]
Do you also have read access on the folders themselves (i.e., `/tmp/cuckoo-tmp` etc)?

**Comment by adimenia** [comment]
Yes i do
![pern](https://cloud.githubusercontent.com/assets/5006200/14419663/031a5012-ffd0-11e5-8522-fbebbdc7b194.jpg)

**Comment by jbremer** [comment]
Did you resolve this issue already? Going to close this as issue unrelated to Cuckoo - just make sure the users involved have access to the same group etc.

**Comment by adimenia** [comment]
Solved thanks

**Comment by BuckyGoat** [comment]
I ran into this same issue recently.  For those of you who may be searching Google and have come across this, my issue was that I was running the webserver using sudo.

You should run the webserver as your normal cuckoo user, "python manage.py runserver" not "sudo python manage.py runserver".

**Comment by obsidianpentesting** [comment]
If you do run the webserver using sudo, make sure you also change the /tmp/cuckoo-tmp ownership and permissions back to normal....otherwise, the contents of that directory will be changed to root as the user and group. And you won't be able to upload new analysis files via the webserver.
