### ISSUE TITLE
Cuckoo web interface error : Templatedoesnotexist exception

### ISSUE THREAD

**Issue by rodneyjeromesamuel** [cuckoosandbox/cuckoo#843]
When I run the command ./manage.py runserver, The server runs fine.
When I type 127.0.0.1:8000
I get a Templatedoesnotexist exception
![error](https://cloud.githubusercontent.com/assets/17762387/14279190/7428a532-fb49-11e5-85b0-02aa965af1b5.png)

**Comment by ppeli** [comment]
You probably did not run the interpreter from the web/ folder.

**Comment by jbremer** [comment]
The `Python path` from the screenshot seems fine. Could you upgrade to Django version 1.8+?

**Comment by rodneyjeromesamuel** [comment]
I solved it.
The problem was there was no TEMPLATE DIRS in the settings.py folder. Once that was assigned it started working fine. Thank you all for your suggestion. @jbremer it's an honor. All the best for the great work u guys are carrying on

**Comment by jbremer** [comment]
See also 4d4a68b1645ff5c234eb400501fbd0bcc2cb0215. I suppose we could abort early if an older version of Django has been detected.

**Comment by rodneyjeromesamuel** [comment]
I have faced that issue too. Aborting would be a good idea if an older version of django is identified.
