### ISSUE TITLE
Cuckoo injection causing error in date

### ISSUE THREAD

**Issue by BlackyFox** [cuckoosandbox/cuckoo#844]
While using Cuckoo in the beginning of the month, I realized something strange happening: the guests date was going from April 1st to January 4th when cuckoo start injecting in the guest.
I later discovered that this error was due to some date format.
My guests are in french thus the date format is DD/MM/YYYY. 
When I changed the format to MM/DD/YYYY, everything went back to normal.

**Comment by jbremer** [comment]
Could you verify the following commit b626d86c98425d384568e403c7ee13c3d8b7b493 (in the latest development version), @BlackyFox? :-)

**Comment by spender-sandbox** [comment]
You're also going to need to make a similar fix as https://github.com/spender-sandbox/cuckoo-modified/commit/2b5a6cb34215c773e0d972cc0541f6e60d36ac50 unless you want to add another database migration script

**Comment by BlackyFox** [comment]
@jbremer I will try out this version asap, but by looking at the code, this seems to be a great fix!
Thanks! :)

**Comment by jbremer** [comment]
Seems to have been working fine for me - closing the issue.
