### ISSUE TITLE
501 Unsupported Method ('GET')

### ISSUE THREAD

**Issue by Sirskinny** [cuckoosandbox/cuckoo#846]
I'm new to cuckoo and I was wondering if someone could help me out. I am getting a 501 error when submiting a sample, and I'm not entirely sure why. I'm running windows 7 guest and cuckoo 2.0

Thanks
-Alex

**Comment by jbremer** [comment]
Do you have some screenshots or logs?

**Comment by JSkier21** [comment]
Also posted to community, but here is a screen shot for you here as well. 
![screenshot at 2016-04-22 15 47 52](https://cloud.githubusercontent.com/assets/3190223/14754645/4a402c2a-08a2-11e6-8d80-684af71caad1.png)

**Comment by jbremer** [comment]
Thanks for the screenshot. This is not actually a bug - the Analyzer is just trying to determine which version of the Agent you're running (this being the old one - which is still supported, though).
I'll try to see if I can document this and other things in the documentation from now on.

**Comment by JSkier21** [comment]
Thanks, that makes sense. I saw this in another reply too, I thought the error was causing the submitted sample not to run (either through web or cli), but that appears to be unrelated, another issue.

**Comment by jbagel2** [comment]
So I pulled from the current master branch and the agent gives this exact same response. Am I missing something. Or is there a different location to get the agent.py, besides the agent folder in the current master?

**Comment by jbremer** [comment]
@jbagel2 Please see the documentation in the FAQ in the following commit 1ece01b627e7c57034d684f08794b0d0d7818992. Closing this issue as resolved - thanks!
