### ISSUE TITLE
tcpdump issue + network traffic shown only on json report ! 

### ISSUE THREAD

**Issue by Nadacsc** [cuckoosandbox/cuckoo#847]
I am using the latest cuckoo sandbox and install and change the permission of tcpdump as recommended: /usr/sbin/tcpdump = cap_net_admin,cap_net_raw+eip
and I've even used at the end : 
$ sudo chmod +s /usr/sbin/tcpdump
but it still gives me permission denied ! and no network analysis is displayed on the html report ( although I can see all the connected hosts + IP on the Json report .. no idea why ! ) 

I've doubled check all the configuration but everything seems fine and I can even see the traffic when running tcpdump by my self during the analysis using : tcpdump -i vboxnet0

any idea ?

**Comment by jbremer** [comment]
Do you have any logs for us? Are your `dump.pcap` empty?

**Comment by Nadacsc** [comment]
Many thanks for your reply 

> Are your dump.pcap files empty?
no it hasn't been created because the permission denied although I've used:  /usr/sbin/tcpdump = cap_net_admin,cap_net_raw+eip .. and I check it and it has been set up correctly 

> Do you have any logs for us
I've uploaded a log.zip file containing the analysis logs and reports of three different samples (If you want it in another file format "other than .zip" please let me know)

Things that are weird in the analysis files: 
- I got always these warnings and errors:
[analyzer] WARNING: File at path "u'\\device\\namedpipe\\lsass'" does not exist, skip.
[lib.common.results] ERROR: Exception uploading file c:\documents and settings\me only\local settings\temp\[filename].exe to host: timed out

- In one of the logs I got : [analyzer] INFO: Error dumping file from path "c:\documents and settings\me only\local settings\temp\nsl25d.tmp": [Errno 13] Permission denied: u'c:\\documents and settings\\me only\\local settings\\temp\\nsl25d.tmp'
Although I have only one user on my windows XP which is the administrator and there is no UAL in WindowsXP as far as I know. 

- It always says "Nothing to display." in the network analysis section in all my html reports
About my Guest setup: I am using WinXP SP3 32bit with the following settings: 
IP: 192.168.56.101
Subnet mask: 255.255.255.0
Default gateway: 192.168.56.1
DNS server: 8.8.8.8

Host: Ubuntu 14.04
and the settings of the vboxnet0 are:
IP: 192.168.56.1
Subnet mask: 255.255.255.0
and I've doubled checked all the conf files.
and the guest can connect to the internet through the 'host only' and forwarding settings and I can retrieve the reports etc so I don't think there is a problem with my connection between the guest and the host. 
However, I cannot access 'some' websites from the guest and when running network diagnostics tool on windows it says : couldn't make HTTPs and FTP connections ! is this normal in this case ? I have the firewall and everything disabled and even with a fresh installation of windows .. is this because of the host only and forwarding ?

Many thanks in advance, and if you want more details just let me now 
[logs.zip](https://github.com/cuckoosandbox/cuckoo/files/210015/logs.zip)

**Comment by jbremer** [comment]
Sorry for the late reply, but a couple of things here:
* If `tcpdump` failed, something is still wrong in your setup. Although if it works in a separate shell, I'm not sure what. If you're for some reason dumping the `.pcap` file to a dot-directory (e.g., `~/.hello/1.pcap`) then you can get Ubuntu AppArmor to complain.
* The HTML reports are deprecated, please take a look at the Web Interface until we release our new and upcoming HTML reports which are up-to-date with the latest information available.

Going to close this issue as I guess it's not relevant anymore. Please reopen if it is.
