### ISSUE TITLE
dll imported vs dll loaded 

### ISSUE THREAD

**Issue by Nadacsc** [cuckoosandbox/cuckoo#848]
what is the difference between the loaded DLL ( in the behaviour analysis section ) and the imported DLL ( in the static analysis section ) .. shouldn't these be the same ? ( I mean the loaded DLL during the run should be imported first ) ... I've uploaded a report which contain both. [report.txt](https://github.com/cuckoosandbox/cuckoo/files/206670/report.txt)

also

**Comment by jbremer** [comment]
In the static view you see static imports. Dynamic imports (those done at runtime) are through a function called `LoadLibrary`. Samples sometimes load DLLs dynamically so to obfuscate which DLLs they're actually using etc.

**Comment by jbremer** [comment]
Does this answer your question? Should I close this issue?

**Comment by Nadacsc** [comment]
I see, thanks .. yes it answers my question

**Comment by jbremer** [comment]
Ok :)
