### ISSUE TITLE
MongoDB Reporting: InvalidStringData

### ISSUE THREAD

**Issue by tt1379** [cuckoosandbox/cuckoo#856]
Hi

I'm running Cuckoo 2.0-rc1 for URL analysis; I seem to be running into an encoding error with the MongoDB reporting. 

```
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/zelos/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/home/zelos/cuckoo/utils/../modules/reporting/mongodb.py", line 224, in run
    self.db.analysis.save(report)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 266, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
InvalidStringData: strings in documents must be valid UTF-8: '<\xc0\xcb\x93\x93\xae\x149\xa7"\xd9\xefV\xd2=~`\xe5\xad\xf7\xf7\xf7x\xbd\xd9\x982\x8co\xdd}\t.5\xe7\x11\x8ab2\x9b\xa3\x1ac\xba\xbd\x89k\x0f*$\xda\xa8\x87\x83\x88\x89\xbe\xf2\x96\xab\xe7\xc7w\xc3\x1b\xf7\x0f!\xe7\xd4K\xf4\xa1d\x8eu\xd2\xde\x19H\xa2\xf63\x7f\xd9\x0c<\x1aT\xbd\x93]\xe3\x11\x81CC\xf8\xd8>\xb57\xba\x90\x89\xdb[V\xc4g\xea\xc2}V\x8c\xf8\xd6=4\x1e\xa1#\xfd\xa1\x9d\xc3\r;^\x90\xed`F\xb2f\xa5!|\x1e\xbd\xb2\xe8<\x07\x9a\x17\xf4.\x1e\xbb\x0c3\xd95+\xb2\xd5\x18:\x15\x1b\xeb4\x1b\x89\x98c.i(6s \x04\xab\x9c\xd7\xc0\xc2G\x99\x80p\xd4y%\xf2:\x95x?\x9c+\x0f\x87P{\xf2\x9d\x87WN/\x96\xfb\xfb\xdf\xfb\xbb\x8cl\x0bq\xd0\xfb\xe3\x80\x11s\xe7a\x80\xc04\xc3K\xd5\x1d\xdc[-\xd1)i\xce\xa2\x98\xc2b\x1c\xad\xcd\x87\x93\xd3\x81\xdd\xdfI\xd68\x1e\xd0\x86\xec\xdd\x8e\xee\xefkb\xc8\xa7I\xb0\xd6\xcf\xfe\xd3\xb9v\xdc\x04\xdb\xfe\x99\x16\x98E\xdb\x7f{\xd0\xd4P,\xf1z\xbc\x0c\xd6\xfd\xf7h\xbc-\x05\r\xba\xede\xa4\xddz\xe7\xd7\xbf\x98\xfdxw\xb0\xaei2pi\xa0-\x87\x1c\xc1\xf0\xff9d\xae~I\x1d\x00\x00'
```

I'm running `process.py` as a separate process. Is anyone else experiencing this issue? 

Thanks

**Comment by KillerInstinct** [comment]
Looks like you got some key which has binary data and isn't either UTF encoded or properly escaped, Try spitting out a report.json and seeing what dict that key is a part of.

**Comment by jbremer** [comment]
@tt1379 Could you please share the `report.json` file for this analysis?
I have a good idea where this is going wrong, but the JSON report would help.
Thanks!

**Comment by jbremer** [comment]
Could also very likely be that this has already been resolved in the latest development version of Cuckoo, btw.

**Comment by zam89** [comment]
Hi guys,
I also encountered similar problem like @tt1379 :

```
2016-06-18 14:21:50,153 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/malwr/Desktop/cuckoo/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/home/malwr/Desktop/cuckoo/modules/reporting/mongodb.py", line 252, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
InvalidStringData: strings in documents must be valid UTF-8: '\xc4d\x05\xa5\xe1J\xd2u}W)8'
```
I'm currently running Cuckoo version 2.0-dev.
I've uploaded my cuckoo.log and report.json : [cuckoo.zip](https://github.com/cuckoosandbox/cuckoo/files/321617/cuckoo.zip)
The sample that I was trying is : https://malwr.com/analysis/Y2VlZjZlYTYxNzdjNDBiYjgxYzBkMjM5MjU5MDhjZDU/

**Comment by jbremer** [comment]
Thanks @zam89. It would appear that the entry in the `pdb path` contains unreadable unicode content - let me sanitize it.

**Comment by jbremer** [comment]
Please find the commit above @zam89, that should do the trick. Going to close this issue as resolved as both reported issues should be fine now. Please re-open or create a new issue if you run into any other problems :)

**Comment by mohammadrad** [comment]
I have this issue with the last pull. 

INFO:cuckoo.process:Task #94: queueing for reporting
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/u2/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/home/u2/cuckoo/utils/../modules/reporting/mongodb.py", line 253, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1903, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 430, in _insert
    gen(), check_keys, self.codec_options, sock_info)
InvalidStringData: strings in documents must be valid UTF-8: "GET http://7-zip.org/a/7z1604.exe%7C7.exeO%06'S\xc5\x98\x81W\x8dN\xd2\xcb%0C\x87\x8fiI\xe9\xd2\x85\x9c\xce3%7D\x8f%60\xfc"
