### ISSUE TITLE
Cannot create directory for analysis #65537

### ISSUE THREAD

**Issue by wbenny** [cuckoosandbox/cuckoo#861]
Currently, if Cuckoo stores the analysis results on the ext4 filesystem, and analysis #65537 is about to be created, it will fail, because of the ext4 subfolder limit count. You can workaround this by setting dir_nlink flag, but... I think it would be kinda better to not bend file system because of the Cuckoo :)

Do you think changing the subdirectory hierarchy is considerable for you?

**Comment by jbremer** [comment]
Are you 100% about that? Reading the following articles it'd appear there is an unlimited amount of subdirectories that can be created. https://en.wikipedia.org/wiki/Ext4#Features http://kernelnewbies.org/Ext4

I also just verified that I can have more than 64k directories by running the following command; `for i in {1..99999}; do mkdir $i; done; ls|wc -l`

**Comment by wbenny** [comment]
Hmm, you are right. On my system i can create > 64k subfolders too.

Actually, my storage folder is a mount of a NFS which I currently do not have physical access to, and I was really convinced it has ext4 as the underlying FS.

You can close this issue then, sorry for bothering. :)

**Comment by jbremer** [comment]
Ok, thanks:)
