### ISSUE TITLE
A server error occurred.  Please contact the administrator.

### ISSUE THREAD

**Issue by alabiana** [cuckoosandbox/cuckoo#864]
Hey folks,

i got this error when entering the /analysis/ site. There seams to be an non-utf-8 char in the string.
console says this:

> DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 105: invalid continuation byte. You passed in "[<Task('46','/tmp/cuckoo-tmp/upload_b0YmQa/Stamping.doc')>,\n <Task('45','/tmp/cuckoo-tmp/upload_82JGbw/Fu\xdfmatte LOTTO 857001.docm')>,\n <Task('43','/tmp/cuckoo-tmp/upload_AqUhCz/Rechnung 4214-987839.rtf')>,\n <Task('42','/home/user/cuckoo/storage/analyses/41/files/b3d510ef04275ca8_excludedictionaryge0407.lex')>,\n <Task('41','/tmp/cuckoo-tmp/upload_z1IcTY/Test.docx')>,\n <Task('33','/tmp/cuckoo-tmp/upload_JaRmJo/G-A0288010040780590521.docm')>,\n <Task('29','/tmp/cuckoo-tmp/upload_yGNdDI/12virus.doc')>,\n <Task('28','/tmp/cuckoo-tmp/upload_qqS_rL/78a0540a36db59d26d1074e87b6458fb21d109685875326418715843b799ce49.js')>,\n <Task('19','/tmp/cuckoo-tmp/upload_qqS_rL/78a0540a36db59d26d1074e87b6458fb21d109685875326418715843b799ce49.js')>,\n <Task('18','/tmp/cuckoo-tmp/upload_qqS_rL/78a0540a36db59d26d1074e87b6458fb21d109685875326418715843b799ce49.js')>,\n <Task('16','/tmp/cuckoo-tmp/upload_caMrIa/28184a31e45c90db6b206b880825de8aceb9a5ab8f9c64fbd10f464b9e6a9669_Makro.docx')>,\n <Task('15','/tmp/cuckoo-tmp/upload_caMrIa/28184a31e45c90db6b206b880825de8aceb9a5ab8f9c64fbd10f464b9e6a9669_Makro.docx')>,\n <Task('14','/tmp/cuckoo-tmp/upload_Mp0Ep6/28184a31e45c90db6b206b880825de8aceb9a5ab8f9c64fbd10f464b9e6a9669_Makro.docx')>,\n <Task('13','/tmp/cuckoo-tmp/upload_MNlvNm/Makro.docx')>,\n <Task('12','/tmp/cuckoo-tmp/upload_tXDgL5/700-3125332-2215572.js')>,\n <Task('11','/tmp/cuckoo-tmp/upload_9T3pwT/12virus.doc')>,\n <Task('10','/tmp/cuckoo-tmp/upload_9T3pwT/12virus.doc')>,\n <Task('9','/tmp/cuckoo-tmp/upload_PHmbbw/jre-8u77-windows-x64.exe')>,\n <Task('8','/tmp/cuckoo-tmp/upload_9_h_nG/rufus-2.7.exe')>,\n <Task('7','/tmp/cuckoo-tmp/upload_0LtuxI/1f294373c82b27f9f0286a6376110f7a3790d8076e9f33a8276eb84c3658b121.zip')>,\n <Task('6','/tmp/cuckoo-tmp/upload_0LtuxI/1f294373c82b27f9f0286a6376110f7a3790d8076e9f33a8276eb84c3658b121.zip')>,\n <Task('5','/tmp/cuckoo-tmp/upload_If3TMY/sha.txt')>,\n <Task('4','/tmp/cuckoo-tmp/upload_EIOM3f/eicar.com')>,\n <Task('3','/tmp/cuckoo-tmp/upload_D4es4B/78a0540a36db59d26d1074e87b6458fb21d109685875326418715843b799ce49.js')>,\n <Task('2','/tmp/cuckoo-tmp/upload_QhKgZF/12virus.doc')>]" (<type 'str'>)

Is there a way to fix this without cleaning the cuckoo data?

**Comment by jbremer** [comment]
Interesting. Do you happen to know whether this could be an issue because of some unicode filenames? Could you share some more information / screenshots perhaps?

**Comment by h3x2b** [comment]
python indeed has got some issues with default encoding, which will probably cause some issues with non-ascii filenames.

try 
export PYTHONIOENCODING=utf8

more details explained in https://github.com/cuckoosandbox/cuckoo/issues/1134

**Comment by alabiana** [comment]
sry forgot to look for this issue... I cleaned the data to continue my work.
