### ISSUE TITLE
What are Cuckoo's limitations?

### ISSUE THREAD

**Issue by bit111** [cuckoosandbox/cuckoo#866]
Hi,
I am doing a study about the features offered by Cuckoo in detail but I would also report what are actually the limits of Cuckoo.
Eg.: what could be one or more missing features?
Could you give me some idea?
Thanks

**Comment by jbremer** [comment]
I'm confident that if you play around with Cuckoo for a week or so that you'll be able to answer this question yourself ;-) Please let us know if you have any more specific questions.

**Comment by bit111** [comment]
before asking my question, I spent a month in configuration and utilisation of Cuckoo. Otherwise I would not have asked here

**Comment by jbremer** [comment]
Oke, sorry to take the assumption that had not been the case then. What are your findings so far? :-)

**Comment by bit111** [comment]
I refer to Cuckoo features. What could be some interesting features to be implemented in the future?
My study will be focused on technical aspects of implementation.
Finally, I think it can be useful for Cuckoo members.
Why not organize a poll?

**Comment by jbremer** [comment]
Given there have been zero comments on this issue I'm going to assume people are not really interested in such a poll. If you'd like to set one up let us know, we'd be able to help spreading the word a little bit maybe.
Other than that, closing this issue.
