### ISSUE TITLE
assert task.id not in pending_results

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#869]
today I started to see this bug first time, it crash process.py so all rest processes stop be processed + once you start it return to process everything and crash for new, looper...

````
  File "process.py", line 128, in autoprocess
    assert task.id not in pending_results
AssertionError
Traceback (most recent call last):
  File "process.py", line 203, in <module>
    main()
  File "process.py", line 185, in main
    autoprocess(parallel=args.parallel)
  File "process.py", line 154, in autoprocess
    pool.join()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 469, in join
    assert self._state in (CLOSE, TERMINATE)
AssertionError
```

**Comment by jbremer** [comment]
Yeah, `process.py` is fairly broken. Given you're using a PostgreSQL-based backend anyway I'd suggest to start using `process2.py`.
As part of #863 I've fixed the whole `process.py`/`process2.py` mess and combined them into one `Cuckoo App` that actually works. Hopefully soon will be the time that people switch to that - after it is merged officially anyway ;-)

**Comment by doomedraven** [comment]
i hope that merge will be soon, i will test with process2, thanks

**Comment by jbremer** [comment]
@doomedraven Feel free to beta-test btw, all feedback is welcome!

**Comment by doomedraven** [comment]
i will for sure, once will finish with distributed :)

**Comment by doomedraven** [comment]
ok after so much time i return to experience this bug, process.py would be backward compartible with current dev branch? to just copy it and use right now? as i can't put in production the package version for few reasons

**Comment by jbremer** [comment]
In master you should probably use `process2.py`. Please feel free to let me know (even privately) which bugs prevent you from using package (and yes, we're aware of a couple of such issues, they're currently on our roadmap).

**Comment by doomedraven** [comment]
in that server with v2 right now i have mysql
```
python process2.py auto
Due to SQL limitations utils/process2.py currently only supports PostgreSQL.
```

is the screenshot bug resolved? i mean they can be visible from webgui?

**Comment by jbremer** [comment]
Oh, right, well then you might have to switch to `PostgreSQL` as `process.py` is freezes at random.

**Comment by jbremer** [comment]
Screenshots should work in both versions, do you mean in master or package?

**Comment by doomedraven** [comment]
In package, i will try today for new
