### ISSUE TITLE
ntOpenMutant issue

### ISSUE THREAD

**Issue by frisk7** [cuckoosandbox/cuckoo#875]
I have been using an array of version 1.1 sandboxes for (malware) analysis of W32 PE executables.   I extract information from the Json output, convert it to a different format and apply heuristic detection and classification rules to that format.

I am now testing 2.0-rc1.  As the Json output  format is slightly different, I had to make a few changes to my converter, but they are not relevant.  What is relevant is that there are a few bits and pieces of information which are completely missing from the 2.0-rc1 output, but were present in 1.1.

**NtOpenMutant**  is the "biggie" for me.

In 1.1, output for calls to NtOpenMutant would look something like this:
                    {
                        "category": "synchronization", 
                        "status": false, 
                        "return": "0xc0000034", 
                        "timestamp": "2015-04-10 13:37:25,746", 
                        "thread_id": "2528", 
                        "repeated": 0, 
                        "api": "NtOpenMutant", 
                        "arguments": [
                            {
                                "name": "Handle", 
                                "value": "0x00000001"
                            }, 
                            {
                                "name": "MutexName", 
                                "value": "Local\\MU_ACBPIDS09_S-1-5-5-0-56046"
                            }
                        ]
                    }, 

With 2.0-rc1 I cannot find any output for NtOpenMutant at all.  None - it is as if it does not exist at all even though I run the same files through 1.1 and 2.0-rc1.

By comparison, NtCreateMutant is absolutely fine  In 1.1 I get something like
                    {
                        "category": "synchronization", 
                        "status": true, 
                        "return": "0x00000000", 
                        "timestamp": "2015-04-16 07:09:52,769", 
                        "thread_id": "4016", 
                        "repeated": 0, 
                        "api": "NtCreateMutant", 
                        "arguments": [
                            {
                                "name": "Handle", 
                                "value": "0x00000128"
                            }, 
                            {
                                "name": "InitialOwner", 
                                "value": "1"
                            }, 
                            {
                                "name": "MutexName", 
                                "value": "fdsfsdfsdf"
                            }
                        ]
                    }, 

while in 2.0-rc1 I get something like

                    {
                        "category": "synchronisation", 
                        "status": 0, 
                        "stacktrace": [], 
                        "last_error": 87, 
                        "nt_status": -1073741515, 
                        "api": "NtCreateMutant", 
                        "return_value": 0, 
                        "arguments": {
                            "initial_owner": 1, 
                            "desired_access": "0x001f0001", 
                            "mutant_name": "fdsfsdfsdf", 
                            "mutant_handle": "0x00000114"
                        }, 
                        "time": 1461004569.75, 
                        "tid": 2932, 
                        "flags": {
                            "desired_access": "STANDARD_RIGHTS_ALL|STANDARD_RIGHTS_REQUIRED|DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE"
                        }
                    }, 

Different format, as I said, but the data is there...and every other API that I have looked at is absolutely fine - it's just NtOpenMutant that seems missing.

**Comment by jbremer** [comment]
You're correct, `NtOpenMutant` was missing from the new monitor. I've added it just now, see also https://github.com/cuckoosandbox/monitor/commit/093efa9199892de0052169cd915c86300b517dbc.
Could you test with http://cuckoo.sh/c83b06896e457eb1/monitor-x64.dll and http://cuckoo.sh/9d39d56f4cdafdda/monitor-x86.dll before I publish said DLLs? :)

**Comment by frisk7** [comment]
Will check, but I will not have the results until after the weekend.

**Comment by frisk7** [comment]
OK, I checked, and there is some brand-new problem.   we just replaced those two files, and now every analysis aborts with "The analysis hit the critical timeout, terminating”" and I get no real report file.   I am not sure what is going on - do those two files maybe depend on some other file being upgraded - I am just using vanilla 2.0-rc1.

**Comment by jbremer** [comment]
Well, that shouldn't happen for sure. Let me check it out.

**Comment by jbremer** [comment]
I just tested the DLLs that I shared with you against the `2.0-rc1` release and got results without any issues. Could you please try again? :-)

**Comment by frisk7** [comment]
Fresh install and re-copying the files solved the problem - whatever it was.   And yes, NtOpenMutant is now handled properly.  Thank you for fixing this.

**Comment by jbremer** [comment]
Thanks again!
