### ISSUE TITLE
Fake "regkey" field

### ISSUE THREAD

**Issue by frisk7** [cuckoosandbox/cuckoo#876]
When I looked at 2.0-rc1 json output files for W32 PE executables, I noticed one thing I really appreciated - the addition of a "fake" regkey field in the output.

One example:
                    {
                        "category": "registry", 
                        "status": 0, 
                        "stacktrace": [], 
                        "last_error": 998, 
                        "nt_status": -2147483622, 
                        "api": "RegEnumValueA", 
                        "return_value": 259, 
                        "arguments": {
                            "index": 0, 
                            "key_handle": "0x80000001", 
                            "value": "", 
                            "regkey_r": "AppEvents", 
                            "reg_type": 0, 
                          **  "regkey": "HKEY_CURRENT_USER\\AppEvents"**
                        }, 
                        "time": 1461057436.375, 
                        "tid": 2592, 
                        "flags": {
                            "reg_type": "REG_NONE"
                        }
                    }, 

"HKEY_CURRENT_USER\\AppEvents" is not passed as a string parameter - in 1.1 I would just get the handle value and had to keep track myself of which registry entry it actually referred to.

Fine - really nice feature...much appreciated.   However, it is incomplete.   The "regkey" field is missing for two APIs, and it would be REALLY nice if it could be added there.

Those are RegQueryInfoKeyW and RegQueryInfoKeyA.   The json output currently looks like this:

                   {
                        "category": "registry", 
                        "status": 1, 
                        "stacktrace": [], 
                        "api": "RegQueryInfoKeyA", 
                        "return_value": 0, 
                        "arguments": {
                            "key_handle": "0x80000001", 
                            "value_max_length": 0, 
                            "class_max_length": 0, 
                            "value_name_max_length": 0, 
                            "value_count": 0, 
                            "subkey_max_length": 20, 
                            "class": "", 
                            "subkey_count": 12
                        }, 
                        "time": 1461057420.375, 
                        "tid": 2592, 
                        "flags": {}
                    }, 

No fake "regkey" field.   (Actually the field is also missing from RegClose, but that is not as important.)

**Comment by jbremer** [comment]
Thanks! The following should do the trick, https://github.com/cuckoosandbox/monitor/commit/88d0d8e715afb4a8cc236c93c79bf39cd6c3556e. Could you please verify with http://cuckoo.sh/340cd9d77351a6b5/monitor-x64.dll and http://cuckoo.sh/2cb68b24795b07da/monitor-x86.dll?

**Comment by frisk7** [comment]
Will check...but I will not have the results until after this weekend

**Comment by jbremer** [comment]
Sure thing, no worries :) Thanks.

**Comment by frisk7** [comment]
Confirmed.   I now get something like

                    {
                        "category": "registry", 
                        "status": 1, 
                        "stacktrace": [], 
                        "api": "RegQueryInfoKeyW", 
                        "return_value": 0, 
                        "arguments": {
                            "key_handle": "0x00000048", 
                            "value_max_length": 0, 
                            "class_max_length": 0, 
                            "value_name_max_length": 0, 
                            "regkey": "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\.NETFramework\\Policy", 
                            "value_count": 0, 
                            "subkey_max_length": 9, 
                            "class": "", 
                            "subkey_count": 6
                        }, 

Checked for RegQueryInfoKeyA as well.   

Thank you.

**Comment by jbremer** [comment]
You're welcome. Let us know if you're missing anything else.
