### ISSUE TITLE
kdbg support matter no? 

### ISSUE THREAD

**Issue by doomedraven** [cuckoosandbox/cuckoo#878]
hello all, finally do this, comparasion of processing one cuckoo report, in this case: `process.py -r X`
just need put it in vm config and set here
https://github.com/cuckoosandbox/cuckoo/blob/master/modules/processing/memory.py#L77
pretty easy, results here :

* hdd no kdbg

```
real 3m6.920s
user 2m56.168s
sys  0m9.164s
````

* ssd no kdbg

```
real 3m5.960s
user 2m55.620s
sys  0m9.120s
```

* hdd + kdbg

```
real 2m27.709s
user 2m17.584s
sys  0m8.816s
```

* ssd + kdbg

```
real 2m28.654s
user 2m17.516s
sys  0m9.176s
```

**Comment by doomedraven** [comment]
for those who don't know what is __kdbg__:

* Among other things, the imageinfo output tells you the suggested profile that you should pass as the parameter to --profile=PROFILE; there may be more than one profile suggestion if profiles are closely related. You can figure out which one is more appropriate by checking the "Image Type" field, which is blank for Service Pack 0 and filled in for other Service Packs. The imageinfo output also tells you the address of the KPCR and KDBG (short for \_KDDEBUGGER_DATA64). Plugins automatically scan for these values when they need them, however you can specify them directly for any plugin by providing --kpcr=ADDRESS or --kdbg=ADDRESS. __By supplying the profile and KDBG (or failing that KPCR) to other Volatility commands, you'll get the most accurate and fastest results possible.__

[source](https://code.google.com/archive/p/volatility/wikis/CommandReference.wiki)

**Comment by jbremer** [comment]
This is indeed something that we could incorporate with the machine baseline functionality. That is, once the `kdbg` address will be located and then that value is stored so it can be reused later on.
(Please run `./utils/submit.py --baseline --machine cuckoo` to get a baseline image).

**Comment by doomedraven** [comment]
ok so i'm finishing integrating it into memory.py and memory.conf, with 

```
[kdbgscan]
enabled = yes
```

and vol plugin __kdbgscan__

it will get baseline data with kdbg value, so it need be enabled once to not calculate it all the time
and it will be stored in json of a baseline of that vm, 

but it still need be read in memory.py(the baseline of that vm) to get kdbg value and speed up memory process, not in baseline comparison 

i will push merge req once everything is tested and works

**Comment by doomedraven** [comment]
@jbremer check this plz https://github.com/cuckoosandbox/cuckoo/pull/885 :) i think this is what you wanted, works as charme for me, to grab it, once activate in memory.conf + activate baseline in processing, prepare baseline and enjoy :)

**Comment by doomedraven** [comment]
just few works more :D

by defaut memory module not get kdbg data, and baseline just copy memory data and store it, so in that commit i added it, as its default vol plugin
once baselines with kdbg generated, kdbgscan can be disabled and baseline if used don't want, but in baseline file we will have already kdbg value, which must be loaded before memdump processing started :)
