### ISSUE TITLE
Some report.json files (and thus /tasks/report/<id> responses) fail to parse as JSON

### ISSUE THREAD

**Issue by milesarmstrong** [cuckoosandbox/cuckoo#879]
Hiya,

I am noticing a large number of responses from /tasks/report/id are failing to parse as JSON.

They parse ok in the latest version of Python:
```
Python 2.7.11 (default, Apr  6 2016, 16:30:49)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json, requests
>>> r = requests.get('http://cuckoo/api/tasks/report/337')
>>> report = json.loads(r.text)
```

But fail to parse in an older version:
```
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json, requests
>>> r = requests.get('http://cuckoo/api/tasks/report/337')
>>> report = json.loads(r.text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unpaired low surrogate: line 61563 column 358 (char 3237686)
```
Also fail to parse in perl:
```
#!/usr/bin/perl

use strict;
use warnings;

use Encode;
use LWP::UserAgent;
use JSON;

my $ua = new LWP::UserAgent;

my $response = $ua->get('http://cuckoo.netcraft.com/api/tasks/report/337');

if ($response->is_success) {
    my $report = $response->content;
    print from_json($report);
}
else {
    die $response->status_line;
}
```
gives:
 ```
missing high surrogate character in surrogate pair, at character offset 3237691 (before ")0000211941000000000...") at /usr/share/perl5/vendor_perl/JSON.pm line 171.
```

I wondered if the API was somehow breaking the JSON inbetween reading from disk and sending the response so I've tested the report.json file directly as well, and the same issue occurs.

I've attached the report.json for analysis 337. In total I've seen around 150 analyses that fail in this way.

[report.json.zip](https://github.com/cuckoosandbox/cuckoo/files/230189/report.json.zip)

**Comment by jbremer** [comment]
This sounds like an unicode issue (with the low/high surrogate errors). Could you perhaps share your `report.json` or consolidate it into just the part that contains the actual error?
Given that it doesn't give errors in the latest version of Python we should perhaps be able to find a workaround for older versions of Python. Regarding support in Perl I can't help you much ;-)

**Comment by milesarmstrong** [comment]
Thanks, I attached to the original issue, but here it is renamed to .txt so github will accept it:
[report.json.txt](https://github.com/cuckoosandbox/cuckoo/files/231501/report.json.txt)

My guess is that its a bad encoding of binary data from registry dumps. It seems to show up mostly in analyses of Microsoft Office files, but i've seen it with other filetypes too.

**Comment by jbremer** [comment]
Oh, sorry, I missed it. Yeah, that sounds about right. I'll check it out later.

**Comment by milesarmstrong** [comment]
Thanks! By the way, my Cuckoo instance is running on Python 2.7.11, so the report.json files are generated from that version.

**Comment by jbremer** [comment]
I'm able to load your json file just fine in Python 2.7.6, so I suppose some unicode related bugs were resolved in-between those versions..

**Comment by milesarmstrong** [comment]
Thanks :) It seems older versions of various languages can't handle the surrogate chars.
