### ISSUE TITLE
Feature request: Fake "service_name" field

### ISSUE THREAD

**Issue by frisk7** [cuckoosandbox/cuckoo#882]
As I mentioned in https://github.com/cuckoosandbox/cuckoo/issues/876 I really appreciate the fake "regkey" field for the various W32 registry-related functions that just take a handle as an argument - without that, everyone would have to keep track of just which registry entry each handle refers to.

However, there is another similar situation with service handles.

Consider for example the following json output

                   {
                        "category": "services", 
                        "status": 0, 
                        "stacktrace": [], 
                        "last_error": 1062, 
                        "nt_status": 0, 
                        "api": "ControlService", 
                        "return_value": 0, 
                        "arguments": {
                            "service_handle": "0x00352f98", 
                            "control_code": 4
                        }, 
                        "time": 1457888495.5, 
                        "tid": 3736, 
                        "flags": {}
                    }, 

It is not obvious which service 0x00352f98 refers to, but the workaround in this case is to keep track of return values from calls to OpenService:  (3485592 == 0x00352f98)

                    {
                        "category": "services", 
                        "status": 1, 
                        "stacktrace": [], 
                        "api": "OpenServiceW", 
                        "return_value": 3485592, 
                        "arguments": {
                            "service_manager_handle": "0x00357b70", 
                            "service_name": "ODService", 
                            "desired_access": 132
                        }, 
                        "time": 1457888495.5, 
                        "tid": 3736, 
                        "flags": {}
                    }, 

It would save people a bit of effort if there was a "fake" field added to the ControlService (and DeleteService) output - something like 

          "service_name": "ODService", 

just as is currently done with the fake "regkey" field.  Quite a few malicious programs attempt to disable security-related services so making it easier to detect that kind of behavior would directly help with malware detection.

**Comment by jbremer** [comment]
I've implemented this functionality, but again, will push it later. Working on some other changes as well currently :-) If you could check it out later that'd be great.

**Comment by jbremer** [comment]
Actually, there we go @frisk7 :)

**Comment by jbremer** [comment]
Did you verify this added functionality, @frisk7?

**Comment by frisk7** [comment]
Eh, no...not yet - is there an updated dll somewhere ?

(and on that subject, is a stable RC2 planned for release in the not-to-distant future?)

**Comment by jbremer** [comment]
Just the following commit is required https://github.com/cuckoosandbox/cuckoo/commit/7ccf983b2ba3aacb749e5e9e9313eb033bff0a0c ;-)

**Comment by frisk7** [comment]
tested, but it didn't work as intended - no fake "service_name" argument in the output.   I will double check whether this is a mistake on our end.

**Comment by frisk7** [comment]
Realized we forgot to do a cuckoo service restart after updating the file.

Now, I’m getting the following error: “[root] CRITICAL: CuckooCriticalError: Unable to import plugin "modules.processing.behavior": cannot import name guid_name”.

Because of this error, cuckoo process server can’t create a report from the data collected by cuckoo agent and uploaded to the server (in order to be processed by the “processing module”).

Seems like the release doesn’t work or partial (maybe we have to update more files on the cuckoo server).

Maybe we will just wait for the next stable full release (rc2?)  as we kind-of have a workaround, as I mentioned in the first post (keeping track of the values ourselves), so this is absolutely not critical.

**Comment by jbremer** [comment]
The `guid_name` thing was added three months ago, so if that all of a sudden throws errors then there may be something else wrong about the setup as well. Ah, I guess you copied the `platform/windows.py` over to your 2.0-rc1 branch? That may not always be the best way to go forward :-)
Anyway, upon popular demand we're working towards a 2.0-rc2 release right now, so hopefully that will be released before the end of this month ;-)

**Comment by jbremer** [comment]
Going to close this as resolved :-) Thanks!
