### ISSUE TITLE
 WARNING: Inconsistent arg count (compared to arg names) on DrawTextExA: {u'I': 261, u'h': 0L, u'args': [1, 17L], u'T': 796, u't': 734} names [u'is_success', u'retval', u'string']

### ISSUE THREAD

**Issue by Nadacsc** [cuckoosandbox/cuckoo#884]
I am getting that error with a couple of samples ? how can this affect the analysis results ? 
I am using Cuckoo Sandbox 2.0-RC1.

**Comment by jbremer** [comment]
Sorry for not replying any earlier, but I somewhat assume that you are no longer experiencing this particular issue? If so, could you please update to the latest and greatest? Thanks!

**Comment by jbremer** [comment]
I assume this has been resolved in the meantime.
