### ISSUE TITLE
ERROR: Failed to run the reporting module "MongoDB"

### ISSUE THREAD

**Issue by M3N9** [cuckoosandbox/cuckoo#886]
![capture](https://cloud.githubusercontent.com/assets/18697046/14847113/8984bee6-0c99-11e6-9791-ba00d2a0a7a9.PNG)

Hello there,
I met with some errors when i submitted a URL for analysis.
Attached is the screenshot of my Ubuntu.
Currently I'm using Cuckoo Sandbox 2.0-rc1.

Hope someone can help.
Thank You.

**Comment by jbremer** [comment]
Assuming you're running 2.0-rc1, could you please manually apply the following commit? a532b191532019d176068139e05b9846ab5136d6
Alternatively you can update to the latest development version, but I believe that commit will fix the issue you reported.

**Comment by M3N9** [comment]
Hi @jbremer, thanks for your help. 
Working fine now :)
