### ISSUE TITLE
analysis package: finish not hit when ended with timeout

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#892]
Hello,
Per reference: http://docs.cuckoosandbox.org/en/latest/customization/packages/

I'm not sure this is a wanted behavior, but it looks like the finish method is not hit when the analysis ends with a timeout. Can someone confirm?

**Comment by jbremer** [comment]
Just checked - no, the `stop()` and `finish()` methods should still be invoked.

**Comment by Tigzy** [comment]
That's weird, the issue must be on my side... Thanks for checking.

**Comment by Tigzy** [comment]
@jbremer You're right, it was hit.
However the code I put here doesn't do anything, and I have no idea why. 
Is NetLogFile supposed to work into a package module just like for an auxiliary module? (this is what you gave me here: https://github.com/cuckoosandbox/cuckoo/issues/888)

```
def finish(self):
  log.info("hit finish")
  nf = NetLogFile("logs/custom.json")
  nf.send(some json string here)
```

**Comment by jbremer** [comment]
The `finish` function should be part of your class that inherits `Auxiliary`, yes, if that's what you're asking :-) If you can provide a full auxiliary module (or something that should do at least something) I can help testing it.

**Comment by Tigzy** [comment]
Sorry, I realize I wasn't very clear, even for myself re-reading :) 
So, the "log.info" DOES actually work (this is how I knew it was hit. 
But the NetLogFile doesn't seem to be working, and is silently failing (not error about it)
This is that later part where I'm stuck. 

The whole module is as simple as EXE package with the finish function I've just pasted

**Comment by Tigzy** [comment]
for reference:

```
import os
import shlex
import json
import logging

from lib.common.abstracts import Package
from lib.common.results import NetlogFile

log = logging.getLogger("analyzer")

class CustomExe(Package):
    """Custom analysis package."""

    def start(self, path):
        args = self.options.get("arguments", "")

        name, ext = os.path.splitext(path)
        if not ext:
            new_path = name + ".exe"
            os.rename(path, new_path)
            path = new_path

        return self.execute(path, args=shlex.split(args))

    # Post execution
    def finish(self):
        log.info("Hit package.custom.finish")
        nf = NetlogFile("logs/custom.json")
        nf.send(json.dumps(['foo2', {'bar2': ('baz2', None, 1.0, 2, False)}]))
        return True
```

**Comment by Tigzy** [comment]
Ok, I found the issue. 
NetLogFile refuses to overwrite an existing file...
Do you have an idea how I could append a message to an existing log file?

**Comment by jbremer** [comment]
Sorry for the delay - no, that's currently not supported (I guess). Feel free to send in a PR to fix that, though. Closing this issue as resolved :-) Let us know if you have any other questions.
