### ISSUE TITLE
Error getting access to Process: 5!

### ISSUE THREAD

**Issue by alanr917** [cuckoosandbox/cuckoo#893]
Hi, I am getting an error with the newest version of Cuckoo when running on a Windows 10 guest VM. I made sure that the account logged in was an administrator, as I read that this error could be cause by that, but I am still having no luck. The agent is running on the guest, but I am still getting this error. Any ideas? Thanks!
![screenshot from 2016-04-29 12-47-55](https://cloud.githubusercontent.com/assets/12801226/14923067/f45fe3c4-0e08-11e6-87b8-d9be6e58ce36.png)

**Comment by jbremer** [comment]
Unfortunately Windows 10 is currently not officially supported. To be honest I have never tested it either, so I definitely can't confirm at this point if it works at all in the first place.

**Comment by alanr917** [comment]
Gotcha, The only reason I moved to Win10 was because I was getting the same error on Win7. I thought Win10 might fix this issue if I had something mis configured with my Win7 VM. I am getting the same error on my Windows 7 VM.

**Comment by jbremer** [comment]
On Windows 7 you should disable UAC :-)

**Comment by alanr917** [comment]
I saw the other ticket that was made for this a while ago, so I disabled UAC and the Firewall. still no luck.

**Comment by jbremer** [comment]
You have to explicitly run Python as Administrator - did you?

**Comment by alanr917** [comment]
I couldnt figure out how to do that. There was no right-click>Run as admin like there is for executables.

**Comment by jbremer** [comment]
You have to run the Python interpreter as Administrator. Closing as resolved.
