### ISSUE TITLE
How Cuckoo intercepts processes started from malware?

### ISSUE THREAD

**Issue by bit111** [cuckoosandbox/cuckoo#897]
Hi,
I would like know how, as a technical point of view, cuckoo knows processes started from malware. It can do with tcpdump and python agent?

**Comment by jbremer** [comment]
The Cuckoo Monitor (https://github.com/cuckoosandbox/monitor) intercepts that information and makes the Analyzer inject itself into the new process. So this is unrelated to tcpdump or the Agent.

**Comment by bit111** [comment]
Hi @jbremer,
probably I have explained evil or perhaps I did not understand your answer, but I wish to understand how cuckoo (installed on linux machine) can knows processes started in guest machine (running windows 7).
Analyzing python agent ([agent.py](https://github.com/cuckoosandbox/cuckoo/blob/master/agent/agent.py)) I understand that agent runs (line 167) [windows analyzer](https://github.com/cuckoosandbox/cuckoo/blob/master/analyzer/windows/analyzer.py)
It is correct to say cuckoo can intercepts processes started on guest machine thanks to python agent and thanks to /cuckoo/analyzer/windows/analyzer.py ?

**Comment by bit111** [comment]
Hi @jbremer,
I reviewed the code with more attention and I understand I made an error in my previous consideration: cuckoo runs **analyzer.py** created in guest machine (eg.: C:\\random_dir\analyzer.py) as we can see in **agent.py** (lines 147-157):

```
    def add_analyzer(self, data):
        """Add analyzer.
        @param data: analyzer data.
        @return: operation status.
        """
        data = data.data

        if not self._initialize():
            return False
        try:
            zip_data = StringIO()
            zip_data.write(data)

            with ZipFile(zip_data, "r") as archive:
                archive.extractall(self.analyzer_folder)
        finally:
            zip_data.close()

        self.analyzer_path = os.path.join(self.analyzer_folder, "analyzer.py")
        return True
```
So, my question is: **analyzer.py** is a copy of /cuckoo/analyzer/windows/analyzer.py ?

**Comment by jbremer** [comment]
Yes, all of `analyzer/windows` is sent over to Guest.

**Comment by bit111** [comment]
Hi @jbremer,
I wish to know some informations about cuckoo analysis (let me know if I have to open another dedicated thread): 
1) can cuckoo collects informations about malware which operates as a service in svchost? And as a process?
2) can cukoo traces services installation in svchost?
Thank you

**Comment by jbremer** [comment]
Current answer would be: partially. Anyway, little bit of a late answer, I think I can close this :)
