### ISSUE TITLE
Memory Download doesn't work with vCenter 6 (machinery vsphere)

### ISSUE THREAD

**Issue by RedWolf74** [cuckoosandbox/cuckoo#901]
Hi,

in Cuckoo 2.0-RC1 the download of the memory dump (snapshot) doesn't work with vCenter 6, lower versions not testet. While downloading a file from an ESXi, the dcPath parameter (Datacenter, in which the VM resides) is optional, with vCenter it is mandatory.
After changing in vsphere.py in function _download_snapshot
param = {"dsName": datastore} to param = {"dsName": datastore, "dcPath": "DatacenterName"} 
it is working well.
Could you please add the datacenter parameter to the construction of the URL request.
This should not conflict with stand alone esxi, 'cause there is this parameter too with the default value "ha-datacenter".

Thanks.

**Comment by jgajek** [comment]
Thanks for the report!  I will take a look.

**Comment by jbremer** [comment]
Thanks for picking up on this issue @jgajek :)

**Comment by RedWolf74** [comment]
@jgajek: thanks for taking a look at this. I know, it's a bad idea to
provide a datastore name via a config file in a vSphere env. My first
approach was to retrieve the dcPath via the pyVim api (like it is possible with i.e.
esxcli), but found no method for this in the api-docs. If you are more
familiar with the pyVim api, I suggest to get the dcPath via the api, if
it is possible.

**Comment by jgajek** [comment]
Yes, it's absolutely my plan to use the API to associate the VM with the correct Datacenter.  I will send a pull request with the changes, but since I only have access to a standalone ESXi host at the moment, I will need you to test it out in a vCenter environment.

**Comment by jbremer** [comment]
@RedWolf74 @certau-davidg please take a look at #978 which just got merged, thanks to @jgajek!

**Comment by jgajek** [comment]
Submitted the pull request with the required changes -- can you give this a shot against a vSphere server?  I would be especially interested in whether this handles VMs within nested Datacenter folders.

**Comment by RedWolf74** [comment]
I've tested against vSphere as well as stand alone ESXi, both is working well. @jgajek what do you mean with nested Datacenter folders?

**Comment by jgajek** [comment]
@RedWolf74 Thanks for confirming.  According to https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.wssdk.pg.doc_50%2FPG_ChC_Http_Access.21.3.html the root datacenter folder can contain datacenter objects as well as child datacenter folders in a nested hierarchy.  For example, to access a file in datacenter DC1, which resides in the datacenter folder FOLDER1, you would specify the dcPath parameter as dcPath=FOLDER1/DC1.  I think I'm handling this correctly, but have no way to test without access to a vCenter server.

**Comment by RedWolf74** [comment]
@jgajek sorry, do not have access to such an constallation and so not able to test it. But this seems to be unlikely for an isolated analyzis environment. Your solution is pretty smart at all. Thanks for this great job.

**Comment by jgajek** [comment]
Ok, we will wait for someone to complain if it doesn't work :)

I'm thinking it might be desirable to have optional per-machine configuration parameters for the datastore and datacenter to allow for complicated datacenter hierarchies with non-unique machine names.  If no such parameters are specified, then current logic of scanning all datacenter folders will be applied.

**Comment by Lindi16** [comment]
Hey.
i guess it suites to this track? ;D

Setup: exi server + vCenter 
-> Ubuntu Vm: Cuckoo
-> Win7SP1x86 Vm -> "analysis1"

after a bit of searching i found that the esx.conf doesn't support the mem.dump -> but the vsphere.conf does so changed :D
--> now i get a mem.dump and vsphere-clinet logs confirm that the snapshot was taken/removed. but the mem.dump file is empty (size 0)

**Comment by E3L-1** [comment]
First of all, i'm psyched this has been working for vsphere! For this issue, after banging my head on the desk for a little while, this issue turned out to be an authorization error for me. :(  One suggestion to help people troubleshoot in the future more easily, is to check the http response when attempting to download the file. It looks for exceptions, but that won't be thrown if you get a 401 or 404, etc. 
line 367:  response = requests.get(url, params=params.  ...... then do a check on the response and error if you get an unexpected http response. 
This way, people will see it in the logs more clearly without having to insert prints into the code.

**Comment by jgajek** [comment]
@E3L-1 I have a PR forthcoming shortly that will throw an error on unexpected HTTP status -- thanks for the feedback!

**Comment by E3L-1** [comment]
Excellent - thank you!

**Comment by jbremer** [comment]
I guess we can close this issue now, or?

**Comment by jgajek** [comment]
Yes, I think so.

**Comment by jbremer** [comment]
Sweet, thanks!
