### ISSUE TITLE
punch++ PCRE engine signature appears as non-compatible signature

### ISSUE THREAD

**Issue by hemzaz** [cuckoosandbox/cuckoo#907]
Hi
We need some help with importing punch++ PCRE matching engine into cuckoo 2.0RC1
[https://github.com/0xd34db33f/cuckoo/blob/master/signatures/punchplusplus.py](https://github.com/0xd34db33f/cuckoo/blob/master/signatures/punchplusplus.py)
For some reason in cuckoo 1.3 or cuckoo-modified it works flawlessly and it just not working on cuckoo 2.0RC1.

**Comment by doomedraven** [comment]
cuckoo-mod and cuckoo v2 has different abstracts, is why is not compatible, you can port it, read abstracts.py

**Comment by hemzaz** [comment]
great thanks!

**Comment by garanews** [comment]
@doomedraven : how to integrate the punchplusplus.py into spender-sandbox/cuckoo-modified ?

**Comment by doomedraven** [comment]
@garanews checks where `punchplusplus.py` loads into cuckoo and where called and save/return data, try do the same in mod and done :)

**Comment by garanews** [comment]
well, I put the script under signatures folder and in process.log I see 2016-07-19 09:30:28,994 [lib.cuckoo.core.plugins] DEBUG: Running signature "punch_plus_plus_pcres"
2016-07-19 09:30:28,996 [lib.cuckoo.core.plugins] DEBUG: Running signature "network_punchplusplus"
and in tcpdump I see traffic 09:30:32.726559 IP sandbox.local.44015 > djskywarp.com.https: Flags [.], ack 67152, win 1307, options [nop,nop,TS val 1483687689 ecr 2516717749], length 0
09:30:32.726823 IP sandbox.local.44015 > djskywarp.com.https: Flags [R.], seq 639, ack 67152, win 1307, options [nop,nop,TS val 1483687689 ecr 2516717749], length 0
I see that 2 files appeared: cuckoo-advanced/pcre-punchplusplus
cuckoo-advanced/web/pcre-punchplusplus

but don't know exactly where to find the result, if will appear in the dashboard or in a file  :)

**Comment by doomedraven** [comment]
where this appes? `cuckoo-advanced/pcre-punchplusplus
cuckoo-advanced/web/pcre-punchplusplus`?

**Comment by garanews** [comment]
exactly where I wrote, in the cuckoo root folder and into web subfolder.
seems the DB of signatures:
![image](https://cloud.githubusercontent.com/assets/16938405/16947959/59f89062-4db2-11e6-8fae-7be273a06683.png)
but not able to find results :)

**Comment by garanews** [comment]
It works:
![image](https://cloud.githubusercontent.com/assets/16938405/16954977/4aa555e8-4dd3-11e6-890d-89b7e0ac386e.png)

Sorry to wrote here but I didn't find another place to speak about this :)

**Comment by jbremer** [comment]
Please submit a PR for any ported Signatures! Thanks in advance. Closing issue as resolved.
