### ISSUE TITLE
Error running httpreplay-based PCAP analysis

### ISSUE THREAD

**Issue by xECK29x** [cuckoosandbox/cuckoo#911]
I have a feeling this is going to be a local issue but wanted to have you guys check it out. I had to change network interfaces of the server and reboot and now I am getting this error with httpreplay.

2016-05-10 12:00:31,911 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/media/xeck29x/Storage/cuckoo/modules/processing/network.py", line 764, in run
    results.update(Pcap2(pcap_path, self.get_tlsmaster()).run())
  File "/media/xeck29x/Storage/cuckoo/modules/processing/network.py", line 695, in run
    r = httpreplay.reader.PcapReader(self.pcap_path)
  File "/home/xeck29x/.local/lib/python2.7/site-packages/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(fp)
  File "/usr/lib/python2.7/dist-packages/dpkt/pcap.py", line 102, in __init__
    self.name = fileobj.name
AttributeError: 'str' object has no attribute 'name'

Attached is the PCAP, httpreplay and dpkt are installed
[pcap.zip](https://github.com/cuckoosandbox/cuckoo/files/257612/pcap.zip)

**Comment by jbremer** [comment]
You're correct, this is an issue with the very latest version of `httpreplay`. Could you verify that you're on version `0.1.15` of httpreplay? This is why we have strict version numbers in the `requirements.txt` file (so there we're still hardcoding to `0.1.14` which is before this API change).

**Comment by jbremer** [comment]
If you try the latest development version of Cuckoo it should properly, please let me know :-)

**Comment by xECK29x** [comment]
Yes I am running httpreplay-0.1.15, will try updating Cuckoo.

**Comment by xECK29x** [comment]
Receiving a slightly different error in the dev version. Also still receiving the Deprecation note on the 'Network Analysis' tab stating I don't have httpreplay installed?

2016-05-10 14:41:03,845 [lib.cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
5470 packets captured
5611 packets received by filter
0 packets dropped by kernel
2016-05-10 14:41:09,592 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/media/xeck29x/Storage/cuckoo-new/cuckoo/modules/processing/network.py", line 809, in run
    results.update(p2.run())
  File "/media/xeck29x/Storage/cuckoo-new/cuckoo/modules/processing/network.py", line 726, in run
    l = sorted(r.process(), key=lambda x: x[1])
  File "/home/xeck29x/.local/lib/python2.7/site-packages/httpreplay/reader.py", line 85, in process
    self.tcp and self.tcp.process(ts, ip, packet)
  File "/home/xeck29x/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 88, in process
    s.process(ts, tcp, to_server)
  File "/home/xeck29x/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 362, in process
    self.states[self.state](self, ts, tcp, to_server)
  File "/home/xeck29x/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 285, in state_conn
    self.parent.handle(self.s, self.ts, "tcp", sent, recv)
  File "/home/xeck29x/.local/lib/python2.7/site-packages/httpreplay/smegma.py", line 576, in handle
    records, length = dpkt.ssl.tls_multi_factory(sent)
AttributeError: 'module' object has no attribute 'tls_multi_factory'
2016-05-10 14:41:43,578 [lib.cuckoo.core.scheduler] INFO: Task #9: reports generation completed (path=/media/xeck29x/Storage/cuckoo-new/cuckoo/storage/analyses/9)

**Comment by jbremer** [comment]
Could you `pip install dpkt==1.8.6.2` and see if that helps? Or, like, `pip install -r requirements.txt` ;-)

**Comment by xECK29x** [comment]
This is going to end up becoming another issue, pip installing requirements.txt led to an install issue of cryptography:

Failed to build cryptography

See attached output.
[output.txt](https://github.com/cuckoosandbox/cuckoo/files/257894/output.txt)

**Comment by jbremer** [comment]
If you're on Ubuntu 16.04 LTS, please remove the strict version from `requirements.txt`. I believe that may work, I'll test myself in a bit.

**Comment by xECK29x** [comment]
I am, re-ran with the version removal, it updated a few packages, still receiving a core dump at the end with no real details:

xeck29x@xeck29x-HP-ZBook-17:/media/xeck29x/Storage/cuckoo-new/cuckoo$ pip install -r requirements.txt 
Collecting alembic (from -r requirements.txt (line 1))
  Downloading alembic-0.8.6.tar.gz (961kB)
    100% |████████████████████████████████| 962kB 358kB/s 
Collecting beautifulsoup4 (from -r requirements.txt (line 2))
  Using cached beautifulsoup4-4.4.1-py2-none-any.whl
Collecting cffi (from -r requirements.txt (line 3))
Collecting chardet (from -r requirements.txt (line 4))
Collecting cryptography (from -r requirements.txt (line 5))
Collecting Django (from -r requirements.txt (line 6))
  Downloading Django-1.9.6-py2.py3-none-any.whl (6.6MB)
    100% |████████████████████████████████| 6.6MB 90kB/s 
Collecting dpkt (from -r requirements.txt (line 7))
  Using cached dpkt-1.8.7-py2-none-any.whl
Collecting ecdsa (from -r requirements.txt (line 8))
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting elasticsearch (from -r requirements.txt (line 9))
  Downloading elasticsearch-2.3.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 138kB/s 
Collecting enum34 (from -r requirements.txt (line 10))
  Using cached enum34-1.1.5-py2.py3-none-any.whl
Collecting Flask (from -r requirements.txt (line 11))
Collecting HTTPReplay (from -r requirements.txt (line 12))
Collecting idna (from -r requirements.txt (line 13))
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting ipaddress (from -r requirements.txt (line 14))
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting itsdangerous (from -r requirements.txt (line 15))
Collecting Jinja2 (from -r requirements.txt (line 16))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting jsbeautifier (from -r requirements.txt (line 17))
  Downloading jsbeautifier-1.6.2.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 269kB/s 
Collecting Mako (from -r requirements.txt (line 18))
  Downloading Mako-1.0.4.tar.gz (574kB)
    100% |████████████████████████████████| 583kB 142kB/s 
Collecting MarkupSafe (from -r requirements.txt (line 19))
Collecting ndg-httpsclient (from -r requirements.txt (line 20))
Collecting oletools (from -r requirements.txt (line 21))
  Downloading oletools-0.46.zip (877kB)
    100% |████████████████████████████████| 880kB 271kB/s 
Collecting pefile from http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile (from -r requirements.txt (line 22))
Collecting pyasn1 (from -r requirements.txt (line 23))
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pycparser (from -r requirements.txt (line 24))
Collecting pymongo (from -r requirements.txt (line 25))
  Downloading pymongo-3.2.2.tar.gz (504kB)
    100% |████████████████████████████████| 512kB 238kB/s 
Collecting pyOpenSSL (from -r requirements.txt (line 26))
  Downloading pyOpenSSL-16.0.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 123kB/s 
Collecting python-dateutil (from -r requirements.txt (line 27))
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 168kB/s 
Collecting python-editor (from -r requirements.txt (line 28))
  Downloading python-editor-1.0.tar.gz
Collecting python-magic (from -r requirements.txt (line 29))
  Downloading python-magic-0.4.11.tar.gz
Collecting requests (from -r requirements.txt (line 30))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 226kB/s 
Collecting six (from -r requirements.txt (line 31))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting SQLAlchemy (from -r requirements.txt (line 32))
  Downloading SQLAlchemy-1.0.12.tar.gz (4.7MB)
    100% |████████████████████████████████| 4.8MB 104kB/s 
Collecting tlslite-ng (from -r requirements.txt (line 33))
  Downloading tlslite-ng-0.5.2.tar.gz (3.0MB)
    100% |████████████████████████████████| 3.0MB 173kB/s 
Collecting wakeonlan (from -r requirements.txt (line 34))
Collecting Werkzeug (from -r requirements.txt (line 35))
  Downloading Werkzeug-0.11.9-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 403kB/s 
Collecting setuptools>=11.3 (from cryptography->-r requirements.txt (line 5))
  Using cached setuptools-21.0.0-py2.py3-none-any.whl
Collecting urllib3<2.0,>=1.8 (from elasticsearch->-r requirements.txt (line 9))
  Using cached urllib3-1.15.1-py2.py3-none-any.whl
Collecting click<7,>=6.6 (from HTTPReplay->-r requirements.txt (line 12))
Building wheels for collected packages: alembic, jsbeautifier, Mako, oletools, pymongo, python-editor, python-magic, SQLAlchemy, tlslite-ng
  Running setup.py bdist_wheel for alembic ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/dd/ea/32/e389366a831f50505aef2220cbb08206f5354581061539ec5a
  Running setup.py bdist_wheel for jsbeautifier ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/04/f0/52/b238092e4257338c941b0fe5584bff5d6f5f3f8c2d2aece308
  Running setup.py bdist_wheel for Mako ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/2a/fa/9a/7030d96d3c51f433848e4cd67a353a411ba6deb5c14e150730
  Running setup.py bdist_wheel for oletools ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/c0/88/2e/22520f8dc9f5b04147cf74288cdfa5811a47551a40d0868d4e
  Running setup.py bdist_wheel for pymongo ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/a6/d7/ea/bd149d9e2fd0f9ab21959b63c250ef509e4e38cc6258f6a07d
  Running setup.py bdist_wheel for python-editor ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/bf/b0/80/87d736b06b442b90950f3e6106cf14ac79a9380a8531f99782
  Running setup.py bdist_wheel for python-magic ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/65/ab/71/40c6c38a050ce64fcbda7e3e8ee3096d5a6302ad4dab28ba8c
  Running setup.py bdist_wheel for SQLAlchemy ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/eb/90/c8/fc08769bc10c0e47ec6e71d998c5ee074b0580bf214b2e9ef0
  Running setup.py bdist_wheel for tlslite-ng ... done
  Stored in directory: /home/xeck29x/.cache/pip/wheels/1c/c6/73/c617f5f59ae5e607937605033526a65c757f2cd5e356beccd0
Successfully built alembic jsbeautifier Mako oletools pymongo python-editor python-magic SQLAlchemy tlslite-ng
Installing collected packages: SQLAlchemy, MarkupSafe, Mako, python-editor, alembic, beautifulsoup4, pycparser, cffi, chardet, setuptools, ipaddress, six, pyasn1, enum34, idna, cryptography, Django, dpkt, ecdsa, urllib3, elasticsearch, itsdangerous, Werkzeug, Jinja2, Flask, tlslite-ng, click, HTTPReplay, jsbeautifier, pyOpenSSL, ndg-httpsclient, oletools, pefile, pymongo, python-dateutil, python-magic, requests, wakeonlan
**Segmentation fault (core dumped)**

**Comment by jbremer** [comment]
That's bad :p To be honest Ubuntu 16.04 is still quite young, you're probably better off using 14.04 ;-)

**Comment by xECK29x** [comment]
Understood, darn bleeding edge! Hopefully these issues will get sorted out in the near future, feel free to close this.

**Comment by jbremer** [comment]
They will - one at a time ;-)

**Comment by doomedraven** [comment]
i don't have any problem on 16.04+cuckoo :P

**Comment by jdpadro** [comment]
doomedraven 
    You mentioned that you got 16.04 to work with cuckoo. Was it the desktop or the server? Did you document your installation process, and are you willing to share that document.

**Comment by jdpadro** [comment]
It seems that I am having an issue with the pip install of;
      http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile
      pyasn1==0.1.8
      pycparser==2.14
      pymongo==3.0.3
      pyOpenSSL==0.15.1

I decided to run each one of the requirements txt individually and noticed that when I attempted to install       http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile it goes belly up. 

pefile-1.2.10-139.tar.gz#egg=pefile
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in <module>
    error=-1)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 57, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'

root@cuckoo1:/home/cuckoo# python --version
Python 2.7.11+

**Comment by jbremer** [comment]
Try to replace the `pefile` line with `pefile==2016.3.28`.

**Comment by doomedraven** [comment]
@jbremer that version is broken :P 
this one last working version
http://pefile.googlecode.com/files/pefile-1.2.10-139.tar.gz#egg=pefile #the same version in github is broken

**Comment by andyrat33** [comment]
I'm on Ubuntu 14.04 LTS Cuckoo 2.0rc1
2016-07-09 10:33:11,660 [modules.processing.network] ERROR: Error running httpreplay-based PCAP analysis
Traceback (most recent call last):
  File "/home/andy/cuckoo/modules/processing/network.py", line 764, in run
    results.update(Pcap2(pcap_path, self.get_tlsmaster()).run())
  File "/home/andy/cuckoo/modules/processing/network.py", line 695, in run
    r = httpreplay.reader.PcapReader(self.pcap_path)
  File "/usr/local/lib/python2.7/dist-packages/httpreplay/reader.py", line 25, in __init__
    self.pcap = dpkt.pcap.Reader(fp)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/pcap.py", line 115, in __init__
    buf = self.__f.read(FileHdr.__hdr_len__)

I followed the instructions to fix HTTPReplay in  Issue #929 and that worked ok but I still get the message 
"Deprecation note: While processing this analysis you did not have the httpreplay Python library installed. Installing this library (i.e., pip install httpreplay) will allow Cuckoo to do more proper PCAP analysis including but not limited to showing full HTTP and HTTPS (!) requests and responses. It is recommended that you install this library and possibly reprocess any interesting analysis tasks."

**Comment by jbremer** [comment]
@andyrat33 Is that warning still present if you do a new analysis? :-)

**Comment by andyrat33** [comment]
Yes it' still there. Happy to try anything you want me to

**Comment by andyrat33** [comment]
I seem to have everything working except for the HTTPReplay. Is there any reason the esx would cause a problem with it? I have vpn working with it but elected to use just a single Nic to do packet capture and be the gateway nic. Cuckoo has two interfaces Internal net eth0 and host only net on eth1 could that be the problem?

**Comment by andyrat33** [comment]
rerunning apt-get -r requirements.txt seems to have solved the problem for me

**Comment by jbremer** [comment]
Going to close this issue as resolved.
