### ISSUE TITLE
AddrSpaceError: No suitable address space mapping found

### ISSUE THREAD

**Issue by satmit** [cuckoosandbox/cuckoo#912]
On running Volatility in Cuckoo Sandbox, we are getting this below error:
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareSnapshotFile: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: Unknown VBox core format version
 VMWareSnapshotFile: Invalid VMware signature: 0x464c457f
 WindowsCrashDumpSpace32: Header signature invalid
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile Win7SP1x64 selected
 IA32PagedMemory: Incompatible profile Win7SP1x64 selected
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check

We tried the manual analysis of Memory Dump, the same error continues.

Details of Versions using:

Cuckoo Sandbox - 2.0
Base machine - RHEL 7 64-bit
Oracle VM 5.0 - Windows 7(tried 32-bit & 64-bit)
Volatility - 2.3.1

![screenshot from 2016-05-11 11 16 59](https://cloud.githubusercontent.com/assets/19163822/15171138/0bd5d3a0-171a-11e6-965e-22908b58fe75.png)

Thanks & regards,
SatheeshKumar T

**Comment by doomedraven** [comment]
i saw it with vol 2.3.1, update to 2.4 or 2.5 and it will be solved :)

**Comment by satmit** [comment]
Thanks @doomedraven ...!!! It works Succesfully.

**Comment by cyjcyjcyj** [comment]
I met this problem,too. And my vol's version is 2.6. How can I solve this problem ?

**Comment by doomedraven** [comment]
what about `vol.py -f path_to_dump imageinfo`  can you post the output?

**Comment by cyjcyjcyj** [comment]
> what about `vol.py -f path_to_dump imageinfo` can you post the output?

Does the 'path_to_dump' is a dump file which is stored in 'cuckoo/storage/analyses/1(or 2..3..)/memory.dump' ?
Here is  my output:
sun@sun-Q170-4S:~/cuckoo-1.2/volatility-master$ vol.py -f ../storage/analyses/24/memory.dmp imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win7SP1x64, Win7SP0x64, Win2008R2SP0x64, Win2008R2SP1x64_24000, Win2008R2SP1x64_23418, Win2008R2SP1x64, Win7SP1x64_24000, Win7SP1x64_23418
                     AS Layer1 : WindowsAMD64PagedMemory (Kernel AS)
                     AS Layer2 : VirtualBoxCoreDumpElf64 (Unnamed AS)
                     AS Layer3 : FileAddressSpace (/home/sun/cuckoo-1.2/storage/analyses/24/memory.dmp)
                      PAE type : No PAE
                           DTB : 0x187000L
                          KDBG : 0xf80003e04070L
          Number of Processors : 1
     Image Type (Service Pack) : 0
                KPCR for CPU 0 : 0xfffff80003e05d00L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2018-09-18 07:41:51 UTC+0000
     Image local date and time : 2018-09-18 15:41:51 +0800

**Comment by doomedraven** [comment]
yes, so here you go 

`Suggested Profile(s) : Win7SP1x64, Win7SP0x64, Win2008R2SP0x64, Win2008R2SP1x64_24000, Win2008R2SP1x64_23418, Win2008R2SP1x64, Win7SP1x64_24000, Win7SP1x64_23418`

which profile do you have set in memory.conf and your hypervisor configs in vm config?

**Comment by doomedraven** [comment]
and if you use `cuckoo-1.2` lol that is too damn old, depricated etc xD
upgrade to 2.0.6

**Comment by doomedraven** [comment]
yes, well it suggest you try one of those, so do tests

`vol.py -f memdump_path --profle=X malfind`

and with profile which not failing, is that your profile, learn how volatility works to solve the problem

**Comment by cyjcyjcyj** [comment]
The test is not failing. But the error is still remaining. Except to update the version of cuckoo, do you have some other suggestions?

**Comment by doomedraven** [comment]
`rm -r /home/sun/cuckoo-1.2/`
`pip install cuckoo`
__READ THE DOCUMENTATION__ to learn how it works on latest version

well if that not fails on test, that mean what in some confs you have a bad profile for vm, referer documentation

**Comment by cyjcyjcyj** [comment]
> `rm -r /home/sun/cuckoo-1.2/`
> `pip install cuckoo`
> **READ THE DOCUMENTATION** to learn how it works on latest version
> 
> well if that not fails on test, that mean what in some confs you have a bad profile for vm, referer documentation

Thanks a lot.

**Comment by doomedraven** [comment]
np :)
