### ISSUE TITLE
HTML template customization, Jinja2 does not recognize a std filter

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#914]
Hello, 
I'm trying to customize the html templates, I've seen it's using Flask/Jinja2 to render the data.
I'm trying to put some Json data in pretty print format, but it looks like the tojson filter isn't recognized. 

I'm not an expert, but I've read the json filter is part of the std library with Jinja2, so I have no idea what's going on. Any help on this?

Template:
`{{ 'test'|tojson }}`

Error:

```
TemplateSyntaxError` at /analysis/32/
Invalid filter: 'tojson'

Request Method:     GET
Request URL:    http://hot.home:8081/analysis/32/
Django Version:     1.8.4
Exception Type:     TemplateSyntaxError
Exception Value:    
Invalid filter: 'tojson'

Exception Location:     /usr/local/lib/python2.7/dist-packages/django/template/base.py in find_filter, line 429
Python Executable:  /usr/bin/python
Python Version:     2.7.6
Python Path:    

['/home/cuckoo/cuckoo/web',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/home/cuckoo/cuckoo/web/..',
 '/home/cuckoo/cuckoo/web/..',
 '/home/cuckoo/cuckoo/web/..',
 '/home/cuckoo/cuckoo/web/..',
 '/home/cuckoo/cuckoo/web/..',
 '/home/cuckoo/cuckoo/web/..']

Server time:    Wed, 11 May 2016 16:53:01 +0200
```

**Comment by jbremer** [comment]
If only it was Jinja2 ;-) We're using Django templating syntax. Although I believe it is possible to enable Jinja2 templating on a per-template basis.

**Comment by Tigzy** [comment]
Ok, what would you recommend in my case? I just need to dump a subpart of the analysis global container into a <pre> block, in pretty print.

**Comment by jbremer** [comment]
Something like `<pre>{{ analysis.info.score }}</pre>`?

**Comment by Tigzy** [comment]
The django templating syntax doesn't seem to have builit json capability: https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#ref-templates-builtins-filters

**Comment by Tigzy** [comment]
@jbremer something is filtering and rendering the json in plain text, in an ugly format: 
`{u'header': {u'environment': {u'user_admin': True, u'program_location': u'c:\\Users\\franck\\AppData\\Local\\Temp\\tmpjh3dz4.exe', u'winpe': False, ... etc`

**Comment by jbremer** [comment]
That means you're directly embedding a dictionary. Sorry for the late reply.
Closing this issue as I'm assuming you've already worked around it by now.
