### ISSUE TITLE
Dropped tab not shown in overview 

### ISSUE THREAD

**Issue by M3N9** [cuckoosandbox/cuckoo#915]
Hello there,
I was wondering how do i allow dropped file tab to show in the overview. And is there any other function that i have miss out.

Attached is my screenshot of Cuckoo Sandbox 2.0-rc1.

(Missing Dropped file tab) 
![dropped](https://cloud.githubusercontent.com/assets/18697046/15202633/c13aa85a-182e-11e6-86b1-258e0fae6e42.PNG)

(Debug mode shows no error)
![debug](https://cloud.githubusercontent.com/assets/18697046/15202639/cf37be5c-182e-11e6-80f6-a955b1222c4d.PNG)

Thank You.

**Comment by doomedraven** [comment]
@M3N9 no behaviour, so nothing dropped? did you execute without injection? or analysis failed? can provide analysis log?

**Comment by M3N9** [comment]
Hi @doomedraven ,

For your reference. 

(analysis log)
![analysis log](https://cloud.githubusercontent.com/assets/18697046/15208508/7e0a049c-185e-11e6-93eb-c9f7a51496ef.PNG)

(cuckoo)
![cuckoo](https://cloud.githubusercontent.com/assets/18697046/15208509/801a3496-185e-11e6-970b-887ba82d2e1d.PNG)

Do i need to edit any of the processing modules? Thank You.

**Comment by doomedraven** [comment]
are those log are from the same analysis ? because here i case see what dll started with pid X, but in previous comment there not behaviour at all

**Comment by M3N9** [comment]
Hi @doomedraven, is a different analysis. This is the behaviour tab.
![ba](https://cloud.githubusercontent.com/assets/18697046/15210708/3214daba-186a-11e6-99e3-5014095bae6f.PNG)

**Comment by doomedraven** [comment]
@M3N9 if you have this enabled https://github.com/cuckoosandbox/cuckoo/blob/master/conf/processing.conf#L32
then do next

do url analsys of ipinfo.io with timeout 60 seg, as it load a lot of scripts you must have dropped tab

**Comment by jbremer** [comment]
If there are no dropped files, then the tab is not shown in the Web Interface, so nothing to worry about :-)

**Comment by M3N9** [comment]
Hi @jbremer & @doomedraven,
Thank You for your help :)
