### ISSUE TITLE
Problem with NtCreateUserProcess ?

### ISSUE THREAD

**Issue by frisk7** [cuckoosandbox/cuckoo#916]
I am currently doing some analysis of various code injection techniques used by malware programs, and have noticed something odd.

When looking at the sandbox .json output file for injectors, I see calls to various injection-related APIs (like WriteProcessMemory and CreateRemoteThread) with the process_handle of the process being injected into. I see the malware sometimes getting the handle initially from NtOpenProcess but usually from CreateProcessInternalW (that is, the malware may for example call CreateProcess, which eventually results in a call to CreateProcessInternalW) - however, I have around 50 samples where there is no indication of an API call where the malware gets the process handle initially, or (and most importantly) how the process got created in the first place.

Analysis of a couple of those files indicates that they call **NtCreateUserProcess**, and it turns out that this API does not seem to get logged at all.  This has me a bit mystified, as that API does appear to be hooked, so what is going on?

There is possibly a similar issue with CreateProcessAsUser[W/A] - I see malware importing that API, but not a single log shows it ever being called.  (And yes, CreateProcessWithLogonW and CreateProcessWithTokenW might possibly have the same issue, but I it appears I do not have a single malware sample that actually uses those APIs)

**Comment by jbremer** [comment]
Thanks for the in-depth report, @frisk7. Could you please share the hashes of some of these samples? That'd definitely help.

**Comment by frisk7** [comment]
Here is a list of MD5 sums of the ~50 files - however this might turn out to be a non-issue - I found an error in the code on my end, so I am going to re-run the processing overnight and see if this is actually an issue....sorry.

010fb46b6fe3d516b678ed68806aa41c
066cff8aef9eaa344f872001ab18319b
07c4b5ffd15cb108f5c21e13c67ad1a8
0821086b21bed41a48abceb1e560ced2
0ca19da0394f8ccd08d877a39c1002cc
14d294fbfef36c063b96fcfb0d849d46
15a2176ba4127df6e40c020ac4995ac8
16853d22f2f91434d844724b68224af6
16bd57f4027273363798670834700663
20f03f52c882dc7f1c2a1bdcd33bfa1e
31afaa440a015cc95f0e182a1680b61f
367bd0b02b47c3de4dcc2331acd0bd0e
36888c36b5b577b5fcdc61edcc696a4b
3ea8e51fe5d93f4d01e5a3897b0a328b
3fc25020c2e11421fdc5dcd93953558e
42496cd97568b3873029781486450dde
49dcddb0eedbbb814e501ef46e2eceac
4bcead4107ed219f4af8a6d206ad3285
4d08934bd040ed25dfa46542e396cb05
5604997bb5733617d2346d58eb6e4afe
58976e5821ae6701f6aabbc279951cc0
66c4e845d0ef8894431dc95e4c083f27
67fa719ca9c20016b7d044d179bb2a2f
6cd71049e2b9e7f09c53c012545ad2a2
76122a06de06408589a08cb8058f8767
7adfeb3e93610d9758fac6f901005768
7bfdd28e8e8e7a1b1e9ac0fb4c4cb9b3
7c2d49af92cecdef96318be3373d5b60
7eac25bfc4781ca44c5d991115aaf0b4
819b2c06dc0b8e19044060209866f377
876021b7626054d5c4ac3f8fca9a21a7
8a264980c33a8482bc8ff991db7a06b3
8eeb03434fec6f3d3d12c5c5b7cb8d7f
8f75fef98f5e52800f3fd50bd5258a56
989fe32c814a09a49cbb56443de5d1d7
9f1b5231fb1bf1a2be0544bb41cca064
a12e01c87fd6c31e6125419c8f57a851
a13f9bbf6d1969b3182676b4ae45bc27
a2b9ccc0e992cb19629064b62ed6c9bc
a379612563a3f4f8c0ff6983c80cf179
a5eab9214f733adfefad4954c5f6a058
a8e4976f73c6f761d7232afa464304c0
abe1c26517d81577f94cb563bb141507
b2f7c8f82cd564f38ad692f8366b2f59
bfd9b8050ddacb7fbe87b4bef6f5e53e
c3c47e50fb4f6687abaf6eee70fcaa40
c7f95cd0f8231d2a0eb20bec4347a6d8
d2a967a79ee53d46095d52156d2da7ad
d9b812f2c323edf69154404003c0b056
d9ef10299ce15a34977092cbc0a89e32
dd2458440cc7c485225bfff8cde66759
dec995ef0cceb8d5fafef16bd71c2e79
ee175d5dd9faf56281b9e482050f31e7
f310c33179551e4b7569fad0f10369bd
f591fc7415eaad367f900eca5bfedea5
f9cfa9ecb81873c0cdb2fae0a94817b5
fb1e6e4a9aa6c2e82eba7647ae706445

**Comment by frisk7** [comment]
OK, I fixed the issue and this turned out to be a non-issue (my own stupid mistake - I had filtered out a set of calls), sorry.

Consider this closed.
