### ISSUE TITLE
[modules.processing.network]ERROR:Error running httpreplay-base PCAP analysis

### ISSUE THREAD

**Issue by indexx99** [cuckoosandbox/cuckoo#929]

**Comment by jbremer** [comment]
For others running into this error, Cuckoo includes a `requirements.txt` with the correct version of httpreplay included. Recently we upgraded both, so you'll need the latest Cuckoo with the latest HTTPReplay, or an older version of both.

**Comment by dforce** [comment]
@jbremer 
The version of tlslite-ng mentionned in requirements.txt is OK but running the install of HTTPReplay give an error ecause it is looking for tlslite-ng==0.6.0a3 which doesn't exists.
It is possible to change this in the tar.gz of the latetst HTTPReplay ?

Thanks

**Comment by jbremer** [comment]
`pip` is being a little bit weird about the `0.6.0-alpha3` vs `0.6.0-a3` thing so I'm still not sure which one to use. E.g., when I create a `virtualenv`, I get the following messages.

```bash
pip install httpreplay -U
You are using pip version 6.0.8, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting httpreplay
  Using cached HTTPReplay-0.1.15.tar.gz
Collecting dpkt==1.8.7 (from httpreplay)
  Using cached dpkt-1.8.7-py2-none-any.whl
Collecting tlslite-ng==0.6.0a3 (from httpreplay)
  Using cached tlslite-ng-0.6.0-alpha3.tar.gz
    /tmp/kek/local/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.6.0a3' instead of '0.6.0-alpha3'.
      self.metadata.version,
```

So.. hmm, it seems that this could perhaps be because of the older version of pip itself.
You can change the dependencies by cloning the httpreplay repository, modifying its `setup.py`, and running `python setup.py sdist` to get a `pip install`-able `.tar.gz` in the `dist/` directory.

**Comment by TiTi87** [comment]
Hey, 
Thanks a lot, it did works for me, I was starting to lose hope here... Here's a more detailed step by step method : 

1. get HTTPReplay tar.gz (or a more recent version) : `wget  https://pypi.python.org/packages/0e/42/dc0e06bdeb032ad089e387f6666e0850798b67f905cc19815131bd64b842/HTTPReplay-0.1.15.tar.gz`
3. Extract the archive : `tar -xvf HTTPReplay-0.1.15.tar.gz`
4. move into the new dir : `cd HTTPReplay-0.1.15`
5. In Setup.py modify `“tlslite-ng==0.6.0a3”` into `“tlslite-ng==0.6.0-alpha4”` (or a more recent version)
6. Build a new tar.gz : `python setup.py sdist`
7. Move into dist : `cd dist/`
8. To avoid any mistake later : `mv HTTPReplay-0.1.15.tar.gz HTTPReplay-0.1.15-custom.tar.gz`
9. Install this custom version : `pip install HTTPReplay-0.1.15-custom.tar.gz`
10. Check install with : `pip freeze | grep HTTPReplay`

Hoping it will help someone.
Thanks for all.
