### ISSUE TITLE
cuckoo2.0 process cuckoo1.0's bson

### ISSUE THREAD

**Issue by xvsfekcn** [cuckoosandbox/cuckoo#930]
cuckoo2.0's process module is not support to handle the bson file which produced by cuckoo1.0.
so there is any way that can translate the 1.0' bson file to 2.0

**Comment by jbremer** [comment]
A complete rewrite was done with regards to the contents delivered by the old CuckooMon and the new Cuckoo Monitor. I think it may still be possible (if with a few small hacks) to load up older CuckooMon logs in the latest version of Cuckoo, but none of the Cuckoo Signatures will work, etc.
You're probably better off re-analyzing your sample(s) if that's a possibility.

**Comment by xvsfekcn** [comment]
ok,I know this. I will try to translate the bson file when the resultserver receive the event. Thx
