### ISSUE TITLE
Run sample in desired location

### ISSUE THREAD

**Issue by reynas** [cuckoosandbox/cuckoo#931]
Is there any way to drop the malicious sample (.dll, exe, ..) anywhere where we want and then execute it from that location? (via the GUI preferably).

thanks

**Comment by reynas** [comment]
Ok, curdir apparently, can we combine options? because that seems to be failing

**Comment by jbremer** [comment]
What do you mean combine options? Give multiple? If so, yes, e.g., `human=0,curdir=xyz`.
I believe this also works for DLL files, yes.

**Comment by reynas** [comment]
Ok, curdir doesn't need quotes, solved now
