### ISSUE TITLE
SetUnhandledExceptionFilter

### ISSUE THREAD

**Issue by Nadacsc** [cuckoosandbox/cuckoo#932]
When the analysis throw an exception or called the API 'SetUnhandledExceptionFilter' does this mean the analysis is not reliable , or something haven't been set properly ? I have lots of  #executables which, according to the Analysis log everything was ok and completed but when checking their APIs I  can see an exception or SetUnhandledExceptionFilter called and some of them does make lots of actions on the other hand some make minimum actions during the analysis !

**Comment by jbremer** [comment]
This function is usually embedded as standard boilerplate code when compiling an application and from there on ran on startup of said application. It definitely does *not* mean that a sample is not running correctly. For samples that don't run as expected, please feel free to open up separate issues (preferably with as much information as possible / md5 or sha1 hashes / etc). Thanks.

**Comment by jbremer** [comment]
Going to close this issue :-) Please open new issues if you have requests regarding specific samples.
