### ISSUE TITLE
Cuckoo fails to write analysis' cuckoo.log, requires restart to function

### ISSUE THREAD

**Issue by arbor-jjones** [cuckoosandbox/cuckoo#933]
The trigger for this appears to be hitting a certain # of analyses after restart as it seems to take about twice as long to happen when i cut the # of allowed parallel analyses in half. I have been making this happen reliably since updating my local git repo yesterday evening.

Once cuckoo fails to write cuckoo.log, it tries to re-do a new analysis using the same VM and ends up with more than max allowed VMs running and have to stop, restart and have it mark all the previously "running" analyses as failed.

The only things I see in the debug output of cuckoo.py are messages like this:

    2016-05-20 10:09:10,470 [lib.cuckoo.core.resultserver] ERROR: FIXME - exception in resultserver     connection ('192.168.57.218', 49614)
    Traceback (most recent call last):
      File "/data/cuckoo2/lib/cuckoo/core/resultserver.py", line 247, in handle
        for event in self.protocol:
      File "/data/cuckoo2/lib/cuckoo/core/resultserver.py", line 323, in __iter__
        log.debug("File upload request for %s", dump_path)
      File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
        self._log(DEBUG, msg, args, **kwargs)
      File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
        self.handle(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
        self.callHandlers(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
        hdlr.handle(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
        self.emit(record)
      File "/data/cuckoo2/lib/cuckoo/core/log.py", line 41, in emit
        with open(logpath, "a+b") as f:
    IOError: [Errno 2] No such file or directory: '/data/cuckoo2/storage/analyses/339673/cuckoo.log'

I believe this issue may be caused by this commit that added the per analysis cuckoo.log:

https://github.com/cuckoosandbox/cuckoo/compare/f4bdcd301d79...800238b7f71d

**Comment by arbor-jjones** [comment]
This appears to happen when the analysis directory is not created before the cuckoo.log file is attempted to be written to. Unsure exactly under what conditions this occurs - error analysis? loaded system where there is a race condition between log messages and directory creation? - but either checking to make sure the directory is created or simply ignoring the IOError exception appears to have resolved the issue in our internal systems.

**Comment by jbremer** [comment]
Could you try the following patch @arbor-jjones?

```patch
diff --git a/lib/cuckoo/core/log.py b/lib/cuckoo/core/log.py
index 27ed488..b4ccedd 100644
--- a/lib/cuckoo/core/log.py
+++ b/lib/cuckoo/core/log.py
@@ -59,6 +59,10 @@ class ConsoleHandler(logging.StreamHandler):
 
         logging.StreamHandler.emit(self, colored)
 
-def init_task_log(task_id):
+def task_log_start(task_id):
     """Associate a thread with a task."""
     _tasks[thread.get_ident()] = task_id
+
+def task_log_stop(task_id):
+    """Disassociate a thread with a task."""
+    _tasks.pop(thread.get_ident(), None)
diff --git a/lib/cuckoo/core/scheduler.py b/lib/cuckoo/core/scheduler.py
index ef1718f..7cd4260 100644
--- a/lib/cuckoo/core/scheduler.py
+++ b/lib/cuckoo/core/scheduler.py
@@ -19,7 +19,7 @@ from lib.cuckoo.common.objects import File
 from lib.cuckoo.common.utils import create_folder
 from lib.cuckoo.core.database import Database, TASK_COMPLETED, TASK_REPORTED
 from lib.cuckoo.core.guest import GuestManager
-from lib.cuckoo.core.log import init_task_log
+from lib.cuckoo.core.log import task_log_start, task_log_stop
 from lib.cuckoo.core.plugins import list_plugins, RunAuxiliary, RunProcessing
 from lib.cuckoo.core.plugins import RunSignatures, RunReporting
 from lib.cuckoo.core.resultserver import ResultServer
@@ -317,7 +317,7 @@ class AnalysisManager(threading.Thread):
             return False
 
         # Initiates per-task logging.
-        init_task_log(self.task.id)
+        task_log_start(self.task.id)
 
         self.store_task_info()
 
@@ -532,6 +532,7 @@ class AnalysisManager(threading.Thread):
         except:
             log.exception("Failure in AnalysisManager.run")
 
+        task_log_stop(self.task.id)
         active_analysis_count -= 1
 
 class Scheduler(object):
```

**Comment by arbor-jjones** [comment]
Thanks! The patch appears to fix the issues I was seeing - been running without issue for ~ 1hr and it was only taking 5-10 minutes to manifest previously

**Comment by jbremer** [comment]
That's what I thought, thanks :-)

**Comment by jbremer** [comment]
Going to close as resolved for now, please re-open if similar issues occur. Thanks again!

**Comment by jbremer** [comment]
So yeah, internally the `thread.get_ident()` calls `pthread_self()` (on Linux) for which it is documented that a thread ID may be reused. From the manpage; `Thread IDs are guaranteed to be unique only within a process.  A thread ID may be reused after a terminated thread has been joined, or a detached thread has terminated.`
