### ISSUE TITLE
Disable Yara

### ISSUE THREAD

**Issue by lindeberg25** [cuckoosandbox/cuckoo#934]
I'd like to disable Yara in Cuckoo.

I've set this:
memory.conf
[yarascan]
enabled = no
filter = no

processing.conf
[procmemory]

enabled = no

what else can I try ?

Thanks in advance

**Comment by jbremer** [comment]
That sounds about right. What's the issue? :-)

**Comment by lindeberg25** [comment]
Disable Yara in Cuckoo, jbremer.

**Comment by jbremer** [comment]
So it is still enabled? Can you share some more information on that.

**Comment by lindeberg25** [comment]
Yes. It´s still enable.

I'm not using Yara and as I could not turn it off, I´m taking too many errors

I've removed Yara from my Linux. That´s ok now. Cuckoo gives a warning message only. 

thanks

**Comment by jbremer** [comment]
Oke. In the future; without any logs it's rather time consuming for us to determine what you mean with *still enabled*. If you're interested to further pursue this issue, please feel free to re-open it.
For any other questions you can open a new issue etc etc. Thanks again :-)
