### ISSUE TITLE
Pinned Dependency (cryptography) Causes Failed Install on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by fxfitz** [cuckoosandbox/cuckoo#935]
With the latest Ubuntu 16.04 LTS release, a newer version of OpenSSL (OpenSSL 1.0.2g-fips  1 Mar 2016) is included in the distribution.  Cryptography has fixed this dependency integration problem in a later release, however since the current release has `cryptography==1.0` in it's requirements.txt, the install will fail.

I understand the reason behind pinning the dependency, but the cryptography team does a good job of always accounting for these OpenSSL dependency issues.  I recommend either unpinning cryptography, or cut a new release (since master's requirements.txt has a latest version).

Note: For production systems, I usually pull a latest release as opposed to jut pulling from master, which is how I caught this.

Thanks!

**Comment by jbremer** [comment]
Thanks :-) This should have been resolved through https://github.com/cuckoosandbox/cuckoo/commit/a7de49d303926a190981d0a0ae85cdcf959d36b5 https://github.com/cuckoosandbox/cuckoo/commit/d0cb6203c6dcb701dbc7025551051f66ae518753, though. Could you please verify with the latest development version?

**Comment by fxfitz** [comment]
Yup! Pulling down master works fine, it just seems to be the Cuckoo Sandbox 2.0-RC1 (cuckoo-current.tar.gz) from cuckoosandbox.org that seems to have the problem.

Glad you guys have caught it! :-)

**Comment by fxfitz** [comment]
FWIW, this also required the latest version of CFFI.

**Comment by jbremer** [comment]
In the second commit that I linked it was bumped to the latest, thanks for noting though :-)

**Comment by fxfitz** [comment]
Ah yeah, I missed that one; sorry!

Anyway, closing the issue since it looks like ya'll are on top of it. :-)
