### ISSUE TITLE
Guest VM will not close on VMWare Fusion

### ISSUE THREAD

**Issue by eimsand** [cuckoosandbox/cuckoo#937]
Currently using Cuckoo 2.0-rc1 with Windows 7 as the guest VM on a MacOS VMWare Fusion setup.  After completing analysis, the agent appears to just sit idle.  (See attached screen capture of agent window.)

Eventually the default timeout is reached, at which time the VM is closed.

![screen shot 2016-05-27 at 11 23 03 am](https://cloud.githubusercontent.com/assets/6923229/15614278/7b8d7866-23fd-11e6-9a6b-722d0e1a1815.png)

**Comment by eimsand** [comment]
Disclaimer: I am "git" stupid.  I know I should probably submit this code somewhere but I'm not sure where.

I did some digging around and this appears related to case sensitivity.  Adding ".lower()" to line 170 has corrected the problem for VMWare Fusion 8.1.1 on Mac OS 10.11.5.

"return vmx_path.lower() in output.lower()"

**Comment by jbremer** [comment]
Interesting. Given that both macOS and Windows are case-insensitive, this change probably makes sense. Thanks for the hint and sorry for the delay :-)
