### ISSUE TITLE
Cuckoo 1.2 Custom Signature - Not receiving Host from Socket Call

### ISSUE THREAD

**Issue by 100341976** [cuckoosandbox/cuckoo#938]
Here's a custom Signature that's used to extract the host from a socket call:

```
from lib.cuckoo.common.abstracts import Signature

class SocketAPI(Signature):
    name = "socket_api"
    description = "Socket APIs were called."
    severity = 4
    categories = ["network"]
    authors = ["xxx"]
    minimum = "1.2"
    evented = True

    def on_call(self, call, process):
        if call["category"] == "socket":
            self.add_match(process, 'api', call)
    
    def on_complete(self):
        return self.has_matches()
```

When the analysis guest machine's report is returned the information returned by the custom signature appears truncated compared to examination of the PCAP file:

e.g:

Returned from the custom signature:
```
send 	buffer: GET /3/getexe.php?spl=pdf_exp HTTP/1.1 Accept: */* Accept-Encoding: gzip, deflate User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E) Host: murr
socket: 0x00000468 
```

Now notice the Host is:

murr

However the results seen wireshark are:

```
GET /3/getexe.php?spl=pdf_exp HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E)
Host: murrr.net
Connection: Keep-Alive

HTTP/1.1 200 OK
Date: Wed, 01 Jun 2016 20:08:49 GMT
Content-Type: text/html
Content-Length: 258
Server: INetSim HTTP Server
Connection: Close

<html>
  <head>
    <title>INetSim default HTML page</title>
  </head>
  <body>
    <p></p>
    <p align="center">This is the default HTML page for INetSim HTTP server fake mode.</p>
    <p align="center">This file is an HTML document.</p>
  </body>
</html>
```

Why is the final part of the hostname being truncated?

i.e. murrr.net becomes murr?

Any ideas?

Thanks
J

**Comment by 100341976** [comment]
OK, so think I might have figured this out. It looks like Cuckoo will only return around 250 bytes from the send call and if the user agent string is too long as defined by the installed software on the analysis guest it looks like the host name gets truncated.

**Comment by jbremer** [comment]
So that Signature merely looks at the packets that were sent over the wire using the `send()` method. If you want to look into the entire HTTP request and response, you might have more luck with the new `get_net_http_ex()` method.

**Comment by jbremer** [comment]
In addition to my last comment, the `get_net_http_ex()` method yields *full* HTTP requests and responses, naturally including the `Host:` header. Going to close this issue as resolved.
