### ISSUE TITLE
Bug in "generic" Analysis Package prevention script execution

### ISSUE THREAD

**Issue by certau-davidg** [cuckoosandbox/cuckoo#940]
There appears to be a bug in the generic analysis package which is stopping execution of .bat scripts and similar.

I have traced this back to the attempted randomisation of the cmd.exe window title.
Sample execution method using current syntax:
"C:\WINDOWS\system32\cmd.exe" /c start /wait hIUYfBN \<file\>
Results in Error:
```
Feb. 6, 2016, 11:10 a.m.
WriteConsoleW
buffer: The system cannot find the file hIUYfBN.
console_handle: 0x0000000b
success 	1
```

The correct syntax actually has double quotes around the window name:
"C:\WINDOWS\system32\cmd.exe" /c start /wait "hIUYfBN" \<file\>

A temporary fix involves changing:
"[cuckoo/analyzer/windows/modules/packages/generic.py](https://github.com/cuckoosandbox/cuckoo/blob/master/analyzer/windows/modules/packages/generic.py)", Line 28:
`args = ["/c", "start", "/wait", rand_title, path]`
to
`args = ["/c", "start", "/wait", '"'+rand_title+'"', path]`

There is however a minor issue with this as it does result in the window title **\hIUYfBN\** due to the "_encode_args" function found in "[cuckoo/analyzer/windows/lib/api/process.py](https://github.com/cuckoosandbox/cuckoo/blob/master/analyzer/windows/lib/api/process.py)" changing the " to \\\".
Hopefully the team can find a better fix which avoids the encoding issues mentioned above.

**Comment by jbremer** [comment]
Keeping in mind commit https://github.com/cuckoosandbox/cuckoo/commit/05f064435c6e3d2323dfb892c9fc5ec6e8b1f69a the backslash issue has probably been resolved already. I'm going to give the proposed changes a go soon, but unfortunately ran into a different issue.. so give me a few days :-)

**Comment by jbremer** [comment]
Feel free to give it a try, @certau-davidg, although it appears there are some other issues as well when analyzing `cmd.exe`..

**Comment by botherder** [comment]
Can we close this?

**Comment by jbremer** [comment]
Not yet, `cmd.exe` is crashing during the analysis for some reason.

**Comment by jbremer** [comment]
The issues present here have been resolved, closing it.
