### ISSUE TITLE
Unencoded signature name leads to failing to drill down mark_ioc items in report

### ISSUE THREAD

**Issue by jpeanut** [cuckoosandbox/cuckoo#947]
Please reference the source code of the report below,  the unencoded space in the anchor may cause the problem. Even there are mark_ioc details in the source code, when I click on the signature, the mark items will not show on the html browser

<a style="text-decoration: none;" href="#**signature_test API CALL**" data-toggle="collapse">  
            <div class="alert alert-danger signature">The api calls made by the sample(30 out of 30 events)</div>
</a>

<div id="signature_test API CALL" class="collapse">
<table class="table table-bordered" style="table-layout: fixed;">

```
                <tr>
                    <td colspan="1">apicall</td>
                    <td colspan="4">NtOpenSection</td>
                </tr>

                <tr>
                    <td colspan="1">apicall</td>
                    <td colspan="4">NtDelayExecution</td>
                </tr>
```

**Comment by jbremer** [comment]
For which Signature does this issue trigger? Also, based on the `30 out of 30 events` I think you're running an outdated version of Cuckoo (see also commit e0e7efd0588581bff0a20a0e34c7115b3cac1d40).

**Comment by jbremer** [comment]
Any update on this issue @jpeanut?

**Comment by jbremer** [comment]
I guess we can close this issue. Please reopen if that's not the case.
