### ISSUE TITLE
Whitelisting URL`s not working

### ISSUE THREAD

**Issue by donatasiv** [cuckoosandbox/cuckoo#948]
Hi folks,

I wanted to whitelist some url in report, because a lot of url entries generates MS Office (when inspecting .doc files) which are actually not relevant or malicious. What I did:
1. updated cuckoo_root/data/whitelist/domain.txt file whit urls`s I dont want to see in report.
2. updated processing.conf
    [network]
    enabled = yes
    dnswhitelist = yes

But nothing happens. Anything I`m missing?

**Comment by jbremer** [comment]
This is currently not yet a feature, hopefully to be fully implemented *soon*'ish. If you'd be up for creating a pull request on this topic, that'd be great of course.

**Comment by razuz** [comment]
so that should be resolved by #1094

**Comment by jbremer** [comment]
Closing as resolved for reasons described above by @razuz.
