### ISSUE TITLE
I created a new signature: how to request a pull?

### ISSUE THREAD

**Issue by bit111** [cuckoosandbox/cuckoo#952]
Hi,
I created a new signature to detect informations stolen from some viruses.
How can I add my signature to cuckoo project?
Thanks,
B.

**Comment by jbremer** [comment]
You can do a pull request for those Signatures on the `community` repository, https://github.com/cuckoosandbox/community. I guess the easiest is if you're logged into Github by clicking on the `create file` button on the Github UI.. and then doing a pull request.

**Comment by jbremer** [comment]
Going to close this issue as resolved by the answer above.

**Comment by bit111** [comment]
Hi @jbremer,
I did a pull request but I don't know if the way is correct.

**Comment by jbremer** [comment]
@bit111 See my comment above ;-)

**Comment by bit111** [comment]
Sorry, I misread XD
So, this file (a signaure) will be added to cuckoo package or it will remain in a seperated package?
Thanks

**Comment by jbremer** [comment]
No, it will be added to the Cuckoo Community repository ;-)

**Comment by bit111** [comment]
Hi @jbremer, sorry for my care, but how many days are needed for a pulled file to be accepted?
Thanks
