### ISSUE TITLE
Why cuckoo uses only one CPU at a time why not all assigned cores.

### ISSUE THREAD

**Issue by masifpak** [cuckoosandbox/cuckoo#954]
I am running cuckoo-modified on a VM assigned one virtual socket with 4 cores. But it is observer cuckoo only uses one core at a time even when one core reached at 100%. More over when cuckoo reach its maximum resources , analysis machine stand on waiting for connection after acquiring for analysis for hours. is there any way of timeout from starting the analysis of a VM. I know default timeout and critical . but i dont know VM remain on for hours.

**Comment by jbremer** [comment]
Can you share your configuration?

**Comment by jbremer** [comment]
Well, first of all you're using cuckoo-modified. Secondly your network configuration is probably incorrect.
Please read through closed github issues to see how people resolved those issues. One day we'll write some documentation on helping out with all of that :)

**Comment by jbremer** [comment]
Closing this issue for lack of feedback etc.
