### ISSUE TITLE
hardcoding addresses of mshtml! and ncrypt functions

### ISSUE THREAD

**Issue by ChriDr** [cuckoosandbox/cuckoo#955]
Hi,

since the following commit [1] I get the following error when the monitor.dll is resolving function from 
javascript.

[analyzer] DEBUG: Error resolving function mshtml!CDocument_write through our custom callback.\n", 
[analyzer] WARNING: Unable to find the correct offsets for functions of: mshtml.dll (with timestamp 0x4ce7b8f3)\n", 
[analyzer] WARNING: Unable to find the correct offsets for functions of: mshtml.dll (with timestamp 0x4ce7b8f3)\n", 
[analyzer] DEBUG: Error resolving function mshtml!CIFrameElement_CreateElement through our custom callback.\n", 
[analyzer] WARNING: Unable to find the correct offsets for functions of: mshtml.dll (with timestamp 0x4ce7b8f3)\n", 
[analyzer] DEBUG: Error resolving function mshtml!CImgElement_put_src through our custom callback.\n", 
[analyzer] WARNING: Unable to find the correct offsets for functions of: mshtml.dll (with timestamp 0x4ce7b8f3)\n", 
[analyzer] DEBUG: Error resolving function mshtml!CScriptElement_put_src through our custom callback.\n"

Also the resolving of the ncrypt function does not work anymore for me.

I assume at the moment the function offsets are only for the 64 Bit version of Windows 7, right? 
For this reason could you please also add the correct function offsets for Windows 7 32 Bit SP1 especially the Internet Explorer 8. 

[1] https://github.com/cuckoosandbox/monitor/commit/dbf1c3a938c1be68815d1ec5625e2c0e99c3b9bf

Thank you in advance

**Comment by jbremer** [comment]
Ah, I see, that used to work for 32-bit as well.. I'm all up for adding offsets for different versions, but the biggest issue there is the fact that it takes me quite a bit of time to figure out the correct offsets in some cases. For the TLS hooks that's not too big of an issue, but for IE8..

**Comment by ChriDr** [comment]
Let me know if I can help. Do you need any logs etc? 
Which version of IE8 should I then use?

**Comment by jbremer** [comment]
I was planning to add the supported versions (right now just one as you can see) to the documentation. This is 64-bit IE8 `8.0.7601.17514` it would appear.

**Comment by ChriDr** [comment]
Hi Jurriaan,

thank you for your quick reply! 
I've checked my version mentime and I'am using the exactly mentioned version from you except it is Windows 7 32 Bit. Please see the attached image. Does it only work for the 64 Bit version of Windows 7?

![scree](https://cloud.githubusercontent.com/assets/6873184/15999063/3dc47342-3143-11e6-800a-b2a13dd3bca4.png)

Best regards,

**Comment by jbremer** [comment]
Yep, currently only 64-bit, which I'd definitely suggest using anyway (I mean, 64-bit Windows 7) ;-)

**Comment by jbremer** [comment]
This should've been resolved in https://github.com/cuckoosandbox/monitor/commit/9b479cb67721f3a0c9980af22ba5f2a308eb7808, could you please give it a try?

**Comment by ChriDr** [comment]
Hi Jurriaa,

yes, it seems to work. But I think there is a new problem with the Monitor dll for the 64bit analyses. Last week, I compiled the Monitor after I had freshly cloned the repositorie with the current state. Then, when I started an analysis within the Internet Explorer ( with the new dll files) especially on a x64 Host, the Internet Explorer crashed. Unfortunately I am now on the road  and therefore I cannot provide you with these log files. Maybe you can take a look :). 

Best regards,

**Comment by ChriDr** [comment]
And of course a big Thanks!!!

**Comment by botherder** [comment]
Closing as it seems resolved. Thank you.
