### ISSUE TITLE
Error while launching Cuckoo in Windows 7

### ISSUE THREAD

**Issue by PReeeT** [cuckoosandbox/cuckoo#962]
I am trying to setup cuckoosandbox in Windows 7. I have resolved the dependencies, but when I run cuckoo.py it shows an error 
`VirtualBox VBoxManage not found at specified path "/usr/bin/VBoxManage". `
This path is true for Linux machine. Could you please help me understand how do I set this right for Windows 7.

**Comment by jbremer** [comment]
Update it in `conf/virtualbox.conf` as specified in the documentation..

**Comment by jbremer** [comment]
Going to close this issue as resolved.
