### ISSUE TITLE
"Too many open files". Due to a specific sample.

### ISSUE THREAD

**Issue by danielgindi** [cuckoosandbox/cuckoo#966]
Sending this for analysis on an XP Pro SP3 x86  - Causes the host Ubuntu to go haywire.

[e42b6a8d215f0fafd7ae39ecfa59ca4fe3fa3d2337b5abd9e4269b19728b8eb6_e42b6a8d215f0fafd7ae39ecfa59ca4fe3fa3d2337b5abd9e4269b19728b8eb6.zip](https://github.com/cuckoosandbox/cuckoo/files/322342/e42b6a8d215f0fafd7ae39ecfa59ca4fe3fa3d2337b5abd9e4269b19728b8eb6_e42b6a8d215f0fafd7ae39ecfa59ca4fe3fa3d2337b5abd9e4269b19728b8eb6.zip)

Many like these are showing up: (Many = Hundreds or maybe thousands)

```
Exception happened during processing of request from ('192.168.56.105', 1986)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
  File "/media/user/Storage/cuckoo-trunk/lib/cuckoo/core/resultserver.py", line 270, in handle
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
  File "/media/user/Storage/cuckoo-trunk/lib/cuckoo/core/log.py", line 41, in emit
IOError: [Errno 24] Too many open files: '/media/user/Storage/cuckoo-trunk/storage/analyses/2829/cuckoo.log'
----------------------------------------
2016-06-19 17:41:33,470 [lib.cuckoo.core.resultserver] ERROR: FIXME - exception in resultserver connection ('192.168.56.105', 1987)
Traceback (most recent call last):
  File "/media/user/Storage/cuckoo-trunk/lib/cuckoo/core/resultserver.py", line 257, in handle
  File "/media/user/Storage/cuckoo-trunk/lib/cuckoo/core/resultserver.py", line 374, in __iter__
IOError: [Errno 24] Too many open files: '/media/user/Storage/cuckoo-trunk/storage/analyses/2829/files/df4d82ea54b075ba_e42b6a8d215f0fafd7ae39ecfa59ca4fe3fa3d2337b5abd9e4269b19728b8eb6mgr.exe'
```

And after cuckoo finally crashes - The host cannot operate properly. Anything you do on the OS results in a "Too many open files" error. Even after force-killing all python processes...

That's a weird one! :-)

**Comment by danielgindi** [comment]
```
ulimit -Hn   # 4096
ulimit -Sn   # 1024
```

Creating 3,000 bson files - going over the limit... And then somehow the resources are not being freed. Damn python.

**Comment by danielgindi** [comment]
More info:

I have observed count of open files of current user while running that task,
And it seems like after finishing a task successfully with a high `ulimit` - it cleans 100% of the open files. But when the limit is low (default) and it crossed the limit - Cuckoo crashes and the resources are not getting freed. And a system restart is mandatory.

Anyone knows anything about this?
Is this a kernel bug, or a python bug?

**Comment by jbremer** [comment]
Python - and any other application - are limited by the amount of file descriptors that can be opened at any time. By default this is 1024 or something like that. Now if you have a malware that requires more than that amount of files - due to whatever reason - then.. it's basically difficult to properly mitigate for us.
The easiest is indeed simply bumping the `ulimit` thing as you've already done.

**Comment by jbremer** [comment]
https://github.com/cuckoosandbox/cuckoo/blob/master/utils/service.sh#L68-L69 because why not ;-)

**Comment by jbremer** [comment]
I've documented the issue and its workaround in our installation guide, https://cuckoo.sh/docs/installation/host/installation.html#raising-file-limits, as well as the FAQ, https://cuckoo.sh/docs/faq/index.html#openfiles24.
I'm not sure if there's anything else we can do from a Cuckoo perspective at this point.
Do you have any ideas @danielgindi?

**Comment by danielgindi** [comment]
Well, maybe we should avoid opening that many files at once :-)

**Comment by danielgindi** [comment]
If, for example, cuckoo wants to pick up dropped files from the guest, and there are thousands of them - I would stream them into a zip file, or a simple archive file.

**Comment by jbremer** [comment]
That is worth a try, but definitely not backwards compatible. Maybe we can pull that off later on. Thanks for the suggestion though.

**Comment by consen** [comment]
Maybe we can use threadpool for resultserver, I have opened a new pull request #1169

**Comment by danielgindi** [comment]
It's not about how many files you process, but how many processes are open inside the vm. Because each of them open a file on your machine. It can be looked at as an attack against cuckoo based machines.

**Comment by reox** [comment]
@danielgindi Does any virtualziation really open a filehandle for each opened file in the VM?
I just tested that by opening 5k handles in a Windows VM which runs via libvirt/kvm but I could not see more handles in the linux host.

**Comment by danielgindi** [comment]
It’s not the virtualization technology,
It’s the Cuckoo server, that receives a pipe of events for each (monitored) process id.
For each one- it opens a file, and pipes the data into it.
After all is done, there’s post processing from those files into one report,
At least that’s how it worked the last time I used Cuckoo.

Now we encountered some samples that attacked the machine by creating thousands of processes, which resulted in thousands of pid files open on the server.
If you have like 5-10 vms, and all of them happen to run such a sample at the same time- you hit the limit on the server.

**Comment by reox** [comment]
Ah sorry, I misunderstood you.
So a fix would be to limit the number of processes in the VM - but it looks like Windows does not support such limits and process creation is basically just limited by the amount of memory you have? See: https://blogs.technet.microsoft.com/markrussinovich/2009/07/05/pushing-the-limits-of-windows-processes-and-threads/

**Comment by danielgindi** [comment]
Yeah. It's great that windows don't have such limits. It's amusing the linux does. It shouldn't...
A fix is far from what you are suggesting.
A fix would be to stream the data to a different target. Instead of opening a file for each process - maybe preallocating chunks on the disk, and rebalancing as they get bigger, or maybe using a database.

**Comment by doomedraven** [comment]
@jbremer  probably can be closed due to old + gevents solution
