### ISSUE TITLE
Submitted files not actually being executed

### ISSUE THREAD

**Issue by jfo4gs** [cuckoosandbox/cuckoo#967]
I've set up Cuckoo on CentOS 7. All dependencies and requirements installed fine, virtual network is able to ping in and out of the guest/host, all seems well.

When I go to submit a file though, the agent.py on the guest machine only shows POST's every second and the file I submitted isn't actually run. I'm running in gui mode to watch the file's actions and nothing is opened or run in anyway. It doesn't even say "Analysis package ... chosen" or anything. The machine just sits there POST'ing every second.

I'm at a dead-end as to where to look for this, any thoughts?

**Comment by jfo4gs** [comment]
Nevermind. I thought the issue had to do with the agent.py file, but it actually stemmed from CentOS, nothing related to Cuckoo.

For anybody who stumbles on this later: CentOS 7's default firewall places vboxnet0 in the public Zone which I believe was blocking it from transferring files to the guest. Moving it to trusted solved the issue for me.

**Comment by jbremer** [comment]
Feel free to do a pull request to include this information in our documentation. Closing this issue :-)
Thanks again!
