### ISSUE TITLE
[usage] doing dynamic analysis for malware without the form of exe?

### ISSUE THREAD

**Issue by naijim** [cuckoosandbox/cuckoo#969]
I got some super old malware without the form of exe. The malware spreads with malicious HTTP request. It is possible to do dynamic analysis with Cuckoo? Cuckoo only accepts submit of malware with the form of executable, right?

**Comment by doomedraven** [comment]
no, check packages selection

**Comment by naijim** [comment]
Thx. I will seek other ways to do that.
