### ISSUE TITLE
Failed to run the reporting module "MongoDB": report["debug"]["cuckoo"] 

### ISSUE THREAD

**Issue by TiTi87** [cuckoosandbox/cuckoo#971]
Hello,

I've ran into a strange error this morning: 
```
2016-06-23 10:48:21,773 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/user/cuckoo-dev/lib/cuckoo/core/plugins.py", line 533, in process
    current.run(self.results)
  File "/home/user/cuckoo-dev/modules/reporting/mongodb.py", line 114, in run
    report["debug"]["cuckoo"] = list(report["debug"]["cuckoo"])
KeyError: 'debug'
```
The error only occurs if option `procmemdump=yes` is specified.
![procmemdump](https://cloud.githubusercontent.com/assets/17823045/16299632/91e6248e-393b-11e6-87b0-873942a58f1b.png)
If set to no (or not specified) no issue.

JSON report module works on this task : so, i'm guessing process memory dumps works, it's reporting that into MongoDB that seems to crash.
It's not a systematic one, it occurs on some malware and works as expected on others. 

Running on a up to date, Cuckoo-dev.

Thanks in advance

**Comment by jbremer** [comment]
Did you disable `debug` in `processing.conf`?

**Comment by jbremer** [comment]
Tested the commit as working, so closing this issue as resolved - thanks again!

**Comment by TiTi87** [comment]
Debug was enabled.
I pulled the last update this morning, then resubmit the analysis : it's working now.

Thanks for your help !
