### ISSUE TITLE
Analysis report error

### ISSUE THREAD

**Issue by adimenia** [cuckoosandbox/cuckoo#973]
Hello

i had a power breakout and after i restarted my machine all of my analysis reports are not avaliable.
here is the debug info
Environment:

Request Method: GET
Request URL: http://x.x.x.x/analysis/8/

Django Version: 1.9.4
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'analysis',
 'compare',
 'api',
 'ratelimit')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'web.headers.CuckooHeaders',
 'ratelimit.middleware.RatelimitMiddleware')

Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
1.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py" in inner
1.             return func(request, _args, *_kwargs)

File "/opt/cuckoo/web/analysis/views.py" in report
1.                  )["hits"]["hits"][0]

Exception Type: IndexError at /analysis/8/
Exception Value: list index out of range

**Comment by jbremer** [comment]
And you're running cuckoo-modified?

**Comment by jbremer** [comment]
Closing as this setup is unrelated to upstream Cuckoo.
