### ISSUE TITLE
Issue with Network Separation

### ISSUE THREAD

**Issue by Sanghyun-Hong** [cuckoosandbox/cuckoo#977]
Hi,

I've been testing Cuckoo with benign files, however, I have an issue before run the REAL malware on Cuckoo environment. Some malware try to connect them to the other network to launch an attack, so I wonder if we can block the network of the VM before starting analysis. According to the documentation ([here](http://docs.cuckoosandbox.org/en/latest/installation/guest_physical/network/)), we can set the network settings of vm as static, however, I wonder if malware can set this to DHCP and break out from my farm.

Thanks,
Sanghyun.

**Comment by seifreed** [comment]
Hi,

Doing good practices, you need to configure your lab/malware environment separately from your real environment.

You can create internal networks and gateways through different machines, so apparently any malware can’t jump and infect you

Regards,
--
Marc Rivero López | @seifreed | www.ecrime.info <http://www.ecrime.info/>

**Comment by Sanghyun-Hong** [comment]
@seifreed, thanks for your comment. I'm only using one pc installed a hypervisor and one virtual machine. Does 'create internal networks and gateways' approach can be configured in this case?

**Comment by botherder** [comment]
I would recommend using a host-only network, and then figure where you want to route the traffic.

**Comment by Sanghyun-Hong** [comment]
@botherder, @seifreed, thanks for the answers. It seems like the Linux configuration issues, not the Cuckoo issue.
