### ISSUE TITLE
Please Help: How to perform analysis on software with GUI  (requiring user interaction)

### ISSUE THREAD

**Issue by cssanchit** [cuckoosandbox/cuckoo#980]
I wish to interact with software in virtual machine. Right now I am unable to perform user interaction. Please help me in this regard.

**Comment by seifreed** [comment]
Hi,

You can do this in two ways:
Activate guy mode in the cuckoo cons

An example to Virtualbox



Create a plugin for cuckoo for interact with the machine (move the mouse, click on the dialog boxes)

Regards,
--
Marc Rivero López | @seifreed | www.ecrime.info <http://www.ecrime.info/>

**Comment by cssanchit** [comment]
Thank you

**Comment by cssanchit** [comment]
Thank you for prompt reply. I enabled GUI mode in virtual box conf. I am able to give input as mouse click but still I can not select combo boxes .  they resets  to original state every time  when I try to select anything  (may be due to screenshot activity). Can you help me in this regard.

**Comment by seifreed** [comment]
Hi,

Check you cuckoo conf and installation, If you enable the gui mode, you are able to full interact with the VM. Check with different samples etc..

Regards,
--
Marc Rivero López | @seifreed | www.ecrime.info <http://www.ecrime.info/>

**Comment by cssanchit** [comment]
Thanks .. I tried 2-3 samples and even disabled screenshot activity. Problem is that my main program windows is losing focus frequently and automatically. Before i try to select anything from combo box , it looses focus and when i click it again it come to original position . for example for simple calc.exe i am not able to select scientific calculator mode.

**Comment by doomedraven** [comment]
check ooption, you not disabling automatic interaciton when uploading task

**Comment by cssanchit** [comment]
Thanks doomedraven for replying. I am not able to find such setting in configuration of cuckoo. Please tell me where it is.

**Comment by doomedraven** [comment]
* see one selected checkbox
<img width="772" alt="screen shot 2016-06-29 at 10 31 55" src="https://cloud.githubusercontent.com/assets/1856495/16445819/be6633f2-3de4-11e6-8687-34ddc7879c34.png">

**Comment by cssanchit** [comment]
![screenshot from 2016-06-29 14-10-28](https://cloud.githubusercontent.com/assets/20201027/16446042/47d10b80-3e03-11e6-9825-8bf09efc3f64.png)

**Comment by doomedraven** [comment]
1 looks like you using cuckoo-mod, not upstream cuckoo
2 Disable automated interaction your option in cuckoo mod

**Comment by RedWolf74** [comment]
@doomedraven cssanchit's screenshot looks like the offical RC-1 where this option does not exist, your screenshot seems to be from a dev-version

**Comment by doomedraven** [comment]
dev one has a lot of bug fixes from rc1

**Comment by cssanchit** [comment]
I am using Cuckoo Sandbox 2.0-rc1. When I click on GUI of application it looses focus in 1-2 seconds and it keeps on repeating. Still not able to find a solution to it..

**Comment by cssanchit** [comment]
Solved it using utils/submit.py --options # human=0 calc.exe
Thanks all
