### ISSUE TITLE
Erroneous Virtual Machine /status failed messages during analysis run

### ISSUE THREAD

**Issue by baufrecht** [cuckoosandbox/cuckoo#981]
Hi, 

when running the latest cuckoo-dev from git. (last commit: 8a6760dad6063812c523bd2f51820593b7e3da5e)  I get the following misleading log message during analysis:

`[lib.cuckoo.core.guest] INFO: Virtual Machine /status failed (ConnectionError(ProtocolError('Connection aborted.', BadStatusLine("''",)),))`

According to the pcap there is one /status API call send out that didn't get any response. 
(I used the  sniffer.debug=1 option to make the API calls visible)

Failed request

```
GET /status HTTP/1.1
Host: 192.168.56.80:8000
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-86-generic
```

Working request

```
GET /status HTTP/1.1
Host: 192.168.56.80:8000
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-86-generic

HTTP/1.0 200 OK
Server: Cuckoo Agent Python/2.7.6
Date: Tue, 28 Jun 2016 14:28:02 GMT

{"status": null, "message": "Analysis status", "description": null}
```

Subsequent /status API calls work again and the analysis is also finished successfully.

Full analysis log is attached.
[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/338885/cuckoo.txt)

The issue can be reproduced with multiple samples. Unfortunately I can't attach a pcap here.

**Comment by botherder** [comment]
It might be worth to suppress that line or turn into a debugging log instead.

**Comment by jbremer** [comment]
Going to assume this issue is no longer relevant, sorry for not replying back then. If this issue is still occurring for you, please reopen or create a new issue. Also don't forget to upgrade etc :-)
