### ISSUE TITLE
Cuckoo Guest cannot handle sample names carrying a pipe character

### ISSUE THREAD

**Issue by remi-armature** [cuckoosandbox/cuckoo#983]
When a sample filename contains a pipe character ("|"), the Guest hangs and never proceeds to the analysis.

**Comment by jbremer** [comment]
Do you have any scenarios where this might be an actual problem? :-)

**Comment by jbremer** [comment]
Or I meant to ask - is this something that is currently being used in-the-wild?

**Comment by remi-armature** [comment]
Not yet. Random finding :)

**Comment by botherder** [comment]
The pipe character isn't even a valid character on Windows, so I doubt it would be a real problem (and it's likely what's causing the guest to hang).
