### ISSUE TITLE
agent.py can be abused for ending analysis through XMLRPC method (Agent.complete())

### ISSUE THREAD

**Issue by remi-armature** [cuckoosandbox/cuckoo#985]
As introduced in #984 a malware sample can proceed to XMLRPC calls for illegitimately call methods.
Calling Agent.complete() leads to ending the analysis and kind of forces the Supervisor into believing the analysis is clean (& complete).

**Comment by botherder** [comment]
Yup. You can also call `TerminateProcess()` and actually terminate the analysis.
