### ISSUE TITLE
XenServer Machinery Memory Dump Functionality

### ISSUE THREAD

**Issue by Sanghyun-Hong** [cuckoosandbox/cuckoo#986]
Hi,

I would like to verify if it's right that we cannot use memory dump functionality with XenServer environment. I enabled all the configuration related to the memory dump and try memory dump, however,  Cuckoo showed the error message "Memory dump functionality does not support ....". (With KVM, we can use it.)

Thanks,
Sanghyun.

**Comment by jbremer** [comment]
I guess if that's what the error message says.. :-)
Little bit late to the party, but surely @KillerInstinct can answer this.

**Comment by jbremer** [comment]
I think we can close this issue now.. if you're still interested in the answer, feel free to reopen or create a new issue.
