### ISSUE TITLE
wkhtmltopdf - converting cuckoo html reports to pdf

### ISSUE THREAD

**Issue by nobbyhegel** [cuckoosandbox/cuckoo#992]
I'm just wondering if anybody else has had a similar issue with using wkhtmltopdf as part of the html reporting module in Cuckoo. The cuckoo html report output seems to have an issue and is giving the same error each time 
"The reporting module "ReportHTML" returned the following error: Failed to generate PDF report: 'ascii' codec can't decode byte 0xc2 in position 1237702: ordinal not in range"

T

**Comment by jbremer** [comment]
The `HTML` report is quite outdated at the moment. It's therefore also missing quite some information.
There are plans to update it in the near future, but as of now it's definitely incomplete and thus it's not necessarily the best idea to use it.

**Comment by nobbyhegel** [comment]
Thanks for the prompt response! Do you have any suggestions as to how best to convert the reports from cuckoo to a pdf version?

**Comment by jbremer** [comment]
As-is not really.. needs some development work to properly export all the latest information in a nice way to a PDF.

**Comment by botherder** [comment]
Opened a dedicated ticket. Closing this one.
