### ISSUE TITLE
Uploading ZIP files

### ISSUE THREAD

**Issue by satmit** [cuckoosandbox/cuckoo#996]
Hi,

I want to upload zip file which contains more than 2 files. Once I upload the zip file, it should unzip the files and need to analyze one by one in Cuckoo.

Kindly help to implement this feature. Thanks in Advance.

Regards,
Satheesh

**Comment by botherder** [comment]
Currently, you can't do this within Cuckoo. You would have to create a script that does that for you and submit the files individually.
We could also extend submit.py to do that perhaps.

**Comment by jbremer** [comment]
We're currently working hard on this and it will therefore be available soon'ish. Thanks for the request.

**Comment by satmit** [comment]
@jbremer: we have completed the unzipping task. Will upload the code shortly.

Thanks for your interest.!

**Comment by jbremer** [comment]
Due to receiving no further feedback and this now being a feature that we're shipping by default (in #863), I'm going to close this issue. Thanks for the request @satmit.
