### ISSUE TITLE
Service written not detected

### ISSUE THREAD

**Issue by Tigzy** [cuckoosandbox/cuckoo#998]
Hello, 
I'm facing a malware that installs a service, but Cuckoo didn't log the activity.
Is it possible that such keys are not monitored?

**HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\services\d880cee2f707c6f3ad5c5aed055afc83**

**Comment by jbremer** [comment]
There is no special handling for specific registry keys, so no, that shouldn't happen.
Do you have a sample hash for me?

**Comment by jbremer** [comment]
@Tigzy Any update by any chance?

**Comment by jbremer** [comment]
Closing as issue has expired (no hash).
